### ISSUE TITLE
`break-words` class might need to include `word-break: break-word`

### ISSUE THREAD

**Issue by LeptoFlare** [tailwindlabs/tailwindcss#10004]
**What version of Tailwind CSS are you using?** `v3.2.4`
**What build tool (or framework if it abstracts the build tool) are you using?** `Gatsby v5.2.0`
**What version of Node.js are you using?** `18`
**What browser are you using?** `Firefox`
**What operating system are you using?** `Windows`

**Reproduction URL**

https://play.tailwindcss.com/OVE2UF43o2

**Describe your issue**

I state "might" because this might be a browser bug, or another class that I should add, apologies if this is the case.
- The `flex` class is *required* on the parent for this to occur, if I remove that, both results become identical.
- Adding `flex-col` *also* causes both results to become identical, which is a bit odd to me.

Here is what it looks like on my screen:
![image](https://user-images.githubusercontent.com/47790183/205520340-1ab51c06-a29d-47a2-a669-950695d770f0.png)

I found it odd that in the docs the `break-words` class uses `overflow-wrap` exclusively, while all of the other classes at least include `word-break`.
![image](https://user-images.githubusercontent.com/47790183/205520420-52ed056b-8473-45f7-b9ab-5e6749a59b01.png)

Perhaps all of those classes should include both `overflow-wrap` and `word-break`.

**Comment by tonyxiao** [comment]
<img width="1122" alt="CleanShot 2023-05-26 at 16 58 35@2x" src="https://github.com/tailwindlabs/tailwindcss/assets/696842/f3165de3-fd06-4213-b5c8-90dbbe333f47">

It seems that `min-w-0` doesn't fix it in all situations. I'm using shadcn/ui `AlertDialogTitle` component and this is what I'm getting when having a long title. `overflow-wrap: anywhere` fixes fwiw

**Comment by serkodev** [comment]
https://github.com/tailwindlabs/tailwindcss/discussions/12127 Created a related research and disscustion for this issue.
