### ISSUE TITLE
`space` and `divideWidth` add space/dividers around some hidden elements

### ISSUE THREAD

**Issue by olets** [tailwindlabs/tailwindcss#10015]
**What version of Tailwind CSS are you using?**

For example: v3.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**

play

**What version of Node.js are you using?**

play

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/tJmnZzZEcu

**Describe your issue**

`space` and `divideWidth` don't reliably "ignore" `.sr-only` and `.hidden` elements. Their selectors only know about `[hidden]`, not other ways to hiding.

I'm currently using an override which replaces the `:not()`s with `:not(:where())`s to add additional "not"s. If that sounds like a good change I'm happy to open a PR. Strictly speaking it would be a breaking change.

**Comment by adamwathan** [comment]
Hey! This is by design, it’s just not really realistic to be able to detect when an element is hidden or not especially when you take into account breakpoints or other conditional modifiers.

Check here to find some previous discussions:

https://github.com/tailwindlabs/tailwindcss/issues/3857

**Comment by olets** [comment]
Got it. How'd I miss those? `flex gap-…` here I come 👍
