### ISSUE TITLE
Reversed order when using numbers as breakpoints

### ISSUE THREAD

**Issue by NeleDeBruycker** [tailwindlabs/tailwindcss#10092]
### Describe the bug 
I'm working in a digital product design studio in Ghent, Belgium and we recently made the step to start using Tailwind in our setups. We are used to working with numbers as breakpoints as you can see in the screenshot below and we would like to keep using this as it's easier when there is a need to add an extra breakpoint. 

![Screenshot breakpoints](https://user-images.githubusercontent.com/69677343/207865029-2b4f5a0e-4227-4ab6-8f0b-1d3229d633b3.png)

We wrote some custom plugins to be able to define text styles like for example h1, in this way we can use typo-h1 which sets the right properties for font-family, font-size, line-height, etc. We also made them responsive. 
By using numbers as breakpoints in the config file, we noticed that Tailwind puts the media queries defined in the tailwind config at the top which results in media queries being set before the default values. (see screenshots below - 1. tailwind config file - 2. console log of the config file in a custom plugin function)

![tailwind config](https://user-images.githubusercontent.com/69677343/207866172-1acce28d-c444-4517-8fc5-9aa0e62fbbc8.png)

![console log tailwind config](https://user-images.githubusercontent.com/69677343/207866187-acee24c5-59a8-4a9f-8e00-1490c1cca27b.png)

### Reproduction
1. Use numbers as screen sizes
2. Add an object in the tailwind config file, using a number
3. Make a custom plugin file where you can log the config

### Expected behavior
The order defined in the config file is respected and not ordered automatically. 

### Platform and versions
Tailwind 3.1.8
Using webpack mix in a Craft CMS setup

### Additional context
Example of what we set for the typography styles
```
theme: {
   screens: {
	  3: em("375px"),
	  5: em("568px"),
	  6: em("640px"),
	  7: em("768px"),
	  9: em("992px"),
	  10: em("1024px"),
	  12: em("1280px"),
	  15: em("1536px"),
  },
    fontStyles: ({ theme }) => ({
	    h1: {
		    "font-family": theme("fontFamily.primary"),
		    "font-size": 42px,
		    "line-height": "normal",
		    "font-weight": theme("fontWeight.medium"),
		    7: {
			    "font-size": rem("64px"),
		    },
	    },
    })
}
```

Code structure in the plugin:
```
const plugin = require("tailwindcss/plugin");
module.exports = plugin(({ matchUtilities, theme }) => {
	matchUtilities(
		{
			typo: (config) => {
				console.log(config);
		},
		{
			values: theme("fontStyles"),
		}
	);
});
```

**Comment by thecrypticace** [comment]
Hey! The behavior you are seeing is native to Javascript itself. Numeric-like keys in an object are always ordered first in ascending order regardless if they are specified as a number or a string):
```js
let foo = { 'font-family': 'test', 9: { 'font-family': 'test2' } }

console.log(foo)
// {9: {…}, font-family: 'test'}

console.log(JSON.stringify(foo))
// {"9":{"font-family":"test2"},"font-family":"test"}
```

If you want to change this behavior you'll need to prefix the numbers with something like `m` so you can keep the numeric scale but bypass the sorting nature of object keys:
```js
let foo = { 'font-family': 'test', m9: { 'font-family': 'test2' } }

console.log(foo)
// {font-family: 'test', m9: {…}}

console.log(JSON.stringify(foo))
// {"font-family":"test","m9":{"font-family":"test2"}}
```
