### ISSUE TITLE
Trouble building the next web application because of `Fixed-range breakpoints`

### ISSUE THREAD

**Issue by ynifamily3** [tailwindlabs/tailwindcss#10126]
**What version of Tailwind CSS are you using?**

`v3.2.4`

**What build tool (or framework if it abstracts the build tool) are you using?**

`postcss 8.4.20, Next.js 13.0.7`

**What version of Node.js are you using?**

`v16.14.0`

**What browser are you using?**

`browser independent`

**What operating system are you using?**

`Windows 10 (wsl2)`

**Reproduction URL**

<https://play.tailwindcss.com/jYjWUkCEGc?file=config>

**Describe your issue**

`error - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[11].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[11].use[2]!./styles/globals.css
TypeError: value.match is not a function`

In playtailwindcss:
![image](https://user-images.githubusercontent.com/13795765/208615738-fa8a1c09-14e1-4f97-a36d-8e3744f3b2ce.png)

**Comment by ynifamily3** [comment]
Older versions of tailwindcss supported numbers, but now I see that they only work with strings.
`
      xxs: { min: "0px", max: "360px" },
`

**Comment by adamwathan** [comment]
Hey! Yep this should be a string, probably worked in the past because was getting lucky with number to string casting. Going to close though as this seems to be working as intended 👍
