### ISSUE TITLE
`prefix` option + `modifier` + `arbitrary variant`: extra prefix is generated for classes inside variant

### ISSUE THREAD

**Issue by jhcarl0814** [tailwindlabs/tailwindcss#10125]
`prefix: "tw-",` + `hover:[&.header-is-scrolled_.menu-list_a]:tw-text-[#FF0000]`
generates:
```CSS
.hover\:\[\&\.header-is-scrolled_\.menu-list_a\]\:tw-text-\[\#FF0000\].tw-header-is-scrolled .tw-menu-list a:hover {
  --tw-text-opacity: 1;
  color: rgb(255 0 0 / var(--tw-text-opacity));
}
```
expected result:
```CSS
.hover\:\[\&\.header-is-scrolled_\.menu-list_a\]\:tw-text-\[\#FF0000\].header-is-scrolled .menu-list a:hover {
  --tw-text-opacity: 1;
  color: rgb(255 0 0 / var(--tw-text-opacity));
}
```

# [Tailwind Play Link](https://play.tailwindcss.com/kuo2fGhMiZ)
![image](https://user-images.githubusercontent.com/5171262/208573193-a916f1a3-0efc-4064-99a9-f9b33fa8de3f.png)
```HTML
<div class="[&.header-is-scrolled_.menu-list_a]:tw-text-[#FF0000] header-is-scrolled">
  <div class="menu-list">
    <a href="#">abc<-</a>
  </div>
</div>
<div class="[&.header-is-scrolled_.menu-list_a]:tw-text-[#FF0000] header-is-scrolled">
  <div class="tw-menu-list">
    <a href="#">abc</a>
  </div>
</div>
<div class="[&.header-is-scrolled_.menu-list_a]:tw-text-[#FF0000] tw-header-is-scrolled">
  <div class="menu-list">
    <a href="#">abc</a>
  </div>
</div>
<div class="[&.header-is-scrolled_.menu-list_a]:tw-text-[#FF0000] tw-header-is-scrolled">
  <div class="tw-menu-list">
    <a href="#">abc</a>
  </div>
</div>

<div class="hover:[&.header-is-scrolled_.menu-list_a]:tw-text-[#FF0000] header-is-scrolled">
  <div class="menu-list">
    <a href="#">abc</a>
  </div>
</div>
<div class="hover:[&.header-is-scrolled_.menu-list_a]:tw-text-[#FF0000] header-is-scrolled">
  <div class="tw-menu-list">
    <a href="#">abc</a>
  </div>
</div>
<div class="hover:[&.header-is-scrolled_.menu-list_a]:tw-text-[#FF0000] tw-header-is-scrolled">
  <div class="menu-list">
    <a href="#">abc</a>
  </div>
</div>
<div class="hover:[&.header-is-scrolled_.menu-list_a]:tw-text-[#FF0000] tw-header-is-scrolled">
  <div class="tw-menu-list">
    <a href="#">abc<-</a>
  </div>
</div>
```

**Comment by Mullins22W** [comment]
Looking for the same issue. Bumped into your thread. Thanks for creating it. [Foremost Pay Online](https://www.foremostpayonline.org/)

**Comment by cristianstu** [comment]
I think I'm having a similar issue with group

This is not working:

```html
<div class="tw-group is-published">
  <div class="hidden group-[.is-published]:block">
    Published
  </div>
</div>
```

But found this is working:

```html
<div class="tw-group tw-is-published">
  <div class="hidden group-[.is-published]:block">
    Published
  </div>
</div>
```

Is this the same issue?

**Comment by thecrypticace** [comment]
Hey! Thank you for reporting this. It made us realize there were _two_ bugs lurking here and so we ended up fixing both! :D

The fix from #10214 has been merged and will be available in our next release. In the meantime you can test it using our insiders build: `npm install tailwindcss@insiders` (should be available in a few minutes)

**Comment by iwarshak** [comment]
Hi. Even using the insiders build on Tailwind Play, I am still running into an issue where TW is adding a prefix in a place where it isn't expected.

In my case, I am using Phoenix LiveView, which will add a `phx-click-loading` class to an element that is clicked. I have added the variant so that I can style the element when the `phx-click-loading` class is present. `phx-click-loading` is one of several classes that Phoenix can add to an element. 

```
plugin(({ addVariant }) =>
  addVariant('phx-click-loading', ['&.phx-click-loading'])
)
```

and this works perfect when I am not using a prefix. When I am using a prefix though, it is incorrectly adding the prefix to part of the generated class.

I am expecting it to add:

```
.phx-click-loading\:tw-animate-spin.phx-click-loading {
  animation: tw-spin 1s linear infinite;
}
```

but instead it is adding

```
.phx-click-loading\:tw-animate-spin.tw-phx-click-loading {
  animation: tw-spin 1s linear infinite;
}
```

I created an example in Tailwind Play (using the insiders build which looks like it has (https://github.com/tailwindlabs/tailwindcss/pull/10214) pulled in: https://play.tailwindcss.com/eBTOwTZWJ3?file=config

**Comment by jhcarl0814** [comment]
@thecrypticace Seems extra prefix is generated for classes inside "plugin-registered" variant. Should we reopen this issue or open another issue?

**Comment by thecrypticace** [comment]
@iwarshak @jhcarl0814 Prefixing classes in `addVariant` and `matchVariant` is by-design. Tailwind itself makes use of this behavior for `group` and `peer` variants. We do have an existing `respectPrefix: false` option for utilities and components. It's possible we could introduce this for variants as well. I'll start the discussion for this internally. In the meantime could you open a discussion for a new feature and @-mention me there please? It'll help keep track of it instead of discussing in a closed issue.

**Comment by adamwathan** [comment]
@iwarshak One way to get around this (we do this in the typography plugin even) is to use an attribute selector for your variant:

```js
plugin(({ addVariant }) =>
  addVariant('phx-click-loading', ['&[class~=“phx-click-loading”]'])
)
```

That’s the easiest way to opt-out of prefixing on a per-selector basis 👍🏻

**Comment by iwarshak** [comment]
@adamwathan This seems to do the trick, thanks!, But to be honest I have been using TW for a couple years now and this was not super obvious to me.

**Comment by emin-alizada** [comment]
> I think I'm having a similar issue with group
> 
> This is not working:
> 
> ```
> <div class="tw-group is-published">
>   <div class="tw-hidden group-[.is-published]:block">
>     Published
>   </div>
> </div>
> ```
> 
> But found this is working:
> 
> ```
> <div class="tw-group tw-is-published">
>   <div class="tw-hidden group-[.is-published]:block">
>     Published
>   </div>
> </div>
> ```
> 
> Is this the same issue?

I still get this problem, is there any workaround to this, because adding tw- to non tailwind class is not an ideal way to go.

**Comment by jhcarl0814** [comment]
@emin-alizada @thecrypticace 

`prefix: "tw-",` + `group-[.is-published]:tw-block`
generates:
```CSS
.tw-group.tw-is-published .group-\[\.is-published\]\:tw-block {
  display: block;
}
```
expected result:
```CSS
.tw-group.is-published .group-\[\.is-published\]\:tw-block {
  display: block;
}
```

(Changing from `group-[.is-published]:tw-block` to `group-[[class~=is-published]]:tw-block` will work.)

# [Tailwind Play Link](https://play.tailwindcss.com/IPjHBfyqw3)

![image](https://user-images.githubusercontent.com/5171262/234987986-3883e70f-6b1f-4979-8926-8e189889aba5.png)

![image](https://user-images.githubusercontent.com/5171262/234987747-e24b0d1f-4c60-4f9a-960b-e9f6e8db18c9.png)

**Comment by emin-alizada** [comment]
> @emin-alizada @thecrypticace
> 
> `prefix: "tw-",` + `group-[.is-published]:tw-block` generates:
> 
> ```css
> .tw-group.tw-is-published .group-\[\.is-published\]\:tw-block {
>   display: block;
> }
> ```
> 
> expected result:
> 
> ```css
> .tw-group.is-published .group-\[\.is-published\]\:tw-block {
>   display: block;
> }
> ```
> 
> (Changing from `group-[.is-published]:tw-block` to `group-[[class~=is-published]]:tw-block` (thanks to @adamwathan ) will work.)
> 
> # [Tailwind Play Link](https://play.tailwindcss.com/IPjHBfyqw3)
> ![image](https://user-images.githubusercontent.com/5171262/234987986-3883e70f-6b1f-4979-8926-8e189889aba5.png)
> 
> ![image](https://user-images.githubusercontent.com/5171262/234987747-e24b0d1f-4c60-4f9a-960b-e9f6e8db18c9.png)

Thank you very much!
