### ISSUE TITLE
print: is not working properly

### ISSUE THREAD

**Issue by HarshilSySCreations** [tailwindlabs/tailwindcss#10152]
**What version of Tailwind CSS are you using?**

v3.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**

express.js v4.16.1

**What version of Node.js are you using?**

v18.12.0

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction URL**

Sorry, It's a production code. Please **DO NOT CLOSE** this issue.

**Describe your issue**

The `print` is not working in a background color. It only works in text colors when we do print preview (Ctrl+P) or in printing.

```html
<div class='flex flex-row bg-gray-400 justify-center print:bg-red-600'>
    <p class='font-semibold text-black print:text-red-800'> Bulk Order : {{bulk_order}}</p>
</div>
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The `print` variant is using the native `@media print {}` media query. It _is_ working, but most printers by default do not print the background images and/or colors. You have to explicitly toggle this in the preview window.

For example on safari, in macOS Ventura, the preview print modal has this option:
<img width="502" alt="image" src="https://user-images.githubusercontent.com/1834413/209134208-a9b41f09-54b4-4d9a-9f27-c1147d0094d9.png">

On Chrome, there is this `More settings` option: 
<img width="416" alt="image" src="https://user-images.githubusercontent.com/1834413/209134499-ada4b6f3-daca-44db-9658-27531acdbdc5.png">

If you scroll down, you have to check this checkbox:
![image](https://user-images.githubusercontent.com/1834413/209134616-e895995e-0bcc-4296-82fd-ad644b4780a9.png)


Hope this helps!
