### ISSUE TITLE
Div content with brackets `[]` prevents arbitrary class from being generated

### ISSUE THREAD

**Issue by tordans** [tailwindlabs/tailwindcss#10180]
## This works: https://play.tailwindcss.com/0VLICQ8oUW

<img width="810" alt="image" src="https://user-images.githubusercontent.com/111561/209682078-7e43a107-52ff-4006-8c37-ec44414abe12.png">

## This does not work: https://play.tailwindcss.com/5KJf7xDKv6
<img width="821" alt="image" src="https://user-images.githubusercontent.com/111561/209682172-de1dcaaa-6e69-429b-907f-840691e35ceb.png">

**Comment by souravsarkar034** [comment]
Hey @tordans I am trying to understand the problem statement. If you elaborate about the project and the problem it will be helpful for me cause I am new in this project and I am trying to contribute in this project.

**Comment by master8848** [comment]
I did check through your code and didnt find any issue just pust a space before  ending "

**Comment by thecrypticace** [comment]
Hey, I've merged in the fix for this one. It'll be in out insiders build in a few minutes as well as available in the next release. Thanks for reporting this!
