### ISSUE TITLE
Brave Browser animate-pulse class does not work properly

### ISSUE THREAD

**Issue by dimka3553** [tailwindlabs/tailwindcss#10200]
**What version of Tailwind CSS are you using?**

v8.30.0

**What build tool (or framework if it abstracts the build tool) are you using?**

 Next.js v13.0.5

**What version of Node.js are you using?**

v16.17.0

**What browser are you using?**

Brave Browser

**What operating system are you using?**

macOS

**Reproduction URL**

https://tailwindcss.com/docs/animation

**Describe your issue**

In Brave browser the pulse animation that is supposed to change the opacity from 100% to 50% and then back to 100% for some reason appears to be a blue outline around the object.

In all other browsers the animation works fine.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I can't reproduce this on the Brave Browser on my mac (aka it works fine there). 

- If it works on the documentation page and not in your project, then make sure that you are configuring your content paths correctly: https://tailwindcss.com/docs/content-configuration#configuring-source-paths 
- If it doesn't work on the documentation page either, double check that you don't have any browser extensions or settings enabled that would interfere with this animation.

**Comment by dimka3553** [comment]
hi, @RobinMalfait,  just in case Here is a link to a video of the thing I'm experiencing, maybe its just for me though but it is super weird.

https://www.youtube.com/watch?v=_qm-ocliEzQ

maybe my brave settings are wrong or something, but I'll leave it here just in case.

**Comment by dimka3553** [comment]
here is an image of the animation style

<img width="346" alt="Screenshot 2022-12-31 at 17 42 51" src="https://user-images.githubusercontent.com/37512400/210150203-04601ad3-ac2c-43ee-b6ee-b10c2b53dbfc.png">
