### ISSUE TITLE
CSS conflict: applies the same CSS properties as

### ISSUE THREAD

**Issue by 1Krishna16** [tailwindlabs/tailwindcss#10209]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/5749

How to overcome css conflits in tailwind css

Example : What if i wanted to add both underline and line-through using tailwind-css

In css you can style it as:

        text-decoration-line: underline line-through;

But in tailwind it produces css conflict error. 
        
        <div class="underline line-through">hello</div>

Is there a way were i can force css to have both the properties of line-through and underline at the same time without using css class, just by tailwind-css class

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

Right now those utilities are not composable, you can either create your own plugin, or use arbitrary properties to achieve the result you want:
```html
<div class="[text-decoration:underline_line-through]">hello</div>
```
Here is a quick playground link with the solution: https://play.tailwindcss.com/baW2CzoBur

Hope this helps!
