### ISSUE TITLE
Multiple definitions of the transition-property

### ISSUE THREAD

**Issue by vermutely** [tailwindlabs/tailwindcss#10257]
**What version of Tailwind CSS are you using?**

For example: v3.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**

- tailwindcss cli (Standalone command)
- Tailwind Play

**What version of Node.js are you using?**

For example: v14.18.1 (tailwindcss cli)

**What browser are you using?**

For example: Chrome 108.0.5359.124

**What operating system are you using?**

For example: Ubuntu 20.04

**Reproduction URL**

 https://play.tailwindcss.com/NR9bHuVry6

**Describe your issue**

Multiple definitions of the transition-property in [Transition Property](https://tailwindcss.com/docs/transition-property).

### Current generated properties
<img width="837" alt="Tailwind Play" src="https://user-images.githubusercontent.com/120990970/211018605-92cbdbfc-e6b9-49c0-b2d7-b7358548b0c8.png">

- transition
```css
transition-property: color, background-color, border-color, fill, stroke, opacity, box-shadow, transform, filter, -webkit-text-decoration-color, -webkit-backdrop-filter;
transition-property: color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter;
transition-property: color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter, -webkit-text-decoration-color, -webkit-backdrop-filter;
transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
transition-duration: 150ms;
```

- transition-colors
```css
transition-property: color, background-color, border-color, fill, stroke, -webkit-text-decoration-color;
transition-property: color, background-color, border-color, text-decoration-color, fill, stroke;
transition-property: color, background-color, border-color, text-decoration-color, fill, stroke, -webkit-text-decoration-color;
transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
transition-duration: 150ms;
```

### Document

- transition
```css
transition-property: color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter;
transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
transition-duration: 150ms;
```

- transition-colors
```css
transition-property: color, background-color, border-color, text-decoration-color, fill, stroke;
transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
transition-duration: 150ms;
```

### Chrome developer tool
Property has been overwritten and is not functional.

<img width="659" alt="Chrome developer tool" src="https://user-images.githubusercontent.com/120990970/211019688-c6ce0b2b-2113-45ab-9725-48902808d088.png">

**Comment by adamwathan** [comment]
Hey! This is [autoprefixer](https://github.com/postcss/autoprefixer) adding vendor prefixes. It is all perfectly functional, this is how vendor prefixing for properties is handled in CSS. That's why the values for each definition are different.
