### ISSUE TITLE
Responsive Design doesn`t work when I use it in ${}.

### ISSUE THREAD

**Issue by businiaoyo** [tailwindlabs/tailwindcss#10271]
**What version of Tailwind CSS are you using?**

v3.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**

vite4.0.0 vue3.2.45

**What version of Node.js are you using?**

v14.21.1

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction URL**

![image](https://user-images.githubusercontent.com/44898875/211199285-e73ae2ae-8a7e-4187-8af2-dfd9d9c6bcac.png)

**Comment by adamwathan** [comment]
Hey! See the docs: https://tailwindcss.com/docs/content-configuration#dynamic-class-names

**Comment by businiaoyo** [comment]
Thanks a lot!
