### ISSUE TITLE
multi config via @config does not include preflight CSS and CSS Variable Defaults

### ISSUE THREAD

**Issue by adamwathan** [tailwindlabs/tailwindcss#10300]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/10215

<div type='discussions-op-text'>

<sup>Originally posted by **Onatcer** January  2, 2023</sup>
So I'm not really sure if this is a bug, missing documentation, if I just overlooked something or if this is expected behavior but I tried the multi-config feature and it did not include preflight CSS and CSS Variable Default Values like it would when I create a project normally. I was able to reproduce it in a minimal project with tailwind CLI.

Thats the style.css

```
@config "../tailwind.admin.config.js"
@tailwind base;
@tailwind components;
@tailwind utilities;
```

and here is the tailwind.admin.config.js

```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js}"],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

I didn't really find any documentation on the multi-config options and I also didn't find a way to manually include the options. I would have expected the multi-config files to behave the same as the regular files. 

Removing the `@config` directive from the CSS file and renaming tailwind.admin.config.js to tailwind.config.js gives me the expected result with preflight CSS and CSS Variable Defaults.

Did anyone else run into this issue? </div>

**Comment by thecrypticace** [comment]
If you end the `@config "../tailwind.admin.config.js"` with a semicolon it works as expected.

**Comment by markmead** [comment]
> If you end the `@config "../tailwind.admin.config.js"` with a semicolon it works as expected weirdly enough

This fixed it for me as well.

**Comment by thecrypticace** [comment]
Okay, this is definitely valid behavior for parsing CSS. Lightning CSS also parses newlines in at-rules as valid. While all the docs discussing `@config` are correct, our blogpost introducing the `@config` directive had the semicolons omitted by accident. It has been updated and should be deployed shortly.

Gonna close as not-a-bug. We're not gonna tweak the behavior for parsing `@config` right now to detect this as it shouldn't be a case people run into normally. We may decide to change this in the future tho.
