### ISSUE TITLE
double escape happening in attribute value selectors

### ISSUE THREAD

**Issue by lifeiscontent** [tailwindlabs/tailwindcss#10353]
**What version of Tailwind CSS are you using?**

v3.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.19

**What version of Node.js are you using?**

v14.19.1

**What browser are you using?**

Chrome

**What operating system are you using?**

Kubuntu Linux

**Reproduction URL**

https://play.tailwindcss.com/sRVqoiJfLV

**Describe your issue**

in the attribute value of a attribute selector the value is being double escaped and there appears to be no way to un-escape it.

**Comment by thecrypticace** [comment]
Hey, I've merged the fix for this in #10400. It'll be available in our next release. In the meantime you can test it using our insiders build which should be available in a few minutes: `npm instal tailwindcss@insiders`.

**Comment by lifeiscontent** [comment]
@thecrypticace thank you! :)
