### ISSUE TITLE
Play CDN not working

### ISSUE THREAD

**Issue by Dienesh89** [tailwindlabs/tailwindcss#10369]
There a an error in you play cdn when i try to use tailwind play csd it gives an error like this "Uncaught SyntaxError: Unexpected token ."
please solve this as soon as possible beacuse post css not installing in my computer beacuse my computer has some problems.that's why i use play cdn and when my dev is completed i convert all the files in post css using github codespaces and i con't use github codespaces as my dev ide beacuse when a switch the tab my code get's dismissed.

Please fix this as soon a pissible.
I hope you will respond.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I can't seem to reproduce this: https://jsfiddle.net/1jx5497t/, are you sure the error is coming from the CDN build?

If so, make sure to create a minimal reproduction that reproduces the issue and give us a bit more information about your OS (+version) and Browser (+version).

Also know that the CDN is not meant for production use and you shouldn't rely on it for production applications.
> Use the Play CDN to try Tailwind right in the browser without any build step. The Play CDN is designed for development purposes only, and is not the best choice for production.
https://tailwindcss.com/docs/installation/play-cdn

**Comment by karthik9728** [comment]
It not working -  <script src="https://cdn.tailwindcss.com"></script> 
To check I hit URL ( https://cdn.tailwindcss.com ) in browser and **got error - We can’t connect to the server at cdn.tailwindcss.com.**

**Comment by taikon** [comment]
Why's it tailwindcss@^2 and not tailwindcss@^3? Aren't we on V3.4 now?

**Comment by ParagRajabhoj18** [comment]
> It not working - <script src="https://cdn.tailwindcss.com"></script> To check I hit URL ( https://cdn.tailwindcss.com ) in browser and **got error - We can’t connect to the server at cdn.tailwindcss.com.**

same here bro any fix

**Comment by karthik9728** [comment]
> > It not working - <script src="https://cdn.tailwindcss.com"></script> To check I hit URL ( https://cdn.tailwindcss.com ) in browser and **got error - We can’t connect to the server at cdn.tailwindcss.com.**
> 
> same here bro any fix

Bro actually its not issue from Tailwind CSS, These issues are caused by network providers because few network providers blocked this website(https://cdn.tailwindcss.com/) that's why there is no response from server but if you try it with any VPN then you will get response from server and styles also start to work. these is one of drawback using external packages.

**Comment by Rahulsaba** [comment]
the issue is while we use live server extension the cdn is not working... use open with browser now my file is connected with network

**Comment by adityashinde9325** [comment]
<script src="https://unpkg.com/@tailwindcss/browser@4"></script>  c
dn not working   (Web server is returning an unknown error)
