### ISSUE TITLE
Order of CSS selectors is inconsistent each time the same build is run with Vite

### ISSUE THREAD

**Issue by joelvh** [tailwindlabs/tailwindcss#10378]
**What version of Tailwind CSS are you using?**

tailwindcss v3.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**

vite v4.0.3

**What version of Node.js are you using?**

node v16.18.1

**What browser are you using?**

Chrome

**What operating system are you using?**

macOs

**Reproduction URL**

CSS from server 1: https://play.tailwindcss.com/FhK4daTQLG?file=css
CSS from server 2: https://play.tailwindcss.com/eWyyqC64HS?file=css

Config file: https://play.tailwindcss.com/7WmGQKPdBk?file=config

**Describe your issue**

Tailwind is outputting CSS with selectors in a different order each time a build runs. This is prevalent when deploying to multiple servers. The same release will result in differing CSS build artifacts.

We experience this from time to time with a 404 error in the browser because the CSS filename on each server has a different hash. The HTML page is served from one server and then the CSS file is served by another server where the filename doesn't match.

I've provided a copy of the output of two servers where you can see the order in which CSS selectors is different. Config is also provided.

I want to say that this started with the move to Vite from Webpack.

Has anyone else experienced this?

<img width="1638" alt="image" src="https://user-images.githubusercontent.com/129096/213828059-a43d4b13-0ce5-490f-ab23-a3f50f0c0069.png">

**Comment by adamwathan** [comment]
Hey! Pushed a tweak that should fix this for you here: https://github.com/tailwindlabs/tailwindcss/pull/10382

Will be in the next release but you can try it now by installing our insiders build:

```
npm install -D tailwindcss@insiders
```

**Comment by joelvh** [comment]
@adamwathan thanks for such a quick response! Much appreciated. Will give this a spin.

**Comment by terryupton** [comment]
@adamwathan - I can confirm this fix also works.
I was having an issue with the order for grid cols breakpoint order is wrong. sm: is overwriting lg: and xl: when using Vite 4 to build.

<img width="466" alt="Screenshot 2023-02-02 at 10 58 52" src="https://user-images.githubusercontent.com/5698596/216310169-c6b773fe-f41f-49ed-911a-5acb669b4876.png">
<img width="1021" alt="Screenshot 2023-02-02 at 10 58 56" src="https://user-images.githubusercontent.com/5698596/216310187-1aa9cab2-4a12-4a9d-8a47-5fc085e1aa81.png">


When do you intend to release this fix?
