### ISSUE TITLE
impossible to use "box-shadow" with tailwind with no filter

### ISSUE THREAD

**Issue by Johnrobmiller** [tailwindlabs/tailwindcss#10375]
All box-shadows in tailwind are done using the "filter" css feature. However, there are some cases that require the dev to use "box-shadow: ..." rather than "filter: box-shadow(...)". For example, using filter, a button with a transparent background will cast a shadow from it's top border and button contents. Box-shadow does not do this.

Without the ability to distinguish between box-shadow and filter, there are some problems that are impossible to solve in Tailwind, resulting in the user needing to write old-fashioned css

**Comment by adamwathan** [comment]
Hey! Not sure what you're seeing but all box shadows in Tailwind use the `box-shadow` property:

https://play.tailwindcss.com/M527ncIjOs

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/4323180/213799995-69440780-5cee-4847-8dce-e6f1e51f842e.png">

We support both [box shadows](https://tailwindcss.com/docs/box-shadow) and [drop shadows](https://tailwindcss.com/docs/drop-shadow), the latter of which uses `filter` of course.
