### ISSUE TITLE
tailwind.config.js snippet code on documentation throws error on Next.js project

### ISSUE THREAD

**Issue by Shofol** [tailwindlabs/tailwindcss#10398]
**What version of Tailwind CSS are you using?**
v3.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**
Next.js 13.1.4

**What version of Node.js are you using?**
16.13.1

**What browser are you using?**
Chrome

**What operating system are you using?**
macOS

**Reproduction URL**
[Run this app and you'll see the error](https://github.com/Shofol/tailwind-issue.git)

**Describe your issue**
There's some formatting issue on ```tailwind.config.js``` file on this documentation page- https://tailwindcss.com/docs/guides/nextjs

If I copy this and completely paste in the project's ```tailwindcss.config.js``` file and try ```npm run dev``` I get this error- 

```
error - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[11].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[11].use[2]!./styles/globals.css
/Users/anowerjahan/tailwind-issue/tailwind.config.js:7


SyntaxError: Invalid or unexpected token
    at compileFunction (<anonymous>)
Import trace for requested module:
./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[11].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[11].use[2]!./styles/globals.css
./styles/globals.css
```
Some other people also faced the issue: https://stackoverflow.com/questions/75186877/tailwind-css-not-allowing-next-js-to-run/75198195

If I remove the space from line 6 then it works fine. 

<img width="1512" alt="Screenshot 2023-01-23 at 6 30 31 PM" src="https://user-images.githubusercontent.com/30428153/214048735-92f2535f-e003-45cc-bf60-49bdc35c9c9d.png">
<img width="1512" alt="Screenshot 2023-01-23 at 6 45 30 PM" src="https://user-images.githubusercontent.com/30428153/214048828-92b2211c-1c7f-4d45-956c-c786a42cc17e.png">

**Comment by thecrypticace** [comment]
Hey! Thanks for reporting this. We added a zero-width space to the code-snippet in an attempt to work around a highlighting issue which I've fixed another way. If you delete the line with the invisible character the error will go away. I've updated the guide as well. Thank you for reporting this! ✨
