### ISSUE TITLE
New color syntax with alpha

### ISSUE THREAD

**Issue by jjagielka** [tailwindlabs/tailwindcss#10401]
**What version of Tailwind CSS are you using?**

v3.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**

N/A

**What version of Node.js are you using?**

N/A

**What browser are you using?**

Firefox

**What operating system are you using?**

Linux

**Reproduction URL**

https://play.tailwindcss.com/NdQDxdS7f3

**Note:** Tailwind Play does not recognize the `bg-{color}-{number}/{alpha}` syntax.

**Describe your issue**

I love the new  `bg-{color}-{number}/{alpha}` syntax, but it does not work for `current` and therefore prevents to do a generic solutions.

```html
<div class="flex bg-blue-500">
    <div>
        <div class="w-56 h-16 bg-red-400" />
        <div class="w-56 h-16 bg-red-400/50" />
        <div class="w-56 h-16 bg-red-400/20" />
    </div>
    <div>
        <div class="w-56 h-16 bg-current" />
        <div class="w-56 h-16 bg-current/50" />
        <div class="w-56 h-16 bg-current/20" />
    </div>
</div>
```

**Comment by adamwathan** [comment]
Hey! It does work, the problem in your demo is that there is no such thing as a self-closing `<div/>` in HTML:

https://play.tailwindcss.com/tKv4tejTgM

**Comment by jjagielka** [comment]
OK. It works for `red` now (thanks for the hint), but I doesn't for `current`. See the corrected example:

https://play.tailwindcss.com/KI6Fnas9Do

**Comment by wesort** [comment]
I've just bumped up against this same scenario where I want to use `border-current/50` on something and was surprised `*-current/#` wasn't universally available with this color syntax.

Usecase: https://play.tailwindcss.com/DVIqs28bcU

**Comment by gambolputty** [comment]
Another use case: separating between "variant" and "color", like [radix-ui does here](https://www.radix-ui.com/themes/docs/components/button). Whereas "color" defines the color of a button and "variant" the background- or border opacity to define different button styles, like "solid", "outline", "ghost" etc.

This was possible with `bg-opacity-*` which is now deprecated syntax.
