### ISSUE TITLE
Read-only state is always applied on input[type="file"]

### ISSUE THREAD

**Issue by ilpet** [tailwindlabs/tailwindcss#10415]
**What version of Tailwind CSS are you using?**

For example: v3.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: Vite 4

**What version of Node.js are you using?**

For example: v18.12.1

**What browser are you using?**

For example: Chrome, Opera

**What operating system are you using?**

For example: macOS

**Reproduction URL**

[https://play.tailwindcss.com/S2BIIJILCW](https://play.tailwindcss.com/S2BIIJILCW)

**Describe your issue**

Read-only state is always applied on input[type="file"], even if it is not read-only.

**Comment by adamwathan** [comment]
Hey! This appears to be just how things work in HTML/CSS, `<input type="file">` always triggers the `:read-only` pseudo-class:

https://jsfiddle.net/m8vaL3h6/1/
