### ISSUE TITLE
Types declaration issues when using js instead of ts

### ISSUE THREAD

**Issue by nizhib** [tailwindlabs/tailwindcss#10450]
**What version of Tailwind CSS are you using?**

v3.2.4

**What version of Node.js are you using?**

v18.13.0

**What operating system are you using?**

Windows 11

**Reproduction URL**

[nizhib/tailwindcss-types-issue](https://github.com/nizhib/tailwindcss-types-issue)

**Describe your issue**

I have JS and TS scripts that produce the same output:
```text
[Function: tailwindcss] { postcss: true }
{ postcssPlugin: 'tailwindcss', plugins: [ [Function (anonymous)] ] }
```

```js
const createPlugin = require("tailwindcss");

/** @type {import('postcss').AcceptedPlugin} */
const plugin = createPlugin;

console.log(plugin);
console.log(plugin());
```

```ts
import createPlugin from "tailwindcss";
import type { AcceptedPlugin } from "postcss";

const plugin: AcceptedPlugin = createPlugin;

console.log(plugin);
console.log(plugin());
```

Although ESLint thinks that the former should not work:
```text
Type 'typeof import(".../tailwindcss/types/index")' is not assignable to type 'AcceptedPlugin'
```

Using `const createPlugin = require("tailwindcss").default;` mutes ESLint but breaks the code itself:
```text
undefined
<...>\src\index.cjs:7
console.log(plugin());
            ^
TypeError: plugin is not a function
```

The origin of the issue is my attempt to make `postcss.config.cjs` code verbose:

```js
const autoprefixer = require("autoprefixer");
const tailwindcss = require("tailwindcss");

/** @type {{plugins?: import('postcss').AcceptedPlugin[] | string }} */
const config = {
  plugins: [tailwindcss, autoprefixer],
};

module.exports = config;
```

**Comment by thecrypticace** [comment]
Hey! This is a limitation of typescript types and `esModuleInterop`. We could technically update the types to use `export =` along with some magical incantations required to make typescript happy and still export named types. However, this would break anyone using typescript that does not have `esModuleInterop` enabled in their project.

I would suggest working around typescript's issues here by using the following in your postcss config:
```js
const autoprefixer = require("autoprefixer");

/** @type {import('tailwindcss').default} */
// @ts-ignore
const tailwindcss = require("tailwindcss");

/** @type {{plugins?: import('postcss').AcceptedPlugin[] | string }} */
const config = {
  plugins: [tailwindcss, autoprefixer],
};

module.exports = config;
```

You'll see that I'm explicitly typing  the`tailwindcss` variable with the "default" export and then ignoring the error typescript would produce on the require line from giving it that type.
