### ISSUE TITLE
Unused classes from plugin accidentally get bundled

### ISSUE THREAD

**Issue by mrcaidev** [tailwindlabs/tailwindcss#10468]
**What version of Tailwind CSS are you using?**

v3.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite v4.0.4, Vanilla HTML/CSS

**What version of Node.js are you using?**

v19.5.0

**What browser are you using?**

Microsoft Edge

**What operating system are you using?**

Windows 11

**Reproduction URL**

https://github.com/mrcaidev/tailwind-plugin-mre

**Describe your issue**

Coming from #10460.

When registering classes with nested dark mode styles in a plugin, the dark mode style is always bundled in the generated CSS, even if never used.

```js
const plugin = require("tailwindcss/plugin");

module.exports = {
  // ...
  darkMode: "class", // The bug only exists when this is set to "class".
  plugins: [
    plugin(({ addComponents }) => {
      addComponents({
        ".bg-custom": {
          backgroundColor: "#f9fafb",
          ".dark &": {
            backgroundColor: "#111827", // This is always bundled, even if never used.
          },
        },
      });
    }),
  ],
};
```

This bug gets extremely tricky, when you register hundreds of classes in the plugin that all specifies `.dark &`. The output CSS bloated from 5KB to ~30KB, filled with unused classes.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The `dark` class is being used so we generate the required classes. Tailwind is not aware of "code", it scans all your code as plain text. You have the word `dark` in your `index.html`, so it will be generated.

More info on this topic: https://tailwindcss.com/docs/content-configuration#class-detection-in-depth

**Comment by mrcaidev** [comment]
So having `dark` class will lead to every class prefixed with `.dark` getting bundled? Even if `.dark .bg-custom` is never mentioned?

**Comment by RobinMalfait** [comment]
Yep so right now we match against classes and since your final result is `.dark .bg-custom` and we found a candidate `dark` which is included in your selector then we include it.

You can work around this if you want by doing something like this:
```js
const plugin = require('tailwindcss/plugin')

module.exports = {
  // ...
  darkMode: 'class', // The bug only exists when this is set to "class".
  plugins: [
    plugin(({ addComponents }) => {
      addComponents({
        '.bg-custom': {
          backgroundColor: '#f9fafb',
          '[class="dark"] &': {
            backgroundColor: '#111827'
          },
        },
      })
    }),
  ],
}
```
