### ISSUE TITLE
Arbitrary color (typed) does not allow `rgb()` wrapping `var()`

### ISSUE THREAD

**Issue by brandonmcconnell** [tailwindlabs/tailwindcss#10486]
**What version of Tailwind CSS are you using?**

v3.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss-cli v8.4.19

**What version of Node.js are you using?**

v18.12.1

**What browser are you using?**

Chrome v109

**What operating system are you using?**

macOS Ventura

**Reproduction URL**

https://play.tailwindcss.com/lJXZzh5f8f

**Describe your issue**

Arbitrary color properties do not work when they use an `rgb()` function that wraps a `var()`.

For example:

* This works: `[border-color:rgb(var(--red)/100%)]`
* This doesn't: `border-[color:rgb(var(--red)/100%))]`

**Comment by sibbng** [comment]
You have an extra parenthesis. If you remove it, it will work.

```html
border-[color:rgb(var(--red)/100%))]
                                  ^
```

**Comment by brandonmcconnell** [comment]
Wow. @sibbng thank you 😅🙏🏼
