### ISSUE TITLE
CSS injection order changed between 3.1.8 and 3.2.0 

### ISSUE THREAD

**Issue by deebov** [tailwindlabs/tailwindcss#10494]
**What version of Tailwind CSS are you using?**

v3.1.8 and v3.2.0

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss-cli 10.1.0

**What version of Node.js are you using?**

v14.19.3

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

v3.1.8
https://codesandbox.io/s/clever-jasper-t1t6q7

v3.2.0
https://codesandbox.io/s/kind-noether-zxdppk

How to run:

1. Fork the sandboxes
2. Create a new terminal
3. Run `yarn watch`
4. There will be a toast notification with a button to open it in the browser pane, click that button

**Describe your issue**

Between v3.1.8 and v3.2.0 there was a breaking change in the CSS injection order. If you check out the [v3.1.8 sandbox](https://codesandbox.io/s/clever-jasper-t1t6q7), you can see that the last element inside `prose` keeps its `md:my-12` in big screens. But in the [v3.2.0 sandbox](https://codesandbox.io/s/kind-noether-zxdppk) the `md:my-12` gets overridden by `@tailwindcss/typography`'s styles. `@tailwindcss/typography`'s styles do not change between the versions. It's just the order in which they're injected changes (not 100% sure but I assume so).

**Comment by adamwathan** [comment]
Hey! I can't for the life of me get the CodeSandbox stuff to even work, it never seems to load any CSS and just shows up using browser default styles.

<img width="721" alt="image" src="https://user-images.githubusercontent.com/4323180/216843372-9a788528-f4e3-4d2f-a336-619e7de66127.png">

I copied the HTML to a Tailwind Play and the margin seems to be applied how I'd expect:

https://play.tailwindcss.com/XrEI1PlCdP

Can you try to reproduce there, or create a very GitHub project I can clone that reproduces the issue?

**Comment by RobinMalfait** [comment]
A quick diff comparing both versions:
```diff
diff --git a/./old.css b/./new.css
index ff668c1..25fcd7a 100644
--- a/./old.css
+++ b/./new.css
@@ -1,4 +1,4 @@
-/* ! tailwindcss v3.1.8 | MIT License | https://tailwindcss.com */
+/* ! tailwindcss v3.2.4 | MIT License | https://tailwindcss.com */
 *,
 ::after,
 ::before {
@@ -756,6 +756,10 @@ video {
   padding-bottom: 3rem;
 }
 @media (min-width: 768px) {
+  .md\:my-12 {
+    margin-top: 3rem;
+    margin-bottom: 3rem;
+  }
   .md\:prose-lg {
     font-size: 1.125rem;
     line-height: 1.7777778;
@@ -954,8 +958,4 @@ video {
     :where(.md\:prose-lg > :last-child):not(:where([class~="not-prose"] *)) {
     margin-bottom: 0;
   }
-  .md\:my-12 {
-    margin-top: 3rem;
-    margin-bottom: 3rem;
-  }
 }
```

Or a visual version of this:
<img width="2144" alt="image" src="https://user-images.githubusercontent.com/1834413/216992463-81f201a3-43c0-4807-ba7c-56f92bcb1368.png">


@adamwathan I'll look into this

**Comment by deebov** [comment]
@RobinMalfait Thanks for fixing this quickly! I can confirm it's fixed in `insiders`.

**Comment by dmtrKovalenko** [comment]
Was this fixed? I noticed the same issue upgrading from 3.1.7 to 3.2.2 which actually broke all the cascading and should've been marked as breaking change
