### ISSUE TITLE
`PluginAPI` Type declaration is missing the helper function `addDefaults`

### ISSUE THREAD

**Issue by yaronuliel** [tailwindlabs/tailwindcss#10514]
https://github.com/tailwindlabs/tailwindcss/blob/7b3de616e9c26211c605d2378b9ceb4888a8cfa1/types/config.d.ts#L261

The plugin api provides an object with helper functions to every registered plugin. The object includes a function called `addDefaults` that can be used to register `:root` level CSS custom properties.
Since it is provided to the plugins - I guess it is there for some reason, so I think it make sense to also include it in the type definition of the API

The function is defined in [here](https://github.com/tailwindlabs/tailwindcss/blob/ef6f9ee6c2df6ff3ecfa4fda127ae7f672735e47/src/lib/setupContextUtils.js#L315) and is used in core plugins such as [border spacing](https://github.com/tailwindlabs/tailwindcss/blob/f821c71b7ebe3c56b5b9a2d39da0877ca3a2f40a/src/corePlugins.js#L782) and [transform](https://github.com/tailwindlabs/tailwindcss/blob/f821c71b7ebe3c56b5b9a2d39da0877ca3a2f40a/src/corePlugins.js#L875)

Open console in this example to see the list of helper functions - https://play.tailwindcss.com/R8vrYWtvNR 

If, for some reason, this method should remain "secret" and be used only for core plugins (e.g. it's a bad practice / its signature might change without introducing a breaking change) - then I think that the library should separate the registration of core plugins for external plugins, and create a different api for that. as long as the function is defined - it should be documented and typed 
(I've opened a [separate issue](https://github.com/tailwindlabs/tailwindcss.com/issues/1502#issue-1574161695) regarding the lack of documentation)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

We currently keep the `addDefaults` as "private", the API isn't the best right now, and we are also reworking it internally so it may not be needed anymore in the near future.

Exposing it in types and in the documentation means that we fully commit to it, right now we don't (yet), hope that makes sense! 

Going to close this for now and we will add the necessary types / documentation once we settle on the API.

**Comment by yaronuliel** [comment]
understood
I'd consider separating core plugin registration from the public plugin API...
if it shouldn't be used - it shouldn't be there

cheers :)
