### ISSUE TITLE
why key object understands as classname

### ISSUE THREAD

**Issue by Musho-T** [tailwindlabs/tailwindcss#10528]
**package version**
```
"next": "13.0.6",
"react": "18.2.0",
"react-dom": "18.2.0",
"autoprefixer": "10.4.13",
"postcss": "8.4.21",
"tailwindcss": "3.2.4"
"@tailwindcss/line-clamp": "0.4.2",
"tailwind-scrollbar": "2.1.0",
"tailwind-scrollbar-hide": "1.1.7",
"typescript": "4.9.5"
```

**tailwind.config.js**

```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",

    // Or if using `src` directory:
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  experimental: {
    optimizeUniversalDefaults: true,
  },
  theme: {
    extend: {},
  },
  plugins: [
    require('tailwind-scrollbar'),
    require('tailwind-scrollbar-hide'),
    require('@tailwindcss/line-clamp'),
  ],
  corePlugins: {
    preflight: false,
    float: false,
    animation: true,
    container: false,
    boxShadowColor: false,
    backgroundOpacity: false,
    textOpacity: false,
    borderOpacity: false,
  },
}
```

**postcss.config.js**

```
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}

```

**I have something like this in my page** 
`
const cars = {
    filter: 'sport',
}
`
**i use it** 
`<div>{cars.filter}</div>`

and without using any class from tailwind,
I get this css after build

`*{scrollbar-color:auto;scrollbar-width:auto}.filter{--tw-blur: ;--tw-brightness: ;--tw-contrast: ;--tw-grayscale: ;--tw-hue-rotate: ;--tw-invert: ;--tw-saturate: ;--tw-sepia: ;--tw-drop-shadow: ;filter:var(--tw-blur) var(--tw-brightness) var(--tw-contrast) var(--tw-grayscale) var(--tw-hue-rotate) var(--tw-invert) var(--tw-saturate) var(--tw-sepia) var(--tw-drop-shadow)}`

**there shouldn't be .filter classname here because I don't use it anywhere**

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

Since the word "filter" is there, the class will be generated. More info about this can be found here: https://tailwindcss.com/docs/content-configuration#class-detection-in-depth
