### ISSUE TITLE
Cant npm i after last update

### ISSUE THREAD

**Issue by ArtistHam** [tailwindlabs/tailwindcss#10537]
After I launch "npm i" got next error

```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path <path-to-project>\node_modules\tailwindcss\oxide-node-api-shim/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open '<path-to-project>\node_modules\tailwindcss\oxide-node-api-shim\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

I am sure that this error is because [this](https://github.com/tailwindlabs/tailwindcss/commit/add16364b4b1100e1af23ad1ca6900a0b53cbba0) commit and error started to show right after new version released

Please, confirm if this problem on my side or yours, this issue literally block my work.

**What version of Tailwind CSS are you using?**

I don`t even use Tailwind CSS

**What build tool (or framework if it abstracts the build tool) are you using?**

"webpack": "^5.73.0"

**What version of Node.js are you using?**

v18.12.1

**What browser are you using?**

Not related

**What operating system are you using?**

Windows

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The commit you linked to _fixes_ the install issue. Make sure to install the latest version.

`npm install tailwindcss@latest`

More info: #10536
