### ISSUE TITLE
Missing justify content "normal"

### ISSUE THREAD

**Issue by DavydeVries** [tailwindlabs/tailwindcss#10559]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/10558

<div type='discussions-op-text'>

<sup>Originally posted by **DavydeVries** February 12, 2023</sup>
Hi,

Currently, I'm using for viewport `sm` the class `sm:justify-center`. But I like to make the element full width on viewport `md`. The default value of `justify-content` is normally `justify-content: normal` (maybe differs on other browsers?). But there is no way to "reset" back to `normal` value.

Do you have suggestions to solve my issue, or is this value missing from the core?

Example:
Element not full width: https://play.tailwindcss.com/pj23KKG5cV
What I like to achieve/Expected behaviour: https://play.tailwindcss.com/oQ38fSUAsn

Kind regards,
Davy

_PS. I already tried to add `normal` to my config as an "extend" but didn't get it to work._</div>

**Comment by DavydeVries** [comment]
I made a pull to add `normal` to the core:
https://github.com/tailwindlabs/tailwindcss/pull/10560

**Comment by adamwathan** [comment]
Going to close this in favor of the discussion on the PR!
