### ISSUE TITLE
[Feature Request] Text stroke

### ISSUE THREAD

**Issue by bergstar** [tailwindlabs/tailwindcss#1056]
Looks like its pretty well supported:
https://caniuse.com/#search=text-stroke
... and there is a shadow fallback method.

Can sometimes look tacky, but a very useful feature when used properly:
https://www.kirupa.com/tricks/text_outline_effect.htm

**Comment by hacknug** [comment]
I created a plugin a while ago for this. If you have any suggestions, please, let me know! https://github.com/hacknug/tailwindcss-text-fill-stroke
