### ISSUE TITLE
@config rule doesn't work correctly with @import from postcss-import

### ISSUE THREAD

**Issue by Nagell** [tailwindlabs/tailwindcss#10613]
### **What version of Tailwind CSS are you using?**

v3.2.6

### **What build tool (or framework if it abstracts the build tool) are you using?**

"postcss": "^8.4.14",
"postcss-import": "^14.1.0",
"vite": "^4.1.0"

### **What version of Node.js are you using?**

v19.4.0

### **What browser are you using?**

N/A

### **What operating system are you using?**

macOS

### **Describe your issue / Reproduction URL**

As soon as I add the new 3.2 feature, which is `multi-config` and try to run or build the project,
I got a series of warnings and the styling doest'n appear.

**Reproduction:**
https://stackblitz.com/edit/tailwind-multi-config-bugreport?file=vite.config.ts,src%2Fstyles%2Findex-base.pcss,src%2Fstyles%2Findex-subsidiary.pcss,src%2Fmain.ts,dist%2Findex-subsidiary.css&terminal=dev

**Important files:**
- index-subsidiary.pcss - is an example of such file using the `@config` rule.
- index-base.pcss - just a normal index file (no `@config`, some `@imports` from `postcss-import`)
- main.ts - here you can switch between index-subsidiary.pcss and index-base.pcss
- dist/index.subsidiary.css - build output file

**Instructions:**
For some reason there is no preview on Stackblitz (probably because of a non-standard vite config), so I recommend you to download the project and run it locally. The system and browser probably doesn't matter.

You can also run 'yarn run build' directly and should also be able to see the problem.
The result which is dist/index.subsidiary.css looks fine at the first glance but it won't be added to the preview and on my machine with a couple of other postcss plugins it isn't even generated.

![image](https://user-images.githubusercontent.com/4633237/219681010-75387d82-4f18-400f-9694-570fac1c4785.png)

**Comment by adamwathan** [comment]
Hey! As you see in the error message the issue is:

`@import must precede all other statements`

Put your `@config` after your imports:

```css
@import "tailwindcss/base";
@import "./subsidiary/base/color.pcss";
@import "./base/paragraph.pcss";

@import "tailwindcss/components";
@import "./components/accordion.pcss";

@import "tailwindcss/utilities";
@import "./utilities/border.pcss";

@config '../../tailwind.subsidiary.config.cjs';
```

Annoying but `postcss-import` is strict about the CSS spec and requires nothing else come before your `@import` statements.

**Comment by Nagell** [comment]
Omg, I assumed naively that it's necessary to add the config at the beginning, since I didn't saw any changes in an output in my local project. Now I see, that I just got lost in my config imports (multirepo with a global config) and connected a wrong one 🤦 

Solved!
