### ISSUE TITLE
First letter selection color issue

### ISSUE THREAD

**Issue by alex-bacart** [tailwindlabs/tailwindcss#10641]
**What version of Tailwind CSS are you using?**

3.2.6, 3.2.7

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.21, CDN

**What version of Node.js are you using?**

v19.6.1

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/2NJ0LlnCWE

**Describe your issue**

Follow provided Tailwind Play link and select the text.

Chrome - first letter is selected with default color.
Safari - first letter isn't selected at all.
Firefox - everything is ok.

**Comment by adamwathan** [comment]
Hey! Unfortunately this isn't something we have any control over, this is just what browsers do even if you write this out as totally vanilla CSS yourself:

https://jsfiddle.net/eknz8rys/

Best luck is probably reporting this as a bug in Webkit and Chromium I'm afraid 🙁
