### ISSUE TITLE
Problem with rebuilding .html

### ISSUE THREAD

**Issue by St4rBoyek** [tailwindlabs/tailwindcss#10685]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/10376

<div type='discussions-op-text'>

<sup>Originally posted by **St4rBoyek** January 20, 2023</sup>
My path is: `"C:\Users\mrkro\Desktop\terstyy\[xddd]\nui"`
cmd: `npx tailwindcss -i ./src/input.css -o ./dist/output.css --watch`
![image](https://user-images.githubusercontent.com/40685883/213797448-3d458d52-3585-4847-ad8e-7d51d3633903.png)
![image](https://user-images.githubusercontent.com/40685883/213797706-c57294e3-7b01-4b1c-bb32-d8c1dabe38b5.png)
when I save index.html css isn't rebuilding, but when I save input.css it's rebuilding. I've noticed that this problem occurs when subfolders contain "[]" characters. What can I do besides renaming the folders?</div>

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Your content is looking for a `.src` folder, but you have a `src` folder. If you want to make them relative then you have to include the `/` as well:

```
'./src/**/*.html'
  ^
```

Hope this helps!

**Comment by St4rBoyek** [comment]
mb. I have ` content: ["./src/**/*.{html,js}"],` and it still not working
