### ISSUE TITLE
The `#{!important}` class does not exist. If `#{!important}` is a custom class, make sure it is defined within a `@layer` directive.

### ISSUE THREAD

**Issue by vasttian** [tailwindlabs/tailwindcss#10713]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/6994

<div type='discussions-op-text'>

<sup>Originally posted by **rupesh45** January 10, 2022</sup>
I'm using sass with tailwindcss and I want to use important!

:host ::ng-deep ss-multiselect-dropdown .open>.dropdown-menu {
    @apply flex #{!important};
    
}

This does not work, throws error!</div>

---
I have tried this usage: [Sass](https://tailwindcss.com/docs/using-with-preprocessors#sass)

My Gulp:
```typescirpt
import { src, dest, parallel, series } from 'gulp'
import dartSass from 'sass'
import gulpSass from 'gulp-sass'
import postcss from 'gulp-postcss'
import autoprefixer from 'gulp-autoprefixer'

const sass = gulpSass(dartSass)
src(resolve(tempFolder, '*.scss'))
  .pipe(postcss({}))
  .pipe(sass.sync())
  .pipe(autoprefixer({ cascade: false }))
  .pipe(dest(distFolder))
```
`postcss.config.js`:
```
module.exports = {
  syntax: 'postcss-scss',
  plugins: {
    'postcss-import': {},
    'tailwindcss/nesting': 'postcss-nesting',
    // 'tailwindcss/nesting': {},
    tailwindcss: {
      config: '../yimian-ui/tailwind.config.js',
    },
    autoprefixer: {},
  },
}
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Please open a new issue with a minimal reproduction repo attached.
