### ISSUE TITLE
Upgrading from tailwindcss@3.2.4 to tailwindcss@3.2.6 breaks specificity rules

### ISSUE THREAD

**Issue by BillBrower-Shopify** [tailwindlabs/tailwindcss#10757]
**What version of Tailwind CSS are you using?**
Version 3.2.6

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss@^8.4.4

**What version of Node.js are you using?**

For example: v14.0.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

A Tailwind Play link or public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways.

A reproduction is **required** when filing an issue — any issue opened without a reproduction will be closed and you'll be asked to create a new issue that includes a reproduction. We're a small team and we can't keep up with the volume of issues we receive if we need to reproduce each issue from scratch ourselves.

If you render this on 3.2.4 the background will be blue and if you render it on 3.2.6 the background will be red `<button class=" border border-black p-4 rounded-lg text-white text-xl bg-red-600 bg-blue-600">Hello</button>` 

**Describe your issue**

In 3.2.4 the last defined class wins in the case that two classes on an element conflict, in 3.2.6 the first defined class wins.

**Comment by adamwathan** [comment]
Hey! Take a look at this existing issue for a comprehensive explanation of what’s happening here:

https://github.com/tailwindlabs/tailwindcss/issues/10603

Hope that helps!
