### ISSUE TITLE
Tailwind not seeing bg-gradient-to-r T3 stack

### ISSUE THREAD

**Issue by Pawel1894** [tailwindlabs/tailwindcss#10769]
Hey, I got stuck for some time trying to use bg-gradient-to-r it is simply just not working even vscode extension is not seeing that. I even copied docs examples 1:1 and still got no effect. I checked in on other projects react created with vite and it worked just fine.

- tailwindcss v3.2.0 + 
- node v18.13.0

tools i use
- next 13.2.1
- postcss 8.4.14
- prettier-plugin-tailwindcss v0.2.1
- vscode tailwind official extension
- windows 10

here is link to my repo: https://github.com/Pawel1894/t3-todo-list

**Comment by thecrypticace** [comment]
Hey! The reason for this is because you're overriding the `backgroundImage` property in your config:

```js
    backgroundImage: {
      "mobile-header": "url(/images/bg-mobile-light.jpg)",
      "desktop-header": "url(/images/bg-desktop-light.jpg)",
      "dark-mobile-header": "url(/images/bg-mobile-dark.jpg)",
      "dark-desktop-header": "url(/images/bg-desktop-dark.jpg)",
    },
```

What you want is to extend the config with additional values:
```js
    extend: {
      backgroundImage: {
        "mobile-header": "url(/images/bg-mobile-light.jpg)",
        "desktop-header": "url(/images/bg-desktop-light.jpg)",
        "dark-mobile-header": "url(/images/bg-mobile-dark.jpg)",
        "dark-desktop-header": "url(/images/bg-desktop-dark.jpg)",
      },
    },
```

**Comment by Pawel1894** [comment]
Thx for fast asnwer I didin't knew it is somehow linked with bgImages :)
