### ISSUE TITLE
Tailwind classes NOT being applied the components in components folder Next JS 

### ISSUE THREAD

**Issue by shanewmurphy** [tailwindlabs/tailwindcss#10793]
Absolutely sick to death of following the documentation and it NOT working! 
**Tailwind CSS Version 3.2.7**

**Next js 13.2.3**

Tailwind config file as per documentation for next JS like so,

```
`/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}`
```

NO tailwind classes are being applied to any of my components within the components folder, Why?
Tailwind classes are being added to files in Pages/Index.js

I created an src folder and added my components there and yeah tailwind classes will be applied. BUT when a push my project to GitHub NONE of my components in the SRC folder get pushed to my github repository.

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏


It's always frustrating when things don't work the way you expected. Unfortunately we can't help you without a minimal reproduction repo that shows the problem. There can be many issues in setup / folder structure / ... that could lead to this problem.

A few things that you can check:
- You talk about "I created a `src` folder", yet, the `content` config you defined only looks in the `app`, `pages` and `components` folder.
- You also typed `Pages/Index.js` (notice the casing). It can be that your filesystem is case (in)sensitive and the server you are deploying on is not (or vice versa). Make sure that the casing is correct.

> "BUT when a push my project to GitHub NONE of my components in the SRC folder get pushed to my github repository"

I'm not 100% sure what this means, if you mean that the files in your `components` folder doesn't show up on GitHub then that's unrelated to Tailwind. You have to make sure that you add & commit those files.

---

If this is still an issue for you, please open a new issue but include a proper reproduction — a [Tailwind Play](https://play.tailwindcss.com) if the issue can be reproduced there, or a GitHub repository where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!

**Comment by RobinMalfait** [comment]
I noticed that you already opened an issue here: https://github.com/tailwindlabs/tailwindcss/issues/10792

Please follow the instructions in the issue template.

**Comment by mmoderwell** [comment]
If anyone comes across this issue, my fix was to make sure I'm importing my globals.css file into ./app/layout.tsx. Since we're not using _app or _document anymore, you still need to be importing the Tailwind directives into the app somewhere, and I found the root layout to be the most logical place for that.
