### ISSUE TITLE
Dynamic setting of grid-cols does not work properly

### ISSUE THREAD

**Issue by chudongvip** [tailwindlabs/tailwindcss#10806]
**What version of Tailwind CSS are you using?**

For example: v3.2.7

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: vite 2.9.12, vue 3.2.37

**What version of Node.js are you using?**

For example: v16.18.1

**What browser are you using?**

For example: Chrome

**What operating system are you using?**

For example: macOS

**Reproduction URL**

[codesandbox](https://codesandbox.io/p/sandbox/upbeat-blackburn-oyj9b0?file=%2FREADME.md)

**Describe your issue**
 
Its work when i without vue bind class. 

```
<div class="grid gap-4 grid-cols-4">
      <div class="border border-red-500" v-for="i in viewBoxCounts">
        {{ i }}
      </div>
</div>
```

**Comment by nhedger** [comment]
Class names should not be dynamically constructed because Tailwind cannot detect them.

https://tailwindcss.com/docs/content-configuration#dynamic-class-names

As a last resort, you can use [safelisting](https://tailwindcss.com/docs/content-configuration#safelisting-classes).

**Comment by chudongvip** [comment]
> Class names should not be dynamically constructed because Tailwind cannot detect them.
> 
> https://tailwindcss.com/docs/content-configuration#dynamic-class-names
> 
> As a last resort, you can use [safelisting](https://tailwindcss.com/docs/content-configuration#safelisting-classes).

I got it, Thanks a lot. 🍺
