### ISSUE TITLE
The arbitrary values with spaces does not take effect when using rgb/rgba

### ISSUE THREAD

**Issue by lvqq** [tailwindlabs/tailwindcss#10863]
**What version of Tailwind CSS are you using?**

v3.2.7

**What build tool (or framework if it abstracts the build tool) are you using?**

Astro v2.1.3

**What version of Node.js are you using?**

v18.15.0

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction URL**

https://play.tailwindcss.com/tJdCWVYuZz

**Describe your issue**

When using rgb/rgba, the arbitrary values with spaces does not take effect. 

For example:
`bg-[rgb(0,0,0)]` works but `bg-[rgb(0, 0, 0)]` doesn't work. And the rgb/rgba color with spaces is available in css.

If it's suitable to support this, I'd like to submit a pr.

Thanks!

**Comment by JawadR1** [comment]
CSS class names can't contain spaces so this can't be supported.
Here are some details to handle white spaces in [Tailwind Docs](https://tailwindcss.com/docs/adding-custom-styles#handling-whitespace).

**Comment by lvqq** [comment]
Thanks! I get it
