### ISSUE TITLE
@tailwindcss/line-clamp check produces an error if bundled.

### ISSUE THREAD

**Issue by mayerraphael** [tailwindlabs/tailwindcss#10894]
https://github.com/tailwindlabs/tailwindcss/blame/3809127a2ce7e8173611ae40c7a260bb56e6342f/src/util/normalizeConfig.js#L304

We use tailwind with StencilJS, which uses Rollup to generate packages. The problem with this change is that the require call is moved out of the check farther up. Now this require call is **called outside the try catch and fails** the whole application. Most bundlers optimize imports, especially if they have to resolve interoparability between ESM and CJS.

This is also the only require call of the whole file, the other imports use ESM.

**Comment by herrlegno** [comment]
I got this problem too after upgrading to v3.3.0:
![image](https://user-images.githubusercontent.com/11634168/228471388-867ad2c9-1082-48c0-9247-b3565c4c67f6.png)

**Comment by fireworks2005** [comment]
I got the same error after upgraded to v3.3.0

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

Can you provide a minimal reproduction repo that showcases this issue?

It's also very odd that tools like rollup modify the intentional source code and create bugs like that 🤔. Either way, if you can provide a reproduction than I am happy to take a look for you!

**Comment by sgarcia-dev** [comment]
> It's also very odd that tools like rollup modify the intentional source code and create bugs like that 🤔. Either way, if you can provide a reproduction than I am happy to take a look for you!

We encountered the same issue as well with webpack 5.77.0. Kinda curious though, could this be related to a `process is not defined` issue we encountered as well? I filed a bug here. We are also mixing ESM + Common JS modules.
https://github.com/tailwindlabs/tailwindcss/issues/10918

**Comment by reinink** [comment]
Hey thanks again for reporting this. This has been fixed in #10919 and will be released as part of `v3.3.1`. Let us know if you have any further issues 👍
