### ISSUE TITLE
Outdated installation documentation (SvelteKit)

### ISSUE THREAD

**Issue by SylvainGarrigues** [tailwindlabs/tailwindcss#10931]
As per the following domumentation on [Install Tailwind CSS with SvelteKit](https://tailwindcss.com/docs/guides/sveltekit), one should run:
```npx tailwindcss init tailwind.config.cjs -p```

This creates an ESM Tailwind config file but the `.cjs`extension is for CommonJS module format.

**Comment by adamwathan** [comment]
Thanks, just pushed a docs update for both SvelteKite and Vite guides which will both generate ESM by default in v3.3+.
