### ISSUE TITLE
truncate: change overflow: hidden to overflow-x: clip

### ISSUE THREAD

**Issue by Jonathan-Jacob** [tailwindlabs/tailwindcss#10939]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/10938

<div type='discussions-op-text'>

<sup>Originally posted by **Jonathan-Jacob** April  4, 2023</sup>
There are certain fonts (Metropolis is an example: https://github.com/dw5/Metropolis) where there exist special characters (e.g., ÄÖÜ) that take up space above or below the line height. These parts of the typeface might not be displayed in a `div` with `overflow: hidden`. However, `overflow-x: clip` will do the trick here. Therefore I suggest changing the property of the `truncate` class from

`overflow: hidden;`
`text-overflow: ellipsis;`
`white-space: nowrap;`

to

`overflow-x: clip;`
`text-overflow: ellipsis;`
`white-space: nowrap;`
</div>

**Comment by reinink** [comment]
Hey! Thanks for this suggestion, but I'm worried that it might be too early for this change. It [looks like Safari](https://caniuse.com/css-overflow) only recently added `overflow: clip` support in version 16 (the latest version), meaning this change has the potential of breaking existing apps. For example, I'm still on macOS Monterey and have Safari 15 installed, and it doesn't work.

That said, if you're okay with not supporting older browsers, you can still totally accomplish this today with Tailwind by combining the following classes:

```html
<div class="whitespace-nowrap text-ellipsis overflow-x-clip w-28">
  Sint ex non proident id sit dolore dolore commodo Lorem laboris nulla. Mollit sunt cillum officia consectetur cillum elit aliqua laboris in.
</div>
```

Hope that helps! 🤙
