### ISSUE TITLE
`line-clamp` on a wrapper element doesn't work as expected in WebKit

### ISSUE THREAD

**Issue by iamchubko** [tailwindlabs/tailwindcss#10994]
**What version of Tailwind CSS are you using?**

v3.3.1

**What build tool (or framework if it abstracts the build tool) are you using?**

Nothing

**What version of Node.js are you using?**

The one in Tailwind Playground

**What browser are you using?**

Safari

**What operating system are you using?**

iOS

**Reproduction URL**

1. https://play.tailwindcss.com/e5MyJ1zroa
2. https://play.tailwindcss.com/ftDsuMZEMS

**Describe your issue**

1. 2 wrapping elements for `p`, the first one with `line-clamp`. Content is not rendered at all. Should be truncated after the 3rd line
2. 1 wrapping element for `p` with `line-clamp`. All content is rendered. Should be truncated after the 3rd line

I tested in a few browsers. Here are the results:
- works as expected: Firefox and Brave on Linux Mint, Chrome on Android
- breaks: WebKit-based browsers in general: Chrome and Safari on iOS in particular

What's the use case?
I use `line-clamp` to truncate content of rich text editor. And this thing has a lot of layers

**Comment by adamwathan** [comment]
Hey! This is just a limitation of how the line-clamp stuff in CSS works I'm afraid — we aren't doing anything special here, just using the CSS features as they're advertised. Seems like line-clamp only really works when applied directly to a node containing text, and not to a wrapper element:

https://jsfiddle.net/z18so9cw/

If you want something more flexible than how the line-clamp property works I think you have to move to a JS based solution 🙁 Sorry can't be more help!
