### ISSUE TITLE
in 3.3 `@apply dark: ` doesn't work anymore with vue `:deep(.child-class)`

### ISSUE THREAD

**Issue by remiconnesson** [tailwindlabs/tailwindcss#11024]
**What version of Tailwind CSS are you using?**
v3.3.1

**What build tool (or framework if it abstracts the build tool) are you using?**
vite4 and vite3 (happened with both)

**What version of Node.js are you using?**
v19.1.0

**What browser are you using?**
 Chrome

**What operating system are you using?**
WSL2 ubuntu 22

**Reproduction URL**
https://github.com/remiconnesson/tailwind-vue-deep-apply-dark-bug

**Describe your issue**
hello,

tailwincss is set in `darkMode: "class"` and we are using `useDark` from `vueUse` to add and remove the dark class.

in `App.vue` we have a child component 
```html
<template>
  [ ... ]
  <div class="wrapper">
    <ChildText />
  </div>
  [ ... ]
</template>

<style scoped>
[...]
.wrapper :deep(.child-text) {
  @apply text-pink-700 dark:text-yellow-300;
}
[...]
</style>
```

targeting `@/components/ChildText.vue`
```html
<template>
  <div class="child-text text-xl mt-8">
    I am targeted by my parent component with
  </div>
  [...]
</template>
```

but the `dark:` modifier doesn't work in `3.3` when it used it work in `3.2`

as shown in the screenshot below

- with `@3.3`, in the repro, one line of text should be yellow but is pink instead

<img width="340" alt="image" src="https://user-images.githubusercontent.com/28846642/232557687-5a00bc6b-d02c-4fd0-9c8f-5e603f5c1c06.png">

- with `@3.2` we observe the correct behavior

<img width="558" alt="image" src="https://user-images.githubusercontent.com/28846642/232558059-eb5a6e9c-3c4a-4d02-80c1-01f146c04e7f.png">

---
P.S: in `App.vue`

```html
<template>
  [...]
  <span class="block classic-apply">this is the target of an @apply rule</span>
  [...]
</template>

<style scoped>
/* A */
.classic-apply {
  @apply text-xl text-orange-700 dark:text-white;
}
</style>

/* B */
<style>
.wrapper .child-text-global {
  @apply text-sky-700 dark:text-purple-300;
}
</style>
```

we show that the dark modifier do work with 
- (A.) `apply` + `dark:` does work for elements in the same SFC inside a scoped style block
- (B.) `apply` + `dark:` does work inside a global style block

---
P.P.S: As stated in the vue doc here
https://vuejs.org/api/sfc-css-features.html#scoped-css

vue transforms this 
```
<style scoped>
.a :deep(.b) {
  /* ... */
}
</style>
```

into this

```
.a[data-v-f3f3eg9] .b {
  /* ... */
}
```

so this issue might not be only related to an interaction vuejs

**Comment by RobinMalfait** [comment]
@thecrypticace do you think this will already be solved by: #10943 & #10962?

**Comment by adamwathan** [comment]
@RobinMalfait Nah this is a Vue issue, we can reproduce it without using Tailwind at all. We're in the middle of researching some workarounds to recommend in the mean time, should have something some time today 👍

**Comment by doutatsu** [comment]
If this is a Vue issue, has anyone opened an issue in Vue.js on this? Been trying to find something, but can't - it would be good for Vue to fix this issue, rather than having to use a workaround. For now, it seems I am blocked form upgrading Tailwind

**Comment by doutatsu** [comment]
@thecrypticace 
> I'm going to work on a write-up and open an issue with Vue about this.

You mentioned you were going to open an issue on this - if you haven't done it so far, should I go ahead and open it myself with a link to this issue?

**Comment by doutatsu** [comment]
Issue opened on Vue ^

**Comment by adamwathan** [comment]
Here's a relevant PR someone has opened to fix this in Vue, just to connect the dots here:

https://github.com/vuejs/core/pull/8929
