### ISSUE TITLE
tailwindcss width no support  inherit  type

### ISSUE THREAD

**Issue by NaCoLiu** [tailwindlabs/tailwindcss#11042]
tailwindcss width no support  inherit  type

**What version of Tailwind CSS are you using?**

  "tailwindcss": "^3.3.1"

**What build tool (or framework if it abstracts the build tool) are you using?**

astrojs

**What version of Node.js are you using?**

v18.14.2

**What browser are you using?**

Chrome

**What operating system are you using?**

MacOS

**Comment by adamwathan** [comment]
Hey! We use issues exclusively for bug reports but this is a feature request so I'm going to close. You can always use arbitrary values for this sort of thing though:

```html
<div class="w-[inherit]">...</div>
```

**Comment by NaCoLiu** [comment]
thx
