### ISSUE TITLE
Underscores do not respect in the new line-height modifier

### ISSUE THREAD

**Issue by Serator** [tailwindlabs/tailwindcss#11045]
**What version of Tailwind CSS are you using?**

v3.3.1

**What build tool (or framework if it abstracts the build tool) are you using?**

play.tailwindcss.com

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction URL**

https://play.tailwindcss.com/NmUTJDQPDF

**Describe your issue**

![image](https://user-images.githubusercontent.com/625005/233361836-600d5c54-52c2-4acd-b66a-b2360aaea209.png)

Underscores are not converted to spaces in the new line-height modifier.

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

This should be fixed by #11057, and will be available in the next release.

You can already try it by using the insiders build `npm install tailwindcss@insiders`.

**Comment by RobinMalfait** [comment]
Updated the Tailwind Play using the latest insiders version: https://play.tailwindcss.com/XIC7aDoDCp

**Comment by Serator** [comment]
It works, thanks! 👍🏻
