### ISSUE TITLE
Pseudoselector empty with prefix not working

### ISSUE THREAD

**Issue by projct1** [tailwindlabs/tailwindcss#11048]
**What version of Tailwind CSS are you using?**
3.3.1

**What build tool (or framework if it abstracts the build tool) are you using?**
mix-tailwindcss  1.3.0
laravel-mix 5.0.9

**What version of Node.js are you using?**
16.19.1

**Describe your issue**
I trying use incredible tailwind with prefix `tw-` for class `tw-empty:hidden`, but rule is not created :(

![image](https://user-images.githubusercontent.com/9752959/233498251-bab8016b-1c5a-479f-b875-74479c801b20.png)
![image](https://user-images.githubusercontent.com/9752959/233498316-6ab2b564-e82a-47c2-9e3a-c29bfa07a537.png)

Here is my `tailwind.config.js`:
```javascript
module.exports = {
    prefix: 'tw-',
    plugins: [],
    content: ['./public_html/**/*.phtml', './resources/**/*.js'],
    theme: {
        extend: {
            fontFamily: {
                sans: ['Roboto'],
                serif: ['Lora']
            }
        }
  }
}
```

**Comment by wongjn** [comment]
Thank you for your report!

As per [the documentation](https://tailwindcss.com/docs/configuration#prefix), the prefix is added *after* any variants, so I believe the class you are looking for is `empty:tw-hidden`, not `tw-empty:hidden`.
