### ISSUE TITLE
Horizontal spacing issue with the first child element in Persian language

### ISSUE THREAD

**Issue by sir-kokabi** [tailwindlabs/tailwindcss#11055]
**What version of Tailwind CSS are you using?**

v3.3.1

**What build tool (or framework if it abstracts the build tool) are you using?**

none.

**What version of Node.js are you using?**

none.

**What browser are you using?**

Chrome.

**What operating system are you using?**

Windows

**Reproduction URL**

Sample repo: https://github.com/sir-kokabi/sample
Preview link: https://refined-github-html-preview.kidonng.workers.dev/sir-kokabi/sample/raw/main/index.html

```html <!doctype html>
<html dir="rtl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
  <ul class="flex space-x-10">
    <li>یک</li>
    <li>دو</li>
    <li>سه</li>
    <li>چهار</li>
  </ul>
</body>
</html>
```

**Describe your issue**
In the Persian language, the first child element does not get affected by the [horizontal spacing](https://tailwindcss.com/docs/space#add-horizontal-space-between-children) set between its sibling elements (i.e., using the "space-x-10" class). Only the second and subsequent child elements will have this spacing applied to them.

![image](https://user-images.githubusercontent.com/116794136/233598382-3e2b2627-270a-4a37-bbd0-7e7ad67439c2.png)

**Comment by adamwathan** [comment]
Hey! See previous issue: https://github.com/tailwindlabs/tailwindcss/issues/5792#issuecomment-944298930

**Comment by sir-kokabi** [comment]
Thank you for your quick response.
This technique is a bit tricky and I think it would be helpful to mention it in the documentation, as it can help RTL languages that use space-x-reverse.
