### ISSUE TITLE
Avoid using !important to override specificity.

### ISSUE THREAD

**Issue by AndyOGo** [tailwindlabs/tailwindcss#11084]
**What version of Tailwind CSS are you using?**

Any version with the `!` important modifier
https://tailwindcss.com/docs/configuration#important-modifier

**Reproduction URL**

https://play.tailwindcss.com/3juwpssaqx

**Describe your issue**

> Avoid using `!important` to override specificity.
https://developer.mozilla.org/en-US/docs/Web/CSS/important#best_practices

A better way is to increase CSS specificity by repeating the selector.

> **Note:** Repeated occurrences of the same simple selector are allowed and do increase specificity.
https://www.w3.org/TR/selectors-3/#specificity

---

I published a plugin to do this:
```js
const plugin = require('tailwindcss/plugin')

module.exports = {
  // ...
  plugins: [
    plugin(function({ addVariant }) {
      addVariant('trump', '&&')
    })
  ]
}
```

Play with it here
https://play.tailwindcss.com/v5ZpuKy2hH

---

Related discussion:
https://github.com/tailwindlabs/tailwindcss/discussions/10924

**Comment by adamwathan** [comment]
Hey! We use issues strictly for bug reports, there’s no bug here. We also already have features in Tailwind for increasing specificity without using important for people who prefer that:

https://tailwindcss.com/docs/configuration#selector-strategy

**Comment by AndyOGo** [comment]
Hi @adamwathan 

Thank you for your quick reply.

Though this is a bug report, please reopen it.

Tailwind promotes a well known anti-pattern of applying `!important`, which leads to all kind of unintended troubles with CSS itself and results in unnecessary over-configuration, like you mentioned.
https://tailwindcss.com/docs/configuration#selector-strategy
