### ISSUE TITLE
Classes made using `@layer` does not apply classes with special characters

### ISSUE THREAD

**Issue by voxxal** [tailwindlabs/tailwindcss#11098]
**What version of Tailwind CSS are you using?**
3.3.1

**What build tool (or framework if it abstracts the build tool) are you using?**
vite 4.3.0

**What version of Node.js are you using?**
19.8.1

**What browser are you using?**
Firefox

**What operating system are you using?**
Linux

**Reproduction URL**
https://play.tailwindcss.com/bMRcaHW3Cg

**Describe your issue**

When using `@layer`, and trying to create a class that uses something like `via-75%`, when using said class, `via-75%` will not be applied to the element. I expect `via-75%` to be applied to the element and have the gradient stop at 75%.

**Comment by adamwathan** [comment]
Hey! This is fixed in v3.3.2 (just came out today), see this updated Play using our insiders build (v3.3.2 isn't on Play yet) 👍 

https://play.tailwindcss.com/4uUjzHpQlS
