### ISSUE TITLE
jit mode compilet error with font-size

### ISSUE THREAD

**Issue by hellosanbao** [tailwindlabs/tailwindcss#11090]
I  set the `font-size` like it: `text-[30rpx]`.
I expect get`font-size:30rpx`,but the result is :`color:30rpx`,
It must end width 'px',but i want set 'rpx'
version: 3.3.1

**Comment by Mrlilili** [comment]
@hellosanbao How was it solved in the end?

**Comment by Simon-He95** [comment]
> @hellosanbao How was it solved in the end?

you can use text-[length:123rpx], or try this vscode plugin when saving,auto transform text-16rpx to text-[length:16rpx]
https://github.com/Simon-He95/vscode-tailwind-magic
