### ISSUE TITLE
Error in v3.3.2 on Linux (works in v3.3.1 and on MacOS in v3.3.2)

### ISSUE THREAD

**Issue by epoberezkin** [tailwindlabs/tailwindcss#11135]
**What version of Tailwind CSS are you using?**

v3.3.2

**What build tool (or framework if it abstracts the build tool) are you using?**

N/A

**What version of Node.js are you using?**

v16.14.0

**What browser are you using?**

N/A

**What operating system are you using?**

Linux

**Describe your issue**

```
npx tailwindcss -i tailwind.css -o _site/css/tailwind.css
```

It works on MacOS in 3.3.2, and it works on linux in 3.3.1, but terminates with an error on linux in 3.3.2 and logs this:

```
Unexpected token '.'
```

tailwind.css:

```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

**Comment by reinink** [comment]
Hey! What version of Node.js are you using? In v3.3.2 we had to drop support for Node.js 12. See #11089.

**Comment by epoberezkin** [comment]
Right, CI indeed uses 12. Thanks!

**Comment by reinink** [comment]
@epoberezkin Glad we got it figured out 👍
