### ISSUE TITLE
The param `addBase` api of plugin functions does not work for `class css style`

### ISSUE THREAD

**Issue by haijie-x** [tailwindlabs/tailwindcss#11134]
**What version of Tailwind CSS are you using?**
^3.3.2

**What build tool (or framework if it abstracts the build tool) are you using?**
"vite": "^4.3.2"

**What version of Node.js are you using?**
v16.15.0

**What browser are you using?**
Chrome version: 112.0.5615.137
For example: Chrome, Safari, or N/A

**What operating system are you using?**
macOS

**Reproduction URL**

A Tailwind Play link or public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways.

A reproduction is **required** when filing an issue — any issue opened without a reproduction will be closed and you'll be asked to create a new issue that includes a reproduction. We're a small team and we can't keep up with the volume of issues we receive if we need to reproduce each issue from scratch ourselves.

The param `addBase` api of plugin functions does not work with `html.dark` but work with `html#dark`
<img width="806" alt="image" src="https://user-images.githubusercontent.com/98948357/235363897-09be60d0-a085-4cff-9344-ce6cef3bfa15.png">
<img width="804" alt="image" src="https://user-images.githubusercontent.com/98948357/235363937-07b34703-6aa1-4bd5-910b-0de0d14333e2.png">
the code is like: 
```js 
plugins: [
    plugin(function ({ addBase }) {
      addBase({
        'html.dark': {
          background: 'black'
        }
      })
    })
  ] 
```

**Comment by adamwathan** [comment]
Hey! This works as expected for me, as long as the `dark` class is present in one of your templates somewhere to make sure Tailwind knows the rule needs to be generated:

<img width="518" alt="image" src="https://user-images.githubusercontent.com/4323180/235367338-4dd3ffaa-89f1-43b6-891d-7a1f8fe48ae6.png">

If you still have issues here please open a new issue that includes a proper reproduction as per the issue template and we can take a closer look 👍
