### ISSUE TITLE
yarn package not updated?

### ISSUE THREAD

**Issue by ImaCrea** [tailwindlabs/tailwindcss#11144]
Hi there,

Thanks for TailwindCS, it's an amazing tool I discovered recently... I wish I tried it before!

I'm using yarn but it seems package is not following latest updates. As you can see on https://yarnpkg.com/package/tailwindcss it says 3.2.7 whereas latest is 3.3.

I'm a novice on yarn and all so I'm maybe missing something..

best,

**Comment by adamwathan** [comment]
Hey! I think the yarn site is just out of date, we only actually publish to npm which is where I believe yarn ultimately pulls from anyways.

**Comment by ImaCrea** [comment]
Thanks for your answer, it's in deed updated to latest version :)
