### ISSUE TITLE
Mixing certain pseudo selectors produces invalid css rules

### ISSUE THREAD

**Issue by jaketodaro** [tailwindlabs/tailwindcss#11146]
**What version of Tailwind CSS are you using?**

v3.0.24

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss ^8.4.12

**What version of Node.js are you using?**

v16.20.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/74pcKVCzJX

**Describe your issue**

Mixing certain psuedo selectors produces in valid css rules. For example `first-line:first-letter:bg-transparent` produces the following CSS

```
.first-letter\:first-line\:bg-transparent::first-line::first-letter {
  background-color: transparent;
}
```

This is a dumb classname to write since you can't actually use `:first-line` and `:first-letter` together, but the fact that this classname causes tailwind to produce an invalid selector causes problems when selectors are merged because it will break the entire css rule.

Recently someone wrote this exact selector in our app and it didn't do anything at the time, but it was a ticking time bomb. When I came along months later and added the first use of the `bg-transparent` class, it got merged with the bad selector and didn't work and was a pain to debug.

```
.bg-transparent,.first-letter\:first-line\:bg-transparent::first-line::first-letter {
  background-color: transparent;
}
```

Ideally tailwind wouldn't produce invalid selectors that will break when merged with other selectors. The bad classname that caused the invalid selector should fail gracefully.

**Comment by adamwathan** [comment]
Hey! I think this is ultimately more a bug/feature request for whatever minification library you are using than for Tailwind, as you run into the same problem writing that sort of CSS by hand of course:

https://cssnano.co/playground/#eyJpbnB1dCI6Ii5mb28ge1xuICBiYWNrZ3JvdW5kLWNvbG9yOiB0cmFuc3BhcmVudDtcbn1cblxuLmJhcjo6Zmlyc3QtbGluZTo6Zmlyc3QtbGV0dGVyIHtcbiAgYmFja2dyb3VuZC1jb2xvcjogdHJhbnNwYXJlbnQ7XG59IiwiY29uZmlnIjoiY3NzbmFuby1wcmVzZXQtZGVmYXVsdCJ9

Lightning CSS is a new tool that handles minification and catches this error:

https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20background-color%3A%20transparent%3B%5Cn%7D%5Cn%5Cn.bar%3A%3Afirst-line%3A%3Afirst-letter%20%7B%5Cn%20%20background-color%3A%20transparent%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D

We could definitely try to catch stuff like this for you so I'll leave this open as a reminder to spend an hour exploring what it would take to validate every selector we generate and test the impact that has on performance, but my gut is it might not be worth it and that this is better handled by using a tool that minifies more safely.

**Comment by Hollywilson90** [comment]
Thanks for sharing..

**Comment by Haydenpayne** [comment]
Thanks for sharing the information. [MyTHDHR
](https://www.mythdhr.ltd/)

**Comment by CodeMode365** [comment]
@jaketodaro I don't fully understand, but i know that you are trying to say that the tailwind class first-line:first-letter:**_SomeColor_** isnot working how about you seperate the class and write it.
As in example below:
https://play.tailwindcss.com/Ezuu37v5hN

**Comment by adamwathan** [comment]
Going to close this one for now as we don't have any plans to make tweaks here — Tailwind just generates what you tell it to generate and I think it's best to just keep it that way for now until this is clearly a bigger/more widepread issue people run into 👍
