### ISSUE TITLE
The two versions have the same class but behave differently

### ISSUE THREAD

**Issue by Godsex** [tailwindlabs/tailwindcss#11177]
**What version of Tailwind CSS are you using?**

V3.3.2

**What build tool (or framework if it abstracts the build tool) are you using?**

Angular14.1.1

**What version of Node.js are you using?**

V16.16.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/7aef44vzB0
https://play.tailwindcss.com/jIaPV6P7ZS

**Describe your issue**
The two versions have the same class but behave differently

**Comment by adamwathan** [comment]
Hey! This isn't unexpected, prior to Tailwind CSS v3.2.5 the order of the generated CSS was non-deterministic for conflicting classes so depending on which class you used first in your project you could see different results.

This was changed in #10382 to always be deterministic, but even so you shouldn't add conflicting classes to the same element, you should just add the one class you actually want to take effect.

We warn about this in Tailwind Play and in the IntelliSense extension with this lint warning:

<img width="813" alt="image" src="https://user-images.githubusercontent.com/4323180/236725936-72367401-1898-4113-b419-e48d8c7586da.png">

Hope that helps!
