### ISSUE TITLE
[v3.3.2] Docs: sticky element not working as expected

### ISSUE THREAD

**Issue by mattmischuk** [tailwindlabs/tailwindcss#11220]
**What version of Tailwind CSS are you using?**
v3.3.2

**What build tool (or framework if it abstracts the build tool) are you using?**
n/a

**What version of Node.js are you using?**
n/a

**What browser are you using?**
Chrome

**What operating system are you using?**
macOS latest

**Reproduction URL**
https://tailwindcss.com/docs/position#sticky-positioning-elements

**Describe your issue**
On the sticky section of the documentation there is a bug where in some cases the category sticky element does not show up as they are expected to.

https://github.com/tailwindlabs/tailwindcss/assets/3485831/9253a536-e457-4ac9-b214-eaec19e5df51

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

It looks like this is a new render bug in Chrome. You can hover your mouse over where the sticky header should be or zoom in/out and it pops up. I'll open an issue on the Chrome bug tracker for this, thanks!

**Comment by mattmischuk** [comment]
@RobinMalfait  Thanks for being such a pro maintainer and addressing this so quickly! Love when OSS is this responsive.

**Comment by RobinMalfait** [comment]
Hey! Sorry about the delay. I was trying to make a minimal reproduction of this issue before submitting a Chromium bug but that seemed harder than expected (my guess is that the big page has something to do with it). But, I filed a bug based on this information and what I see in Chrome itself using the example on our documentation website. Link to the Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1459318

I'll keep an eye on it and report back when there is more information.
