### ISSUE TITLE
bug in the divide-x class when use on rtl version page.

### ISSUE THREAD

**Issue by nafasebra** [tailwindlabs/tailwindcss#11245]
Hi.
I see a bug when use the divide-x class in rtl direction what border was not set on first item

I am using latest version now (3.3.2) and my browser is Chrome - Windows

this my code:

```html
   <div class="divide-x-2 divide-gray-200">
      <!-- some items :) -->
   </div>
```

and this is preview:

![Capture](https://github.com/tailwindlabs/tailwindcss/assets/74317517/c1b05481-dd69-4ad1-b666-66002a621731)

**Comment by adamwathan** [comment]
Hey! See previous issue: https://github.com/tailwindlabs/tailwindcss/issues/10179#issuecomment-1365963521
