### ISSUE TITLE
Arbitrary groups seem doesn't work

### ISSUE THREAD

**Issue by cawa-93** [tailwindlabs/tailwindcss#11246]
**What version of Tailwind CSS are you using?**
2.2.19

**What browser are you using?**
Firefox 114

**What operating system are you using?**

Windows 10

**Reproduction URL**
https://play.tailwindcss.com/YShTf1coHJ

**Describe your issue**

I simply copy-paste code samples from docs, and seems tailwind doesn't generate CSS for Arbitrary groups:

![зображення](https://github.com/tailwindlabs/tailwindcss/assets/1662812/98a33a38-9062-473d-8c0a-4f8a1351ffc7)

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

The arbitrary types are only available in Tailwind CSS v3.x and up. They weren't available in Tailwind CSS v2.x yet.

Here is an updated Tailwind Play with version 3 selected: https://play.tailwindcss.com/QQXxXCIYRa

If you want to make use of this feature, make sure to upgrade to Tailwind CSS v3. More info about this can be found in the upgrade guide: https://tailwindcss.com/docs/upgrade-guide

Hope this helps!
