### ISSUE TITLE
shadow-md doesn't work with shadow-color

### ISSUE THREAD

**Issue by jvalrog** [tailwindlabs/tailwindcss#11242]
**What version of Tailwind CSS are you using?**

v3.3.2

**What build tool (or framework if it abstracts the build tool) are you using?**

vite 2.9.9
postcss 8.4.23

**What version of Node.js are you using?**

v16.20

**What browser are you using?**

Firefox 113

**What operating system are you using?**

Ubuntu Linux

**Describe your issue**

When using `shadow-md` and `shadow-[color]-[number]` the color isn't applied.

It works with `shadow`, `shadow-sm`, `shadow-lg`and `shadow-xl`.

Problem is `shadow-md` is added after `shadow-color`:

![image](https://github.com/tailwindlabs/tailwindcss/assets/456311/f71f849e-c517-4434-a18d-1c7e14ef5315)

While if you use `shadow-lg` for example:

![image](https://github.com/tailwindlabs/tailwindcss/assets/456311/43230314-6e18-404b-b026-f00a6251a8f6)

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

Can you share a minimal reproduction repo that showcases this issue?
I can't seem to reproduce it: https://play.tailwindcss.com/0hTRtfxIxA

If you can share a minimal reproduction repo than I'm more than happy to help figure out what's going on!

**Comment by jvalrog** [comment]
Hello, sorry cannot get a reproduction url this time. I see it doesn't happen there, so it must be something with my setup.

This is my postcss.config.js btw:

```js
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
```
