### ISSUE TITLE
Mismatch in TS types and docs example for `matchVariant`

### ISSUE THREAD

**Issue by brandonmcconnell** [tailwindlabs/tailwindcss#11251]
The [docs](https://tailwindcss.com/docs/plugins#dynamic-variants) (2nd example under "Dynamic variants" section) show this example: 

```js
matchVariant("min", (value) => `@media (min-width: ${value})`, {
  sort(a, z) {
    return parseInt(a) - parseInt(z);
  },
});
```

but when I add that same example to Tailwind Play ([here](https://play.tailwindcss.com/7jSUGQ5kjV?file=config)), I see these type linting errors:

```
(parameter) a: {
    value: string;
    modifier: string;
}
Argument of type '{ value: string; modifier: string; }' is not assignable to parameter of type 'string'.(2345)
```

```
(parameter) z: {
    value: string;
    modifier: string;
}
Argument of type '{ value: string; modifier: string; }' is not assignable to parameter of type 'string'.(2345)
```

Presumably, the example in the docs needs to be updated to use the `value` property like this:

```js
matchVariant("min", (value) => `@media (min-width: ${value})`, {
  sort(a, z) {
    return parseInt(a.value) - parseInt(z.value);
  },
});
```

**Comment by thecrypticace** [comment]
Oooh good catch! That documentation was written before it was finalized and we added info for modifiers and we missed updating it. I've updated the documentation and it'll be deployed shortly.

**Comment by brandonmcconnell** [comment]
@thecrypticace Thanks!

**Comment by brandonmcconnell** [comment]
@thecrypticace For future reference, would an issue related to the website be better submitted to the website repo (https://github.com/tailwindlabs/tailwindcss.com)?

**Comment by thecrypticace** [comment]
Yep, that would indeed be preferable
