### ISSUE TITLE
Tailwind breaks feature, just by being installed

### ISSUE THREAD

**Issue by aarav2you** [tailwindlabs/tailwindcss#11279]
**What version of Tailwind CSS are you using?**

3.3.2

**What build tool (or framework if it abstracts the build tool) are you using?**

AstroJS

**What version of Node.js are you using?**

v17.6.0

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows and/or Linux

**Reproduction URL**

1. WITHOUT TAILWIND: https://github.com/aarmort/normal/tree/main
2. WITH TAILWIND: https://github.com/aarmort/normal/tree/with_tailwind

**Describe your issue**
Steps to run:
1. Clone specified branch
2. Run `npm i`
3. Run `npm run dev`
---
1. Use the[ repository/branch without tailwind](https://github.com/aarmort/normal/tree/main): Drag your mouse across the screen and you see that it moves the whole track/image to the other end effortlessly
2. Use the [branch with tailwind](https://github.com/aarmort/normal/tree/with_tailwind): You see that tailwind is NOT even used anywhere in the code, yet when you try to move the track by dragging your mouse it stops at one point and cannot go any further

But why? I haven't even used tailwind in the code, only added it via `npx astro add tailwind`

**Comment by aaravrav** [comment]
It seems to be because of this rule in Tailwind preflight:
```css
img, video {
    max-width: 100%;
      height: auto;
}
```

Specifically, the max-width: 100% property. You could override this by applying max-width: none to all the .image elements by >adding the max-w-none class or disable the preflight core plugin.
