### ISSUE TITLE
[Bug] `bg-[radial-gradient(...)]` not taking effect

### ISSUE THREAD

**Issue by wenfangdu** [tailwindlabs/tailwindcss#11293]
**What version of Tailwind CSS are you using?**

v3.3.2

**What build tool (or framework if it abstracts the build tool) are you using?**

webpack 5.28.1

**What version of Node.js are you using?**

16.9

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/jO8stKEINM

**Describe your issue**

`bg-[radial-gradient(79.84% 234.26% at -33.27% 51.79%, rgba(0, 0, 0, 0.08) 0%, rgba(0, 0, 0, 0.0410285) 27.33%, rgba(0, 0, 0, 0.0001) 100%)]` not taking effect.
![image](https://github.com/tailwindlabs/tailwindcss/assets/28700378/e2fb3fd5-7a20-44c7-adff-971cdc19ba50)

**Comment by wongjn** [comment]
Classes are delimited with whitespace, so [as per the documentation](https://tailwindcss.com/docs/adding-custom-styles#handling-whitespace), you'd need to escape any spaces with an underscore (`_`):

```
bg-[radial-gradient(79.84%_234.26%_at_-33.27%_51.79%,rgba(0,0,0,0.08)_0%,rgba(0,0,0,0.0410285)_27.33%,rgba(0,0,0,0.0001)_100%)]
```

See it working at https://play.tailwindcss.com/jO8stKEINM

**Comment by wenfangdu** [comment]
@wongjn Thanks, didn't know that.
