### ISSUE TITLE
Styling based on sibling `:visited` state not working

### ISSUE THREAD

**Issue by zhongl** [tailwindlabs/tailwindcss#11337]
**What version of Tailwind CSS are you using?**

v3.3.2

**What build tool (or framework if it abstracts the build tool) are you using?**

Only tailwindcss

**What version of Node.js are you using?**

For example: v20.1.0

**What browser are you using?**

Chrome, Safari

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/COwjw8FpFA

**Describe your issue**

Styling based on sibling `:visited` state not working.

**Comment by adamwathan** [comment]
Hey! This is just a CSS limitation — for privacy/security reasons the browser forbids using the `:visited` pseudo-class in certain ways:

https://developer.mozilla.org/en-US/docs/Web/CSS/Privacy_and_the_:visited_selector

You're running into this one:

> If you use a sibling selector such as :visited + span, the adjacent element (span in this example) will be styled as if the link were unvisited.

Unfortunately nothing we can do about this one I'm afraid.
