### ISSUE TITLE
Some class doesn't work on Next.js App Router

### ISSUE THREAD

**Issue by minkyung00** [tailwindlabs/tailwindcss#11330]
**What version of Tailwind CSS are you using?**

- v3.3.2

**What build tool (or framework if it abstracts the build tool) are you using?**

- Next.js 13.4.1 (using App Router)

**What version of Node.js are you using?**

- v16.16.0

**What browser are you using?**

- Chrome

**What operating system are you using?**

- macOS

**Reproduction URL**

- https://github.com/minkyung00/next-chakra-tailwind

**Describe your issue**

> Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead.

### Some classes did not reflect: `flex` working while `mb-2` not working.

`mb-2` isn't working but `flex`, `items-center`, `justify-between` is working.
![](https://github.com/tailwindlabs/tailwindcss/assets/80238096/afa53c21-809f-4661-b505-7e963103cb22)

`mb-2` applies to class but not to css.
<img src="https://github.com/tailwindlabs/tailwindcss/assets/80238096/03c2d79f-f9b6-449a-a74d-c554cb02d78d" width="400px" />

```
"dependencies": {
    "@chakra-ui/react": "^2.7.0",
    "@emotion/react": "^11.11.0",
    "@emotion/styled": "^11.11.0",
    "@types/node": "20.2.5",
    "@types/react": "18.2.7",
    "@types/react-dom": "18.2.4",
    "autoprefixer": "10.4.14",
    "eslint": "8.41.0",
    "eslint-config-next": "13.4.4",
    "framer-motion": "^10.12.16",
    "next": "13.4.4",
    "postcss": "8.4.24",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "tailwindcss": "3.3.2",
    "typescript": "5.0.4"
  }
```

**Comment by wongjn** [comment]
It seems like the DOM for the code is in the `src/feature/domainName/components/LNB/LNB.tsx` file, but this is not covered by the `content` file globs in `tailwind.config.js`. Consider adding an entry for the file:

```diff
 module.exports = {
   content: [
     "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
     "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
     "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
+    "./src/feature/domainName/components/LNB/LNB.tsx",
   ],
   theme: {
```
This example is a very specific entry but feel free to broaden it if needed.
