### ISSUE TITLE
Why are there no group selectors?

### ISSUE THREAD

**Issue by MrOxMasTer** [tailwindlabs/tailwindcss#11360]
Why can't I write for example lg:{flex p-10} or lg:[flex p-10]. Why, for example, when compiling, just do not divide by lg:flex and lg:p-10.
In fact, as I see it, the only problem with tailwind is adaptive or others like hover, because it's inconvenient to prescribe it. Estimate if you will have:
min-[320px]:text-center and you need to prescribe for each. Yes, you can take it out somewhere, but damn. The very essence is that because of tailwind, classes are already huge, and prescribing md to everyone: it's just a waste of time and symbols.

damn, well, it can be thought out somehow. Why, for example, md:flex md:p-10 does not prescribe 2 media requests? Probably because it is somehow implemented under the hood. I think there are a lot of ideas to come up with here and I would really like this feature to be added and then tailwind would have no equal

**Comment by MrOxMasTer** [comment]
I believe this is the main problem of tailwind. Inconvenient adaptive and other Pseudo-classes and pseudo-elements.

**Comment by MrOxMasTer** [comment]
https://github.com/tailwindlabs/tailwindcss/discussions/2764

**Comment by MrOxMasTer** [comment]
Just make a convenient recording

**Comment by adamwathan** [comment]
Hey! Please use issues for bug reports, this is a topic better suited for our discussion forum 👍🏻
