### ISSUE TITLE
Group Class with prefix config doesn't work

### ISSUE THREAD

**Issue by vityapro** [tailwindlabs/tailwindcss#11384]
**What version of Tailwind CSS are you using?**

For example: v3.3.2

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: postcss-cli 8.3.1

**What version of Node.js are you using?**

For example: v14.5.0

**What operating system are you using?**

For example: Ubuntu

**Reproduction URL**
https://play.tailwindcss.com/cxSWYn1qBg

**Describe your issue**

Have issue with prefix config and group hover
`prefix: 'tw-'`

parent : group
children: group-[.class]:tw-hidden

**Comment by calvinagar** [comment]
I'm having this issue as well, except in my case I'm using custom variants as described [here](https://tailwindcss.com/docs/plugins#adding-variants).

`hocus` works just fine, but `group-hocus` does not work as described in the [docs](https://tailwindcss.com/docs/plugins#parent-and-sibling-states).

[Tailwind Play](https://play.tailwindcss.com/WD1EmAxaYa)

**Comment by thecrypticace** [comment]
@calvinagar The 2nd argument to addVariant is a selector or list of selectors.

What you want is to write this as:
```
addVariant('group-hocus', [':merge(.group):hover &', ':merge(.group):focus &'])
```

Here's a [Tailwind Play](https://play.tailwindcss.com/bqT9SUXxVW?file=config) of that working.

**Comment by calvinagar** [comment]
Works perfectly, thank you!

**Comment by stijn-code** [comment]
It doesn't work with named groups tho...

Example:
`group-hocus/body:bg-black`

**Comment by thecrypticace** [comment]
@Movsar-Khalakhoev Named groups use the `matchVariant` API — this is also available for you to use! Any variant can be defined with this API to gain support for modifiers (the thing that named groups and named peers use internally). There's nothing "special" in Tailwind CSS about using the `group` name or class in a variant that enables name/modifier support.

For your case the `group` variant includes support for custom selectors already — as an arbitrary value:

```html
<div class="group-[&[data-loading=true]]/foo:bg-red-500"></div>
```

However, if you want a more terse syntax (like `group-loading/foo`) you can use the `matchVariant` API to add a custom variant that also supports names:

```js
matchVariant(
  'group-loading',
  (_, { modifier }) => {
    return modifier
      ? `:merge(.group\\/${modifier})[data-loading=true] &`
      : `:merge(.group)[data-loading=true] &`
  },
 {
   // The `DEFAULT` value here lets you use group-loading/foo without an arbitrary value
   // Otherwise you'd always have to write it as group-loading-[something-here]/foo:bg-red-500
   values: { DEFAULT: null },
 }
)
```

Here's a [Tailwind Play](https://play.tailwindcss.com/93fENK5g6k) of this working.

**Comment by Movsar-Khalakhoev** [comment]
@thecrypticace Thank you for your help! This is exactly what I need!
