### ISSUE TITLE
space-x-* doesn't work with flex-row-reverse

### ISSUE THREAD

**Issue by ironyman** [tailwindlabs/tailwindcss#11392]
**What version of Tailwind CSS are you using?**

3.3.2

**What build tool (or framework if it abstracts the build tool) are you using?**

none

**What version of Node.js are you using?**

css issue

**What browser are you using?**

chrome

**What operating system are you using?**

windows

**Reproduction URL**
```
<div class="flex flex-row-reverse space-x-8">
<div id="divA"></div>
<div id="divB"></div>
</div>
```
**Describe your issue**

margin-left is non zero on divB but is not on divA. divA appears visually after divB so the margin-left should rather be on divA and not divB.

Visually you don't get the expected space between because the margin in the middle is 0 and there's margin on the left of the first div for no reason.

Same issue probably for flex-col-reverse and space-y-*.

e.g. adding flex-row-reverse to the docs example gives this result because of the same issue.
![image](https://github.com/tailwindlabs/tailwindcss/assets/502496/d3734ba1-a79c-4d45-b80e-906c3a023814)

**Comment by RobinMalfait** [comment]
Hey! Make sure you add the `space-x-reverse` class: https://tailwindcss.com/docs/space#reversing-children-order

**Comment by ironyman** [comment]
Oops I missed that from the docs. Thank you!
