### ISSUE TITLE
not support ie 11 or chrome version less then 88

### ISSUE THREAD

**Issue by DOCjx** [tailwindlabs/tailwindcss#11403]
**What version of Tailwind CSS are you using?**

v3.3.2

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.17, vue 2.7.1, vite 4.2.0

**What version of Node.js are you using?**

v14.19.2

**What browser are you using?**

Chrome 83

**What operating system are you using?**

macOS

**Reproduction URL**

open https://tailwindcss.com/docs/flex-wrap in chrome version less then 88 or other browser not support css selector [:is()], like ie 11

**Describe your issue**

any css will unuseable with the browser not support css selector [:is()]. see https://caniuse.com/?search=%3Ais. seems unuseable after Tailwind 3.3.0 commit (https://github.com/tailwindlabs/tailwindcss/pull/10835)

**Comment by adamwathan** [comment]
Hey! Yeah we don't support old browsers, can see more about our browser support approach here:

https://tailwindcss.com/docs/browser-support
