### ISSUE TITLE
VSCode parsing issue with @apply #{important}

### ISSUE THREAD

**Issue by riderx** [tailwindlabs/tailwindcss#11434]
**What version of Tailwind CSS are you using?**

For example: v2.0.4

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: postcss-cli 8.3.1, Nuxt.js 3.5.4

**What version of Node.js are you using?**

For example: v18.0.0

**What operating system are you using?**

macOS

**Reproduction URL**

https://stackblitz.com/edit/github-gdkixd-ptbywd

The issue is not visible in stackblitz but if you download the project and open with VSCode you should see the error as well

<img width="1027" alt="CleanShot 2023-06-15 at 19 30 30@2x" src="https://github.com/tailwindlabs/tailwindcss/assets/4084527/ea34e3d6-67bf-47a2-88f0-611ce41a24d4">

**Describe your issue**

sass display one error but all compile properly. I'm not sure here was the right place to post

**Comment by thecrypticace** [comment]
Hey! I did some poking around and this error looks to be displayed by the sass/scss support in VSCode itself and isn't specific to Vue, Tailwind, or any related extensions. Not sure there's much we can do about that unfortunately. Sorry!

**Comment by riderx** [comment]
We can report it to vscode then no ?
