### ISSUE TITLE
[Bug]: Example of Sticky Positioning Element Not Working in Tailwind Docs

### ISSUE THREAD

**Issue by Arindam200** [tailwindlabs/tailwindcss#11509]
## Description:
I noticed an issue with the example of the sticky positioning element in the Tailwind CSS documentation. The example provided is not functioning as expected. To demonstrate the problem, I have attached a video showcasing the issue.

## Environment:

Browser: Brave Browser (version: [Please specify version])
Tailwind CSS version: v3.3.2

## Steps to Reproduce:

1. Go to the documentation page containing the example for sticky positioning.
2. Observe that the sticky positioning element does not behave correctly.

## Expected Behavior:

The sticky positioning element should stick to the specified position on the page as the user scrolls.

## Actual Behavior:
The sticky positioning element does not stick to the specified position and behaves incorrectly when scrolling.

## Attached Files:

https://github.com/tailwindlabs/tailwindcss/assets/109217591/27b0b64f-2e2a-49ce-9da9-18902c0babe5

**Comment by Arindam200** [comment]
Thanks a lot!

**Comment by RobinMalfait** [comment]
Hey! I filed a bug based on this information and what I see in Chrome itself using the example on our documentation website. Link to the Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1459318

I'll keep an eye on it and report back when there is more information. Going to close this issue for now and will report back with more info!

**Comment by Arindam200** [comment]
Thanks a lot, Robin!

**Comment by RobinMalfait** [comment]
Hey! Small update, it looks like the issue on the Chromium side has been marked as fixed and I expect it to be available in the next versions. https://bugs.chromium.org/p/chromium/issues/detail?id=1459318#c10
