### ISSUE TITLE
Warning utility not generated, slow compile

### ISSUE THREAD

**Issue by bigskillet** [tailwindlabs/tailwindcss#11517]
Tailwind: 3.3.2
webpack: 5.88.1
postcss: 8.4.24
node: 20.2.0

https://github.com/bigskillet/webpack-tailwind-error

Running start or build via webpack, it stalls out at 37%, outputs the warning below, then eventually proceeds:

`The utility w-[calc(100%-theme('spacing[some_key][1.5]'))] contains an invalid theme value and was not generated.`

**Comment by wongjn** [comment]
Your `content` file glob, `./**/*.{html,js}` seems too broad and ends up covering code in `node_modules`. There are probably many, many files in `node_modules` and thus probably why Tailwind is slow to compile. The error would probably be coming from a Tailwind test, again in `node_modules` code. Consider narrowing your `content` file globs to *your* code, perhaps something like:

```diff
 module.exports = {
   content: [
-    './**/*.{html,js}'
+    './index.html',
+    './scripts/main.js',
   ],
```

**Comment by bigskillet** [comment]
Sorry about that. You are correct. Thanks for the quick response.
