### ISSUE TITLE
Tailwind CLI creates .css which violates MIT License

### ISSUE THREAD

**Issue by unsungNovelty** [tailwindlabs/tailwindcss#11536]
**What version of Tailwind CSS are you using?**

v3.3.2

**What build tool (or framework if it abstracts the build tool) are you using?**

- Tailwind CLI

**What version of Node.js are you using?**

- v18.6.1

**What browser are you using?**

- Firefox 114.0.2 (64-bit)

**What operating system are you using?**

- Arch Linux

**Reproduction URL**

- N/A

**Describe your issue**
While I was writing a blog post on open licenses, I accidentally found that creating a `style.css` using Tailwind CSS (and probably other build tool as well?) outputs a `.css` file which doesn't have MIT License and copyright notice which are the only requirements for MIT License. To be clear, this is NOT about the Tailwind CSS github repo lincense BUT the output `.css` file created while using Tailwind CSS. This means even if I manually add the MIT License text, every time I rebuild the `style.css`, it will be overwritten. This means I am violating the MIT license and so are other Tailwind CSS users without knowing. 

Currently, the `.css` which has only `/*! tailwindcss v3.3.2 | MIT License | https://tailwindcss.com*/` instead of the copyright notice MIT License text which are required. 
- Link to my site's CSS - https://www.unsungnovelty.org/style.9d0af9572f6003cb392754fdaf78fdc5b409376cb976da8afe1901d0107e4b08.css

>MIT License
>
>Copyright (c) Tailwind Labs, Inc.
>
>Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

> **The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.**

If you go to https://github.com/tailwindlabs/tailwindcss/blob/master/LICENSE, the conditions of the MIT License can be seen there as well.
![image](https://github.com/tailwindlabs/tailwindcss/assets/11845908/9105b55e-d0d6-4a1e-8aa8-5df26543f140)

I have had reported this previously on discord and [discussions](https://github.com/tailwindlabs/tailwindcss/discussions/11094) instead of opening a bug report. But it didn't catch any attention and I waited a few months in the hope someone would've caught it.

Could the required License and Copyright notice be included while building a `.css` file?

### Further reading
- https://drewdevault.com/2022/02/07/Free-software-licenses-MIT.html

**Comment by adamwathan** [comment]
Hey! Good question and not something I've thought terribly hard about — my instinct is that it's important to me that the license and copyright notice are included when making a copy or derivative of Tailwind CSS the tool (made up of files [like this one](https://github.com/tailwindlabs/tailwindcss/blob/master/src/corePlugins.js)), but that the generated CSS is generally yours, not ours.

There's a bit of a gray area here with things like [preflight](https://github.com/tailwindlabs/tailwindcss/blob/master/src/css/preflight.css) which is a considerable chunk of CSS code that becomes part of your project, but I'm not personally bothered by that.

Candidly it's not important to me that the generated CSS contains any mention of Tailwind or our license for legal purposes at all, we only add it there because it's a helpful way to tell when a site is using Tailwind and what version it's on, and not even for any particular data analysis reasons or anything, just because it's fun to celebrate when we see a cool new site that's built with Tailwind.

I checked a bunch of other CSS projects and everyone is just doing this exact same thing, so TL;DR just don't worry about it. If you're extremely nervous you can always prepend the license to the generated CSS yourself using a PostCSS plugin or something.

**Comment by unsungNovelty** [comment]
@adamwathan - Thanks for the quick response here. This has no legal implications to Tailwind CSS. But since the open licenses like MIT work under the copyright sphere, the moment end user is in violation of the license, they are using copyrighted content as promises guaranteed by the MIT license are legally void. This violation means _everyone_ using Tailwind CSS is probably in violation of MIT License unless they have put an extra bit of workaround for this. I was assuming the reason why you have included the text `/*! tailwindcss v3.3.2 | MIT License | https://tailwindcss.com*/` is for easier license compliance for the user, apart from your legal responsibilities of course.

> I checked a bunch of other CSS projects and everyone is just doing this exact same thing, so TL;DR

I looked at an old Bulma file and it is doing the same thing (unless the recent version have corrected it). And this seems to be incorrect way as you would've obviously seen as mentioned in the MIT License text - `The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software` part means the end user is in violation of Tailwind CSS's MIT license. This also means apart from the individual users like me, any businesses using Tailwind CSS is also  most likely to be in violation since we are rebuilding with tools like Tailwind CLI

 >  If you're extremely nervous you can always prepend the license to the generated CSS yourself using a PostCSS plugin or something.
 
 I am not nervous but like I mentioned, I was writing about open licenses when I stumbled up on it. In case my understanding is NOT wrong, adding compliance and copyright notice in the build file once in one place would solve this instead making thousands of people create a workaround.
 
 It would be super awesome if you could re-consider. 🙂

**Comment by mitar** [comment]
I am glad to read @adamwathan that the main reason for including the MIT header in CSS output is promotion and not really hinting that the CSS output itself is MIT licensed.

Generally, compiled output from compilers do not carry the license of the compiler itself. And often compilers do use some hand-crafted templates (e.g., mapping from C "if statement" to assembly code) when compiling code.

@adamwathan, I do think it would be better if this would be explicitly noted somewhere in documentation. That copyright holders of tailwindcss do not claim any copyright over the output from tailwindcss. You could even explicitly license the output as CC0. And the headers from tailwindcss should maybe be something like /*! created using tailwindcss v3.3.2 | https://tailwindcss.com*/ or something.

**Comment by MICHAELKITH** [comment]
good
