### ISSUE TITLE
[postcss] Cannot create property tailwind.config.js on string node-jiti (File: index.css)

### ISSUE THREAD

**Issue by talkohavy** [tailwindlabs/tailwindcss#11546]
**Tailwind**: v3.3.2
**Vite**: v4.3.9
**React**: v18.2.0
**Node**: v19.0.0
**Browser**: Chrome
**OS**: Windows
**pnpm**: V8.6.5
**Reproduction URL**: https://github.com/talkohavy/vite-tailwind-bug

## **Describing the issue**
All I did was simply create a new vite project, with react, and follow your documentation on how to add tailwind.
The steps being:
1. npm create vite@latest my-project -- --template react
2. cd my-project
3. code .
4. pnpm add -D tailwindcss postcss autoprefixer
5. npx tailwindcss init -p
6. add content to tailwind.config.js:
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
7. add to index.css these lines:
   @tailwind base;
   @tailwind components;
   @tailwind utilities;
8. run the command: npm run dev

After doing all that, when I run the start script of `npm run dev`, I open up the brower to see the app,
and get this error:

[plugin:vite:css] [postcss] **Cannot create property** '*******\my-project\tailwind.config.js' on string '*****/AppData/Local/Temp/node-jiti'

![1](https://github.com/tailwindlabs/tailwindcss/assets/51020442/d006d1f5-ec6b-4bb0-9c03-19e652991f17)

**Comment by bebetoalves** [comment]
Same here. Also, it looks like the documentation for Vite (whether react or vue) is out of date. I followed all the steps and tailwind just doesn't work.

**Comment by szmarczak** [comment]
https://github.com/unjs/jiti/issues/147#issuecomment-1620289214

**Comment by regzon** [comment]
@szmarczak 
Thanks! After `npm update` everything works fine.
