### ISSUE TITLE
Span's cannot be inline for group translate/transform modifiers to act as expected. (Note in the docs?)

### ISSUE THREAD

**Issue by atengberg** [tailwindlabs/tailwindcss#11541]
Maybe this is something already known well in web development about the default quality of inline elements such as span, but group-selector actions involving transforms will fail to work if the span is still set to inline. However, if the span's display is set to `block` (or it is the child of a container making it not inline, like a parent flex div) the transforms will work. 

I doubt this is a bug, but perhaps it should be explicitly noted in the docs just as a heads up to newer developers?

Here's a tailwindplay to demonstrate: https://play.tailwindcss.com/mR5rXnUQO4

**Comment by adamwathan** [comment]
Hey! Yeah this is just a CSS thing and is part of the spec. This is the first time it's been brought up here so going to hold off on adding any additional noise to the docs for now but if I hear from more people getting bit by this we can definitely throw something in there 👍
