### ISSUE TITLE
By adding style prefixes, dark mode conditions have no effect on styles.

### ISSUE THREAD

**Issue by jacktanxd** [tailwindlabs/tailwindcss#11555]
**What version of Tailwind CSS are you using?**

3.3.2

**What build tool (or framework if it abstracts the build tool) are you using?**
    
"postcss": "^8.4.14","vite": "^2.9.13"

**What version of Node.js are you using?**

node-v18.16.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Describe your issue**

In my project I am using the Quasar framework. To avoid style conflicts, I added the configuration prefix: "t-" in tailwind.config.js . But when I dynamically set the dark style class, the ”dark:“ condition has no effect on styles.

`document.documentElement.classList.add("dark");`

`<span class="t-absolute t-mt-2 t-text-2xl dark:t-text-red-500 t-text-green-500">test</span>`

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

If you add a prefix, then you also have to prefix the `dark` class itself:
```diff
- document.documentElement.classList.add("dark");
+ document.documentElement.classList.add("t-dark");
```

If you don't want this, then you can set a custom selector in your config to use the `dark` class:
```diff
/** @type {import('tailwindcss').Config} */
  module.exports = {
    prefix: 't-',
-   darkMode: 'class',
+   darkMode: ['class', '[class="dark"]'],
    theme: {
      extend: {
        // ...
      },
    },
    plugins: [],
  }
```

**Comment by RobinMalfait** [comment]
The `darkMode` using the `class` strategy should work with `t-dark`: https://play.tailwindcss.com/Sa9rT2xRsE (also check out the generated CSS). Note that only the `dark` class needs prefixing, not the variant. So you would still write `dark:t-underline`.

The reason it works with `xl:` is because it doesn't generate a class like `.xl` it uses a `@media` query instead.
