### ISSUE TITLE
Variables are sometimes used in tailwind and sometimes not.

### ISSUE THREAD

**Issue by kimmingyu1234756** [tailwindlabs/tailwindcss#11556]
**What version of Tailwind CSS are you using?**

v.3.2.7

**What build tool (or framework if it abstracts the build tool) are you using?**

"webpack-cli": "^5.0.1",
    "webpack-dev-server": "^4.12.0",
    "workbox-webpack-plugin": "^6.5.4"
"react": "^18.2.0",
"react-dom": "^18.2.0",
    "react-router-dom": "^6.9.0",

**What version of Node.js are you using?**

v16.15.1

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows10

**Describe your issue**

Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead.

```javascript


import React, { useState } from "react";
import { TableHeader } from "../commons/TableHeader";
import { TableCell } from "../commons/TableCell";


export const Table = () => {
  const [name, setName] = useState("");
  const [file, setFile] = useState("");
  const [state, setState] = useState("");
  const [content, setContent] = useState("");


  const [textareaList, setTextareaList] = useState<string[]>([
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ]);


  const [colNum, setColNum] = useState(0);


  const checkingGridcols = () => {
    if (colNum < 10) {
      const gridcols = [
        "grid-cols-1",
        "grid-cols-2",
        "grid-cols-3",
        "grid-cols-4",
        "grid-cols-5",
        "grid-cols-6",
        "grid-cols-7",
        "grid-cols-8",
        "grid-cols-9",
        "grid-cols-10",
        "grid-cols-11",
        "grid-cols-12",
      ];
      return gridcols[colNum];
    } else {
      alert("Don't increasing.");
      return "grid-cols-10";
    }
  };


  const testGridcols = () => {
    const gridcols = `grid-cols-${colNum}`;
    return gridcols;
  };
  const gridcols = `grid-cols-${colNum}`;


  const addTextarea = () => {
    setTextareaList([...textareaList, ...Array(colNum).fill("")]);
    // console.log(textareaList);
  };


  const addTextCol = () => {
    setColNum(colNum + 1);
    // let addTextareaList: string[] = [];
    // textareaList.map((row, index) => {
    //   if ((index + 1) % colNum === 0) {
    //     addTextareaList.push(row, "");
    //   } else {
    //     addTextareaList.push(row);
    //   }
    // });
    // // console.log(addTextareaList);
    console.log(colNum);
    // setTextareaList(addTextareaList);
  };


  return (
    <div className="flex">
      <div>
        <div>
          <TableHeader placeholder="name" />
          <TableHeader placeholder="file" />
          <TableHeader placeholder="status" />
          <TableHeader placeholder="etc" />
        </div>
        <div className={`grid ${testGridcols()}`}>
          {/* <div className={`grid grid-cols-${colNum}`}> */}
          {textareaList.map((textarea, index) => (
            // <div>{index}</div>
            <TableCell />
          ))}
        </div>
        <button className="w-full hover:bg-pinkgray" onClick={addTextarea}>
          ++
        </button>
      </div>
      <div>
        <button className="grid w-5 hover:bg-pinkgray" onClick={addTextCol}>
          +
        </button>
      </div>
    </div>
  );
};

```

I want to change `grid-cols-${variable}`. variable is useState.

But that's not working except function checkingGridcols in react.  

I tried to replace the variables by putting them into tailwind, but that's not the way tailwind works, so I thought I'd pre-create them as strings. 

  const testGridcols = () => {
    const gridcols = `grid-cols-${colNum}`;
    return gridcols;
  };

  const gridcols = `grid-cols-${colNum}`;

I've tried making them both functions and variables, but sometimes it works and sometimes it doesn't, so I'm confused.

What should I do?

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

This is happening because Tailwind is a build-time tool without a runtime and we don't evaluate your code. More info on this topic: https://tailwindcss.com/docs/content-configuration#dynamic-class-names

A solution you can use instead is to make use of CSS variables:
```js
<div class="grid-cols-[--cols]" style={{ '--cols': colNum }}></div>
```
This way the `grid-cols-[--cols]` is always found in the codebase and therefore Tailwind generates a class for it. Setting the value of `--cols` can happen dynamically at runtime.

Hope this helps!
