### ISSUE TITLE
Unable to Import Component Files After @tailwind Declaration

### ISSUE THREAD

**Issue by rizkimuhammada** [tailwindlabs/tailwindcss#11560]
**What version of Tailwind CSS are you using?**
^3.3.2

**What build tool (or framework if it abstracts the build tool) are you using?**
- postcss-import ^15.1.0
- vue ^3.3.4
- @vitejs/plugin-vue ^4.2.3
- autoprefixer ^10.4.14
- postcss ^8.4.25
- tailwindcss ^3.3.2
- vite ^4.4.0

**What version of Node.js are you using?**
v19.6.0

**What browser are you using?**
Chrome

**What operating system are you using?**
macOS

**Reproduction URL**
https://github.com/rizkimuhammada/rep

**Describe your issue**
I followed the step-by-step guide provided in the [Tailwind CSS documentation](https://tailwindcss.com/docs/guides/vite#vue) to set up Tailwind CSS with Vite and Vue. However, I encountered an issue while trying to import my component files after the @tailwind declaration.

To reproduce the issue, I followed these steps:

- Installed the "postcss-import" package using the command `npm install postcss-import`.
- Created a main file to import my component files, following the example given in the [Tailwind CSS documentation](https://tailwindcss.com/docs/using-with-preprocessors#build-time-imports).

Expected behavior: I expected to be able to import my component files successfully after the @tailwind declaration.

Actual behavior: Despite following the documentation example precisely, I found that the imports after the @tailwind declaration were not working as expected. I am unable to import my component files.

`12:05:55 AM [vite] Internal server error: [postcss] postcss-import: /Users/muhammadrizkia/Desktop/Projects/my-project/src/custom-components.css:1:1: `@layer components` is used but no matching `@tailwind components` directive is present.`

Please note that I have a basic understanding of Vue, Tailwind CSS, and using the command line interface. I believe this issue may be related to the order of imports or the configuration setup.

I would appreciate any guidance or assistance to resolve this issue. Let me know if you need any additional information.

**Comment by wongjn** [comment]
Could be a bug with Vite `v4.4.0`: vitejs/vite#13732.

**Comment by hunter-woodall** [comment]
Try changing 

```
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
 ```

to 

 ```
@tailwind base;
@tailwind components;
@tailwind utilities;
 ```

in your `style.css`
