### ISSUE TITLE
TailwindCSS drop-shadow property creates a new stacking context and overlaps elements with a z-index

### ISSUE THREAD

**Issue by DylandeBruijn** [tailwindlabs/tailwindcss#11599]
**What version of Tailwind CSS are you using?**

v3.3.2

**What build tool (or framework if it abstracts the build tool) are you using?**

Nuxt 3

**What version of Node.js are you using?**

v18.16.0

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows with WSL2

**Reproduction URL**

https://play.tailwindcss.com/B0c0nVZYRA

**Describe your issue**

The drop-shadow TailwindCSS class creates a new [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_context) because of the usage of filter(). 

In my project I have a card component with a drop-shadow. In this card component I have dropdown components and when they open another card component directly below them overlaps the dropdown menu.

<img width="479" alt="image" src="https://github.com/tailwindlabs/tailwindcss/assets/24457152/a42f9f5e-2dcc-4521-bd8a-201548b8bee3">

**Comment by adamwathan** [comment]
Hey! Yep this is just what CSS does, there's no way to use filters without creating a stacking context, that's just what happens. Nothing we can do to change this, we're just using CSS.

In your case though I would use a box-shadow not a drop-shadow — drop-shadow is only really needed for elements with odd shapes:

https://tailwindcss.com/docs/box-shadow

Just updated the docs for drop-shadow to make this more clear:

https://tailwindcss.com/docs/drop-shadow
