### ISSUE TITLE
CDN throw error "No utility classes were detected in your source files."

### ISSUE THREAD

**Issue by marianocodes** [tailwindlabs/tailwindcss#11608]
**What version of Tailwind CSS are you using?**

CDN - https://cdn.tailwindcss.com

**What build tool (or framework if it abstracts the build tool) are you using?**

Nuxt 2.17.0

**What version of Node.js are you using?**

V16.16

**What browser are you using?**

Chrome / Arc

**What operating system are you using?**

macOS

**Reproduction URL**

https://stackblitz.com/edit/nuxt-starter-drwk2h?file=nuxt.config.js

**Describe your issue**
Using the Tailwind through the CDN throws this warning "warn - No utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CSS configuration."

The config was set as it's documented. Warning sometimes disappears to repro, refresh the page a couple of times until it shows up

Tailwind config and CDN

<img width="884" alt="Screenshot 2023-07-13 at 5 12 54 PM" src="https://github.com/tailwindlabs/tailwindcss/assets/16544451/d97f6328-3df2-4a9d-b087-081d72eedb8c">

<img width="1474" alt="Screenshot 2023-07-13 at 5 07 17 PM" src="https://github.com/tailwindlabs/tailwindcss/assets/16544451/d7d91627-b7fd-4e78-8d5f-a434b36626fa">

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

Luckily this is just a warning and can happen if the JS runs before the DOM is ready. Everything should still work as expected (e.g.: the green text "Test" is using Tailwind CSS).

We'll remove the warning for the CDN.

**Comment by RobinMalfait** [comment]
This has now been solved, once the cache is purged you should not see any incorrect warnings anymore.

**Comment by marianocodes** [comment]
Wow! That was quick! Thanks @RobinMalfait!
