### ISSUE TITLE
Utilities do not work with prefix

### ISSUE THREAD

**Issue by michalbundyra** [tailwindlabs/tailwindcss#11656]
**What version of Tailwind CSS are you using?**

3.3.3

**What build tool (or framework if it abstracts the build tool) are you using?**

N/A

**What version of Node.js are you using?**

18.16.1

**What browser are you using?**

N/A

**What operating system are you using?**

N/A

**Reproduction URL**

https://play.tailwindcss.com/23jQdQle1e

**Describe your issue**

When setting prefix in the tailwindcss config utility classes are not working - in the example using `peer` and `group`, but I guess it will be the issue with other as well.

(in the example prefix is set to `tw-` so all classes and utilities are used with `tw-`, when you remove `tw-` and delete prefix in config all works as expected).

**Comment by wongjn** [comment]
Hi! Thank you for your report.

As [per the documentation](https://tailwindcss.com/docs/configuration#prefix):

> It’s important to understand that this prefix is added *after* any variant modifiers. That means that classes with responsive or state modifiers like `sm:` or `hover:` will still have the responsive or state modifier *first*, with your custom prefix appearing after the colon:
> ```html
> <div class="tw-text-lg md:tw-text-xl tw-bg-red-500 hover:tw-bg-blue-500">
>   
> </div>
> ```

How it should look in your example: https://play.tailwindcss.com/5AIRkPaqQH

**Comment by michalbundyra** [comment]
@wongjn I have completely missed that, tried different combinations but unfortunately not that 🤦‍♂️  thanks!
