### ISSUE TITLE
Mismatch of matchVariant type definition from implementation

### ISSUE THREAD

**Issue by agrobbin** [tailwindlabs/tailwindcss#11664]
Hi Tailwind maintainers! This is my first issue opened on the repo, so if there is anything I'm missing that would be helpful, let me know. I came across this while implementing a custom plugin that needed to walk the rules to find a particular declaration.

The implementation of `matchVariant` exposes `container` alongside `modifier`:

https://github.com/tailwindlabs/tailwindcss/blob/6eed8cb3f6e9673990d1773b8b0e2cf5f1b3a02e/src/lib/setupContextUtils.js#L591
https://github.com/tailwindlabs/tailwindcss/blob/6eed8cb3f6e9673990d1773b8b0e2cf5f1b3a02e/src/lib/setupContextUtils.js#L613-L620

However, the type definition does not include `container` in the callback function arguments:

https://github.com/tailwindlabs/tailwindcss/blob/6eed8cb3f6e9673990d1773b8b0e2cf5f1b3a02e/types/config.d.ts#L314-L324

That results in a mismatch when defining my config file with TypeScript.

**Comment by adamwathan** [comment]
Hey @agrobbin! This is intentional at the moment — we still support some of that container walking stuff for backwards compatibility with Tailwind CSS v2 variant plugins but are moving away from it and eventually plan to only support the declarative/string-based API in the future, which is why we've only included that API in the types. So it's considered deprecated right now which is why it's also not in the documentation.

If you'd like to keep using this API until it's removed of course you're welcome to do so, I'd just suggest using a `// @ts-ignore` or whatever to deal with the types.

Hope that helps!

**Comment by agrobbin** [comment]
Interesting, thanks for the detail @adamwathan! So far that's exactly what I have done (ignoring the TS warning), but if the current container walking behavior is deprecated, I am curious if you have some advice for how best to implement my current behavior in the "modern" way:

```typescript
const CUSTOMER_THEME_PROPERTIES = [
  'background-color',
  'color',
  'border-color',
  'border-left-color',
  'border-right-color',
  'border-top-color',
  'border-bottom-color',
  'fill',
  'stroke',
  '--tw-ring-color',
];

const declarationsRegex = new RegExp(CUSTOMER_THEME_PROPERTIES.join('|'), 'gi');

plugin(({ matchVariant }) => {
    matchVariant(
      'customer-theme',
      // @ts-expect-error -- `container` does not seem to be part of the `matchVariant` parameters type, but it is available
      (value, { container }) => {
        container.walkRules((rule: Rule) => {
          rule.walkDecls(declarationsRegex, (decl: Declaration) => {
            decl.value = `var(--customer-theme-${value}, ${decl.value})`;
          });
        });
      },
    );
  });
```

In the end, the goal is to create a modifier that takes the underlying value (e.g. the color for `border-sky-400`) and wrap it as a `var` fallback, where the CSS variable is defined if a customer has a custom theme. Without being able to walk the rules + declarations, I'm not sure how I would be able to accomplish something similar.

Any ideas would be appreciated!! Thanks in advance.
