### ISSUE TITLE
extending screens with raw fails max-* screens properties

### ISSUE THREAD

**Issue by yunuli** [tailwindlabs/tailwindcss#11698]
@RobinMalfait 
I've found why  max-* fails.  
overrides default only cause the missing key fails, like missing `'sm'` only make `'max-sm'` fails
it is by extending with `raw`, make all the max-* fails

```
module.exports = {
  theme: {
    extend: {
      screens: {
        tall: { raw: '(min-height: 800px)' },
        laptop: '1024px',
      },
    },
  },
  plugins: [],
}
```

_Originally posted by @yunuli in https://github.com/tailwindlabs/tailwindcss/discussions/11685#discussioncomment-6549278_

**Comment by thecrypticace** [comment]
Hey! This one is by design. Essentially, we can't handle automatic sorting and cannot handle inversion (to create the `max` variants) of the media query under these circumstances.

See https://github.com/tailwindlabs/tailwindcss/pull/9558#restrictions for a list of restrictions on when and how the min/max variants work.

**Comment by letehaha** [comment]
@thecrypticace I strongly believe that this kind of info should be described in the official documentation better. I just spent a few hours just to reach your comment. I also asked a bunch of people who actively using Tailwind and **no one** knew about these restrictions. That means it's not well-known by the common users. Can this https://github.com/tailwindlabs/tailwindcss/pull/9558#restrictions comment be added as a link to [Targeting a breakpoint range](https://tailwindcss.com/docs/responsive-design#targeting-a-breakpoint-range) section in the documentation? I can open a PR if that makes sense

**Comment by Elastoman** [comment]
I agree that this information should be added to the documentation. Took me hours to find out the hard way. Anyhow, keep up the good work and thx!
