### ISSUE TITLE
Typescript type for `presets` should allow config without `content` property

### ISSUE THREAD

**Issue by wimbarelds** [tailwindlabs/tailwindcss#11725]
**What version of Tailwind CSS are you using?**

3.3.2

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.3.1, Next.js 13.4.9, webpack 5.88.2

**What version of Node.js are you using?**

For example: v18.16.0

**What browser are you using?**

N/A

**What operating system are you using?**

vscode devcontainer from `mcr.microsoft.com/vscode/devcontainers/typescript-node:0-18-bullseye`

**Reproduction URL**

https://codesandbox.io/s/upbeat-engelbart-srwsmw?file=/src/tailwind.preset.ts

**Describe your issue**

`content` is required in preset, but preset configs sometimes/often/generally should not override the `content` property.

[edit] Updated the code-sandbox slightly to better illustrate the point.

The (js) example on the tailwind website does not have a `content` property.
https://tailwindcss.com/docs/presets

Currently the relevant typing is:
```ts
interface OptionalConfig {
  // ...
  presets: Partial<PresetsConfig>;
  // ...
}

type PresetsConfig = Config[];
```

Instead, I think it should be:

```ts
interface OptionalConfig {
  // ...
  presets: PresetsConfig;
  // ...
}

type PresetsConfig = Partial<Config>[];
```

(I assume the intent was to make array members partial, instead of making the array itself partial; as I cannot come up with any reason why the array itself should be partial/would benefit from being partial)

**Comment by RobinMalfait** [comment]
Hey, thank you for this bug report! 🙏

This should be fixed by #11730, and will be available in the next release.

You can try it by using the insiders build (which should be available within the next 10 minutes)
- `npm install tailwindcss@insiders`
