### ISSUE TITLE
Keep an eye on actions in CI workflows

### ISSUE THREAD

**Issue by szepeviktor** [tailwindlabs/tailwindcss#11809]
GHA says

> The following actions uses node12 which is deprecated and will be forced to run on node16: actions-rs/toolchain@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

Please consider enabling Dependabot for GitHub Actions. Once a week or once a month.
Here is the configuration.
https://github.com/szepeviktor/byte-level-care/blob/master/.github/dependabot.yml#L1-L10
Dependabot version updates can be enabled here.
https://github.com/tailwindlabs/tailwindcss/settings/security_analysis

From #11808

**Comment by reinink** [comment]
Hey! Thanks for this suggestion, we'll consider this for the future. At the moment we're not using Dependabot on this project — we're using Depfu. Definitely not a bad idea though, just not sure I want to enable a second bot for dependency alerts at this time.
