### ISSUE TITLE
actions-rs is not supported

### ISSUE THREAD

**Issue by szepeviktor** [tailwindlabs/tailwindcss#11811]
Let's remove `action-rs/*` actions!
https://github.com/actions-rs/toolchain/issues/216

Ubuntu images already contain up-to-date Rust tools.
https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#rust-tools

**Comment by reinink** [comment]
Hey thanks for the heads up, I've gone ahead and removed this dependency in #11826 👍

**Comment by szepeviktor** [comment]
You're welcome.
