### ISSUE TITLE
Erroneous lint warning applying scale-x and scale-y

### ISSUE THREAD

**Issue by codewizard-dt** [tailwindlabs/tailwindcss#11843]
**What version of Tailwind CSS are you using?**

tailwind v3.2.4
headless-ui 0.1.2

**What build tool (or framework if it abstracts the build tool) are you using?**

react-scripts 5.0.1

**What version of Node.js are you using?**

For example: v18.12.1

**What browser are you using?**

n/a (pre-compilation)

**What operating system are you using?**

MacOS

**Reproduction URL**

As this is a lint warning here is a screenshot instead of a URL
![Screen Shot 2023-08-17 at 11 57 16 AM](https://github.com/tailwindlabs/tailwindcss/assets/94571813/68b11700-2af6-4556-b5b1-83510c38c476)

**Describe your issue**

This is just one of those annoying bugs that doesn't really affect anything after compilation.  But anyway... applying `scale-x-<num>` and `scale-y-<num>` results in a linting warning that I cannot seem to disappear with eslint-disable or ts-ignore. 

Actual warning: `'scale-x-[1.01]' applies the same CSS properties as 'scale-y-105'.(cssConflict)`

**Comment by reinink** [comment]
Hey! This looks like it might be the exact same issue as https://github.com/tailwindlabs/tailwindcss-intellisense/issues/841, which was just fixed yesterday. Upgrading to `v0.9.13` of the Tailwind IntelliSense plugin should fix the issue — let me know if it doesn't 👍

**Comment by codewizard-dt** [comment]
WOW quickest issue resolution ever!  (It worked)
