### ISSUE TITLE
Tracking classes issue

### ISSUE THREAD

**Issue by marcosvzqz** [tailwindlabs/tailwindcss#11989]
**What version of Tailwind CSS are you using?**

For example: v3.3.3

**What build tool (or framework if it abstracts the build tool) are you using?**

Astro

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Describe your issue**

tracking-tighter
tracking-tight
classes should be positive (+) and are negative (-)

same with 
-tracking-tighter
-tracking-tight
classes should be negative (-) and are positive (+)

--and having -tracking-normal (-0em) is redundant to tracking-normal (0em)

**Comment by adamwathan** [comment]
Hey! Sounds like you figured out your issue so going to close this one.
