### ISSUE TITLE
Getting `The `-_indent-px` class does not exist` error when `prefix: '_'` is set in tailwind config

### ISSUE THREAD

**Issue by B2o5T** [tailwindlabs/tailwindcss#12033]
**What version of Tailwind CSS are you using?**

3.3.3

**What build tool (or framework if it abstracts the build tool) are you using?**

next.js

**What version of Node.js are you using?**

18

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/flTOSJ38xV?file=css

**Describe your issue**

it's totally valid start CSS class name with `-_`

```css
.-_foo {
  background: red;
}
```

<img width="226" alt="image" src="https://github.com/tailwindlabs/tailwindcss/assets/7361780/36a0ef52-ca71-49bf-820e-c56feb1a714a">
<img width="861" alt="image" src="https://github.com/tailwindlabs/tailwindcss/assets/7361780/25518e9f-ea99-4aa7-90cf-7b23c179e838">

**Comment by RobinMalfait** [comment]
Hey!

The prefix should be in front of the `-` sign. This means that you have to apply the following diff:
```diff
- -_mt-[100px]
+ _-mt-[100px]
```

Here is an updated Tailwind Play: https://play.tailwindcss.com/30TMsq9V2n?file=css

Hope this helps!
