### ISSUE TITLE
Compilation error for rule reusing important selector within a layer and using @apply

### ISSUE THREAD

**Issue by mwnciau** [tailwindlabs/tailwindcss#12110]
**What version of Tailwind CSS are you using?**

v3.3.3  
Reproduced on current play.tailwindcss.com version

**What build tool (or framework if it abstracts the build tool) are you using?**

vite v4.4.9  
postcss v8.4.29

**What version of Node.js are you using?**

v18.17.0

**What browser are you using?**

N/A

**What operating system are you using?**

Ubuntu

**Reproduction URL**

https://play.tailwindcss.com/xsicGQjVTh

**Describe your issue**

When using a selector in the `important` configuration option, adding a class using that same selector within a layer and using `@apply` causes a compilation error.

e.g.

```js
// config
{
  important: '.a-class',
}

// css
@layer base {
  .a-class {
    @apply font-bold;
  }
}
```

The crash seems to happen in [applyImportantSelector.js](https://github.com/tailwindlabs/tailwindcss/blob/d32228628ed45941a3ca1d2ca9d946d72c0d0cfa/src/util/applyImportantSelector.js#L10) because `sel.nodes` is an empty array, and it is assumed `sel.nodes[0]` is defined.

Either not using `@apply` or moving out of the `@layer` block makes this work as expected.

**Comment by thecrypticace** [comment]
This should be fixed by #12112, and will be available in the next release.

You can already try it by using the insiders build (usually takes around 15–20m to become available):
```
npm install tailwindcss@insiders
```
