### ISSUE TITLE
`group-hover` doesn't work not even when set in variants

### ISSUE THREAD

**Issue by martinsik** [tailwindlabs/tailwindcss#12134]
**What version of Tailwind CSS are you using?**

For example: v3.3.3

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: stackblitz.com

**What version of Node.js are you using?**

For example: stackblitz.com

**What browser are you using?**

For example: Chrome

**What operating system are you using?**

For example: macOS

**Reproduction URL**

https://stackblitz.com/edit/tailwindcss-bymruc?file=package.json

**Describe your issue**

The following HTML should make the text to change color to `red` when mouse hovering over it because its parent has class `group`:

```
<div class="group">
  <span class="text-blue-500 group-hover:text-red-500">ABC</span>
</div>
```

This should not require any config changes. However, hardcoding `variants: { textColor: ['group-hover'], }` into config.

**Comment by rodrigomata** [comment]
I opened your example and it's not working for me and I'm experiencing the same issue with v3.3.5, can you share what did you do to make it work?
