### ISSUE TITLE
minifying css files result in wrong order of classes

### ISSUE THREAD

**Issue by mymoto23** [tailwindlabs/tailwindcss#12152]
**What version of Tailwind CSS are you using?**

v3.3.3

**What build tool (or framework if it abstracts the build tool) are you using?**

Next.js v13.4.13

**What version of Node.js are you using?**

v16.14.2

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**
https://github.com/mymoto23/tailwindcss-minify-bug

**Describe your issue**
In the reproduction repo is a css file ([main.css](https://github.com/mymoto23/tailwindcss-minify-bug/blob/main/main.css)).

The [output.css](https://github.com/mymoto23/tailwindcss-minify-bug/blob/main/output.css) file is a result of running the following command:

`npx tailwindcss -o output.css main.css --minify`

Apparently in the process of minifying the css file,
tailwind groups classes with duplicate css properties.

For example:
the CSS
```
.Heading-20 {
	font-size: 16px;
	font-weight: 600;
	line-height: 22px;
	letter-spacing: -0.2px;

	@media screen and (min-width: 640px) {
		font-size: 20px;
		font-weight: 600;
		line-height: 28px;
		letter-spacing: -0.2px;
	}
}

.Heading-18 {
	font-size: 14px;
	font-weight: 600;
	line-height: 22px;
	letter-spacing: -0.2px;

	@media screen and (min-width: 640px) {
		font-size: 18px;
		font-weight: 600;
		line-height: 26px;
		letter-spacing: -0.2px;
	}
}
```

is minified into:

```
.Heading-20 {
	font-size: 16px;
	@media screen and (min-width: 640px) {
		font-size: 20px;
		line-height: 28px;
	}
}
.Heading-18,
.Heading-20 {
	font-weight: 600;
	line-height: 22px;
	letter-spacing: -0.2px;
	font-weight: 600;
	letter-spacing: -0.2px;
}
.Heading-18 {
	font-size: 14px;
	@media screen and (min-width: 640px) {
		font-size: 18px;
		line-height: 26px;
	}
}
```

The problem of this is that as the classes sharing the same property values are grouped and redeclared,
it's being placed AFTER the original class, which meddles with the [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) and results in an unintended behavior.

I believe that in the process of minifying css, original classes should always come after the grouped classes, as such:

```
.Heading-18,
.Heading-20 {
	font-weight: 600;
	line-height: 22px;
	letter-spacing: -0.2px;
	font-weight: 600;
	letter-spacing: -0.2px;
}
.Heading-20 {
	font-size: 16px;
	@media screen and (min-width: 640px) {
		font-size: 20px;
		line-height: 28px;
	}
}
.Heading-18 {
	font-size: 14px;
	@media screen and (min-width: 640px) {
		font-size: 18px;
		line-height: 26px;
	}
}
```

**Comment by thecrypticace** [comment]
Hey, this is because nesting support is not enabled by default in our CLI and it appears that cssnano does not understand nesting. In this case the solution is to enable nesting support by creating a postcss config, adding the `tailwindcss/nesting` plugin, and using the `--postcss` flag on the CLI to use the postcss config.

I've opened a PR on your reproduction showing how to do this. Hope that helps. ✨
