### ISSUE TITLE
WHY 2/4?

### ISSUE THREAD

**Issue by njfamirm** [tailwindlabs/tailwindcss#12168]
hi

https://github.com/tailwindlabs/tailwindcss/blob/5f00c18bd9c6035690a709938d582251bea62ffd/stubs/config.full.js#L270

Since my math is very good, I know that 1/2 is equal to 1/4, so why this class exits?

**Comment by thecrypticace** [comment]
Hey this is for consistency so we have 1/4, 2/4, and 3/4. 1/2 also exists in the config if you want to use it instead. It's easier to reason about using 1/4, 2/4, 3/4 rather than 1/4, 1/2, 3/4 when writing out widths in a grid system. It's the same reason we have 1/12, 2/12, 3/13, 4/12, etc…

**Comment by njfamirm** [comment]
ok thank you
