### ISSUE TITLE
Tailwind in large project results in JavaScript heap out of memory

### ISSUE THREAD

**Issue by newtriks** [tailwindlabs/tailwindcss#12167]
**What version of Tailwind CSS are you using?**

v3.3.3

**What build tool (or framework if it abstracts the build tool) are you using?**

vite v4.4.9

**What version of Node.js are you using?**

v18.18.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS 13.5.1

**Reproduction URL**

Requires a large project to reproduce

**Describe your issue**

We have a large monorepo project using pnpm workspaces. We have about 125 packages but most are relatively small. When introducing tailwind using the postcss setup documented on the website and adding regex to look through the packages in the `content` of the tailwind config, it breaks with error below.

I did consider adding an async function call using a library such as globby which is what we do for storybook, however, see @adamwathan discouraged this feature in the discussion [here](https://github.com/tailwindlabs/tailwindcss/discussions/11672).

```
<--- Last few GCs --->

[94974:0x7f78f714f000]   180372 ms: Mark-sweep (reduce) 3771.6 (3832.3) -> 3771.5 (3832.3) MB, 1343.6 / 0.0 ms  (average mu = 0.828, current mu = 0.000) last resort; GC in old space requested
[94974:0x7f78f714f000]   181651 ms: Mark-sweep (reduce) 3771.5 (3832.3) -> 3771.5 (3832.3) MB, 1279.0 / 0.0 ms  (average mu = 0.701, current mu = 0.000) last resort; GC in old space requested


<--- JS stacktrace --->

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0x108688045 node::Abort() [/Users/person/.nvm/versions/node/v18.18.0/bin/node]
 2: 0x108688225 node::OOMErrorHandler(char const*, bool) [/Users/person/.nvm/versions/node/v18.18.0/bin/node]
 3: 0x10880ccec v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/person/.nvm/versions/node/v18.18.0/bin/node]
 4: 0x1089c301f v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/person/.nvm/versions/node/v18.18.0/bin/node]
 5: 0x1089a471a v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/Users/person/.nvm/versions/node/v18.18.0/bin/node]
 6: 0x10899c554 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/Users/person/.nvm/versions/node/v18.18.0/bin/node]
 7: 0x108cc4c0e v8::internal::MaybeHandle<v8::internal::OrderedHashSet> v8::internal::OrderedHashTable<v8::internal::OrderedHashSet, 1>::Rehash<v8::internal::Isolate>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashSet>, int) [/Users/person/.nvm/versions/node/v18.18.0/bin/node]
 8: 0x108dc6c55 v8::internal::Runtime_SetGrow(int, unsigned long*, v8::internal::Isolate*) [/Users/person/.nvm/versions/node/v18.18.0/bin/node]
 9: 0x1091bcbf9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/person/.nvm/versions/node/v18.18.0/bin/node]
```

**Comment by newtriks** [comment]
> @newtriks I know this is a long shot but is there _any_ chance the repo is public or otherwise accessible in some way?

@thecrypticace sadly not. I debated opening a bug ticket for this based on the fact I couldn't share anything, sorry about that.

I have managed to get it running if I focus on a restricted area of the codebase e.g. less files within the content array, however, I haven't found the upper limit yet. I don't think it's monorepo specific either, I simply think it's a file max limit. I'll update things here if I find either the upper limit or something else specific to cause this issue in the meantime.

**Comment by thecrypticace** [comment]
@newtriks No worries at all. I'm going to close this one for now but if you're able to figure out what's going on or perhaps a way you can share a reproduction please @-mention me and I'll re-open this one and take a look. Unfortunately with scenarios like these it can be hard to triage what the actual problem might be without a reproduction.
