### ISSUE TITLE
Unable to change color based styles in nested divs

### ISSUE THREAD

**Issue by karansinghgit** [tailwindlabs/tailwindcss#12174]
**What version of Tailwind CSS are you using?**

3.3.3

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss-cli 8.4.29, Next.js 13.4.19 @nextui-org/react: ^2.1.13

**What version of Node.js are you using?**

v20.8.0

**What browser are you using?**

Chrome, Firefox

**What operating system are you using?**

macOS

**Reproduction URL**

minimal working repo on Github:
https://github.com/karansinghgit/dev-tools

**Describe your issue**

- `bg-color-xxx`, `border-xxx-xxx`,  or any other color based styles are not being applied to any element, while other styles such as `rounded-xx`, `w-x/y` etc. can be applied and take effect.
- this only seems to happen on pages which use a common layout.
Will give example files below from the repository above:

Scenario 1: Page with faulty behaviour:

- https://github.com/karansinghgit/dev-tools/blob/main/pages/posts/line-deduper.tsx
the above imports a layout, which is where I believe the problem lies.

any color styles imported within this layout don't work unless if they were already there at running the dev server (`npm run dev`).

- https://github.com/karansinghgit/dev-tools/blob/main/layouts/stt.tsx
this is the layout file where color based styles don't get updated on fast refresh.

Scenario 2: Page with correct behaviour:
If I just copy over the exact logic from STTLayout and embed it directly inside another page view, the styles seem to work and get updated normally:

https://github.com/karansinghgit/dev-tools/blob/main/pages/posts/line-deduper-v2.tsx (just a combination of the 2 files in the 1st scenario).

Please let me know how I can provide more details. I want to be able to use a common layout instead of replicating my logic everytime to a new file.

Thank you so much!

**Comment by RobinMalfait** [comment]
Hey!

This is happening because you are not scanning the `layouts` folder. You can update your `tailwind.config.js` file like this:

```diff
  import {nextui} from '@nextui-org/react'

  /** @type {import('tailwindcss').Config} */
  module.exports = {
    content: [
      './pages/**/*.{js,ts,jsx,tsx,mdx}',
      './components/**/*.{js,ts,jsx,tsx,mdx}',
      './app/**/*.{js,ts,jsx,tsx,mdx}',
+     './layouts/**/*.{js,ts,jsx,tsx,mdx}',
      './node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}'
    ],
    theme: {
      extend: {},
    },
    darkMode: "class",
    plugins: [nextui()],
  }
```

If you want, you can also combine those:
```diff
  import {nextui} from '@nextui-org/react'

  /** @type {import('tailwindcss').Config} */
  module.exports = {
    content: [
-     './pages/**/*.{js,ts,jsx,tsx,mdx}',
-     './components/**/*.{js,ts,jsx,tsx,mdx}',
-     './app/**/*.{js,ts,jsx,tsx,mdx}',
-     './layouts/**/*.{js,ts,jsx,tsx,mdx}',
+     './{pages,app,components,layouts}/**/*.{js,ts,jsx,tsx,mdx}',
      './node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}'
    ],
    theme: {
      extend: {},
    },
    darkMode: "class",
    plugins: [nextui()],
  }
```

Hope this helps!
