### ISSUE TITLE
Custom variant not "hiding" built-in variant of same name

### ISSUE THREAD

**Issue by AaronBeaudoin** [tailwindlabs/tailwindcss#12187]
**What version of Tailwind CSS are you using?**

v3.3.3

**What build tool (or framework if it abstracts the build tool) are you using?**

Nuxt v3.7.4

**What version of Node.js are you using?**

v18.18.0

**What browser are you using?**

Arc (Chrome)

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/pnRPGYgQu1

**Describe your issue**

When I make a plugin creating variants with the same names as built-in ones (my intention is to replace the built-in ones with me own—I'll explain why in a moment) the custom variant doesn't always seem to always hide the built-in one in the IDE suggestions. This can be seen even in the playground.

My use case is to replace all built-in hover-related variants. To avoid hover styles from being applied when tapping on touch-enabled devices, I run a tiny custom utility script which watches mouse and touch events and adds a `.hover` class to the root `<html>` element only when the user seems to be using a mouse.

So then, when using the `hover:` variant, what I need is `html.hover &:hover` instead of the default `&:hover`.

As you can see at the playground link above, I add this plugin to my config:

```js
plugin(({ addVariant }) => {
  addVariant("hover", "html.hover &:hover");
  addVariant("peer-hover", "html.hover .peer:hover ~ &");
  addVariant("group-hover", "html.hover .group:hover &");
})
```

But when I actually go to use the variant, I see this strange duplication:

<img width="489" alt="image" src="https://github.com/tailwindlabs/tailwindcss/assets/26592486/aa72c06c-70c6-48eb-84ba-214f04d20a64">

What's odd is that the `hover:` built-in variant has been properly "replaced" with my custom one, but for the other two the built-in variants have not been removed from the list, although it seems my custom one is still be properly applied in the final CSS regardless of which option I choose from the list. Still, it'd be nice if this were a little more tidy.

**Comment by thecrypticace** [comment]
Bug aside, I think the option `future.hoverOnlyWhenSupported` might prevent you from needing to add these variants. It wraps our hover variants in `hover: hover` and `pointer: fine` media queries.

Revised version of your Play example: https://play.tailwindcss.com/qo3pfnyZje

**Comment by AaronBeaudoin** [comment]
@thecrypticace Is that flag documented anywhere? I was not aware of it. In any case, this solution is still a bit inferior to a small JS helper because devices like touchscreen laptops which use both a mouse and touch as well will still always show hover styles even when tapping. See [this](https://stackoverflow.com/questions/23885255/how-to-remove-ignore-hover-css-style-on-touch-devices) SO question.

Implementation aside, it'd be nice to see this duplication fixed.

**Comment by thecrypticace** [comment]
You know, I'm not sure if it is other than on Github issues/PRs at the moment (well that and the typescript types). Good point about the dual touch screen + pointer — sadly I don't think that can be detected reliably in CSS alone so a JS helper can make sense there.

And yeah I'm looking into the duplication 👍

**Comment by thecrypticace** [comment]
I figured out the source of the problem in intellisense itself. I'll publish a new version of the extension on Monday most likely. Gotta get Play updated too.
