### ISSUE TITLE
Nesting plugin type error

### ISSUE THREAD

**Issue by lxxorz** [tailwindlabs/tailwindcss#12216]
**What version of Tailwind CSS are you using?**

v3.3.3

**What build tool (or framework if it abstracts the build tool) are you using?**

vite v4.4.11

**What version of Node.js are you using?**

v18.18.0

**What browser are you using?**

Chrome

**What operating system are you using?**

ubuntu 22.04(wsl)

**Reproduction URL**
https://stackblitz.com/edit/vitejs-vite-fnvtrj?file=vite.config.ts

**Describe your issue**
I encounter a type error ('Could not find a declaration file for module 'tailwindcss/nesting'.') when I import the nesting plugin in vite.config.ts.

![image](https://github.com/tailwindlabs/tailwindcss/assets/39158330/93021ff8-2e02-4cc2-8034-283863601a5a)

**Comment by thecrypticace** [comment]
Thanks for pointing this out — I've added the types in #12269 which will be in our next release. It'll be available in our insiders build in about 15 minutes or so:
```
npm install tailwindcss@insiders
```
