### ISSUE TITLE
Add `leading-inherit` / `leading-reset` class to help with WCAG requirement that allows users to increase `line-height`

### ISSUE THREAD

**Issue by jsdev** [tailwindlabs/tailwindcss#12239]
**What version of Tailwind CSS are you using?**

3.3.3

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss-cli 8.3.1, Next.js 10.0.9, webpack 5.28.0

**What version of Node.js are you using?**

 v12.0.0 - LTS

**What browser are you using?**

All browsers

**What operating system are you using?**

All Os, Linux, Windows, Mac

**Reproduction URL**

https://codepen.io/jsdev/pen/mdaZZaB

**Describe your issue**

There is currently no way to set text-sm and opt-out of the line-height injection. For Accessibility issue that allows users to increase line height with their own custom stylesheet / assistive technology, tailwindcss developers need to be able to leading-reset to make line-height: inherit, currently leading-normal sets to 1.5 and leading-none sets to 1, nothing sets to inherit, so suggesting a leading-reset or leading-inherit class name added
![example of leading-reset needed](https://github.com/tailwindlabs/tailwindcss/assets/1638860/d8d08355-8328-48ff-99e4-49074587ffca)

**Comment by jsdev** [comment]
this is the WCAG that is currently flagging TailwindCss only development teams
https://www.w3.org/WAI/WCAG21/Understanding/text-spacing.html

**Comment by thecrypticace** [comment]
Hey so you can do this today in your own projects by using arbitrary values, arbitrary modifiers, or by adding a key to your config. Basically, your example of `text-sm leading-reset` can be written today as `text-sm leading-[inherit]`.

I've prepared an example Tailwind Play for you:
https://play.tailwindcss.com/LHXKXcKml0

**Comment by thecrypticace** [comment]
Hey, I'm gonna close this one since you _can_ actually do this today by any of the 4 methods mentioned above / in the Tailwind Play link.

**Comment by jsdev** [comment]
@thecrypticace thanks for the fast response. This was a great example of how to "opt in" to better accessibility

You may want to consider making the class in there at default at some point as developers are starting to weigh 508 more than ever before when choosing a design system now.
