### ISSUE TITLE
Calculated (ie. calc) Value for max-w- Not Generating Corresponding Style

### ISSUE THREAD

**Issue by machineghost** [tailwindlabs/tailwindcss#12242]
**What version of Tailwind CSS are you using?**

    "tailwindcss": "^3",

**What build tool (or framework if it abstracts the build tool) are you using?**

    "next": "13.5.5",

**What version of Node.js are you using?**

v20.3.0

**What browser are you using?**

Chrome

**What operating system are you using?**

Linux

**Reproduction URL**

https://play.tailwindcss.com/7aEeVivkD9 ... but it's literally one line:

    <hr class="max-w-[calc(100% - 460px)]"  />

If you inspect the generated `hr` element, you'll see it lacks a generated `max-width` style.

**Describe your issue**

As I understand it, I should be able to `max-w-[X]`, where `X` is a valid CSS value for `max-width`.

However, although `calc(100% - 460px)` *is* a valid value, it doesn't work in Tailwind. When used in a `max-w-` class the element does not get the corresponding style (of `max-width: calc(100% - 460px)`).

**Comment by adamwathan** [comment]
Hey! Just gotta remove the spaces:

https://play.tailwindcss.com/qxxBH4cWi6

<img width="679" alt="image" src="https://github.com/tailwindlabs/tailwindcss/assets/4323180/fbd53e47-4927-4d82-8875-b56150dd0988">

In your example you actually had three different classes — `max-w-[calc(100%`, `-`, and `460px)]`. Spaces are how the browser separates things into different classes.

**Comment by machineghost** [comment]
Ah, that makes complete sense, thanks.
