### ISSUE TITLE
important:true is making 10x slower (sometimes more)

### ISSUE THREAD

**Issue by hanoii** [tailwindlabs/tailwindcss#12284]
**What version of Tailwind CSS are you using?**
3.3.4

**What build tool (or framework if it abstracts the build tool) are you using?**

The whole project is using laravel mix, but I've testing this out only with the tailwindcss cli.

**What version of Node.js are you using?**

Latest 18

**What browser are you using?**

N/A

**What operating system are you using?**

macOS, but this is tested inside a linux container using ddev

**Reproduction URL**

Not sure what to provide here, it's a compile time issue/question.

**Describe your issue**

I was experiencing a very slow build time and I set out to find what was causing it as it's really not a huge project and not at all the times I am used to with other projects I am using tailwind on. It has quite a few configuration and extensions but I narrowed it down to two things, but one of those is the `important:true` config.

Some figures (and the output is a ~900 lines css) without `important:true` it's taking ~2s, with `important: true` ~10s. This geets a lot more noticeable when I start adding back everything I need from the tailwind.conf.js. I find it very odd that just adding !important to every class makes that much of a difference so I'd thought of flagging this.

**Comment by thecrypticace** [comment]
Can you provide a link to a repo on GitHub?

**Comment by hanoii** [comment]
In creating such a repo I am now failing to reproduce this. I spent a few hours this morning where this was pretty evident but now I can't reproduce it 🤷 . I will come back to this, if not I will close it.

**Comment by thecrypticace** [comment]
Okay, no worries. I'm gonna go ahead and close this but if you are able to reproduce it then go ahead and mention it here and @-mention me and I'll take a look. Thanks!
