### ISSUE TITLE
Nesting tailwind directives generates responsive variants outside scope

### ISSUE THREAD

**Issue by fredericoo** [tailwindlabs/tailwindcss#12326]
**What version of Tailwind CSS are you using?**

v3.3.5

**What build tool (or framework if it abstracts the build tool) are you using?**

`tsup` running `postcss`

**What version of Node.js are you using?**

v18.16.0

**What browser are you using?**

N/A

**What operating system are you using?**

macOS

**Reproduction URL**

I’ve committed `/dist` so you can see the issue:
https://github.com/fredericoo/tailwind-repro/blob/main/dist/index.css#L112

**Describe your issue**

Adding tailwind directives under a selector works fine (e.g.: ```#test { @tailwind base; }``` except all the responsive variants are not correctly scoped — i.e.: they’re generated outside of the parent selector.

I’m using a parent selector to isolate my tailwind classes as part of a widget that may be installed on 3rd parties. (yes I know you can add a prefix, but holy hell prefixing every class name is dreadful)

**Comment by thecrypticace** [comment]
The automatic placement of the variants layer is always at the root. If you need to change it you'll need to explicitly use `@tailwind variants` in your CSS.

For example:

```css
#parent {
    @tailwind base;
    @tailwind components;
    @tailwind utilities;
    @tailwind variants;
}
```
