### ISSUE TITLE
`/` is not allowed in arbitrary modifier

### ISSUE THREAD

**Issue by ArnaudBarre** [tailwindlabs/tailwindcss#12362]
Version: 3.3.5
Repro: https://play.tailwindcss.com/yLjHBexR1d

Not really something I wrote in real life, just something I though of when testing edge cases of my own implementation.
So could be considered as not supported, this is issue is just to let you know. Feel free to close!

**Comment by thecrypticace** [comment]
Hey I've merged the fix for this in #12515 and it'll be available in our next release.

It'll also be available via our insiders build in about 15 minutes:
```
npm install tailwindcss@insiders
```
