### ISSUE TITLE
Array with comma separated arbitrary value classes in JS does not generate as expected

### ISSUE THREAD

**Issue by Oskar-Nilsen-Roos** [tailwindlabs/tailwindcss#12371]
**What version of Tailwind CSS are you using?**

v3.3.5

**What build tool (or framework if it abstracts the build tool) are you using?**

--

**What version of Node.js are you using?**

--

**What browser are you using?**

N/A

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/X5qTU0S68S

**Describe your issue**

Check generated css > utilities in playground link.

Tailwind play link is simplification for a weird issue I ran into when bundling a component library, where I generate styles by looking at the JS files in the project that consumed the library.

When minified, spaces from arrays are removed. e.g.:

```
["min-w-[17rem]", "max-w-[17rem]"]
```

turns into

```
["min-w-[17rem]","max-w-[17rem]"]
```

Example 1 works as expected, while example 2 does not generate both arbitrary value styles, only the first.

Is this intended behaviour? And is there any way for me to work around it?

Thank you!

**Comment by RobinMalfait** [comment]
This should be fixed by #12396, and will be available in the next release.

You can already try it by using the insiders build `npm install tailwindcss@insiders`.
