### ISSUE TITLE
Website down. Cloudflare SSL handshake error

### ISSUE THREAD

**Issue by corysimmons** [tailwindlabs/tailwindcss#12373]
![image](https://github.com/tailwindlabs/tailwindcss/assets/224636/2d3bcee5-a7de-41d5-aea7-42bc76db8bc0)

I'm not sure if this is something from the Cloudflare outage a day or so ago, but the site is currently down. Just figured I'd open a ticket in case no one has noticed.

**Comment by RomanHrynevych** [comment]
Everything work fine, double check please 🙂 

<img width="1728" alt="image" src="https://github.com/tailwindlabs/tailwindcss/assets/82209198/c47f059d-e386-4ee7-b332-d82a5b29a469">

**Comment by corysimmons** [comment]
haha, now it works. 🖖
