### ISSUE TITLE
Missing `appearance-none`

### ISSUE THREAD

**Issue by quick007** [tailwindlabs/tailwindcss#12401]
**What version of Tailwind CSS are you using?**

3.3.5

**What build tool (or framework if it abstracts the build tool) are you using?**

CLI

**What version of Node.js are you using?**

18.2.1

**What browser are you using?**

For example: Chrome, Safari, or N/A

**What operating system are you using?**

Windows

**Reproduction URL**

https://play.tailwindcss.com/PxecKTGWVQ

**Describe your issue**

I'm categorizing this as a bug because Tailwind wants to have "modified" value (i.e. none) and a default value (auto) that can be used with hover for example. I believe it's on their docs somewhere but I couldn't find it In this case, there is the modified value (`appearance-none`) but not the default value (theoretically called `appearance-auto`). It's obviously quite trivial to do this via arbitrary values, but I also believe that it's a bug in Tailwind that should be fixed.

**Comment by adamwathan** [comment]
Added here, thanks! 
https://github.com/tailwindlabs/tailwindcss/pull/12404
