### ISSUE TITLE
JavaScript heap out of memory issue on large monorepos codebase

### ISSUE THREAD

**Issue by newtriks** [tailwindlabs/tailwindcss#12433]
**What version of Tailwind CSS are you using?**

v3.3.3

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss-cli 8.4.31, react 17.0.2, vite 4.4.9

**What version of Node.js are you using?**

v16.14.2

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

Sorry large scale internal project, hard to replicate with an example and unable to share.

**Describe your issue**

We've a large codebase harnessing pnpm workspaces edging just over 100 packages in total. Defined the packages in the tailwind config `content` results in the browser hanging and heap out of memory errors. The only way we can get it to work is to dramatically reduce the scope within the content array to a smaller subset of packages.

```
<--- Last few GCs --->

[37134:0x7feae2900000]  9949912 ms: Mark-sweep 4042.3 (4131.2) -> 4026.5 (4131.4) MB, 621.4 / 0.0 ms  (average mu = 0.309, current mu = 0.377) allocation failure scavenge might not succeed
[37134:0x7feae2900000]  9950836 ms: Mark-sweep 4042.5 (4131.4) -> 4026.8 (4131.7) MB, 847.8 / 0.0 ms  (average mu = 0.203, current mu = 0.083) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x110938a25 node::Abort() (.cold.1) [/Users/me/.nvm/versions/node/v16.14.2/bin/node]
 2: 0x10f62e0f9 node::Abort() [/Users/me/.nvm/versions/node/v16.14.2/bin/node]
 3: 0x10f62e26f node::OnFatalError(char const*, char const*) [/Users/me/.nvm/versions/node/v16.14.2/bin/node]
 4: 0x10f7af7e7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/me/.nvm/versions/node/v16.14.2/bin/node]
 5: 0x10f7af783 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/me/.nvm/versions/node/v16.14.2/bin/node]
 6: 0x10f950e65 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/me/.nvm/versions/node/v16.14.2/bin/node]
 7: 0x10f954ead v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/Users/me/.nvm/versions/node/v16.14.2/bin/node]
 8: 0x10f95178d v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/me/.nvm/versions/node/v16.14.2/bin/node]
 9: 0x10f94ecad v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/me/.nvm/versions/node/v16.14.2/bin/node]
10: 0x10f95c090 v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/me/.nvm/versions/node/v16.14.2/bin/node]
11: 0x10f95c111 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/me/.nvm/versions/node/v16.14.2/bin/node]
12: 0x10f9291a7 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/Users/me/.nvm/versions/node/v16.14.2/bin/node]
13: 0x10fce0dae v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/Users/me/.nvm/versions/node/v16.14.2/bin/node]
14: 0x11008a879 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/me/.nvm/versions/node/v16.14.2/bin/node]
15: 0x11001cecd Builtins_StringSubstring [/Users/me/.nvm/versions/node/v16.14.2/bin/node]
16: 0x1149ce58f 
```

**Comment by mominshaikhdevs** [comment]
I guess this is not an issue with tailwindcss itself and therefore it can be closed.

**Comment by thecrypticace** [comment]
Yeah, unfortunately without something we can use to reproduce this is unlikely to be something we can even look into. I imagine what's happening is we're scanning a some files that:
- Are either collectively large enough that Node runs out of memory reading them
- The file produces enough "candidates" (our word for something that looks like it could be a utility class) that Node runs out of memory

This could very well happen if your content list includes node_modules and also doesn't limit the scope of what files are being read.

In cases like this I'd suggest changing your content array to be a lot more limited in the files, directories, and file extensions its reading. And, as mentioned above, if for some reason that's isn't sufficient I'd recommend using NODE_OPTIONS like above to increase the memory limit.

Something else you can do is upgrade your Node version as later versions of Node do better reading in `utf-8` in a way that is quicker and likely uses less memory.

**Comment by xantari** [comment]
Similar issue, but using watch, which works for awhile then ultimately has some sort of memory leak I suspect and crashes

> npx tailwindcss -i wwwroot/css/app.css -o wwwroot/css/appbundle.css --watch


Rebuilding...
Done in 5930ms.
Rebuilding...
Done in 361ms.
Rebuilding...
Done in 491ms.
Rebuilding...
Done in 527ms.
Rebuilding...
Done in 951ms.
Rebuilding...
Done in 783ms.
Rebuilding...
Done in 855ms.
Rebuilding...
Done in 832ms.
Rebuilding...
Done in 942ms.
Rebuilding...
Done in 1039ms.
Rebuilding...
Done in 1511ms.
Rebuilding...
Done in 1235ms.
Rebuilding...
Done in 1292ms.
Rebuilding...
Done in 1978ms.
Rebuilding...
Done in 1610ms.
Rebuilding...
Done in 2052ms.
Rebuilding...
Done in 2402ms.
Rebuilding...
Done in 2059ms.

<--- Last few GCs --->

[36228:000001BDB1820080]  8234176 ms: Mark-Compact 4051.5 (4138.6) -> 4040.2 (4143.1) MB, 1462.72 / 0.00 ms  (average mu = 0.805, current mu = 0.108) allocation failure; scavenge might not succeed
[36228:000001BDB1820080]  8236765 ms: Mark-Compact 4056.0 (4143.1) -> 4043.8 (4146.6) MB, 2558.07 / 0.00 ms  (average mu = 0.573, current mu = 0.012) allocation failure; scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 00007FF6A7BA72EB node::SetCppgcReference+18123
 2: 00007FF6A7B18F04 DSA_meth_get_flags+90724
 3: 00007FF6A8590701 v8::Isolate::ReportExternalAllocationLimitReached+65
 4: 00007FF6A8579E58 v8::Function::Experimental_IsNopFunction+1336
 5: 00007FF6A83DB8A0 v8::Platform::SystemClockTimeMillis+659328
 6: 00007FF6A83D8928 v8::Platform::SystemClockTimeMillis+647176
 7: 00007FF6A83EDC3A v8::Platform::SystemClockTimeMillis+733978
 8: 00007FF6A83EE4B7 v8::Platform::SystemClockTimeMillis+736151
 9: 00007FF6A83FCDAF v8::Platform::SystemClockTimeMillis+795791
10: 00007FF6A80BCD05 v8::CodeEvent::GetFunctionName+116773
11: 00007FF6A864208E v8::PropertyDescriptor::writable+678094
12: 00007FF6A85B31F8 v8::PropertyDescriptor::writable+92728
13: 00007FF6288B6287

**Comment by Tiodaspizza** [comment]
I have the same problem. Did you find a solution?

**Comment by ssternal** [comment]
Even I don't like necro-posting old threads, the following hint helped me solving the issue in my case:

> This could very well happen if your content list includes node_modules and also doesn't limit the scope of what files are being read.

The pipeline builds worked out, but local development died even when allowing 16 GB RAM during build. Since our libraries are linked locally during development, the tailwind pattern included the node_modules folders of the linked libraries leading to extremely large amount of files. Narrowing the file search pattern solved the issue.

```javascript
module.exports = {
    content: [
        './node_modules/@my_kewl_company/*/{src,dist}/**/*.{js,jsx,ts,tsx}',
    ],
};
```
