### ISSUE TITLE
[Bug]: Configuring and using custom prefix i.e. "tw-" breaks the mediaquery based classes

### ISSUE THREAD

**Issue by mrfzd** [tailwindlabs/tailwindcss#12441]
**What version of Tailwind CSS are you using?**

v3.3.3

But it also breaks in Tailwind's own playground, please see https://play.tailwindcss.com/Qun0aQUlRp (doesn't work)

Non-prefix version: https://play.tailwindcss.com/Fbg2nEKWiG (it works)

**Describe your issue**

Basically when defining a prefix in config file, in our case 'tw-', it then breaks the entire mediaquery based utility classes such as tw-md:*

However, when this prefix is removed from the config and class names are changed back to non-prefix classes such as md:* then things start working again!

**Comment by wongjn** [comment]
Hi! Thank you for your report! So as per [the documentation](https://tailwindcss.com/docs/configuration#prefix):

> It’s important to understand that this prefix is added *after* any variant modifiers. That means that classes with responsive or state modifiers like `sm:` or `hover:` will still have the responsive or state modifier first, with your custom prefix appearing after the colon:
>
> ```html
> <div class="tw-text-lg md:tw-text-xl tw-bg-red-500 hover:tw-bg-blue-500">
>   
> </div>
> ```

Hence for your example, the class should be `md:tw-flex`, not `tw-md:flex`: https://play.tailwindcss.com/3dk8AuKhBn

**Comment by mrfzd** [comment]
> Hi! Thank you for your report! So as per [the documentation](https://tailwindcss.com/docs/configuration#prefix):
> 
> > It’s important to understand that this prefix is added _after_ any variant modifiers. That means that classes with responsive or state modifiers like `sm:` or `hover:` will still have the responsive or state modifier first, with your custom prefix appearing after the colon:
> > ```
> > <div class="tw-text-lg md:tw-text-xl tw-bg-red-500 hover:tw-bg-blue-500">
> >   
> > </div>
> > ```
> 
> Hence for your example, the class should be `md:tw-flex`, not `tw-md:flex`: https://play.tailwindcss.com/3dk8AuKhBn

Oh I see!
Thanks for your prompt reply and help, appreciate that! 🙏
