### ISSUE TITLE
Sorting 'dark' variants only works when 'darkMode': 'class'

### ISSUE THREAD

**Issue by CHE1RON** [tailwindlabs/tailwindcss#12615]
The title already says it: 

Whenever `class` is not present in `darkMode` config option, TailwindCSS prettier plugin sorts `dark:` variants to the frontend (= it then considers them 'custom' / 'non-Tailwind' classes). 

This obviously conflicts for people using `data-` attributes to indicate 'darkMode' being on/off.

**Comment by adamwathan** [comment]
Hey! Can you share some sort of reproduction that demonstrates the actual problem you're experiencing?

Looks to me like configuring dark mode to use data attributes works as expected and [as documented](https://tailwindcss.com/docs/dark-mode#customizing-the-class-name):

https://play.tailwindcss.com/Qg9EYycJfF?file=config

**Comment by CHE1RON** [comment]
It just occured to me when palying with your demo that `'class'` has to be there (and the IDE tells you, so you would have to be dumb like me to disable it for a config file so you don't notice 😅)

Cheers - and keep up the great work, really love TailwindCSS
