### ISSUE TITLE
important modifier on animation breaks keyframes

### ISSUE THREAD

**Issue by philippkuehn** [tailwindlabs/tailwindcss#12623]
**What version of Tailwind CSS are you using?**

v3.4.0

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.32

**What version of Node.js are you using?**

v21.4.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/4mir5NtQdV

**Describe your issue**

If you use the !important modifier for animations, the keyframe steps of the animation are removed (and the animation breaks). You can also see this in tailwind intellisense.

![CleanShot 2023-12-19 at 23 02 29@2x](https://github.com/tailwindlabs/tailwindcss/assets/2500670/f2079572-00a0-4825-a79f-2e4d7015eeed)

**Comment by thecrypticace** [comment]
Hey thanks for reporting this. I've merged the fix in #12639 and it'll be available in the next release.

It'll also be in our insiders build in about 15 minutes or so:
```
npm install tailwindcss@insiders
```
