### ISSUE TITLE
React examples are broken

### ISSUE THREAD

**Issue by anshul-kai** [tailwindlabs/tailwindcss#12659]
**What version of Tailwind CSS are you using?**
3.3.5

**What build tool (or framework if it abstracts the build tool) are you using?**
Next.js 14

**What version of Node.js are you using?**
v18.19.0

**What browser are you using?**
Chrome

**What operating system are you using?**
macOS

**Describe your issue**
Example code for React isn't copy/paste friendly. So far I've noticed two issues:
1. class tags need to be renamed to classNames
2. closing tags are sometimes missing

I love this project and the work done here and am m happy to create a PR if it would help.

Cheers!

**Comment by adamwathan** [comment]
Hey! What example code?

**Comment by anshul-kai** [comment]
I must have been exhausted and copying the HTML code instead of React. I can't seem to find the issue today. My sincere apologies!
