### ISSUE TITLE
'-webkit-text-size-adjust' is not supported

### ISSUE THREAD

**Issue by Siddhesh-Agarwal** [tailwindlabs/tailwindcss#12650]
'`-webkit-text-size-adjust`' is not supported by Chrome, Chrome Android, Edge 79+, Firefox, Safari, and Samsung Internet. Add '`text-size-adjust`' to support Chrome 54+, Chrome Android 54+, Edge 79+, Samsung Internet 6.0+.

**Source**: https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust/

**Comment by adamwathan** [comment]
Hey! `text-size-adjust` is not supported by Firefox or Safari, but all browsers (including Firefox and Safari) support `-webkit-text-size-adjust`.

This is from Firefox:

<img width="352" alt="image" src="https://github.com/tailwindlabs/tailwindcss/assets/4323180/0d10162b-75e0-4b1f-9cd6-c41d63e3ae40">

No plans to change anything here.

**Comment by areriklq** [comment]
@adamwathan I am seeing this warning (localhost) in both Firefox and Edge (Chromium):
![image](https://github.com/tailwindlabs/tailwindcss/assets/156663890/e51c0907-0397-4c6b-898a-c92d9bf07738)
![image](https://github.com/tailwindlabs/tailwindcss/assets/156663890/ae0d6cc6-e8cb-414d-bfc3-844307dd97a4)
From my understanding this CSS property comes from CSS imported from Tailwind (base?). Do I need to take action to get rid of it?

**Comment by RustemZhangazin** [comment]
Error is still there with new version. Any plans to fix it?

**Comment by RustemZhangazin** [comment]
> I guess we can add the property to get rid of the warning.

Hage you fixed it?

**Comment by alpapan** [comment]
FWIW current error is 
```
'-webkit-text-size-adjust' is not supported by Chrome, Chrome Android, Edge 79+, Firefox, Safari. Add **'text-size-adjust'** to support Chrome 54+, Chrome Android 54+, Edge 79+.
```
