### ISSUE TITLE
Arbitrary values for 'grid-cols' generate incorrect CSS

### ISSUE THREAD

**Issue by utherpally** [tailwindlabs/tailwindcss#12654]
**What version of Tailwind CSS are you using?**

v3.4.0

**What build tool (or framework if it abstracts the build tool) are you using?**

@solidjs/start 0.4.2

**What version of Node.js are you using?**

v18.19.0

**What browser are you using?**

Firefox

**What operating system are you using?**

Linux (NixOS 24.05.20231211.a9bf124)

**Reproduction URL**

[Tailwind Play link ](https://play.tailwindcss.com/hVyoYMv52i)

**Describe your issue**

```html
<div class="grid-cols-[[full-width-start]_minmax(1rem,1fr)_[content-start]_min(100%-2rem,60rem)_[content-end]_minmax(1rem,1fr)_[full-width-end]]" />
```

CSS generated:

```css
grid-template-columns: [full-width-start] minmax(1rem,1fr) [content - start] min(100% - 2rem,60rem) [content - end] minmax(1rem,1fr) [full-width-end];
```

Expected:

No spaces in `content - start` and `content - end`

```css
grid-template-columns: [full-width-start] minmax(1rem,1fr) [content-start] min(100% - 2rem,60rem) [content-end] minmax(1rem,1fr) [full-width-end];
```

Related https://github.com/tailwindlabs/tailwindcss/issues/12281

**Comment by thecrypticace** [comment]
This should be fixed by #12704, and will be available in the next release.

You can try it before then by using our insiders build — which should be ready in ~15m:
```
npm install tailwindcss@insiders
```
