### ISSUE TITLE
Play CDN doesn't support `container-queries` plugin

### ISSUE THREAD

**Issue by mnik01** [tailwindlabs/tailwindcss#12667]
When I'm trying to load script with plugins via:
https://cdn.tailwindcss.com?plugins=forms,typography,container-queries,line-clamp

It falls with:
```console.error("Unknown plugin: `container-queries`\nAvailable plugins: `aspect-ratio`, `forms`, `line-clamp`, `typography`")```

**What version of Tailwind CSS are you using?**
CDN Play v3.4.0

**What build tool (or framework if it abstracts the build tool) are you using?**
- CDN Play v3.4.0
- Clean HTML File

**Describe your issue**

When I'm trying to load script with plugins via CDN url it falls on container-queries

**Comment by mnik01** [comment]
Well, maybe this should be feature request actually...

**Comment by thecrypticace** [comment]
I've updated the CDN — you can now use the container queries plugin (and the link you gave now works) 👍
