### ISSUE TITLE
Firefox not working with (group) "has" style modifiers

### ISSUE THREAD

**Issue by Joostdeboer** [tailwindlabs/tailwindcss#12660]
**What version of Tailwind CSS are you using?**

v3.4.0 (TailwindPlay)

**What build tool (or framework if it abstracts the build tool) are you using?**

Using the TailwindPlay application

**What version of Node.js are you using?**

See TailwindPlay

**What browser are you using?**

Firefox, Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/2rm8AujAJo

**Describe your issue**

Open the link in Google Chrome. You will be able to hover over the 2nd element in the link, and note that the top element's bottom rounded state remains without roundedness (as is intended). If you open and try this same action in Firefox, you will not see the element update accordingly.

This can also be observed in the docs: https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-descendants. Here, in Firefox, one does not see any other colored background, while in Chrome this is visible.

**Comment by adamwathan** [comment]
Hey! Make sure you are on the latest version of Firefox — Firefox only added support for `:has()` 9 days ago on December 18 with the release of Firefox 121:

https://www.mozilla.org/en-US/firefox/121.0/releasenotes/

I've tested your example in the latest version and it works as expected 👍
