### ISSUE TITLE
@layer directive not working like expected

### ISSUE THREAD

**Issue by raphi-0901** [tailwindlabs/tailwindcss#12699]
**What version of Tailwind CSS are you using?**

v3.3.5

**What build tool (or framework if it abstracts the build tool) are you using?**

Nuxt v.3.8.0

**What version of Node.js are you using?**

v18

**What browser are you using?**

Chrome

**What operating system are you using?**

Ubuntu 22.04

**Reproduction URL**
https://stackblitz.com/edit/nuxt-starter-bjk7vh?file=assets%2Fcss%2Ftailwind.css

**Describe your issue**
In the logs while running `npm run dev` an error is shown but the underline-effect class works like expected. 
But when running `npm run build` it throws an error and prevents the build.

On my local machine I actually only get an error when running `npm run build` but I was not able to reproduce this case.

In the stackblitz provided you can see that the `underline-effect-test` class works as expected but the `underline-effect` does not.

Why is it working but also showing an error that the class does not exist?

**Comment by adamwathan** [comment]
Hey! Check out these docs, they explain this exact situation: https://tailwindcss.com/docs/functions-and-directives#using-apply-with-per-component-css
