### ISSUE TITLE
TailwindCSS Not Processing Files in Nested Directories Unless Another File in Parent Directory Requires Processing

### ISSUE THREAD

**Issue by zvictor** [tailwindlabs/tailwindcss#12755]
## Description:

I am currently using Next.js with TailwindCSS and I've encountered an issue where TailwindCSS does not process files in nested directories unless another file in the parent directory requires processing.

## Environment:

Next.js: v14.0.4
TailwindCSS: v3.4.1
Nodejs: v18.19.0
OS: macOS
Browser: Firefox

## Steps to Reproduce:

1. Create a Next.js project with TailwindCSS.
2. Add a file in a nested directory, for example `./components/ui/avatar.tsx`.
3. In the TailwindCSS configuration file, add the path to the nested directory in the `content` array:

```js
const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './modules/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  // rest of the config
}
```

4. Run the Next.js project.

## Expected Behavior:

TailwindCSS should process the `avatar.tsx` file and apply the necessary styles.

## Actual Behavior:

TailwindCSS does not process the `avatar.tsx` file. The styles are not applied.

## Workaround:

If I add another file in the parent directory (`./components`) that contains an expression that needs to be processed by TailwindCSS, then the `avatar.tsx` file is processed. For example, if I add a `README.mdx` file in `./components` with the following content:

```html
<div className="grid-cols-[max-content,1fr]" />
```

Then, and only then, the `avatar.tsx` file is processed by TailwindCSS.

## Additional Information:

The `./components` directory only contains the `./components/ui` directory, which in turn only contains the `avatar.tsx` file. 
This issue seems to be a bug in TailwindCSS's file processing logic. It appears that TailwindCSS does not process files in nested directories unless there is another file in the parent directory that requires processing. This behavior is unexpected and can lead to styles not being applied as intended.

* Reproduction URL: https://github.com/zvictor/tailwind-bug-12755

**Comment by adamwathan** [comment]
Hey! The bug here is just that you are using string interpolation in `page.tsx` to create the `grid-cols-[max-content,1fr]` class:

https://github.com/zvictor/tailwind-bug-12755/blob/main/app/page.tsx#L6

Get rid of the interpolation there and everything works as expected — all of the files are all being scanned it's just that this class isn't actually being generated because Tailwind can't extract dynamically created class names from static source files:

https://tailwindcss.com/docs/content-configuration#dynamic-class-names

**Comment by zvictor** [comment]
Thanks for the clarification! I was led to believe by GPT-4 that using string interpolation in the `className` wouldn't be a problem. Clearly, I was mistaken and your input has been invaluable.

I'm new to Tailwind and I must say, your quick support and the quality of the documentation have been impressive. Keep up the good work!
