### ISSUE TITLE
can we add new colors based on condition in plugin

### ISSUE THREAD

**Issue by malikmubashar** [tailwindlabs/tailwindcss#12848]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/12847

<div type='discussions-op-text'>

<sup>Originally posted by **malikmubashar** January 28, 2024</sup>
I am trying to make a personal tailwind plugin but stucked with a issue you can see in the example:
[https://play.tailwindcss.com/ONWu9MLujc?file=config](https://play.tailwindcss.com/ONWu9MLujc?file=config)

In plugin, i am trying to **add secondry** color in config file if it has primary color.

Is i am doing somethig wrong? Please guide.

Tailwind Version: 3.3.0</div>

**Comment by adamwathan** [comment]
Hey! We use issues strictly for bug reports so going to close this in favor of the discussion.
