### ISSUE TITLE
Prettier prevents using underscores in tokens or custom properties.

### ISSUE THREAD

**Issue by bricejar** [tailwindlabs/tailwindcss#12865]
**What version of Tailwind CSS are you using?**

3.4.0.

**What build tool (or framework if it abstracts the build tool) are you using?**

prettier 2.8 , VsCode, eslint-plugin-prettier.

**Describe your issue**

Prettier automatically escapes "useless" escaped characters. For example `"\_"` will be changed to `"_"`. However, tailwind uses underscores to represent text spaces in some cases.

So for example

```
border-b-[length:theme(spacing[input_border_bottom_width])]
border-b-[length:var(--input_border_bottom_width)]
```

Must be written

```
border-b-[length:theme(spacing[input\_border\_bottom\_width])]
border-b-[length:var(--input\_border\_bottom\_width]
```

Because tailwind interprets `var(--input_border_bottom_width)` as `var(--input border bottom width)`

However in JSX  the following code

``` jsx
return <div className="border-b-[length:var(--input\_border\_bottom\_width)]"> </div>
```

will be replaced by this if you use prettier 

``` jsx
return <div className="border-b-[length:var(--input_border_bottom_width)]"> </div>
```

Given the fact that prettier is a very widely used tool in frontend I believe we should have a solution for this.

**Comment by reinink** [comment]
Hey! Can you please provide a minimal reproduction of this as a Git repo?

Here at Tailwind Labs we use Prettier (v2 previously, v3 now) on basically all of our React projects, and haven't run into this (at least not that I'm aware of). I just tested these exact classes in a project of ours and Prettier didn't strip the slashes. I'm wondering if it maybe has something to do with the `eslint-plugin-prettier` plugin.

Either way, if you could please provide a *minimal* reproduction of this as a Git repo that will make it much easier for us to reproduce and helpfully provide some help 👍

**Comment by bricejar** [comment]
Hi, thank you for your answer. Yes let me get back to you asap with a reproduction.

**Comment by bricejar** [comment]
Alright ! 

eslint-plugin-prettier : 5.1.3
prettier : 3.2.4

https://github.com/bricejar/prettier-tailwind-escape-issue

If you run the "lint" script you get : 

```
  6:55  error  Delete `\`  prettier/prettier
✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

**Comment by bricejar** [comment]
I also added a "pretty" command to run prettier directly without eslint (it will modify the file) and you get the same result.

**Comment by bricejar** [comment]
In the prettier playground v3.2.4, 

I made a strange observation.

The following code 

```
function Removed() {
  return <div className={"\_HelloWorld"}></div>;
}

function NotRemoved() {
  return <div className="\_HelloWorld"></div>;
}
```

outputs this

```
function Removed() {
  return <div className={"_HelloWorld"}></div>;
}

function NotRemoved() {
  return <div className="\_HelloWorld"></div>;
}

```

You can notice the bug in the first function but not the second. 

You may try it there : https://prettier.io/playground/ .

**Comment by bricejar** [comment]
I opened an issue in the prettier repo https://github.com/prettier/prettier/issues/16008 .

**Comment by bricejar** [comment]
They gave an explanation. JSX strings are parsed as if they are html strings.
However, when one puts a string in brackets, it becomes a js string. And in javascript `"\_"` and `"_"` are equivalent. 
I just realized that this unintuitive behavior is in the official tailwind documentation. The remedy is to use String.raw.

https://tailwindcss.com/docs/adding-custom-styles

**Quote** : 

If you’re using something like JSX where the backslash is stripped from the rendered HTML, use [String.raw()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/raw) so the backslash isn’t treated as a JavaScript escape character: 
 
```
<div className={String.raw`before:content-['hello\_world']`}>
  <!-- ... -->
</div>
``` 

**End quote**. 

I wish we had an alternative way of displaying underscores. 

I believe the symbol * is forbidden as a css property. So we could write underscores like this `"property*_name*_with*_underscores" `

Or why not  `"property*name*with*underscores" `.

Just a quick thought.



Thank you for your help and your time !

**Comment by reinink** [comment]
Ahh yes, this rings a bell now! I agree, it's kind of annoying to have to do `String.raw`, but that is the required approach at this time if you want to use underscores in JSX.

One suggestion, consider using dashes instead of underscores in your utility name, like `input-border-bottom-width`. That's what we do in Tailwind core with utilities like `cursor-not-allowed` and `row-span-2`.

Also, just an observation, a class like `border-b-[length:theme(spacing[input_border_bottom_width])]` is kind of strange to begin with. Personally I'd probably just use an arbitrary value like `border-b-[3px]` in this situation, or if I really wanted it as part of my theme I'd try to just add that value as part of my border size scale, like `border-b-3` (for a 3px border), even if that value was only ever used for the bottom border. Generally though I try to avoid implementation specific things like input border widths from ever becoming part of my theme.

Anyway, glad you got it figured out, hope that helps 👍

**Comment by bricejar** [comment]
Regarding your observation: I'm working on an existing codebase for which underscores are the convention. 

The reason for that class is that I have to accomodate different design systems, by configuration. So that leads me to very specific tokens. 

For example, one design system has a specific border bottom width of 2px for inputs, and other border width are 0px. And for other systems all borders are 1px. I even have variations on some specific border radius. 
And inputs refers to text inputs, but also textareas, rich text editors, date pickers etc.  

Since I don't know in advance the values, it makes sense to refer to them with a token or a custom property.
I could also define new classes, such as border-b-input ,border-l-input, but I believe this is an anti-pattern because sooner or later it would lead to dead code.
