### ISSUE TITLE
darkMode: 'class' feature not working with Tailwind CDN (v3.4.1)

### ISSUE THREAD

**Issue by zulkufdemirhan** [tailwindlabs/tailwindcss#12871]
**What version of Tailwind CSS are you using?**

v3.4.1

**What build tool (or framework if it abstracts the build tool) are you using?**

CDN

**What version of Node.js are you using?**

CDN, so N/A

**What browser are you using?**

Firefox

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/zulkufdemirhan/tailwind-dark-mode

**Describe your issue**

**Dark Mode On:**
<img width="1428" alt="Screenshot 2024-02-02 at 20 04 17" src="https://github.com/tailwindlabs/tailwindcss/assets/95721351/78cb6543-24b8-4b0b-8c1c-b5a5cda5bd7a">

**Dark Mode Off:**
<img width="1431" alt="Screenshot 2024-02-02 at 20 05 22" src="https://github.com/tailwindlabs/tailwindcss/assets/95721351/fec73d08-89c5-4c87-8144-76c4b57cd8c5">

 'darkMode: 'class'' feature is not working in conjunction with Tailwind CDN (v3.4.1). However, after removing the CDN, I ran it and it worked without CDN.

- After setting up my project with Tailwind CLI, I'm adding Tailwind CDN additionally to use some features. This situation causes an issue with the 'darkMode' feature.
- When I follow only the Tailwind CDN usage guidelines without installing Tailwind CLI, the 'darkMode' feature works.

**Comment by adamwathan** [comment]
Hey! Can you share a reproduction?

**Comment by montaserfzy** [comment]
same thing here

**Comment by zulkufdemirhan** [comment]
> Hey! Can you share a reproduction?

Here is test repo: https://github.com/zulkufdemirhan/tailwind-dark-mode

**Comment by adamwathan** [comment]
Got it, so the problem is you aren't actually configuring `darkMode` to `class` anywhere in your project. For the CDN, you need to do that in a `<script>` tag as per [the documentation](https://tailwindcss.com/docs/installation/play-cdn) — it can't read your `tailwind.config.js` file from the filesystem.

Here's a working demo:

https://jsfiddle.net/98ecmb7g/1/

Hope that helps!
