### ISSUE TITLE
Background clip extend not applied

### ISSUE THREAD

**Issue by elvince** [tailwindlabs/tailwindcss#12898]
**What version of Tailwind CSS are you using?**

For example: v3.4.1

**What build tool (or framework if it abstracts the build tool) are you using?**

No specific tool - Error is also on Tailwind Playground

**What browser are you using?**

 Chrome

**What operating system are you using?**

 Windows

**Reproduction URL**

https://play.tailwindcss.com/zcFoeAWuqn

**Describe your issue**

I can't extend background clip as I can background Image

This prevents me to set properly my background clipping.

As per the documentation, I'm not sure that I can extend the clip.

In not,how can I deal with this? should I used my fix with the css class?
Is this something you can improve in the next version?

Thanks,

**Comment by thecrypticace** [comment]
Hey! So you are correct that you _cannot_ extend the existing background clip utilities.

There are a few options you have to introduce a custom utility here:

1. Use arbitrary properties — which let you use any CSS property as a utility. This is my preferred solution — especially for one-off use cases:

```html
<div class="[background-clip:padding-box,border-box]">…</div>
```

2. Add a the `bg-clip-test` utility to your CSS:
```css
@layer utilities {
  .bg-clip-test {
    background-clip: padding-box, border-box;
  }
}
```

3. Add the `bg-clip-test` utility with a plugin in your config file:

```js
/** @type {import('tailwindcss').Config} */
export default {
  // ...
  plugins: [
    function ({ addUtilities }) {
      addUtilities({
        '.bg-clip-test': {
          'background-clip': 'padding-box, border-box'
        },
      })
    }
  ],
}
```

Hope that helps! ✨

**Comment by elvince** [comment]
Thanks for the quick feedback and for providing solution
