### ISSUE TITLE
CLI does not work with `--watch` when daemonized

### ISSUE THREAD

**Issue by WesleyAC** [tailwindlabs/tailwindcss#12954]
**What version of Tailwind CSS are you using?**
3.4.1

**What build tool (or framework if it abstracts the build tool) are you using?**

yarn v1.22.19

**What version of Node.js are you using?**

v18.18.2

**What browser are you using?**

N/A

**What operating system are you using?**

Linux

**Reproduction URL**

N/A (this is a bug in the CLI, not the generated CSS)

**Describe your issue**

Running the following bash script does not result in Tailwind rebuilding when files are changed:

```bash
#!/usr/bin/env bash
yarn tailwindcss -i ./css/style.css -o ./static/style.css --watch &
read
```

Just running `yarn tailwindcss -i ./css/style.css -o ./static/style.css --watch` is fine, but when it's put in the background and something else is run, it fails.

**Comment by thecrypticace** [comment]
This is because backgrounding a process inside of a bash script closes stdin for that process. This then causes our process to exit. You can work around this by using `--watch=always` instead of just `--watch`.

**Comment by WesleyAC** [comment]
Ah, I see. Could this be documented somewhere? I would have tried this if `--help` mentioned that it existed.

**Comment by guillemus** [comment]
Man I've been bit by this many times, thank you @WesleyAC for posting this.
I think the cli should show a warning to the user if --watch is passed without always and stdin is closed. Silently do nothing and exit gives a really bad experience, as if file watching is buggy.
Just a little warning or something saying using --watch on stdin won't work, use --watch=always instead.

idk it it's the right fix, but a warning would have saved me a lot of struggle!
