### ISSUE TITLE
Adds additional class-name on adding decimal classes

### ISSUE THREAD

**Issue by sbimochan** [tailwindlabs/tailwindcss#12957]
On using `gap-2.5` it generates two class-names: `gap-2` and `gap-2\.5`. I think we have rooms for improvements in the compiler.

**What version of Tailwind CSS are you using?**

v3.3.3

**What build tool (or framework if it abstracts the build tool) are you using?**

 webpack 5.28.0

**What version of Node.js are you using?**

v20.5.1

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

N/A

**Describe your issue**

On using `gap-2.5` it generates two class-names: `gap-2` and `gap-2\.5`. I think we have rooms for improvements in the compiler.

**Comment by sbimochan** [comment]
Cool! It's not much of a big deal. The extra classname that it generates also has potential probability of being used too. I just wanted to point out it but looks like it was a well known a year ago. I don't think we need to used that extract function. It should be good!

**Comment by AnshSinghSonkhia** [comment]
Hey @reinink, where can I know more about Tailwind CSS v4 ?? SUPER EXCITED

**Comment by reinink** [comment]
@AnshSinghSonkhia Hey! See here: https://www.youtube.com/watch?v=CLkxRnRQtDE
