### ISSUE TITLE
text- arbitrary value assumes color when enough info present to suggest font size

### ISSUE THREAD

**Issue by rob-gordon** [tailwindlabs/tailwindcss#12960]
**What version of Tailwind CSS are you using?**

3.4.1

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite

**What version of Node.js are you using?**

18.17

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/mJQiLPU1x0

**Describe your issue**

Using arbitrary value syntax to reference css custom properties. Of course tailwind can't know the true value of the custom property on the client, but at build time I would think using a fallback could be a nice way of telling it what css property it's targeting for overloaded properties like `text-`. Tailwind assumes color when it should be font size (checkout play link).

**Comment by reinink** [comment]
Hey! Tailwind provides a way to resolve ambiguities like this by adding a type before the value:

```html
<span class="text-[length:var(--font-size,16px)]">Hello World</span>
```

Here's a Tailwind Play demoing this: https://play.tailwindcss.com/3ztGp8e9Tq

You can read more about these type hints in the [resolving ambiguities](https://tailwindcss.com/docs/adding-custom-styles#resolving-ambiguities) section of the "Using arbitrary values" docs.

Hope that helps! 🤙

**Comment by rob-gordon** [comment]
@reinink Appreciate it!

**Comment by assemmarwan** [comment]
@reinink How to hint that the intention is font family. Currently, when using `font-[var(--heading-font)]`, it resolves to `font-weight`. I tried `font`, `family` and `font-family`, but no lucl

**Comment by assemmarwan** [comment]
> You can use `lookup`, `generic-name` or `family-name`.

Unfortunately, none of these worked for me. 

Nevertheless,I found through Tailwind's[ documentation](https://tailwindcss.com/docs/adding-custom-styles#arbitrary-properties), that we can use CSS properties directly like so:

 `[font-family:var(--subheading-font)]` or `[font-family:--subheading-font]` for short.

As they mention in the documentation, this is almost like using _inline styles_, with the added benefit of using modifiers like `lg:`, `hover:`, etc...
