### ISSUE TITLE
[v4] The "preflight.css" file has more priority than it should have!?

### ISSUE THREAD

**Issue by devcaeg** [tailwindlabs/tailwindcss#13112]
**What version of Tailwind CSS are you using?**
v.next

**What build tool (or framework if it abstracts the build tool) are you using?**
vite (v5.1.5), @builder.io/qwik (v1.5.1), @builder.io/qwik-city (v1.5.1), @tailwindcss/vite (v.next)

**What version of Node.js are you using?**
v20.9.0

**What browser are you using?**
Chrome, Safari, Edge

**What operating system are you using?**
macOS

**Reproduction URL** 
https://codesandbox.io/p/devbox/loving-glade-zdpd88?file=%2Fsrc%2Froutes%2Findex.tsx

**Describe your issue**

I'm experimenting with TailwindCSS version 4 and have encountered an issue: certain styles don't seem to apply correctly. Upon investigating, I discovered that the styles defined in "preflight.css" take precedence over other TailwindCSS styles. To illustrate this problem, "preflight.css" sets that "h1, h2, h3, h4, h5, h6" inherit the font size through the style "font-size: inherit". This means that if you assign the "text-3xl" class to an "h1" element, the style intended by "text-3xl" is overridden by the one established in "preflight.css".

**Comment by thecrypticace** [comment]
I've just confirmed it's Qwik doing this. In their Vite plugin they inject link tags for all CSS files known to the Vite module graph but this will also include files that were imported into CSS layers, media queries, supports blocks, etc…:

https://github.com/BuilderIO/qwik/blob/c88e53d49dc65020899d770338f4e51f3134611e/packages/qwik/src/optimizer/src/plugins/vite-server.ts#L102-L126

**Comment by devcaeg** [comment]
@thecrypticace 

Do you think there is a solution for this error?

**Comment by thecrypticace** [comment]
Right now, I don't believe so. This would be on Qwik to address given that we're making use of normal CSS features that they're not handling correctly.

**Comment by devcaeg** [comment]
I just opened an issue in the Qwik repository linking to this issue, to see how to approach a solution.

**Comment by devcaeg** [comment]
@thecrypticace 

Thank you very much for your quick response and finding the error.

**Comment by wmertens** [comment]
The reasoning is that the import graph contains all css for the sure. So for some reason the css exists 3 times?

**Comment by thecrypticace** [comment]
Gonna close since this is a bug in Qwik and there's a workaround for now.
