### ISSUE TITLE
v4 crashes with .scss

### ISSUE THREAD

**Issue by piscopancer** [tailwindlabs/tailwindcss#13147]
### v4.0.0-alpha.6

Crashes if `.scss` file used:
```scss
@import "tailwindcss";
```
![image](https://github.com/tailwindlabs/tailwindcss/assets/109352196/99572b8a-a184-42b5-a522-2421df6ea5d9)

**Comment by RobinMalfait** [comment]
If you want to use `scss`, then you have to process it before giving it to Tailwind CSS. Are there any features you must use that won't work in native `.css` files?

Can you also provide a minimal reproduction repo?
