### ISSUE TITLE
[v4] Using PostCSS @theme doesn't work in a Next.js project

### ISSUE THREAD

**Issue by Facug03** [tailwindlabs/tailwindcss#13156]
**What version of Tailwind CSS are you using?**

v4.0.0-alpha.6

**What build tool (or framework if it abstracts the build tool) are you using?**

tailwindcss/postcss: 4.0.0-alpha.6, Next.js 14.1.3

**What version of Node.js are you using?**

v18.17.1

**What browser are you using?**

Firefox

**What operating system are you using?**

Windows

**Reproduction URL**

https://github.com/Facug03/tailwind-v4-next 

It's a repo that i created only to try the new version

**Describe your issue**

I installed the most recent version of Next.js, followed by the installation of the latest version of Tailwind using PostCSS, and it worked. However, when attempting to utilize the new '@theme', it threw an error:

![imagen](https://github.com/tailwindlabs/tailwindcss/assets/107658697/e4f1311a-5fab-4292-b914-29effa645454)

CSS:

![imagen](https://github.com/tailwindlabs/tailwindcss/assets/107658697/4bc869eb-7ea9-4f37-8c79-858e2351bd07)

**Comment by adamwathan** [comment]
Fixed in #13162, thanks for reporting! Publishing a new release in a sec.
