### ISSUE TITLE
[v4] Gradients not working in Firefox

### ISSUE THREAD

**Issue by n0ah01** [tailwindlabs/tailwindcss#13198]
**What version of Tailwind CSS are you using?**

tailwindcss v4.0.0-alpha.7

**What build tool (or framework if it abstracts the build tool) are you using?**

@tailwindcss/cli@4.0.0-alpha.7

**What version of Node.js are you using?**

node v21.6.2
npm 10.2.4

**What browser are you using?**

Firefox: 123.0.1

**What operating system are you using?**

Ubuntu 22.04.4 LTS

**Reproduction URL**

[https://play.tailwindcss.com/1E6nLOSBdR](https://play.tailwindcss.com/1E6nLOSBdR)

```
<div class="grid gap-2">
	<div class="rounded h-16 border-solid border-slate-500 border bg-gradient-to-r from-cyan-500 to-blue-500"></div>
	<div class="rounded h-16 border-solid border-slate-500 border bg-gradient-to-r [--tw-gradient-stops:#f00,#0f0]"></div>
</div>
```

**Describe your issue**

Creating a normal gradient with default Tailwind classes like `bg-gradient-to-r from-cyan-500 to-blue-500` does not produce working CSS for Firefox, works normali in Brave/Chrome. The problem seems to be in the `--tw-gradient-stops` variable of the `.to-XXX` class with the value `var(--tw-gradient-via-stops,var(--tw-gradient-from)var(--tw-gradient-from-position),var(--tw-gradient-to)var(--tw-gradient-to-position))`.
If I edit the variable value to `var(--tw-gradient-via-stops, var(--tw-gradient-from), var(--tw-gradient-to))` it works as expected.

**Comment by adamwathan** [comment]
Hey! Try it in Firefox Nightly — the v4 alpha depends on `@property` which will only work in Firefox beginning with version 126:

https://caniuse.com/mdn-css_at-rules_property

**Comment by n0ah01** [comment]
Thanks @adamwathan! Greetings from switzerland
