### ISSUE TITLE
`leading-normal` should have apply `line-height: normal` and not `line-height: 1.5`

### ISSUE THREAD

**Issue by mrleblanc101** [tailwindlabs/tailwindcss#13196]
**What version of Tailwind CSS are you using?**

3.4.1

**What build tool (or framework if it abstracts the build tool) are you using?**

vite 5

**What version of Node.js are you using?**

20

**What browser are you using?**

Chrome 

**What operating system are you using?**

macOS

**Reproduction URL**

A Tailwind Play link or public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways.

A reproduction is **required** when filing an issue — any issue opened without a reproduction will be closed and you'll be asked to create a new issue that includes a reproduction. We're a small team and we can't keep up with the volume of issues we receive if we need to reproduce each issue from scratch ourselves.

**Describe your issue**

Confusingly, `leading-normal` apply `line-height: 1.5` instead of `line-height: normal`.
There is no way to opt into the font file default line-height.
You can always use `leading-[normal]`, but that seems weird.
I think `line-height: 1.5` should be rename `leading-regular` or something similar ?

**Comment by RobinMalfait** [comment]
Hey!

The names and values are some defaults we chose, if you want you can override `leading-normal` via your `tailwind.config.js` file. 

More info: https://tailwindcss.com/docs/line-height#customizing-your-theme 
E.g.: https://play.tailwindcss.com/ER0Fpktyif?file=config

Hope this helps!

**Comment by mrleblanc101** [comment]
@RobinMalfait I know this, but still I wonder if the defaults are right for this property. Maybe it could be reconsidered for Tailwind v4 since it would obviously be a breaking change.
