### ISSUE TITLE
[V4] Border property is not working

### ISSUE THREAD

**Issue by Facug03** [tailwindlabs/tailwindcss#13206]
**What version of Tailwind CSS are you using?**

@tailwindcss/postcss: 4.0.0-alpha.8
  tailwindcss: 4.0.0-alpha.8

**What build tool (or framework if it abstracts the build tool) are you using?**

next: 14.1.3

**What version of Node.js are you using?**

v18.17.1

**What browser are you using?**

Firefox

**What operating system are you using?**

Windows

**Reproduction URL**

![imagen](https://github.com/tailwindlabs/tailwindcss/assets/107658697/bcd3521b-bc48-4e95-8bbf-6510420afb62)

**Describe your issue**

When using the border property it doesn't show in the ui

**Comment by adamwathan** [comment]
Hey! Try Firefox Nightly — right now the v4 alpha only works in browsers with `@property` support:

https://caniuse.com/mdn-css_at-rules_property

**Comment by Facug03** [comment]
ahh okey, just tried with Chrome and Edge and it worked

**Comment by adamwathan** [comment]
Awesome! Going to close this one then — Firefox will support it out of the box by the time we tag v4.0 and we'll probably polyfill it for older browsers just in case too.
