### ISSUE TITLE
Consider transform fallback for translate property

### ISSUE THREAD

**Issue by raaaahman** [tailwindlabs/tailwindcss#13214]
**What version of Tailwind CSS are you using?**

4.0.0-alpha.6

**What build tool (or framework if it abstracts the build tool) are you using?**

@postcss/tailwindcss 4.0.0-alpha.6 with Next.js 14.1.0

**What version of Node.js are you using?**

v20.10.6

**What browser are you using?**

Firefox 123.0.1 (Mozilla Firefox Snap for Ubuntu)

**What operating system are you using?**

Ubuntu 22.04.4 LTS

**Reproduction URL**

https://github.com/raaaahman/tailwind-4-translate

**Describe your issue**

Tailwind 4 is now using the `translate` property instead of the `transtorm: translate()` one. Although it seems this property is well supported for modern browsers, I still have issues with it in the latest version of Firefox for Linux.

![Using the `translate`css property in Mozilla Firfefox Snap for Ubuntu](https://github.com/tailwindlabs/tailwindcss/assets/16425382/6dc60530-37eb-49db-afd0-3ea553cea4f5)

Whereas it works fine in  Chromium:

![Using the `translate` css property in Chromium](https://github.com/tailwindlabs/tailwindcss/assets/16425382/bf34fac1-1d02-4f77-b87f-5cc9988ed9bb)

Could we have a fallback to the old `transform: translate()` property, or a way to configure this? 

Thank you.

**Comment by adamwathan** [comment]
Hey! My guess here is that what you're really running into is that Firefox doesn't support `@property` yet:

https://caniuse.com/mdn-css_at-rules_property

Firefox Nightly does though, and it will be in Firefox 126 which will be out before we do a v4 stable release.

Can you try Firefox Nightly and see if you still have any issues?

**Comment by raaaahman** [comment]
Hello,

It seems you've guessed right, as I can see it working fine in Firefox 125.0a1 (same visual than Chromium).

 Thank you for the quick response!
