### ISSUE TITLE
Peer not compiled when using prefix

### ISSUE THREAD

**Issue by amtee** [tailwindlabs/tailwindcss#13226]
**What version of Tailwind CSS are you using?**

3.4.1

**What build tool (or framework if it abstracts the build tool) are you using?**

npx tailwind -w -m -o Resources/Public/Dist/tailwind.css

**What version of Node.js are you using?**

v16.20.2

**What browser are you using?**

irrelevant

**What operating system are you using?**

macOS

**Reproduction URL**

[NOT WORKING: Tailwind play with prefix `tw-` and peer](https://play.tailwindcss.com/0BjxzGQr1l) 

[WORKING: Tailwind play without prefix ` and peer](https://play.tailwindcss.com/x20u8TAw5R)

**Describe your issue**

When setting a prefix the peer classes will not be added to the target css file.

**Comment by wongjn** [comment]
As per [the documentation](https://tailwindcss.com/docs/configuration#prefix):

> It’s important to understand that this prefix is added *after* any variant modifiers. That means that classes with responsive or state modifiers like `sm:` or `hover:` will still have the responsive or state modifier *first*, with your custom prefix appearing after the colon:
>
> ```html
> <div class="tw-text-lg md:tw-text-xl tw-bg-red-500 hover:tw-bg-blue-500">
>   
> </div>
> ```

So in your case, the class name should be `peer-checked:tw-my-12`, not `tw-peer-checked:my-12`. See this working in [this Tailwind Play](https://play.tailwindcss.com/Arhlqvjkam).

**Comment by amtee** [comment]
🤦🏻‍♂️ 

Thank you, Justin, for clarification.
