### ISSUE TITLE
[v4] `transform` utilities not working in Firefox due to no support for `@property`

### ISSUE THREAD

**Issue by zoomoid** [tailwindlabs/tailwindcss#13268]
**What version of Tailwind CSS are you using?**

v4.0.0-alpha.9

**What build tool (or framework if it abstracts the build tool) are you using?**

@tailwindcss/postcss 4.0.0-alpha.9, Next.js 14.1.3

**What version of Node.js are you using?**

v20.11.0

**What browser are you using?**

Firefox v123.0.1 (64 bit)

**What operating system are you using?**

macOS

**Reproduction URL**

Clone the NextJS repo at https://github.com/zoomoid/tailwindcss-4-experiments and run the project in `missing-transform-defaults`.

**Describe your issue**

Firefox currently only has support for `@property` in nightly builds and not at all for Firefox for Android. The CSS variables used in `transform`, `translate` and so forth are partially undefined in Firefox, rendering the entire rule without effect.

In the example above, the `<p>` should be translated by 2rem to the right, using `transform translate-x-8`. This works in Chrome and Safari as previously in < 4.0.0, because `translate-x-*` expands to two rules, one for setting `--tw-translate-x` and one for rendering

```css
transform: translate(var(--tw-translate-x),var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
```

where the rest of the variables are defaulted from the preflight settings.

In v4, these are set via CSS's `@property` rules with appropriate defaults, but those at-rules are not yet supported in mainline Firefox. `translate-x-*` is also expanded into a singular rule, e.g.,

```css
.translate-x-8 {
    --tw-translate-x: 3rem;
    translate: var(--tw-translate-x) var(--tw-translate-y);
}
```

where the undefinedness of --tw-translate-y breaks the property's effect. You can quickly fix this by adding

```css
--tw-translate-x: 0;
--tw-translate-y: 0;
--tw-rotate: 0;
--tw-skew-x: 0;
--tw-skew-y: 0;
--tw-scale-x: 1;
--tw-scale-y: 1;
```

to your `@theme` block to default them at the root.

**Comment by adamwathan** [comment]
Hey! Yeah lack of Firefox support is known/intentional right now, you'll want to use Firefox Nightly to play with v4 which does have `@property` support. Will be in Firefox stable channels in May 👍 We may sort of polyfill this using the approach we used in v3 depending on when we tag v4 for real, will have to see.
