### ISSUE TITLE
[v4] Doesn't detect Svelte class directives 

### ISSUE THREAD

**Issue by ryanylee** [tailwindlabs/tailwindcss#13263]
**What version of Tailwind CSS are you using?**

v4.0.0-alpha.9

In Svelte, I have a div as follows
```
<script>
   let show = true;
</script>

<div class:opacity-10={show}>hi!</div>
```

Currently `.opacity-10` is not generated

**Comment by RobinMalfait** [comment]
Hey!

This has been implemented in #13274 and will be available in the next v4 alpha release.
