### ISSUE TITLE
[v4] @tailwindcss/vite@4.0.0-alpha.10 throws internal error on clean install

### ISSUE THREAD

**Issue by HiggsWRX** [tailwindlabs/tailwindcss#13308]
**What version of Tailwind CSS are you using?**

v4.0.0-alpha.10

**What build tool (or framework if it abstracts the build tool) are you using?**

vite@5.1.6

**What version of Node.js are you using?**

v21.6.1

**What browser are you using?**

Firefox Developer Edition

**What operating system are you using?**

macOS

**Reproduction URL**

A Tailwind Play link or public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways.

A reproduction is **required** when filing an issue — any issue opened without a reproduction will be closed and you'll be asked to create a new issue that includes a reproduction. We're a small team and we can't keep up with the volume of issues we receive if we need to reproduce each issue from scratch ourselves.

**Describe your issue**
After upgrade from alpha 9 to alpha 10 vite throws this error:

`[vite] Internal server error: i?.waitForRequestsIdle is not a function`

Using alpha 10 of `@tailwindcss` in conjunction with alpha 9 of `@tailwindcss/vite` sidesteps the issue

**Comment by thecrypticace** [comment]
Are you on Vite 5.2.0?

**Comment by HiggsWRX** [comment]
Thanks @thecrypticace, that was indeed the issue. I have upgraded my vite version and the error went away.

Closing this issue!
