### ISSUE TITLE
[v4] @apply not effected (SvelteKit, Vite)

### ISSUE THREAD

**Issue by szig83** [tailwindlabs/tailwindcss#13305]
**What version of Tailwind CSS are you using?**

4.0.0-alpha.9

**What build tool (or framework if it abstracts the build tool) are you using?**

Svelte 5.0.0-next.80, SvelteKit 2.5.4, @tailwindcss/vite 4.0.0-alpha.9, vite 5.2.2

**What version of Node.js are you using?**

For example: v20.10.0

**What browser are you using?**

Brave (Chrome), Firefox, Safari

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/szig83/svelte5-tailwind4
(https://github.com/szig83/svelte5-tailwind4/blob/main/src/routes/%2Bpage.svelte)

**Describe your issue**
The problematic code snippet can be found in the src/routes/+page.svelte file. I created a custom CSS class where I wanted to use the @apply directive. There is no error during build and runtime, but the @apply directive seems to not take effect.
The div element with the Tailwind class (bg-gray-700) is applied correctly.

**Comment by coolemur** [comment]
@apply should be deprecated

**Comment by szig83** [comment]
"And what would be the solution if I want to apply Tailwind classes within my own class definition?"

**Comment by coolemur** [comment]
> And what would be the solution if I want to apply Tailwind classes within my own class definition?

I think if you use @apply you lose all the benefits of Tailwind. For example, portability of your code becomes less and less possible (if you deal with multiple projects).

Also your code base now just has additional pattern - mixing patterns is not right thing to do.

So the main question is **why you think you need @apply**, not why you don't have it.

Take a look a this: https://twitter.com/adamwathan/status/1226511611592085504?lang=en

**Comment by coolemur** [comment]
And if you **really** need it for some weird reason, if I were you, I would use separate css file with custom classes.

Your tailwind utility classes are plain CSS. So you can just inspect what they do and re-apply them to your custom css.

This way at least you would have your weird code in a single place.

**Comment by coolemur** [comment]
And if you really need it, why not just apply plain CSS class with custom styles?
This must be exceptional use case, not a pattern in your code anyway.

**Comment by szig83** [comment]
I see. It's logical after all :) Thanks for the info.

**Comment by QuentiumYT** [comment]
I think it should still be included for CMS that uses content from a WYSIWYG for example. I do have some default styles using Tailwind for some blocs :)

**Comment by fweth** [comment]
I like `@apply`, but I think it might be less relevant in v4 when everything is configured via custom properties, as you can access those also in vanilla CSS.

**Comment by aaronadamsCA** [comment]
Just because there are lots of bad use cases for `@apply` doesn't mean there aren't some great ones too!

If anything, given v4 ships CSS-first configuration and built-in nesting support, I think the use case for `@apply` is even stronger than it was before.

For example, roll your own `.prose` class for styling HTML you don't control:

```css
@layer components {
  .prose {
    @apply text-neutral-700 *:first:mt-0 *:last:mb-0;
    caption {
      @apply caption-bottom mt-4 text-left text-xs;
    }
    del {
      @apply opacity-70;
    }
    iframe {
      @apply border-0;
    }
    p {
      @apply my-4;
    }
    /* etc. etc. etc. */
  }
}
```

This approach stays true to Tailwind, but is much more readable than the alternative. I'd love to see this supported.

**Comment by coolemur** [comment]
> Just because there are lots of bad use cases for `@apply` doesn't mean there aren't some great ones too!
> 
> If anything, given v4 ships CSS-first configuration and built-in nesting support, I think the use case for `@apply` is even stronger than it was before.
> 
> For example, roll your own `.prose` class for styling HTML you don't control:
> 
> ```css
> @layer components {
>   .prose {
>     @apply text-neutral-700 *:first:mt-0 *:last:mb-0;
>     caption {
>       @apply caption-bottom mt-4 text-left text-xs;
>     }
>     del {
>       @apply opacity-70;
>     }
>     iframe {
>       @apply border-0;
>     }
>     p {
>       @apply my-4;
>     }
>     /* etc. etc. etc. */
>   }
> }
> ```
> 
> This approach stays true to Tailwind, but is much more readable than the alternative. I'd love to see this supported.

Yes and no.

By enabling @apply you open door to abusing it 
(And developers will. Espacially in larger code bases. You won't be able to enforce the rule "don't create custom utils using @apply - which defeats the purpose of Tailwind")

And this prose case is just exception that could be handled using pure CSS instead of applying styles.

**Comment by coolemur** [comment]
To those who disagree - wait till you work on big scale project with larger team who will abuse @apply rule... Then you will understand my concern. 🤙

**Comment by fweth** [comment]
I don't think software should make itself non-abusable.  If `@apply` is difficult to maintain and there are more important features that could use those ressources, then sure, drop it.  But otherwise, I'd say it's the responsibility of the developers to write good code, not the responsibility of the library authors.

**Comment by QuentiumYT** [comment]
I agree, a lot of developers write the code how they want. We should have the ability to *choose* what to write and how we use the features. Indeed, there is some good and bad ways but sometimes we have to use some "deprecated" features rather than the forced way to do it.

**Comment by coolemur** [comment]
I don't agree, seeing abused code on a daily basis where it could be solved worldwide with a single opinionated solution 🙃

It's like a seatbelts or DUI - if ppl had freedom, they would make big mistakes.

And I am telling you right-now: freedom + saying "don't use it" will not work. 😆

**Comment by fweth** [comment]
In any case, please don't take nesting support away :D

**Comment by lucas-subli** [comment]
Having the same issue:

![image](https://github.com/user-attachments/assets/a567b266-7a49-4ce4-8877-17f2a05406b2)

![image](https://github.com/user-attachments/assets/4637893e-1d0e-4be7-9afe-f0139f93d535)


#### What version of Tailwind CSS are you using?
4.0.0-alpha.17

#### What build tool (or framework if it abstracts the build tool) are you using?
Svelte 5, vite 5.0.3

#### What version of Node.js are you using?
v20.10.0

#### What browser are you using?
Chrome, Firefox

#### What operating system are you using?
Ubuntu 24.04

#### Reproduction URL

https://github.com/lucas-subli/svelte-5-tailwind-4
```
pnpm install
pnpm start
```

#### Describe your issue

Using a class that has `@apply` does not seem to work, in the example the text should be red, but it is not.
This was working with Tailwind 3 using postcss.

#### A small defense for @apply
@apply is very useful for making components with variation.
For example, in a project that has 3 types of a buttons, `standard,` `outline`, and `text` with 3 possible colors `primary,` `accent`, and `danger.`

It is easy to create a svelte component with `class="{type} {color}"`
And define `.standard .outlined (...) .danger` styles with @apply
Removing apply would make this much harder than it needs to be

**Comment by lucas-subli** [comment]
Although there are ways to make it work now the discussion is ongoing on: https://github.com/tailwindlabs/tailwindcss/discussions/15205
