### ISSUE TITLE
[v4] `i?.waitForRequestsIdle is not a function`

### ISSUE THREAD

**Issue by Steffan153** [tailwindlabs/tailwindcss#13356]
After upgrading to alpha.10:

```
15:55:14 [ERROR] i?.waitForRequestsIdle is not a function. (In 'i?.waitForRequestsIdle(t)', 'i?.waitForRequestsIdle' is undefined)
  Stack trace:
    at <anonymous> (/[...]/node_modules/@tailwindcss/vite/dist/index.mjs:0:1353)
    [...] See full stack trace in the browser, or rerun with --verbose.
```

`await server?.waitForRequestsIdle?.(id)` fixes it:
https://github.com/tailwindlabs/tailwindcss/blob/85c3b2b6a208bead416bcb0b785aa3b2f6f554a8/packages/%40tailwindcss-vite/src/index.ts#L128

**Comment by adamwathan** [comment]
Hey! Upgrade to Vite 5.2+ and that will resolve the issue, we're using a very new API 👍

**Comment by Steffan153** [comment]
Actually my bad, this was fixed in https://github.com/tailwindlabs/tailwindcss/commit/3249777383489fa2996d7ad23181952911ea6ad2 already.
