### ISSUE TITLE
[v4] TailwindCSS error in Vite: i?.waitForRequestsIdle is not a function

### ISSUE THREAD

**Issue by devcaeg** [tailwindlabs/tailwindcss#13378]
**What version of Tailwind CSS are you using?**
v.next

**What build tool (or framework if it abstracts the build tool) are you using?**
vite (v5.1.6), @builder.io/qwik (v1.5.1), @builder.io/qwik-city (v1.5.1), @tailwindcss/vite (v.next)

**What version of Node.js are you using?**
v21.7.1

**What browser are you using?**
Chrome, Safari, Edge

**What operating system are you using?**
macOS

**Describe your issue**

I'm using the "next" version of TailwindCSS since v4 was announced, everything was working relatively well (some bugs or missing styles) but in less than 24 hours there was some change that doesn't let me start the project.

<img width="1470" alt="Captura de pantalla 2024-03-27 a la(s) 9 46 06 a  m" src="https://github.com/tailwindlabs/tailwindcss/assets/115333735/5b908b40-d3d1-4918-ac9e-4625d2ad77e3">

**Comment by adamwathan** [comment]
Hey! Update to Vite 5.2, this is a new API in Vite that was just added to support the sort of stuff we need to do in our plugin 👍

**Comment by devcaeg** [comment]
@adamwathan Excellent, this solved the problem. I had not updated to the latest version of Vite (v5.2.6), because for some reason when you are using TailwindCSS in this version of Vite, it has a bug. When you start the development mode and enter the web for the first time, it takes a long time to load, then everything works normally.
