### ISSUE TITLE
"@apply dark:" classes do not work on ":host" selectors in Angular scss files when "darkMode" strategy is set to "selector"

### ISSUE THREAD

**Issue by SeraphCoding** [tailwindlabs/tailwindcss#13374]
**What version of Tailwind CSS are you using?**
3.4.1

**What build tool (or framework if it abstracts the build tool) are you using?**
Angular 17.3.0 (and upwards)

**What version of Node.js are you using?**
20.12.0

**What browser are you using?**
Chrome

**What operating system are you using?**
Windows

**Reproduction URL**
https://github.com/SeraphCoding/hostApplyDarkDoesNotWork

**Describe your issue**
Using `dark:` classes in a components scss file will not work when using `@apply` on the `:host` element, while using `darkMode: "selector"`. It does work however when using the default approach utilizing media queries. Classes without `dark:` will work. 

In the example below the background for `my-component` will not turn blue, if the `<html>` element has the class `dark`.

Example SCSS file for `my-component.component.scss`
```scss
:host {
   @apply dark:bg-blue-500;
}
```
app.component.html
```html
<app-my-component />
```

tw config 
```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "selector",
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

**Workaround**:
The workaround is to apply the "dark:" class on the component in its implementation. 

So if I have a `my-component.component.ts` and I implement it in my `app.component.html` - I can work around this issue by applying the dark class here like so:

```html
<app-my-component class="dark:bg-blue-500" />
```

This does however force me to keep reusing classes, that I want this component to apply on it's host element automatically.

**Comment by thecrypticace** [comment]
Hey, so this is a known bug in Angular (see https://github.com/angular/angular/issues/45686). There is also an open PR for Angular to address this (see https://github.com/angular/angular/pull/49169).

For a bit more in-depth explanation of what's going on you can look at my comment about this issue from a while back: https://github.com/tailwindlabs/tailwindcss/issues/12352#issuecomment-1792285794

Ultimately not a Tailwind bug and not something we can fix on our end unfortunately. You do have the option of completely replacing the dark mode variant if you want to not include `:is()` but it'll be a little different in how it applies to elements. You can do this by using the `variant` dark mode strategy.

Your config would look like this:
```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['variant', '.dark &'], // I changed this line
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {},
  },
  plugins: [],
};
```
