### ISSUE TITLE
`<input>`s, `<button>`s, etc don't inherit letter spacing

### ISSUE THREAD

**Issue by mybearworld** [tailwindlabs/tailwindcss#13377]
**What version of Tailwind CSS are you using?**

For example: v3.4.0

**What build tool (or framework if it abstracts the build tool) are you using?**

PostCSS 8.4.32, also Vite 5.0.12

**What version of Node.js are you using?**

v18.16.0

**What browser are you using?**

Edge

**What operating system are you using?**

Windows

**Reproduction URL**

https://play.tailwindcss.com/IBKvBYzX9U

**Describe your issue**

`<input>`s, `<button>`s and other elements setting their own font don't get their `letter-spacing` property reset, so they don't inherit it from the parent.

**Comment by adamwathan** [comment]
Hey! This will be fixed in the next release 👍 

https://github.com/tailwindlabs/tailwindcss/pull/13328

**Comment by mybearworld** [comment]
Oh! I'm sorry, I didn't see that.
