### ISSUE TITLE
`fixed` element behaves like an `absolute` element in `dark mode`

### ISSUE THREAD

**Issue by mho22** [tailwindlabs/tailwindcss#13390]
**What version of Tailwind CSS are you using?**

v3.4.3

**What build tool (or framework if it abstracts the build tool) are you using?**

VueJS 3.0 

**What version of Node.js are you using?**

v21.7.1

**What browser are you using?**

Google Chrome v123.0.6312.58

**What operating system are you using?**

macOS 14.3.1

**Reproduction URL**

[Tailwind Play Link](https://play.tailwindcss.com/lHrrykaAyM)

**Describe your issue**

I still gave the informations above even if the Tailwind Play Link reproduces the problem. Anyway, based on the Tailwind Play link provided, the behavior of the `fixed` div changes when the `dark` class is applied to the root `div`.

When the `dark` class is not applied, the `div` with the `fixed` class behaves like a typical `fixed` div. However, when you apply the `dark` class to the root `div`, possibly because the `fixed` `div`'s parent has a `dark:` variant, it changes the behavior of the `fixed` `div` to that of an `absolute` `div`.

I can't explain why at the moment but I'm here to assist. Feel free to ask me anything.

**Comment by thecrypticace** [comment]
Hi! So what's happening here is that you are using `dark:invert` which is setting the `filter` property on a parent element. This is causing `fixed` to behave like `absolute`. This behavior is correct [according to the CSS spec](https://drafts.fxtf.org/filter-effects/#FilterProperty):

> A value other than none for the [filter](https://drafts.fxtf.org/filter-effects/#propdef-filter) property results in the creation of a [containing block](https://drafts.csswg.org/css-display-4/#containing-block) for absolute and fixed positioned descendants unless the element it applies to is a document root element in the current [browsing context](https://html.spec.whatwg.org/multipage/document-sequences.html#browsing-context). The list of functions are applied in the order provided.

Here's a Play demonstrating both cases: https://play.tailwindcss.com/VHqGZWVrrN

I did notice that this doesn't happen in Safari but that's actually a bug.

Closing as this is working as designed and we wouldn't be able to change it anyway.

**Comment by mho22** [comment]
Thank you for your time. I thought it was an issue. Apologies.
