### ISSUE TITLE
divide-y behavior with grid causes odd top border behavior

### ISSUE THREAD

**Issue by nwparker** [tailwindlabs/tailwindcss#13400]
**What version of Tailwind CSS are you using?**
3.4.3

**What build tool (or framework if it abstracts the build tool) are you using?**
N/A

**What version of Node.js are you using?**
N/A

**What browser are you using?**
Chrome

**What operating system are you using?**
Mac

**Reproduction URL**
https://play.tailwindcss.com/1XdwsvlrXe

**Describe your issue**
Top most borders appear oddly / non-uniformly

![image](https://github.com/tailwindlabs/tailwindcss/assets/4138956/de1de8fe-66a2-4d0c-802a-5d21f698575f)

**Comment by adamwathan** [comment]
Hey! This is the expected outcome in this case — all `divide-y` does is add a top border to every item except the first one, there's no way for it to do anything magical/special because the items are in a grid or anything.

So what you're seeing is Item 1 has no border, but Item 2 through Item 6 have a top border.

When I'm trying to add grid lines in a grid, I'll often use a background color with a gap on the grid instead, might work for your situation:

https://play.tailwindcss.com/XuV1PCAdzp

```html
<div class="grid grid-cols-3 gap-y-2 bg-gray-200">
  <div class="bg-white">Item 1</div>
  <div class="bg-white">Item 2</div>
  <div class="bg-white">Item 3</div>
  <div class="bg-white">Item 4</div>
  <div class="bg-white">Item 5</div>
  <div class="bg-white">Item 6</div>
</div>
```

**Comment by holic** [comment]
Could you unset the divide width via `grid-cols-*` for the first number of elements as dictated by the number of columns?
```css
/* may need to filter this on `[hidden]` like divide does */
.grid-cols-3 :nth-child(-n + 3) {
  --tw-divide-width: 0;
}

```

**Comment by holic** [comment]
I ended up solving this with a plugin for my specific use case. Unfortunately has to use a gnarly selector to get specificity precedence for the border width override:

```ts
export const gridDivideFix = plugin(function ({ addComponents }) {
  addComponents({
    // TODO: more column/divide sizes
    ".grid-cols-2.divide-y": {
      // this selector is to achieve higher specificity than the divide one, but is gross
      // TODO: make this better
      // TODO: can we do this with vars instead of unsetting a property here?
      "& > :not([hidden]) ~ :not([hidden]):nth-child(-n + 2)": {
        borderTopWidth: "0",
        borderBottomWidth: "0",
      },
    },
  });
});
```
