### ISSUE TITLE
Tailwind CDN page is empty

### ISSUE THREAD

**Issue by ezani92** [tailwindlabs/tailwindcss#13429]
**What version of Tailwind CSS are you using?**

For example: v2.0.4

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: postcss-cli 8.3.1, Next.js 10.0.9, webpack 5.28.0

**What version of Node.js are you using?**

For example: v12.0.0

**What browser are you using?**

For example: Chrome, Safari, or N/A

**What operating system are you using?**

MAC OS CHROME

**Reproduction URL**

https://cdn.tailwindcss.com/

**Describe your issue**

CDN stop working. When i visit the CDN site. it return empty instead of showing script

**Comment by tttpeng** [comment]
same

**Comment by madeintwenty** [comment]
same. We are in emergency

**Comment by dustinrouillard** [comment]
I just switched to using the version'd route for now as that seems to work.
https://cdn.tailwindcss.com/3.4.3

**Comment by wdmahbubur** [comment]
Same. I have a prototype project, client will give demo today, but now CDN is not working. 😭😭

**Comment by wdmahbubur** [comment]
> I just switched to using the version'd route for now as that seems to work. https://cdn.tailwindcss.com/3.4.3

Thank you

**Comment by yugjadvani-dev** [comment]
> I just switched to using the version'd route for now as that seems to work. https://cdn.tailwindcss.com/3.4.3

Thanks You

**Comment by asaxena1415** [comment]
pls fix urgently!

**Comment by AlexanderKozhevin** [comment]
I had to migrate like 12 links in production projects

**Comment by samazgor** [comment]
Mine too. Any solution so far?

**Comment by samazgor** [comment]
> I just switched to using the version'd route for now as that seems to work. https://cdn.tailwindcss.com/3.4.3

Thanks

**Comment by brandonmcconnell** [comment]
It appears to be fixed now, with https://cdn.tailwindcss.com/ redirecting to https://cdn.tailwindcss.com/3.4.3.

Can anyone else confirm that?

**Comment by dustinrouillard** [comment]
Can confirm

**Comment by dustinrouillard** [comment]
> It appears to be fixed now, with https://cdn.tailwindcss.com/ redirecting to https://cdn.tailwindcss.com/3.4.3.
> 
> Can anyone else confirm that?

Can confirm

**Comment by hcweb** [comment]
same 😭😭

**Comment by JiSikKim** [comment]
For unavoidable reasons, my company was using it for production services and I was surprised.

**Comment by RobinMalfait** [comment]
Hey!

Sorry about the inconvenience, I'm not too sure what happened over night but it seems to be working again.

For the people using this in production, please try and migrate to a proper build because the Play CDN is designed for development purposes only.

More info: https://tailwindcss.com/docs/installation
