### ISSUE TITLE
[V4] Box Shadow Color doesn't work

### ISSUE THREAD

**Issue by alexhtech** [tailwindlabs/tailwindcss#13438]
**What version of Tailwind CSS are you using?**

For example: 4.0.0-alpha.11

**What build tool (or framework if it abstracts the build tool) are you using?**

nextjs@14

**What version of Node.js are you using?**

For example: v21.7.1

**What browser are you using?**

For example: Chrome

**What operating system are you using?**

For example: macOS

**Reproduction URL**

https://github.com/alexhtech/tailwindcss4-test

**Describe your issue**

`<div className="h-20 w-20 shadow-xl shadow-red-500" />` - color isn't applied it tends to be `rgba(0,0,0, 0.1)`

**Comment by RobinMalfait** [comment]
Hey!

You mentioned that you are using Chrome but I'm 99% sure you are using Firefox. If that's the case then this is currently expected behaviour.

We rely on `@property` which isn't supported in Firefox yet. You can use Firefox Nightly and I believe it should be available in the release of May in normal Firefox.

Are you using Firefox by any chance?

**Comment by ashley-hunter** [comment]
I'm seeing this issue in Chrome too, seems `--tw-shadow-colored` doesn't use `var(--tw-shadow-color)` when using `shadow-xl`:

<img width="329" alt="image" src="https://github.com/tailwindlabs/tailwindcss/assets/20795331/c90da932-4d87-4b76-999a-4aa9ed2a2a89">

Compared to just `shadow` which does include it:

<img width="328" alt="image" src="https://github.com/tailwindlabs/tailwindcss/assets/20795331/4be56c38-40d0-41fc-8616-1ad9e826366a">

Updating `--tw-shadow-colored` to the following resolves the issue.

```css
 --tw-shadow-colored: 0 20px 25px -5px var(--tw-shadow-color), 0 8px 10px -6px var(--tw-shadow-color);
```

**Comment by adamwathan** [comment]
Looked into this quickly — definitely a real bug, regression we introduced when we started including the `var(...)` function call in resolved theme values. Fix is a bit more complicated than I hoped, will take a peek tomorrow!
