### ISSUE TITLE
[V4] - @keyframes not being hoisted into built css

### ISSUE THREAD

**Issue by The-Code-Monkey** [tailwindlabs/tailwindcss#13458]
**What version of Tailwind CSS are you using?**

4.0.0-alpha.13

**What build tool (or framework if it abstracts the build tool) are you using?**

Tailwindcss/cli

**What version of Node.js are you using?**

Not using node using bun

**What browser are you using?**

Chrome

**What operating system are you using?**

MAC

**Reproduction URL**

[repoduction](https://codesandbox.io/p/devbox/trusting-black-rwpl6n?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clums4zgt00083b6iav5neh6g%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clums4zgt00033b6iszuw4zz0%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clums4zgt00063b6i2me8z3l6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clums4zgt00073b6iisvv707h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clums4zgt00033b6iszuw4zz0%2522%253A%257B%2522id%2522%253A%2522clums4zgt00033b6iszuw4zz0%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clums4zgt00073b6iisvv707h%2522%253A%257B%2522id%2522%253A%2522clums4zgt00073b6iisvv707h%2522%252C%2522activeTabId%2522%253A%2522clums5g10001y3b6ixpz7muvr%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clums5g10001y3b6ixpz7muvr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clums4zgt00063b6i2me8z3l6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clums4zgt00043b6in3qal21y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clums4zgt00053b6ixr07cfg7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clthehtu2004tdijpdg4g358j%2522%257D%255D%252C%2522id%2522%253A%2522clums4zgt00063b6i2me8z3l6%2522%252C%2522activeTabId%2522%253A%2522clums4zgt00043b6in3qal21y%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Describe your issue**

The keyframe value should be put into the css but it isnt being

**Comment by RobinMalfait** [comment]
Hey!

The `@keyframes` will only be injected if they are used as one of the `--animate` configuration values. E.g.:
```css
@theme {
  @keyframes mixin { /* … */ }
  
  --animate-mixin: mixin 1s linear infinite;
  /*        ^^^^^ */
}
```

If you always want to inject the `@keyframes`, then you can take it out of the `@theme` rule and store it as a sibling.

Hope this helps!
