### ISSUE TITLE
Vendor prefix not being applied for `backdrop-filter`, using CLI tool

### ISSUE THREAD

**Issue by brandonmcconnell** [tailwindlabs/tailwindcss#13475]
## What version of Tailwind CSS are you using?

v3.4.3

## What browser are you using?

Chrome v123.0.6312.107 (Official Build) (arm64)
Safari v17.4.1 (19618.1.15.11.14)

## What operating system are you using?

macOS Sonoma v14.4.1 (23E224)

## Reproduction URL

https://play.tailwindcss.com/gO656Xsgjh

## Describe your issue

The [documentation states](https://tailwindcss.com/docs/browser-support#vendor-prefixes) that "If you’re using the Tailwind CLI tool, vendor prefixes like this will be added automatically."

However, in the case of `backdrop-filter`, the needed `webkit` filter does not appear to get applied, preventing Safari from blurring the backdrop.

| Chrome | Safari |
|--------|--------|
| ![](https://github.com/tailwindlabs/tailwindcss/assets/5913254/087ab04c-4582-4b9e-ab76-d32ec19155cc) | ![](https://github.com/tailwindlabs/tailwindcss/assets/5913254/2dd56697-36c1-4ce6-a4ca-5780b2d45541) | 

In this example below, I add the vendor-prefixed style, and you can see the blur take effect:
https://play.tailwindcss.com/6KUJEBtoue

![](https://github.com/tailwindlabs/tailwindcss/assets/5913254/694af0ce-4bb9-401b-8aa7-c07246be56be)

**Comment by adamwathan** [comment]
Hey! Just tried to reproduce this but I can't — I see the `-webkit-*` prefix being generated when using the CLI:

<img width="1061" alt="image" src="https://github.com/tailwindlabs/tailwindcss/assets/4323180/bac08d6d-dbea-4bab-b8f7-1c5f1f3ed5d8">

Can you share a proper reproduction? If it's an issue that only shows up using the CLI we'll need a GitHub repo using the CLI.

**Comment by brandonmcconnell** [comment]
@adamwathan Ah, I mistakenly thought the Play CDN was running the CLI under the hood.

Enabling the PostCSS plugin in my local instance fixed the issue per the docs' instructions.

Thanks! Closing this issue.
