### ISSUE TITLE
Yarn 2 compatible executable (npx)

### ISSUE THREAD

**Issue by ConsoleTVs** [tailwindlabs/tailwindcss#1350]
When trying to execute the npx tailwind command it fails, that's why yarn 2 have what's known as `yarn dlx` to execute a binary in a temp environment (https://yarnpkg.com/cli/dlx). However, when trying to run the tailwind binary using the new `yarn dlx` command, the following is prompted:

```
$ yarn dlx tailwind init
```

```
Internal Error: Binary not found (tailwind) for root-workspace-0b6124@workspace:.
    at m (E:\<PROJECT_ROOT>\.yarn\releases\yarn-rc.js:24:7171)
    at async Object.t.executeWorkspaceAccessibleBinary (E:\<PROJECT_ROOT>\.yarn\releases\yarn-rc.js:24:9551)
    at async u.execute (E:\<PROJECT_ROOT>\.yarn\releases\yarn-rc.js:58:123405)
    at async u.validateAndExecute (E:\<PROJECT_ROOT>\.yarn\releases\yarn-rc.js:24:40434)
    at async c.run (E:\<PROJECT_ROOT>\.yarn\releases\yarn-rc.js:36:533800)
    at async c.runExit (E:\<PROJECT_ROOT>\.yarn\releases\yarn-rc.js:36:533934)
```

**Comment by julienpa** [comment]
If you don't have tailwindcss installed globally or locally with npm, then the `tailwind` executable is not available as it's installed when you install tailwindcss (understood that by reading this [older issue](https://github.com/tailwindcss/discuss/issues/304))

In order to fix this command above, you need to do something like:
```
yarn dlx tailwindcss init tailwind.js
```
(note the tailwind**css** command)

You then get the expected:
```
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 2.25s
➤ YN0000: ┌ Fetch step
➤ YN0013: │ electron-to-chromium@npm:1.3.395 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 0.08s
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0.13s
➤ YN0000: Done in 2.47s


   tailwindcss 1.2.0

   ✅ Created Tailwind config file: tailwind.js
```

**Comment by adamwathan** [comment]
Use the tailwindcss binary, the tailwind binary is deprecated and no longer documented.

**Comment by julienpa** [comment]
How does one use the tailwindcss binary with Yarn 2?
I installed tailwindcss with `yarn add tailwindcss --dev` but I don't have anything in `./node_modules/.bin/`.
I ended up installing tailwindcss as a global npm package to have access to `tailwind` in my npm/yarn scripts.

**Comment by julienpa** [comment]
After reading the doc again, I'm guessing I could use `npx tailwindcss` everywhere.
Will give this a try.

**Comment by tlgreg** [comment]
As per docs, the `yarn run` command should still work. If there is no script for it in `package.json` it should match with a local binary. The `tailwind` command is deprecated though as Adam said above, so it should be:
`yarn run tailwindcss <command>`

**Comment by ConsoleTVs** [comment]
This can be closed I assume if the provided solutions work then @adamwathan. I will let you close it in case this was not the final solution. Didn't have time to check it out yet.

**Comment by hhsm95** [comment]
> As per docs, the `yarn run` command should still work. If there is no script for it in `package.json` it should match with a local binary. The `tailwind` command is deprecated though as Adam said above, so it should be: `yarn run tailwindcss <command>`

This is the answer, use: `yarn run tailwindcss init -p` instead of `npx tailwindcss init -p`
