### ISSUE TITLE
[V4] @tailwindcss-vite: Cannot read properties of undefined (reading 'send')

### ISSUE THREAD

**Issue by rohmann** [tailwindlabs/tailwindcss#13524]
Using `tailwind` `4.0.0-alpha.14` and `@tailwindcss-vite` `4.0.0-alpha.14` with Storybook and Vite I'm getting this error:

```
[vite] Internal server error: Cannot read properties of undefined (reading 'send')
```

The error is coming from this line: https://github.com/tailwindlabs/tailwindcss/blob/b07cc4d3bd039de1874472a0036bc97a7f5b3c85/packages/%40tailwindcss-vite/src/index.ts#L53

I was able to get it working by updating the first line to ensure the `hot` property is available first.

https://github.com/tailwindlabs/tailwindcss/blob/b07cc4d3bd039de1874472a0036bc97a7f5b3c85/packages/%40tailwindcss-vite/src/index.ts#L26

```ts
function updateCssModules(isSSR: boolean) {
    // If we're building then we don't need to update anything
    if (!server?.hot) return
```

Regretfully, I don't have a repro. I'm using Bun + Storybook + Vite + Tailwind and this only happens when Storybook is running Vite.   I'm not sure of a more isolated way to reproduce it, but it seems like in some edge cases it's possible for `updateCssModules` to be triggered before the server is ready for sending `hot` updates.

**Comment by rohmann** [comment]
Apollogies, it's *partially* working. I'm not getting all utility classes. I'll re-open if I have something consistently reproducible or solved.

**Comment by johnfn** [comment]
I'm also seeing this.
