### ISSUE TITLE
Missing `exports` field in the package.json file

### ISSUE THREAD

**Issue by jakubmazanec** [tailwindlabs/tailwindcss#13527]
**What version of Tailwind CSS are you using?**

3.4.3

**Reproduction URL**

https://github.com/jakubmazanec/tailwind-exports-bug

Steps:

```
npm install
npm run typecheck
```

**Describe your issue**

In some configurations, TypeScript needs `exports` field in the package.json file of the `tailwindcss` package. Otherwise code like this:

```TypeScript
import {type Config} from 'tailwindcss';
import plugin from 'tailwindcss/plugin';

export type CreateTailwindConfigOptions = {
  content: string[];
};

export function createTailwindConfig({content}: CreateTailwindConfigOptions): Config {
  return {
    content,
    plugins: [
      plugin(({addVariant}) => {
        addVariant('ui-icon', [`&[data-icon]`, `:where([data-icon]) &`]);
      }),
    ],
  };
}
```

leads to an error:

```
source/main.ts:2:20 - error TS2307: Cannot find module 'tailwindcss/plugin' or its corresponding type declarations.

import plugin from 'tailwindcss/plugin';
                   ~~~~~~~~~~~~~~~~~~~~
```

If I add `exports` for this particular use case, error goes away:

```json5
{
  "name": "tailwindcss",
  "version": "3.4.3",
  // ...
  "exports": {
    ".": {
      "types": "./types/index.d.ts",
      "require": "./lib/index.js",
      "import": "./lib/index.js"
    },
    "./plugin": {
      "types": "./plugin.d.ts",
      "require": "./plugin.js",
      "import": "./plugin.js"
    }
  },
  // ...
}
```

**Comment by thecrypticace** [comment]
Unfortunately, for Tailwind v3, utilizing an `exports` field is not possible. Adding an `exports` field _can_ often be a backwards incompatible change — especially for anything relying on internals. Though it depends entirely on the exports you add. A lot of our own tools (e.g. intellisense and Prettier) rely on internals for v3 and earlier and as such cannot operate with this change.

I was going to look at your repo's `tsconfig.json` to see if I could suggest some alternative config settings but the repo is empty. If you update your repo and let me know I'll take a look at it!

**Comment by jakubmazanec** [comment]
Thank you for the quick reply. You can look at the repo (I forgot to push, but it should be ok now), but please don't waste too much time - I'll just add some temporary fix while waiting for v4.
