### ISSUE TITLE
Tailwindcss can't be able to capitalize UPERCASE default text

### ISSUE THREAD

**Issue by kralion** [tailwindlabs/tailwindcss#13549]
**What version of Tailwind CSS are you using?**

For example: v3.2.7

**What build tool (or framework if it abstracts the build tool) are you using?**

For example:  Next.js 13.5

**What version of Node.js are you using?**

For example: v20.10

**What browser are you using?**

For example: Chrome

**What operating system are you using?**

For example:  Windows

**Reproduction URL**

https://play.tailwindcss.com/tX6nnIZbP2

**Describe your issue**

I expect that UPPERCASE default **text** should be transformed to `capitalize` but it doesn't work

**Comment by adamwathan** [comment]
Hey! That’s just not what the CSS text-transform feature does I’m afraid, not something that’s in our control. Uppercase characters are preserved as per the spec:

https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform#capitalize

**Comment by kralion** [comment]
Thanks man 👍
