### ISSUE TITLE
ERROR - Module not found - Can't resolve './${previewSrc}'

### ISSUE THREAD

**Issue by nicitaacom** [tailwindlabs/tailwindcss#13616]
Original issue - https://github.com/vercel/next.js/issues/63091#issuecomment-2082927182
re-created here because this issue not related to next.js - but its related to tailwind

**What version of Tailwind CSS are you using?**

package.json
```json
 "devDependencies": {
    "tailwindcss": "latest",
}
```

Tailwind CSS IntelliSense
v0.10.5

**What build tool (or framework if it abstracts the build tool) are you using?**

package.json
```json
    "next": "14.2.0",
```

**What version of Node.js are you using?**

```bash
node -v                          
v20.0.0
```

**What browser are you using?**

Chrome

**What operating system are you using?**

Kali linux (how it might help you?)

**Reproduction URL**

https://codesandbox.io/p/devbox/mvp-cannot-resolve-previewsrc-8kfn23

**Describe your issue**

ERROR - Module not found - Can't resolve './${previewSrc}'

More information see in `Reproduction URL`

**Comment by RobinMalfait** [comment]
Hey!

In the `VideoOverlay.tsx` file you have the following code:

```ts
<div
  className={`preview bg-[url('${previewSrc}')] absolute inset-0 z-[1] bg-cover bg-no-repeat`}
  onClick={() => {
    playPauseVideo()
  }}
></div>
```

Tailwind CSS itself doesn't execute your code, so it generates the `bg-[url(…)]` as-is (more info: https://tailwindcss.com/docs/content-configuration#dynamic-class-names). This means that it generates the following CSS:
```css
.bg-\[url\(\'\$\{previewSrc\}\'\)\] {
  background-image: url('${previewSrc}');
}
```

Once that is generated, Next.js does optimizations for (background) images. In this case, it will look for `url('${previewSrc}')` which doesn't exist on disk. Note: this would also happen without Tailwind CSS if you used that literal string in the `background-image`.

To solve your issue, I would recommend to use a CSS variable instead:
```diff
  <div
-   className={`preview bg-[url('${previewSrc}')] absolute inset-0 z-[1] bg-cover bg-no-repeat`}
+   className={`preview bg-[url:var(--preview-src))] absolute inset-0 z-[1] bg-cover bg-no-repeat`}
+   style={{ '--preview-src': `url(${previewSrc})` }}
    onClick={() => {
      playPauseVideo()
    }}
  ></div>
```

This way, Tailwind generates the following CSS for `bg-[url:var(--preview-src))]`:
```css
.bg-\[url\:var\(--preview-src\)\] {
  background-image: var(--preview-src);
}
```

Now you can generate the `--preview-src` dynamically at runtime using the `style` prop.

Hope this helps!

**Comment by nicitaacom** [comment]
```
Object literal may only specify known properties, and ''--preview-src'' does not exist in type 'Properties<string | number, string & {}>'.typescript(2353)
index.d.ts(1982, 9): The expected type comes from property 'style' which is declared here on type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'
```

![image](https://github.com/tailwindlabs/tailwindcss/assets/39565703/c3074abd-379f-433c-8793-b36cd2965143)


It doen't work in way you described

Here is editor permissions - https://codesandbox.io/p/devbox/mvp-cannot-resolve-previewsrc-8kfn23
Send me code that you mean
