### ISSUE TITLE
[Feature Proposal]: Utilities for the CSS "inherit" keyword

### ISSUE THREAD

**Issue by lilisgeorge** [tailwindlabs/tailwindcss#1361]
Hi,

There are cases where using inherit css keyword would make more sense. Especially when you have a calculated css rule and need to inherit from that rather than duplicating it

e.g.
Instead of ...
``` css
.parent {
  min-height: calc(100vh - 3rem);
}
.parent > .child {
  min-height: calc(100vh - 3rem);
}
```

```html
<div class="calculated-class">
  <div class="child">...</div>
</div>
```

... better have a dedicated utility
``` css
.parent {
  min-height: calc(100vh - 3rem);
}
.min-h-inherit {
  min-height: inherit;
}
```

```html
<div class="calculated-class">
  <div class="min-h-inherit">...</div>
</div>
```

Keep up the good work.

Regards,
GL

**Comment by keith0305** [comment]
+1. Thanks for raising this. I too, find myself extending Tailwind for this purpose in almost every project.

**Comment by le717** [comment]
I would like to take this. We're getting hit at my job by the lack of native inherit support and I've been working on a PR to add support. What all properties should be granted inheritance? So far, I've added `background-color`, `color`, `border-color`, `[min-max-]h` and `[min-max]w`. Are there other things that might benefit from an `inherit` util?

**Comment by adamwathan** [comment]
Trying to figure out why I’ve never needed this — in the first example could you not use height: 100% for the child, or use flexbox to solve it?

**Comment by le717** [comment]
[min-]height: 100% doesn't work. I tested it using the test case given by @lilisgeorge and added a border to each container to visually see the height of the child element. `min-height: inherit` is the only thing that causes the child's height to match the parent's height.

I think it fails because `calc()` is being used. height: 100% requires the parent element to have an "absolute" value, absolute in this case meaning it's something the browser computed as part of the normal render routine. Since it's a dynamically calculated value that "absoluteness" is tossed out so the child element doesn't know what "100%" is. It can only inherit whatever that value is.

I know that's probably not the most technically accurate theory but that's how I've come to understand it.

I've not looked at the code lately, but I believe whenever this came up, flexbox did not work due to the way the application code is structured.

```html
<!-- My test case html showing only inherit works correctly-->
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="/dist/tailwind.css">
    <title>Hello, world!</title>
    <style>
      .parent {
        min-height: calc(100vh - 3rem);
      }
      .parent > .child {
        /* min-height: calc(100vh - 3rem); */
        /* height: 100%; */
        /* min-height: 100%; */
        min-height: inherit;  /* only this works */
      }
    </style>
  </head>
  <body class="p-4">
    <div class="parent border-4 border-solid border-blue-600 p-2">
      parent
      <div class="child border-4 border-solid border-pink-500">child</div>
    </div>
    </div>
  </body>
</html>
```

**Comment by lilisgeorge** [comment]
Hi again,

This is a sample of a layout I was experimenting back then, where it fails with height: 100% or min-height: 100% but works with min-height: inherit.

```html
<body class="bg-green-300 relative pt-12">
  <div class="bg-white h-12 absolute top-0 left-0 right-0 w-full">
    header
  </div>
  <div class="main">
    <!-- try replacing min-h-inherit with h-full or min-h-full to see it failing. For some reason it stops forcing to stretch full height -->
    <div class="bg-gray-200 min-h-inherit">
      Content
    </div>
  </div>
</body>
```

```css
.main {
  min-height: calc(100vh - 3rem);
}

.min-h-inherit {
  min-height: inherit;
}
```

**Comment by rightaway** [comment]
I added this to my config file and think it would be a good addition to the default config

```
theme: {
  extend: {
    colors: {
      inherit: 'inherit'
    }
  }
}
```

**Comment by wesort** [comment]
Adding a use case for this: _I want a child element to inherit the background colour._

Specifically, I'm positioning something absolutely on top of another element and need that parent's background colour to cascade naturally and on hover.

```
<div class="relative w-8 h-8 bg-white hover:bg-gray-300">
  <IconClock></IconClock>
  <div class="absolute bg-inherit">
    <div>H</div>
  </div>
</div>
```
