### ISSUE TITLE
not working in docker

### ISSUE THREAD

**Issue by tsukinoko-kun** [tailwindlabs/tailwindcss#13709]
**What version of Tailwind CSS are you using?**

3.4.3

**What build tool (or framework if it abstracts the build tool) are you using?**

Docker Compose

**What version of Node.js are you using?**

For example: 20.13.1

**What browser are you using?**

N/A

**What operating system are you using?**

macOS

**Describe your issue**

When running tailwindcss cli in a docker container, it isn't doing anything. Exits with code 0.

```Dockerfile
FROM node:current-bullseye
WORKDIR /App/BlazorApp
RUN ["npm", "install", "-g", "pnpm"]
ENTRYPOINT ["bash", "-c", "pnpm install && pnpm exec tailwindcss -i ./Styles/app.css -o ./wwwroot/app.css --watch"]
```

Isn't working with or without `--watch`.
Isn't working with or without `tty: true` in compose.yaml (#5324).

If I run the same thing outside of Docker it works as expected.

**Comment by tsukinoko-kun** [comment]
I ensured that the tailwind config, package.json, input files (css, html, razor) are available and the container has write access.

**Comment by maxdzin** [comment]
@tsukinoko-kun maybe `stdin_open: true` along with `tty: true` will help for your case?

**Comment by kashw2** [comment]
`node:current-bullseye` is currently pulling NodeJS 22.2.0.

Is it not possible that recent changes with Node 22 to how ESM / Require / Import syntax is handled internally that [this](https://github.com/tailwindlabs/tailwindcss/blob/b01283cc9b66cf830d87cbfe1fbb5ebb8561226a/src/lib/load-config.ts#L29-L36) is causing issue?

If you instead opt for a current LTS version of the Node docker image such as `20-bullseye` does this issue persist?

**Comment by thecrypticace** [comment]
You'll want to specify both `stdin_open: true` _and_ `tty: true` in a docker compose file or you can run with the flags `-t` and `-I`. Our CLI exits when stdin is closed — this is a standard behavior for CLI tools. Alternatively, you can specify `--watch=always` which will not exit when stdin closes.

Here's an example compose file that works:

```
services:
  web:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: ./app
        target: /App/BlazorApp
```

Or an example docker run command (assumes code is located at ./app in the current dir):
```
docker run -dti -v $(pwd)/app:/App/BlazorApp $(docker build -q .)
```
