### ISSUE TITLE
`<alpha-value>` is not recognized on reuse

### ISSUE THREAD

**Issue by Serator** [tailwindlabs/tailwindcss#13716]
**What version of Tailwind CSS are you using?**

v3.4.3 (last)

**Reproduction URL**

https://play.tailwindcss.com/iK3QZJynRz?file=config

**Describe your issue**

<img width="800" alt="image" src="https://github.com/tailwindlabs/tailwindcss/assets/625005/d43b6f8d-47a8-4994-8568-3767c0ce76cb">

Tailwind config
```
/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: {
      colors: {
                                         ⬇⬇⬇⬇⬇⬇⬇⬇                     ⬇⬇⬇⬇⬇⬇⬇⬇
        primary: 'light-dark(rgb(0 0 0 / <alpha-value>), rgb(255 255 255 / <alpha-value>))',
      }
    },
  },
}
```

CSS
```
                              ⬇⬇                     ⬇⬇⬇⬇⬇⬇⬇⬇
color: light-dark(rgb(0 0 0 / 0.5), rgb(255 255 255 / <alpha-value>));
```

When adding a color to a Tailwind setting with more than one use of `<alpha-value>` in a single value, only the first occurrence of `<alpha-value>` is recognized.

More information is available [here](https://github.com/tailwindlabs/tailwindcss/discussions/12172#discussioncomment-9236533) (сс @olyckne).

**Comment by thecrypticace** [comment]
The fix for this was merged. Will look at tagging a patch release next week 👍

**Comment by thecrypticace** [comment]
v3.4.4 has been released with the fix — you can see the Play now works too! ✨
