### ISSUE TITLE
Vulnerable Dependency - micromatch 

### ISSUE THREAD

**Issue by JagdeepThakur** [tailwindlabs/tailwindcss#13721]
Bump micromatch  to avoid vulnerabilities 

References:

https://github.com/micromatch/micromatch/issues/249

**Comment by LWX-Praveen** [comment]
I am facing the similar issue for the micromatch and braces.

**Comment by vaibhav00018** [comment]
Any solution for this, Facing the same issue for micromatch and braces.

**Comment by reinink** [comment]
Hey thanks for bringing this to our attention.

You can fix this issue in your project by upgrading to the latest versions of the `braces` and `micromatch` packages:

```sh
npm upgrade braces micromatch
```

Tailwind CSS doesn't have any version constraints in place that would prevent you from getting on the latest versions of these packages.

Worth also mentioning that when installing Tailwind CSS fresh you'll get these latest versions.

Hope that helps 👍
