### ISSUE TITLE
Classes generation error using symlink

### ISSUE THREAD

**Issue by ScreamZ** [tailwindlabs/tailwindcss#13731]
**What version of Tailwind CSS are you using?**
(next-cli)
```
dependencies:
next 14.2.3
react 18.3.1
react-dom 18.3.1

devDependencies:
@types/node 20.12.12
@types/react 18.3.2
@types/react-dom 18.3.0
postcss 8.4.38
tailwindcss 3.4.3
typescript 5.4.5       
```

**What build tool (or framework if it abstracts the build tool) are you using?**

NextJS

**What version of Node.js are you using?**

v20.11.1

**What browser are you using?**

Firefox tested, also chrome

**What operating system are you using?**

MacOS

**Reproduction URL**

https://github.com/ScreamZ/bug-tw

**Describe your issue**

For a project, I've been in the need of duplicating pages in two separated folders. Therefore tailwind is silently not generating classes (after restart of the dev server).

Then when starting the server it generate classes that it found, but once the page is rendered, it's not able to generate new classes (that doesn't already exists in the generated file).

If you remove the symlink it works again after restart.

Repro instruction in readme of repo

Thanks

**Comment by thecrypticace** [comment]
Hey, so this looks to be a bug in Next.js. It seems the criteria for this bug are as follows:
- Next 14
- A PostCSS plugin runs and registers _any_ path as a `dir-dependency`
- There's a symlink present somewhere inside `./src/app`. Just inside `src` is NOT sufficient. The destination can point anywhere _as long as the file exists_
- The symlink MUST use a relative target. Absolute symlinks do not trigger the bug.
- That symlink doesn't even need to be a JS file. You could even do something like `ln -s ../../../something.txt` as long as `something.txt` exists in the relevant location.

- Note: if the symlink points to a file that does not exist the Next dev server starts compiling on the first request but never finishes. This happens for both relative and absolute path symlinks. I think this is a separate bug but seems interesting enough to note here.


Tailwind itself doesn't even need to be involved here. The following plugin is sufficient to trigger the bug:

```js
// my-plugin.js
const path = require("path");

module.exports = function myPlugin() {
  return {
    postcssPlugin: "my-plugin",
    plugins: [
      function (root, result) {
        console.log("My plugin was called");

        result.messages.push({
          plugin: "my-plugin",
          parent: result.opts.from,
          type: "dependency",
          file: path.resolve(__dirname, "./src/app/page.tsx"),
        });

        // If you comment out this call the plugin will be called whenever ./src/app/page.tsx is saved
        result.messages.push({
          plugin: "my-plugin",
          parent: result.opts.from,
          type: "dir-dependency",
          dir: path.resolve(__dirname, "./src/app"),
          glob: "**/*.tsx",
        });

        return root;
      },
    ],
  };
};

module.exports.postcss = true;
```

And be sure to load the plugin in your PostCSS config:
```js
// postcss.config.mjs
import { createRequire } from "module";
const require = createRequire(import.meta.url);

/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    [require.resolve("./my-plugin.js")]: {},
  },
};

export default config;
```

All in all this isn't a Tailwind bug but looks to be a bug in Next that's related to the app directory. I don't think there's anything we can do to work around it either. Sorry :(
