### ISSUE TITLE
Col-end does not support negative values

### ISSUE THREAD

**Issue by eloyesp** [tailwindlabs/tailwindcss#13754]
This is a very small issue, col-end does not support negative values out of the box, but negative values makes a lot of sense there. This happens on **v3.4.3**.

https://play.tailwindcss.com/8L8o0VhDfr

The code is here:

~~~ html
<div class="grid grid-cols-3">
  <div class="-col-end-1">BROKEN</div>
  <div class="col-end-[-1]">WORKS</div>
</div>
~~~

I'm not sure if this is exactly a bug, because it is not explicitly described in the documentation, but it is a broken expectation (I've expected that to work for consistency).

**Comment by thecrypticace** [comment]
I've added support for this and it'll be available in the next patch release for v3 (and the next alpha for v4). 👍 

I'm planning to tag a patch release for v3 this week (probably tomorrow or Wednesday)

**Comment by thecrypticace** [comment]
v3.4.4 has been released with the fix — you can see the Play now works too! ✨
