### ISSUE TITLE
Small bug on negative 0.5 classes (like "-left-0.5")

### ISSUE THREAD

**Issue by eloyesp** [tailwindlabs/tailwindcss#13782]
When using 0.5 as negative value, tailwind generates "-foo-0" as an extra class on the generated css.

Here is the reproduction of the issue on play: https://play.tailwindcss.com/5zq4jfVadZ using v3.4.3

~~~ html
<div class="fixed -inset-0.5 -left-0.5">Hy</div>
~~~

And the generated css ends with:

~~~ css
.-inset-0 {
  inset: -0px;
}
.-inset-0\.5 {
  inset: -0.125rem;
}
.-left-0 {
  left: -0px;
}
.-left-0\.5 {
  left: -0.125rem;
}
~~~

It is not a big bug in this case, just two extra lines on the css, but may be it have other escenarios with a bigger impact. Regards.

**Comment by barvian** [comment]
I just ran into this too. It looks like it's a known limitation: https://github.com/tailwindlabs/tailwindcss/issues/9354#issuecomment-1254034051

**Comment by adamwathan** [comment]
Yeah unfortunately this is a limitation of the regex-based JS parser in v3 as mentioned in the linked comment. The good news is that the v4 parser handles this better and won't pick up `-left-0` 👍 

Going to close this one since it's an intentional trade-off but will be better in the future!
