### ISSUE TITLE
[v4] Default values do not include CSS variables

### ISSUE THREAD

**Issue by lubomirblazekcz** [tailwindlabs/tailwindcss#13834]
**What version of Tailwind CSS are you using?**

v4.0.0-alpha.16

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite 5.3.0

**What version of Node.js are you using?**

v18.20.0

**What browser are you using?**

N/A

**What operating system are you using?**

macOS

**Reproduction URL**
https://play.tailwindcss.com/A2WnHpJjBq

**Describe your issue**
Default values such as `rounded`, `blur`, `shadow` etc. doesn't include correct variable eg. `var(--rounded, 0.25rem)` same way as `rounded-xl` and others.

These values are included correctly in default theme though.

**Comment by thecrypticace** [comment]
Thanks for reporting this one. I've merged in the fix for this — it'll go out in the next alpha release of v4. 👍
