### ISSUE TITLE
[Bug] Adding a custom directive to `theme.extend.screens` breaks other breakpoints.

### ISSUE THREAD

**Issue by hirasso** [tailwindlabs/tailwindcss#13898]
**What version of Tailwind CSS are you using?**

v3.4.4

**What build tool (or framework if it abstracts the build tool) are you using?**

- webpack 5.92.0
- postcss-loader 8.1.1
- postcss-preset-env 9.5.14

**What version of Node.js are you using?**

For example: v20.11.0

**What browser are you using?**

Arc

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/csci1nIOS9?file=config

**Describe your issue**

The reproduction URL basically shows my issue. As soon as I add a custom directive `hoversupport` to my `theme.screens.extend` in `tailwind.config.js`, my breakpoints stop working. Is this intended behavior or a bug? It feels like a bug to me.

**Comment by hirasso** [comment]
...turns out that this seems to be the way to add custom modifiers (instead of in the `theme.extend.screens` object):

```js
{
  plugins: [
    plugin(function ({ addVariant }) {
      /** allow to only apply a style on devices that support hover **/
      addVariant('hoversupport', '@media (hover: hover) and (pointer: fine)')
    }),
  ]
}
```

I'd still be interested to learn why this disabled all my other breakpoints:

```js
{
  theme: {
    extend: {
      screens: {
        xs: "360px",
        hoversupport: { raw: "(hover: hover) and (pointer: fine)" },
      },
    },
  },
}
```

**Comment by wongjn** [comment]
See https://github.com/tailwindlabs/tailwindcss/pull/9558#user-content-restrictions.

**Comment by wongjn** [comment]
Seems to be working fine in the Tailwind Play your provided:

![image](https://github.com/tailwindlabs/tailwindcss/assets/11310624/b6c0b4cc-84e1-45a2-8c9a-939cec20fbaa)

**Comment by hirasso** [comment]
No, the first box should be blue at this screen size.

**Comment by wongjn** [comment]
Ah, in that case, you'd want to [adjust the classes a bit](https://play.tailwindcss.com/kXG2y0poPu?size=540x720):

```diff
-<p class="rounded-md bg-green-300 p-2 md:bg-blue-300">This box should be …
+<p class="rounded-md p-2 bg-blue-300">This box should be green on screens…
```
![image](https://github.com/tailwindlabs/tailwindcss/assets/11310624/df71cffd-4265-4196-b36f-1b8fa388fc85)

**Comment by hirasso** [comment]
but it shouldn't be blue at all screen sizes. Only if at or above `md`. I have probably confused you with my demo more than I've helped I'm afraid 😅

...anyways, it's working fine (as expected) if I use the plugin approach, so this all isn't a huge issue after all.

**Comment by wongjn** [comment]
As per https://github.com/tailwindlabs/tailwindcss/issues/13898#issuecomment-2191518715, the viewport is `500px` width, which is narrower than the `md` breakpoint of `768px`. Thus, the box is green, and when the viewport is wider than `768px`, it is blue. This seems to act as you desire, unless I'm missing something?

**Comment by hirasso** [comment]
Oh my god, you are right! I got confused building the demo. But check this out: It stops working if I use an arbitrary value for the first box, like `min-[300px]:bg-blue-300`

https://play.tailwindcss.com/b1IyFxPSQk

**Comment by wongjn** [comment]
That's a known limitation, see https://github.com/tailwindlabs/tailwindcss/pull/9558#user-content-restrictions and https://github.com/tailwindlabs/tailwindcss/issues/12489#issuecomment-1827633949 for details.

**Comment by hirasso** [comment]
Thank you @wongjn for your help! The links to the comments are great. Thanks again!
