### ISSUE TITLE
Shadow color is not automatically set on hover:shadow

### ISSUE THREAD

**Issue by mDeram** [tailwindlabs/tailwindcss#13895]
**What version of Tailwind CSS are you using?**

v3.4.4

**What build tool (or framework if it abstracts the build tool) are you using?**

vite v5.2.0, postcss v8.4.38, autoprefixer v10.4.19

**What version of Node.js are you using?**

v20.12.2

**What browser are you using?**

Tested on:
Mozilla Firefox 126.0.1
Chromium 125.0.6422.112 for Linux Mint

**What operating system are you using?**

Linux Mint

**Reproduction URL**

https://play.tailwindcss.com/cr3sF7yq4d

**Describe your issue**

Hello,

I noticed that shadow colors are not being applied automatically when using hover shadows. I feel like it is not the expected behavior. It needs to be reapplied. Here is the code I expected to work in order to apply a color to a shadow:

`
shadow-purple-500 shadow-lg hover:shadow-2xl
`

To make the expected behavior work I need to repeat the shadow color with the hover like so:
`
shadow-purple-500 shadow-lg hover:shadow-purple-500 hover:shadow-2xl
`

Thanks you for tailwind it is amazing,
Have a nice day!

**Comment by Simon-He95** [comment]
You can try this way
https://play.tailwindcss.com/LxqBkCyROk

**Comment by mDeram** [comment]
I don't think using !important is addressing the main issue. The main issue is that other tailwind classes like text-color and text-size are working properly when changing the size on hover for example and I think it should be the same for shadow.

**Comment by gdavidetanca** [comment]
By design the shadow class itself resets the color, that's why you need to declare the shadow color twice

See #13450

**Comment by mDeram** [comment]
Thanks for linking #13450 it is exactly the issue I was talking about and having the creator of tailwind saying that this is by design and not a bug closes this issue, therefore I searched for it in the documentation. It's right there https://tailwindcss.com/docs/box-shadow-color#preserving-shadow-color-when-changing-the-shadow-size
