### ISSUE TITLE
Config typing doesn’t support opacity function

### ISSUE THREAD

**Issue by WillSquire** [tailwindlabs/tailwindcss#13917]
**What version of Tailwind CSS are you using?**

v3.4.4

**What build tool (or framework if it abstracts the build tool) are you using?**

Next.js

**Describe your issue**

I’m getting a typescript error `Type '({ opacityVariable, opacityValue, }: { opacityVariable?: string; opacityValue?: string; }) => string' is not assignable to type 'string | RecursiveKeyValuePair<string, string>’` when following this example: https://github.com/adamwathan/tailwind-css-variable-text-opacity-demo.

The example works, and I can see it is calling this as a function, but it doesn’t look like the typing supports it in `tailwind.config.ts` using `import type { Config } from ‘tailwindcss’`.

**Comment by adamwathan** [comment]
Hey! That example is a bit out-dated, we've deprecated that function syntax in favor of the `<opacity-value>` placeholder string we document now here:

https://tailwindcss.com/docs/customizing-colors#using-css-variables

So we've left those types out deliberately to discourage people from using the deprecated API.

The example in that repo can be rewritten like this now:

```js
module.exports = {
  theme: {
    colors: {
      primary: 'rgba(var(--color-primary), <opacity-value>)',
      secondary: 'rgba(var(--color-secondary), <opacity-value>)',
    },
  },
  plugins: [],
}
```
