### ISSUE TITLE
Slim template regression with v3.4.5

### ISSUE THREAD

**Issue by ledermann** [tailwindlabs/tailwindcss#14005]
**What version of Tailwind CSS are you using?**

v3.4.5

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss-cli 8.4.39 (but IMHO not relevant here)

**What version of Node.js are you using?**

v20.9.0

**What browser are you using?**

Not relevant

**What operating system are you using?**

macOS (but not relevant)

**Reproduction URL**

Because the bug belongs to Pug or slim, `play.tailwindcss.com` cannot be used to build an example. I will send a PR to fix, please don't close this issue.

**Describe your issue**

After upgrading my Rails application (using Slim templates) to Tailwind CSS [v3.4.5](https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.4.5), I found a regression that some classes are not generated anymore. Example:

```slim
.bg-green-300.2xl:bg-red-300
  '(Look mom, no closing tag!)
```

The class `2xl:bg-red-300` is missing. It seems this happens because #13959 uses an invalid number check.

Stay tuned, I'm working on a PR to fix this.

**Comment by thecrypticace** [comment]
fix released in v3.4.6 -- thanks!

**Comment by Skulli** [comment]
I have a similar problem (in haml) with the class `xl:col-span-2` in the line `.xl:col-span-2.xl:pr-8`. With 3.4.5 and 3.4.6 the `col-span-2` class is not extracted. Can open a new issue, if required.

**Comment by ledermann** [comment]
@Skulli I just tried your example in the test suite of tailwindcss `v3.4.6` and it works fine. Both classes are extracted. So it seems to be a different thing, maybe your example is not complete. I suggest creating a new issue with a minimal failing example.
