### ISSUE TITLE
Data attribute modifier doesn't work with numeric values

### ISSUE THREAD

**Issue by flauwekeul** [tailwindlabs/tailwindcss#14026]
**What version of Tailwind CSS are you using?**

3.4.6

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite 5.3.3 (no Vue/React/Angular)

**What version of Node.js are you using?**

20.12.1

**What browser are you using?**

Any browser

**What operating system are you using?**

MacOS

**Reproduction URL**

https://play.tailwindcss.com/urhLO2C0Zj

**Describe your issue**

When the `data-*` modifier is used and the `data` attribute has a numeric value, the class isn't applied.

**Comment by philipp-spiess** [comment]
Hey @flauwekeul! Sorry for reaching out a few hours too late but wanted to let you know that we'll be fixing this in the next patch release 🙂 Thank you so much for reporting this!

**Comment by flauwekeul** [comment]
Thanks! I saw the fix was merged already. Happy to contribute to this great lib 😃

**Comment by omermesser** [comment]
Foy anyone using and older version: `` `data-[my-number="0.0"]:bg-blue-200` ``
This solved it for me, I managed to select numeric data attribute using Template literals (Template strings)
