### ISSUE TITLE
[v3] scale transitions broken since scale moved away from css transforms

### ISSUE THREAD

**Issue by dylancom** [tailwindlabs/tailwindcss#14059]
**What version of Tailwind CSS are you using?**

For example: v3.4.7

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss-cli 8.3.1

**What version of Node.js are you using?**

For example: v12.0.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS, Windows

**Describe your issue**

The "scale" class switched from using the css property transform `transform: scale(2, 2)` to the new css property `scale`. This breaks animations that use the class `transition`. As it doesn't include `scale`. I noticed it is added to v4 though.

Fix: the transition class should include `scale`

**Comment by adamwathan** [comment]
Hey can you provide a reproduction? v3 does not use the `scale` property, it uses `transform`:

https://play.tailwindcss.com/9j5HX7AzDU

![image](https://github.com/user-attachments/assets/b6fcfe5c-06c0-45af-89c5-d844db517631)

**Comment by dylancom** [comment]
Whoops sorry, I found out the repo was using the plugin: tailwindcss-3d, which altered it.
