### ISSUE TITLE
Regression: classes with decimals no longer showing up in 4.0.0-alpha.18

### ISSUE THREAD

**Issue by karlhorky** [tailwindlabs/tailwindcss#14064]
**What version of Tailwind CSS are you using?**

For example: v4.0.0-alpha.18

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: @tailwindcss/postcss 4.0.0-alpha.18, Next.js 15.0.0-rc.0

**What version of Node.js are you using?**

For example: v20.15.0

**What browser are you using?**

For example: Chrome

**What operating system are you using?**

For example: macOS

**Reproduction URL**

Tailwind Play for v4.0.0-alpha.17 (DOES NOT show bug, because it's a regression in v4.0.0-alpha.18): https://play.tailwindcss.com/1xOx8bbAcO?layout=horizontal

![Screenshot 2024-07-26 at 12 27 32](https://github.com/user-attachments/assets/6072b1e4-18f7-416b-973d-64cc7b48c257)

In v4.0.0-alpha.18, the CSS block in the bottom right of the DevTools is missing.

**Describe your issue**

The CSS for the `lg:w-0.5/10` class is missing in `tailwindcss@4.0.0-alpha.18`

```css
.lg\:w-0\.5\/10 {
    @media (width >= 64rem) {
        width: calc(0.5 / 10* 100%);
    }
}
```

Details:

1. Other responsive width classes without decimals like `lg:w-9/10` work
2. It is present in `tailwindcss@4.0.0-alpha.17`

**Keywords for search**

decimal, period, dot, point

**Comment by philipp-spiess** [comment]
Hey @karlhorky! Fun to see you here 😄 

We chatted about this a bit internally: Is there any particular reason to write the fraction as `0.5/10` over `1/20`? We have not supported arbitrary fractions in v3 but want to make this a bit looser in v4, however it feels like having a fraction on top of a fraction is maybe a bit of an overkill? There's also the potential confusion of `0.5` being a width value defined in the theme (`0.125rem`) so it might be one-tenth of 0.125rem, which we don't like.

**Comment by karlhorky** [comment]
Hey @philipp-spiess 👋 `10` is our grid columns in our design system, so ideally we would like to keep that `/10` string in the code

But if it's unsupported, then I guess we'll have to deal with this in our code and this issue can be closed as `wontfix` / `working as intended`

**Comment by adamwathan** [comment]
Yeah sorry this one wasn't really ever actually meant to work, surprised anyone was relying on it before the behavior changed! For now I'd recommend writing `w-[calc(0.5/10*100%)]` if it's important to keep the `10` in there.

**Comment by karlhorky** [comment]
In case this helps anyone else looking for a numerator with a decimal, I ended up abstracting this in a component:

```tsx
import type { HTMLAttributes } from 'react';
import { twMerge } from 'tailwind-merge';

const widthClassNames = {
  // 10 column grid
  '0.5/10': 'lg:w-1/20',
  '1/10': 'lg:w-1/10',
  '2/10': 'lg:w-2/10',
  '3/10': 'lg:w-3/10',
  '4/10': 'lg:w-4/10',
  '5/10': 'lg:w-5/10',
  '6/10': 'lg:w-6/10',
  '7/10': 'lg:w-7/10',
  '8/10': 'lg:w-8/10',
  '9/10': 'lg:w-9/10',
  '10/10': 'lg:w-10/10',
};

export interface Props extends HTMLAttributes<HTMLDivElement> {
  span: keyof typeof widthClassNames;
}

export default function Column({ className, span, ...props }: Props) {
  return (
    <div
      className={twMerge('px-4', widthClassNames[span], className)}
      {...props}
    />
  );
}
```

This allows the `0.5/10` string wherever it's used:

```tsx
  <Row>
    <Column span="0.5/10" />
```
