### ISSUE TITLE
[Feature proposal] Scroll Snap 

### ISSUE THREAD

**Issue by jesse-deboer** [tailwindlabs/tailwindcss#1406]
Hey! 👋

I love using TailwindCSS and use it even for making sliders while using minimal custom css. There is just one thing I need to declare to make use of sliders on mobile that I think would be a great addition to TailwindCSS:

**Scroll snapping**
For better horizontal (could also be vertical) scrolling on mobile I use scroll-snap in the following way:

```
.scroll-x-mandatory {
	scroll-snap-type: x mandatory;
}

.scroll-start-align {
	scroll-snap-align: start;
}
```

I think it would work to implement this in TailwindCSS, I am thinking about using it like this:

For scroll-snap-type:
- snap-both
- snap-x-mandatory
- snap-y-proximity
- snap-inline
- snap-block

_And so on_

For scroll-snap-align:
- snap-start
- snap-center
- snap-none

_And so on_

**Comment by ortuagustin** [comment]
This could be really great @adamwathan 

I've found this through this [blog)(https://markus.oberlehner.net/blog/super-simple-progressively-enhanced-carousel-with-css-scroll-snap/)

It's crazy how with a few css properties you can build a carousel
