### ISSUE TITLE
Individual transforms can't get converted to compatible syntax by lightningcss

### ISSUE THREAD

**Issue by ottomated** [tailwindlabs/tailwindcss#14094]
**What version of Tailwind CSS are you using?**

4.0.0-alpha.18

**What build tool (or framework if it abstracts the build tool) are you using?**

vite@5.3.5

**What version of Node.js are you using?**

v20.16.0

**What browser are you using?**

Chrome 103.0.5060.134 (OBS CEF)

**What operating system are you using?**

Linux

**Reproduction URL**

[LightningCSS](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%2F*%20Current%20output%20*%2F%5Cn.translate-x-4%20%7B%5Cn%20%20--tw-translate-x%3A%20var(--spacing-4%2C%201rem)%3B%5Cn%20%20translate%3A%20var(--tw-translate-x)%20var(--tw-translate-y)%3B%5Cn%7D%5Cn%5Cn%2F*%20Can't%20just%20add%20transform%3A%20none%20*%2F%5Cn.also-broken%20%7B%5Cn%20%20transform%3A%20none%3B%5Cn%20%20--tw-translate-x%3A%20var(--spacing-4%2C%201rem)%3B%5Cn%20%20translate%3A%20var(--tw-translate-x)%20var(--tw-translate-y)%3B%5Cn%7D%5Cn%5Cn%2F*%20transform%20prop%20is%20required%20*%2F%5Cn.broken%20%7B%5Cn%20%20translate%3A%201rem%201rem%3B%5Cn%7D%5Cn%5Cn%2F*%20only%20case%20where%20it%20works%20*%2F%5Cn.works%20%7B%5Cn%20%20transform%3A%20none%3B%5Cn%20%20translate%3A%201rem%201rem%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

**Describe your issue**

The `translate` property (and other individual transforms) is [only supported in newer browsers](https://developer.mozilla.org/en-US/docs/Web/CSS/translate).

Per https://github.com/parcel-bundler/lightningcss/issues/247, lightningcss does support converting `translate: ...;` into `transform: translate(...);`. However, it seems to have a few caveats - it needs a `transform` property in the same class, and it also doesn't seem to work when `var`s are used to define the parameters.

The v3 docs say:
> While most of the features in Tailwind CSS will work in all modern browsers, Tailwind also includes APIs for several bleeding-edge features that aren’t yet supported by all browsers, for example the `:focus-visible` pseudo-class and `backdrop-filter` utilities.

In my opinion, a common utility such as `transform` should be supported in all browsers - the lack of support blocks me from using v4 in any production applications.

**Comment by adamwathan** [comment]
Hey! Yeah so for v4 we are targeting fairly modern browsers, aiming for Safari 16.4+ so we can use features like `@property` (Safari 16.4/Chrome 88), `color-mix()` (Safari 16.2/Chrome 111), and `@layer` (Safari 15.4/Chrome 99).

Independent transforms were added in Chrome 104 which was released two years ago. If we have to support Chrome 103 then we also can't use `@layer` which is a really important part of the v4 architecture, so I don't think there's any benefit to changing this unfortunately since you'd still have problems with other features if you need to support old Chrome versions.

Appreciate the feedback either way, helpful to keep track of in case it does make sense to change our plans.

**Comment by ottomated** [comment]
I understand. Looks like that adds up to [84.4%](https://browsersl.ist/#q=chrome%3E%3D111%2Cedge%3E%3D111%2Csafari%3E%3D16.4%2Cfirefox%3E%3D128%2Copera%3E%3D97%2Cchromeandroid%3E%3D127%2Csamsung%3E%3D22%2Cios%3E%3D16.4) on browserslist, which is unfortunately a dealbreaker for me. What do you think is the feasibility of an official or community-supported pulgin for "legacy" compat? I don't see it on the roadmap, and I think it's a mistake to advertise backwards compatibility if v4 only supports bleeding-edge css.

**Comment by ottomated** [comment]
opening a new issue for visibility
