### ISSUE TITLE
Inverting light/dark scales without using :dark variant by playing with data-theme attribute or class name

### ISSUE THREAD

**Issue by hassanaitnacer** [tailwindlabs/tailwindcss#14091]
**What version of Tailwind CSS are you using?**

v4.0.0-alpha.18

**What build tool (or framework if it abstracts the build tool) are you using?**

Remix 2.9

**What version of Node.js are you using?**

v20.10.0

**What browser are you using?**

Firefox

**What operating system are you using?**

None. I am using a Linux distro.

**Reproduction URL**

https://play.tailwindcss.com/jIhAOOOUUW?file=css

**Describe your issue**

Hello everyone,

I'm using the latest alpha version, and I need to have multiple scopes for color switching (e.g., having both dark sections and light sections within the same page). I’m using a third-party library that defines CSS variables (I do not have control over it, so I can not simply parse and tweak them. I am looking to an easy way). Look at the attached image to understand the issue:

![Tailwind CSS Question](https://github.com/user-attachments/assets/e7802163-2c7a-4638-9571-20169a5ed999)

**Comment by adamwathan** [comment]
That's annoying! This is another manifestation of this general CSS behavior I also ran into myself recently:

https://x.com/adamwathan/status/1775937299919859961

Put together this PR to add a new option to `@theme` blocks to resolve it:

https://github.com/tailwindlabs/tailwindcss/pull/14095

Let me know what you think or if you have any better ideas!

**Comment by hassanaitnacer** [comment]
It's really annoying! I was facing this for a week now and honestly I tried a bunch of working ideas but the issue with all of them was finding myself repeating what's inside @theme...

I will see if I have a better idea...

**Comment by adamwathan** [comment]
Hey! We've shipped the `inline` option in v4.0.0-alpha.19, so you should be able to use that to handle this problem 👍 

Here's a demo:

https://play.tailwindcss.com/0MrudUsd0p?file=css

**Comment by hassanaitnacer** [comment]
Hi, Adam! Thanks I used it and everything is working just fiiine!

https://x.com/Hassan_AitNacer/status/1829184978930020409
