### ISSUE TITLE
[v4] Clarify browser support

### ISSUE THREAD

**Issue by ottomated** [tailwindlabs/tailwindcss#14119]
Tailwind v4 seems to be taking a different direction for browser support than v3, using some pretty bleeding-edge CSS features for common utilities rather than just providing APIs for them. This is fine, but requires:

1. Very obvious documentation upon release, so people upgrading are aware that their existing code will stop working on older browsers
2. Potentially, an official plugin that transpiles utilities such as `transform` that lightningcss does not support (#14094)
3. Potentially, said plugin being enabled by default

I think this issue will be more pervasive upon release given that v4 will support backwards compatibility for config files and might be mistakenly seen as a drop-in replacement.

**Comment by muhharuntahir** [comment]
I agree that several steps need to be taken to ensure a smooth transition for users. Here are a few key points to consider:

1. **Clear and Detailed Documentation:** It is crucial that the documentation accompanying the release of Tailwind v4 is clear and detailed. Users should be informed about the major changes and how they will affect their code, especially regarding support for older browsers.
2. **Official Plugin for Transpilation:** Developing an official plugin that can transpile utilities such as transform that are not supported by lightningcss would be highly beneficial. This will ensure that users can still utilize new features without sacrificing compatibility with older browsers.
3. **Enabling the Plugin by Default:** If such a plugin exists, enabling it by default would be a wise move. This will reduce the burden on users to reconfigure their projects and ensure broader compatibility without additional effort.
4. **Clarification on Backwards Compatibility:** It is essential to emphasize that although v4 supports backwards compatibility for configuration files, this does not mean that old code will work perfectly in all scenarios without modifications. Clear communication and guidelines should be provided to avoid this misconception.

By taking these steps, we can ensure that the transition to Tailwind v4 will be smooth and not cause significant disruptions for existing users.

**Comment by sdavids** [comment]
@adamwathan 

> we'll be very clear about browser support

Unfortunately neither the [migration guide](https://tailwindcss.com/docs/upgrade-guide) nor the [announcement blog](https://tailwindcss.com/blog/tailwindcss-v4) mention the minimum browser support.


Maybe also mention whether it supports [Baseline](https://developer.mozilla.org/en-US/docs/Glossary/Baseline/Compatibility)?

**Comment by beiatisi** [comment]
I think we need to understand the browser support, otherwise some key projects will not dare to upgrade tailwind to the latest version and experience the better experience it brings us.

**Comment by philipp-spiess** [comment]
@sdavids @beiatisi We have a page for compatibility that mentions the browser support as the first thing: https://tailwindcss.com/docs/compatibility

**Comment by sdavids** [comment]
Maybe you could add a link to that page on the [migration guide](https://tailwindcss.com/docs/upgrade-guide) to make it easier to find.


Also, you might want to:

- Instead of stating specific browser versions state that the Tailwind v4 Core is [Baseline 2024](https://web.dev/baseline/2024) (due to [CSS @property](https://web.dev/blog/at-property-baseline)).

- State that for the lifetime of v4 this will not change.

Should I create a new issue for these suggestions? – Considering this issue is closed?

**Comment by Soviut** [comment]
I definitely got bitten by the higher than expected compatibility requirement. All I saw was "run this npx package and you'll be automatically upgraded"; if there was a compatibility message, I didn't see it.

I'm on a project where the device I'm developing for is pinned to Chrome 87; not terribly old, but definitely out of range of the Chrome 111 (which I found _after_ upgrading). The issue being that things like native cascading layers, OKLab colours, etc. aren't supported that far back. I tried some PostCSS plugins that at least got the site rendering with styles, but so many things were broken I had to revert it.

For projects like mine, it'll be impossible to upgrade to Tailwind 4 without some compatibility settings or a compatibility plugin. I don't mind "legacy" browsers not being the initial target, but support should make it's way backwards eventually. Chrome 87 was from late 2020 and there are potentially millions of devices still running it, meaning new tailwind sites could be breaking on them with no recourse.

**Comment by alexanderbuhler** [comment]
Just going to leave that here for anyone who dares to tinker:  https://gist.github.com/alexanderbuhler/2386befd7b6b3be3695667cb5cb5e709

@Soviut what parts of your project didn't work properly? Polyfilling `@property` rules did the heavy lifting for me, the rest is basically minor.

**Comment by ottomated** [comment]
@alexanderbuhler #14094 is an issue too

**Comment by alexanderbuhler** [comment]
@ottomated Added this to the gist today. Appreciate you pointing that out to me!

**Comment by kerams** [comment]
Unless you have a hard requirement to support old browsers, I can recommend using `!CSS.supports('color:oklch(0 0 0)')` in JS to show an unsupported browser warning of some sort. That way users will at least know why the website is broken and how to proceed.

**Comment by wevertondcl** [comment]
@alexanderbuhler Have ani tip for use the Gist? tried everything to add this to my laravel 12 + tailwind v4 project, but didn't work.
I need a way to make tailwind v4 compatible with Chrome 109..

**Comment by zounar** [comment]
In my case, I have to support older browsers, but I don't want to stick with Tailwind 3 just because of it. I made two changes that improved the backwards compatibility. It's not perfect, but decent enough.

Check out [this repo](https://github.com/zounar/tailwind-4-rgb-palette) where I document those changes.

**Comment by alexanderbuhler** [comment]
@wevertondcl My gist assumes that you have a PostCSS processing step in your build pipeline. 
@zounar Good stuff! I am using https://www.npmjs.com/package/@csstools/postcss-oklab-function for conversion.
