### ISSUE TITLE
 Can't resolve 'tailwindcss/plugin'

### ISSUE THREAD

**Issue by batazor** [tailwindlabs/tailwindcss#14169]
**What version of Tailwind CSS are you using?**

"tailwindcss": "4.0.0-alpha.19"

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: Next.js 14/15

**What version of Node.js are you using?**

For example: v22.4.1

**What operating system are you using?**

macOS

**Describe your issue**

Is there a missing package or an error somewhere else? I couldn't find this library on npm

**Comment by adamwathan** [comment]
Hey! The v4 alpha builds don't have proper plugin support yet so this file doesn't exist in those builds right now. Working on it as we speak but stick to v3 if you need plugin support for now 👍
