### ISSUE TITLE
Double backslash in js to escape class name with underscore will result in tailwindcss not being generated correctly

### ISSUE THREAD

**Issue by Lexachoc** [tailwindlabs/tailwindcss#14164]
**What version of Tailwind CSS are you using?** 

v3.4.9

**What build tool (or framework if it abstracts the build tool) are you using?**

I use `npx tailwindcss -i ./src/input.css -o ./dist/output.css --watch`

**What version of Node.js are you using?** 

v20.11.1

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows 10

**Reproduction URL**

https://play.tailwindcss.com/Z56PzBtttq

**Describe your issue**

When I use the selector to make the outline show when hovering (only when the class `sorting_disabled` is not exist):

`[&:not(.sorting\\_disabled)]:hover:outline` in js file (I need to escape the backslash to make it rendered correctly in HTML as:

`[&:not(.sorting\_disabled)]:hover:outline`

The problem is, the generated css becomes:

```
.\[\&\:not\(\.sorting\\\\_disabled\)\]\:hover\:outline:hover:not(.sorting\_disabled) {
  outline-style: solid;
}
```
when using double backslash in js file, which is not correct.

But if I don't escape the backslash in js, although it generates the correct css:

```
.\[\&\:not\(\.sorting\\_disabled\)\]\:hover\:outline:hover:not(.sorting\_disabled) {
  outline-style: solid;
}
```

but the class name in HTML becomes `[&:not(.sorting_disabled)]:hover:outline` which is then not escaped correctly.

**Comment by Lexachoc** [comment]
I find my issue related to this discussion https://github.com/tailwindlabs/tailwindcss/discussions/11413.

Is there any native support for this? Since I didn't use [PostCSS](https://postcss.org/) to compile tailwindcss.

**Comment by wongjn** [comment]
As per [the documentation](https://tailwindcss.com/docs/adding-custom-styles#handling-whitespace), you could try using [`String.raw()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/raw) in the JavaScript file to avoid backslash-escaping:

> If you’re using something like JSX where the backslash is stripped from the rendered HTML, use [String.raw()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/raw) so the backslash isn’t treated as a JavaScript escape character:
>
> ```jsx
> <div className={String.raw`before:content-['hello\_world']`}>
>   
> </div>
> ```

**Comment by wongjn** [comment]
You have the `String.raw` call inside the string, you may have meant:

```diff
 thead: {
   row: 'border-b border-gray-100 dark:border-gray-700/50',
-  cell: 'outline-2 outline-offset-[-2px] outline-gray-200 String.raw`[&:not(.sorting\\_disabled)]:hover:outline`'
+  cell: 'outline-2 outline-offset-[-2px] outline-gray-200 ' + String.raw`[&:not(.sorting\\_disabled)]:hover:outline`
 },
