### ISSUE TITLE
[BUG] Not clean old classes on --watch rebuild

### ISSUE THREAD

**Issue by PatrykKuniczak** [tailwindlabs/tailwindcss#14180]
**What version of Tailwind CSS are you using?**

For example: v3.4.9

**What build tool (or framework if it abstracts the build tool) are you using?**

For example:
https://github.com/PatrykKuniczak/tw-reproduce/blob/main/package.json

**What version of Node.js are you using?**

For example: v20.11.1

**What browser are you using?**

For example: Chrome (Latest)

**What operating system are you using?**

For example: Windows 11

**Reproduction URL**

[A Tailwind Play link or public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways.
](https://github.com/PatrykKuniczak/tw-reproduce)

**Describe your issue**

Run ```npm dev``` for reproduce, what's on video.

https://github.com/user-attachments/assets/e221f7d7-6f1c-478f-b9ca-29aaad214c96

As you can see, --watch flag works well, but it leaves unnecessary old classes in output file.
I think it checks only, if class don't exists yet and create it, or even don't check nothing, overwrite file with brute force :)

I was used this classes, only once:

![image](https://github.com/user-attachments/assets/88843fc7-0ee5-4000-8d4d-d0ed414f7af3)

![image](https://github.com/user-attachments/assets/f4775595-456b-4c74-8b52-e1a6202d26ff)

**Comment by thecrypticace** [comment]
Hi! This behavior is an intentional performance optimization for development. It makes it so that we don't have to:
- Rescan all files for every change (bad for memory and CPU); OR 
- Keep track of which files every class appears in (bad for memory usage)

If you want the unused classes to be removed you can do a fresh build. Hope that helps!

**Comment by PatrykKuniczak** [comment]
@thecrypticace Yeah, i know i can do fresh build, but it seems strange.

Thanks for answer.
