### ISSUE TITLE
[v4] Broken types on @tailwindcss/postcss from version 4.0.0-alpha.19

### ISSUE THREAD

**Issue by AlbertSabate** [tailwindlabs/tailwindcss#14253]
**What version of Tailwind CSS are you using?**

"@tailwindcss/postcss": "4.0.0-alpha.19",
"@tailwindcss/postcss": "4.0.0-alpha.20",

**What build tool (or framework if it abstracts the build tool) are you using?**

BunJS 1.1.26

**What version of Node.js are you using?**

BunJS 1.1.26

**What browser are you using?**

N/A

**What operating system are you using?**

macOS

**Reproduction URL**

Just install the library and check the build folder, the problem is with @tailwindcss/postcss not with tailwindcss. You will find the .d.ts and .d.mts with export {  }.

[Can't be reproduced on the playground](https://play.tailwindcss.com/M7TxWXpLnq?file=css)

**Describe your issue**

From version "@tailwindcss/postcss": "4.0.0-alpha.19" the types for the plugin @tailwindcss/postcss stopped working. After research I can find that the type file export becomes empty.

<img width="407" alt="Screenshot 2024-08-25 at 10 54 21 PM" src="https://github.com/user-attachments/assets/f8fc20e3-44da-4707-8fe1-efdcf1090045">

It should be as per version "@tailwindcss/postcss": "4.0.0-alpha.18". I can confirm downgrading to version "@tailwindcss/postcss": "4.0.0-alpha.18" everything is working fine.

<img width="566" alt="Screenshot 2024-08-25 at 10 55 48 PM" src="https://github.com/user-attachments/assets/67bc2749-7a0a-45d0-94a4-decb91a6d646">

**Comment by philipp-spiess** [comment]
@AlbertSabate We merged a fix for this in #14256, it'll be out in the next alpha release .Thanks a ton for reporting this!
