### ISSUE TITLE
ltr and rtl don't respect the direction when dir=auto is used

### ISSUE THREAD

**Issue by shedokan** [tailwindlabs/tailwindcss#14305]
**What version of Tailwind CSS are you using?**

3.4.10

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.41, svelte 4.2.19, vite 5.4.2

**What version of Node.js are you using?**

v20.17.0

**What browser are you using?**

Arc (Chromium based)

**What operating system are you using?**

macOS

**Reproduction URL**

It is expected that when using dir=auto the english(ltr) and hebrew(rtl) texts would also be coloured

https://play.tailwindcss.com/ZKvy8eFhha

**Describe your issue**

When using [dir=auto](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir) on an element, the user agent parses the content and figures out the direction to be used.

The current attributes depend on the attribute, instead of the [`:dir()`](https://developer.mozilla.org/en-US/docs/Web/CSS/:dir)
https://github.com/tailwindlabs/tailwindcss/blob/ac6d4a6e8e9ae7ca197bf98d933ae2f205be3635/packages/tailwindcss/src/variants.ts#L902-L903

Note: Things like `ps` and `pe` do work

**Comment by Marlene495Hadley** [comment]
It looks like Tailwind CSS doesn’t support dir=auto directly. You can customize your Tailwind configuration to add dir-ltr and dir-rtl variants. Here’s a quick example:

JavaScript

// tailwind.config.js
module.exports = {
  plugins: [
    function ({ addVariant }) {
      addVariant('dir-ltr', '&:dir(ltr)');
      addVariant('dir-rtl', '&:dir(rtl)');
    },
  ],
};

Then use these variants in your HTML:

HTML

<div class="text-blue-500 dir-ltr:text-red-500 dir-rtl:text-green-500" dir="auto">
  This text will change color based on the text direction.
</div>

This should help you achieve the desired behavior.

**Comment by RobinMalfait** [comment]
Hey! Thanks again for working on this. This was fixed by #14306, and is available in the v4 alpha releases.

You can try it by using `npm install tailwindcss@next`.
