### ISSUE TITLE
[4.0.0-alpha.21] Next.js build fails when imported CSS file with `@import 'tailwindcss';`

### ISSUE THREAD

**Issue by devjiwonchoi** [tailwindlabs/tailwindcss#14341]
> [!NOTE]
> `tailwindcss@4.0.0-alpha.20` works

**What version of Tailwind CSS are you using?**

v4.0.0-alpha.21

**What build tool (or framework if it abstracts the build tool) are you using?**

```
"dependencies": {
  "next": "14.2.7",
  "react": "18.3.1",
  "react-dom": "18.3.1"
},
"devDependencies": {
  "@tailwindcss/postcss": "4.0.0-alpha.21",
  "@types/node": "22.5.3",
  "@types/react": "18.3.5",
  "@types/react-dom": "18.3.0",
  "tailwindcss": "4.0.0-alpha.21",
  "typescript": "5.5.4"
},
```

**What version of Node.js are you using?**

v18.18.0

**What browser are you using?**

N/A

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/devjiwonchoi/repro-tailwindcss-next

**Describe your issue**

1. Imported a `globals.css` file at the root `layout.tsx`.
2. `globals.css` includes `@import 'tailwindcss';` at the top.
3.  Build fails with `TypeError: w.register is not a function` error.

Output:

```
> next build

  ▲ Next.js 14.2.7

   Creating an optimized production build ...
Failed to compile.

-- inner error --
TypeError: w.register is not a function
    at Object.<anonymous> (/.../node_modules/@tailwindcss/node/dist/index.js:1:2323)
    at ...

Import trace for requested module:
./app/globals.css

> Build failed because of webpack errors
```

**Comment by philipp-spiess** [comment]
Hey! The issue here is the Node version. Alpha 21 started to depend on `Module#register` which was added in `v18.19.0` and I see here you are in `v18.18.0`. 

I will look into possibilities of working around this API requirement.

**Comment by thecrypticace** [comment]
The fix for this has been merged and will be in the next alpha release (I _think_ that's happening today)
