### ISSUE TITLE
[4.0.0-alpha.23] Next.js build fails with a TypeError

### ISSUE THREAD

**Issue by renderkid** [tailwindlabs/tailwindcss#14384]
**What version of Tailwind CSS are you using?**
v4.0.0-alpha.23

**What build tool (or framework if it abstracts the build tool) are you using?**
Next.js v14.2.9, Turbo 2.1.1

**What version of Node.js are you using?**
v20.17.0

**What browser are you using?**
–NA–

**What operating system are you using?**
macOS

**Reproduction URL**
–NA–

**Describe your issue**
Upgrading my Next.js app to the latest Tailwind version (v4.0.0-alpha.23) breaks the build with a TypeError.

Output:
```
ModuleBuildError: ./apps/product/lib/intervariable_7902fd61.module.css
TypeError: (0 , h.compile) is not a function
     [at A (/node_modules/@tailwindcss/node/dist/index.js:1:1823)]
     [at u (/node_modules/@tailwindcss/postcss/dist/index.js:1:2561)]
     [at OnceExit (/node_modules/@tailwindcss/postcss/dist/index.js:1:2649)]
     at LazyResult.runAsync (node_modules/postcss/lib/lazy-result.js:298:21) [/apps/product/.next/chunks/08b5e_b3d708._.js:6118:35]
     [at process.processTicksAndRejections (node:internal/process/task_queues:95:5)]
     at async transform (/apps/product/.next/chunks/[project]_apps_product_8ff6a0._.js:97:36)
     (error resolving source map: Execution of FileContent::lines failed)
     at async run (/turbopack/[turbopack-node]/ipc/evaluate.ts:92:23) [/apps/product/.next/chunks/[turbopack-node]__138e29._.js:426:31]
```

The same error is thrown for multiple .css files that are in the codebase.

The only change i've made to the codebase is to upgrade the alpha version. I was on v4.0.0-alpha.19, where everything was working well. I've tried with multiple latest alpha versions and alpha.20 works fine too. The build starts to break with the same error for alpha.21 and above.

First time ever filing a bug report so please let me know if more details are needed. Thank you for all the great work on v4 🙌🏽

**Comment by adamwathan** [comment]
Hey! Did you make sure to update both `tailwindcss` and `@tailwindcss/postcss`? I think you'd get this error if you forgot to update `@tailwindcss/postcss` at the same time as updating `tailwindcss`.

**Comment by renderkid** [comment]
Thank you @philipp-spiess and @adamwathan for looking into this. I did have both `tailwindcss` and `@tailwindcss/postcss` updated to the same version 🙂 

I created a new repo with similar setup as my original project and I don't see the error! So clearly it's something else in my codebase that's messing things up and not alpha.23 version! I'll close this issue.

I should've tried creating a new repo first before reporting the issue. Apologies. Hopefully i'll find the root cause soon 🤞🏽

Thank you for your help 🙌🏽

**Comment by philipp-spiess** [comment]
Ha, no worries! Please do let us know what the problem was, though. Perhaps we can help improve the situation. It does feel like the `tailwindcss` package might be checked in at a different version somewhere, so trying to find out what versions are installed based on your current package manger would be a good next step!

**Comment by renderkid** [comment]
Oh gosh! You're right. That was the issue – a different version of `tailwindcss` was being used in the other app in the monorepo 🤦🏽  Thank you for pointing me in the right direction!

**Comment by philipp-spiess** [comment]
Ahh, gotcha! Glad you found it! What bundler are you using? npm, yarn, or pnpm?

**Comment by renderkid** [comment]
yarn
