### ISSUE TITLE
Performance issue with backdrop-blur on Firefox Mobile app

### ISSUE THREAD

**Issue by adsingh14** [tailwindlabs/tailwindcss#14392]
**What version of Tailwind CSS are you using?**

For example: v3.2.0

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: Vite React package, Plain JS (with tailwind npm)

**What version of Node.js are you using?**

For example: v20

**What browser are you using?**

For example: Firefox mobile (v130.0) 

**What operating system are you using?**

For example: Android 13

**Reproduction URL**

1. Open any of these links:
 - https://tailwindcss.com/docs/blur#blurring-elements
 - https://tailwindcss.com
2. Scroll the page to the footer to see the performance drop. 

**Describe your issue**

Performance issue is noticeable when `backdrop-blur` class/es is in use regardless it's a single `<div>` in plain HTML or multiple.
It affects the performance when scrolling the page.

**Comment by adamwathan** [comment]
Hey! Not much we can do about this I'm afraid, we're not doing anything here that isn't just using the vanilla CSS `backdrop-filter` property and `blur()` functions. Performance considerations like this are something you just need to consider when using these CSS features.
