### ISSUE TITLE
[Feature Proposal] Consider adding not-first and not-last variants

### ISSUE THREAD

**Issue by thanosisalive** [tailwindlabs/tailwindcss#1441]
Right now we have variants like `first` and `last` for this:
```
<div v-for="item in items" class="border-t first:border-t-0">
  {{ item }}
</div>
```
Personally, I don't like this method, because here we assign and reset the value. Isn't it better to assign a value by condition? In the example above, we could have a large number of classes and they can be sorted differently so that the reset class for the first child is not obvious.

Compare this method with the previous one:
```
<div v-for="item in items" class="not-first:border-t">
  {{ item }}
</div>
```
Much better, isn't it? I noticed that in each project I always add these variants: 
```
addVariant('not-first', ({ modifySelectors, separator }) => {
  modifySelectors(({ className }) => {
    return `.${e(`not-first${separator}${className}`)}:not(:first-child)`
  })
})
addVariant('not-last', ({ modifySelectors, separator }) => {
  modifySelectors(({ className }) => {
    return `.${e(`not-last${separator}${className}`)}:not(:last-child)`
  })
})
```

It would be nice to have these variants available by default.

**Comment by davelsan** [comment]
Leaving a comment here for future reference. It would seem the dev team considers this proposal not in line with the current design.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">You could write a custom variant that worked that way, but I think doing it this way is a bit more aligned with how other things in Tailwind work, like `bg-blue-500 hover:bg-blue-400`, or `h-16 sm:h-24`. Very common to specify a value and then override it with a different one.</p>&mdash; Adam Wathan (@adamwathan) <a href="https://twitter.com/adamwathan/status/1149749241692086272?ref_src=twsrc%5Etfw">July 12, 2019</a></blockquote>

**Comment by simonswiss** [comment]
The `spacing` and `divide` utilities take care of most of use cases here, so I am going to assume we can close this issue 👍
