### ISSUE TITLE
Infinite draggable window size at playground

### ISSUE THREAD

**Issue by gabrielramos731** [tailwindlabs/tailwindcss#14414]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/14413

<div type='discussions-op-text'>

<sup>Originally posted by **gabrielramos731** September 13, 2024</sup>
At the playground on Tailwind oficial page, the window size has a infinite draggable size (apparently has no upper limits).
![image](https://github.com/user-attachments/assets/6aa0f990-847c-43af-b148-63db94f7ad3e)
</div>

**Comment by Anne165Hernadez** [comment]
Hello!
It sounds like you’re referring to the Tailwind Play online playground. This tool allows users to experiment with Tailwind CSS directly in the browser. The draggable window size in the playground indeed seems to have no upper limits, which can be useful for testing responsive designs across various screen sizes.  
Best Regards,
[thedisneyhub](https://www.the-disneyhub.com)
