### ISSUE TITLE
`optimizeUniversalDefaults: true` breaks shadows

### ISSUE THREAD

**Issue by alex-jitbit** [tailwindlabs/tailwindcss#14426]
**Reproduction URL**

https://play.tailwindcss.com/JN9kLsgnWE

**Describe your issue**

Using `optimizeUniversalDefaults: true` adds css var overrides that remove shadows (when used in `base` layer)

**Comment by adamwathan** [comment]
Good catch! Fix here, just need to update a bunch of tests and tag a patch 👍 

https://github.com/tailwindlabs/tailwindcss/pull/14427

**Comment by adamwathan** [comment]
Merged the fix, will get a patch tagged today 👍
