### ISSUE TITLE
Unexpected behavior coming from custom animations

### ISSUE THREAD

**Issue by Benjamin-Gelb** [tailwindlabs/tailwindcss#14425]
**What version of Tailwind CSS are you using?**

v^3.4.1

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss-cli v^8, Next.js v14.2.11

**What version of Node.js are you using?**

v21.7.2

**What browser are you using?**

Mozilla Developer Edition

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/Benjamin-Gelb/tailwindcss-issue-reproduction

**Describe your issue**

I encountered this issue in my NextJS application. I think the issue is related to how the tailwind compiler bundles CSS.
I specified a custom keyframe in the tailwind.config.ts file for use in some one-off animations.
This feature documented here:
https://tailwindcss.com/docs/animation#arbitrary-values
I wanted the animations to be timed dynamically so I used string interpolation to attempt this:

❌ Doesn't Work
```typescript
const duration = 4;
return (
  <div className={`animate-[wiggle_${duration}s_ease-in-out_infinite]`}>
  ...
  </div>
)
// (assuming wiggle is a valid Keyframe in the tailwindcss.config.ts file)
```

This wouldn't work and I felt like I was going crazy.
After some experimentation, I made a really unfortunate realization.
From what I can intuit is that one-off animations compiled into individual classes during the tailwind compilation-step.
"animate-[wiggle_4s_ease-in-out_infinite]"
Is compiled as one fixed animation. It's not translating the specifications of the animation at runtime like I expect Tailwind's base classes to behave.

My band-aid solution is to just include comments with the dynamic variations of the animation I want.
The animations are pre-compiled and included in the CSS bundle to be dynamically iterated through.

✅ Works
```typescript
  // animate-[giggle_1s_ease-in-out_infinite]
  // animate-[giggle_2s_ease-in-out_infinite]
  // animate-[giggle_3s_ease-in-out_infinite]
  // animate-[giggle_4s_ease-in-out_infinite]
const duration = 3; // duration 1-4 is supported
return (
  <div className={`animate-[wiggle_${duration}s_ease-in-out_infinite]`}>
  ...
  </div>
```

I think this behavior needs to be documented. Since this behavior a deviation from the expectations of TailwindCSS' design system but inevitable since CSS animations do need to be pre-compiled. I doubt most people actually get this far and would normally give up or reach for inline styles. Maybe I should have honestly.

**Comment by adamwathan** [comment]
Hey! This is documented here: https://tailwindcss.com/docs/content-configuration#dynamic-class-names
