### ISSUE TITLE
[v4] Vite+tsx fails with `The URL must be of scheme file`

### ISSUE THREAD

**Issue by brandongit2** [tailwindlabs/tailwindcss#14420]
**What version of Tailwind CSS are you using?**

- `tailwindcss@4.0.0-alpha.24`
- `@tailwindcss/vite@4.0.0-alpha.24`

(But the error presents starting at `4.0.0-alpha.21`)

**What build tool (or framework if it abstracts the build tool) are you using?**

- `vite@5.4.2`
- `tsx@4.17.0`

**What version of Node.js are you using?**

v18.19.1

**What browser are you using?**

N/A

**What operating system are you using?**

macOS Sonoma 14.6.1

**Reproduction URL**

https://github.com/brandongit2/tailwind-bug

Run `pnpm run dev` in the repo and it errors immediately.

Commenting out the Tailwind plugin from the Vite config makes the error go away.

**Describe your issue**

The error occurs starting at `4.0.0-alpha.21`. `4.0.0-alpha.20` works fine.

```
> tailwind-bug@ dev /Users/brandontsang/projects/tailwind-bug
> tsx server/index.ts

✘ [ERROR] Could not resolve "/Users/brandontsang/projects/vite.config.ts"

failed to load config from /Users/brandontsang/projects/vite.config.ts
/Users/brandontsang/projects/tailwind-bug/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1472
  let error = new Error(text);
              ^

Error: Build failed with 1 error:
error: Could not resolve "/Users/brandontsang/projects/vite.config.ts"
    at failureErrorWithLog (/Users/brandontsang/projects/tailwind-bug/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1472:15)
    at /Users/brandontsang/projects/tailwind-bug/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:945:25
    at runOnEndCallbacks (/Users/brandontsang/projects/tailwind-bug/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1315:45)
    at buildResponseToResult (/Users/brandontsang/projects/tailwind-bug/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:943:7)
    at /Users/brandontsang/projects/tailwind-bug/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:970:16
    at responseCallbacks.<computed> (/Users/brandontsang/projects/tailwind-bug/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:622:9)
    at handleIncomingPacket (/Users/brandontsang/projects/tailwind-bug/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:677:12)
    at Socket.readFromStdout (/Users/brandontsang/projects/tailwind-bug/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:600:7)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

Node.js v18.19.1
 ELIFECYCLE  Command failed with exit code 1.
```

Running a Vite server through the tsx CLI. After some debugging sessions, I believe tsx is attempting to import `'file:///Users/[...]/node_modules/.pnpm/@tailwindcss+node@4.0.0-alpha.24/node_modules/@tailwindcss/node/dist/esm-cache.loader.mts'` (note the `.mts` instead of the correct `.mjs` extension) and failing. It looks like tsx attempts to resolve import paths by trying to `require` imports with various different extensions. Or something like that. I suppose that's why it's attempting to import the `.mts` extension.

A screenshot from the debugging session I had which could be useful:

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/0d3ce04e-7599-49d0-8db4-8a74f057fd75">

**Comment by philipp-spiess** [comment]
@brandongit2 Thanks for the repro! This does indeed seem to have to do with how tsx resolves imports, however I can't reproduce this in a minimal repo that _only_ tries to load the `@tailwindcss/node` folder:

```bash
mkdir tsx-resolver-issue
cd tsx-resolver-issue/
pnpm init
pnpm add @tailwindcss/node@next tailwindcss@next
node
  await import("@tailwindcss/node") // works fine
pnpx tsx 
  await import("@tailwindcss/node") // also works fine
```

So I did some more digging and it seems to be related to the `"allowJs": true` option in your TS config. If I remove this in your repro repo (and fix the typo where you have one `..` too much when assembling the path to the Vite config), it works!

**Comment by brandongit2** [comment]
Yep, you're absolutely right! Closing this issue as resolved.

**Comment by immerrr** [comment]
FTR, I was also seeing this issue, and after some digging it would appear that the error appeared when loading
```
file:///home/immerrr/src/myrepo/node_modules/.pnpm/@tailwindcss+node@4.1.4/node_modules/@tailwindcss/node/dist/esm-cache.loader.mjs
```

The workaround with removing `allowJs: true` helped. So did upgrading node from `v22.3.0` to `v22.15.0`.
