### ISSUE TITLE
Bug in v4 with `--inset-shadow-*` generating `inset` position rule 

### ISSUE THREAD

**Issue by Kinbaum** [tailwindlabs/tailwindcss#14440]
**What version of Tailwind CSS are you using?**

`v4.0.0-alpha.24`

**What build tool (or framework if it abstracts the build tool) are you using?**

- next: `14.2.11`
- tailwindcss: `4.0.0-alpha.24`
- @tailwindcss/postcss: `4.0.0-alpha.24`

**What version of Node.js are you using?**

`v20.11.0`

**What browser are you using?**

N/A

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/R5yKQBCPfX?file=css

**Describe your issue**

When using the `--inset-shadow` custom CSS property to generate an inset shadow, v4 is generating the inset position rule by mistake. Here is the generated output from the tailwindplay listed above (notice the highlighted section).

<img width="1602" alt="Screen Shot 2024-09-16 at 8 47 43 PM" src="https://github.com/user-attachments/assets/b26625ba-da08-4a66-8dad-a90bf21358d2">

**Comment by adamwathan** [comment]
Oof good catch, this is going to be a fun one to fix 🙃 Thanks for reporting!

**Comment by Kinbaum** [comment]
Haha happy to help
