### ISSUE TITLE
Fix compiler in non-Node.js environments?

### ISSUE THREAD

**Issue by aaronadamsCA** [tailwindlabs/tailwindcss#14523]
**What version of Tailwind CSS are you using?**

Since `v4.0.0-alpha.21`

**Reproduction URL**

I'm not sure it's necessary, plus let's first confirm you even want to support this scenario.

**Describe your issue**

Until recently I could `import { compile } from "tailwindcss"` in a worker (or, presumably, browser) runtime and build a Tailwind stylesheet from my own list of candidate classes. This was awesome because we could compile certain Tailwind styles at runtime instead of build time.

Starting with `v4.0.0-alpha.21` this is broken because of a new unguarded reference to `process.env`:

https://app.renovatebot.com/package-diff?name=tailwindcss&from=4.0.0-alpha.20&to=4.0.0-alpha.21

I'm not sure this is a bug _per se_, because I don't know if you officially support running the compiler directly in non-Node.js environments.

But… could you? Would you? Our use case doesn't require a scanner, because our classes are in pure HTML, where a regex works flawlessly; we just need the compiler to build the CSS (AFAIK the same is true for Tailwind Play).

Obviously we can polyfill `process` to work around this for now, but I wanted to get your POV here. It seems to me if the compiler could pass tests in both Node.js and browser environments, you'd have a pure ESM package that could run anywhere, including worker runtimes. I just don't know if it's something you want to support.

**Comment by thecrypticace** [comment]
Yeah the core package is intended to work in basically any environment. We introduced that `process.env.VERSION` check as a workaround for a bug in our Standalone CLI build process. fwiw the process.env.NODE_ENV check has been there possibly since the first alpha tho.

We should probably add a `typeof process !== "undefined"` check. cc @philipp-spiess thoughts?

**Comment by philipp-spiess** [comment]
Ah, yes, definitely. Thanks for reporting!

**Comment by adamwathan** [comment]
Very cool that you’re already playing with v4 in these scenarios! Definitely something we want to support, please forgive us though because the APIs are probably going to change a lot still between now and a stable release — definitely keep playing with them and letting us know how it’s going though if you can tolerate the churn 🙈

**Comment by aaronadamsCA** [comment]
Thanks all, that's a big relief! For now I'll just patch it out locally.

Yes we definitely adopted early, but v4's developer experience was just way too good to resist, and I'm happy to keep the issues coming as you continue to refine your approach (which is great btw).

> fwiw the process.env.NODE_ENV check has been there possibly since the first alpha tho.

I'm pretty sure that's a [compile-time environment variable](https://tsup.egoist.dev/#compile-time-environment-variables) that `tsup` is replacing with a string thanks to the `--env` flag here:

https://github.com/tailwindlabs/tailwindcss/blob/89f0047c0dfe487da6c0329e00ee52c10ccbfcb4/packages/tailwindcss/package.json#L15-L16

So maybe it's possible to use the same approach for the version?

**Comment by thecrypticace** [comment]
> I'm pretty sure that's a [compile-time environment variable](https://tsup.egoist.dev/#compile-time-environment-variables) that tsup is replacing with a string thanks to the --env flag here:

🤦 yep yep I forgot that we did that

Turns out we didn't actually need the `process.env.VERSION` check anymore. I've removed it and it should be fixed in the next release 👍
