### ISSUE TITLE
[V4] preflight overrides components layer

### ISSUE THREAD

**Issue by Matheun** [tailwindlabs/tailwindcss#14559]
Using tailwind v4.0.0.25

```scss
@import "tailwindcss/preflight" layer(base);
@import "../components/_index.scss" layer(components);
```
In the images below you can see that the font styles are being overridden bij the tailwind preflight

<img width="333" alt="image" src="https://github.com/user-attachments/assets/3ea9d2c9-c6ee-49be-9d5d-84ef82ef4b68">

<img width="332" alt="image" src="https://github.com/user-attachments/assets/6f3e8691-c64b-4e40-8a18-ebf936c0a24a">

**Comment by adamwathan** [comment]
Hey! Can you post a full reproduction? Based on just that code snippet this doesn’t happen.

**Comment by Matheun** [comment]
Weirdly enough, i cant either
