### ISSUE TITLE
Tailwind puts desktop-first media queries in a wrong order causing specificy issue

### ISSUE THREAD

**Issue by dx1ded** [tailwindlabs/tailwindcss#14580]
**What version of Tailwind CSS are you using?**

v3.4.3

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss v8.4.21

**What version of Node.js are you using?**

v18.6.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Describe your issue**

I tried to use desktop-first approach using Tailwind and it causes a specificy issue. Let's start with my config for `screens`:

```javascript
screens: {
    xl: { max: "80em" }, // 1280px
    lg: { max: "64em" }, // 1024px
    md: { max: "48em" }, // 768px
    sm: { max: "36em" }, // 576px
    xs: { max: "26.25em" }, // 420px
    xss: { max: "23.4375em" }, // 375px
  },
```

Then let's apply it to the element:

```html
<ul className="flex list-none items-center gap-8 md:flex-col md:gap-2 lg:gap-6"></ul>
```

Here's what we see in browser:

![image](https://github.com/user-attachments/assets/cfa71112-1b64-469a-bdc3-68e9f067e53a)

The query for smaller screens didn't work because Tailwind always puts queries in mobile-first way regarless of `tailwind.config` settings:

![image](https://github.com/user-attachments/assets/735fd5ed-00c1-4815-81da-133698795198)

**Comment by adamwathan** [comment]
Hey! Can you provide a reproduction? Using your same config things sort as expected for me (descending order since they are max-width):

https://play.tailwindcss.com/dBE5BfL0PS

![image](https://github.com/user-attachments/assets/399a7749-e264-4edf-9684-c06e40358b49)

**Comment by dx1ded** [comment]
@adamwathan, yeah you're right! I guess, it simply conflicted with shadcn/ui settings. I changed the name to "d_md" and etc and it works!
