### ISSUE TITLE
Temporary files created and removed causing cli to crash with ENOENT no such file or directory lstat error

### ISSUE THREAD

**Issue by krompaco** [tailwindlabs/tailwindcss#14613]
**What version of Tailwind CSS are you using?**

v4.0.0-alpha.26

**What build tool (or framework if it abstracts the build tool) are you using?**

npx @tailwindcss/cli@next -i ./styles.css -o ./wwwroot/dist/styles.css --postcss --watch --verbose

**What version of Node.js are you using?**

v20.9.0

**What operating system are you using?**

Windows

**Describe your issue**

The watcher in the cli crashes quite frequently. It can work for hours so this is not a massive blocker - in general v4 is great!

```
..
Done in 1ms <<< It works for a awhile but then an edit can get this thrown:
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, lstat 'C:\a-full-path\in-a-dotnet-project\1jufg13t.3fy~'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'C:\\a-full-path\\in-a-dotnet-project\\1jufg13t.3fy~'
}
```

The files ending with ~ are not part of my project. I think they are used to swap compiled bits of code when running my dotnet web project and doing hot reload. Or they are just temporary files that exists for a shorter while during compilation/build.

Maybe the error handling can be improved or the list of watched files (if there is one) needs to adapt more quickly on temp files being added and removed in the space?

**Comment by philipp-spiess** [comment]
@krompaco Oh yeah this seems very unexpected. I suppose the async change observer will yield a change for a file that was removed until we eventually try to read it. Will look into it. Thanks for the report!
