### ISSUE TITLE
update fast-glob 3.3.2 which will fix micromatch 4.0.8 dependency (ReDoS) issue

### ISSUE THREAD

**Issue by zanuka** [tailwindlabs/tailwindcss#14696]
**What version of Tailwind CSS are you using?**

3.4.14

**What build tool (or framework if it abstracts the build tool) are you using?**

Vue 3.4.21, Vite 5.1.5

**What version of Node.js are you using?**

Node 20.15.1

**What browser are you using?**

N/A

**What operating system are you using?**

macOS

**Reproduction URL**

N/A

**Describe your issue**

Once this fast-glob PR gets merged: https://github.com/mrmlnc/fast-glob/pull/456

am proposing an update to their next release ( current is 3.3.2 ) and causes the following audit issue 

```
Regular Expression Denial of Service (ReDoS) in micromatch (Severity: moderate)
  - Affected package: micromatch
  - Patched in: >=4.0.8
```

**Comment by RobinMalfait** [comment]
Hey! This should be fixed by #14697, and will be available in the next release.

You can already try it by using the insiders build `npm install tailwindcss@insiders`.
