### ISSUE TITLE
`work-break` typo (and also a sort order suggestion)

### ISSUE THREAD

**Issue by aaronadamsCA** [tailwindlabs/tailwindcss#14715]
**What version of Tailwind CSS are you using?**

v4.0.0-alpha.28

**Reproduction URL**

https://play.tailwindcss.com/AU8RQ3P1UP

**Describe your issue**

The only true bug in this bug report is this `word-break` typo that's been lurking since the start of v4:

https://github.com/tailwindlabs/tailwindcss/blob/b701ed6916573c84567984780ab30c286ac0397f/packages/tailwindcss/src/property-order.ts#L170-L176

But instead of just fixing that, what I actually want to bring up is the sort order itself, which feels a bit off:

```html
<div class="text-balance bg-linear-to-b from-red-500 to-blue-500 p-8 text-base leading-7 text-white">Balance</div>
<div class="text-pretty bg-linear-to-b from-red-500 to-blue-500 p-8 text-base leading-7 text-white">Pretty</div>
```

I feel like these six properties should move further down the sort order to be with the rest of the text properties.

**Comment by RobinMalfait** [comment]
Hey! This should be fixed by #14787, and is available in the latest alpha release.

You can already try it by using `npm install tailwindcss@next`.
