### ISSUE TITLE
[v4.0.0-alpha.28] The `neutral` color doesn't work well with `color-mix` for transparency

### ISSUE THREAD

**Issue by benjamincanac** [tailwindlabs/tailwindcss#14740]
**What version of Tailwind CSS are you using?**

v4.0.0-alpha.28

**What build tool (or framework if it abstracts the build tool) are you using?**

Nuxt

**What version of Node.js are you using?**

v20.13.1

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://ui3.nuxt.dev/getting-started

![CleanShot 2024-10-21 at 17 19 10@2x](https://github.com/user-attachments/assets/c85ec262-ce19-41fd-9cca-931af0162315)

**Describe your issue**

It occurs when using `--color-neutral-*` color with a transparency: `bg-neutral-900/75`.

The issue might be in the definition of the color:

`--color-neutral-900: oklch(0.205 0 none)` -> `--color-neutral-900: oklch(0.205 0 0)`

**Comment by sandros94** [comment]
Doesn't appear to be OS specific (I tested also on Windows and Android), mostly affects Chromium-based browsers. Firefox and forks aren't affected

**Comment by benjamincanac** [comment]
Might be a duplicate of #14732!
