### ISSUE TITLE
The `ps-10` or `pe-10` is not applied as expected because `px-5` takes precedence.

### ISSUE THREAD

**Issue by Malik-Jouda** [tailwindlabs/tailwindcss#14772]
**What version of Tailwind CSS are you using?**

v4.0.0-alpha.28

**What build tool (or framework if it abstracts the build tool) are you using?**

nuxt 3.13.2, nuxt ui3 v3.0.0-alpha.7

**What version of Node.js are you using?**

v22.9.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/user-attachments/assets/fc5c1401-e915-4a0f-a0a4-1591adb14b67

**Describe your issue**

in version 4.0.0-alpha.28, the  `ps-10` is not applied as expected because `px-5` takes precedence, while in version 3.4.13, `ps-10` works correctly.

**Comment by adamwathan** [comment]
Oh good catch — fixing here: https://github.com/tailwindlabs/tailwindcss/pull/14777

Likely get this out in a new release today 👍
