### ISSUE TITLE
Tailwind cdn url is not working

### ISSUE THREAD

**Issue by rajatgupta-dev** [tailwindlabs/tailwindcss#14816]
**Version of Tailwind CSS - v3.4.13** 

**Browser - Chrome, and Firefox** 

**Operating system - Ubntu v22.04.4**

**URL - https://cdn.tailwindcss.com** 

**Describe your issue**

When hitting this URL in browser it is not working. it showing error for the check the below screenshot from chrome & firefox

![Screenshot from 2024-10-29 04-55-59](https://github.com/user-attachments/assets/33da2444-5027-446a-9e2e-3a796041756f)

![image](https://github.com/user-attachments/assets/98420d28-0dc9-44fe-a317-a00518a151ff)

![image](https://github.com/user-attachments/assets/399343d1-0ffd-4e01-a45c-680aa67809d6)

![image](https://github.com/user-attachments/assets/e8c57970-634c-4d28-84f2-64741559db5e)

**I am following the official documentation**

![image](https://github.com/user-attachments/assets/15b2d149-add8-4633-80c3-788bb04e4b1b)

**Comment by thecrypticace** [comment]
Hi!

1. Are you still seeing this issue?
2. If so, the `DNS_PROBE_FINISHED_NXDOMAIN` error you're seeing implies that your DNS resolver can't find an IP address for cdn.tailwindcss.com. Do you happen to know who's providing your DNS? You should be able to check with `resolvectl status eth0`

**Comment by thecrypticace** [comment]
It could still be a problem with the DNS server you're connecting to. It could also be related to the DNS cache on the machine making the request. My computer has done similar things for other websites before where restarting the DNS service addressed the issue.

And yeah as far as we know the CDN is up. I've checked from here and I'm not seeing any issues.

**Comment by rajatgupta-dev** [comment]
I checked it in my moblile using mobille data from different service provides. It is working fine but I'm using internet in my system from Wifi router So I think there is not any issue with my system the issue I'm facing that is from my broadband connection.
Glad to meet you and Thanks for the information.
