### ISSUE TITLE
`select-all` adds extra whitespace

### ISSUE THREAD

**Issue by NiklasBr** [tailwindlabs/tailwindcss#14837]
**What version of Tailwind CSS are you using?**

v3.4.13 (current version on the Docs site)

**What build tool (or framework if it abstracts the build tool) are you using?**

(none, the issue is reproducible on the Docs site)

**What version of Node.js are you using?**

(none, the issue is reproducible on the Docs site)

**What browser are you using?**

Firefox 132.0

**What operating system are you using?**

Windows

https://tailwindcss.com/docs/user-select#selecting-all-text-in-one-click

**Describe your issue**

When clicking on the 

![image](https://github.com/user-attachments/assets/d6bdc6ab-b4a0-43ba-a7bc-df855f739d45)

It becomes

![image](https://github.com/user-attachments/assets/0c24cec6-ef04-44a8-a04d-4132572710e3)

Now press `CTRL`+`C` (or equivalent on your operating system) to copy the content.

Then paste said content into a text area, such as here, the result will contain extra white-space and new-lines in front of and at the end of the selected text.

This is probably because there is actually white-space and new-lines in the HTML source:

![image](https://github.com/user-attachments/assets/ca3c47ce-53e4-438e-8cd2-c12fcaa6d19f)

As a web developer I sort of know about this quirk, but as a user I am a bit annoyed, because some sites I use with Tailwind CSS use this `select-all` class for things like URL:s and that always means I have to then manually remove the extra space after pasting it in the target after having copied it.

**Comment by adamwathan** [comment]
Hey! Unfortunately this isn't something we have control over, this is just the behavior of `user-select: all` which is the style `select-all` applies. Tailwind is just a thin API for exposing CSS features in HTML, so whatever CSS does is the same thing Tailwind does.

**Comment by NiklasBr** [comment]
@adamwathan I still think it is fixable here.

Instead of doing:

```html
<div class="select-all">
    Text
</div>
```

You do 
```html
<div class="select-all">Text</div>
```

Can I at least petition you to update the docs to mention how to fix this as a sort of best-practice so tat not everyone will use the annoying behaviour?
