### ISSUE TITLE
`@tailwindcss/vite@alpha` used in vite vue, `:deep()` selector can not  use in build mode, dev mode is ok 

### ISSUE THREAD

**Issue by huchaomin** [tailwindlabs/tailwindcss#14839]
**What version of Tailwind CSS are you using?**

@tailwindcss/vite  `4.0.0-alpha.31`

**What build tool (or framework if it abstracts the build tool) are you using?**

"vite": "^5.4.10"    "vue": "^3.5.12"   "@vitejs/plugin-vue": "^5.1.4",

**What version of Node.js are you using?**

20.18.0

**What browser are you using?**

 Chrome

**What operating system are you using?**

Windows

[**Reproduction URL**](https://github.com/huchaomin/tw4alpha-vite-deep-select-bug)
it's an empty Vite/vue project.

:::bash
pnpm i
pnpm build
:::

![Snipaste_2024-10-31_10-44-16](https://github.com/user-attachments/assets/73cfbae7-77b3-4e75-96fe-08369ec25d0c)

when i dont use `@tailwindcss/vite`  in `vite.config.ts`,  build again

![Snipaste_2024-10-31_10-46-07](https://github.com/user-attachments/assets/c75c820e-fe42-4c03-8f57-37d3953d8bbb)

![Snipaste_2024-10-31_10-44-16](https://github.com/user-attachments/assets/1e1b9364-71d4-4a62-9cff-b7d7c2a1c819)

 `:deep()` selector works!!!!

need help, love Tailwind, thanks!

**Comment by philipp-spiess** [comment]
Hey @huchaomin. Thanks a bunch for reporting this! We have pushed a fix for this which is going to be released as part of the next alpha release. Please let us know if you run into any more issues 🙂

**Comment by huchaomin** [comment]
hey @philipp-spiess nice to see your replay,thankyou very much, i will try this in next alpha  release,haha
