### ISSUE TITLE
[Feature Proposal] CSS Logical Properties (margin-inline-start...)

### ISSUE THREAD

**Issue by Yiddishe-Kop** [tailwindlabs/tailwindcss#1483]
**[Feature Proposal]**

First of all - Thank you! Love Tailwindcss! 😍

For margin, padding, borders etc:

I think it would be great to add utilities for `margin-inline-start` & `margin-inline-end` [same for padding & borders], which will help greatly with layouts of all directions.

This approach will make building **bi-directional layouts** _much_ easier, let us write less code: write only one class that will handle both directions.

Or at least can somebody point out how to add it myself, with `tailwind.config.js`.
Thanks!

**Comment by ahmadalfy** [comment]
You don't actually need that in Tailwind, this can be done using PostCSS plugins.

**Comment by Yiddishe-Kop** [comment]
@ahmadalfy can you explain?
Why not have it built into Tailwind (just like `mr-1`, maybe have `ms-1` for `margin-inline-start`), without adding another build process?

**Comment by Yiddishe-Kop** [comment]
I would even go as far to say that maybe the default `ml-1` should use `margin-inline-start` etc., as most of the time that's what I really need.
Although there are cases when you do want to use a direction agnostic margin, most of the time you want the margins to be according to the writing direction. 
Maybe there could be a way to opt out of this behaviour in the config file. 
At least there should be away to extend Tailwind yourself through the config.

**Comment by 20lives** [comment]
Hi, check out this plugin: [tailwindcss-rtl](https://github.com/20lives/tailwindcss-rtl) which is probably what you are looking for.

**Comment by MathGeniusJodie** [comment]
I would much prefer if I could use "start" and "end" instead of "right" and "left", it matches with flexbox's naming, and it doesn't assume a writing direction

**Comment by MathGeniusJodie** [comment]
tailwindcss-rtl should just be part of tailwind imo

**Comment by HapLifeMan** [comment]
@MathGeniusJodie I found [tailwindcss-logical](https://github.com/stevecochrane/tailwindcss-logical) and it does the job very well!
Also using sometimes [tailwindcss-dir](https://github.com/stevecochrane/tailwindcss-logical) for `right-[x]/left-[x]` things 😊

It's working very well without having to deal with `[dir=rtl]` everywhere so I'm happy with that but totally agree that Tailwind should have these utilities built-in to be RTL/LTR compatible.

**Comment by MathGeniusJodie** [comment]
logical properties are supported in edge now, so no more technical reason why this can't be done

**Comment by 20lives** [comment]
@HapLifeMan @MathGeniusJodie [tailwindcss-rtl](https://github.com/20lives/tailwindcss-rtl) already implemented logical properties (with support for legacy browsers)
