### ISSUE TITLE
The social image for this Github repo is outdated

### ISSUE THREAD

**Issue by MOZGIII** [tailwindlabs/tailwindcss#14845]
<img width="753" alt="Снимок экрана 2024-10-31 в 13 54 33" src="https://github.com/user-attachments/assets/b8cc45a3-066d-4535-8324-bc1b7952fcab">
<img width="250" alt="Снимок экрана 2024-10-31 в 13 55 57" src="https://github.com/user-attachments/assets/57c40f5f-e80d-4977-860b-a68ddaa268b3">

Social image says `3.0`, last version is `3.4` already 🤔 

This is just a nit though, feel free to close this

**Comment by RobinMalfait** [comment]
Hey!

We will update this when a new major release drops, thanks for noticing!
