### ISSUE TITLE
[v4] Vite plugin breaks svelte global animation keyframes handling

### ISSUE THREAD

**Issue by emmbm** [tailwindlabs/tailwindcss#14965]
**What version of Tailwind CSS are you using?**

v4.0.0-alpha.32

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite with SvelteKit 2.8.0 (latest)

**What version of Node.js are you using?**

For example: v23.1.0

**What browser are you using?**

Chrome

**What operating system are you using?**

MacOS

**Reproduction URL**

https://github.com/emmbm/tailwind-svelte-keyframes

**Describe your issue**

Updating from `@tailwindcss/vite@4.0.0-alpha.31` to `@tailwindcss/vite@4.0.0-alpha.32` breaks svelte's expected handling (read here _renaming_) of global keyframes defined in style blocks.

In svelte components, styles are scoped by default. This scoping also applies to keyframes, [unless they are defined with a `-global-` prefix which svelte then removes during build](https://svelte.dev/docs/svelte/global-styles#:global()). This behavior is broken in the current `next` version of tailwind.

**Comment by philipp-spiess** [comment]
Yeah it does seem that the default Svelte transforms now no longer apply at all. Looking into it, thanks for the report.

**Comment by philipp-spiess** [comment]
@emmbm The next alpha will have a fix for this! Thanks again for the report 🙇
