### ISSUE TITLE
v4 alpha.32 translate regression

### ISSUE THREAD

**Issue by madmoizo** [tailwindlabs/tailwindcss#14960]
**What version of Tailwind CSS are you using?**

v4 alpha 32

**What build tool (or framework if it abstracts the build tool) are you using?**

vite

**What version of Node.js are you using?**

v22

**What browser are you using?**

Edge

**What operating system are you using?**

Windows

**Reproduction URL**

A Tailwind Play link or public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways.

A reproduction is **required** when filing an issue — any issue opened without a reproduction will be closed and you'll be asked to create a new issue that includes a reproduction. We're a small team and we can't keep up with the volume of issues we receive if we need to reproduce each issue from scratch ourselves.

**Describe your issue**

ok alpha 31:
<img width="299" alt="image" src="https://github.com/user-attachments/assets/610536c9-ce65-4997-a88a-d2ed94103b4f">

Not ok alpha 32:
<img width="302" alt="image" src="https://github.com/user-attachments/assets/51cb1aac-2d14-4293-a344-26af52a0f44a">

**Comment by philipp-spiess** [comment]
@madmoizo Thanks for the report! I can reproduce this issue as well. Looking into it!
