### ISSUE TITLE
Need to resolve the :has() empty sub selector after build the angular project.

### ISSUE THREAD

**Issue by BVPritesh** [tailwindlabs/tailwindcss#14998]
After building the Angular project, I found that a warning was displayed. However, the style.css file is not empty; the .has() selector has a value. Please check the screenshot below.

Let me know if you need further adjustments!

Warning message as below:
```
WARNING] 7 rules skipped due to selector errors:
  .has-\[\:checked\]\:border-indigo-200:has() -> Empty sub-selector
  .has-\[\:checked\]\:bg-indigo-50:has() -> Empty sub-selector
  .has-\[\:checked\]\:bg-indigo-500:has() -> Empty sub-selector
  .has-\[\:checked\]\:text-indigo-900:has() -> Empty sub-selector
  .has-\[\:checked\]\:text-white:has() -> Empty sub-selector
  .has-\[\:checked\]\:ring-2:has() -> Empty sub-selector
  .has-\[\:checked\]\:ring-indigo-600:has() -> Empty sub-selector
```  
Screenshot:  
![image](https://github.com/user-attachments/assets/18c83f7f-c195-4cf4-b422-90571236a645)

**Comment by philipp-spiess** [comment]
Hey there! I see you already created a discussion as well, I'll reply there since `has-[:checked]:text-white` is doing what you're telling it to in Tailwind CSS. 

Will reply here: https://github.com/tailwindlabs/tailwindcss/discussions/14997
