### ISSUE TITLE
[v4] Can't find Plugins in standalone cli

### ISSUE THREAD

**Issue by delCatta** [tailwindlabs/tailwindcss#15012]
**What version of Tailwind CSS are you using?**

For example: v4.0.0.alpha.34

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: standalone-cli @ 4.0.0.alpha.34

**What version of Node.js are you using?**

For example: N/A

**What browser are you using?**

For example: N/A

**What operating system are you using?**

For example: macOS

**Reproduction URL**

https://github.com/delCatta/tailwind-issue

**Describe your issue**

Using the latest release I'm unable to use the @tailwindcss/typography plugin because it is not included in the executable.

I copied the release file and created an `input.css` file with the following contents:

```
@import "tailwindcss";
@plugin "@tailwindcss/typography";
```

Then I ran `./tailwindcss-macos-arm64 -i index.css -o built.css` and got:

```
./tailwindcss-macos-arm64 -i index.css -o built.css
5737 |       }
5738 |       const message = `resolve '${request}' in '${path}'`;
5739 |       const finishResolved = (result) => {
5740 |         return callback(null, result.path === false ? false : `${result.path.replace(/#/g, "\0#")}${result.query ? result.query.replace(/#/g, "\0#") : ""}${result.fragment || ""}`, result);
5741 |       };
5742 |         const error = new Error("Can't " + message);
                             ^
error: Can't resolve '@tailwindcss/typography' in '<THE-CURRENT-FOLDER>'
      at finishWithoutResolve (/$bunfs/root/tailwindcss-macos-arm64:5742:23)
      at /$bunfs/root/tailwindcss-macos-arm64:5834:19
      at /$bunfs/root/tailwindcss-macos-arm64:5834:19
      at /$bunfs/root/tailwindcss-macos-arm64:5834:19
      at /$bunfs/root/tailwindcss-macos-arm64:5834:19
      at /$bunfs/root/tailwindcss-macos-arm64:5834:19
```

I wish to be able to use on rails using [tailwind-rails](https://github.com/rails/tailwindcss-rails) and [tailwind-ruby](https://github.com/flavorjones/tailwindcss-ruby)

**Comment by JDavidVR** [comment]
I've already asked it on twitter (now X) so here is the answer from Adam https://x.com/adamwathan/status/1853609169334542685

```
Not yet, we’re going to reimagine those plugins in general for v4 so need to do that first.
```

**Comment by philipp-spiess** [comment]
Hey! Thanks for the report. We're working on adding support for this: https://github.com/tailwindlabs/tailwindcss/pull/15028 @JDavidVR is right in that we want to reimagine these plugins for v4 but we also don't want you to prevent that from adopting v4 👍

**Comment by miharekar** [comment]
I'm still getting these errors 🤔 

```
⚡➜ npx @tailwindcss/cli
≈ tailwindcss v4.0.0-beta.3

⚡➜ npx @tailwindcss/cli -i app/assets/stylesheets/application.tailwind.css -o app/assets/builds/tailwind.css -w
Error: Can't resolve '@tailwindcss/forms' in '/Users/miharekar/Development/Personal/visualizer/app/assets/stylesheets'
```

even if the css is simply
```
@import 'tailwindcss';

@plugin "@tailwindcss/forms";
@plugin "@tailwindcss/typography";
```

What am I doing wrong?
