### ISSUE TITLE
[v4] Break-keep produces broken CSS

### ISSUE THREAD

**Issue by imjeehoo** [tailwindlabs/tailwindcss#15107]
**What version of Tailwind CSS are you using?**

For example: 4.0.0-beta.1

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: postcss-cli 8.4.47, Next.js 15.0.3

**What version of Node.js are you using?**

For example: Bun 1.1.34

**What browser are you using?**

For example: Safari

**What operating system are you using?**

For example: macOS

**Reproduction URL**

Use break-keep

**Describe your issue**

`break-keep` should produce `word-break: keep-all` but produces `word-break: break-keep`

<img width="280" alt="image" src="https://github.com/user-attachments/assets/f321a550-6ec7-4f47-9354-2e2b2e5c9f89">

**Comment by adamwathan** [comment]
Thanks, fixed in #15108 and will tag a new beta shortly!
