### ISSUE TITLE
v4 larger base output

### ISSUE THREAD

**Issue by kasperaamodt** [tailwindlabs/tailwindcss#15136]
**What version of Tailwind CSS are you using?**

v4.0.0-beta.2

**What build tool (or framework if it abstracts the build tool) are you using?**

N/A

**What version of Node.js are you using?**

N/A

**What browser are you using?**

N/A

**What operating system are you using?**

N/A

**Reproduction URL**

https://play.tailwindcss.com/an51ZGYAGV

**Describe your issue**

Is the v4 base output supposed to be 3.5 times larger than the v3 base output? Just switch between v3 and v4 to see the size difference. 1.13kb (v3) vs 3.94kb (v4).

**Comment by tobimori** [comment]
This is because it *always* includes all theme variables as CSS variables, so that you can access them during runtime.

**Comment by MorganMcmillan** [comment]
Is there any way to opt out of this behavior? For me it's 18kb minified and optimized.

**Comment by Maarten-Dekker** [comment]
You probably want to import the preflight and untilities.

_style.css_
```css
// replace this line
@import "tailwindcss";

// with these
@import "tailwindcss/preflight" layer(base);
@import "tailwindcss/utilities" layer(utilities);
```

Next you can set your required variables.
You can find the default values here:
https://github.com/tailwindlabs/tailwindcss/blob/next/packages/tailwindcss/theme.css

**Comment by Harshkt214** [comment]
I also encountered the same issue, which seems to be fixable using [Tailwind CSS v4 Beta: Overriding the Default Theme](https://tailwindcss.com/docs/v4-beta#overriding-the-default-theme). However, the problem is that we have to remove the variables manually, which I consider not an ideal approach.

**Comment by philipp-spiess** [comment]
Hey all! What you're seeing is indeed intended right now, we do now emit all design tokens as CSS variables so you're able to use and modify them even if the class is not used at runtime. This does slightly increase CSS bundle size but the increase is going to be limited to your theme config as well.

If you don't need most of the tokens and want to remove the output, you can either [remove namespaces from the default theme](https://tailwindcss.com/docs/v4-beta#overriding-the-default-theme) or _eject_ from the default completely.

To do the latter, you'd first split the main Tailwind CSS require into its three pieces:

```diff
- @import "tailwindcss";
+ @layer theme, base, components, utilities;
+ 
+ @import 'tailwindcss/theme.css' layer(theme);
+ @import 'tailwindcss/preflight.css' layer(base);
+ @import 'tailwindcss/utilities.css' layer(utilities);
```

Now, what you can do is fork our default theme from here: https://github.com/tailwindlabs/tailwindcss/blob/next/packages/tailwindcss/theme.css, adjust it to your likings, and replace it inside your project:

```diff
  @layer theme, base, components, utilities;
  
- @import 'tailwindcss/theme.css' layer(theme);
+ @import './theme.css' layer(theme);
  @import 'tailwindcss/preflight.css' layer(base);
  @import 'tailwindcss/utilities.css' layer(utilities);
```

This might be more ergonomic than having to manually unset all namespaces in case you really only need a very thing config.

Is that something that would work for all your use cases?

**Comment by kasperaamodt** [comment]
Forgive me if this is a stupid question, but will that break things? If I detach the entire theme, will `bg-blue-500` or `text-slate-300` have no meaning?

**Comment by philipp-spiess** [comment]
@kasperaamodt Yep, if you unregister the colors these utilities won't work anymore! My idea is to inline only the variables you also need so you don't end up with unused variables.

**Comment by kasperaamodt** [comment]
I see. So v3 had automatic pickup of used vars and v4 does not? Or v3 didn't have vars to track maybe? Manual tracking of used vars can get messy quick. But I guess its a small tradeoff compared to all the new cool stuff! v4 with the Vite setup is really good.

**Comment by philipp-spiess** [comment]
@kasperaamodt v3 did not use CSS variables at all. Instead, every utility would contain the value of the variable that you set via the JavaScript configuration with no way for doing any changes at runtime.

**Comment by kasperaamodt** [comment]
I see. Well I will see what I end up doing.

At the moment, I'm creating static sites. Maybe there is a way to scan the code during the build, and generate a theme with the correct vars. Thank you!

**Comment by ksmsk** [comment]
> Hey all! What you're seeing is indeed intended right now, we do now emit all design tokens as CSS variables so you're able to use and modify them even if the class is not used at runtime. 

@philipp-spiess 

I'm struggling to understand why I’d want to modify a CSS variable at runtime if it’s not being used in the first place. Could you provide an example scenario where this behavior would actually be useful?

**Comment by fongandrew** [comment]
+1 to @ksmsk's point. I _think_ one alternate way of thinking about what @philipp-spiess is saying is that there are ways to use the CSS variables that Vite and/or Tailwind can't easily detect?

Like:
1. Trying to access the theme from JavaScript and doing some runtime thing like `--color-orange-${myNumber}` so a simple grep for the string doesn't bring it up.
2. Building a CSS framework where you drop a theme file with the variables on a bunch of different sites that the build tool can't examine.

Those seem like edge cases though! And the suggestion of ejecting from the default is a non-starter for folks (a big sell of Tailwind is that it has a bunch of batteries already included), not does it entirely solve the problem (if I add a CSS theme var, use it, then stop using it, it'd be ideal if the build tool could automatically stop shipping it).

Anyhow, it'd be nice to have an opt-in / opt-out pref in the Vite plugin or something to check for CSS variable usage the same way it checks for classes and remove them accordingly. My guess is we can probably do this manually by hooking it up to something like https://github.com/tomasklaen/postcss-prune-var, but that requires opting into PostCSS again.

**Comment by fongandrew** [comment]
OK, `postcss-prune-var` does indeed do the job, provided that you're using PostCSS rather than the Vite plugin, and you're not accessing those variables in places other than CSS.

Here's my `postcss.config.js`:

```js
import tailwindcss from '@tailwindcss/postcss';
import pruneVars from 'postcss-prune-var';

export default {
	plugins: [tailwindcss, pruneVars],
};
```

This dropped the size of a bare `@import 'tailwindcss';` from 19.3 kB to 5.9 kB for me.

**Comment by jloh** [comment]
Would be awesome to be able to opt out of this behaviour as its increased my build size form 19k -> 37k with no other changes apart from upgrading.

Small change but I don't use the variables, site is static with no JS 😄

**Comment by stfnx** [comment]
I also don't like this default behaviour. I agree that this should be configurable.
