### ISSUE TITLE
[v4] `@tailwindcss/cli` returns error on windows arm64

### ISSUE THREAD

**Issue by Nickoriuk** [tailwindlabs/tailwindcss#15131]
**What version of Tailwind CSS are you using?**

v4.0.0-beta.2

**What build tool (or framework if it abstracts the build tool) are you using?**

npm 10.8.1

**What version of Node.js are you using?**

v20.9.0, v22.3.0

**What browser are you using?**

N/A

**What operating system are you using?**

Windows 11 ARM64

**Reproduction URL**

N/A

**Describe your issue**

On ARM64 Windows devices, the cli fails with a `MODULE_NOT_FOUND` error. I can recreate this on a windows ARM64 device with the following commands:

```shell
npm init

npm install tailwindcss@next @tailwindcss/cli@next

npx @tailwindcss/cli --help
```

The first two steps succeed, but on the last command the following error occurs:

```
PS D:\projects\tailwindrepro> npx @tailwindcss/cli --help
node:internal/modules/cjs/loader:475
      const err = new Error(
                  ^

Error: Cannot find module 'D:\projects\tailwindrepro\node_modules\@tailwindcss\oxide-win32-arm64-msvc\tailwindcss-oxide.win32-arm64-msvc.node'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:475:19)
    at Module._findPath (node:internal/modules/cjs/loader:758:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1198:27)
    at Module._load (node:internal/modules/cjs/loader:1038:27)
    at wrapModuleLoad (node:internal/modules/cjs/loader:212:19)
    at Module.require (node:internal/modules/cjs/loader:1297:12)
    at require (node:internal/modules/helpers:123:16)
    at Object.<anonymous> (D:\projects\tailwindrepro\node_modules\@tailwindcss\oxide\index.js:100:29)
    at Module._compile (node:internal/modules/cjs/loader:1460:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1544:10) {
  code: 'MODULE_NOT_FOUND',
  path: '\\\\?\\D:\\projects\\tailwindrepro\\node_modules\\@tailwindcss\\oxide-win32-arm64-msvc\\package.json',
  requestPath: '@tailwindcss/oxide-win32-arm64-msvc'
}

Node.js v22.3.0
```

The same commands on x86-64 are successful, and prints the help menu as expected.

It appears as though the package `@tailwindcss/oxide-win32-arm64-msvc` is missing the `.node` file compared to the `@tailwindcss/oxide-win32-x64-msvc` package for x86-64.

**Comment by philipp-spiess** [comment]
Looks like the binary is missing in that dependency, oof. Huge oversight from us, sorry! https://www.npmjs.com/package/@tailwindcss/oxide-win32-arm64-msvc/v/4.0.0-beta.2?activeTab=code

**Comment by silenius** [comment]
looks like FreeBSD is missing too, see #15731

**Comment by gamesover** [comment]
I think there is no linux arm64 version for 4.0.0 either.
I downgraded to [3.4.17](https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.4.17), everything works fine.
