### ISSUE TITLE
[V4] Windows + Nuxt + Vite:  Pre-transform error: Cannot read properties of undefined (reading 'Sequential')

### ISSUE THREAD

**Issue by ManasMadrecha** [tailwindlabs/tailwindcss#15157]
**What version of Tailwind CSS are you using?**

v4.0.0-beta.2

**What build tool (or framework if it abstracts the build tool) are you using?**

- Pnpm
- Nuxt 3.14.159
- Postcss (already pre-installed with Nuxt)
- "@tailwindcss/postcss": ^0.0.0-development.1

**What version of Node.js are you using?**

20.16.0

**What browser are you using?**

Edge

**What operating system are you using?**

Windows 11

**Reproduction URL**

This issue is related to #15156 

New Nuxt app. 

```ts

import tailwindcssVite from '@tailwindcss/vite'

export default defineNuxtConfig({
  // modules: [['../src/module', {}]],
  devtools: { enabled: true },
  compatibilityDate: '2024-11-21',
  css: ['~/assets/styles/tw.css'],
  // postcss: {
  //   plugins: {
  //     '@tailwindcss/postcss': {},
  //   },
  // },
  vite: {
    plugins: [tailwindcssVite()],
  },
})
```

```css
// assets/styles/tw.css

@import "tailwindcss";
```

**Describe your issue**

Run the app. Got this Fatal error: 

```bash

ERROR  Pre-transform error: Cannot read properties of undefined (reading 'Sequential')
```

**Comment by RobinMalfait** [comment]
Hey! Make sure you are using `npm install @tailwindcss/postcss@next` when installing the dependencies. Looks like you have a (very) old version installed (^0.0.0-development.1)

Once you install the dependencies using `@next`, these errors should go away.

Another confusing part is that you mention that you have installed `@tailwindcss/postcss`, but in the snippet you are using `@tailwindcss/vite`. Make sure you are using the correct packages.

Hope this helps!

**Comment by ManasMadrecha** [comment]
Thanks, yes installing `next` version solved it. Used the development version because that was shown as the latest in the IDE 😁 

![image](https://github.com/user-attachments/assets/ede2bfd4-b6e7-4c40-88e6-ff119201c3ed)
