### ISSUE TITLE
[Feature proposal] Add `-webkit-box` display type

### ISSUE THREAD

**Issue by hipstermojo** [tailwindlabs/tailwindcss#1516]
I use `display: -webkit-box` when doing [text clamping](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp) and I can't hide that HTML element using `none` from Tailwind. I think it would be cool if `-webkit-box` could be in Tailwind so I wouldn't need this. However, `-webkit-box` is not supported in IE so I don't know if you might interested in adding it.

**Comment by royvanv** [comment]
That's the [old flexbox spec](https://css-tricks.com/old-flexbox-and-new-flexbox/), right? Can't you just use `.flex` instead?

**Comment by simonswiss** [comment]
Hey @hipstermojo 👋

This plugin that provides text clamping uitlitie susing `-webkit-box` might be interesting to you: https://www.npmjs.com/package/@neojp/tailwindcss-line-clamp-utilities

**Comment by hipstermojo** [comment]
This certainly looks like it addresses what I need. Is there a reason why this is not in the core library?
