### ISSUE TITLE
[v4] weird webpack warning

### ISSUE THREAD

**Issue by aymanoid** [tailwindlabs/tailwindcss#15175]
**What version of Tailwind CSS are you using?**

@tailwindcss/postcss@4.0.0-beta.2
tailwindcss@4.0.0-beta.2

**What build tool (or framework if it abstracts the build tool) are you using?**

https://tailwindcss.com/docs/v4-beta#upgrading-from-v3
Next.js 15.0.3

**What version of Node.js are you using?**

v22.11.0

**What operating system are you using?**

Windows 11

**Reproduction URL**

Just a fresh project initiated with `pnpx create-next-app@latest`, then `pnpx @tailwindcss/upgrade@next` was used to upgrade to v4

**Describe your issue**

I keep getting this warning that seems to be related to webpack whenever I run dev or build command. I'm guessing it's something related to Windows' weird pathing, but not sure. The application seems to work fine though.

![image](https://github.com/user-attachments/assets/8a3bec15-3dbf-40aa-bd52-28afcffbd618)

**Comment by harold07douglas** [comment]
Hello,

It’s fascinating to see how tools like Tailwind CSS and Next.js adapt to rapid ecosystem changes, but it's equally a reminder of how tricky cross-platform compatibility can be—especially when Windows gets thrown into the mix. The fact that the app still runs fine is a testament to how resilient these modern frameworks are, even when they're yelling warnings at us. It's like driving with the "check engine" light on but still enjoying the ride! That said, diving into verbose mode or waiting for the [este enlace](https://www.ingresosolidario.com.co) Tailwind team to iron out these quirks might save you some future headaches. It’s also a reminder to always keep an LTS version of Node.js handy

**Comment by philipp-spiess** [comment]
This is going to be fixed in the next release (hopefully later this week). Thanks for the report! https://github.com/tailwindlabs/tailwindcss/pull/15321

**Comment by lefreet** [comment]
> This is going to be fixed in the next release (hopefully later this week). Thanks for the report! #15321

Please expedite the release of a fix for this issue; we greatly appreciate it. Our team attempted to use version v4 last Friday, but it failed to function properly on the Windows systems of most of our team members, causing our upgrade plan to be temporarily halted. tty.
