### ISSUE TITLE
v4.0.0 Beta missing --spacing-* variables

### ISSUE THREAD

**Issue by DavidCodina** [tailwindlabs/tailwindcss#15182]
Hello.

It seems like --spacing-* custom properties are missing from the generated output.
I'm using a Vite/React build + Chrome browser

<img width="721" alt="browser" src="https://github.com/user-attachments/assets/3c317100-81ca-49a7-94f3-169e56a9fbd5">

**Comment by adamwathan** [comment]
Hey! That's actually the only variable we define by default now, everything else is based on that:

https://tailwindcss.com/docs/v4-beta#dynamic-spacing-scale

**Comment by DavidCodina** [comment]
Got it! Then I can just use that as a multipler with calc(). Thanks
