### ISSUE TITLE
peer-checked:group-[]: Selector Behavior Changed in Tailwind v4?

### ISSUE THREAD

**Issue by Livog** [tailwindlabs/tailwindcss#15194]
**What version of Tailwind CSS are you using?**

v4.0.0-beta.2

**What build tool (or framework if it abstracts the build tool) are you using?**

Tailwind Play

**What version of Node.js are you using?**

N/A (Tailwind Play)

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/L2HaZ4fE7s

You can switch the version to v4 in the playground to see that the same selectors no longer works.

Click on "Icon" text to open menus.

**Describe your issue**

In Tailwind v3, `peer-checked:group-[.toggle]:rotate-180` works as expected, allowing specific target of chidlren when the parent is same level as peer. However, in v4.

It seems like this selector no longer works in v4. I’m wondering if this is an intentional change requiring the use of the new `in-` selector, or if it’s a bug? There doesn’t seem to be any clear documentation about this change. If it’s intended, it would be great to have clarification on the correct way to achieve this behavior in v4.

Thank you!

**Comment by wongjn** [comment]
In v3, it would produce the following selector:

```css
.peer:checked ~ .group.toggle .peer-checked\:group-\[\.toggle\]\:rotate-180
```
Making the `peer` functionality relative to the `.group` element.

However, with nesting in v4, the selector becomes:

```css
.peer-checked\:group-\[\.toggle\]\:rotate-180 {
  &:is(:where(.peer):checked ~ *) {
    &:is(:where(.group):is(.toggle) *) {
```

Thus, the `peer` becomes relative to the element the class is on, not the `.group` element (swapping order of variants does not change this either).

I'm not sure if there is a way to retain the v3 behavior without changing any markup but you could consider using [the new compound variants system](https://tailwindcss.com/docs/v4-beta#composable-variants) like: https://play.tailwindcss.com/AGlQJyRn7J

**Comment by adamwathan** [comment]
Hey! It's a bit buried but the change is in the docs here: https://tailwindcss.com/docs/v4-beta#stacking-order-sensitive-variants

**Comment by Livog** [comment]
@wongjn Wow, thank you so much! This is starting to make more and more sense.

Issue resolved: `peer-checked:group-[.toggle]:rotate-180` -> `group-peer-checked:rotate-180`

**Comment by wongjn** [comment]
If this is in regards to the active tab indicator, this seems to be a problem with Daisy UI v5. In Daisy UI v4, the `tab-active` classes could be modified via variants:

```css
.tab:is(.peer\/a:checked ~ .group .peer-checked\/a\:group-\[\]\:tab-active, [aria-selected="true"]):not(.tab-disabled):not([disabled]) {
  border-color: var(--fallback-bc,oklch(var(--bc)/var(--tw-border-opacity)));
  --tw-border-opacity: 1;
  --tw-text-opacity: 1;
}
```
Whereas in v5, your `group-peer-checked/a:tab-active` rules don't seem to exist.

**Comment by namimo** [comment]
I was talking about this part:

```
<div class="group text-primary">
  <div class="hidden group-peer-checked/a:block">One</div>
  <div class="hidden group-peer-checked/b:block">Two</div>
  <div class="hidden group-peer-checked/c:block">Three</div>
  <div class="hidden group-peer-checked/d:block">Four</div>
</div>
```

**Comment by wongjn** [comment]
I see, thank you for the clarification. You'd have to use an arbitrary value then: https://play.tailwindcss.com/xnVZLZ0Fr1

**Comment by namimo** [comment]
Thanks for the quick response. It works.
