### ISSUE TITLE
[v4] @tailwindcss/postcss - transpilation uses css :is selector but breaks specificity

### ISSUE THREAD

**Issue by TobyPerplex** [tailwindlabs/tailwindcss#15207]
**What version of Tailwind CSS are you using?**

4.0.0-beta.2

**What build tool (or framework if it abstracts the build tool) are you using?**

vite 6.0.0

**What version of Node.js are you using?**

v22.8.0

**What browser are you using?**

Chrome 131.0.6778.86 (Official Build) (arm64)

**What operating system are you using?**

macOS

**Describe your issue**

```
.rte {
    ul.checklist,
    ol {
        --sz-i-li: calc(var(--s) * 4);
        --gap: calc(var(--s) * 3.5);

        li {
            padding-inline-start: calc(var(--sz-i-li) + var(--gap));
            position: relative;

            &::before,
            > .icon {
                width: var(--sz-i-li);
                height: var(--sz-i-li);
                position: absolute;
                inset-block-start: calc(((var(--fs-base) * var(--lh-base)) - var(--sz-i-li)) / 2);
                inset-inline-start: 0;
            }

            &::before {
                content: '';
            }
        }

        @media (--lg-up) {
            --sz-i-li: calc(var(--s) * 5);
            --gap: calc(var(--s) * 7);
        }
    }    

    ol {
        display: flex;
        flex-direction: column;
        gap: calc(var(--s) * 7.5);

        li {
            padding-inline-start: 4rem;
            counter-increment: step-counter;
            position: relative;

            &::before {
                display: flex;
                align-items: center;
                justify-content: center;
                width: calc(var(--s) * 11.75);
                height: calc(var(--s) * 11.75);
                border-radius: 50%;
                background: var(--color-cerise);
                content: counter(step-counter);
                font-weight: 500;
                font-size: calc(var(--s) * 6);
                color: var(--color-white);
                position: absolute;
                inset: 0;
            }

            @media (--lg-up) {
                padding-inline-start: 6rem;

                &::before {
                    width: calc(var(--s) * 15);
                    height: calc(var(--s) * 15);
                }
            }
        }
    }
}
```
With this v3 postcss config:
```
import advancedVariables from 'postcss-advanced-variables';
import nesting from 'tailwindcss/nesting';
import tailwind from 'tailwindcss';
import autoprefixer from 'autoprefixer';
import globalData from '@csstools/postcss-global-data';
import presetEnv from 'postcss-preset-env';

export default {
    plugins: [
        advancedVariables,
        nesting,
        tailwind,
        autoprefixer,
        globalData({
            // So you dont have to import them when using scoped css
            files: ['src/styles/base/custom-media.css'],
        }),
        presetEnv({
            stage: 1,
        }),
    ],
};

```
used to compile to:
<img width="322" alt="Screenshot 2024-11-27 at 10 41 25" src="https://github.com/user-attachments/assets/50aae4d8-de06-48f4-85bb-4fa242386941">

But with this v4 postcss config:
```
import advancedVariables from 'postcss-advanced-variables';
import tailwind from '@tailwindcss/postcss';
import globalData from '@csstools/postcss-global-data';
import presetEnv from 'postcss-preset-env';

export default {
    plugins: [
        advancedVariables,
        tailwind,
        globalData({
            // So you dont have to import them when using scoped css
            files: ['src/styles/base/custom-media.css'],
        }),
        presetEnv({
            // v4 docs say you can remove presetEnv but that breaks custom media like @custom-media --motionOK (prefers-reduced-motion: no-preference); so we keep it
            stage: 1,
        }),
    ],
};
```
it compiles to:
<img width="324" alt="Screenshot 2024-11-27 at 10 25 15" src="https://github.com/user-attachments/assets/1fd9ad95-a7ab-4d4f-9bd6-d8eea14a11ad">
Which breaks specificity. If this is not a bug please tell me how to disable the Lightning CSS `:is` selector feature because there is no documentation on how to disable Lightning CSS features like `IsSelector` in the tailwind/postcss config.

**Comment by philipp-spiess** [comment]
Hey @TobyPerplex! Based on the CSS spec for nesting, the specificity should indeed be calculated [on the largest specificity in the associated selector list](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Nesting_and_specificity), so what lightningcss does here is indeed correct, even when it's unexpected for you due to [postcss-nested](https://github.com/postcss/postcss-nested) plugin that was used before transpiling things differently. You are right though that this is in fact a breaking change when running the _upgrade_ tool.

I understand the desire to opt out of this but even if you don't post-process the CSS, the browser will now use the wrong specificity.

One thing to try is to still keep the `@tailwindcss/nesting` postcss rule before the `@tailwindcss/postcss` step. Have you tried that already? Something like this:

```diff
  import advancedVariables from 'postcss-advanced-variables';
+ import nesting from 'tailwindcss/nesting';
  import tailwind from '@tailwindcss/postcss';
  import globalData from '@csstools/postcss-global-data';
  import presetEnv from 'postcss-preset-env';
  
  export default {
     plugins: [
          advancedVariables,
+         nesting, 
          tailwind,
          globalData({
              // So you dont have to import them when using scoped css
              files: ['src/styles/base/custom-media.css'],
          }),
          presetEnv({
              // v4 docs say you can remove presetEnv but that breaks custom media like @custom-media --motionOK (prefers-reduced-motion: no-preference); so we keep it
              stage: 1,
          }),
      ],
  };
````

**Comment by TobyPerplex** [comment]
Hey @philipp-spiess! If I do `tailwindcss/nesting` I get `Missing "./nesting" specifier in "tailwindcss" package [plugin externalize-deps]` so I tried `@tailwindcss/nesting`. That however breaks almost all styling, looks like it can't handle custom media anymore.

```
import advancedVariables from 'postcss-advanced-variables';
import nesting from '@tailwindcss/nesting';
import tailwind from '@tailwindcss/postcss';
import globalData from '@csstools/postcss-global-data';
import presetEnv from 'postcss-preset-env';

export default {
    plugins: [
        advancedVariables,
        nesting,
        tailwind,
        globalData({
            // So you dont have to import them when using scoped css
            files: ['src/styles/base/custom-media.css'],
        }),
        presetEnv({
            stage: 1,
        }),
    ],
};

```

**Comment by philipp-spiess** [comment]
Oh yeah sorry that was totally my oversight, thanks for trying the other package as well! Yeah this version is very outdated haha, I think it's intended to only be shipped within the `tailwindcss` v3 package and the fact that it's on npm is a side-effect of the current release setup 😅 

Given that `tailwindcss/nesting` is just a wrapper around `postcss-nesting`, maybe it's best if you use the latest version of that plugin directly instead: https://www.npmjs.com/package/postcss-nesting

And then for the custom media query, this is also an extension of CSS. I'm not yet why this worked in your initial version, but I'd expect to see a postcss plugin that transpiles the `@custom-media` syntax into normal `@media` queries, e.g.: https://www.npmjs.com/package/postcss-custom-media

**Comment by TobyPerplex** [comment]
Unfortunately adding `postcss-nesting` didn't reverse the specificity to what it was in v3. I gave up and just edited the CSS so the compiled specificity is correct. My postcss config is still:
```
import advancedVariables from 'postcss-advanced-variables';
import tailwind from '@tailwindcss/postcss';
import globalData from '@csstools/postcss-global-data';
import presetEnv from 'postcss-preset-env';

export default {
    plugins: [
        advancedVariables,
        tailwind,
        globalData({
            // So you dont have to import them when using scoped css
            files: ['src/styles/base/custom-media.css'],
        }),
        presetEnv({
            // Tailwind v4 docs say you can remove presetEnv but that breaks custom media like @custom-media --motionOK so we keep it
            stage: 1,
        }),
    ],
};
```
@philipp-spiess closing this issue :)
