### ISSUE TITLE
[v4] JavaScript config with tailwind-plugin.js treat addComponent as addUtilities

### ISSUE THREAD

**Issue by minimit** [tailwindlabs/tailwindcss#15239]
**What version of Tailwind CSS are you using?**

`4.0.0-beta.3`

**What build tool (or framework if it abstracts the build tool) are you using?**

```
    "@tailwindcss/postcss": "^4.0.0-beta.3",
    "postcss": "^8.4.49",
    "postcss-cli": "^11.0.0",
    "tailwindcss": "^4.0.0-beta.3"
```

**What version of Node.js are you using?**

`v22.11.0`

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/minimit/twbug-add-components

**Describe your issue**

`npm install` and `npm run test`

addComponents gives error on complex styles, it should compile

```
Error: `addUtilities({ '@media (prefers-reduced-motion: reduce)' : … })` defines an invalid utility selector. Utilities must be a single class name and start with a lowercase letter, eg. `.scrollbar-none`.
```

**Comment by philipp-spiess** [comment]
@minimit Hey! Yeah the utility name must be first in v4 right now, you can get the example you posted working by inverting the media query with the class rule:

```js
addComponents({
  '.custom': {
    '@media (prefers-reduced-motion: reduce), (update: slow)': {
      color: 'red',
    },
  },
})
```

Are you running into plugins like this in the wild while upgrading from v3?

**Comment by minimit** [comment]
> @minimit Hey! Yeah the utility name must be first in v4 right now, you can get the example you posted working by inverting the media query with the class rule:
> 
> ```js
> addComponents({
>   '.custom': {
>     '@media (prefers-reduced-motion: reduce), (update: slow)': {
>       color: 'red',
>     },
>   },
> })
> ```
> 
> Are you running into plugins like this in the wild while upgrading from v3?

Thanks

Yes I'm trying to update from v3 to v4 my plugins, anyway now I've the problem that `!important` is not supported in utilities.
