### ISSUE TITLE
[docs]: add info about purgecss and what that tool do in installation docs 

### ISSUE THREAD

**Issue by pumano** [tailwindlabs/tailwindcss#1525]
Thanks for a great css library.

I spend 2 days for trying to understand why in my vue project leaflet.css file not loaded to my project in test environment while in dev it's OK.

Please add information warning to installation section about purgecss

Also will be good to add note how to add whitelist styles to purgecss

```
module.exports = {
  plugins: {
    tailwindcss: {},
    'vue-cli-plugin-tailwind/purgecss': {
      "whitelistPatterns": ["/^leaflet/"],
    }
  }
}
```

Also website not have info about how to install tailwindcss via vue CLI.

Thanks

**Comment by ifaniqbal** [comment]
Thanks @pumano . This makes me aware of it.

In my project (latest Laravel 6, tailwind ^1.4, leaflet), I have to add these lines in `webpack.mix.js`:
```
if (mix.inProduction()) {
  mix.version()
    .purgeCss({
      whitelistPatterns: [/(leaflet[-a-z]*)/],
    })
}
```

**Comment by simonswiss** [comment]
The use of Purge CSS is greatly simplified now since it's "built-in" and you just need to specify what to purge [directly in the config file](https://tailwindcss.com/docs/controlling-file-size#removing-unused-css) 👍
