### ISSUE TITLE
Trying to upgrade a plugin to v4

### ISSUE THREAD

**Issue by KevinGrajeda** [tailwindlabs/tailwindcss#15315]
**What version of Tailwind CSS are you using?**

v4

**What build tool (or framework if it abstracts the build tool) are you using?**

"vite": "^6.0.1"

**What version of Node.js are you using?**

v20.18.0

**What browser are you using?**

N/A

**What operating system are you using?**

macOS

**Reproduction URL**

new vite project with tailwind and tailwindcss-motion
https://github.com/KevinGrajeda/plugin-v4

**Describe your issue**

I'm the developer of https://github.com/romboHQ/tailwindcss-motion and I'm trying to check the compatibility of the plugin with Tailwind v4 and when I run the project it throws me this error:

```
[plugin:@tailwindcss/vite:generate:serve] Package subpath './lib/util/flattenColorPalette' is not defined by "exports" in 
/Users/yokev/dev/rombo/example/upgrade-to-v4/node_modules/.pnpm/tailwindcss-motion@0.4.3-beta_tailwindcss@4.0.0-
beta.5/node_modules/tailwindcss/package.json
```

I'm using flattenColorPalette to add animations with the theme colors

https://github.com/romboHQ/tailwindcss-motion/blob/09ceaeca9654598bca430872f1c967eb066ca4a5/src/baseAnimations.js#L472-L473 

Is there a new approach for doing this? What can I do?

**Comment by philipp-spiess** [comment]
Hey! We're going to add back that API in the next beta version (hopefully out later this week).

**Comment by KevinGrajeda** [comment]
thank you 🙌🙌
