### ISSUE TITLE
[v4] Unused CSS selector warning with new @import "style.css" reference with svelte

### ISSUE THREAD

**Issue by stephanedemotte** [tailwindlabs/tailwindcss#15323]
**What version of Tailwind CSS are you using?**

v4 beta 5

**What build tool (or framework if it abstracts the build tool) are you using?**

svelte5, vite 6

**What version of Node.js are you using?**

 v22

**What browser are you using?**

 Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/stephanedemotte/_issue-tw-v4-unused-css-selector

**Describe your issue**

When i'm using the new `@import "$lib/style.css" reference` i've got a warning `Unused CSS selector`, in a real project i've got hundred of warning :)

<img width="1012" alt="Screenshot 2024-12-06 at 10 42 39 AM" src="https://github.com/user-attachments/assets/b2403248-1f38-45c8-86c1-71d867f8fd66">

Another thing i've got `Unknow at rule @apply` and `Unknow at rule @theme` :/

<img width="792" alt="Screenshot 2024-12-06 at 10 15 51 AM" src="https://github.com/user-attachments/assets/c946acd4-aa66-4a32-b833-ea3dffe671b5">

<img width="1275" alt="Screenshot 2024-12-06 at 10 42 57 AM" src="https://github.com/user-attachments/assets/61c2958c-d8b3-4702-b325-31d2cf3e0385">

Thank you

**Comment by adamwathan** [comment]
Hey! Update to beta 6 and this should be fixed 🤞🏻

**Comment by stephanedemotte** [comment]
https://github.com/tailwindlabs/tailwindcss/pull/15307
