### ISSUE TITLE
v4: build warning

### ISSUE THREAD

**Issue by mynona** [tailwindlabs/tailwindcss#15329]
Tailwind generates this code:

```
img, svg, video, canvas, audio, iframe, embed, object {
    display: block;
    vertical-align: middle;
  }
```

Warning:
Property is ignored due to the display. With 'display: block', vertical-align should not be used.

**Comment by adamwathan** [comment]
Hey! See prior discussions like here: https://github.com/tailwindlabs/tailwindcss/pull/1221

The idea is that if you do this:

```html
<img src="..." class="inline-block">
```

...that the image will get `vertical-align: middle`. Bad lint rule IMO, at least for things like Tailwind where you combine lots of classes.
