### ISSUE TITLE
[BUG] [Loading PostCSS Plugin failed: Cannot find module '/node_modules@jridgewell\gen-mapping\dist\gen-mapping.umd.js']

### ISSUE THREAD

**Issue by mjjabarullah** [tailwindlabs/tailwindcss#15355]
**What version of Tailwind CSS are you using?**
3.4.16

**What version of Node.js are you using?**
v20.11.0

**What operating system are you using?**
Windows 11
**Reproduction**
tried to run "npx tailwindcss init -p"

**Describe your issue**
cannot run npx tailwindcss init -p in terminal it throws [Failed to load PostCSS config: Failed to load PostCSS config (searchPath: D:/jafa/Portal/UI): [Error] Loading PostCSS Plugin failed: Cannot find module 'D:/jafa/Portal/UI/node_modules@jridgewell\gen-mapping\dist\gen-mapping.umd.js'

**Comment by Criheacy** [comment]
@mjjabarullah The verion 0.3.6 of @jridgewell/gen-mapping has no dist folder. Have been fixed after the author published a release of 0.3.7.
See https://github.com/jridgewell/sourcemaps/issues/9

**Comment by mjjabarullah** [comment]
it works good now.
