### ISSUE TITLE
NotFound error with sucrase@3.35.0 in Deno Fresh

### ISSUE THREAD

**Issue by tanquar** [tailwindlabs/tailwindcss#15362]
**What version of Tailwind CSS are you using?**

v3.4.16
via deno.json
```json
...
  "imports": {
    ...
    "tailwindcss": "npm:tailwindcss@^3.4.16",
    "tailwindcss/plugin": "npm:/tailwindcss@^3.4.16/plugin.js",
  }
```

**What build tool (or framework if it abstracts the build tool) are you using?**

Deno Fresh via
```bash
$ deno run -A -r https://fresh.deno.dev
# Do you want to use a styling library? [y/N] y
# 1. tailwindcss (recommended) 1
```

then

```bash
$ deno run start
```

**What version of Node.js are you using?**

Deno v2.1.3

**What browser are you using?**

Chrome (but not related to rendering on a browser)

**What operating system are you using?**

macOS Sequoia 15.1.1 (24B91)

**Reproduction URL**

https://github.com/tanquar/tailwind-sucrase-error

This repository is minimal sample. See Readme for steps to create this state.
Basically only this:
```bash
$ deno run -A -r https://fresh.deno.dev .
# The target directory is not empty (files could get overwritten). Do you want to continue anyway? [y/N] y
# Do you want to use a styling library? [y/N] y
# 1. tailwindcss (recommended) 1
```

**Describe your issue**

On my macOS Sequoia 15.1.1 (24B91), the following error is produced when executing `$ deno run start`

```
$ deno run start
error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
    at Function.Module._resolveFilename (node:module:608:12)
    at Function.Module._load (node:module:497:27)
    at Module.require (node:module:681:19)
    at require (node:module:812:16)
    at Object.<anonymous> (file:///Users/me/tailwind-sucrase-error/node_modules/.deno/sucrase@3.35.0/node_modules/sucrase/dist/computeSourceMap.js:1:328)
    at Object.<anonymous> (file:///Users/me/tailwind-sucrase-error/node_modules/.deno/sucrase@3.35.0/node_modules/sucrase/dist/computeSourceMap.js:91:4)
    at Module._compile (node:module:745:34)
    at loadMaybeCjs (node:module:770:10)
    at Object.Module._extensions..js (node:module:755:12)
    at Module.load (node:module:662:32)
Watcher Process failed. Restarting on file change...
```

The same error is not present when init the project with Deno Fresh via
```bash
$ deno run -A -r https://fresh.deno.dev
# Do you want to use a styling library? [y/N] n
```
or
```bash
$ deno run -A -r https://fresh.deno.dev
# Do you want to use a styling library? [y/N] y
# 2. twind 2
```

**Comment by tanquar** [comment]
My own progress:

After a few attemps including deletion of node_modules and specifying different tailwind versions, I finally tried
```bash
$ deno install --reload
```
then
```bash
$ deno run start
```

The problem is gone now and it builds correctry without "NotFound" error.

**Comment by RobinMalfait** [comment]
Hey!

Glad it's working now! Going to close this since there is nothing further we can do and everything should work as expected now.
