### ISSUE TITLE
Cursor-pointer missing from button styles

### ISSUE THREAD

**Issue by quick007** [tailwindlabs/tailwindcss#15403]
**What version of Tailwind CSS are you using?**

4.0.0-beta.6

**Reproduction URL**

https://play.tailwindcss.com/2ha6uj7Vkw

**Describe your issue**

By default, tailwind used to include a cursor pointer within the basic button styles (or rather, not remove it). However, that seems to be missing in the betas. It feels like an oversight on tailwinds part to change that, and because it's not documented in the changelog for v4, I (assume) it's not intentional.

**Comment by wongjn** [comment]
See #15203 for previous discussion on this topic.

**Comment by quick007** [comment]
Interesting, I guess it's intentional. Weird.
