### ISSUE TITLE
[v4] Defining some custom theme values to var() results in non-existent CSS variables

### ISSUE THREAD

**Issue by StevenStavrakis** [tailwindlabs/tailwindcss#15470]
**What version of Tailwind CSS are you using?**

For example: v4 beta

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite 6.0.3

**What version of Node.js are you using?**

v22.0.0

**What browser are you using?**

Electron 32 (?) (above 30), also on tailwind play

**What operating system are you using?**

macOS, windows

**Reproduction URL**

[Tailwind Play Reproduction](https://play.tailwindcss.com/9cZH5W5bQW)

**Describe your issue**

It seems that in some cases, defining custom values that use `var()` results in empty CSS variable generation. In the reproduction case, `--color-background-modifier-border` is not defined.

**Comment by wongjn** [comment]
There's a typo in your CSS variable definition: https://play.tailwindcss.com/WS1sCaomvq?file=css

```diff
 :root {
-  --background-modofier-border: red;
+  --background-modifier-border: red;
   --color-pretty: deeppink;
 }
```

**Comment by StevenStavrakis** [comment]
And here, I thought things were going to be simple.

My repo:
https://github.com/StevenStavrakis/obsidian-sarah/tree/v4-class-issue

1. Clone it
2. Bun/npm/pnpm install
3. Install Obsidian
4. Open the `dev-vault` inside the repo with Obsidian
5. Go to settings -> community plugins -> Activate both hot-reload and Sarah
6. Right click on a file in the file tree and select "whetstone"
7. You'll see that the header of the chat does not have the border on the bottom correctly applied
8. Open the developer console and inspect, you'll see that the `--color-background-modifier-border` variable is non-existent.

This relates to the `Chat.svelte` file, where you will be able to see how I am using `border-background-modifier-border` on the element containing the "Chat Title" and it isn't working as expected.

Interestingly, the compiled styles.css _does_ have the variable in it, and the variable _does_ exist in the style tag at the head of the document, but for some reason it isn't accessible. By comparison, using the arbitrary value `border-(--background-modifier-border)` works fine.

**Comment by wongjn** [comment]
Could it be that the `--background-modifier-border` CSS variable is set on some element that is not the `<html>`/`:root` element? If that is the case, consider using `@theme inline`:

```diff
 @import "tailwindcss";

-@theme {
+@theme inline {
   /* Colors */
```

**Comment by StevenStavrakis** [comment]
Ok, yeah that worked.
