### ISSUE TITLE
Safari 15 does not show borders with Tailwind 4 beta

### ISSUE THREAD

**Issue by ryanzec** [tailwindlabs/tailwindcss#15506]
**What version of Tailwind CSS are you using?**

4.0.0-beta.7

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite 6

**What version of Node.js are you using?**

v20.18.0

**What browser are you using?**

Safari

**What operating system are you using?**

macOS (12) / Safari (15)

**Describe your issue**

It seems like with Safari 15 (not sure about 16) no border is being render is Safari however in Safari 17 they are being rendered.

**Comment by wongjn** [comment]
See https://github.com/tailwindlabs/tailwindcss/discussions/15284#discussioncomment-11449551

**Comment by adamwathan** [comment]
Hey! As @wongjn mentioned, Tailwind CSS v4 only supports Safari 16.4+ because of features we depend on like [@property](https://developer.mozilla.org/en-US/docs/Web/CSS/@property) and [color-mix](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix).
