### ISSUE TITLE
PluginAPI type doesn't expose postcss object

### ISSUE THREAD

**Issue by RodrigoTomeES** [tailwindlabs/tailwindcss#15508]
**What version of Tailwind CSS are you using?**

3.4.17

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.49, Next.js 15.1.3, webpack 5.97.1

**What version of Node.js are you using?**

22.11.0

**What browser are you using?**

N/A

**What operating system are you using?**

macOS 15.2 (24C101)

**Describe your issue**

<img width="901" alt="image" src="https://github.com/user-attachments/assets/31e87bb3-c3c5-41de-8a6a-7a765a359be1" />

**Comment by thecrypticace** [comment]
Hi! The omission from the types is intentional. The `postcss` property wasn't documented in v2 nor is it documented in v3 as far as I know. It exists for backwards compatibility.

When doing the types we left it out as it should not be relied on. Also plugins that use it will not work in v4. If you need to use postcss in your plugin I would import it directly instead of using the provided `postcss` property.

**Comment by RodrigoTomeES** [comment]
Hi @thecrypticace I tried as you said to import postcss directly but I also have types errors, look:

<img width="1073" alt="image" src="https://github.com/user-attachments/assets/eb82372a-4708-40c1-9c38-0301182412b7" />

### Error

<div class="hover-row" tabindex="0" style="display: flex; color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(32, 32, 32); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="marker hover-contents" style="padding: 4px 8px; font-family: Menlo, Monaco, &quot;Courier New&quot;, monospace; font-weight: normal; font-size: 12px; font-feature-settings: &quot;liga&quot;, &quot;calt&quot;; font-variation-settings: normal; line-height: 18px; letter-spacing: 0px;"><span style="white-space: pre-wrap;">Argument of type 'import("/node_modules/postcss/lib/root").default' is not assignable to parameter of type 'import("/node_modules/@types/postcss-js/node_modules/postcss/lib/root").default'.<br>  Type 'Root_' is missing the following properties from type 'Root_': normalize, markDirty</span><span style="opacity: 0.6; padding-left: 6px;">ts(2345)</span></div></div><div class="hover-row" tabindex="0" style="display: flex; border-top: 1px solid rgba(69, 69, 69, 0.5); color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(32, 32, 32); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="hover-row-contents" style="display: flex; flex-direction: column; min-width: 0px;"><div class="markdown-hover"><div class="hover-contents code-hover-contents" style="padding: 4px 8px;"><div class="rendered-markdown"><p style="margin: 0px 0px 8px;"><span style="color: rgb(249, 99, 99);">⚠ Error<span> </span></span><span style="color: rgb(95, 95, 95);">(TS2345)<span> </span><a data-href="https://typescript.tv/errors/#ts2345" title="See detailed explanation" href="vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html" style="text-decoration: none; color: var(--vscode-textLink-foreground);"><span class="codicon codicon-link-external" style="display: inline-block; font-style: normal; font-variant: normal; font-size-adjust: none; font-kerning: auto; font-optical-sizing: auto; font-feature-settings: normal; font-variation-settings: normal; font-weight: normal; font-stretch: normal; font-size: inherit; line-height: 1; font-family: codicon; text-align: center; text-decoration: none; text-rendering: auto; text-transform: none; -webkit-font-smoothing: antialiased; user-select: none; color: inherit; vertical-align: middle;"></span><span> </span></a>|<span> </span><a data-href="https://ts-error-translator.vercel.app/?error=IIJw5grgtgpgdgFwAQHsBmSEE8AOMkDkAllDiiAgBQBEA9AKoDOMIjtIKAJiEWCgHQIUsWgGUiCGGwBGvAMYgAhmkmsAtIyEgYaDolpwuMAPpQuEADZTaZTXMZsLRaexQoE1AJT9OOxZYQCJCJGJENkRQdeOEVpK0wUJBxFJVhVVAxsPEISMgoaBmZWV25eASERcUkZeSUVFkYNLR09BAMjU3MrNgABLOtbBHtGgCs2Q19OzksBlDsHWicXDncvHz8Agn4AKCQkABVcfAIAJTcEYyCQpCgQxiI4MEwAC3w0FAsLFAB3B6ecDh4ChEKRIXTCTBHQhndyXABcYXIUEUTgAXjAADQ3FIAawAIkQKFggA" title="See translation" href="vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html" style="text-decoration: none; color: var(--vscode-textLink-foreground);"><span class="codicon codicon-globe" style="display: inline-block; font-style: normal; font-variant: normal; font-size-adjust: none; font-kerning: auto; font-optical-sizing: auto; font-feature-settings: normal; font-variation-settings: normal; font-weight: normal; font-stretch: normal; font-size: inherit; line-height: 1; font-family: codicon; text-align: center; text-decoration: none; text-rendering: auto; text-transform: none; -webkit-font-smoothing: antialiased; user-select: none; color: inherit; vertical-align: middle;"></span></a></span><br></p><p style="margin: 8px 0px;"></p><span><span>Argument of type<span> </span></span><span class="codicon codicon-none" style="display: inline-block; font-style: normal; font-variant: normal; font-size-adjust: none; font-kerning: auto; font-optical-sizing: auto; font-feature-settings: normal; font-variation-settings: normal; font-weight: normal; font-stretch: normal; font-size: inherit; line-height: 1; font-family: codicon; text-align: center; text-decoration: none; text-rendering: auto; text-transform: none; -webkit-font-smoothing: antialiased; user-select: none; color: inherit; vertical-align: middle; background-color: var(--vscode-textCodeBlock-background);"><div data-code="id#289"><span style="font-family: Menlo, Monaco, &quot;Courier New&quot;, monospace; font-weight: normal; font-size: 12px; font-feature-settings: &quot;liga&quot;, &quot;calt&quot;; font-variation-settings: normal; line-height: 18px; letter-spacing: 0px;"><div class="monaco-tokenized-source" style="white-space: var(--vscode-hover-sourceWhiteSpace,pre-wrap);"><span class="mtk1" style="color: rgb(204, 204, 204);"> </span><span class="mtk6" style="color: rgb(86, 156, 214);">import</span><span class="mtk1" style="color: rgb(204, 204, 204);">(</span><span class="mtk12" style="color: rgb(206, 145, 120);">"/node_modules/postcss/lib/root"</span><span class="mtk1" style="color: rgb(204, 204, 204);">).</span><span class="mtk10" style="color: rgb(156, 220, 254);">default</span><span class="mtk1" style="color: rgb(204, 204, 204);"> </span></div></span></div></span><span> </span><span>is not assignable to parameter of type<span> </span></span><span class="codicon codicon-none" style="display: inline-block; font-style: normal; font-variant: normal; font-size-adjust: none; font-kerning: auto; font-optical-sizing: auto; font-feature-settings: normal; font-variation-settings: normal; font-weight: normal; font-stretch: normal; font-size: inherit; line-height: 1; font-family: codicon; text-align: center; text-decoration: none; text-rendering: auto; text-transform: none; -webkit-font-smoothing: antialiased; user-select: none; color: inherit; vertical-align: middle; background-color: var(--vscode-textCodeBlock-background);"><div data-code="id#290"><span style="font-family: Menlo, Monaco, &quot;Courier New&quot;, monospace; font-weight: normal; font-size: 12px; font-feature-settings: &quot;liga&quot;, &quot;calt&quot;; font-variation-settings: normal; line-height: 18px; letter-spacing: 0px;"><div class="monaco-tokenized-source" style="white-space: var(--vscode-hover-sourceWhiteSpace,pre-wrap);"><span class="mtk1" style="color: rgb(204, 204, 204);"> </span><span class="mtk6" style="color: rgb(86, 156, 214);">import</span><span class="mtk1" style="color: rgb(204, 204, 204);">(</span><span class="mtk12" style="color: rgb(206, 145, 120);">"/node_modules/@types/postcss-js/node_modules/postcss/lib/root"</span><span class="mtk1" style="color: rgb(204, 204, 204);">).</span><span class="mtk10" style="color: rgb(156, 220, 254);">default</span><span class="mtk1" style="color: rgb(204, 204, 204);"> </span></div></span></div></span><span> </span><span>.</span><p style="margin: 8px 0px;"></p><span>
  | Type  Root_  is missing the following properties from type  Root_  :normalizemarkDirty
-- | --


</span></span></div></div></div></div></div><div class="hover-row" tabindex="0" style="display: flex; border-top: 1px solid rgba(69, 69, 69, 0.5); color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(32, 32, 32); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="hover-row-contents" style="display: flex; flex-direction: column; min-width: 0px;"><div class="markdown-hover"><div class="hover-contents" style="padding: 4px 8px; max-width: var(--vscode-hover-maxWidth,500px); overflow-wrap: break-word;"><div class="rendered-markdown"><h2 style="margin: 8px 0px; line-height: 1.1;">Translation</h2></div></div></div><div class="markdown-hover"><div class="hover-contents code-hover-contents" style="padding: 4px 8px;"><div class="rendered-markdown"><div data-code="id#293"><span style="font-family: Menlo, Monaco, &quot;Courier New&quot;, monospace; font-weight: normal; font-size: 12px; font-feature-settings: &quot;liga&quot;, &quot;calt&quot;; font-variation-settings: normal; line-height: 18px; letter-spacing: 0px;"><div class="monaco-tokenized-source" style="white-space: var(--vscode-hover-sourceWhiteSpace,pre-wrap);"><span class="mtk1" style="color: rgb(204, 204, 204);">Argument of type 'import("/node_modules/postcss/lib/root").default' is not assignable to parameter of type 'import("/node_modules/@types/postcss-js/node_modules/postcss/lib/root").default'.</span></div></span></div><hr style="border-width: 1px 0px 0px; border-left-style: initial; border-left-color: initial; border-right-style: initial; border-right-color: initial; box-sizing: border-box; height: 1px; margin: 4px -8px -4px; border-top-style: solid; border-top-color: rgba(69, 69, 69, 0.5); border-bottom-style: solid; border-bottom-color: rgba(69, 69, 69, 0.5);"><p style="margin: 8px 0px 0px;">I was expecting<span> </span><code style="font-family: var(--monaco-monospace-font); border-radius: 3px; padding: 0px 0.4em; background-color: var(--vscode-textCodeBlock-background);">import("/node_modules/@types/postcss-js/node_modules/postcss/lib/root").default</code>, but you passed<span> </span><code style="font-family: var(--monaco-monospace-font); border-radius: 3px; padding: 0px 0.4em; background-color: var(--vscode-textCodeBlock-background);">import("/node_modules/postcss/lib/root").default</code>.</p></div></div></div><div class="markdown-hover"><div class="hover-contents code-hover-contents" style="padding: 4px 8px;"><div class="rendered-markdown"><div data-code="id#294"><span style="font-family: Menlo, Monaco, &quot;Courier New&quot;, monospace; font-weight: normal; font-size: 12px; font-feature-settings: &quot;liga&quot;, &quot;calt&quot;; font-variation-settings: normal; line-height: 18px; letter-spacing: 0px;"><div class="monaco-tokenized-source" style="white-space: var(--vscode-hover-sourceWhiteSpace,pre-wrap);"><span class="mtk1" style="color: rgb(204, 204, 204);">Type 'Root_' is missing the following properties from type 'Root_': normalize, markDirty</span></div></span></div><hr style="border-width: 1px 0px 0px; border-left-style: initial; border-left-color: initial; border-right-style: initial; border-right-color: initial; box-sizing: border-box; height: 1px; margin: 4px -8px -4px; border-top-style: solid; border-top-color: rgba(69, 69, 69, 0.5); border-bottom-style: solid; border-bottom-color: rgba(69, 69, 69, 0.5);"><p style="margin: 8px 0px 0px;"><code style="font-family: var(--monaco-monospace-font); border-radius: 3px; padding: 0px 0.4em; background-color: var(--vscode-textCodeBlock-background);">Root_</code><span> </span>is missing some required properties from type<span> </span><code style="font-family: var(--monaco-monospace-font); border-radius: 3px; padding: 0px 0.4em; background-color: var(--vscode-textCodeBlock-background);">Root_</code>:<span> </span><code style="font-family: var(--monaco-monospace-font); border-radius: 3px; padding: 0px 0.4em; background-color: var(--vscode-textCodeBlock-background);">normalize, markDirty</code>.</p></div></div></div></div></div><div class="hover-row" tabindex="0" style="display: flex; opacity: 1; outline-color: var(--vscode-focusBorder); outline-offset: -1px; outline-style: solid; outline-width: 1px; border-top: 1px solid rgba(69, 69, 69, 0.5); color: rgb(204, 204, 204); font-family: -apple-system, &quot;system-ui&quot;, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(32, 32, 32); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="hover-row-contents" style="display: flex; flex-direction: column; min-width: 0px;"><div class="markdown-hover"><div class="hover-contents code-hover-contents" style="padding: 4px 8px;"><div class="rendered-markdown"><div data-code="id#295"><span style="font-family: Menlo, Monaco, &quot;Courier New&quot;, monospace; font-weight: normal; font-size: 12px; font-feature-settings: &quot;liga&quot;, &quot;calt&quot;; font-variation-settings: normal; line-height: 18px; letter-spacing: 0px;"><div class="monaco-tokenized-source" style="white-space: var(--vscode-hover-sourceWhiteSpace,pre-wrap);"><span class="mtk1" style="color: rgb(204, 204, 204);">(</span><span class="mtk10" style="color: rgb(156, 220, 254);">alias</span><span class="mtk1" style="color: rgb(204, 204, 204);">) </span><span class="mtk6" style="color: rgb(86, 156, 214);">function</span><span class="mtk1" style="color: rgb(204, 204, 204);"> </span><span class="mtk16" style="color: rgb(220, 220, 170);">postcss</span><span class="mtk1" style="color: rgb(204, 204, 204);">(</span><span class="mtk10" style="color: rgb(156, 220, 254);">plugins</span><span class="mtk3" style="color: rgb(212, 212, 212);">?:</span><span class="mtk1" style="color: rgb(204, 204, 204);"> </span><span class="mtk17" style="color: rgb(78, 201, 176);">postcss</span><span class="mtk1" style="color: rgb(204, 204, 204);">.</span><span class="mtk17" style="color: rgb(78, 201, 176);">AcceptedPlugin</span><span class="mtk1" style="color: rgb(204, 204, 204);">[])</span><span class="mtk3" style="color: rgb(212, 212, 212);">:</span><span class="mtk1" style="color: rgb(204, 204, 204);"> </span><span class="mtk17" style="color: rgb(78, 201, 176);">postcss</span><span class="mtk1" style="color: rgb(204, 204, 204);">.</span><span class="mtk17" style="color: rgb(78, 201, 176);">Processor</span><span class="mtk1" style="color: rgb(204, 204, 204);"> (+</span><span class="mtk7" style="color: rgb(181, 206, 168);">1</span><span class="mtk1" style="color: rgb(204, 204, 204);"> </span><span class="mtk17" style="color: rgb(78, 201, 176);">overload</span><span class="mtk1" style="color: rgb(204, 204, 204);">)</span><br><span class="mtk1" style="color: rgb(204, 204, 204);">(</span><span class="mtk10" style="color: rgb(156, 220, 254);">alias</span><span class="mtk1" style="color: rgb(204, 204, 204);">) </span><span class="mtk16" style="color: rgb(220, 220, 170);">namespace</span><span class="mtk1" style="color: rgb(204, 204, 204);"> </span><span class="mtk16" style="color: rgb(220, 220, 170);">postcss</span><br><span class="mtk18" style="color: rgb(197, 134, 192);">import</span><span class="mtk1" style="color: rgb(204, 204, 204);"> </span><span class="mtk10" style="color: rgb(156, 220, 254);">postcss</span></div></span></div></div></div></div><div class="markdown-hover"><div class="hover-contents code-hover-contents" style="padding: 4px 8px;"><div class="rendered-markdown"><p style="margin: 0px 0px 8px;">Create a new<span> </span><code style="font-family: var(--monaco-monospace-font); border-radius: 3px; padding: 0px 0.4em; background-color: var(--vscode-textCodeBlock-background);">Processor</code><span> </span>instance that will apply<span> </span><code style="font-family: var(--monaco-monospace-font); border-radius: 3px; padding: 0px 0.4em; background-color: var(--vscode-textCodeBlock-background);">plugins</code><span> </span>as CSS processors.</p><div data-code="id#296"><span style="font-family: Menlo, Monaco, &quot;Courier New&quot;, monospace; font-weight: normal; font-size: 12px; font-feature-settings: &quot;liga&quot;, &quot;calt&quot;; font-variation-settings: normal; line-height: 18px; letter-spacing: 0px;"><div class="monaco-tokenized-source" style="white-space: var(--vscode-hover-sourceWhiteSpace,pre-wrap);"><span class="mtk6" style="color: rgb(86, 156, 214);">let</span><span class="mtk1" style="color: rgb(204, 204, 204);"> </span><span class="mtk10" style="color: rgb(156, 220, 254);">postcss</span><span class="mtk1" style="color: rgb(204, 204, 204);"> </span><span class="mtk3" style="color: rgb(212, 212, 212);">=</span><span class="mtk1" style="color: rgb(204, 204, 204);"> </span><span class="mtk16" style="color: rgb(220, 220, 170);">require</span><span class="mtk1" style="color: rgb(204, 204, 204);">(</span><span class="mtk12" style="color: rgb(206, 145, 120);">'postcss'</span><span class="mtk1" style="color: rgb(204, 204, 204);">)</span><br><span class="mtk1" style="color: rgb(204, 204, 204);"></span><br><span class="mtk16" style="color: rgb(220, 220, 170);">postcss</span><span class="mtk1" style="color: rgb(204, 204, 204);">(</span><span class="mtk10" style="color: rgb(156, 220, 254);">plugins</span><span class="mtk1" style="color: rgb(204, 204, 204);">).</span><span class="mtk16" style="color: rgb(220, 220, 170);">process</span><span class="mtk1" style="color: rgb(204, 204, 204);">(</span><span class="mtk10" style="color: rgb(156, 220, 254);">css</span><span class="mtk1" style="color: rgb(204, 204, 204);">, { </span><span class="mtk10" style="color: rgb(156, 220, 254);">from</span><span class="mtk1" style="color: rgb(204, 204, 204);">, </span><span class="mtk10" style="color: rgb(156, 220, 254);">to</span><span class="mtk1" style="color: rgb(204, 204, 204);"> }).</span><span class="mtk16" style="color: rgb(220, 220, 170);">then</span><span class="mtk1" style="color: rgb(204, 204, 204);">(</span><span class="mtk10" style="color: rgb(156, 220, 254);">result</span><span class="mtk1" style="color: rgb(204, 204, 204);"> </span><span class="mtk6" style="color: rgb(86, 156, 214);">=&gt;</span><span class="mtk1" style="color: rgb(204, 204, 204);"> {</span><br><span class="mtk1" style="color: rgb(204, 204, 204);">  </span><span class="mtk10" style="color: rgb(156, 220, 254);">console</span><span class="mtk1" style="color: rgb(204, 204, 204);">.</span><span class="mtk16" style="color: rgb(220, 220, 170);">log</span><span class="mtk1" style="color: rgb(204, 204, 204);">(</span><span class="mtk10" style="color: rgb(156, 220, 254);">result</span><span class="mtk1" style="color: rgb(204, 204, 204);">.</span><span class="mtk10" style="color: rgb(156, 220, 254);">css</span><span class="mtk1" style="color: rgb(204, 204, 204);">)</span><br><span class="mtk1" style="color: rgb(204, 204, 204);">})</span></div></span></div><p style="margin: 8px 0px;"><em>@param</em><span> </span><code style="font-family: var(--monaco-monospace-font); border-radius: 3px; padding: 0px 0.4em; background-color: var(--vscode-textCodeBlock-background);">plugins</code><span> </span>— PostCSS plugins.</p><p style="margin: 8px 0px 0px;"><em>@return</em><span> </span>— Processor to process multiple CSS.</p></div></div></div></div></div>
