### ISSUE TITLE
Add: border-style-hidden

### ISSUE THREAD

**Issue by michaeljakob** [tailwindlabs/tailwindcss#1558]
Please add `border-style-hidden`. It's a commonly used setting for tables without outer borders

`table {
    border-collapse: collapse;
    border-style: hidden;
}

table td, table th {
    border: 1px solid black;
}`

Reference: https://stackoverflow.com/questions/1257430/how-can-i-apply-a-border-only-inside-a-table

https://tailwindcss.com/docs/border-style/

**Comment by tinfoil-knight** [comment]
Can I work on this @adamwathan ?
