### ISSUE TITLE
Justify-items: Center

### ISSUE THREAD

**Issue by mateBe95** [tailwindlabs/tailwindcss#1628]
Hey, u missed positions classes for GRID  as the same in the title

Justify-items: Center

**Comment by simonswiss** [comment]
Merging this with #1647

**Comment by simonswiss** [comment]
Apologies, "merging" was probably not the right thing here as these two issues are actually different.

Will re-open this issue for now, and create another issue that consolidates a few discussions around `justify-items`, `justify-self` and `align-content` 👍

By the way, #1647 has not been implemented.

**Comment by simonswiss** [comment]
I have now created a "home" for this issues and a few other discussions around `justify-items`. 

Consolidating this with #2241, which will remain open.
