### ISSUE TITLE
Arabic Support

### ISSUE THREAD

**Issue by fox880919** [tailwindlabs/tailwindcss#1690]
Dear Sir/Madam,

I'm using your amazing framework in my website, and I want to add an option for user to switch Arabic language. My problem is that, in Arabic, we write and arrange items from right to left.

I know I can achieve that by flex-wrap reverse, but in VueJS I will have to use a lot of v-if for that.

I'm trying to see how to create a custom variant, such that it can have two cases like the following

class="flex en:flex-wrap     ar:flex-wrap-reverse"

Having something like this will make my life more easy.

I hope if you can guide me more on this.

Thanks and regards,
Faiez

**Comment by fox880919** [comment]
Ok, I managed to achieve what I want by using vue i18n localization library, and document.dir = 'rtl' or 'ltr'.

I'm very appreciative of your efforts on tailwind. Keep it up.

**Comment by hkan** [comment]
You can also add `dir="rtl"` to your `<html>` tag, or `direction: rtl;` to `html` selector in CSS. Unless you absolutely need to use JavaScript for that (e.g. multi language reasons), I recommend against it.

**Comment by shirazz** [comment]
@fox880919 did you tried https://github.com/RonMelkhior/tailwindcss-dir

**Comment by T-Alkathiri** [comment]
Dear Bro Faiez,
Please see this link: [https://github.com/20lives/tailwindcss-rtl]
It will help you a lot for Arabic support.
Thank you very much.

**Comment by fox880919** [comment]
Thanks. I. forgot to make. an update here. It. is working fine. For whom may be interested, here is my website link:

https://pnadi.cm

Regards,
Faiez

**Comment by simonswiss** [comment]
Thanks for the suggestion and for the kind words!

Closed this issue, but here's a link to a [relevant discussion on the RTL topic](https://github.com/tailwindlabs/discuss/issues/64)

As stated there, the recommendation for now is indeed to use this above-mentioned plugin: https://github.com/RonMelkhior/tailwindcss-dir

There are no concrete plans to add this to Tailwind core, but thankfully the plugin system makes it straightforward to augment Tailwind with functionality like this if needed. 👍
