### ISSUE TITLE
Don't force camelCase on custom css properties

### ISSUE THREAD

**Issue by hejmartin** [tailwindlabs/tailwindcss#1694]
From the Tailwind docs:

> For convenience, property names can also be written in camelCase and will be automatically translated to dash-case:

```js
addComponents({
  '.card': {
    backgroundColor: '#fff',
    borderRadius: '.25rem',
    boxShadow: '0 2px 4px rgba(0,0,0,0.2)',
  }
})
```

Since this applies to custom css properties as well, there's no way of having a different naming convention other than dash-case. E.g. `--color--MainBg` would come out as `--color--main-bg`. I would prefer it if custom properties was passed through exactly as defined.

**Comment by adamwathan** [comment]
This is actually an upstream bug that has been fixed but not released yet:

https://github.com/postcss/postcss-js/pull/46

When a new version of that is tagged we will make sure to pull it in so we inherit this fix 👍  I'll leave this open until then so we have something to remind us to check on it.

**Comment by dsturm** [comment]
Hey @adamwathan,

since [postcss/postcss-js](https://github.com/postcss/postcss-js/) [released v3.0](https://github.com/postcss/postcss-js/releases), did you already had time to take a look? As far as I can see, an upgrade would be safe - all tests passed. But they dropped support for multiple Node.js versions. 🤔

```md
# Change Log

## 3.0
* Removed support for Node.js 6.x, 8.x, 11.x, and 13.x versions.
* Moved to PostCSS 8.0.
* Added ES modules support.
* Avoid stringification of unitless values (by Rishabh Rathod).
```

**Comment by adamwathan** [comment]
Can’t upgrade until Tailwind 2.0 unfortunately since they dropped support for node 8. Coming in November though.

**Comment by adamwathan** [comment]
Upgraded to postcss-js 3.0 this morning now that we're working on getting Tailwind 2.0 released in a few weeks, so can close this 🙌
