### ISSUE TITLE
[Feature Proposal] - Mono gray palette

### ISSUE THREAD

**Issue by jenstornell** [tailwindlabs/tailwindcss#1719]
I've looked at the colors in https://tailwindui.com/documentation#how-tailwindcss-ui-extends-tailwind and they look great. I'm looking forward to see them in a future version of Tailwind.

There are two gray palettes but no "real" gray.

## I added a mono palette into the mix

I've removed the blue from the new default palette as a new "Mono gray".

Because it's completely gray, it will fit well with every other color in the other palettes.

![image](https://user-images.githubusercontent.com/927011/81164788-362a6780-8f91-11ea-9879-fa1f543e48f5.png)

## Suggested name

For example `bg-mono-500` and `text-mono-500` sounds good to me. The name `mono` is short and descriptive.

What do you think? Would it be a good native feature or is it better to let the user create it as a custom config?

**Comment by alvinkonda** [comment]
I think the naming like Material design is more descriptive. So, the current gray color should be named `blue-gray` and then should be provided another palete for the `gray` color, which of course should be just gray.

**Comment by kylecordes** [comment]
I also found this surprising. Out-of-the-box, the thing called gray is pretty far from pure gray. You can purchase an add-on which has something closer to pure gray in the box, but still not. My naive expectation of a utility CSS kit was to contain a broad variety of useful colors, including the most boring and obvious of all, shades of un-tinted gray. I'm sure it will turn out to be straightforward to add such a color set in the configuration, so this will be a minor speedbump.
