### ISSUE TITLE
Some options passed to purge are not working as expected

### ISSUE THREAD

**Issue by dmorda** [tailwindlabs/tailwindcss#1728]
I'm having an issue where some of the parameters I'm specifying in the `options` block that I pass to purge do not seem to have any effect. I am running tailwindcss 1.4.5 and gatsby 2.21.16.

```
// tailwind.config.js
module.exports = {
  purge: [
    content: [
      './src/**/*.js',
    ],
    options: {
      rejected: true,
      printRejected: true,
      whitelistPatterns: [/^grid-rows-/],
    }
  ]
}
```

**Expected Results**
I see the classes that have been removed and it displays a message summarizing how much the filesize was reduced.

**Actual Results**
It does the purge and processes the "whitelistPatterns", but it does not display any classes removed or provide any totals.

However, if I follow [these instructions](https://purgecss.com/plugins/gatsby.html) to use the "gatsby-plugin-purgecss" plugin, the output works as expected.

**Comment by adamwathan** [comment]
The `printRejected` option is specific to the Gatsby wrapper and not actually an official of PurgeCSS as far as I can tell:

https://purgecss.com/configuration.html#options

We might be able to simulate the behavior in Tailwind though if someone feels like poking around how they pulled it off.

**Comment by dmorda** [comment]
Ah, snap...sorry about that @adamwathan. I totally missed that. But a simulated behavior would be awesome to display some metrics and troubleshooting info.
