### ISSUE TITLE
Match Svelte’s `class:` directive when purging

### ISSUE THREAD

**Issue by ryanditjia** [tailwindlabs/tailwindcss#1731]
Currently Tailwind’s default purge doesn’t match [Svelte’s `class:` directive](https://svelte.dev/tutorial/classes).

`bg-red-500` will be removed in prod:

```svelte
<div class:bg-red-500={true} />
```

## Reproduction

I’ve made a reproduction case: https://github.com/ryanditjia/sapper-tailwind-purge-repro

How to reproduce:

```sh
git clone https://github.com/ryanditjia/sapper-tailwind-purge-repro
cd sapper-tailwind-purge-repro
yarn install
yarn dev # this takes about 20 seconds
```

Visit localhost:3000 and you can see a block of text with red background.

Now create production build:

```sh
yarn export
npx serve __sapper__/export
```

Visit localhost:5000 and the red background is gone.

I hope this use case can be supported. Thank you for the continued development of Tailwind (been a happy user for a long time).

**Comment by babichjacob** [comment]
For reference, I "solved" this by changing the extractor to
```js
defaultExtractor: (content) => [...content.matchAll(/(?:class:)*([\w\d-/:%.]+)/gm)].map(([_match, group, ..._rest]) => group)
```
This is not based on the [existing extractor(s)](https://github.com/tailwindcss/tailwindcss/blob/master/src/lib/purgeUnusedStyles.js#L84-L92) at all, so it's likely not that good of an idea to incorporate this verbatim there (because it'll probably match different things).

**Comment by evdama** [comment]
This one I put together a while ago, also with input from the tw discourse channel

```js
  const svelteExtractor = ( content ) => {
    const regExp = new RegExp(/[A-Za-z0-9-_:/]+/g)
    const matchedTokens = []
    let match = regExp.exec(content)

    while (match) {
      if (match[0].startsWith('class:')) {
        matchedTokens.push(match[0].substring(6))
      } else {
        matchedTokens.push(match[0])
      }
      match = regExp.exec(content)
    }
    return matchedTokens
  }
```

**Comment by codeyash** [comment]
Any updates please
