### ISSUE TITLE
Disabling hover styles on mobile

### ISSUE THREAD

**Issue by rightaway** [tailwindlabs/tailwindcss#1739]
If I create a custom media query that uses https://caniuse.com/#feat=css-media-interaction to target devices that are not mobile, I can do something like `notmobile:hover:font-bold` to make sure the bold style only takes effect not on mobile devices.

The problem is that I'd have to remember to always use `notmobile:hover:` everywhere I'm using `hover:`, which clutters the html and could lead to forgetting to use it in certain places.

A feature where we could set `:hover` to only apply for a certain media query that applies globally would be useful. Often the hover styles cause issues on mobile browsers where they're better off not being there.

Alternatively is there a way to write a media query that automatically appends another style to each style? So that when I create the `notmobile` media query I can tell it to generate all its styles appending `:hover` to it. Then I only need to use `notmobile:font-bold` instead of `notmobile:hover:font-bold`. This feature could be a better way of doing it than what I suggested before because this is more generic and could allow for interesting possibilities.

**Comment by estevanmaito** [comment]
Could you expand on this? Because `:hover` is not even triggered on mobile.

> Often the hover styles cause issues on mobile browsers where they're better off not being there.

It could be the case when you have content that is hidden/revealed on hover, but then thats also a problem for eveybody that's not using a mouse.

> Alternatively is there a way to write a media query that automatically appends another style to each style?

It can be done with [plugins](https://tailwindcss.com/docs/plugins/#app)

**Comment by rightaway** [comment]
`:hover` is triggered on mobile.

**Comment by stefanfisk** [comment]
`:hover`s behavior is browsers dependent on mobile. Safari sets hover on touch, and only removes it once another element is touched.

**Comment by rightaway** [comment]
Exactly and this inconsistency is another reason to want to disable them.

**Comment by VaibhavAcharya** [comment]
You can create your own media rule to do this.
Add this to your `tailwind.config.js`

```
module.exports = {
    theme: {
        extend: {
            screens: {
                'notmobilehover': {'raw': '(hover: hover)'},
            }
        }
    }
}
```
This will check if hover is supported by the device and only run if media query translates to true.
You can use it like this :

`<div class="notmobilehover:bg-red-400">hover over me</div>`

**Comment by VaibhavAcharya** [comment]
Best way is to use media query to detect if a device supports hover and only disable it if it does not.

This can be done by adding this to your `tailwind.config.js` file :
```
module.exports = {
    theme: {
        extend: {
            screens: {
                'betterhover': {'raw': '(hover: hover)'},
            }
        }
    }
}
```

Now you can use it like this : `betterhover:font-bold`

**Comment by royvanv** [comment]
The downside to @VaibhavAcharya's solution is that it is currently not possible to make it responsive.
