### ISSUE TITLE
[email protected] in Tailwind CDN link url

### ISSUE THREAD

**Issue by iBelieve** [tailwindlabs/tailwindcss#1759]
The CDN URL at https://tailwindcss.com/docs/installation/ shows `[email protected]` instead of what I assume should be the package name and version. The `[email protected]` link below leads to https://tailwindcss.com/cdn-cgi/l/email-protection

---

<img width="697" alt="Screen Shot 2020-05-12 at 9 30 54 PM" src="https://user-images.githubusercontent.com/3230912/81764742-de5f9500-9497-11ea-8c41-1650ada865ae.png">

---

<img width="971" alt="Screen Shot 2020-05-12 at 9 31 31 PM" src="https://user-images.githubusercontent.com/3230912/81764776-f46d5580-9497-11ea-98cd-bca3db942698.png">

**Comment by estevanmaito** [comment]
CloudFlare thinks you're a bot.

> By enabling Cloudflare Email Address Obfuscation, email addresses on your web page will be obfuscated (hidden) from bots, while keeping them visible to humans. In fact, there are no visible changes to your website for visitors.

From the first link in your "Email Protection" print https://support.cloudflare.com/hc/en-us/articles/200170016-What-is-Email-Address-Obfuscation-
