### ISSUE TITLE
group-hover prefix stopped working?

### ISSUE THREAD

**Issue by gilbert** [tailwindlabs/tailwindcss#1786]
See [this flems](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ALeBbKIANCAGYCWMYaA2qAHYCGuEamO+RIsA9nYn6wA8UMnQDWAAiwAnCCQC8AHRA54ABzCoA9FoCudNWIDmGHri3wGFAO6iksMGAACARgwAWDAFYtSMmHgLKyhbOiQMXFFTR2UJWSglcHgAT0osCAh4ZQA+RTo8wT8ANwlYKAZHRKNpbl01CQAjIwBaaywyRCluIohpVCbmhqhdCGavAAZxnLyJCUF6soqwRMQAD3hm6oZk5oBOSYlq2rVmrG7e1DWNto6IHIA5CGsJAAUagCs4eEEtNVy6WbzUrlSrKK6baTbZoAdgORzqp3OfXBN0QOQAwrIGJ0GBI6E8JGoPl8JCQargJLiigxpGRMskJNwSBIAjT4KIjBJELg1OVEGAMD8-gVfGQiv9OJAYAgyLwqOgAGyocYgAC+hHoTBY6Aw7yoxB4fAgAnQao1IEYzFY0X1XF4-HgrDVAF1VUA). I thought maybe `group-hover` had to be enabled, but the [docs](https://tailwindcss.com/docs/configuring-variants/#app) say it's supported out of the box.

**Comment by adamwathan** [comment]
It's supported but not enabled. See docs here:

https://tailwindcss.com/docs/pseudo-class-variants#default-variants-reference

**Comment by gilbert** [comment]
Ah! Got it, thank you. Maybe adding this to the page could help others like me in the future:

> The following variants are supported out of the box (but not all are enabled by default):

**Comment by estevanmaito** [comment]
@gilbert but it already says that, under group hover documentation https://tailwindcss.com/docs/pseudo-class-variants/#group-hover

**Comment by gilbert** [comment]
@estevanmaito I don't see it? The verbiage under that part of the page is the same for every other variant, including built-in ones like `hover:`.

**Comment by estevanmaito** [comment]
This is exactly what is written:

You can control whether `group-hover` variants are enabled for a utility in the `variants` section of your `tailwind.config.js` file:

```js
// tailwind.config.js
module.exports = {
  // ...
  variants: {
    textColor: ['responsive', 'hover', 'focus', 'group-hover'],
  },
}
````

**Comment by gilbert** [comment]
That doesn't help the original issue. It's not any different from a built-in like hover:

You can control whether `hover` variants are enabled for a utility in the `variants` section of your `tailwind.config.js` file:

```js
// tailwind.config.js
module.exports = {
  // ...
  variants: {
    backgroundColor: ['responsive', 'hover', 'focus'],
  },
}
```
