### ISSUE TITLE
[Feature proposal] Add transition property for width and height

### ISSUE THREAD

**Issue by WoodyDark** [tailwindlabs/tailwindcss#1801]
Transitioning width and height are rather commonly used in creating dropdown menus, charts, progress bars etc. Would like to request for width and height to be added into `.transition` and also add a `.transition-size` class.

**Comment by luukdv** [comment]
Personally, I would recommend against this. `width` and `height` cannot be animated cheaply, and in most cases `transform` can be used instead. For the exceptions, these can be added manually to the Tailwind config.

**Comment by adamwathan** [comment]
No plans to add this to core right now but can always add this in your config 👍🏻
