### ISSUE TITLE
Feature discussion: Cropping off top and aligning baseline for typography

### ISSUE THREAD

**Issue by johot** [tailwindlabs/tailwindcss#1823]
Thank you for creating such a lovely CSS framework! It really speeds up my work and makes everything look so beautiful! ...but I am really missing one feature and would love to discuss it with you :)

We got really inspired by a talk from Mark Dalgleish at SEEK on how to handle Typography in a really nice way. Maybe you have already seen it but here are some links regarding the topic:

https://www.youtube.com/watch?v=jnV1u67_yVg (10:20 mark)
https://css-tricks.com/how-to-tame-line-height-in-css/

The gist of it all is basically that we want to remove the white space we get around text when doing something simple as a `<span>`.

Even if we set the line-height to `tight` (in Tailwind) or to the same value as the `font-size` we always end up with some white space around the text. This makes it harder to create nice layouts where for example I want an equal spacing on the top of a Heading (say inside a Card) and say to the left of the heading. Even if the Card itself had a padding of say 24px we always get more space above the heading than 24px because of that extra whitespace which doesn't look as balanced (in my mind) leading to different line-height hacks or negative margins to fix.

By also removing the white space under the text we can more easily create vertical rhythm and align baselines if that is your thing :)

Is this anything you considered for tailwind? Id love to help and explain more if needed (I've written some good docs about this topic), we implemented this in our design system (React) and it works really great. I guess this could be implemented in PostCSS as new utility css classes?

Would love to hear what you think of this topic, and thank you again :)

**Comment by nternetinspired** [comment]
The issue with all of the hacks I've seen to ’fix’ handling of lineheight in css is that they all rely on a magic number, specific to the font be used. How do you calculate the cap height for font when you don't know which one is displayed by the browser?

The only point at which you can be sure, or reasonably sure, which font is being used by the browser is when you reduce the font-stack to a single font.

Personally I can't see how this could be workable at the framework level, this is a per-project customisation no?

**Comment by johot** [comment]
Yes @nternetinspired you are totally correct in the difficulties with this. I mostly wanted to bring up the discussion to see if what opinions the tailwindcss team specifically @adamwathan and @reinink has regarding this topic.

For example is it totally unnecessary, too hard to get right (like you suggest) etc, a good idea and so on :)

What I could see as as a possible solution (at the framework level) is an optional tool for generating utility classes for font baseline and cropping fixes (using PostCSS), but another solution is ofc to simply let consumers create this themselves if needed.

It's a pity this is so hard in CSS, it has been so nice and helpful to have in our projects and make for designs that look really really great with very balanced white space, aligning of elements and so on.

**Comment by adamwathan** [comment]
I wish CSS worked this way but unfortunately it doesn't and the tricks required to make it happen are a little heavy-handed to apply at a framework level in my opinion 😞  Maybe one day CSS will be better!

**Comment by SergiArias** [comment]
I was thinking of giving the same feedback. Tailwind is great for spacings, but with the poorly designed typography system the magic just gets broken. I apply this hack to all my websites with a variant that uses pseudoselectors and translateY transforms.
I think this tool autocalculates the crop values: https://seek-oss.github.io/capsize/
I agree it should not be part of the tailwind framework, but an official plugin would be awesome.
Thanks for considering though!

**Comment by acalvino4** [comment]
I believe the new [text-box](https://developer.mozilla.org/en-US/docs/Web/CSS/text-box) css property does this. Not widely supported yet, but perhaps `* {text-box: trim-start cap alphabetic;}` could go into `preflight.css` in the next major version as it really is the most sensible default.

**Comment by acalvino4** [comment]
Along the same lines, would be awesome if switching the font kept the same font height with no further changes by the user. I was thinking about how this could be achieved, and came up with the following theoretical solution.
- `font-family` utilities are modified to also output `--cap-height-ratio: ___` with value based on font metrics.
    - For most common open source fonts, these metrics can be pulled from [capsize](https://github.com/seek-oss/capsize) at build time.
    - For other fonts, would need some way for the user to provide and/or compute this number.
    - `cap-height-ratio` probably defaults to 1; which would preserve the way fonts currently work.
- `text-size` utilities are modified to use `calc` and divide the theme variables by the current value of `—cap-height-ratio`. e.g. `font-size: calc(var(--text-xs)/var(--cap-height-ratio));`
- `text-size` utilities can easily make line-height relative to actual font height using new `cap` unit. e.g. `line-height: 2cap` (once that is widely available, of course)

I realize tw only provides some basic font stack options, so in this theoretical implementation, its role would simply be
- calculate `font-size` and `line-height` based on `--cap-height-ratio` (defaulted to 1) and `cap` unit, respectively
- when user sets custom font family options via theme, provide a way to pass in `--cap-height-ratio` for the provided font.
