### ISSUE TITLE
[Feature Proposal] Ability to build all classes for the purpose of IDE completions

### ISSUE THREAD

**Issue by tylergets** [tailwindlabs/tailwindcss#1844]
Hey Tailwind Team, absolutely love it and been a long term user.

It would be really useful for me (and possibly others?) to be able to generate a css file with all of the tailwind classes, without purging or requiring an input CSS file. 

The purpose being IDE completitons, webstorm for example will pick up the CSS file and provide hints. There is plugins for some IDEs, but this is a more universal solution. 

Right now this is kind of cumbersome and I think it may be somewhat common issue for people. 

My current solution is an npm script with
```npx tailwind build tailwind.css -o .tw.css```

where tailwind.css is just a css file with

```
@tailwind base;

@tailwind components;

@tailwind utilities;
```

I then handle purging outside of tailwind.

Any thoughts? I'd be happy to open a PR.

**Comment by adamwathan** [comment]
Interesting idea! Are you basically just asking for the ability to do this:

```
npx tailwindcss build -o tw.css
```

...so that you could build a CSS file without manually creating the input file or specifying it on the command line? If that's all it would take I don't see why we couldn't support that.

**Comment by tylergets** [comment]
Yup that more or less gets me what I am looking for.

Only thing would be that we need to ignore purge settings, if there isn't already a separate flag for that

**Comment by OwenMelbz** [comment]
@tylergets 1.6 supports the above command to generate a .css without needing an input file :)
