### ISSUE TITLE
Importing tailwind config file in a Create-React-App breaks while attempting a production build

### ISSUE THREAD

**Issue by rohanfaiyazkhan** [tailwindlabs/tailwindcss#1853]
Hi, first of all thank you for all your work on this wonderful project.

I faced this particular edge case while importing the tailwind config so I could extract breakpoint variables using `resolveConfig` according the [referencing config in Javascript guide](https://tailwindcss.com/docs/configuration/#referencing-in-javascript).

```js
import tailwindConfig from "../../../tailwind.config";
import resolveConfig from "tailwindcss/resolveConfig";

const config = resolveConfig(tailwindConfig);

const mdBreakpoint = config.theme.screens.md
```

While this works just fine in development, it breaks when I run `yarn build` with this error:

```
Failed to compile.

./src/core/utils/tailwindUtils/tailwindTheme.ts
Attempted import error: '../../../tailwind.config' does not contain a default export (imported as 'tailwindConfig').
```

I apologize if the problem is with CRA and not tailwind but I definitely would like to get to the bottom of this.

**Comment by estevanmaito** [comment]
I think it has something to do with Webpack seeing mixed `import` and `module.exports`

What happens if you change your imports to `require`s?

```js
const tailwindConfig = require("../../../tailwind.config");
const resolveConfig = require("tailwindcss/resolveConfig");
```

*considering that both files export using `module.exports`

**Comment by rohanfaiyazkhan** [comment]
It then compiles fine but throws a runtime error.

```
TypeError: "exports" is read-only
```
