### ISSUE TITLE
[Feature Request] `blur` for `filter` and `backdrop-filter`

### ISSUE THREAD

**Issue by iDuuck** [tailwindlabs/tailwindcss#1880]
I would like to have something where I can blur an element with (perhaps even blur the background).

### Blur of an element

This can be achieved with the following code:
```
.blur {
  filter: blur(8px);
}
```

### Blur of the background

This can be achieved with the following code:
```
.bg {
  backdrop-filter: blur(0.8);
}
```

**Comment by iDuuck** [comment]
Will also create a PR.

**Comment by Macxim** [comment]
Check out this plugin: https://github.com/benface/tailwindcss-filters

**Comment by iDuuck** [comment]
Thanks, @Macxim! However, I think this would be a good addition to Tailwind. Have you seen my PR (#1881), which contains various customisation options, that the plugin does not offer?
