### ISSUE TITLE
Inconsistent results with color values

### ISSUE THREAD

**Issue by hellomikes** [tailwindlabs/tailwindcss#2008]
Hi

I'm having a nightmare with trying to get colour values to work with a site I'm working on

I've upgraded to v1.4.2 today (having been working on 1.1.2 up till then) as I've been having issues with my implementation of PurgeCSS.  I am now using the configuration built in with Tailwind (great addition btw) but it's now giving me really inconsistent results with purging classes, particularly colors.

This is an example of the colors object I have in my tailwind config:

```
colors: {
      transparent: 'transparent',
      /**
       * Brand colours, and any variations
       */
      brand: {
        dark: '#373A3E',
        medium: '#0E315A',
        light: '#a3ac84',
        'ultra-light': '#F1F3F5'
      },
      /**
       * Colors for body text
       */
      text: {
        primary: '#373A3E',
        secondary: '#72746E'
      },
      /**
       * Any alert message colours
       */
      alert: {
        error: '#cf2500',
        success: '#768F1C'
      },
      /**
       * Any colours for specific categories
       */
      category: {
        alpha: '#7B5901',
        beta: '#768F1C',
        gamma: '#B86A22',
        delta: '#006054',
        epsilon: '#0080A8',
        zeta: '#771325'
      },
      /**
       * Treatments
       */
      treatment: {
        brown: '#907c75',
        'brown-dark': '#7a6b58',
        'brown-light': '#be9f71',
        orange: '#c88a4d',
        'summer-tan': '#c48343'
      }
    },
```
Now, some of the colors work for things such as `bg-*`, `border-*` etc., but some of the colors don't get applied at breakpoints (`md:`), and some colors don't display at all.

When using 1.1.2 I had to construct a custom exclude list for PurgeCSS to get some of these colors to work, and I was hoping that I wouldn't have to do that now (hence my upgrade), however I'm now completely stuck for what to do.  For example, the following doesn't render as expected:

```
<div class="bg-category-alpha md:bg-brand-light lg:bg-category-beta">
  I should change colours with every breakpoint
</div>
```

It will only apply the `bg-category-alpha` class, however if I replace that with `bg-brand-light` or `bg-category-beta`, that class will be applied.

I really am at the end of what I can do to sort this out, so if anyone has any idea of anything I can do I would be grateful as the project is very late in the process to think of alternate solutions.

To give some context to the project setup, it is a Vue Storefront project, with some classes hardcoded into templates/components, and some coming from a data API that is applied to the markup via `serverPrefetch()` and generated with Vue-SSR.  Hardcoded and API-driven classes produce the same inconsistent results.

My purge object:
```
purge: {
    enabled: true,
    content: [
      './path/to/theme/pages/*.vue',
      './path/to/theme/templates/*.html',
      './path/to/theme/components/*.vue',
      './path/to/theme/components/**/*.vue',
      './path/to/theme/components/**/**/*.vue',
      './path/to/theme/css/*.scss',
      './path/to/theme/css/tailwind.css',
      './path/to/theme/css/**/*.scss',
      './path/to/theme/layouts/*.vue',
    ],
  },
```

If there is any other information I can give please ask and I will happily provide

Many thanks

**Comment by estevanmaito** [comment]
The built in purge option was only introduced in 1.4.6 (https://tailwindcss.com/docs/release-notes/#tailwind-css-v1-4)

Try to update your Tailwind version (you're using 1.4.2) and see if the error persists.

**Comment by hellomikes** [comment]
@estevanmaito Hi there, thanks for your reply, I appreciate it

You know, I have no idea why I said 1.4.2, because it is 1.4.6.  The purging is definitely happening, it just seems to be purging too much.

In terms of getting a repo together, because of the structure and requirements needed for a Vue Storefront project this might be a bit difficult to put together, I will see if I can setup a basic Vue project with my tailwind config and see if I can reproduce there though

**Comment by hellomikes** [comment]
OK, I have set up a test repo at https://github.com/hellomikes/tailwind-demo

Now, of course this is working as expected so will probably make me look like an idiot, however it contains my tailwind config (modified the path values in the purge object to match this new structure), as well as some sample components I have currently.

To give an idea of the output I am getting after purge, this is how the 'Fencing' column in my repo currently looks (I've highlighted it to show that there is actual text there and it's not just an image
![image](https://user-images.githubusercontent.com/48011140/86895827-f3a21a00-c0fc-11ea-83b6-786f6027329c.png)

Another difference I have is that I am initiating tailwind through webpack rather then the PostCSS config file:

```
  loader: 'postcss-loader',
  options: {
    ident: 'postcss',
    plugins: loader => [
      require('tailwindcss')(path.join(themeRoot, 'tailwind.config.js')),
      require('postcss-flexbugs-fixes'),
      require('autoprefixer')({
        flexbox: 'no-2009'
      }),
    ]
  }
}
```
But I don't think this is an issue - it all loads, it purges, it just doesn't seem to pick up everything.

I appreciate that this isn't a like-for-like reproduction, however if the issue sounds like anything familiar I'd be happy for any advice

Thanks again

**Comment by hellomikes** [comment]
OK, I think I have a theory for this, I just want to see if anyone else agrees with it?

If I add classes to an element (i.e. `mb-0 md:mb-2`) then reload the page, the changes don't come into effect.  If I create a new class i.e. 
```css
.margin-bottom-med { 
    @apply mb-0;

    @screen md {
        @apply mb-2;
    }
}
```
and then apply this class, it loads straight away.

HOWEVER, if I restart my local dev server, the original tailwind classes are applied.  Likewise I have done a deployment to our production server, and the classes seem to be displaying now.

Is anyone able to confirm if this is a feasible reason behind what is going on?  Does the server need to fully re-build in order for the purge list to update?

If this is the case then my question is, is there any way around it?  We have about 90% of our content coming from blocks sent via an ElasticSearch API, and so we ideally want style classes to be applied as and when we need them.  If this is not possible, what do we think the best solution would be, as ideally we want to purge stuff but don't want to write an allow list with everything we need.  

Do people think it would be best to write CMS friendly classes and apply the styles, so rather then people adding `bg-brand-dark text-white font-black p-5` they can add `button-primary` (though the reason I wanted to use Tailwind was so that we didn't have this rigidness with class names)

On a related note, I have set up a test demo repo if anyone wants to try and verify this - https://github.com/hellomikes/vsf-tailwind

To get started, you will have to do a `yarn && yarn installer` to get API credentials set up (it should allow you to connect to a demo API) and then `yarn dev` to run.  Files are updated in `/src/themes/default/`, and the home page is in the `Pages/Home.vue` file.

Again, I appreciate anyone whoe has any time to help out with this

**Comment by adamwathan** [comment]
Your CSS is purged at build-time, so if your content is changing dynamically at run-time you are probably out of luck. You would have to rebuild your CSS every time the content changed, or you would have to safelist a set of classes that people are allowed to use in dynamic content and make sure those are never purged.

Going to close this as nothing we can do about it I'm afraid, but feel free to [open a discussion](https://github.com/tailwindlabs/tailwindcss/discussions) to continue discussing this topic if you like 👍

**Comment by michaelsmedley** [comment]
Hi @adamwathan 

Thanks for the reply, I really appreciate it.  It also sort proves that I knew what I was talking about when coming up with my theory, so even better!

I'm happy to open a discussion about this because I really want to understand what the best practice is with situations like this - surely in the age of JAM stack and headless CMS's there are people out there who are using Tailwind within content managed markup, so would be good to try and find some general consensus as to what should be done

Thanks again!
