### ISSUE TITLE
add weights for black & white colours

### ISSUE THREAD

**Issue by redxtech** [tailwindlabs/tailwindcss#2064]
This issue is in regard to PR #2063 

When using dynamically generated classes, it is possible that you could have a string like this:
```js
const style = `text-${colour}-${weight}`
```
While this will normally work, it does not when the `colour` variable is either black or white, as there aren't any different weights for those colours.

This PR should fix that by adding all the usual weights to both black and white, while keeping the default colour in place to avoid breaking changes.

**Notes:** When I ran the tests, it told me that a few of the tests failed, but the output of the command was trimmed, so I couldn't see the full context and which tests were the ones that were failing. If anyone could point me in the right direction on how to fix the tests to account for this that would be great, thanks!

**Comment by adamwathan** [comment]
Closing for reasons explained in the PR 👍🏻
