### ISSUE TITLE
Desktop first responsive config, fails to generate few classes?

### ISSUE THREAD

**Issue by shafkathullah** [tailwindlabs/tailwindcss#2076]
### Describe the problem:

Desktop first media queries like below, seemingly fail to produce responsive ```container``` classes & ```max-w-screen-xl``` and similar classes.

```
theme: {
    screens: {
      xl: { max: "1279px" },
      // => @media (max-width: 1279px) { ... }

      lg: { max: "1023px" },
      // => @media (max-width: 1023px) { ... }

      md: { max: "767px" },
      // => @media (max-width: 767px) { ... }

      sm: { max: "639px" },
      // => @media (max-width: 639px) { ... }
    },
}
```

**Comment by adamwathan** [comment]
What exact css for the container would you expect this to generate?

**Comment by shafkathullah** [comment]
Not sure about this, for my project I try to remove all use of container classes from markup, and tried to contain the fluid width with ```max-w-screen-xl``` but it didn't worked.
```
.container {
  width: 100%;
  max-width: 1280px;
}

@media (max-width: 1280px) {
  .container {
    /* max-width: 1280px; */
    max-width: 1024px;
  }
}

@media (max-width: 1024px) {
  .container {
    /* max-width: 1024px; */
    max-width: 768px;
  }
}

@media (max-width: 768px) {
  .container {
    /* max-width: 768px; */
    max-width: 640px;
  }
}
```
https://codepen.io/shafkathullah/full/pogBWVX

**Comment by adamwathan** [comment]
This is sort of what I feared, that for the results to make sense we'd have to do weird math like subtracting/adding one pixel and trying to be hyper intelligent about things. No plans to do that at the moment unfortunately, maybe the `screens` option for the container could be helpful for you to manually configure it though:

https://github.com/tailwindlabs/tailwindcss/blob/master/__tests__/containerPlugin.test.js#L48

If not I'd recommend disabling the container plugin and adding the classes you want yourself 👍

**Comment by shafkathullah** [comment]
Yeah, I felt somewhat same, but for below config taken from [here](https://tailwindcss.com/docs/breakpoints/#max-width-breakpoints)
```
// tailwind.config.js
module.exports = {
  theme: {
    screens: {
      'xl': {'max': '1279px'},
      // => @media (max-width: 1279px) { ... }

      'lg': {'max': '1023px'},
      // => @media (max-width: 1023px) { ... }

      'md': {'max': '767px'},
      // => @media (max-width: 767px) { ... }

      'sm': {'max': '639px'},
      // => @media (max-width: 639px) { ... }
    }
  }
}
```
a div like this
```
<div className="h-20 bg-red-600 sm:bg-blue-600"></div>
```
is expected to have a ```background-color``` of blue in small screens right? but its acting vice-versa.
