### ISSUE TITLE
missing Keyframe css for animations if @tailwind base is missing

### ISSUE THREAD

**Issue by garethworld** [tailwindlabs/tailwindcss#2103]
Just upgraded to 1.6.0 and the animation css is generated but not the matching keyframe css - this is for the default animations and any custom ones I create.  This is the case with a blank config file.  

I have used everything else fine with no @tailwind base; instead using my own smaller reset css.

**Comment by adamwathan** [comment]
Fixed and tagged v1.6.1, thanks for reporting!
