### ISSUE TITLE
Enabling "important" in config breaks all keyframes

### ISSUE THREAD

**Issue by tomhughes-invento** [tailwindlabs/tailwindcss#2113]
### Describe the problem:

When you enable important via the config it applies an `!important` tag to the end of every line in keyframes. This causes the animation to not run in chrome.
For example, with `important` is set to true in the config, the following css is generated for ping:
```
@keyframes ping {
  0% {
    transform: scale(1) !important;
    opacity: 1 !important;
  }

  75%, 100% {
    transform: scale(2) !important;
    opacity: 0 !important;
  }
}

```

Even though this is technically valid CSS, Chrome effectively ignores it as it takes the state of the end of the animation as the overriding value.

### Link to a minimal reproduction:

Config is just the default config, only difference is that `important` is set to true

**Comment by adamwathan** [comment]
Fixed in v1.6.2 👍  Thanks!
