### ISSUE TITLE
flex next breakpoint ignored

### ISSUE THREAD

**Issue by psdon** [tailwindlabs/tailwindcss#2122]
### Describe the problem:
I would like to have 2 columns for a custom breakpoint and 3 columns for `sm` breakpoint using flex. I'm not really sure why `sm:flex-three-rows` is getting ignored, while `ml:flex-two-rows` is workings fined.

### Link to a minimal reproduction:

```
@media (min-width: 425px)
.ml\:flex-two-rows {
    flex: 1 1 40%;
}


// This part is being ignored.
@media (min-width: 640px)
.sm\:flex-three-rows {
    flex: 1 1 30%;
}
```

**Comment by adamwathan** [comment]
Can you link to an actual reproduction on Codepen or similar?

**Comment by psdon** [comment]
@adamwathan 
Minimal reproduction app: https://serene-spence-7d26a7.netlify.app/

**Comment by psdon** [comment]
Here's the minimal reproduction link: https://serene-spence-7d26a7.netlify.app/

**Comment by naydogdu** [comment]
It seem your custom breakpoint is loaded after other breakpoints. You need to keep ordering when you add your custom breakpoint. 

In tailwind.config.js, you must add your 'ml' breakpoint before 'sm', not after 'lg'.

There is a piece of code from your generated CSS file, we can see that .ml: override other breakpoints :

```
@media (min-width:1024px) {
 .lg\:block {
  display:block
 }
 ...
}
@media (min-width:425px) {
 .ml\:block {
  display:block
 }
 .ml\:flex-row {
  flex-direction:row
 }
 .ml\:flex-two-rows {
  flex:1 1 40%;
 }
 ...
```
