### ISSUE TITLE
Adding breakpoints doesn't generate responsive classes

### ISSUE THREAD

**Issue by DallasO** [tailwindlabs/tailwindcss#2130]
### Describe the problem:

When extending the `screens` config with an additional breakpoint, I would expect responsive utilities to also be created, specifically the width utilities.
**E.g.**
`2xl:w-1/2`

_(Please forgive if I'm not using the correct terminology, this is my first `tailwindcss` project 🎉 )_

### Config to a minimal reproduction:

```javascript
module.exports = {
  // Remove unused CSS selectors
  purge: ["./src/**/*.js", "./src/**/*.jsx", "./src/**/*.ts", "./src/**/*.tsx"],
  theme: {
    extend: {
      screens: {
        "2xl": "1660px",
      },
    },
  },
  variants: {},
  plugins: [],
};
```

I see the container breakpoint is working fine, but trying to do a responsive utility results in error:
```
2xl:w-1/2 was not found
```

**Comment by IL4Miy** [comment]
@DallasO 
This is the correct way: https://tailwindcss.com/docs/breakpoints/
```
module.exports = {
  purge: ["./components/**/*.js", "./pages/**/*.js", "./pages/**/*.mdx", "./jobs/**/*.md"],
  theme: {
     screens: {
      '2xl': '1400px',
     }
  },
};
```

**Comment by DallasO** [comment]
That means I'd have to redeclare the default screen sizes as well which doesn't seem intuitive.

Alas, same error with `screens` outside of the `extend`: 
```
2xl:w-1/2 was not found
```

**Comment by adamwathan** [comment]
Where are you seeing that error? I can't think of any place in the code base Tailwind generates that string except for when trying to use `@apply`, which doesn't work with responsive variants regardless.

**Comment by DallasO** [comment]
That's my bad, I guess it was a compatibility issue with `twin.macro`, fixed by upgrading.
I wasn't sure where the errors were coming from.

❤️  my experience with tailwind so far
