### ISSUE TITLE
Static Build OOM (Out of Memory) Error with PurgeCSS/Tailwind

### ISSUE THREAD

**Issue by jhull** [tailwindlabs/tailwindcss#2131]
Thought this was a Nuxt issue, but it looks like it's Tailwind ([original issue in nuxt/tailwindcss module](https://github.com/nuxt-community/tailwindcss-module/issues/132)).

`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

Error is fixed when I rollback to the `1.0.0` version of that module. Not sure what has changed then in Tailwind's Purge, but this is a large app with over 1200 pages, and while I've seen similar errors here: OOM Error, #5931 and nuxt-community/auth-module#286 (comment), neither of them provided a viable solution short of producing a repro - which is not feasible given the nature of the error.

Deploying through Netlify, and waiting on them to see if there is anymore info I can give you - thanks.

**Comment by adamwathan** [comment]
Does it happen locally or only on Netlify? Have you tried increasing the memory limit in node? Unfortunately can't troubleshoot without a repro.

**Comment by jhull** [comment]
So it looks like this was a Node thing. Adding this:

```
[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
```
to my `netlify.toml` file fixed everything. Apologies for not investigating fully first (but appreciate the rec. about node)

**Comment by TommasoAmici** [comment]
I'm getting the same error after upgrading from `^1.9.6` to `^2.0.1`.
I tried bumping the memory limit to 4GB for node, but that wasn't enough. I wen even higher to 8GB and I still got `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

**Comment by acoyfellow** [comment]
I'm running into the same issues after upgrading to 2.0.1. Something for sure is goign on.

**Comment by jhull** [comment]
FWIW, since I was the OP on this, I'm not experiencing this issue anymore, after upgrading to 2.0.1 and building to Netlify. Only thing I had to do was set ENV variable NODE to 12 (since TW requires latest).

**Comment by TommasoAmici** [comment]
I left this aside for a bit, but after some digging I found some circular dependencies in my index.css file. After I removed those it worked fine.

**Comment by frandiox** [comment]
I had the same problem on GitHub Actions. The error mentioned `tailwindExtractor`, that's how I found this issue.
After changing memory limit in Node, it works:

```yaml
- name: Build Frontend
  run: |
    yarn build
  env:
    NODE_OPTIONS: --max_old_space_size=4096
```
