### ISSUE TITLE
`<li>` outside `<ol>` and `<ul>` is still styled

### ISSUE THREAD

**Issue by chengluyu** [tailwindlabs/tailwindcss#2139]
### Describe the problem:

Hi, today I accidentally found `<li>` outside `<ol>` and `<ul>` is still styled. Is this an expected behavior?

### Link to a minimal reproduction:

Just put an `<li>` outside of any `<ol>` and `<ul>`, you'll see the list marker. I've tested on Chrome 84.0.4147.105 and Firefox 80.0b3.

**Comment by itzshahay** [comment]
I'm fairly sure `<li>` are supposed to be within `<ol>` or `<ul>`.

**Comment by merelinguist** [comment]
Correct, the `<li>` element can be a direct child of either the `<ul>` or the `<ol>` elements but it should never exist outside of either of these parent elements, that would be invalid HTML.

**Comment by adamwathan** [comment]
I would just classify this as undefined behavior since it's invalid HTML. No plans to make any changes here.
