### ISSUE TITLE
Default value override variation values because of the css compilation order

### ISSUE THREAD

**Issue by damien-pilot-in** [tailwindlabs/tailwindcss#2140]
### Describe the problem:

If you have a color "red" for example with multiple variations like "400","600" and also a default value for that color, you should be able to use it with classes like that on a element:

`class="text-red text-red-600"`

You should have the variation that should take priority over the default value but it's not the case.
With this example, `text-red` override the value of `text-red-600` because the default value is added after variations in the css compilation.

I tried multiple things in the tailwind config to see if the compiled css change but it doesn't seems to change anything.

### Link to a minimal reproduction:

![issue](https://user-images.githubusercontent.com/62112531/89628436-9389c980-d89c-11ea-94bf-ca84fe4b47a1.jpg)
![tailwind-config](https://user-images.githubusercontent.com/62112531/89628438-94baf680-d89c-11ea-959a-7ab9d18f8c03.jpg)

**Comment by estevanmaito** [comment]
I didn't get it right, maybe because of the lack of context but, what is the use case of this? Why don't you simply define just one shade of the color?

This would also raise a warning using Intellisense, something like "text color is duplicate/already present"

**Comment by adamwathan** [comment]
@damien-pilot-in The issue is that in JavaScript numeric keys are always sorted before alpha keys:

![image](https://user-images.githubusercontent.com/4323180/89653326-dcd61b00-d894-11ea-9301-5e23f750c0fa.png)

Solution is to define your colors not using the object syntax, unfortunate but don't have a better solution for you.

```js
colors: {
  'red-500': '...',
  'red-100': '...',
  'red-200': '...',
  // ...
  'red': '...',
}
```
