### ISSUE TITLE
Issue with tailwind purge and postcss-nested

### ISSUE THREAD

**Issue by tillkruss** [tailwindlabs/tailwindcss#2152]
Prior to the Tailwind `purge` option this CSS worked and wasn't purged:

```css
.dropdown {
    @apply relative;

    &.is-expanded {
        .dropdown-menu {
            @apply block;
        }
    }
}
```

Now I need to wrap all `&.classname` in `start ignore` blocks.

The JavaScript for that class like like:

```js
el.classList.add('is-expanded');
```

This works by the way:

```css
.dropdown {
    @apply relative;
}

.dropdown.is-expanded {
    .dropdown-menu {
        @apply block;
    }
}
```

**Comment by adamwathan** [comment]
Can you post a project that reproduces? My gut is to say you should make sure the nesting plugin runs _before_ Tailwind which I bet fixes it.

**Comment by tillkruss** [comment]
That worked, kinda. Might be worth updating [the docs](https://tailwindcss.com/docs/using-with-preprocessors#nesting).

```
[
    require('postcss-import'),
    require('postcss-nested'),
    require('tailwindcss'),
    require('autoprefixer'),
]
```

However, now the `@screen sm` directives don't work any longer.

What's the best practice here, not use nesting? Use `postcss-nesting`?

**Comment by adamwathan** [comment]
Use the `bubble` option to make sure `@screen` directives are bubbled:

https://github.com/postcss/postcss-nested#bubble

**Comment by tillkruss** [comment]
This isn't working with either `bubble` or `unwrap` and with `postcss-nested` before or after tailwind.

Either media queries don't do `@apply`, or nested selectors are ignored. 

I ended up not using `@apply` directives inside @screen as a workaround.

**Comment by adamwathan** [comment]
Yeah there's another issue about this now too, bleh. Have to fix a bug in postcss-nested unfortunately.

**Comment by adamwathan** [comment]
Here's the open issue that is the same underlying issue:

https://github.com/tailwindlabs/tailwindcss/issues/2192

**Comment by tillkruss** [comment]
Perfect. I'll follow that 👍🏻

**Comment by ollyollyollyltd** [comment]
For anyone here from Google, note that the [Tailwind docs](https://tailwindcss.com/docs/using-with-preprocessors#nesting) now recommend using `tailwindcss/nesting`:

> To add support for nested declarations, we recommend our bundled `tailwindcss/nesting plugin`, which is a PostCSS plugin that wraps [postcss-nested](https://github.com/postcss/postcss-nested) or [postcss-nesting](https://github.com/jonathantneal/postcss-nesting) and acts as a compatibility layer to make sure your nesting plugin of choice properly understands Tailwind’s custom syntax like `@apply` and `@screen`.
