### ISSUE TITLE
hover:bg-opacity-* not working

### ISSUE THREAD

**Issue by rahadkc** [tailwindlabs/tailwindcss#2167]
### Describe the problem: 
hover:bg-opacity-* not working when using custom color variable using css variable. 
hover:bg-opacity-* works when using default Tailwind color variable

  I have custom css color variable generated using tailwind.config.js

![custom-tailwind-color-variable](https://user-images.githubusercontent.com/8745638/90303349-1fb87400-decf-11ea-8137-7cc61bbc504e.png)

when I am using `bg-gray-500 hover:bg-opacity-50` it works fine.
But when I am using `bg-primary hover:bg-opacity-50` , it doesn't work. Opacity have no effect.

Tailwind Version: 1.5.2

**Comment by kevinruscoe** [comment]
The opacity utils use a --bg-opacity var for the opacity, so your colours will need to use that. Make a look through the code, you'll see what needs to change.

**Comment by crswll** [comment]
If you set your variables like
```css
:root {
  --primary: 0 0 0;
  --secondary: 0 255 0;
}
```
You can do:
```js
{
  primary: 'rgb(var(--primary) / var(--bg-opacity, 1))',
  secondary: 'rgb(var(--secondary) / var(--bg-opacity, 1))',
}
```

**Comment by rahadkc** [comment]
@crswll  it's bit complex though. I'm just using `opacity-*` instead of `bg-opacity-*`. It serves the purpose now.
Anyway, thanks for your answer.

**Comment by agl320** [comment]
> @crswll it's bit complex though. I'm just using `opacity-*` instead of `bg-opacity-*`. It serves the purpose now. Anyway, thanks for your answer.

Does not serve the purpose

**Comment by crswll** [comment]
It's been a long time since this post. You can do this a lot easier now:

```css
:root {
  --a: red;
  --b: #00f;
  --c: hsl(230, 50%, 50%);
}
```
then in the config do:
```
colors: {
  a: `color-mix(in srgb, var(--a) calc(100% * <alpha-value>), transparent)`,
  b: `color-mix(in srgb, var(--b) calc(100% * <alpha-value>), transparent)`,
  c: `color-mix(in srgb, var(--c) calc(100% * <alpha-value>), transparent)`,
}
```
A sample play: https://play.tailwindcss.com/f8a1pjWafv?file=config

**Comment by mylmz10** [comment]
You can do it with using `<alpha-value>`

```js
{
  primary: 'rgb(var(--primary) / <alpha-value>)',
  secondary: 'rgb(var(--secondary) / <alpha-value>)',
}
```
