### ISSUE TITLE
Responsive font sizes and line-height doesn't play well with the new `defaultLineHeights` feature.

### ISSUE THREAD

**Issue by pktharindu** [tailwindlabs/tailwindcss#2188]
Say you have a line-height defined like `leading-relaxed` for example, and you have some responsive font sizes like `md:text-xl`.
In this case, `leading-relaxed` will be overwritten by the default line-height in `md:text-xl` because the line-height defined in responsive font size is more specific.

![image](https://user-images.githubusercontent.com/23132672/90586082-f4e25e80-e1f3-11ea-9ebb-45de24500901.png)

Now the only way to actually apply the line-height I want is to define it for all responsive font sizes used, which I think is counter-intuitive.
For example, now we have to do `leading-relaxed sm:leading-relaxed sm:text-lg text-base` instead of  `leading-relaxed sm:text-lg text-base`.

**Comment by adamwathan** [comment]
Personally I think the current behavior makes the most sense, as changing the font-size should almost always come with a change in line-height anyways. Changing this would involve some pretty complex and specific hacks in the codebase as well so no plans to make any changes here sorry. If you'd rather not use default line-heights I would recommend overriding that part of the default config when this becomes the default, and just not using the `defaultLineHeights` option in the mean time.

Appreciate the suggestion though, thank you!
