### ISSUE TITLE
applyComplexClasses compiler stuck with @apply inside media queries or variants

### ISSUE THREAD

**Issue by minimit** [tailwindlabs/tailwindcss#2192]
### Describe the problem:

With the new applyComplexClasses if you put `@apply` **the old way**: inside a `@screen` (media query) or a `&:hover` (variant), the complier gets stuck (using postcss loader in webpack).

### Link to a minimal reproduction:

This css makes the compiler gets stuck (apply content can be anything):

```
.selector {
  @screen md {
    @apply w-2/6;
  }
}
```

```
.selector {
  &:hover {
    @apply text-white;
  }
}
```

I know the I should use the new way to `@apply md:w-2/6` and `@apply hover:text-white`, but for backward compatibility could be good fixing this bug, or at least give an error in the compiler, right now it just gets stuck compiling.

**Comment by minimit** [comment]
This should be fixed mainly because it bugs also when you apply custom selectors where you can't use variants in the `@apply`:

```
.selector {
  @screen lg {
    @apply overflow-sub;
  }
}
```

**Comment by adamwathan** [comment]
This is a tough one to fix but I'm sure we can sort it out. In the mean time I would move your nesting plugin _before_ Tailwind so that there is no nested CSS left once the CSS is processed by Tailwind.

**Comment by adamwathan** [comment]
This should be 95% fixed now (some really complex edge cases we don't handle yet but we will tackle soon). Going to close this but can capture the edge cases in a new issue.

Will tag new patch release in a couple min here.

**Comment by AndrewBogdanovTSS** [comment]
@adamwathan one thing I just noticed when trying out `applyComplexClasses` is that all of my `!important` statements are stripped out from the compiled code.
I use PostCSS with the next build config:
```
postcss: {
    // Allows the use of single line comments
    // in .pscss and .vue files
    parser: 'postcss-comment',
    plugins: {
      'postcss-import': {},
      tailwindcss: {},
      'postcss-nested': {},
      'postcss-hexrgba': {},
      'postcss-custom-properties': {
        importFrom: [{customProperties}]
      },
      autoprefixer: {}
    },
    preset: {
      // Change the postcss-preset-env settings
      autoprefixer: {
        grid: true
      }
    }
  },
```
than in my vue component I have
```
.swiper{
   &-pagination {
      bottom: -40px !important;
   }
}
```
resulting code just doesn't contain that !important:
```
.swiper-pagination {
    bottom: -40px;
}
```
without `applyComplexClasses` !important is there

I tried to use 
```
'postcss-nested': { bubble: ['screen']},
```
above tailwindcss in the config but that that just makes build fail
