### ISSUE TITLE
Needs configuration to set log level or disable logs

### ISSUE THREAD

**Issue by naturalethic** [tailwindlabs/tailwindcss#2199]
### Describe the problem:

Info logs are printing to console.  Add-ons should be respectful and quiet when asked.

There should be a configurable option to set the desired log level.

### Link to a minimal reproduction:

Just run tailwind.

```
info - You have opted-in to future-facing breaking changes: removeDeprecatedGapUtilities
info - These changes are stable and will be the default behavior in the next major version of Tailwind.
```

Nice to know, but uses valuable console real estate.

**Comment by cossssmin** [comment]
Yes, please! Since you have to manually opt in anyway, I think it would be ok to even not show the `info` logs 😇

**Comment by adamwathan** [comment]
I've disabled those info messages as of v1.7.3, now we only warn about experimental features and upcoming breaking changes 👍
