### ISSUE TITLE
Tailwind 1.7.2 logging to stdout  breaks CSS

### ISSUE THREAD

**Issue by bep** [tailwindlabs/tailwindcss#2203]
I use Tailwind in Hugo via `postcss-cli` reading the output from `stdout`. This has worked great, but in `1.7.2` I see the following in the header of my CSS file, which doesn't ... work.

Ref. `postcss-cli` docs:

```bash
If neither -o, --dir, or
--replace is passed, it writes to stdout.
```

```
warn - You have enabled experimental features: applyComplexClasses
warn - Experimental features are not covered by semver, may introduce breaking changes, and can change at any time.

risk - There are upcoming breaking changes: removeDeprecatedGapUtilities
risk - We highly recommend opting-in to these changes now to simplify upgrading Tailwind in the future.
risk - https://tailwindcss.com/docs/upcoming-changes
```

It would be great if you could either/both:

1. Log these to `stderr`
2. Provide a way to toggle off the above output.

**Comment by jensamunch** [comment]
seeing the same thing..thanks for filing @bep

**Comment by bep** [comment]
@jensamunch there's a ugly workaround in https://github.com/gohugoio/hugo/issues/7581

**Comment by jensamunch** [comment]
Thanks @bep it's working great locally but Netlify keeps overwriting it...i'm tearing my hair out!!

**Comment by jensamunch** [comment]
for now just deploying /public with no build but honestly 🤯 

thanks for the ugly workaround 🤗
