### ISSUE TITLE
New color palette and other experiments on the docs site

### ISSUE THREAD

**Issue by frederikhors** [tailwindlabs/tailwindcss#2207]
As stated in Release notes for 1.7 I'm trying to use

```js
experimental: {
  uniformColorPalette: true
}
```

I really like new colors, but is there a way to see them all like the ones now on docs site?

Is there a "future" version to see `master` branch news day by day there?

Something like:

![image](https://user-images.githubusercontent.com/41120635/90794127-b2607500-e30c-11ea-860b-049fd1538284.png)

Why not?

**Comment by stnwk** [comment]
You can take a look at my comment here: https://github.com/tailwindlabs/tailwindcss/pull/2132#issuecomment-675639181 :)


![image](https://user-images.githubusercontent.com/2981250/90633627-aac6a080-e226-11ea-9f71-513fb4956cb0.png)

**Code Sandbox:** https://codesandbox.io/s/tailwind-color-palette-comparison-f1igi

**Comment by stefanbuck** [comment]
I wrote a [Color Theme Explorer for Tailwind CSS](https://stefanbuck.com/tailwind-color-theme-explorer) which supports the upcoming color palette. Super handy if you have to tinker with the Tailwind CSS colors.

<img width="1005" alt="Screenshot 2020-11-06 at 22 04 25" src="https://user-images.githubusercontent.com/1393946/98415762-2bef4000-207e-11eb-9abb-b3256e9d1d3a.png">
