### ISSUE TITLE
NODE_ENV always production in tailwind.config.js with parcel 2

### ISSUE THREAD

**Issue by vincaslt** [tailwindlabs/tailwindcss#2223]
### Describe the problem:

I'm trying to purge only production builds with parcel 2. My parcel config includes this:

```
const defaultTheme = require('tailwindcss/defaultTheme')

console.log('env', process.env.NODE_ENV)
module.exports = {
  purge: {
    enabled: process.env.NODE_ENV === 'production',
    content: ['./public/**/*.html'],
  },
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter var', ...defaultTheme.fontFamily.sans],
      },
    },
  },
  plugins: [
    require('@tailwindcss/ui')({
      layout: 'sidebar',
    }),
  ],
}
```

However, it seems that in tailwind config, process.env.NODE_ENV is always production, no matter what I set:

![image](https://user-images.githubusercontent.com/944727/90939048-4b79b380-e413-11ea-8684-b457c3264c5d.png)

I added a console log in the app's index.js and it logs `development` as expected.

**Comment by lukekarrys** [comment]
I think this is a bug with Parcel 2: https://github.com/parcel-bundler/parcel/issues/4550

**Comment by adamwathan** [comment]
Unfortunately this seems to be a bug in Parcel. I would recommend setting the `enabled` option based on something else instead if you need to use Parcel until that bug is fixed — can you use a custom environment variable perhaps or does the Parcel bug still cause issues then?

Going to close as not a Tailwind bug but happy to keep discussing workarounds.

**Comment by akaibukai** [comment]
I still have the same issue..
I was pulling my hair trying to figure out what was going on..

Does anyone find a workaround?

**Comment by scastiel** [comment]
Until the Parcel bug is fixed, my workaround is to use another environment variables, which does not seem to cause the same issue.

_package.json_:
```json
"scripts": {
  "build": "parcel build public/index.html",
  "start": "DISABLE_TAILWIND_PURGE=yes parcel serve public/index.html"
}
```

_tailwind.config.js_:
```js
module.exports = {
  purge: process.env.DISABLE_TAILWIND_PURGE
    ? false
    : ['./src/**/*.tsx', './public/**/*.html'],
```

Hope it helps 🙂
