### ISSUE TITLE
Extraneous info type Logs 

### ISSUE THREAD

**Issue by ahmadawais** [tailwindlabs/tailwindcss#2252]
I'm using the latest tailwind with Next.js and keep getting a warning about `removeDeprecatedGapUtilities`.
![image](https://user-images.githubusercontent.com/960133/91413578-c522fe80-e864-11ea-830a-e867d55204b8.png)

So I clicked the URL and added to my tailwind config:

```js
future: {
		removeDeprecatedGapUtilities: true,
	},
```

And now I am getting:

![image](https://user-images.githubusercontent.com/960133/91413470-99a01400-e864-11ea-8057-ac2f0360188c.png)

This is extraneous. I know I put it in the config. I don't need to be told that. I'm saying this that I love to keep the log info minimal. 

This log goes away only when I set `removeDeprecatedGapUtilities: false,` which I shouldn't be doing right? I'm also not using this CSS feature (maybe prose typography uses it).

Can we address this?

**Comment by adamwathan** [comment]
You’re not on the latest version, the extra logging was removed in 1.7.3. Just need to update.

**Comment by ahmadawais** [comment]
Dang. There was a monorepo conflict — reading the wrong version of the tailwind on my end. Just fixed it. Thanks.
