### ISSUE TITLE
Extended font size scale can't be accessed with the theme function

### ISSUE THREAD

**Issue by aerni** [tailwindlabs/tailwindcss#2253]
### Describe the problem:
The experimental extended font size scale can't be accessed with the `theme` function. Other experimental features like the extended spacing scale work as expected. The issue probably lies in using the `extend` object. The extended font size scale is the only experimental feature using it. If you remove `extend`, the theme function picks it up correctly.

```js
export default {
  theme: {
    // extend: {
      fontSize: {
        '7xl': ['5rem', { lineHeight: '1' }],
        '8xl': ['6rem', { lineHeight: '1' }],
        '9xl': ['8rem', { lineHeight: '1' }],
      },
    // },
  },
}
```

### Link to a minimal reproduction:

Try accessing the experimental font size scale with the `theme` function. It won't work. Remove the `extend` object and try again. Now it works. https://github.com/tailwindlabs/tailwindcss/blob/v1.7.0/src/flagged/extendedFontSizeScale.js

**Comment by simonswiss** [comment]
Hey @aerni 👋

I wrote a test (see PR linked above ☝️) that tries to access the experimental font sizes via the theme function, and it passes.

The test successfully access values from both the default fontSize scale (`5xl`) and the extended scale (`7xl` and `8xl`).

```javascript
test('experimental extended font sizes can be accessed via the `theme()` function', () => {
  return postcss([
    tailwind({
      experimental: {
        extendedFontSizeScale: true,
      },
    }),
  ])
    .process(
      `
        .heading-1 { font-size: theme('fontSize.8xl'); }
        .heading-2 { font-size: theme('fontSize.7xl'); }
        .heading-3 { font-size: theme('fontSize.5xl'); }
      `,
      { from: undefined }
    )
    .then(result => {
      const expected = `
        .heading-1 { font-size: 6rem; }
        .heading-2 { font-size: 5rem; }
        .heading-3 { font-size: 3rem; }
      `

      expect(result.css).toMatchCss(expected)
    })
})

```

Are you able to share a reproduction of the bug in a CodeSandbox or a GitHub repo?

**Comment by aerni** [comment]
I tested it again on another project and it works as expected. It was a configuration error on my part. Sorry for that.

**Comment by simonswiss** [comment]
All good, no worries 👍
