### ISSUE TITLE
Custom left/top not working

### ISSUE THREAD

**Issue by blackstormx** [tailwindlabs/tailwindcss#2282]
I am using some custom left/top values in taliwind for `left:1` and `top:1`, but for some reason, they just aren't working.

```
module.exports = {
  purge: [],
  theme: {
    extend: {
      left: {
        "1": "15px"
      },
      top: {
        "1": "15px"
      }
    }
  },
  variants: {
    width: ["responsive"],
    left: ["responsive"],
    top: ["responsive"]
  },
  plugins: [
    require("postcss-preset-env")({ stage: 0 }),
    require("tailwindcss")("tailwind.config.js"),
    require("autoprefixer")
  ]
};
```

Thats how I use them: 

```
   <span className={
                    "top-1 left-0 md:left-1  "
                  }>
```
Neither responsive prefixes work.

Package.json:

```
  "dependencies": {
    "autoprefixer": "^9.8.6",
    "next": "9.5.1",
    "postcss-cli": "^7.1.1",
    "postcss-import": "^12.0.1",
    "postcss-preset-env": "^6.7.0",
    "postcss-scss": "^2.1.1",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-redux": "^7.2.1",
    "redux": "^4.0.5",
    "sass": "^1.26.10",
    "tailwindcss": "^1.7.3"
  }
```

Node: v14.2.0

**Comment by adamwathan** [comment]
You need to add your customizations under the “inset” key, not “left” or “top”:

https://tailwindcss.com/docs/top-right-bottom-left#customizing
GitHub <notifications@github.com> wrote:
“I am using some custom left/top values in taliwind for left:1 and top:1, but for some reason, they just aren't working.

module.exports = {
  purge: [],
  theme: {
    extend: {
      left: {
        "1": "15px"
      },
      top: {
        "1": "15px"
      }
    }
  },
  variants: {
    width: ["responsive"],
    left: ["responsive"],
    top: ["responsive"]
  },
  plugins: [
    require("postcss-preset-env")({ stage: 0 }),
    require("tailwindcss")("tailwind.config.js"),
    require("autoprefixer")
  ]
};

Thats how I use them:

   <span className={
                    "absolute w-full md:w-auto text-center transition-all duration-500 ease-in-out font-bold inline-block color-red top-1 left-0 md:left-1  "
                  }>

Neither responsive prefixes work.

Package.json:

  "dependencies": {
    "autoprefixer": "^9.8.6",
    "next": "9.5.1",
    "postcss-cli": "^7.1.1",
    "postcss-import": "^12.0.1",
    "postcss-preset-env": "^6.7.0",
    "postcss-scss": "^2.1.1",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-redux": "^7.2.1",
    "redux": "^4.0.5",
    "sass": "^1.26.10",
    "tailwindcss": "^1.7.3"
  }

Node: v14.2.0”

**Comment by blackstormx** [comment]
Still doesn't work.

Changed to:

```
module.exports = {
  purge: [],
  theme: {
    inset: {
      "1": "15px"
    }

```

**Comment by adamwathan** [comment]
Please create a GitHub project that reproduces the issue, much easier to see what is misconfigured then 👍🏻

**Comment by adamwathan** [comment]
Here's a working minimal example for you to compare against:

https://tailwind.run/E6JKU4

The other thing you were missing was adding a class like `absolute` or `relative` to your element, you can't use `top` with statically positioned elements (just how CSS works.)

**Comment by blackstormx** [comment]
I have more classes to that component in the real project. What I meant by "not working" is that .top-1 and .left-1 classes didn't appear in devtools styles section at all, neither they were generated in final tailwind.css file. 

I will try to add sample project recreating the problem, if I don't solve it myself, but not sure when.

**Comment by blackstormx** [comment]
I am sorry for wasting your time. I just forgot to run tailwind css build. I hope we can delete this github issue from the observable universe, since github is planning to store lot of its data on glass chips in Antarctica for thousands of years. I don't want this issue to survive there :D
