### ISSUE TITLE
Not throwing errors for nested circular dependency.

### ISSUE THREAD

**Issue by jjjrmy** [tailwindlabs/tailwindcss#2293]
This throws a circular dependency error (which is expected).
```css
.rounded-full {
    @apply rounded-full;
}
```

This doesn't throw an error but just gets stuck then crashes with some out of memory error.
```css
.rounded-full {
    img { @apply rounded-full; }
}
```

I'm pretty sure the above code worked at one time, but probably doesn't anymore due to the recent changes.
But it should probably throw an error instead of just loading forever then crashing.

**Comment by adamwathan** [comment]
At its core this is the same underlying issue as #2192, so going to close this one but once we fix general support for nesting with `@apply` you will see a useful error here instead of the infinite loop crashing crap 👍
