### ISSUE TITLE
Shall we remove upcoming breaking changes warnings if we are not using that features?

### ISSUE THREAD

**Issue by frederikhors** [tailwindlabs/tailwindcss#2328]
I'm trying the 1.8.2 (amazing!).

But I have this annoying warning in console:

```console
risk - There are upcoming breaking changes: purgeLayersByDefault
risk - We highly recommend opting-in to these changes now to simplify upgrading Tailwind in the future.
risk - https://tailwindcss.com/docs/upcoming-changes
```

but I'm not using `purgeCSS` at all (I have my reasons not to).

Can you please disable these warnings if I'm not using these featues?

Thanks for your amazing really amazing work!

**Comment by adamwathan** [comment]
Hey @frederikhors! Best bet in this case is to just add `purgeLayersByDefault` to your config:

```js
// tailwind.config.js
module.exports = {
  future: {
    purgeLayersByDefault: true,
  },
  // ...
}
```

This will silence the warning and since you aren't using that feature it won't do anything anyways. When Tailwind 2.0 comes out and you upgrade to that, you'll be able to remove this from your config.

**Comment by frederikhors** [comment]
Thanks @adamwathan, your replies non-replies are great!

:smile:
