### ISSUE TITLE
Applying the `last` variant to `margin` breaks responsive classes

### ISSUE THREAD

**Issue by jonbellah** [tailwindlabs/tailwindcss#2330]
Apologies if this has already been reported... looked through the issues but didn't see anything similar.

### Describe the problem:

When applying the `last` variant to `margin` in `tailwind.config.js`, the responsive margin classes are no longer properly applied.

### Link to a minimal reproduction:

```
// tailwind.config.js
module.exports = {
    ...
    variants: {
        margin: ['last'],
    },
    ...
}
```

When this is added, `sm:mt-0` and `sm:ml-3` are no longer applied:
```
<div className="mt-3 rounded-md shadow sm:mt-0 sm:ml-3 sm:flex-shrink-0">
    <button className="w-full flex items-center justify-center px-5 py-3 border border-transparent text-base leading-6 font-medium rounded-md text-white bg-indigo-500 hover:bg-indigo-400 focus:outline-none focus:bg-indigo-400 transition duration-150 ease-in-out">
        Sign me up
    </button>
</div>
```

Before:
![Screen Shot 2020-09-05 at 11 52 42 AM](https://user-images.githubusercontent.com/2601219/92310729-559cc580-ef6e-11ea-889e-a143240ff5ad.png)

After:
![Screen Shot 2020-09-05 at 11 52 24 AM](https://user-images.githubusercontent.com/2601219/92310731-59304c80-ef6e-11ea-834f-4306419e79e8.png)

**Comment by adamwathan** [comment]
Hey! This is actually expected behavior, variants are not merged by default so in your config you are disabling the `responsive` variant by not relisting it:

```js
// tailwind.config.js
module.exports = {
    ...
    variants: {
        // Don't forget to include `responsive` here
        margin: ['responsive', 'last'],
    },
    ...
}
```

Tailwind 1.8 (released yesterday) introduced some new APIs that make this a little easier:

```js
// tailwind.config.js
module.exports = {
    ...
    variants: {
        // Adds `last` to the end of the default list
        margin: ({ after }) => after(['last']),
    },
    ...
}
```

Hope that helps!

**Comment by jonbellah** [comment]
Derp, Saturday morning coding. Missed it in the docs. Thanks!
