### ISSUE TITLE
ResolveConfig with experimental -> uniformColorPalette

### ISSUE THREAD

**Issue by frederikhors** [tailwindlabs/tailwindcss#2345]
I'm using this code in my `tailwind.config.js` ([because of this](https://github.com/tailwindlabs/tailwindcss/discussions/2338#discussioncomment-63704)):

```js
const resolveConfig = require('tailwindcss/resolveConfig')

module.exports = resolveConfig(
  {
    experimental: {
      uniformColorPalette: true
    }
  }
)
```

This is not working because new palette colors doesn't show up.

If I use `lodash/merge` it works.

**Comment by adamwathan** [comment]
Should be fixed now, grab v1.8.5 👍
