### ISSUE TITLE
Overriding a single shade not working with uniformColorPalette

### ISSUE THREAD

**Issue by florianbouvot** [tailwindlabs/tailwindcss#2352]
Hi tailwind team,

When I override a single color, `50` shade from `uniformColorPalette` are remove.

I'm working with lastest tailwind version 1.8.5 using the following config 

`tailwind.config.js`

```
const { colors } = require('tailwindcss/defaultTheme')

module.exports = {
  theme: {
    extend: {
      colors: {
        blue: {
          ...colors.blue,
          '900': '#2A3142'
        },
        yellow: {
          ...colors.yellow,
          '500': '#FCCF36'
        },
        gray: {
          ...colors.gray,
          '300': '#D7DADD'
        },
      },
    },
  },
  experimental: {
    uniformColorPalette: true,
  },
}
```

In this case `blue-50`, `yellow-50` and `gray-50` are remove but not from others colors.

Thanks, Florian.

**Comment by adamwathan** [comment]
Yeah this is because the uniformColorPalette stuff is not part of the `defaultTheme` file. Best bet for now (while this is still experimental) is to directly import the underlying file that powers it and use that instead:

```js
const { theme: { colors } } = require('tailwindcss/lib/flagged/uniformColorPalette')

module.exports = {
  theme: {
    extend: {
      colors: {
        blue: {
          ...colors.blue,
          '900': '#2A3142'
        },
        yellow: {
          ...colors.yellow,
          '500': '#FCCF36'
        },
        gray: {
          ...colors.gray,
          '300': '#D7DADD'
        },
      },
    },
  },
  experimental: {
    uniformColorPalette: true,
  },
}
```

**Comment by florianbouvot** [comment]
@adamwathan waouh, thank you for your reactivity.

_Recent experimental feature like `uniformColorPalette`, `extendedSpacingScale` make me think that tailwindui (the CSS part) can "merge" with tailwindcss v2. And maybe you can just share customize config for some components like (from and prose).
Seems convenient to me._

**Comment by adamwathan** [comment]
Yeah the goal is for Tailwind UI to just rely on Tailwind 2.0 defaults 👍  Tailwind UI is basically a testing ground for Tailwind 2.0! When we release it, we'll get rid of the Tailwind UI plugin.

**Comment by florianbouvot** [comment]
@adamwathan great 👍🏻
I recently remove tailwindui from my current projects and it's the right way 😄

**Comment by florianbouvot** [comment]
Using `const { theme: { colors } } = require('tailwindcss/lib/flagged/uniformColorPalette')` I've this error 'Tailwind CSS: Cannot read property 'colors' of undefined'.

**Comment by adamwathan** [comment]
Sorry, add `.default`:

```
const { theme: { colors } } = require('tailwindcss/lib/flagged/uniformColorPalette').default
```
