### ISSUE TITLE
Breaking change after updating to 1.8.x (from 1.7.5)

### ISSUE THREAD

**Issue by AlexanderOpran** [tailwindlabs/tailwindcss#2354]
We have an Angular 10 project in which we are using TailwindCSS and we are also using _resolveConfig._ After updating to 1.8 we are getting a critical breaking change error (Uncaught ReferenceError: global is not defined). We have narrowed this down to the usage of the _resolveConfig_ (if we do not use _resolveConfig_ everything works fine even on 1.8). The error itself seems to be somehow related to the postcss-selector-parser package.

We can do a temporary workaround using things like:

`(window as any).global = window;` 

in polyfills.ts but nevertheless, I do not think this should be an issue.

**Comment by benji014628** [comment]
You should check out v1.8.5 pretty sure it fixed that

**Comment by adamwathan** [comment]
Hey sorry to hear about this! Can you please provide a GitHub repo that reproduces the issue so we can more easily troubleshoot and diagnose the issue?

**Comment by AlexanderOpran** [comment]
Hey Adam,

Thanks for the quick response. I cannot exactly share the repository but a regular angular 10 cli project + tailwind will have the exact same issues after build. I will try and do that if need be.

One additional thing, this issue cannot be reproduced by running the project locally with the development webserver, it will only be an issue after the build (so perhaps test that using docker or a regular  webserver).

@benji014628, tried updating the package to the latest version (1.8.6), sadly we have the same issue.

![image](https://user-images.githubusercontent.com/16990110/92637728-e9a9bc80-f2e1-11ea-831f-58895d5167b5.png)

Caused by _postcss-selector-parser_ trying to call a node util (_deprecate_) and as such, _global.deprecate._

This is what is causign the issue (from postcss-selector-parser):

`var _require = require("util"),
    deprecate = _require.deprecate;

var WRAPPED_IN_QUOTES = /^('|")(.*)\1$/;
var warnOfDeprecatedValueAssignment = deprecate(function () {}, "Assigning an attribute a value containing characters that might need to be escaped is deprecated. " + "Call attribute.setValue() instead.");
var warnOfDeprecatedQuotedAssignment = deprecate(function () {}, "Assigning attr.quoted is deprecated and has no effect. Assign to attr.quoteMark instead.");
var warnOfDeprecatedConstructor = deprecate(function () {}, "Constructing an Attribute selector with a value without specifying quoteMark is deprecated. Note: The value should be unescaped now.");
`

**Comment by adamwathan** [comment]
Can you share a GitHub repository you create that reproduces the issue? It doesn't have to be your actual work project. Just _something_ so I don't have to set it up from scratch myself.

**Comment by AlexanderOpran** [comment]
Hey @adamwathan,

I created a repository and reproduced the issue. https://github.com/AlexanderOpran/angular-tailwind-debug

Just run `npm install` and `npm` start. If you downgrade to 1.7.5 the issue will go away. Same if you remove the `resolveConfig.`

Funnily enough, in the larger project I can only reproduce this issue after the build not on local but in that repo above the issues is also on local. Not sure why, but nevertheless, same issue.

Please let me know if I can help with anything else. 😸

**Comment by adamwathan** [comment]
Should be fixed in v1.8.8 👍
