### ISSUE TITLE
Purging seems not working anymore when custom classes are added?

### ISSUE THREAD

**Issue by gremo** [tailwindlabs/tailwindcss#2356]
### Describe the problem:

Seems that purging is not working anymore. I'm pretty sure it was working fine some time ago.

### Link to a minimal reproduction:

- Clone this repository https://github.com/gremo/webpack-boilerplate which includes Tailwind CSS with purge enabled
- Run `run npm install`
- Edit `src/style.css` add a new class `.foobarbaz { color: red }`
- Run `npm build`

**Expected result**: class `.foobarbaz` is missing in the output CSS file
**Actual result**: class `.foobarbaz` is present in the output CSS file, even if it's not in any files configured under the `purge `configuration.

EDIT: general purging is working, output file is as small as 4KB (instead of 1.7MB)... but still, custom class is present.

**Comment by adamwathan** [comment]
This is a change in v1.8 which results in a slightly larger bundle until you make a few tweaks. Now Tailwind will only purge custom CSS if you explicitly "bucket" it so Tailwind knows what category those styles belong to.

You'll want to just do this:

```css
@layer utilities {
  .foobarbaz { color: red }
}
```

Then the custom styles will be automatically purged whenever Tailwind is configured to purge the "utilities" layer (which is the default).

**Comment by gremo** [comment]
Oh so sorry not reading about the change in v1.8. Thanks!
