### ISSUE TITLE
"future" is not included in the simple config stub

### ISSUE THREAD

**Issue by dextermb** [tailwindlabs/tailwindcss#2370]
### Describe the problem:

Currently the `future` property is not included in the simple config stub but there are also currently two recommendations for enabling breaking changes early.

I'd like to open a PR to simply include the `future` property in the stub, but I wondered if there was a reason why it wasn't included to begin with.

**Comment by adamwathan** [comment]
No reason, just an oversight! Happy to accept a PR 👍🏻

**Comment by adamwathan** [comment]
Maybe even with the future flags in there by default but commented out, to make it even easier.
