### ISSUE TITLE
View rounded button on Google Chrome

### ISSUE THREAD

**Issue by tr0yka** [tailwindlabs/tailwindcss#2371]
Google Chrome v85.0.4183.102
Rounded button displayed with black outline
![3220514e35](https://user-images.githubusercontent.com/2771379/92953442-c82c0a80-f472-11ea-844c-e42fd8965852.jpg)

**Comment by adamwathan** [comment]
Hey! That's just the default focus state in Chrome for everything. Same for links, etc.

![image](https://user-images.githubusercontent.com/4323180/92954025-bb86c280-f430-11ea-9541-1cfa82e3c8ee.png)

**Comment by tr0yka** [comment]
Mb use `outline : none;` on buttons? Bad idea?
