### ISSUE TITLE
space-*-* overrides m-*

### ISSUE THREAD

**Issue by tomhughes-invento** [tailwindlabs/tailwindcss#2389]
### Describe the problem:

I'm not sure if this is by design (or if indeed there is any way around it), but I couldn't see anything listed in the docs that would suggest it is - space classes override the margin classes.

For example: If you apply `space-y-2` on a parent element, then `mt-4` on a child within that parent, the top margin is set as `0.5rem`, taken from the calc being ran on the space class.

Personally I think this should be the other way around, as setting a margin on an element is the more explicit request vs setting space on the parent.

### Link to a minimal reproduction:

https://stackblitz.com/edit/tailwindcss-alhxcw

**Comment by adamwathan** [comment]
Hey! This is just an issue of how specificity works in CSS I'm afraid and not an explicit design goal.

More discussion here:

https://github.com/tailwindlabs/tailwindcss/issues/1614
