### ISSUE TITLE
Button styling overzealous

### ISSUE THREAD

**Issue by tomhughes-invento** [tailwindlabs/tailwindcss#2408]
### Describe the problem:

Tailwind's default style normalizing applies the following snippet:

``[type=button], [type=reset], [type=submit], button {
    -webkit-appearance: button;
}``

This seems like it is being a bit overzealous, as it ends up applying to any element with those type (in our angular project we use type as a custom attribute on a component). If it is supposed to be applying to inputs with those type (which is the only other non-button use case I can think of that would use that attribute in regular HTML), can the selectors be updated to be more explicit, e.g. `input[type=button], input[type-reset], input[type=submit]`?

### Link to a minimal reproduction:

Just need the default tailwind build

**Comment by adamwathan** [comment]
This is part of normalize.css and the point of using just the attribute selector is to avoid increased specificity. If we used `input[type=button]`, you wouldn't be able to use utilities to override the styles.

One solution that is probably totally fine for your situation is to just override this style to use `appearance: none`:

```css
[type=button], [type=reset], [type=submit], button { -webkit-appearance: none; }
```

If this is raised by more people in the future we can definitely consider overriding it by default but for now I would do it in userland 👍🏻

**Comment by maddhruv** [comment]
Hey @adamwathan somehow for us, even setting `-webkit-appearance: none` doesn't help. `background-color: transparent` is still overriding our custom styles.

**Comment by JordanStuckings** [comment]
hey @adamwathan I'm also getting this in our production site but not when developing locally, i'm not sure why.

These are the styles overriding everything in my site:


```
[type=button], [type=reset], [type=submit], button {
    -webkit-appearance: button;
    background-color: transparent;
    background-image: none;
}
```
