### ISSUE TITLE
.first .last .odd and .even pseudo-class-variants not working

### ISSUE THREAD

**Issue by devinfd** [tailwindlabs/tailwindcss#2410]
### Describe the problem:

I will admit that I am new to tailwind so perhaps there is something that I am missing.

It seems that the .first .last .odd and .even pseudo-class-variants are not working or available anymore? Looking at my compiled (not using purgeCss) tailwind css file, none of the classes are there. Additionally, they don't appear to be in the CDN file as well. https://unpkg.com/tailwindcss@1.8.10/dist/tailwind.min.css

Were these variants removed intentionally? Should the docs be updated? https://tailwindcss.com/docs/pseudo-class-variants#first-child

Thanks!

**Comment by devinfd** [comment]
https://github.com/tailwindlabs/tailwindcss/issues/2412 may be related.

**Comment by adamwathan** [comment]
They all exist but they aren't enabled by default (never have been). To enable them you can follow the instructions in the documentation:

https://tailwindcss.com/docs/configuring-variants

You can see what's enabled by default here:

https://tailwindcss.com/docs/configuring-variants#default-variants-reference

**Comment by devinfd** [comment]
ah! Yes thanks.
