### ISSUE TITLE
.focus pseudo-class-variant not working with inset

### ISSUE THREAD

**Issue by stefanfrede** [tailwindlabs/tailwindcss#2412]
### Describe the problem:

After adding the focus variant to inset in `tailwind.config.js` no focus styles are generated.

### Link to a minimal reproduction:

https://codesandbox.io/s/tailwindcss-playground-wm6vi?file=/public/index.html

**Comment by adamwathan** [comment]
It works, the problem is you've deleted the `top-0` class by completely overriding the `inset` config. Make sure you use `extend` 👍 

```js
module.exports = {
  future: {
    purgeLayersByDefault: true,
    removeDeprecatedGapUtilities: true,
  },
  purge: ['./public/**/*.html'],
  theme: {
    extend: {
      inset: {
        '-20': '-5rem',
      },
    },
  },
  variants: {
    inset: ['responsive', 'focus'],
  },
  plugins: [],
};
```
