### ISSUE TITLE
Complex nested appy bugs

### ISSUE THREAD

**Issue by minimit** [tailwindlabs/tailwindcss#2423]
### Describe the problem:

Great work with apply, but there are still some inconsistencies with nested apply in css and utilities.
Seems that with `postcss-nested` apply doesn't compile nested values. I've done a minimal github repo with the wrong behaviour with nested **css** apply (nested rules are compiled without nested selectors, and with @media in the wrong position) and with nested **utilities** apply (nested rules are not compiled). There are also `!important` missing on nested appy.

This is the output:

```
.css {
  position: initial;
}

.css > .css-inner {
  display: inline-block;
  display: block !important;
}

.final-css {
  @media (min-width: 768px) {
    position: initial;

    display: inline-block;

    display: block !important;
  }
}

@media (min-width: 768px) {
  .final-plugin {
    position: initial !important;
  }
}
```

Should be:

```
.css {
  position: initial;
}

.css > .css-inner {
  display: inline-block;
  display: block !important;
}

@media (min-width: 768px) {
  .final-css {
    position: initial !important;
  }

  .final-css > .css-inner {
    display: inline-block !important
    display: block !important;
  }
}


@media (min-width: 768px) {
  .final-plugin {
    position: initial !important;
  }

  .final-plugin > .plugin-inner {
    display: inline-block !important
    display: block !important;
  }
}
```

### Link to a minimal reproduction:

https://github.com/minimit/twbug-apply-complex

**Comment by adamwathan** [comment]
Thanks for the report! The nesting issue should be resolved by moving `postcss-nested` _after_ Tailwind in your `postcss.config.js`:

```js
module.exports = {
  plugins: {
    tailwindcss: {},
    'postcss-nested': {},
  },
}
```

It _should_ be solvable using the `bubble` option to make `@screen` rules bubble but there's a long-standing bug in `postcss-nested` currently that stops it from working: https://github.com/postcss/postcss-nested/issues/81

The other issues you're seeing are likely just complex edge cases we haven't had a chance to iron out. Will keep this open until we can fix them.

Ideally, you could provide us with a clear minimal input and expected output that we could use for a test so we can easily see what the real edge case is 🙏  Right now there's a lot of stuff going on and it'll take a long time for us to troubleshoot the real issue, which means we need to set aside significant time to look at it. Based on our current schedule that would likely be sometime in late October/early November, but if you can reduce the reproduction down to something very small then we can fix it faster. Thanks!

**Comment by minimit** [comment]
Thank you, I'm not sure what the real edge case is, I've done a "minimal reproduction" right here but it seems they are different nested bugs and **postcss-nested** is involved.

I've encountered this complex apply rules on some edge cases (disabling nested components styles with an apply) when porting my UI framework to use tailwind.

I've no hurry, it's more than enough that you'll look into it since it's scoping out what tailwind uses `@apply` for (no nested rule).

**Comment by robksawyer** [comment]
I've also had some problems with postcss-nested. Downgrading to ```"postcss-nested": "5.0.1",``` worked for me.

**Comment by strlns** [comment]
For me the easiest workaround was to switch to postcss-nesting, include that after tailwindcss and add the "missing" & in all my nested selectors.
That was before reading that downgrading to postcss-nested 5.0.1 would have prevented the problem.

I had trouble with #2152 when including postcss-nested 5.0.3 after tailwindcss. 
Putting postcss-nested before tailwindcss then triggered https://github.com/postcss/postcss-nested/issues/81.

So this change is probably related?
https://github.com/postcss/postcss-nested/issues/101#issuecomment-737639539

**Comment by minimit** [comment]
Updated demo with `yarn upgrade --latest` the situation changed. https://github.com/minimit/twbug-apply-complex

Applying nested css rule now works propery.
But applying nested tailwind plugins output is wrong, and it's different if you use `@screen` or `@apply md:`.

See output here https://github.com/minimit/twbug-apply-complex/blob/master/out.css

@adamwathan maybe they fixed the nested bug in postcss-nested and it's time to fix tailwind apply?

**Comment by Calvert0210** [comment]
Thanks for the post-it helps me

**Comment by minimit** [comment]
@adamwathan great work with jit I totally love it.

I've updated the demo with jit and tailwindcss 2.2.0

Seems almost perfect, I removed an apply of css since it's no longer possible. And the apply of variant and screens of tailwind utils works fine.

But there's a bug when applying a plugin with a variant.

```
.final-plugin {
  @apply md:plugin !important;
}
```

While this works fine.

```
.final-plugin-screen {
  @screen md {
    @apply plugin !important;
  }
}
```

See the demo for the output.

**Comment by adamwathan** [comment]
Hey! I looked at the out.css file and aside from some superficial formatting/indentation stuff it looks correct to me — all the CSS rules are exactly what you have in the "should be" comments. Can you be a bit more specific so I know exactly what you mean? Totally possibly I missed something, it's 6am 😄

**Comment by minimit** [comment]
> Hey! I looked at the out.css file and aside from some superficial formatting/indentation stuff it looks correct to me — all the CSS rules are exactly what you have in the "should be" comments. Can you be a bit more specific so I know exactly what you mean? Totally possibly I missed something, it's 6am 😄

With apply variants seems the class `final-plugin` is `plugin` on nested selectors.

```
@media (min-width: 768px) {
  .final-plugin {
    position: initial !important;
  }
  .plugin > .final-plugin-inner {
    display: inline-block !important;
  }
  .plugin > .final-plugin-inner {
    display: block !important;
  }
}

/* SHOULD BE
@media (min-width: 768px) {
  .final-plugin {
    position: initial !important;
  }

  .final-plugin > .plugin-inner {
    display: inline-block !important
    display: block !important;
  }
}
*/

```

**Comment by adamwathan** [comment]
No plans to dig into this further at this point, instead I recommend using our new nesting plugin which guarantees the CSS is unnested properly before any "apply" statements are processed and will avoid any issues 👍🏻

https://tailwindcss.com/docs/using-with-preprocessors#nesting
