### ISSUE TITLE
Failed to set up Tailwind in Angular 9 and 10 - TypeError: Cannot read property 'charCodeAt' of undefined in postcss

### ISSUE THREAD

**Issue by paranerd** [tailwindlabs/tailwindcss#2426]
### Describe the problem:
I'm trying to use Tailwind in my Angular 10 project which failes with the following errors:

```
Unknown error from PostCSS plugin. Your current PostCSS version is 7.0.27, but postcss-functions uses 6.0.23. Perhaps this is the source of the error below.
```

```
ERROR in ./src/styles.scss (./node_modules/@angular-builders/custom-webpack/node_modules/css-loader/dist/cjs.js??ref--13-1!./node_modules/@angular-builders/custom-webpack/node_modules/postcss-loader/src??embedded!./node_modules/resolve-url-loader??ref--13-3!./node_modules/@angular-builders/custom-webpack/node_modules/sass-loader/dist/cjs.js??ref--13-4!./node_modules/postcss-loader/dist/cjs.js??ref--17!./src/styles.scss)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read property 'charCodeAt' of undefined
```

#### Here are the steps I took:
```
ng new tailwind-app
```

```
npm i tailwindcss postcss-import postcss-loader postcss-scss @angular-builders/custom-webpack -D
```

Added those at the beginning of styles.scss:
```
@import 'tailwindcss/base';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';
```

Created this webpack.config.js in the root of my project:
```
module.exports = {
  module: {
    rules: [
      {
        test: /\.scss$/,
        loader: "postcss-loader",
        options: {
          postcssOptions: {
            ident: "postcss",
            syntax: "postcss-scss",
            plugins: [
              require("postcss-import"),
              require("tailwindcss"),
              require("autoprefixer"),
            ],
          },
        },
      },
    ],
  },
};
```

Used those to update my angular.json:
```
ng config projects.tailwind-app.architect.build.builder @angular-builders/custom-webpack:browser
ng config projects.tailwind-app.architect.build.options.customWebpackConfig.path webpack.config.js
ng config projects.tailwind-app.architect.serve.builder @angular-builders/custom-webpack:dev-server
ng config projects.tailwind-app.architect.serve.options.customWebpackConfig.path webpack.config.js
```

Then serve the app using:
```
ng serve
```

The error exists with Angular 9.1.12 (LTS) as well as 10.1.2.

**Comment by BogdanDarius** [comment]
There is a problem with postcss 8.0.7. Downgrade to postcss 8.0.6.
https://github.com/postcss/postcss/issues/1419

**Comment by paranerd** [comment]
I never actually installed postcss - it just came as a dependency with the highest version of 7.0.32

**Comment by zenhuw** [comment]
found this issue as well, same reproduction step

**Comment by paranerd** [comment]
Fixed it:
```
npm i -D postcss-scss@2.1.1
```

Version 3.0.0 of postcss-scss seems to break things.

I would highly appreciate you putting up some guide on how to implement Tailwind with Angular. There's a bunch of tutorials on the web - half of them outdated/wrong.

Keep up the great work!

**Comment by adamwathan** [comment]
Glad you got it sorted out! I'd love to put together a guide on integrating Tailwind with Angular but have never actually used Angular so don't know where to start. If anyone wants to share an example repo that they think is the best possible setup (given how Angular doesn't allow you to customize the PostCSS config if I'm not mistaken), I'd love to use it as a starting point to come up with something we can endorse.

**Comment by nartc** [comment]
@adamwathan https://medium.com/@jacobneterer/angular-and-tailwindcss-2388fb6e0bab this is one of the most up-to-date article about tailwind + angular.

**Comment by paranerd** [comment]
@nartc And even that one is outdated and wrong. For example the postcss-loader does not have an "options" parameter, it's "postcssOptions". And that's just one.
@adamwathan I'd be happy to support you in setting up the guide!

**Comment by cssberries** [comment]
> "I'd be happy to support you in setting up the guide!"

@paranerd, it would be great!

**Comment by cssberries** [comment]
By the way, it seems that instead of:
`plugins: () => [
							require('postcss-import'),
							require('tailwindcss'),
],`

it should be: 
`plugins: [
							require('postcss-import'),
							require('tailwindcss'),
						],`

**Comment by paranerd** [comment]
@cssberries How would you like me to set up the guide?

**Comment by cssberries** [comment]
@paranerd I think it could be similar to what was [mentioned ](https://medium.com/@jacobneterer/angular-and-tailwindcss-2388fb6e0bab)above but up to date and right.

**Comment by simonswiss** [comment]
Hey - moving this to GitHub discussions to keep the conversation going 👍
