### ISSUE TITLE
Define PostCSS compatibility with peerDependencies?

### ISSUE THREAD

**Issue by callumlocke** [tailwindlabs/tailwindcss#2440]
I've got here after a very long day of debugging a problem which turned out to be as follows: I was using a different version of PostCSS than the one used by TailwindCSS. This led to confusing error messages about something being undefined. Eventually I tried downgrading my PostCSS dep to the same one used by tailwindcss, and it fixed it.

Can you please specify your peerDependencies to prevent this happening again?

**Comment by adamwathan** [comment]
This is all supposed to "just work" (PostCSS 8 is supposed to be backwards compatible with PostCSS 7 plugins) but there are currently bugs in PostCSS 8 that make it incompatible with Tailwind. They are working on it.

**Comment by callumlocke** [comment]
I see. but if Tailwind depends on a specific version of PostCSS and it fails (in a confusing way) if you try to use it alongside another version of PostCSS, and this situation will remain until PostCSS manages to fix issues on their side, I think it would make sense to either add a peer dep or document it somewhere.

**Comment by adamwathan** [comment]
It's already fixed :)

https://github.com/postcss/postcss/commit/ce29228e3fdc8978a69ad8d4a9f75df00bd8ac3d

**Comment by adamwathan** [comment]
PostCSS v8.0.9 fixes the issue and will be available to install any minute, it's already tagged on GitHub here:

https://github.com/postcss/postcss/releases/tag/8.0.9

**Comment by adamwathan** [comment]
Released now and just tested everything locally and everything is working 👍  With any luck this is the end of any PostCSS 8 compatibility issues 🤞
