### ISSUE TITLE
Custom color not applied

### ISSUE THREAD

**Issue by SalvesTestservices** [tailwindlabs/tailwindcss#2447]
### Describe the problem:

I have added a custom color to `tailwind.config.js` like this:

```
module.exports = {
  future: {
    // removeDeprecatedGapUtilities: true,
    // purgeLayersByDefault: true,
  },
  purge: ['./app/**/*.html.erb', './app/**/*.rb'],
  theme: {
    extend: {
      colors: {
        'mycolor': '#7fff00',
      }
    }
  },
  variants: {},
  plugins: [require('@tailwindcss/ui'), require('@tailwindcss/typography')],
}
```
And it is used in the code like this:

```
  <div class="bg-mycolor text-white">my text</div>
  <div class="bg-white text-mycolor">my text</div>
```
The color is not applied to both the background color and the text color.

### Link to a minimal reproduction:

https://tailwind.run/G1m8yD

**Comment by asifm** [comment]
It works after you remove `require('@tailwindcss/typography')` from the config's plugins array.  It can't find that plugin, as you can see in the error message at the bottom of the page.

See fork [here](https://tailwind.run/5rkFfh).

**Comment by SalvesTestservices** [comment]
Removing the typography plugin did solve it, thanks.
