### ISSUE TITLE
'applyComplexClasses' does not support 'active' pseudo class

### ISSUE THREAD

**Issue by 8** [tailwindlabs/tailwindcss#2454]
### Describe the problem:

I watched your great youtube videos from (https://blog.tailwindcss.com/whats-new-in-tailwindcss-on-youtube) and had to try out the new `applyComplexClasses` switch. I tried to move my split up @apply code from from multiple declarations to one, but got an error when trying to add the 'active:' pseudo class.

Using
```
experimental: {
    applyComplexClasses: true,
  },
```
doesn't work with `active:` pseudo class.

### Link to a minimal reproduction:

1. Add the following to your tailwind.css:

```
.btn {
  @apply active:bg-green-500;
}
```

2. Observe the following error being displayed in the browser:
```
(8:10) The `active:bg-green-500` class does not exist. If you're sure that `active:bg-green-500` exists, make sure that any `@import` statements are being properly processed before Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

   6 | 
   7 | .btn {
>  8 |   @apply active:bg-green-500;
     |          ^
   9 | }
  10 | 
```

3. Change "active" to "focus"

```
.btn {
  @apply focus:bg-green-500;
}
```

4. And notice that everything works fine.

This leads me to believe that the 'active' pseudo class is not supported with applyComplexClasses.

I apologize in advance if I missed anything obvious.

Take care,
Martin

**Comment by adamwathan** [comment]
Hey Martin! Did you make sure to enable the active variant in your config? That class doesn’t exist by default so the error could be correct if you haven’t enabled that variant.

**Comment by 8** [comment]
Hi Adam,
thank you - you are of course totally right.
My bad, sorry for wasting your time, time to go to bed.
Wanted to mention that I enjoyed your new youtube channel a lot!

Thanks again & take care,
Martin

**Comment by adamwathan** [comment]
Hey no problem at all, glad it’s working now!

**Comment by simonswiss** [comment]
Thanks for the kind words on the new YouTube channel, @8 🙌
