### ISSUE TITLE
border-color not be applied

### ISSUE THREAD

**Issue by jasonericdavis** [tailwindlabs/tailwindcss#2461]
### Describe the problem:

The border-color rule is not being applied according to the documentation at: 
https://tailwindcss.com/docs/border-color

### Link to a minimal reproduction:

https://github.com/jasonericdavis/tailwindcss-border-color-issue

**Comment by afoures** [comment]
There is a typo in your `border-color` class, you used `border-color-red-200` instead of `border-red-200` as in the documentation.

**Comment by jasonericdavis** [comment]
Thank you for pointing out my spelling mistake. The root of the problem that I was seeing was an error in my tailwind.config.js file. I had my colors defined under theme instead of under theme -> extend. 
Thank you agin for your help.
