### ISSUE TITLE
[1.8.10 / macOS] The problem with emoji

### ISSUE THREAD

**Issue by afuno** [tailwindlabs/tailwindcss#2499]
This problem is only on macOS. If you are using another OS, then everything that is written below is not valid for you.

---

I have been observing this problem for a long time. But somehow there was not enough time to understand it in more detail. But now I think I understand where it comes from. And I hope for a joint solution to this problem.

I specifically checked everything on the current version of your site.

First, go to the main page (it is [here](https://tailwindcss.com)) and edit the title. You need to replace the text "123" with this smiley — ⚠️. The result is this:

<img width="300" alt="Снимок экрана 2020-10-05 в 17 03 01" src="https://user-images.githubusercontent.com/2853419/95089627-07c1db80-072d-11eb-98d5-dc6134bb4210.png">

At that stage, I will clarify - the problem is not with all emoticons:

<img width="300" alt="Снимок экрана 2020-10-05 в 17 07 02" src="https://user-images.githubusercontent.com/2853419/95089789-35a72000-072d-11eb-8f8d-617a55c49c4b.png">

The TailwindCSS site currently uses this font set:

```
Inter var,system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji
```

If turn off all these fonts, then the problem smiley will start working.

I'm having this problem in Chrome. Safari is fine.

In my example, I inserted the smiley manually. If I paste this emoticon in the Atom editor, nothing helps.

All other smilies work fine. There are no problems with them. There may be some other problematic smilies, but I haven't found them yet.

Demo:

![111111](https://user-images.githubusercontent.com/2853419/95094045-21195680-0732-11eb-83b4-f8860889aec3.gif)

Sorry for the quality. GitHub has a size limit for images.

**Comment by afuno** [comment]
It's funny. GitHub (presumably Primer or Bootstrap) has this problem too:

![22222](https://user-images.githubusercontent.com/2853419/95093844-e44d5f80-0731-11eb-89ed-c779d6b451ef.gif)

**Comment by adamwathan** [comment]
Interesting discovery! From my testing it appears to be the result of including `system-ui` in the font stack.

Pinging @argyleink in case he's seen this before — ever noticed including `system-ui` to break certain emoji?

Renders emoji correctly:

```
font-family: Inter var;
```

Doesn't render as expected:

```
font-family: Inter var, system-ui;
```

**Comment by argyleink** [comment]
I have hunches, thx for bringing me in! 

I think my Android has the same issue?? I don't see a smiley in the comment, I see the problem emoji. I'm in the native GitHub app..

![Screenshot_20201006-063207.png](https://user-images.githubusercontent.com/1134620/95208475-febd2280-079d-11eb-9082-883772de7c3b.png)

Will check back soon when at my desk 🤘💀

**Comment by argyleink** [comment]
Here's some of my research and clues, as well as where I'm investigating next:

<details>

<summary>Inter font, proper emoji, computed/rendered font screenshot:</summary>

<img width="247" alt="Screen Shot 2020-10-06 at 8 59 36 AM" src="https://user-images.githubusercontent.com/1134620/95227143-9b89bb00-07b2-11eb-9db8-e833d24d09ed.png">

</details>

<details>

<summary>system-ui font, wrong emoji, computed/rendered font screenshot:</summary>

<img width="247" alt="Screen Shot 2020-10-06 at 8 59 36 AM" src="https://user-images.githubusercontent.com/1134620/95227295-cbd15980-07b2-11eb-81f8-5a8208e702d0.png">

</details>

<details>

<summary>system-ui font, different emoji, computed/rendered font screenshot:</summary>

<img width="247" alt="Screen Shot 2020-10-06 at 8 59 36 AM" src="https://user-images.githubusercontent.com/1134620/95227624-2d91c380-07b3-11eb-90a1-63c6b5f7002c.png">

</details>

From what I can tell, this looks like a Chromium issue where the system-ui character resolution isn't properly "discovering" this ⚠️ emoji and swapping it for the proper `Apple Color Emoji` font. I don't think it's a font issue, it's an emoji resolution issue. 

`Inter var` doesnt have emojis, so it moves on to system-ui as the fallback, and system-ui font logic is gobbling up that emoji and not letting it get wrapped proper. Moving this up to proper engineers on Chromium, will return with more information!

**Comment by afuno** [comment]
I just wanted to add one more smile to the issue - ☹️
I insert it into the layout in Atom, and as a result this:

<img width="89" alt="Снимок экрана 2020-10-06 в 19 18 50" src="https://user-images.githubusercontent.com/2853419/95229043-c6066300-0808-11eb-8bcd-83fdef36b0a3.png">

**Comment by argyleink** [comment]
2 things here:
1. system-ui has emoji included, they're the flat single color ones we see in this bug. it's "claiming" the emoji instead of letting it "fallback" to the colorful apple emoji font (which is what happens when Inter var, etc do since they dont claim/include any emoji)
2. we dont strictly adhere to variation selectors on the emoji, if we did we might be able to sneak by the system font so it uses the colorful apple emoji one. 

There's a bug here https://bugs.chromium.org/p/chromium/issues/detail?id=964527 and one here https://bugs.chromium.org/p/chromium/issues/detail?id=1033453 that talk about the above 2 things.

Can confirm that Safari is doing special things to make sure the better emoji is used. 
Can also confirm this is on the radar of our typography team.  It does sound like one day this bug will be gone tho, and the higher quality emojis will be chosen by Chromium 👍 

If I was you, I'd put my emoji inside a `<code class="🙂">` with `.🙂 { font-family: sans-serif; }` or something. I like starting with inline emoji, but do find I end up wrapping them for more control, like in a chat app or feature in a header.

**Comment by afuno** [comment]
@argyleink Thank you for your detailed answer. And thank you for the suggested option. `font-family: sans-serif;` really saves the day.

**Comment by adamwathan** [comment]
Legend, thanks man! Going to close as "not a Tailwind bug" 👍🏻
