### ISSUE TITLE
tailwind sass imports - invalid tailwind directive?

### ISSUE THREAD

**Issue by sebszocinski** [tailwindlabs/tailwindcss#2503]
Not a bug really, as it doesn't break tailwind but my VSCode editor keeps saying my tailwind.sass file has errors (lights up the file in red) and shows this:

![image](https://user-images.githubusercontent.com/5466694/95137159-0802bb00-07af-11eb-9967-b73d0da7b4e2.png)

Does anyone know how to fix this or tell VSCode to ignore it as it doesn't seem to break anything.

**Comment by mintymatt** [comment]
I don't use VSCode myself, but this looks like it could be a highlighting issue, have you tried adding `;` at the end of each import?

**Comment by adamwathan** [comment]
Most syntax linters won't recognize the custom Tailwind stuff. Only option is to disable that sort of linting in your editor, or switch to the PostCSS language mode if you can (probably not a good idea for Sass though).

Unfortunately nothing we can do about this from within Tailwind itself so going to close. Someone could write a Sass language extensions for VS Code that was more forgiving or understood Tailwind's custom at rules though.

**Comment by memark** [comment]
There is a good VS code extension that solves this
https://marketplace.visualstudio.com/items?itemName=csstools.postcss
