### ISSUE TITLE
GitHub Actions test matrix includes Node 8 which is end-of-life

### ISSUE THREAD

**Issue by HonkingGoose** [tailwindlabs/tailwindcss#2521]
### Describe the problem:

Node 8 is end-of-life, according to the [Node.js release page](https://nodejs.org/en/about/releases/).
However the test matrix runs tests for Node 8.
Maybe we can drop the Node 8 tests?

I have not found a support matrix on the TailwindCSS website, so I don't know what your support strategy is with regards to the Node versions you'll support. Are you planning on supporting users who use Node 8 and run into issues?

If you want I'll make a pull request to remove Node 8 from the GitHub Actions test matrix.

### Link to a minimal reproduction:

Node 8 is in the test matrix:
https://github.com/tailwindlabs/tailwindcss/blob/427299ec0943d340b027dbd770c81cbb43304c5b/.github/workflows/nodejs.yml#L16-L18

GitHub Actions runs a build for Node 8 on a recent pull request:
https://github.com/tailwindlabs/tailwindcss/runs/1226581885?check_suite_focus=true

**Comment by adamwathan** [comment]
We have to support Node 8 until Tailwind 2.0 but will be dropping it then. Removing it before then would be a breaking change unfortunately. Thankfully Tailwind 2.0 will be out next month, and we'll likely only support Node 12+ going forward.
