### ISSUE TITLE
Logging "experimental feature" warnings to stderr causing failed builds in snowpack

### ISSUE THREAD

**Issue by fubhy** [tailwindlabs/tailwindcss#2522]
This change (https://github.com/tailwindlabs/tailwindcss/pull/2205) causes a regression in snowpack now where output into `stderr` is considered a failure of the build plugin. Thus, snowpack renders a big fat error message instead of the app whenever we are trying to use experimental features.

https://github.com/pikapkg/snowpack/blob/master/plugins/plugin-build-script/plugin.js#L33-L35

Now in my opinion both tailwind and snowpack are equally "responsible" for this. I don't think it's right to write to "info" level notifications like this to stderr, on the other hand, snowpack shouldn't assume stderr output is a critical failure. They should really just look at the exit code of the underlying script for that. I am going to open a PR in the snowpack repository but just wanted to let y'all now and document this problem in case someone else runs into it.

Note: This problem arose for us when we were trying to use the new dark mode experimental feature in snowpack through a snowpack build script: 

```
Build Error: build:postcss
Error: 
warn - You have enabled experimental features: darkModeVariant
warn - Experimental features are not covered by semver, may introduce breaking changes, and can change at any time.
```

./cc @adamwathan in case you want to re-consider this change also for tailwind?

**Comment by fubhy** [comment]
Note that `console.warn` (which is used here) is simply an alias to `console.error` and i'd argue that the warning message here is not equivalent to an error (arguably, the naming of console.warn is wrong considering that it's technically just an alias for console.error but that's a whole different discussion, lol). Anyways... imho, stdout is a better place for this :-)

**Comment by fubhy** [comment]
Pull request for snowpack: https://github.com/pikapkg/snowpack/pull/1255

**Comment by FredKSchott** [comment]
@fubhy thanks for the Snowpack PR! Just merged

**Comment by adamwathan** [comment]
@fubhy Any good ideas on how we can log things to the console but avoid them being included in piped output without used `stderr`? 🤔

**Comment by FredKSchott** [comment]
For stdin->stdout workflows, you really want `stdout` to just be the result of the CLI. Anything that ends up in stdout ends up mixing with the "result" of the CLI itself, which would break the result. stderr is unfortunately the only alternative that I'm aware of.

**Comment by fubhy** [comment]
Yeah if the concern is that the output is used in cli scripts (sorry, I didn't realize that that was the reason why this was done) then stderr is probably the only way 😶

**Comment by fubhy** [comment]
I guess this could be closed then as there is nothing actionable left for tailwind as far as the original problem is concerned. Sorry for the noise 🤫
