### ISSUE TITLE
Support for closure colors in fill and stroke utilities

### ISSUE THREAD

**Issue by JeffSchofield** [tailwindlabs/tailwindcss#2535]
### Describe the problem:

The `fill` and `stroke` utilities do not currently support closure colors. This can cause an error if you're using the theme function to destructure the entire color configuration.

I believe the color functions are only called by the `withAlphaVariable` utility and since we don't yet have `fill-opacity-` or `stroke-opacity-` utils the color function doesn't get a chance to be called.

https://github.com/tailwindlabs/tailwindcss/blob/0feb064054b6566589e0e5b1a4d469976606be70/src/util/withAlphaVariable.js#L22

### Link to a minimal reproduction:

Currently throws an error: https://play.tailwindcss.com/KpLmGtRf8t?file=config

Destructuring in the entire color config will throw the same error if there are any closure colors:  https://play.tailwindcss.com/pNL2hSFBbc?file=config

**Comment by adamwathan** [comment]
Should be fixed in v1.8.13, will have to update the playground next week 👍🏻

**Comment by saintplaybitorical** [comment]
Hi! is there a reason why fillOpacity or strokeOpacity don't exists?

**Comment by homerjam** [comment]
> Hi! is there a reason why fillOpacity or strokeOpacity don't exists?

Same question here 🤔
