### ISSUE TITLE
Does not creating opacity classes for dark mode

### ISSUE THREAD

**Issue by vpcvdc** [tailwindlabs/tailwindcss#2540]
### Describe the problem:
tailwindcss[v1.8.12] does not creating opacity classes for dark mode

### Link to a minimal reproduction:
tailwind.config.js
```js
'use strict';

module.exports = {
  dark: 'class',
  experimental: 'all',
  future: {
    purgeLayersByDefault: true,
    removeDeprecatedGapUtilities: true,
  },
  purge: [
    './public/**/*.html',
    './src/**/*.js',
  ],
  theme: {
    extend: {},
  },
  variants: {},
  plugins: [],
};
```
one example., (dark:border-opacity-25, dark:hover:opacity-75) classes are not creating...

**Comment by adamwathan** [comment]
You'll need to enable the `dark` variant for those utilities, they aren't enabled by default.

Here's a playground that shows how to enable them:

https://play.tailwindcss.com/D8c47pT0ZL?file=config
