### ISSUE TITLE
All functions are missing from config file

### ISSUE THREAD

**Issue by GHNewbiee** [tailwindlabs/tailwindcss#2556]
### Describe the problem
*tailwindcss: 1.9.1*

After running
```shell
$ npx tailwindcss init --full
```
the produced `tailwind.config.js` file does not include any more functions such as:
```js
 width: theme => ({...})
```
Do I miss something?

**Comment by adamwathan** [comment]
Yep this is a bug, sorry about this! Going to fix.

**Comment by adamwathan** [comment]
This should be fixed in v1.9.3, thank you for reporting!
