### ISSUE TITLE
CorePlugins Outline disabled failed

### ISSUE THREAD

**Issue by jahnli** [tailwindlabs/tailwindcss#2565]
I don't need to use Outline in my project, so I want to disable it as if it's not ineffective

![image](https://user-images.githubusercontent.com/20943608/96101133-b7eecb80-0f07-11eb-8011-b3982976a517.png)

![image](https://user-images.githubusercontent.com/20943608/96101031-9a216680-0f07-11eb-9879-e04e8906c390.png)

**Comment by adamwathan** [comment]
That's how you disable all of Tailwind's `outline` utilities, not how you actually remove outlines from your design.

You want to keep `outline` _enabled_, then use the `focus:outline-none` class on elements where you want to hide the focus ring.

**Comment by aliwa** [comment]
how we should do to remove focus-within and focus variants from outline utilities ?
