### ISSUE TITLE
2.0.0-alpha.1 can't build with @tailwindcss/ui plugin

### ISSUE THREAD

**Issue by robbevp** [tailwindlabs/tailwindcss#2636]
### Describe the problem:

Wanted to try out the new alpha in my project, build the build failed immediately.
I've narrowed it down to the inclusion of the @tailwindcss/ui plugin. (I have not tried any other plugins)

### Link to a minimal reproduction:

I've set up a repo that is as simple as possible: https://github.com/robbevp/tailwindcss2-alpha/tree/main

If I run the build command I get the error in the readme.
If I leave out the ui plugin the build will succeed, if I downgrade tailwindcss to 1.9.5 the build will succeed

Edit: I realise that this can be an issue on the side of the plugin and that there might be some changes necessary there to work with 2.0. But since the release description didn't mention any (breaking) changes for plugins, I decided to create an issue

**Comment by surjithctly** [comment]
While you are here, can you check whether the 2.0.0 raw output has "indigo" colors? 

I can't even find it here: https://unpkg.com/tailwindcss@2.0.0-alpha.1/dist/tailwind.min.css

Just wanted to make sure its not only for me :)

**Comment by adamwathan** [comment]
@surjithctly Tailwind 2.0 doesn't include indigo by default, please refer to the default config to find the answers to these questions:

https://github.com/tailwindlabs/tailwindcss/blob/master/stubs/defaultConfig.stub.js

**Comment by adamwathan** [comment]
@robbertkl Yeah we haven't updated any of our plugins for 2.0 yet, working on it today. Tailwind UI is not going to be officially compatible until we actually release 2.0 either way though as we need to make some updates there, for example we are planning to change the primary color to violet instead of indigo so it uses something that's included in the default Tailwind 2.0 color palette.

**Comment by surjithctly** [comment]
@adamwathan Oh i see. I did not see it mentioned it anywhere. Any particular reason? because this might be a breaking change for folks upgrading. 

Because of that `@apply bg-indigo-600;`  is also not working with 2.0.0. I'm not sure if an extra setting is needed or not. 

```js
const { colors } = require("tailwindcss/defaultTheme");

module.exports = {
...
 extend: {
      colors: {
        indigo: {
          ...colors.indigo,
        },
      },
    },
...
```

**Comment by surjithctly** [comment]
Okay, As per the `defaultConfig.stub.js`, the following works.

```js
const colors = require("tailwindcss/colors");
module.exports = {
...
 extend: {
      colors: {
        indigo: colors.indigo,
      },
    },
...
```

**Comment by brandonpittman** [comment]
> Thanks for clarifying @adamwathan
> I'll close this issue

It's still an issue.
