### ISSUE TITLE
New tailwind default fonts override tailwind config

### ISSUE THREAD

**Issue by benji014628** [tailwindlabs/tailwindcss#2640]
### Describe the problem:

I know about the new 'DEFAULT' setting and I'm having trouble figuring out why the new default fonts show in the 'html' element and my custom font using the defaultTheme show in the 'body' element but they're overwritten.

### Link to a minimal reproduction:

https://github.com/benji014628/portfolio/tree/jakelamb-tailwindv2-alpha
![Screen Shot 2020-10-21 at 11 33 58 AM](https://user-images.githubusercontent.com/44789941/96767414-5c05c600-1391-11eb-8cd2-d16a5ab3f8e8.png)

**Comment by danbeneventano** [comment]
Having this issue as well
