### ISSUE TITLE
2.0.0 alpha1 - does this mean anything to you? I'm using Hugo

### ISSUE THREAD

**Issue by jensamunch** [tailwindlabs/tailwindcss#2650]
![image](https://user-images.githubusercontent.com/1650140/96911576-ed139480-1498-11eb-922a-32047e54ba4c.png)

![image](https://user-images.githubusercontent.com/1650140/96911903-67441900-1499-11eb-9c97-40f4a670b831.png)

**Comment by jensamunch** [comment]
i guess its because im using tailwind/ui

https://github.com/tailwindlabs/tailwindcss/issues/2636

**Comment by adamwathan** [comment]
Correct, we are working on updating those plugins to be 2.0 compatible already:

https://github.com/tailwindlabs/tailwindcss-custom-forms/commit/bfe21f1094dda5918bb4bba656f62dd94f5d91f7

If you need to use plugins I would recommend staying on Tailwind 1.9, 2.0 is still very alpha with lots of known little issues like this that we are working out.
