### ISSUE TITLE
custom-forms causing error with v2 alpha

### ISSUE THREAD

**Issue by brandonpittman** [tailwindlabs/tailwindcss#2654]
### Describe the problem:

Include the custom forms plugin, watch the build fail.

```
tailwindcss 2.0.0-alpha.1

   🚀 Building: src/tailwind.css

   🚫 TypeError: value.charCodeAt is not a function
```

### Link to a minimal reproduction:

```js
const forms = require("@tailwindcss/custom-forms");
module.exports = {
  plugins: [forms],
};
```

I'm sure the response will be the same as it was in regards to #2636 , but I figured I'd file this issue anyways. I'm sure lots of people use the forms plugin, and would not assume it to create a failure that stops them from using v2.

**Comment by adamwathan** [comment]
Yep this is already being solved over on that repo, the plugin needs to be updated:

https://github.com/tailwindlabs/tailwindcss-custom-forms/commit/bfe21f1094dda5918bb4bba656f62dd94f5d91f7

We'll tag a release for it probably next week. In the mean time just keep using the latest stable version of Tailwind.

**Comment by vesper8** [comment]
@adamwathan I just upgraded to Tailwind 2 and I noticed that my radio inputs that are styled with `"@tailwindcss/custom-forms"` no longer show an outline (thin gray border) around the unselected radio inputs.. which makes them almost invisible

**Comment by vesper8** [comment]
Actually I'm noticing this on all inputs that are styled with `"@tailwindcss/custom-forms"` including text inputs as well, there is no longer a thin gray border around them

**Comment by adamwathan** [comment]
Unfortunately we decided to go a different route and the custom-forms plugin is not compatible with Tailwind CSS v2. We recommend migrating to the `@tailwindcss/forms` plugin instead.

**Comment by vesper8** [comment]
@adamwathan that's cool.. I'll upgrade to `@tailwindcss/forms`

However I noticed that `@tailwindcss/ui` is installing `@tailwindcss/custom-forms` even after I removed it

```
warning " > @tailwindcss/ui@0.7.2" has incorrect peer dependency "tailwindcss@^1.8.3".
warning "@tailwindcss/ui > @tailwindcss/typography@0.2.0" has incorrect peer dependency "tailwindcss@^1.5.0".
warning "@tailwindcss/ui > @tailwindcss/custom-forms@0.2.1" has incorrect peer dependency "tailwindcss@^1.0".
```

**Comment by MCarroll** [comment]
Yes upgrading to @tailwindcss/forms I @tailwindcss/us is installing custom-forms as well.

**Comment by Hokkaydo** [comment]
I'm facing the same problem.
Why is custom-forms acting like this ?
Could it be fixed ?

**Comment by SimonJ** [comment]
same here 😄

**Comment by driftingly** [comment]
Ran into the same issue, looks like `@tailwindcss/ui` is no longer needed.
https://tailwindui.com/changes-for-v2

Removing the UI plugin fixed the issue for me.

**Comment by perryraskin** [comment]
I'm hitting the following errors when I try to update to v2. After running `npm install tailwindcss@latest postcss@latest autoprefixer@latest` I get:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: tailwindcss@2.0.2
npm ERR! node_modules/tailwindcss
npm ERR!   tailwindcss@"2.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer tailwindcss@"^1.0" from @tailwindcss/custom-forms@0.2.1
npm ERR! node_modules/@tailwindcss/custom-forms
npm ERR!   @tailwindcss/custom-forms@"^0.2.1" from @tailwindcss/ui@0.5.0
npm ERR!   node_modules/@tailwindcss/ui
npm ERR!     @tailwindcss/ui@"^0.5.0" from the root project
```
I tried uninstalling `/ui` and `/custom-form` but I still seem to be getting this. Anyone see something similar and solved it?

**Comment by eugenevdm** [comment]
> Ran into the same issue, looks like `@tailwindcss/ui` is no longer needed.
> https://tailwindui.com/changes-for-v2
> 
> Removing the UI plugin fixed the issue for me.

Can someone please give me a clue "remove UI plugin?"

**Comment by robbyrice** [comment]
You should remove it from the plugins section in your tailwind.config.js file and then recompile your css and javascript

```
module.exports = {
  purge: {},
  theme: {},
  variants: {},
  plugins: [
    require('@tailwindcss/ui') <- this is the line you need to delete
  ]
};
```
