### ISSUE TITLE
Purge doesn't keep tailwind classes used in HTML

### ISSUE THREAD

**Issue by noook** [tailwindlabs/tailwindcss#2703]
### Describe the problem:

The classes I added in the HTML are not conserved when building and purging style.

There is no CSS output
```vue
<template>
  <div class="text-3xl text-red-100">
    <h1>Hello</h1>
  </div>
</template>
```
```js
module.exports = {
  purge: {
    content: [
      './src/**/*.vue',
      './src/**/*.html',
      './src/**/*.js',
    ],
  },
};
```

### Link to a minimal reproduction:

[Github repository](https://github.com/noook/vue-ui-lib)

`yarn build` to see that there is no CSS included in the build

**Comment by sa3dany** [comment]
Are you sure postcss runs? I've checked the build script in package.json and the only thing it does is execute `vue-cli-service build`.

**Comment by noook** [comment]
Isn't PostCSS part of the build process ? If I change the purge config or put wrong configuration I have warnings so I guess the purge step is executed.

**Comment by sa3dany** [comment]
I am not really familiar with `vue-cli` so that's why I asked. Does running postcss directly also not produce an output?
`postcss src/assets/main.scss --output dist/styles.css`

**Comment by noook** [comment]
It runs correctly, it outputs a file of 106 347 lines, I guess nothing's purged in it.

**Comment by sa3dany** [comment]
You need to set the NODE_ENV to production for the purging to happen `NODE_ENV=production postcss src/assets/main.scss --output dist/styles.css`.

**Comment by noook** [comment]
Oh right, indeed it works way better. And my classes are now appended to the output, which is nice ! What's the trick then ? 

I checked `vue-cli` documentation under the "Working with postcss" section, so my config file should be read when building.

Any idea what's happening ? That's the first time I work with a post-processor I don't think I have enough knowledge about those things yet

**Comment by sa3dany** [comment]
Adding `import './assets/main.scss';` in `src/App.vue` within the <script> tags seems to produce the correct output.
I suggest closing this issue though since we have established that this is not a tailwind issue.

**Comment by Destreyf** [comment]
@noook @sa3dany 

I am using tailwind with vue in one of my projects, I imported the base style into my main.ts file and it worked as well.
