### ISSUE TITLE
Tailwindcss Alpha.5 - PostCSS 8 not working

### ISSUE THREAD

**Issue by benji014628** [tailwindlabs/tailwindcss#2711]
### Describe the problem:

Can't build tailwindcss because `Error: true is not a PostCSS plugin`

### Link to a minimal reproduction:

https://github.com/benji014628/portfolio/tree/jakelamb-tailwindv2-alpha-5
![Screen Shot 2020-10-30 at 9 42 13 AM](https://user-images.githubusercontent.com/44789941/97732815-4fb9f100-1a94-11eb-8052-42861bab2d1f.png)

**Comment by sumanthratna** [comment]
my guess is that this error is occurring due to the @tailwindcss/typography plugin—the tailwind devs haven't updated the plugins for v2 yet

**Comment by benji014628** [comment]
> my guess is that this error is occurring due to the @tailwindcss/typography plugin—the tailwind devs haven't updated the plugins for v2 yet

dang

**Comment by adamwathan** [comment]
You can use a prerelease version of the typography plugin if you like:

https://www.npmjs.com/package/@tailwindcss/typography?activeTab=versions

`npm install @tailwindcss/typography@dev`

We're still working on it but it works a bit better.

Closing as this is known and something we're already working on, everything will all be fine for the actual 2.0 release.
