### ISSUE TITLE
space-x-... and space-y-... do not work together 

### ISSUE THREAD

**Issue by lmittmann** [tailwindlabs/tailwindcss#2734]
### Describe the problem:

If `space-x-...` and `space-y-...` are used together the margin of the first child element is wrong.

### Link to a minimal reproduction:

https://play.tailwindcss.com/ALVUbVB3m1

```html
<div class="flex flex-wrap space-x-4 space-y-4 w-64">
  <div class="w-16 h-16 bg-gray-200"></div>
  ...
  <div class="w-16 h-16 bg-gray-200"></div>
</div>
```
This is also the case when `space-x-reverse space-y-reverse` is used.

**Comment by shiftgeist** [comment]
I don't think this is how `space-x-*` or `space-y-*` are intended to be used.

I suggest to only use `space-{x,y}-*` with one axis at a time.

If you need to have both I would use `grid` as shown in this example:

https://play.tailwindcss.com/fzWoY4kH3m

**Comment by adamwathan** [comment]
@shiftgeist is correct, this is the expected behavior for what you're doing I'm afraid. Using `gap` with grid is probably what you want, or something more complicated using flex box and wrapper elements and negative margins.
