### ISSUE TITLE
I can't create a tailwind plugin with gradient image background

### ISSUE THREAD

**Issue by prantaDutta** [tailwindlabs/tailwindcss#2737]
I am new to tailwind css. I am trying to create a tailwind plugin for my background with rgba color and an image. Here's my code

const plugin = require("tailwindcss/plugin");

module.exports = plugin.withOptions(() => {
    return function({ addUtilities }) {
        const newUtilities = {
            ".bg-img-with-opacity": {
                background:
                    linear -
                    gradient(
                        rgba(43, 108, 176, 0.9),
                        rgba(43, 108, 176, 0.9)
                    ),
                    url("../images/background-1.jpg")
            }
        };

        addUtilities(newUtilities);
    };
});

The problem here is that as classes are objects here I can't use url("../images/background-1.jpg") with a comma. I can't seem to find any solution to this. Thanks in advance.

**Comment by cossssmin** [comment]
```js
// tailwind.config.js
const plugin = require('tailwindcss/plugin')

module.exports = {
  plugins: [
    plugin(function({ addUtilities }) {
      const newUtilities = {
        '.bg-img-with-opacity': {
          backgroundImage: "linear-gradient(rgba(43, 108, 176, 0.9), rgba(43, 108, 176, 0.9)), url('../images/background-1.jpg')"
        },
      }

      addUtilities(newUtilities)
    })
  ]
}
```

But if you just need it for yourself / you're not looking to publish a plugin for others to use, define an utility:

```js
// tailwind.config.js
module.exports = {
  theme: {
    extend: {
      backgroundImage: {
        'img-with-opacity': "linear-gradient(rgba(43, 108, 176, 0.9), rgba(43, 108, 176, 0.9)), url('../images/background-1.jpg')",
      }
    }
  }
}
```

**Comment by prantaDutta** [comment]
Thanks, that totally worked.
