### ISSUE TITLE
sr-only elements are affecting spacing

### ISSUE THREAD

**Issue by mbenadda** [tailwindlabs/tailwindcss#2740]
### Describe the problem:

When using spacing utilities, eg `space-x-4` to lay out elements, `sr-only` elements affect the spacing flow, when in my opinion they should not as they are, by definition, not visible.

### Link to a minimal reproduction:

https://play.tailwindcss.com/XRtlRULbOU

There is a space before the "Visible item 1" (see the blue background not hitting the side of the viewport) where there should not be in my opinion.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

While this might not be ideal, you can solve this by applying a `hidden` attribute. Note, this is a change on the spacing utilities for Tailwind CSS 2.0

You can find a fix with the hidden prop on v2 here: https://play.tailwindcss.com/ujs1CJletT

**Comment by mbenadda** [comment]
Hey, thanks for your answer.

Unfortunately this fix is not helpful for `sr-only` elements as applying a `hidden` attribute will hide the element from screen reader users, the very users that should be the only ones to see the element.

I'll just keep removing the margin using a hardcoded inline style until there is a fix for `sr-only` 🙏

**Comment by adamwathan** [comment]
Hey @mbenadda, I would recommend just using an extra element and keeping the `sr-only` element out of the group:

https://play.tailwindcss.com/YDwwQ2uDhS

There is no real practical way for us to make this work automatically in Tailwind I'm afraid. Eventually once we have solid `gap` support in flexbox across browsers you will be able to use that instead.

The reason this is hard to build in to Tailwind is that we'd need to handle every combination of `hidden`, `sr-only`, `sm:sr-only`, `lg:focus:sr-only`, etc. etc. etc. The rule would have hundreds of selectors with lots of complex media query stuff and is just not worth the complexity, if it's even solvable at all. Way easier to just structure your markup taking this into account.

**Comment by mbenadda** [comment]
Hey Adam, thanks for the explanation!

I did not realize it might be so hard to implement. Unfortunately it's not always easy to alter markup in this way as that often has constraints for accessibility, but I do understand the rationale. Tradeoffs I guess 😅
