### ISSUE TITLE
@apply with class that has a dot, "." in the name produces a syntax error when used in LESS style block

### ISSUE THREAD

**Issue by coryvirok** [tailwindlabs/tailwindcss#2742]
Thanks for building my favorite CSS framework! Tailwind is a game-changer and reminds me of the early days of Bootstrap, but without the JS hassle. 

### Describe the problem:

I'm running into a Syntax Error while trying to use the `@apply` function inside a LESS style, (in Vue) for a class name that has a "." in it. E.g. this breaks while using the TailwindUI `-ml-0.5` class.

The error:

```
Syntax Error: `@apply` cannot be used with `.-mr-0` because `.-mr-0` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.-mr-0` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.
```

I've verified that the style `-mr-0.5` is in the built CSS file and I've also verified that this works if I don't use LESS and just use vanilla CSS. I've also tried escaping the dot using backslash as well as quoting the whole class name. But no luck...

### Link to a minimal reproduction:
Using a minimal Vue app created using vue-cli `@vue/cli 4.4.6`

 E.g. component.vue

```vue
<template>
  <div class="nope">Hello World</div>
</template>

<script>
export default {
  name: `Nope`
}
</script>

<style scoped lang="less">
.nope {
  @apply -mr-0.5;
}
</style>
```

Here's the postcss.config.js

```
const autoprefixer = require("autoprefixer");
const tailwindcss = require("tailwindcss");

module.exports = {
  plugins: [tailwindcss, autoprefixer],
};
```

I'm guessing this is either:
1. An issue with the `@apply` directive since escaping the class name, (e.g. `-ml-0\.5`) doesn't work
2. A postcss config issue

**Comment by adamwathan** [comment]
Tried to reproduce this but it works as expected here:

https://play.tailwindcss.com/dfXbhdd9Ig

Can you create an actual reproduction repository? What you've provided isn't enough for me to test, I need an actual repo I can clone and run and see the error.

**Comment by coryvirok** [comment]
Hey Adam. Thanks for taking a look. Here's a repro repo :) https://github.com/coryvirok/tailwindcss-apply-repro

You'll just need to:
1. `git clone https://github.com/coryvirok/tailwindcss-apply-repro.git`
2. `cd tailwindcss-apply-repro`
3. `npm install`
4. `npm run serve`

You should see:

```
 ERROR  Failed to compile with 1 errors                                                                              9:42:01 PM

 error  in ./src/components/HelloWorld.vue?vue&type=style&index=0&id=469af010&scoped=true&lang=less&

Syntax Error: SyntaxError

(2:3) `@apply` cannot be used with `.-ml-0` because `.-ml-0` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.-ml-0` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

  1 | .foo {
> 2 |   @apply -ml-0 0.5;
    |   ^
  3 | }
  4 |



 @ ./node_modules/vue-style-loader??ref--10-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--10-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--10-oneOf-1-2!./node_modules/less-loader/dist/cjs.js??ref--10-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/HelloWorld.vue?vue&type=style&index=0&id=469af010&scoped=true&lang=less& 4:14-468 14:3-18:5 15:22-476
 @ ./src/components/HelloWorld.vue?vue&type=style&index=0&id=469af010&scoped=true&lang=less&
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://10.0.0.236:8081&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

```

**Comment by khaled-sadek** [comment]
**-ml-0** is not found in Tailwind 1.9
Just update to Tailwind 2 or add it to your config manually

**Comment by coryvirok** [comment]
> **-ml-0** is not found in Tailwind 1.9
> Just update to Tailwind 2 or add it to your config manually

The problem isn't that `-ml-0` is not found. The problem is that the CSS class name `-ml-0.5` does not parse when used in a LESS style.

**Comment by adamwathan** [comment]
This is to do with how Less is parsing the input and for whatever reason it just doesn't understand the syntax. You can get around it this by using the `~` in Less to tell the compiler to treat the contents as raw output:

```html
<style scoped lang="less">
.foo {
  @apply ~"-ml-0.5";
}
</style>
```

Nothing we can do about this within Tailwind I'm afraid.

**Comment by coryvirok** [comment]
That works. Thanks @adamwathan!

**Comment by progtarek** [comment]
how can i fix it in scss?
