### ISSUE TITLE
Custom variant wrongly purged

### ISSUE THREAD

**Issue by hanoii** [tailwindlabs/tailwindcss#2748]
I defined the following custom variant:

```js
      // aos variant
      addVariant('aos', ({ modifySelectors, separator }) => {
        modifySelectors(({ selector }) => {
          return selectorParser(selectors => {
            const clonedSelectors = selectors.clone();
            [selectors, clonedSelectors].forEach((sel, i) => {
              sel.walkClasses(classNode => {
                classNode.value = `aos${separator}${classNode.value}`;
                classNode.parent.insertBefore(classNode, selectorParser().astSync(`.aos-animate${i === 0 ? '' : ' '}`));
              });
            });
            selectors.append(clonedSelectors);
          }).processSync(selector);
        });
      });
```

The variant works propery, as in `aos:translate-x-0` for instance. The problem is that when I build it for production using the default purge settings, this variant css is not included.

It seems the dash in the `.aos-animate` css is the culprit as I have another variant called `stuck` which doesn't get purged.

If I rename eveything to `aos-animate`, including variant name, it still doesn't work.

If I rename everythign to `aos`, including css selector in the modified css, it does work but obviously it doesn't work as the library I am using sets it to `aos-animate`.

I am going to probably switch the library (a scroll to reveal) that will allow me to set the class to something single workd, but I do believe this is a bug.

Thanks! Just started to use tailwind (and UI) and happy with it so far. Still riding the learning curve.

**Comment by vmarnauza** [comment]
I'm having the same issue with text direction variants added by https://github.com/RonMelkhior/tailwindcss-dir. I'm using tailwind v1.9.6.

I tried using the `safelist` option of the postcss config as a workaround, but so far couldn't get it to work. Also, the `safelist` option is still referred to as `whitelist` in the Tailwind docs https://tailwindcss.com/docs/controlling-file-size#purge-css-options.

**Comment by vmarnauza** [comment]
Nevermind, I seem to have fixed it based on https://github.com/tailwindlabs/tailwindcss/issues/1931#issuecomment-655547867

I used the exact config from the comment, using `whitelist` instead of `safelist`.

**Comment by smarterdigitalltd** [comment]
I have just discovered a similar issue on a ~3-month-old project - although, with a much simpler case. It seems that any custom variant I have created is getting purged, which hasn't always been the case.

The CSS classes are non-interpolated/concatenated strings in the templates, and all default variants "work" (purge or not-purge) correctly. 

I have tried whitelisting/safelisting as a test, but even that didn't work.

When I don't purge (ie a non-production build), everything works fine.

**Comment by smarterdigitalltd** [comment]
Here's what I've found so far:

Here's an example of a variant that works fine in non-prod (ie non-purged) environments (confirming that the CSS targeting is correct, as well as the plugin inclusion + variant config are all OK):

```
module.exports = plugin(function ({ addVariant, e }) {
  addVariant("scrolled", ({ modifySelectors, separator }) => {
    modifySelectors(({ className }) => {
      return `.headroom--not-top.headroom--pinned .${e(`scrolled${separator}${className}`)}`;
    });
  });
})
```

However, that stops working with PurgeCSS until I change to:

```
module.exports = plugin(function ({ addVariant, e }) {
  addVariant("scrolled", ({ modifySelectors, separator }) => {
    modifySelectors(({ className }) => {
      return `.${e(`headroom--not-top`)} .${e(`scrolled${separator}${className}`)}`;
    });
  });
})
```

Note that I had to drop the ".headroom--pinned" selector - it seemed that this wouldn't work even if I tried this:

```
module.exports = plugin(function ({ addVariant, e }) {
  addVariant("scrolled", ({ modifySelectors, separator }) => {
    modifySelectors(({ className }) => {
      return `.${e(`headroom--not-top`)}.${e(`headroom--pinned`)} .${e(`scrolled${separator}${className}`)}`;
    });
  });
})
```

This should be equivalent to the original working-only-in-dev version at the top in terms of what should be rendered, but nothing at all for this variant appears in the CSS file.

So now I'm using the second example. However - another variant which uses the exact same structure as the above isn't working unless it's a non-prod/purged environment (this might be related to @hanoii 's hyphen weirdness - although hyphens worked for me above):

```
module.exports = plugin(function ({ addVariant, e }) {
  addVariant("current-menu-item", ({ modifySelectors, separator }) => {
    modifySelectors(({ className }) => {
      return `.${e(`current-menu-item`)} .${e(`current-menu-item${separator}${className}`)}`;
    });
  });
})
```

Apart from the variant and class names, it's identical to the earlier example which _did_ work in both purged & non-purged environments.

Finally, I tried alternative syntax as per @hanoii 's example (and other libraries) - although this seems to be a PurgeCSS - not a PostCSS - thing.

Doesn't work:

```
module.exports = plugin(function ({ addVariant, e }) {
  addVariant("scrolled", ({ modifySelectors, separator }) => {
    modifySelectors(({ selector }) => {
      return selectorParser(selectors => {
        selectors.walkClasses(classNode => {
          classNode.value = `scrolled${separator}${classNode.value}`;
          classNode.parent.insertBefore(classNode, selectorParser().astSync(`.${e('headroom--pinned')}.${e('headroom--not-top')} `));
        });
      }).processSync(selector);
    });
  });
})
```

Works:

```
module.exports = plugin(function ({ addVariant, e }) {
  addVariant("scrolled", ({ modifySelectors, separator }) => {
    modifySelectors(({ selector }) => {
      return selectorParser(selectors => {
        selectors.walkClasses(classNode => {
          classNode.value = `scrolled${separator}${classNode.value}`;
          classNode.parent.insertBefore(classNode, selectorParser().astSync(`.${e('headroom--pinned')} `));
        });
      }).processSync(selector);
    });
  });
})
```

Plus, for all of these variations, I've tried combos of the PurgeCSS whitelist (I tried "safelist" too) config (Regex isn't my thing, so I'm not fully confident here):

```
    whitelist: {
      greedy: [/headroom/, /current-menu-item/],
    },
```

```
    whitelist: {
      deep: [/headroom/, /current-menu-item/],
    },
```

I'm also tied to using Tailwind 1.9.x on this project for the time being so I'm quite stuck! I can't go live with un-purged CSS, so I might need to start extracting variants out to CSS files for the time being.

**Comment by adamwathan** [comment]
Hey! Please provide an actual reproduction repository so we can troubleshoot the issue, if a reproduction isn't provided we have to try and recreate your problem from scratch which means the issue just sits untouched forever because we don't really have time for that.

Will leave this open for a few days to wait for a reproduction, otherwise will close and you can open a new issue with a reproduction if this is still an issue.

**Comment by hanoii** [comment]
In the process of creating a replication repo I learned that purgecss takes into account not just the class on its own, but also the parent selectos as well.

So in my case I am creating a variant called `aos` but that variant will only be affected if the aos class is present on the same html element of the parent, but that class is going to be set by javascript so it's not present initially on any files processed by purgecss.

I would call this something at least not intuitive and I would think that something like this is desirable although not sure where the problem lies. Maybe a different purgecss extarctor is needed, but not sure.

The repo I created where this behaviour is noticed is on https://github.com/hanoii/tailwind-purge-bug

**Comment by adamwathan** [comment]
Yeah this is expected behavior with PurgeCSS, it will remove all CSS selectors that don't appear to be used. So for example:

```css
.foo .bar {
  background: white;
}
```

Here the only way for this selector to ever actually *do* anything is if _both_ `foo` and `bar` appear in your HTML. If PurgeCSS can't find both of them, it will consider the selector to be unused and remove the CSS.

The solution is to either safelist `aos`, or make sure PurgeCSS is looking at the JavaScript file that adds the class (that's the approach I would take).

We explain this very explicitly in the documentation:

![image](https://user-images.githubusercontent.com/4323180/102510222-62dd4c00-4055-11eb-9f09-695b1a6a81e5.png)

> **This list should include any files in your project that reference any of your styles by name.** For example, if you have a JS file in your project that dynamically toggles some classes in your HTML, you should make sure to include that file in this list.

Going to close as not a bug but hopefully that is helpful!
