### ISSUE TITLE
ResolveConfig helper does not return all corePlugins properties

### ISSUE THREAD

**Issue by dobromir-hristov** [tailwindlabs/tailwindcss#2778]
### Describe the problem:

Tailwind version: 1.9.1

We use the `resolveConfig` helper to do some extraction from the Tailwind config, and I noticed that the `corePlugins` property returns an array of all the properties, with the exception of `screens,colors,spacing,keyframes`. Is this intentional? 

I tried with a bare empty config, and its still the case.

I also noticed that `corePlugins` is always returned as an array of items, no matter the format you specify in your config, I assume that is by design and if so great, but this is how I found out the issue I have above.

### Link to a minimal reproduction:

https://codesandbox.io/s/tailwind-resolve-config-output-tmhf1

**Comment by adamwathan** [comment]
Hey! The result you're seeing is correct, those missing keys are not core plugins, they are just arbitrary theme sections that other core plugins read from.

You can see the complete list of core plugins here:

https://tailwindcss.com/docs/configuration#core-plugins

and here in code:

https://github.com/tailwindlabs/tailwindcss/blob/master/src/plugins/index.js
