### ISSUE TITLE
is tailwindcss's server down ?

### ISSUE THREAD

**Issue by ahmadsiddeeq0** [tailwindlabs/tailwindcss#2785]
is tailwindcss's server down ?
visiting https://tailwindcss.com/ show that the website is down

**Comment by hastebrot** [comment]
It's up again on my side. Maybe it was because of the imminent release of TailwindCSS v2.

**Comment by ahmadsiddeeq0** [comment]
on my side is not , but i will keep checking

thanks for your reply

**Comment by benji014628** [comment]
This issue should be at https://github.com/tailwindlabs/tailwindcss.com/issues

**Comment by adamwathan** [comment]
Should be up!
