### ISSUE TITLE
Html body is not getting full width in tailwindcss

### ISSUE THREAD

**Issue by prantaDutta** [tailwindlabs/tailwindcss#2788]
Hello, I am new in tailwindcss. But I am having an issue here. 

Look at the screenshots, the background color is not applying in the navbar. Also the whole html body is not getting full width in medium and small screens.

What I don't understand is that I still haven't used any of the responsive classes from tailwindcss like md, sm or lg. But there are serious problems with width and I tried using tailwind class of w-full and w-screen. None of them work. 
 Here's the screenshot of the problem
![screenshot-2](https://user-images.githubusercontent.com/44747303/99542317-1d891880-29dc-11eb-91ba-8f5c15612b0f.png)
![screenshot-3](https://user-images.githubusercontent.com/44747303/99542326-211c9f80-29dc-11eb-827a-da1c7d12e51a.png)
![screenshot-4](https://user-images.githubusercontent.com/44747303/99542334-22e66300-29dc-11eb-96aa-3c8215880211.png)
![screenshot-1](https://user-images.githubusercontent.com/44747303/99542335-237ef980-29dc-11eb-831d-1e1ef13b1772.png)

  
You can find the code here: https://codesandbox.io/s/focused-curran-jdyup

Thanks in Advance.

**Comment by PaulMorel** [comment]
Your Code Sandbox link doesn't work. Maybe try with https://play.tailwindcss.com/ ?

**Comment by prantaDutta** [comment]
@PaulMorel link updated, check now

**Comment by deadcoder0904** [comment]
@prantaDutta it looks fine to me

![image](https://user-images.githubusercontent.com/16436270/99630288-9bdace80-2a5f-11eb-84e0-d571bd16d2b3.png)

**Comment by prantaDutta** [comment]
@deadcoder0904 just try it in the medium and small screen

**Comment by deadcoder0904** [comment]
@prantaDutta still works for me 🤷‍♂️

maybe make a minimal repro on Tailwind Play. Codesandbox loads too slow for me at least :(

**Comment by prantaDutta** [comment]
@deadcoder0904 Sorry I can't recreate the problem in Tailwind Play. So I created this GIF.

![for_github](https://user-images.githubusercontent.com/44747303/99637878-abfaaa00-2a6f-11eb-8a5b-125dcfb6f738.gif)

**Comment by deadcoder0904** [comment]
I am not sure which file to look at? Can you point me to where your `width`-related code is?

**Comment by prantaDutta** [comment]
@deadcoder0904 that's the thing. There is no width related code. Actually what happened is that I created this page first with just plain tailwind classes. Then I thought about making it responsive. And this is what I see the first time I opened my dev tools.

**Comment by prantaDutta** [comment]
@deadcoder0904 @PaulMorel ok, look at this guys, this is GIF, guys. 

I am trying to recreate the problem in Tailwind Play. But I couldn't. Then I noticed that the same line of code works perfectly in Tailwind Play but not with nextjs. I don't know what the problem here is but I shared both the Tailwind Play and NextJS code below.
Tailwind Play: 
`
<div class="flex justify-between items-center p-5 bg-indigo-800 text-white">
      <div class="ml-16">
        <div class="flex items-center">
          <div class="">
            <h4 class="tracking-widest uppercase">GrayScale</h4>
          </div>
          <div class="lg:hidden">
            <button
              type="button"
              class="text-gray-400 mt-1 hover:text-white focus:text-white focus:outline-none"
            >
              <svg
                class="w-6 h-6"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M4 6h16M4 12h16M4 18h16"
                ></path>
              </svg>
            </button>
          </div>
        </div>
      </div>
      <div class="mr-16">
          <a
            key={link.label}
            class="p-2 pr-2 uppercase tracking-widest font-semibold hover:bg-indigo-900 hover:text-gray-400 rounded-md"
          >
            Home
          </a>
          <a
            key={link.label}
            class="p-2 pr-2 uppercase tracking-widest font-semibold hover:bg-indigo-900 hover:text-gray-400 rounded-md"
          >
            Home
          </a>
          <a
            key={link.label}
            class="p-2 pr-2 uppercase tracking-widest font-semibold hover:bg-indigo-900 hover:text-gray-400 rounded-md"
          >
            Home
          </a>
          <a
            key={link.label}
            class="p-2 pr-2 uppercase tracking-widest font-semibold hover:bg-indigo-900 hover:text-gray-400 rounded-md"
          >
            Home
          </a>
          <a
            key={link.label}
            class="p-2 pr-2 uppercase tracking-widest font-semibold hover:bg-indigo-900 hover:text-gray-400 rounded-md"
          >
            Home
          </a>
      </div>
    </div>
`

NextJS Code: 
`
export default function IndexPage() {
  return (
    <div className="flex justify-between items-center p-5 bg-indigo-800 text-white">
      <div className="ml-16">
        <div className="flex items-center">
          <div className="">
            <h4 className="tracking-widest uppercase">GrayScale</h4>
          </div>
          <div className="lg:hidden">
            <button
              type="button"
              className="text-gray-400 mt-1 hover:text-white focus:text-white focus:outline-none"
            >
              <svg
                className="w-6 h-6"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M4 6h16M4 12h16M4 18h16"
                ></path>
              </svg>
            </button>
          </div>
        </div>
      </div>
      <div className="mr-16">
        <a className="p-2 pr-2 uppercase tracking-widest font-semibold hover:bg-indigo-900 hover:text-gray-400 rounded-md">
          Home
        </a>
        <a className="p-2 pr-2 uppercase tracking-widest font-semibold hover:bg-indigo-900 hover:text-gray-400 rounded-md">
          Home
        </a>
        <a className="p-2 pr-2 uppercase tracking-widest font-semibold hover:bg-indigo-900 hover:text-gray-400 rounded-md">
          Home
        </a>
        <a className="p-2 pr-2 uppercase tracking-widest font-semibold hover:bg-indigo-900 hover:text-gray-400 rounded-md">
          Home
        </a>
        <a className="p-2 pr-2 uppercase tracking-widest font-semibold hover:bg-indigo-900 hover:text-gray-400 rounded-md">
          Home
        </a>
      </div>
    </div>
  );
}

`

**Comment by deadcoder0904** [comment]
@prantaDutta Tailwind Play might be using some kind of Normalizr or your Next code might be the issue but still not a Tailwind issue. I recommend asking on StackOverflow :)

**Comment by prantaDutta** [comment]
@deadcoder0904 I also asked on Stackoverflow. I haven't got any response yet. But I am using the default template of nextjs examples with tailwindcss. So shouldn't it be normailized? Also, I think tailwind automatically normalizes my code.

**Comment by deadcoder0904** [comment]
@prantaDutta no idea

**Comment by PaulMorel** [comment]
![image](https://user-images.githubusercontent.com/1200261/99683052-eb180380-2a4d-11eb-8b1f-9b882ebdf447.png)

It seems to be your input in your footer that's causing your overflow.

**Comment by prantaDutta** [comment]
@PaulMorel @deadcoder0904 Thanks for helping me out. It turned out I used some containers in different sections. That's how the elements were overflowing. I am closing this issue. Also, I am new to tailwind so any tips on avoiding this kind of errors?

**Comment by deadcoder0904** [comment]
@prantaDutta This has nothing to do with Tailwind. Tailwind is just knowing CSS well enough so you might want to learn CSS properly. It's okay though, even after 5 years, CSS is still my hardest language 😂

**Comment by Mixpeal** [comment]
Adding overflow-hidden to the main container solved it for me

**Comment by rattanakneariroth** [comment]
@Mixpeal Thank you it worked just adding overflow-hidden

**Comment by ItsTerm1n4l** [comment]
@Mixpeal Thanks this solved it for me too!
