### ISSUE TITLE
hard warning about purge 2.0 changes even though tailwind.config.js settings as you request

### ISSUE THREAD

**Issue by narration-sd** [tailwindlabs/tailwindcss#2791]
### Describe the problem:

I'm getting the warnings as in attached image, even though the code you request is in tailwind.config.js. I didn't get them until recently - nothing here has changed.  Now on Tailwind 1.9.6 as you'll see

```
module.exports = {
  future: {  // their request from Tailwind as they transition
    removeDeprecatedGapUtilities: true,
    purgeLayersByDefault: true,
  },
...
  purge: {
    // Learn more on https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css
    layers: ['utilities'], // also Tailwind says this needed but still warns
    enabled: process.env.NODE_ENV === 'production',
    content: [
      'src/components/**/*.vue',
      'src/layouts/**/*.vue',
      'src/views/**/*.vue',
      'src/plugins/**/*.js',
      '!src/components/DocsContents.vue'
    ]
  }
```

### Link to a minimal reproduction:

you can help this without a reproduction, thanks. 
This is a big project, and not reducible (electron involved).
I'd pretty likely be confident others are seeing the problem.

![tailwind--faux-error](https://user-images.githubusercontent.com/247945/99572909-3963ce80-298a-11eb-8f99-a3516bd6f39d.png)

**Comment by benji014628** [comment]
enabled: process.env.NODE_ENV === 'production', should be `enabled: 'true`

**Comment by narration-sd** [comment]
Thanks for the idea, @benji014628 Jacob.

I tried it, though `process.env.NODE_ENV === 'production'` should be true during the build.

Unfortunately, hard-set of true made no difference.  Still the 'warn's come.

**Comment by adamwathan** [comment]
`purgeLayersByDefault` should take care of this and I can't reproduce this so it must be something else to do with the complexity of the project. Are there multiple builds of Tailwind happening somehow? Is there another config file somewhere that hasn't been updated?

Try explicitly adding `mode: "layers"` under `purge` and seeing if that helps.

**Comment by narration-sd** [comment]
@adamwathan Adam, that was the trick of it. Thank you very kindly.

I backed out Jacob's thoughtful idea, and put in the layers mode, and all now works perfectly.

It's indeed possible that Tailwind sees a kind of multiple builds, as where the problem happens, I'm compiling an Electron app into distributable form.. There are two processes, and they are compiled one after the other. Tailwind isn't involved in the Node portion, but may be getting included there, and so what you thought of may be what's happening. 

In any case, glad to feel we're operating normally again, and in such an actually complex scenario as Electron creates, not concerned with some minor things around the edges, as often show.

Thank you.
Clive

**Comment by narration-sd** [comment]
And just to add, @adamwathan , really appreciate that you looked straight into this. 

More confidence yet as I and we have had, that Tailwind is a very welcome and desired ability.
