### ISSUE TITLE
PostCSS plugin postcss-nested requires PostCSS 8

### ISSUE THREAD

**Issue by JuanM04** [tailwindlabs/tailwindcss#2799]
### Describe the problem:

When I upgraded Tailwind CSS to the version 2.0.1 inside my Next.js 10.0.2 (which should come with PostCSS 8, because Autoprefixer v10 works) project, it throw:

```
error - ./utils/styles/tailwind.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/next/dist/compiled/postcss-loader/cjs.js??ref--5-oneOf-6-2!./utils/styles/tailwind.css)
Error: PostCSS plugin postcss-nested requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
```

**Comment by dqn** [comment]
If using Next.js 10.0.2, `./node_modules/next/node_modules/postcss` will be 8.1.7.
Probably, `postcss-nested` uses `./node_modules/postcss`.

You can get around this by installing PostCSS 8 in your own project, but I don't think it's a fundamental solution.

**Comment by JuanM04** [comment]
@dqn it worked, but as you said, there should be a better solution

**Comment by nickturrietta** [comment]
I just ran into the same problem.

Solution here: https://tailwindcss.com/docs/installation#post-css-7-compatibility-build

**Comment by Rayaan522** [comment]
> I just ran into the same problem.
> 
> Solution here: https://tailwindcss.com/docs/installation#post-css-7-compatibility-build

thanks it works

**Comment by j-greig** [comment]
Note in case it helps anyone... if you get errors with the Postcss 7 npm installation above, try prefixing the `^` wildcard characters with a backslash — eg
`npm install tailwindcss@compat postcss@\^7 autoprefixer@\^9`

**Comment by JuanM04** [comment]
Using Next.js 10, I was able to install `tailwindcss@compat` and left the other plugins (like Autoprefixer) in their only-postcss8 version.

**Comment by taponidhitulsi** [comment]
For compatibility with **postcss v7**, install these:
- tailwindcss@compat
- postcss@^7
- autoprefixer@^7

Also if you are using nextjs, install these too:
- postcss-flexbugs-fixes@^4
- postcss-preset-env

**postcss-flexbugs-fixes** released **v5** recently supporting **postcss 8**. So we still need v4 for compatibilty. 

In short:
`yarn add tailwindcss@compat postcss@^7 autoprefixer@^7 postcss-flexbugs-fixes@^4 postcss-preset-env`.

**Comment by adamwathan** [comment]
For Next.js 10 you don't need the compatibility build, install Tailwind like this:

```
npm install tailwindcss@latest postcss@latest autoprefixer@latest
```

PostCSS and Autoprefixer need to be peer-dependencies as of PostCSS 8.

> You can get around this by installing PostCSS 8 in your own project, but I don't think it's a fundamental solution.

This _is_ the correct solution as of PostCSS 8: https://evilmartians.com/chronicles/postcss-8-plugin-migration

It's why we include `postcss` and `autoprefixer` in the installation instructions.

**Comment by IRediTOTO** [comment]
i got this too, I can come from `@zeit/next-css` let's check for it. I removed it

**Comment by boussadjra** [comment]
I followed the steps in [post-css-7-compatibility-build](https://tailwindcss.com/docs/installation#post-css-7-compatibility-build) to upgrade tailwind to v2.x with vue 3 and it fails, it always raises that error.

**Comment by adamwathan** [comment]
@boussadjra Please open a new issue that includes a link to a GitHub repo that reproduces the problem.

**Comment by StephanSchmidt** [comment]
Vue 3 works for me with the PostCSS 7 compatible install. 

It doesn't find plugins though

```
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Cannot find module '@tailwindcss/forms'
```

neither did other plugins like typography nor if I use npm:@tailwindcss

**Comment by boussadjra** [comment]
@StephanSchmidt please try to open a new issue where you put a link to reproduction repository

**Comment by getspooky** [comment]
Hi, 
Downgrade your autoprefixer to version 9, use
```json
 "autoprefixer": "9.0.0",
```

**Comment by muhsalaa** [comment]
Do we still need to use `postcss-flexbug-fixes` along with tailwindcss?

**Comment by giraffesyo** [comment]
@muhsalaa Not if you're using tailwindcss version 2, IE support has been dropped.

**Comment by Jay-flow** [comment]
> For compatibility with **postcss v7**, install these:
> 
> * tailwindcss@compat
> * postcss@^7
> * autoprefixer@^7
> 
> Also if you are using nextjs, install these too:
> 
> * postcss-flexbugs-fixes@^4
> * postcss-preset-env
> 
> **postcss-flexbugs-fixes** released **v5** recently supporting **postcss 8**. So we still need v4 for compatibilty.
> 
> In short:
> `yarn add tailwindcss@compat postcss@^7 autoprefixer@^7 postcss-flexbugs-fixes@^4 postcss-preset-env`.

It is work for me.
My dependency list is as below.
```
{
  "name": "one-page",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.34",
    "@fortawesome/free-brands-svg-icons": "^5.15.2",
    "@fortawesome/react-fontawesome": "^0.1.14",
    "next": "10.0.5",
    "public-ip": "^4.0.3",
    "react": "17.0.1",
    "react-device-detect": "^1.15.0",
    "react-dom": "17.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.10",
    "@storybook/addon-actions": "^6.1.15",
    "@storybook/addon-essentials": "^6.1.15",
    "@storybook/addon-links": "^6.1.15",
    "@storybook/react": "^6.1.15",
    "@types/node": "^14.14.22",
    "@types/react": "^17.0.0",
    "@typescript-eslint/eslint-plugin": "^4.14.1",
    "@typescript-eslint/parser": "^4.14.1",
    "autoprefixer": "^7",
    "babel-loader": "^8.2.2",
    "eslint": "^7.18.0",
    "eslint-config-prettier": "^7.2.0",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-react": "^7.22.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "postcss": "^7",
    "postcss-flexbugs-fixes": "^4",
    "postcss-preset-env": "^6.7.0",
    "prettier": "^2.2.1",
    "tailwindcss": "^2.0.1-compat",
    "typescript": "^4.1.3"
  }
}

```

**Comment by Lambertn33** [comment]
> I just ran into the same problem.
> 
> Solution here: https://tailwindcss.com/docs/installation#post-css-7-compatibility-build

Thank you..it worked

**Comment by Lambertn33** [comment]
> I just ran into the same problem.
> 
> Solution here: https://tailwindcss.com/docs/installation#post-css-7-compatibility-build

Thank you..it worked

**Comment by kshekh** [comment]
> https://tailwindcss.com/docs/guides/create-react-app

This works, Thanks.

https://tailwindcss.com/docs/guides/create-react-app

**Comment by logan0611** [comment]
If you using mac Os this will be solve your problem
Change ^ prefix for ~
npm install -D tailwindcss@npm:@tailwindcss/postcss7-compat postcss@~7 autoprefixer@~9

**Comment by lemonpatwari** [comment]
It is work for me.

1. npm uninstall tailwindcss
2. npm install -D tailwindcss@latest postcss@latest autoprefixer@latest

 https://tailwindcss.com/docs/installation#post-css-7-compatibility-build // source
