### ISSUE TITLE
New darkMode: 'media' Not Working Mac Big Sur

### ISSUE THREAD

**Issue by tance77** [tailwindlabs/tailwindcss#2803]
The new darkMode: 'media' does not seem to be working. I made a working example here in the tailwind playground. I would expect the background color to be black since my system is set to dark and not light. Yet it is rendering bg-pink-200. I also tried switching browsers thinking it might have had something to do with Chrome. I tried Safari and still no dice. I feel like I'm using the variant correctly. Maybe I'm just using it wrong I'm unsure. 

[DarkMode Docs](https://tailwindcss.com/docs/dark-mode)

**Example**
https://play.tailwindcss.com/GSKHAqLZK6

![Screen Shot 2020-11-18 at 3 09 52 PM](https://user-images.githubusercontent.com/3421501/99599826-fec15c80-29b0-11eb-8dba-af372de68bab.png)
<img width="1382" alt="Screen Shot 2020-11-18 at 3 11 48 PM" src="https://user-images.githubusercontent.com/3421501/99599827-ff59f300-29b0-11eb-87bf-9b3255da868c.png">

**Comment by j-griffiths** [comment]
Hmm—I'm also experiencing issues with Dark Mode on Big Sur (11.0.1 build 20B29). I have tried adding `dark` to the `backgroundColor` variants but with no joy.

Can you share your working code?

**Comment by tance77** [comment]
I basically copy and pasted my tailwind.config.js file for you @j-griffiths. While I was updating my original one I linked. I noticed I had placed the darkMode property within ```theme:{}```  that is just wrong. ```darkMode``` is its own property and should be on the root of the config. The one below has it in the correct spot and is working.

https://play.tailwindcss.com/zlP6yibsFl

**Comment by j-griffiths** [comment]
Magic! All working now. I'm not sure why it took me this long to figure it out!

Cheers.

**Comment by b7s9** [comment]
@tance77 bless you 🙏 , I just spent way too long on the same issue lol
