### ISSUE TITLE
[Bug Report] Search functionality no longer works since v2 release

### ISSUE THREAD

**Issue by alexperronnet** [tailwindlabs/tailwindcss#2806]
### Bug report

Hello, first of all congratulations on the v2 update, it's really a great job. Since the release the search functionality on [tailwindcss.com](https://tailwindcss.com) no longer works for either [V2](https://tailwindcss.com/) &  [V1](https://v1.tailwindcss.com)...

### Screenshots

![tailwindScreenshotV2](https://user-images.githubusercontent.com/59840413/99608442-2f83af00-2a0e-11eb-83fd-6313d8931de9.PNG)

![tailwindScreenshotV1](https://user-images.githubusercontent.com/59840413/99608443-30b4dc00-2a0e-11eb-950c-a2c3926664ed.PNG)

**Comment by benji014628** [comment]
He knows already.....

**Comment by KeentDev** [comment]
Would be nice if this was acknowledged though, also looks like the previous issues about search not working was not present here. Maybe removed? idk, kind of disappeared.

**Comment by KeentDev** [comment]
This is where all the issues went https://github.com/algolia/docsearch-configs/issues?page=1&q=is%3Aissue+is%3Aopen, on Algolia's repo. The breaking change already increased 80% of algolia's number of issues already.

Can someone from dev can actually acknowledge this issue?

**Comment by alexperronnet** [comment]
The search functionality is now operational. I will close this issue.
