### ISSUE TITLE
tailwindcss cli throws

### ISSUE THREAD

**Issue by PutziSan** [tailwindlabs/tailwindcss#2814]
### Describe the problem:

```
Cannot find module 'autoprefixer'
```

![image](https://user-images.githubusercontent.com/13392042/99670814-6939d180-2a71-11eb-893a-53859c6010ce.png)

### Link to a minimal reproduction:

```cli
mkdir tmp-tester-tailwind
cd tmp-tester-tailwind
npx tailwindcss build -o tailwind.css
```

I am using windows 10.

**Comment by stuki** [comment]
MacOS 10.15.7, Same thing happens to me

**Comment by adamwathan** [comment]
Ah crap we know about this but forgot. I'll fix! In the mean time:

```
npx -p autoprefixer postcss -c "tailwindcss build -o tailwind.css"
```

Ugly right? We'll make it better soon, sorry!

**Comment by ericholdridge** [comment]
> ### Describe the problem:
> ```
> Cannot find module 'autoprefixer'
> ```
> 
> ![image](https://user-images.githubusercontent.com/13392042/99670814-6939d180-2a71-11eb-893a-53859c6010ce.png)
> 
> ### Link to a minimal reproduction:
> ```
> mkdir tmp-tester-tailwind
> cd tmp-tester-tailwind
> npx tailwindcss build -o tailwind.css
> ```
> 
> I am using windows 10.

Did you get this working?

**Comment by SamuelMS** [comment]
> npx -p autoprefixer postcss -c "tailwindcss build -o tailwind.css"

@adamwathan I just get `npx: command not found: postcss` with this now.

**Comment by badguybluebane** [comment]
Same here. Just when in try to `npx tailwind init`

**Comment by adamwathan** [comment]
Forgot a -p sorry:

`npx -p autoprefixer -p postcss -c "tailwindcss build -o tailwind.css" `

**Comment by pikeas** [comment]
Also seeing a warning from yarn:

```
warning " > tailwindcss@2.0.1" has unmet peer dependency "autoprefixer@^10.0.2".
```

I'm using Next.js, updating to TW 2.0 went smoothly but did require a small additional step of adding PostCSS and autoprefixer to package.json.

Phenomenal upgrade guide overall, one of the best I've ever seen!

**Comment by RobinMalfait** [comment]
Hey!

We've fixed this with a cleaner tailwind-cli for npx:

```
npx tailwindcss-cli@latest build -o tailwind.css
```

More information: https://tailwindcss.com/docs/installation#using-tailwind-without-post-css
