### ISSUE TITLE
@apply breaks with `hover:` and `active:`

### ISSUE THREAD

**Issue by Uninen** [tailwindlabs/tailwindcss#2816]
### Describe the problem:

I have some buttons that I wanted to clean up with @apply (Tailwind 2) but it breaks when there are `hover:` and `active:` in the same apply. It works fine if you break them into separate items like before. (That is `.btn {}, .btn:hover {}, btn:active {}` ) 

Not sure if this is a bug but "apply anything" doesn't seem to be valid here.

### Link to a minimal reproduction:

This Play repros the error: https://play.tailwindcss.com/07OlVsPz3P?file=css

**Comment by ryanw3b3r** [comment]
Hi,

I think you have to add active variant to backgroundColor. I can fix your example by changing variants property to:

```
variants: {
    extend: {
      backgroundColor: ['active']
    }
  },
```

**Comment by Uninen** [comment]
That seems to break with some TS issue on Play but indeed solves the problem. 

Thanks @ryanw3b3r 👍
