### ISSUE TITLE
2.0.1-compat incompatible with @tailwindcss/ui

### ISSUE THREAD

**Issue by Negan1911** [tailwindlabs/tailwindcss#2835]
## Describe the problem:

Whenever we try to run Tailwind 2 with `@tailwindcss/ui` we get this error:

```
./src/index.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./src/index.css)
TypeError: value.charCodeAt is not a function
```

There are two workarounds:
1. Remove the `@tailwindcss/ui` plugin, which makes trouble using Tailwind UI.
2. Comment `@tailwind components;` which makes the project work again but with unknown consecuences.

### Link to a minimal reproduction:

https://github.com/Negan1911/tailwind-error-repro

Install all and run `yarn start` and you'll face the issue, you can also try both workarounds to see them working again.

**Comment by trevyn** [comment]
`@tailwindcss/ui` is to be removed when upgrading to Tailwind 2. See: https://tailwindui.com/changes-for-v2#updating-your-tailwind-ui-projects

**Comment by Negan1911** [comment]
Ah, I see, thanks for clarifying!

**Comment by Pringels** [comment]
Excuse my ignorance, but where exactly in the upgrade guide is this mentioned?

**Comment by Negan1911** [comment]
@Pringels looks to be a new doc on Tailwind UI page, haven't seen it before and I think that was not published yet when I was having this issue, but looks to be on the tailwindui.com header
![Uploading Screen Shot 2020-11-20 at 10.55.51.png…]()

**Comment by Pringels** [comment]
Ah gotcha, thanks @Negan1911 ! 

I think it might be a good idea to include a hint somewhere in the Tailwind CSS upgrade guide. 
Something like: "Note to Tailwind UI users: you will also need to follow **this** guide"
