### ISSUE TITLE
Color override of transparent & current are missing

### ISSUE THREAD

**Issue by stefanoruth** [tailwindlabs/tailwindcss#2841]
### Describe the problem:

I am trying to override the colors, with a specefic set that i have chosen but, some of the more default values dosent seem to work like: transparent and current.

Here is my config and i have linked a demo project below

```js
const colors = require("tailwindcss/colors");

module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: {
    colors: {
      transparet: colors.transparet,
      current: colors.current,
      white: colors.white,
      black: colors.black,
      green: colors.lime,
      red: colors.red,
      gray: colors.coolGray,
    },
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
};

```
### Link to a minimal reproduction:

I have recreated the project here where you can see that the output in the `tailwind.css` file, if you look for the class `.bg-transparet` then the value is not being set, the same issue appears for  `.bg-current`

https://github.com/stefanoruth/tailwindcss-test

**Comment by fedeci** [comment]
Hi, `transparent` and `current` are not exports of the `tailwindcss/colors` module.
They are the equivalent of these CSS properties
- `color: transparent`
- `color: currentColor`

and can be added in this way:
```js
module.exports = {
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      ...
  },
  ...
}
```

**Comment by stefanoruth** [comment]
Ohh Damm, you are right, they arent in the color set, thanks 😊

**Comment by fedeci** [comment]
Nope, `tailwincss/colors` just contains the default color palette. I don't think it would make sense to add it there.
