### ISSUE TITLE
@apply with dot(.) in front of class name throws an error.

### ISSUE THREAD

**Issue by abepark01** [tailwindlabs/tailwindcss#2843]
### Describe the problem:
In Tailwind 1.9.6, I was able to do something like the following; however, this no longer works in Tailwind 2.X.

```css
html {
  @apply .box-border;
}
```

I get the following error:

```
Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(2:10) The `.box-border` class does not exist, but `box-border` does. If you're sure that `.box-border` exists, make sure that any `@import` statements are being properly processed before Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

  1 | html {
> 2 |   @apply .box-border;
    |          ^
  3 | }
  4 |

ℹ ｢wdm｣: Failed to compile.
```

Unfortunately, I have a lot of legacy CSS that uses the @apply directive.
Would it be possible to support @apply with classes that have a dot in front of them?
Preserving backward compatibility would be ideal.

Tailwind 0.7.4 and 1.9.6 both supported this approach.

Thank you!

**Comment by mdegoys** [comment]
Yes, it is documented here: https://tailwindcss.com/docs/upgrading-to-v2#remove-leading-dot-from-apply-statements. This is no longer supported.

**Comment by abepark01** [comment]
@mdegoys 
That's a bit unfortunate, but Thanks for the note!

**Comment by abepark01** [comment]
I whipped up a quick python script to remove the leading dots from the @apply statements.

https://gist.github.com/abepark01/13da5f470121ea3f3d54400db299b34d

In my case, I had 137 changes. So, manually removing the dots would have been a bit tedious 😄 


```python
#!/usr/bin/env python3

import os
import sys

if __name__=="__main__":
    if len(sys.argv) >  1:
        path = sys.argv[1]
    else:
        sys.exit("The folder path is required")

for subdirectories, directories, files in os.walk(path):
    for filename in files:
        fullpath = subdirectories + os.path.sep + filename

        if fullpath.endswith('.css') or fullpath.endswith('.scss') or fullpath.endswith('.less'):
            data = []
            with open(fullpath, 'r') as fstream:
                for line in fstream:
                    line = line.rstrip()
                    pieces = line.split(' ')
                    if len(pieces) > 0 and '@apply' in pieces:
                        updated_pieces = [item.replace('.', '', 1) for item in pieces]
                        data.append(' '.join(updated_pieces) + "\n")
                    else:
                        data.append(line + "\n")
            with open(fullpath, 'w') as fstream:
              fstream.writelines(data)
```

**Comment by progtarek** [comment]
is there a solution for SCSS, I am trying to add 
`py-2.5`
but i am getting compilation error 

The `"py-2.5"` class does not exist. If `"py-2.5"` is a custom class, make sure it is defined within a `@layer` directive.
