### ISSUE TITLE
Tailwind 2.0 won't purge unused animation utilities

### ISSUE THREAD

**Issue by robertgorbul** [tailwindlabs/tailwindcss#2847]
### Describe the problem:
When `purge` option is enabled and `animation` utilities isn't used it still present in final bundle

### Link to a minimal reproduction:
gatsby 2.26.1
gatsby-plugin-postcss 3.2.0
tailwind 2.0.1
autoprefixer 10.0.2
postcss 8.1.3
postcss-csso 5.0.0
postcss-import 13.0.0
postcss-normalize 9.0.0
postcss-preset-env  6.7.0

**tailwind.config.js**:
```
purge: {
    enabled: true,
    content: ['src/**/!(*.d).{js,jsx,ts,tsx}'],
    options: {
      safelist: [/^text-social/],
    },
  },
```

**postcss.config.js**:
```
const cssImport = require('postcss-import');
const normalize = require('postcss-normalize');
const presetEnv = require('postcss-preset-env');
const csso = require('postcss-csso');
const tailwindcss = require('tailwindcss');

module.exports = ({ mode }) => {
  const isProduction = mode === 'production';

  const plugins = [
    normalize(),
    cssImport(),
    tailwindcss(),
    presetEnv({
      stage: 2,
      features: {
        'nesting-rules': true,
        'prefers-color-scheme-query': true,
      },
    }),
    isProduction && [csso()],
  ];

  return {
    plugins,
  };
};

```

**styles.css**:
```
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';
```

Compiled styles starts with(csso restructure moves it to the beginning):
`@-webkit-keyframes spin{to{transform:rotate(360deg)}}@keyframes spin{to{transform:rotate(360deg)}}@-webkit-keyframes......`

**Comment by adamwathan** [comment]
You'll need to configure PurgeCSS to do this for you as removing unused keyframes is not the default behavior (usually this is handled by a minifier like cssnano since it has nothing to do with your HTML).

You can enable it like this:

```js
module.exports = {
  purge: {
    // ...
    content: [
      // ...
    ],
    options: { keyframes: true }
  }
}
```
