### ISSUE TITLE
Futures/experimental keys no longer needed?

### ISSUE THREAD

**Issue by pikeas** [tailwindlabs/tailwindcss#2859]
```
module.exports = {
    experimental: {
        additionalBreakpoint: true,
        extendedFontSizeScale: true,
        extendedSpacingScale: true,
    },
    future: {
        defaultLineHeights: true,
        purgeLayersByDefault: true,
        removeDeprecatedGapUtilities: true,
    },
}
```

https://tailwindcss.com/docs/upcoming-changes is gone, and there's no CLI message, so these seem to be unnecessary in 2.0. It's worth a note in the upgrade guide and/or a CLI warning so that users can keep tailwind.config.js lean.

**Comment by benji014628** [comment]
But isn't obvious to remove them after?

**Comment by adamwathan** [comment]
Yeah none of those keys do anything currently, I can add a note to the upgrade guide. We will still use `experimental` in the future for new features for sure but right now there are no experimental features.
