### ISSUE TITLE
Installing tailwind 2 in vue 3 raises the error  PostCSS plugin tailwindcss requires PostCSS 8

### ISSUE THREAD

**Issue by boussadjra** [tailwindlabs/tailwindcss#2861]
### Describe the problem:

I've already installed a fresh project using vue 3 and typescript with vue cli 4, the app works fine but when i install the tailwind 2 and setup `postcss.config.js` i get the error cited above and the code will not be compiled, I tried to solve the problem by following the solutions in this [issue](https://github.com/tailwindlabs/tailwindcss/issues/2799) but that doesn't work for me 

### Link to a minimal reproduction:
[my reproduction repository link](https://github.com/boussadjra/vue3-tailwind2)

**Comment by ammuhaysin** [comment]
Maybe this link could help.
https://tailwindcss.com/docs/installation#post-css-7-compatibility-build

**Comment by DasdWaller** [comment]
Check this [docs](https://tailwindcss.com/docs/installation#post-css-7-compatibility-build)

**Comment by boussadjra** [comment]
> Check this [docs](https://tailwindcss.com/docs/installation#post-css-7-compatibility-build)

I've already tried out that, it's mentioned in the issue that I cited

**Comment by adamwathan** [comment]
Hey! You need to use the compatibility build, Vue does not support PostCSS 8 yet. Follow the instructions here:

https://tailwindcss.com/docs/installation#post-css-7-compatibility-build

Your package.json shows the wrong version for Tailwind, PostCSS, and autoprefixer.

**Comment by adamwathan** [comment]
Opened a pull request that adds the right dependencies:

https://github.com/boussadjra/vue3-tailwind2/pull/1

To fix it I ran these commands from the instructions 👍🏻 

```
npm uninstall tailwindcss postcss autoprefixer
npm install tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
```

**Comment by boussadjra** [comment]
Thanks and sorry for commenting again, I pulled your changes in my local environment and I ran `npm i` after removing `node_modules` folder but when I run `npm run serve` it shows me again the same issue :

![image](https://user-images.githubusercontent.com/11801238/99910118-97771580-2cec-11eb-9114-67bc5068f47d.png)
 
my env : windows 10, node 12.16.3, npm 6.14.5.

I tried out in codesandbox and it doesn't work.

[![Edit compassionate-euclid-j6iwj](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/compassionate-euclid-j6iwj?fontsize=14&hidenavigation=1&theme=dark)

**Comment by adamwathan** [comment]
Can you try deleting your package-lock.json/yarn.lock files in addition to node_modules and trying again? Would like to see the contents of package-lock.json after you do that.

Right now it's still installing the wrong version of tailwindcss which is where that error is coming from.

CodeSandbox isn't the best place to test this stuff because it doesn't provide a proper build environment unless you use one of their server templates like Nuxt.js.

**Comment by boussadjra** [comment]
Now after deleting `package-lock.json` and rerunning `npm i` it works , @adamwathan thank you very much for this awesome framework and your current help.

**Comment by WarenGonzaga** [comment]
The complete documentation can be found here: https://tailwindcss.com/docs/installation#post-css-7-compatibility-build works for me.
