### ISSUE TITLE
Heroku fails to build

### ISSUE THREAD

**Issue by ManuelFrigerio** [tailwindlabs/tailwindcss#2864]
### Describe the problem:

Hi, I upgraded my Rails app to Tailwind 2.0.1-compat.
Everything works normal on my machine but when I deploy on Heroku I get this error:

```
       ERROR in ./app/javascript/css/application.scss

       Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):

       ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

       SassError: File to import not found or unreadable: tailwindcss/base.

               on line 2 of /tmp/build_fd32fb6b_/app/javascript/css/application.scss

       >> @import "tailwindcss/base";
```

### Link to a minimal reproduction:

All files to reproduce the issue are in this gist: https://gist.github.com/ManuelFrigerio/5113aeaadd17846f17828d126e229c4f

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you verify that it works on your machine with the same environment variables, for example a production build with `NODE_ENV=production`.

While I doubt that this might be the problem, make sure that you use a node version on Heroku that is node 12.13 or higher (https://tailwindcss.com/docs/upgrading-to-v2#upgrade-to-node-js-12-13-or-higher)

**Comment by adamwathan** [comment]
I wonder if this has something to do with Sass trying to process your `@import` statements. Do you actually need it to be an `scss` file? It looks like you are trying to do everything with PostCSS.

**Comment by ManuelFrigerio** [comment]
It actually turns out that the problem was related to the fact that on Heroku you must have the node buildpack AND it must be the first buildpack in your list. it took me hours to figure that out but once I changed that it all worked fine.

**Comment by adamwathan** [comment]
Ah ok well glad to hear you found the solution! Thanks for sharing it here.

**Comment by Hat52** [comment]
What do you mean by buildpack to be the first one? Can you please explain? I am facing the same issue.
