### ISSUE TITLE
"border-1" doesn't work

### ISSUE THREAD

**Issue by fuzzthink** [tailwindlabs/tailwindcss#2866]
### Describe the problem:

"border-1" doesn't work.

### Link to a minimal reproduction:

https://play.tailwindcss.com/Wjb2Q1Yp3p

**Comment by DasdWaller** [comment]
check [docs](https://tailwindcss.com/docs/border-width), `border-1` doesnt exist but you can create on your configs.
close this issue please.

**Comment by fuzzthink** [comment]
Thank you, missed the border-width section.

**Comment by KhaledMohamedP** [comment]
I was looking for `border-1`, but noticed I can just use `border`, so it goes `border, border-2, border-4 ...`. That was bit confusing for me, was that the case for you too?

**Comment by appcypher** [comment]
There should be a redundant `border-1`
