### ISSUE TITLE
Dark Mode classes not adhered to on Brave iOS

### ISSUE THREAD

**Issue by shnparker** [tailwindlabs/tailwindcss#2867]
### Describe the problem:

I've set up a basic WIP nextjs website to enable dark mode on user OS preference. It works as seen in the following:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/15893956/99902468-b793de00-2cc6-11eb-8f7e-2832e504b924.gif)

On Brave iOS it does not follow the color scheme (Brave Desktop works fine). 
**UPDATE**: It works if brave browser is restarted, but does not immediately switch like Safari does.
Safari iOS works as intended, so I think the issue is localised to Brave iOS
URL is https://shaneparker.co.za 

### Link to a minimal reproduction:

I was unable to set up a tailwind play config the same way as I am unable to figure out how dark mode enables in the output section (toggling dark mode on the play site only switches themes for outer containers). Here's a gif instead (hope it helps). 

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/15893956/99902618-c9c24c00-2cc7-11eb-8e17-177c8f05b23f.gif)

I can also give access to or make the repo public if needed.
If this is an issue with Brave Browser I'm happy to report this to them and close issue as well

**Comment by DasdWaller** [comment]
Maybe the problem is from brave because tailwindcss suport `prefers-color-scheme` and brave have a problem with this. Check [this ](https://community.brave.com/t/brave-rewards-doesnt-utilize-prefers-color-scheme/73485) from brave community.

**Comment by fedeci** [comment]
The problem is probably with Brave not listening properly for a change in system settings and not updating WebKit as a consequence. This would also demonstrate why if you restart the app you get the right colors.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

However, it seems like this is not an issue with tailwind itself. As mentioned above, we use the `prefers-color-scheme` media queries, and we can't change anything about that behaviour.

As @DasdWaller mentioned, it is apparently a known issue in Brave itself.
