### ISSUE TITLE
Version 2.0.1 not working properly with webpack

### ISSUE THREAD

**Issue by lucaros97** [tailwindlabs/tailwindcss#2871]
### Describe the problem:
I have a problem using new functionalities like the new color palette in the 2.0.1 version.

I'm using a Jestream app so I upgraded with the PostCSS 7 compatibility build.
I have also removed the `@tailwind/ui`plugin from the `tailwind.config.js` which seems not be working anymore.
The problem it's that some colors like the cool-gray are not working.

### Link to a minimal reproduction:

Here is an example of what I means:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/8333004/99906742-09456400-2cd9-11eb-8f88-1f28c8399c7c.png">

As you can see I applied the bg-coolgray-100 class

Here is the link of the button in Play:
https://play.tailwindcss.com/pf2FwfUPId

**Comment by lucaros97** [comment]
Ok as the described in the background-colors page seems the colors available by default are only the included in the "default color palette:
https://tailwindcss.com/docs/background-color#background-colors

**Comment by adamwathan** [comment]
Hey! There is no `bg-coolgray-100` class, this is your config file in that Play:

```js
const colors = require('tailwindcss/colors')

module.exports = {
  theme: {
    extend: {
      colors: {
        'light-blue': colors.lightBlue,
        cyan: colors.cyan,
      },
    },
  },
  variants: {},
  plugins: [],
}
```

Please follow the upgrade guide to upgrade from v1.0 to v2.0, it explains all of the changes:

https://tailwindcss.com/docs/upgrading-to-v2

If you want there to be a "coolgray" color you will need to add it to your config:

https://play.tailwindcss.com/Lo8p1XX7hM?file=config

The "gray" is already "coolGray" by default though, so if that's the color you want you can just use "gray".
