### ISSUE TITLE
Tailwind compatible PostCSS 7 install does not find plugins for TailwindUI 2

### ISSUE THREAD

**Issue by StephanSchmidt** [tailwindlabs/tailwindcss#2880]
### Describe the problem:

For TailwindUI I use Tailwindcss 2.0.

When using Vue with PostCSS 7 and the Tailwind compatible PostCSS 7 install, plugins are not found.
```
error  in ./src/assets/styles/index.css

Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Cannot find module '@tailwindcss/forms'

```

### Link to a minimal reproduction:

https://github.com/StephanSchmidt/tailwind-plugin-issue

**Comment by web2033** [comment]
Did you install them? (they go as separate packages)
`npm i @tailwindcss/forms @tailwindcss/typography @tailwindcss/aspect-ratio`

then require them in tailwind.config.js
```js
plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    require('@tailwindcss/aspect-ratio'),
],
```

**Comment by StephanSchmidt** [comment]
No I haven't ;-) I thought about this and searched about installing the plugins but didn't find anything so I assumed they are part of the tailwind package. Thanks.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

- `@tailwindcss/ui` is not needed anymore for Tailwind CSS 2.0

More information can be found here: https://tailwindui.com/changes-for-v2

**Comment by alexkb** [comment]
This may seem obvious to some, but initially wasn't for me - I had installed the forms package and was still seeing the error. It wasn't until I restarted 'npm run dev' that the error went away.
