### ISSUE TITLE
@apply classes breaks with some focus: classes

### ISSUE THREAD

**Issue by philfreo** [tailwindlabs/tailwindcss#2888]
Works:

https://play.tailwindcss.com/YduMNBK97u?layout=horizontal&file=css

Doesn't work:

https://play.tailwindcss.com/n3j5SjOVE4?layout=horizontal&file=css

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This will be fixed in the next version of Tailwind!

2 relevant PR's:

- Fix issue with @apply not working as expected with !important inside an atrule (#2824)
- Fix issue with @apply not working as expected with defined classes (#2832)
