### ISSUE TITLE
focus class not working with primary color

### ISSUE THREAD

**Issue by cprodhomme** [tailwindlabs/tailwindcss#2896]
### Describe the problem:

```html
// work
<input class="focus:ring-green-500 focus:border-green-500">

// not work
<input class="focus:ring-primary-500 focus:border-primary-500">
```

![Capture d’écran 2020-11-25 à 15 23 46](https://user-images.githubusercontent.com/7428736/100239930-45273600-2f32-11eb-8eee-27e4579a40bd.png)
![Capture d’écran 2020-11-25 à 15 23 58](https://user-images.githubusercontent.com/7428736/100239926-448e9f80-2f32-11eb-9a48-04cb6b9335fb.png)

my primary color is set : 
```js
module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        primary: '#10B981',
        secondary: '#ecc94b'
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
```

### Link to a minimal reproduction:

Use the tailwindcss version 2.0.1

**Comment by fedeci** [comment]
With the configuration you provided only `*-primary` classes are created, not all their shades.
This is the right way to make it work:
```html
<input class="border focus:ring-green-500 focus:border-primary">
```
or you must provide shades in the configuration file:
```js
module.exports = {
  theme: {
    extend: {
      colors: {
        primary: {
          500: '#10B981',
        }
      },
    },
  },
}
```

**Comment by cprodhomme** [comment]
oh i see ! 🤦 
thanks !
