### ISSUE TITLE
tailwindcss 2.0 is not working on laravel 8

### ISSUE THREAD

**Issue by abdinur99** [tailwindlabs/tailwindcss#2901]
### Describe the problem:
1 installed tailwindcss postcss autoprefixer 
2 added directives to resource/css/app.css 
3 upgraded laravel-mix 5.1 to 6 beta

when i run npm run dev
✔ Compiled Successfully in 8498ms
┌───────────────────────────────────┬──────────┐
│ File                              │ Size     │
├───────────────────────────────────┼──────────┤
│ /js/app.js                        │ 593 KiB  │
├───────────────────────────────────┼──────────┤
│ css/app.css                       │ 61 bytes

**Comment by adamhopkinson** [comment]
I'm having the same issue, [posted it on StackOverflow yesterday](https://stackoverflow.com/questions/65010873/installing-tailwindcss-v2-into-laravel-works-but-does-nothing-when-run) but no suggestions yet.

**Comment by stefanfisk** [comment]
You need to integrate Tailwind in the asset build pipeline for the directives to work. Here is an article that show some options on how to achieve that: https://justlaravel.com/how-to-use-tailwind-css-laravel/.

**Comment by abdinur99** [comment]
> You need to integrate Tailwind in the asset build pipeline for the directives to work. Here is an article that show some options on how to achieve that: https://justlaravel.com/how-to-use-tailwind-css-laravel/.

it doesn't work for tailwindcss 2.0.....

**Comment by adamwathan** [comment]
Here are the instructions for installing Tailwind 2.0 with Laravel Mix (5):

https://tailwindcss.com/docs/guides/laravel

You need to use the compatibility build until Mix 6 is released.

If you are still having issues please open another issue and include a reproduction. Issues that do not include reproductions will just be closed as unfortunately it's not realistic for us to recreate everyone's projects from scratch.

**Comment by adamhopkinson** [comment]
Thanks @adamwathan. I'd put a reproduction in my StackOverflow link above, but should have reproduced it here.

In a couple of hours of searching for a solution, I didn't find the Laravel-specific installation guide you've linked above. Maybe I was being stupid and it's obvious, but I don't think the ['standard' Tailwind installation page](https://tailwindcss.com/docs/installation) has a single mention of 'Laravel'. Maybe it should?
