### ISSUE TITLE
Missing DEFAULT option for ringOffsetWidth and ringOffsetColor

### ISSUE THREAD

**Issue by rafaelpimpa** [tailwindlabs/tailwindcss#2911]
### Describe the problem:

Trying to set a default ring with offset doesn't work.

### Link to a minimal reproduction:

https://play.tailwindcss.com/hNYXW0Qzj9

**Comment by simonswiss** [comment]
Hey! 👋

There is no offset specified in your Play example, only the `ring` itself (defaulting to 3px).

If you add a `ring-offset-2` for example, the ring will be offset by 2 pixels, as expected:

https://play.tailwindcss.com/W4SSmpZj4h

**Comment by rafaelpimpa** [comment]
I'm aware of that, is it normal to use 4 classes for a ring? I thought we could setup defaults for the 4 elements of ring and use a single ``focus:ring`` class, otherwise the classes are gonna be huge, e.g. ``focus:ring-2 focus:ring-green-500 focus:ring-offset-2 focus:ring-offset-white``

**Comment by adamwathan** [comment]
This is a valid request, will play with this more at some point soon and see if it makes sense to make it work this way 👍🏻 Thanks for bringing it up!
