### ISSUE TITLE
Custom default Black/White colors in v2.01 aren't being ouput correctly

### ISSUE THREAD

**Issue by tobydallder** [tailwindlabs/tailwindcss#2918]
In a previous project using an earlier version of Tailwind I added a custom set of black colors like this:

```
black: {
  default: "#000",
  "15": "rgba(0, 0, 0, 0.15)",
  "50": "rgba(0, 0, 0, 0.50)",
  "75": "rgba(0, 0, 0, 0.75)",
  "95": "rgba(0, 0, 0, 0.95)"
}
```

Giving me the following default options:  `text-black` `border-black`  `bg:black` as well as my transparent options.

In a new project I'm using v2.0 and when trying the same technique, The default eg. `text-black` isn't generated in the css output but `text-black-default` is generated instead. This issue isn't happening with our other custom colours blue, green, red etc.

Here is an example of this in Tailwind Play:

https://play.tailwindcss.com/8DIFSDLSbn

**Comment by DylanVann** [comment]
```diff
- default: "#000",
+ DEFAULT: "#000",
```

https://tailwindcss.com/docs/upgrading-to-v2#update-default-theme-keys-to-default

**Comment by tobydallder** [comment]
Thanks @DylanVann !

I wasn't aware that changed from v1 to v2.

Problem solved.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

@DylanVann thanks for helping out!
