### ISSUE TITLE
Border-Transparent not aplying

### ISSUE THREAD

**Issue by wefixit-tech** [tailwindlabs/tailwindcss#2939]
i copy the default hero section from tailwind UI, and has border-transparent but when a see the live page it has a border white, the only way to solve is to change to border-none, but i want to know if there is a fix?

**Comment by adamwathan** [comment]
Can you share your config file? Perhaps the transparent color doesn't exist.

**Comment by wefixit-tech** [comment]
const defaultTheme = require("tailwindcss/defaultTheme");
const colors = require("tailwindcss/colors");

module.exports = {
    purge: [
        "./storage/framework/views/*.php",
        "./resources/views/**/*.blade.php",
    ],

    theme: {
        colors: {
            // Build your palette here
            gray: colors.blueGray,
            blue: colors.blue,
            lightblue: colors.lightBlue,
            red: colors.red,
            green: colors.green,
            indigo: colors.indigo,
            white: colors.white,
        },
        extend: {
            fontFamily: {
                sans: ["Nunito", ...defaultTheme.fontFamily.sans],
            },
        },
    },

    plugins: [
        require("@tailwindcss/forms"),
        require("@tailwindcss/typography"),
        require("@tailwindcss/aspect-ratio"),
    ],
};


Here is. i read the docs of tailwind v2 and not see anything to have to add a transparent color or to enable it?

**Comment by adamwathan** [comment]
Yeah you are not including `transparent` in your color palette. Do this instead:

```diff
  module.exports = {
    theme: {
      colors: {
        // Build your palette here
+       transparent: 'transparent',
        gray: colors.blueGray,
        blue: colors.blue,
        lightblue: colors.lightBlue,
        red: colors.red,
        green: colors.green,
        indigo: colors.indigo,
        white: colors.white,
      },
      extend: {
        fontFamily: {
          sans: ["Nunito", ...defaultTheme.fontFamily.sans],
        },
      },
    },
  
    plugins: [
      require("@tailwindcss/forms"),
      require("@tailwindcss/typography"),
      require("@tailwindcss/aspect-ratio"),
    ],
  };
```

We should document this, sorry for the confusion.

**Comment by mabasic** [comment]
Why does this not work out of the box?

**Comment by jjalonso** [comment]
> ```diff
> transparent: 'transparent'
> ```

I guess it works when you adding colors inside extends prop, if you do it outside you overwriting all the colors and the theme will contain only the colors you have inside, all props works like that depending if its inside extend or outside.

**Comment by jjalonso** [comment]
> Why does this not work out of the box?

I guess it works when you adding colors inside extends prop, if you do it outside you overwriting all the colors and the theme will contain only the colors you have inside, all props works like that depending if its inside extend or outside.

**Comment by natrodrigo** [comment]
@adamwathan 

> ```diff
>         // Build your palette here
> +       transparent: 'transparent',
> ```

I think docs need to be clearead about this, because it does not work as colors, and docs suggest it without warning that this limitation exists. It's 2024 and I only found this info here.
