### ISSUE TITLE
The space-x-reverse does not get applied for large screens

### ISSUE THREAD

**Issue by ajmeraaxesh** [tailwindlabs/tailwindcss#2942]
Was going through the tailwind labs videos and the following css of space-x-reverse  
![Screen Shot 2020-11-29 at 10 34 21 AM](https://user-images.githubusercontent.com/831046/100533827-b4e93980-322e-11eb-8685-7179e57211bb.png)
does not get applied on larger screens

```
<div className="flex flex-row-reverse items-center space-x-6 space-x-reverse lg:space-x-12">
                <div className="h-20 w-20 bg-white rounded shadow-md"></div>
                <div className="h-20 w-20 bg-white rounded shadow-md"></div>
                <div className="h-20 w-20 bg-white rounded shadow-md"></div>
                <div className="h-20 w-20 bg-white rounded shadow-md"></div>
 </div>
```

**Comment by DasdWaller** [comment]
I had the same problem yesterday. Link to [reproduction](https://play.tailwindcss.com/5WjKLi6uaW?size=998x1077) I create a playground. If you see the playground the first one without `flex-row-reverse` and smaller equal than 1023 pix remove the space from first child. But with `flex-row-reverse` and bigger equal than 1024 pix remove the space from first child. Another strange problem is when your remove the `lg:space-x-12` from the first element without `flex-row-reverse` then the two class with or whiteout `flex-row-reverse` remove the space from their first childs.

**Comment by adamwathan** [comment]
Need to add `lg:space-x-reverse`:

https://play.tailwindcss.com/XiCON4uuaV?size=836x1077

The idea here is that all `space-x-*` classes reset the direction, otherwise you'd have no way to _un_reverse something at a bigger screen size.

**Comment by ajmeraaxesh** [comment]
Ok thanks for the comment. In the videos though, its not mentioned. Would suggest to create a pinned comment for that
