### ISSUE TITLE
Responsive border not functional

### ISSUE THREAD

**Issue by gaslit** [tailwindlabs/tailwindcss#2948]
How do I create a responsive border so the following code works:

`<div class="border-l-2 border-red-600 md:border-l-2 md:border-t-2 md:border-blue-100">1</div>`

Basically on small screens, this has a 2px thick border at the left that is red-600 colored. On scaling to big screens, there should be a top 2px border while the left border disappears. The border color is switched to blue-100.

However, the behavior for the md breakpoints never enable and the border on medium screens and above is the same as the small one. Any advice?

Thanks.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

The trick is to reset the border on the left `md:border-l-0`, see: https://play.tailwindcss.com/XmeO41tHAi

**Comment by gaslit** [comment]
Sorry for late reply. It was a bug on my end. Thanks very much. May you have a great year ahead.
