### ISSUE TITLE
Tailwind CSS v2.0 compat build - 'npx tailwindcss init -p' not working

### ISSUE THREAD

**Issue by mpellegrini** [tailwindlabs/tailwindcss#2957]
### Describe the problem:

Creating a new issue after going thru #2831 

As I understand the requirements, tailwinds 2.0 requires Node >= 12 as per https://github.com/tailwindlabs/tailwindcss/issues/2831#issuecomment-731616851

I am using the latest LTS of node v14.15.1 which should be good.  However when running 

npx tailwindcss init -p

I am getting the following error

"Cannot find module 'autoprefixer'"

### Link to a minimal reproduction:

```
~/Documents/Projects% node -v
v14.15.1
~/Documents/Projects%
~/Documents/Projects% mkdir compat-test && cd compat-test
~/Documents/Projects/compat-test%
~/Documents/Projects/compat-test% npm init -y
Wrote to /Users/michael/Documents/Projects/compat-test/package.json:

{
  "name": "compat-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


~/Documents/Projects/compat-test% npm install -D tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN compat-test@1.0.0 No description
npm WARN compat-test@1.0.0 No repository field.

+ postcss@7.0.35
+ @tailwindcss/postcss7-compat@2.0.1 (as tailwindcss)
+ autoprefixer@9.8.6
added 90 packages from 91 contributors in 4.204s

10 packages are looking for funding
  run `npm fund` for details

~/Documents/Projects/compat-test% npx tailwindcss init -p
npx: installed 84 in 4.698s
Cannot find module 'autoprefixer'
Require stack:
- /Users/michael/.npm/_npx/46296/lib/node_modules/tailwindcss/lib/cli/commands/build.js
- /Users/michael/.npm/_npx/46296/lib/node_modules/tailwindcss/lib/cli/commands/index.js
- /Users/michael/.npm/_npx/46296/lib/node_modules/tailwindcss/lib/cli/main.js
- /Users/michael/.npm/_npx/46296/lib/node_modules/tailwindcss/lib/cli.js
```

However if I use the current Node v15.3.0, everything works as expected
```
~/Documents/Projects% node -v
v15.3.0
~/Documents/Projects% mkdir compat-test && cd compat-test
~/Documents/Projects/compat-test% npm init -y
Wrote to /Users/michael/Documents/Projects/compat-test/package.json:

{
  "name": "compat-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


~/Documents/Projects/compat-test% npm install -D tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9

added 90 packages, and audited 90 packages in 4s

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
~/Documents/Projects/compat-test% npx tailwindcss init -p

   @tailwindcss/postcss7-compat 2.0.1

   ✅ Created Tailwind config file: tailwind.config.js
   ✅ Created PostCSS config file: postcss.config.js
```

**Comment by davidgut** [comment]
I just encountered the same issue and indeed, updating to the latest node version solves the issue:

```
npm cache clean -f
npm install -g n
n latest

npm uninstall tailwindcss postcss autoprefixer
npm install tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
npx tailwindcss init
```

**Comment by jiaming10** [comment]
This issue is very weird because I can confirm it is working at 23 November, because I created a new project on that date. However when I tried to create another project today, then it started to fail. 

I'm also using the Node LTS, and I don't think updating NodeJS version as per https://github.com/tailwindlabs/tailwindcss/issues/2831#issuecomment-731616851 is the solution.

**Comment by adamhopkinson** [comment]
I had the same issue a few days ago, and can confirm that updating node to v15 is one possible solution. Glad to see that there's another solution which doesn't involve going ahead of the stable node version.

**Comment by adamwathan** [comment]
I wonder if this is really an issue of npm v6 vs npm v7 — does Node 15 use npm 7 by default? It sounds like npx isn't noticing that `tailwindcss` is installed and aliased within package.json.

I'm running npm 7 so haven't run into this myself :/

This solution will always work though:

```
npx tailwindcss-cli@latest init -p
```

This whole compatibility build stuff is a nightmare, sorry about this folks.

**Comment by mpellegrini** [comment]
For sure, Node 15 uses NPM 7, while Node 14 uses NPM 6.  And more likely the culprit rather than Node.

And can confirm that 

``` bash
 npx tailwindcss-cli@latest init -p
```
always works.

Just a matter of time for things to get caught up and not require this compat build.  Still appreciating all the great things in tailwinds 2.0 - so thanks to the team for a great job!!

**Comment by hamedghaderi** [comment]
> npx tailwindcss-cli@latest init -p

Yes, it worked for me

**Comment by robertwt7** [comment]
[this](https://github.com/tailwindlabs/tailwindcss/issues/2831#issuecomment-731038281) comment worked for me on node v12.18.4

Had the exact same issue with command:
`npx tailwindcss init` 

on the tailwind website installation instruction

**Comment by erkage** [comment]
Came from:
https://tailwindcss.com/docs/installation

Ran:
`npx tailwind init -p` 

Got Error:
```
Cannot find module 'autoprefixer'
Require stack:
.npm/_npx/65167/lib/node_modules/tailwindcss/lib/cli/commands/build.js
.npm/_npx/65167/lib/node_modules/tailwindcss/lib/cli/commands/index.js
.npm/_npx/65167/lib/node_modules/tailwindcss/lib/cli/main.js
.npm/_npx/65167/lib/node_modules/tailwindcss/lib/cli.js
```

My solution:
- Update Node to v14.15.1 (from around v14.8) and NPM 6.14.8
- Ran `npm install -D tailwindcss@latest postcss@latest autoprefixer@latest`

->`npx tailwindcss init -p` just worked

**Comment by satyakresna** [comment]
I just try use `npx tailwindcss-cli@latest init -p` after install tailwindcss version 2.0.1 with it's dependencies in my Laravel project and it works!

Here are the step I reproduce:

```
laravel new test-tailwind
npm install
npm install -D tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
npx tailwindcss-cli@latest init -p
```

<img width="592" alt="Screen Shot 2020-12-05 at 07 00 13" src="https://user-images.githubusercontent.com/11099186/101223688-8ef8e480-36c7-11eb-94d4-ea831c5eb459.png">

**Comment by RobinMalfait** [comment]
Hey all!

Glad it worked out with the `npx tailwindcss-cli@latest init -p`!
Going to close this issue, if there are other issues, feel free to open a new issue!

**Comment by shruti29799** [comment]
npx: installed 123 in 40.235s
Invalid or unexpected token
