### ISSUE TITLE
addBase plugin in tailwind.config.js is not working

### ISSUE THREAD

**Issue by batrasaurabh90** [tailwindlabs/tailwindcss#2965]
### addBase plugin in tailwind.config.js is not working

  I am using tailwind v2 with css in js. I want to use header tags (h1, h2, h3) to work as they normally would without tailwind as I have html generated from markdown files.

My `tailwind.config.js` file:
```javascript
const plugin = require('tailwindcss/plugin')

module.exports = {
  purge: [],
  theme: {
    extend: {},
  },
  variants: {},
  plugins: [
    // require('@tailwindcss/typography'),
    plugin(function({ addBase, config }) {
      addBase({
        'h1': { fontSize: config('theme.fontSize.2xl') },
        'h2': { fontSize: config('theme.fontSize.xl') },
        'h3': { fontSize: config('theme.fontSize.lg') },
      })
    })
  ],
}
```
My gatsby-browser.js file:
```javascript
import "tailwindcss/dist/base.min.css"
require("prismjs/themes/prism-coy.css")
```
I tried typography too but that seems to have impact on prismjs css.
Now my first choice, but I tried to disable preflight in tailwind.config.js file. That didn't work for me.

I did npx tailwind build and gatsby develop after changes on each step.

Are disabling preflight & addBase features not supported when using CSS in JS or is this some bug or am I missing anything?

**Comment by batrasaurabh90** [comment]
I am using tailwind v2 with CSS in JS & gatsby.
I am trying to add header tags (h1, h2, h3) in base css using plugin because html returned from markdown uses that. But that doesn't seem to work.

My tailwind.config.js:
```javascript
const plugin = require('tailwindcss/plugin')

module.exports = {
  purge: [],
  theme: {
    extend: {},
  },
  variants: {},
  plugins: [
    // require('@tailwindcss/typography'),
    plugin(function({ addBase, config }) {
      addBase({
        'h1': { fontSize: config('theme.fontSize.2xl') },
        'h2': { fontSize: config('theme.fontSize.xl') },
        'h3': { fontSize: config('theme.fontSize.lg') },
      })
    })
  ],
}
```

My gatsby-browser.js:
```javascript
import "tailwindcss/dist/base.min.css"
require("prismjs/themes/prism-coy.css")
```

Though not my first choice, I tried disabling preflights in config file. That didn't work too.

Are these not supported when using CSS in JS or is this a bug?

**Comment by adamwathan** [comment]
Use the `theme` function, not the config function. The config function is returning more than just the font-size, since font-size utilities have default line heights. You're essentially doing something like this which won't work

```js
addBase({
  h1: { fontSize: ['20px', { lineHeight: '32px' }] }
})

**Comment by adamwathan** [comment]
Here's a working example:

https://play.tailwindcss.com/uF9rN9jewc?file=config

**Comment by batrasaurabh90** [comment]
Thanks Adam. But this too doesn't seem to work.
I am not using css like this. But using CSS-in-JS using Twin Babel Macro and Emotion. Option 2 from https://www.gatsbyjs.com/docs/tailwind-css/

If this is not supported with that config, I might have to port to postcss from styled components.

**Comment by jamesvclements** [comment]
@adamwathan What is the proper way to get the line heights also applied to the base tags?

```js
    extend: {
      fontSize: {
        headingXl: ["var(--heading-xl)", "var(--heading-xl-leading)"],
        headingLg: ["var(--heading-lg)", "var(--heading-lg-leading)"],
        headingMd: ["var(--heading-md)", "var(--heading-md-leading)"],
      },
    },
  },
  plugins: [
    plugin(function ({ addBase, theme }) {
      addBase({
        h1: { fontSize: theme("fontSize.headingXl") },
        h2: { fontSize: theme("fontSize.headingLg") },
        h3: { fontSize: theme("fontSize.headingMd") },
      });
    }),
  ],
```
This applies the font sizes to the tags, but not the line heights

**Comment by mariod84** [comment]
> [@adamwathan](https://github.com/adamwathan) What is the proper way to get the line heights also applied to the base tags?
> 
>     extend: {
>       fontSize: {
>         headingXl: ["var(--heading-xl)", "var(--heading-xl-leading)"],
>         headingLg: ["var(--heading-lg)", "var(--heading-lg-leading)"],
>         headingMd: ["var(--heading-md)", "var(--heading-md-leading)"],
>       },
>     },
>   },
>   plugins: [
>     plugin(function ({ addBase, theme }) {
>       addBase({
>         h1: { fontSize: theme("fontSize.headingXl") },
>         h2: { fontSize: theme("fontSize.headingLg") },
>         h3: { fontSize: theme("fontSize.headingMd") },
>       });
>     }),
>   ],
> This applies the font sizes to the tags, but not the line heights

I have the same question too.
in my case i have to read also fontweight and letterSpacing from 
` fontSize: {
        'h1-desktop-v2': [
          '4rem',
          {fontWeight: 500, lineHeight: '4.5rem', letterSpacing: '-0.08rem'},
        ],`

**Comment by wongjn** [comment]
You can access the second array element using its key, `1`, like:

```js
addBase({
  h1: {
    fontSize: theme("fontSize.h1-desktop-v2"),
    fontWeight: theme("fontSize.h1-desktop-v2.1.fontWeight"),
    lineHeight: theme("fontSize.h1-desktop-v2.1.lineHeight"),
    letterSpacing: theme("fontSize.h1-desktop-v2.1.letterSpacing"),
  },
});
```
Or more succinctly as:
```js
addBase({
  h1: {
    fontSize: theme("fontSize.h1-desktop-v2"),
    ...theme("fontSize.h1-desktop-v2.1"),
  },
});
```
Which results in:
```css
h1 {
  font-size: 4rem;
  font-weight: 500;
  line-height: 4.5rem;
  letter-spacing: -0.08rem;
}
```
See https://play.tailwindcss.com/FDcWmgzUkz?file=config

**Comment by mariod84** [comment]
yes, it works!
Thankyou!
