### ISSUE TITLE
`@layer` doesn't check the the passed name

### ISSUE THREAD

**Issue by c4710n** [tailwindlabs/tailwindcss#2977]
### Describe the problem:

When I am using `@layer` like this:
```css
/* These styles will all be purged */
@tailwind base;
@tailwind components;
@tailwind utilities;

/* These styles will be purged */
@layer componentssssssssssss {  /* create a typo intentionally */
  .btn { /* ... */ }
}

/* These styles will not be purged */
.flatpickr-innerContainer { /* ... */ }
.flatpickr-weekdayContainer { /* ... */ }
.flatpickr-weekday { /* ... */ }
```
Although I create a typo, it still can be built successfully.

 A part of result is:
```text
t-animation-timing-function:cubic-bezier(0,0,.2,1);animation-timing-function:cubic
-bezier(0,0,.2,1)}}@layer componentssss{.anchor{font-weight:500;transition-property
:background-color,border-color,color,fill,stro
```
As you can see, **@layer componentssss** is write into bundle directly.

Maybe, when passing a wrong layer name to `@layer`, it should throw an error?

**Comment by adamwathan** [comment]
Hey! `@layer` is actually a proposed CSS feature so I think it would be a bad idea to error if someone was using it with other names:

https://drafts4.csswg.org/css-cascade-5/#at-layer

Agree the experience would probably be a bit better but I think it's best to keep this behavior as-is at the moment.
