### ISSUE TITLE
Custom gradients removes existing gradients from Tailwind

### ISSUE THREAD

**Issue by joaoalpalhao** [tailwindlabs/tailwindcss#2980]
When creating a custom backgroundImage in the tailwind.config.js all the existing gradients seem disappear.

```
module.exports = {
  theme: {
    backgroundImage: theme => ({
      'loadingdiv': 'linear-gradient(to right, #E5E5E5 0%, #F5F5F5 30%, #E5E5E5 50%)'
    }),
}
```

Same happened to colors, had to add all the default ones otherwise it wouldn't show up.

I'm using React.

**Comment by joaoalpalhao** [comment]
Found out that I was overriding instead of extending the config settings.

**Comment by louh** [comment]
Thanks for updating your issue with your solution! I ran into the same issue as well and this helped me a lot.
