### ISSUE TITLE
Can't use `theme()` helper in CSS for new decimal spacings

### ISSUE THREAD

**Issue by robclancy** [tailwindlabs/tailwindcss#2981]
Can't use `theme()` helper in CSS for new decimal spacings.

For example, `theme('spacing.1.5')` will not work because it is looking for `spacing[1][5]`. I'm fairly sure this is because you use `lodash get` which doesn't support this. https://github.com/tailwindlabs/tailwindcss/blob/master/src/lib/evaluateTailwindFunctions.js#L36

I'm on 1.x still so never tested 2 but I don't see any changes that would make it any different between the branches.

When using `theme` in JS I can just do `theme('spacing')[1.5]` but I don't have that option in the CSS. (unless there is some special syntax I don't know about)

**Comment by adamwathan** [comment]
Hey! You can do this:

```
theme('spacing[1.5]')
```
