### ISSUE TITLE
Unable to extend default of ringOffsetColor

### ISSUE THREAD

**Issue by Braunson** [tailwindlabs/tailwindcss#2988]
### Describe the problem:

Unable to override the default of ringOffsetColor

### Link to a minimal reproduction:

https://play.tailwindcss.com/1mpiZGRgy1?file=config

**Comment by OwenVey** [comment]
Looking at the default config [here](https://github.com/tailwindlabs/tailwindcss/blob/d1ef88a61b2f7b42b211d1b31b214e6add0c19be/stubs/defaultConfig.stub.js#L537-L541), it doesn't look like you're able to. I do think that this would be a good feature to add however.

**Comment by adamwathan** [comment]
This has been added (https://github.com/tailwindlabs/tailwindcss/pull/2951) 🥳 Will be in the next release 👍🏻
