### ISSUE TITLE
col-start-1 not working with screensize

### ISSUE THREAD

**Issue by jochemgruter** [tailwindlabs/tailwindcss#2989]
### Describe the problem:
col-start-1 is not putting the col at position 1 if you use a screensize identifer. Please check the reproduction for explaination.

### Link to a minimal reproduction:

https://play.tailwindcss.com/VybCKIzokN

**Comment by adamwathan** [comment]
Hey! The `col-span` classes override the start/end values (only real way this can all work), so you need to specify the start/end value again at that screen size, like:

```
col-start-1 sm:col-span-2 sm:col-start-1
```

Here's a demo:

https://play.tailwindcss.com/qxQCNJNVv0

**Comment by ocielgarrido** [comment]
por que a mi es la pagina de mostracion me funciona y no en la mia, la estrucura

 <body>   
         {{-- menu navegacion        --}}
         @livewire('navigation-menu')

            <div class="grid grid-cols-6 md:grid-cols-12 gap-2">
                <div class="col-span-6 md:col-span-4 bg-cyan-500 p-4">
                  col span 2
                </div>
                <div class="col-span-6 md:col-span-8 bg-cyan-500 p-4">
                  col span 4
                </div>
              </div>
        

            
                     
          

        @stack('modals')

        @livewireScripts
    </body>

**Comment by alexschcom** [comment]
> Hey! The `col-span` classes override the start/end values (only real way this can all work), so you need to specify the start/end value again at that screen size, like:

@adamwathan I think it would be very helpful to have this little caveat mentioned [in the docs](https://tailwindcss.com/docs/grid-column#starting-and-ending-lines), since it specifically states that `col-start` and `col-span` can be combined. (Same with [`grid-row` and `row-span`](https://tailwindcss.com/docs/grid-row#starting-and-ending-lines), I assume?)
