### ISSUE TITLE
Documentation error for white-space nowrap

### ISSUE THREAD

**Issue by RobertMei** [tailwindlabs/tailwindcss#3027]
### Describe the problem:

The documentation at https://tailwindcss.com/docs/whitespace describes the class  for CSS

white-space: nowrap;

as

"whitespace-nowrap" <-- wrong

Please change to 

"whitespace-no-wrap" as it is in the CSS

Thanks
Robert

**Comment by gabrielzevedo** [comment]
This is part of the upgrade to version 2: https://tailwindcss.com/docs/upgrading-to-v2#update-renamed-utility-classes

**Comment by RobertMei** [comment]
Sorry, my bad
