### ISSUE TITLE
Any other solutions for TypeError: getProcessedPlugins is not a function?

### ISSUE THREAD

**Issue by marcodeluca** [tailwindlabs/tailwindcss#3039]
The error:
Module build failed (from ./node_modules/postcss-loader/src/index.js):          
TypeError: getProcessedPlugins is not a function

Solutions provided in https://github.com/tailwindlabs/tailwindcss/issues/2810 or here: https://tailwindcss.com/docs/installation#post-css-7-compatibility-build do not work when using services like Netlify to build and deploy a project.

Any suggestions or solutions on how to make this work?

I'm using gridsome if that matters, basically a nuxt-like static content generator.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Is this issue only occurring when you are pushing it to those services like Netlify? Or does it also occur locally?
That being said, make sure that you are using `Node 12.13` or higher both locally and on Netlify: https://tailwindcss.com/docs/upgrading-to-v2#upgrade-to-node-js-12-13-or-higher

**Comment by marcodeluca** [comment]
Thanks for the quick reply, I just came back to update the issue with a solution as well. Upgrading node resolves the issue locally, and netlify makes it pretty easy to do the same. 

In the deploy settings, you can set environment variables, so using NODE_VERSION=v12.13.1 resolves this issue.

**Comment by semyin** [comment]
凭什么让人家升级node版本？生产环境说改版本就改？
