### ISSUE TITLE
Vue's Vite not working with Tailwind v2

### ISSUE THREAD

**Issue by caneco** [tailwindlabs/tailwindcss#3041]
### Describe the problem:

It seams that Tailwind v2 does work well with VueJS Vite.

Even in a fresh install, I can boot a local server with **Vite** – by running the `npm run dev` command; but can't anymore as soon as I install Tailwind according to your docs:

I'm currently trying the code in a Mac with **Node v15.3.0** and **npm v6.14.8**

```bash
npm install tailwindcss postcss autoprefixer
```

### Link to a minimal reproduction:

https://github.com/caneco/tailwind-vite-bug

### A step-by-step to reproduce:

1. `npx create-vite-app testing-vite`
2. `cd testing-vite`
3. `npm install`
4. `npm run dev` – **this should work normally**
5. `ctrl+c`
6. `npm install tailwindcss postcss autoprefixer`
7. `npm run dev` – **this is where it fails** 😔

**Comment by adamwathan** [comment]
I recommend following our Vite-specific installation guide, you are missing some steps:

https://tailwindcss.com/docs/guides/vue-3-vite

Most important thing is you need to use the PostCSS 7 compatibility build, since Vite/Vue do not support PostCSS 8 yet.

**Comment by caneco** [comment]
I totally missed your compatibility build.

**That worked!**

Thanks

**Comment by 17biubiu** [comment]
it not work. the error is 
`Could not load path (imported by node_modules/postcss/lib/input.js): ENOENT: no such file or directory, open 'path'`

node version: v14.15.0
npm version: v6.14.8
