### ISSUE TITLE
‘Basic usage’ of purging removes pseudo-elements from modern-normalize

### ISSUE THREAD

**Issue by DavidOliver** [tailwindlabs/tailwindcss#3043]
Many thanks for making Tailwind available.

When purging is enabled as per [the basic usage in the documentation](https://tailwindcss.com/docs/optimizing-for-production#basic-usage), pseudo-element selectors such as `::-moz-focus-inner` are removed from the modern-normalize styles. (Selectors such as `[type='reset']` are also removed from modern-normalize styles, but I expect this is because no such elements exist in the content I'm feeding purge, and so probably makes sense.)

To avoid this, I'm using `layers: ['components', 'utilities']` in the purge config. [This ability to restrict purging is mentioned in the documentation](https://tailwindcss.com/docs/optimizing-for-production#purging-specific-layers), but the connection to preserving the reset is not made clear, which I expect means many users of Tailwind will be missing normalizing styles without realising.

Can/should the base layer be exempted from purging by default?

**Comment by AndrewPrifer** [comment]
Just ran into this as well with @tailwindcss/forms. I'm using Reakit, so `type="..."` is never explicitly in my code when using e.g. checkboxes. I think it would be appropriate to mention in the documentation that PurgeCSS also by default purges base styles, I imagine this is a common problem for people using unstyled component libraries with Tailwind.

**Comment by adamwathan** [comment]
Good catch, we'll look into coming up with a solution for this. I think ideally we should try to find a way to make PurgeCSS _only_ purge class selectors by default and not base elements or attribute selectors.

**Comment by TheEskhaton** [comment]
Hi All, 

Hopefully you don't mind I'm jumping in on this issue. 

Would a valid solution be the following- Instead of preserving only HTML elements here via the  `preserveHtmlElements`  flag: 
https://github.com/tailwindlabs/tailwindcss/blob/eac11cf57d4a98afd2d53725f5e63c5b01df7d06/src/lib/purgeUnusedStyles.js#L108-L116
You could keep the `preserveHtmlElements` config, but also include a default safelist of selectors which includes a Regex or multiple Regex-es that safelist pseudo-element selectors -  https://purgecss.com/safelisting.html#patterns
Users of the framework and plugins creators could still just add `safelist: []` to the PurgeCSS config.

**Comment by samtrion** [comment]
Is it perhaps an option to prepend the `preflight` after the purgeUnusedStyles?
Is not the most elegant solution, but would exclude the `preflight` from the purge process without exception.

**Comment by bjuppa** [comment]
For anyone in need of a quick fix, here's an example `tailwind.config.js` with a `safelist` option added to keep the pseudo element selectors starting with `:` from being purged:

```js
const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
    purge: {
        content: [
            './vendor/laravel/jetstream/**/*.blade.php',
            './storage/framework/views/*.php',
            './resources/views/**/*.blade.php',
        ],
        options: {
            safelist: [/^:/],
        },
    },

    // ...
}
```

Perhaps it'd make sense for Tailwind to add the pattern `/^:/`  by default to purgecss' `safelist` config?
If it is possible to push a regex onto the `preserved` list as @TheEskhaton suggested, I think that'd be great!

Here's the full list of selectors used in Tailwind you'd expect to be kept but are currently purged:

- `::-moz-focus-inner`
- `:-moz-focusring`
- `:-moz-ui-invalid`
- `::-webkit-inner-spin-button`+ `::-webkit-outer-spin-button`
- `::-webkit-search-decoration`
- `::-webkit-file-upload-button`
- `::-webkit-datetime-edit-fields-wrapper`
-  `::-webkit-date-and-time-value`

**Comment by Cummings14210** [comment]
Is it perhaps an option to prepend the preflight after the purgeUnusedStyles?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

In v3 we are not using PurgeCSS anymore, and any selector that is used that doesn't contain a class will be generated by default. E.g.: https://play.tailwindcss.com/ZnG4z0kalk?file=css

Going to close this, if any other issues occur with incorrectly removed pseudo-elements, then please open a new issue with a minimal reproduction repo or play link.

**Comment by DavidOliver** [comment]
Ah, that's great to hear. Thanks.
