### ISSUE TITLE
Font Family

### ISSUE THREAD

**Issue by sgentile** [tailwindlabs/tailwindcss#3047]
latest tailwind is apply fonts and overriding my applications fonts.   I do not want this behavior.

I set fontFamily to false and it is still happening ?

```
module.exports = {
    theme: {
        extend: {
            margin: {
                sm: '24px',
            },
        },
        fontFamily: false,
    },
    purge: [],
    darkMode: false, // or 'media' or 'class'
    variants: {},
    plugins: [],
};
```

**Comment by benji014628** [comment]
First put this above `module.exports`, `const defaultTheme = require('tailwindcss/defaultTheme');`
Then specify which font you want like this: 
`fontFamily: {
        sans: ['Poppins', ...defaultTheme.fontFamily.sans],
      },`

**Comment by RobinMalfait** [comment]
Hey! Thank you for your issue!
Much appreciated! 🙏

If you want to disable fontFamily generation make sure to disable the plugin altogether: https://tailwindcss.com/docs/font-family#disabling

```js
// tailwind.config.js
module.exports = {
  corePlugins: { // (*) Notice that you have to put this in the `corePlugins` section, and not in the `theme` section
    // ...
    fontFamily: false,
  }
}
```
