### ISSUE TITLE
All dark mode classes are purged

### ISSUE THREAD

**Issue by mattiaz9** [tailwindlabs/tailwindcss#3061]
### Describe the problem:

When I build the production style all the dark mode classes are removed. This happens with the utility classes, for instance `dark:text-gray-500`, but not when you create custom components with `@apply`.

I tried searching for any class that begins with `dark:` in the compiled stylesheet, but I couldn't find any.

My purge config is the following:
```
purge: {
  content: [
    "./public/**/*.html",
    "./src/app/**/*.js",
    "./src/components/**/*.js",
    "./src/pages/**/*.js",
  ],
}
```

I'm using 
- tailwindcss 2.0.1
- react-scripts 4.0.1
- @craco/craco 6.0.0

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you create a reproduction repository that you can share with us?
Also verify that if you are using `darkMode: "class"` that your code to toggle the `"dark"` class is also in one of the files listed in the `purge` list.

Example: https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually

**Comment by mattiaz9** [comment]
I couldn't really reproduce the issue, but I managed to fix it by being less specific in the purge config.
In particular instead of specifying all the folders in `src` containing react components, I specified the entire folder like so:
```
purge: {
  content: [
    "./public/**/*.html",
    "./src/**/*.js",
  ],
}
```
