### ISSUE TITLE
\32xl\ string in css file

### ISSUE THREAD

**Issue by GHNewbiee** [tailwindlabs/tailwindcss#3069]
### Describe the problem:
After building a css file I get

```css
@media (min-width: 1536px) {
  .\32xl\...
```
Is this normal? *Tia*

*"tailwindcss": "^2.0.1",*

**Comment by adamwathan** [comment]
Hey! Yes that's normal, classes can't start with a number so they need to be escape. That's just a `2xl:...` class. You'll see other similar escaping in selectors like `.hover\:bg-black:hover`.

I would recommend actually testing if there is a problem before opening an issue, you would see that the class actually works as expected 👍

**Comment by GHNewbiee** [comment]
Sorry, I was not aware that string `\3` is used for escaping digits in CSS. I could never imagine that, too! *Mea culpa!* I have always been avoiding using special characters trying to comply with safe coding practices. In case of `2xl`, I altered it by preference into `xxl`. Same number of characters and more familiar/natural due to clothing code.

I use `tailiwind CSS` via `JS` and I have to escape/transform/alter some special characters/strings. So what it works as plain CSS it may not work straight after JS-ification. Also debugging CSS, as JS-ified, is not very friendly and I need to go by trial and error due to lack of experience.

I have sent you in the past a message about <code>`</code> character, found 34 times if I remember correct, in the comments which creates a problem but you were not positive for altering it to a character which does not interfere with `JS`.

Anyway, thanks a lot for your response and sorry for any inconvenience.
