### ISSUE TITLE
[Feature proposal] Text shadow

### ISSUE THREAD

**Issue by d8vjork** [tailwindlabs/tailwindcss#307]
Hi there,

I think on a utility that add text shadow just like box shadow, it will be useful maybe if we want to write some text above a block with a background image.

**Comment by steveoh** [comment]
whats the status of this?

**Comment by roydebangshu** [comment]
@steveoh you can use [tailwindcss-textShadow](https://github.com/iunteq/tailwindcss-textShadow)  package.
