### ISSUE TITLE
Colors in main colors source file aren't working and aren't showing up in documentation

### ISSUE THREAD

**Issue by Christian-von-Uffel** [tailwindlabs/tailwindcss#3070]
### Describe the problem:

  Colors listed in the [main color.js file](https://github.com/tailwindlabs/tailwindcss/blob/master/colors.js) aren't loading when installing Tailwind 2.0 via CDN

### Link to a minimal reproduction:

 [Codepen - Color Palette Options Not Working in Default Template - Tailwind CSS 2.02]( https://codepen.io/cvonu/pen/yLaVGMZ)

<img width="1280" alt="Colors Not Showing Up in Documentation" src="https://user-images.githubusercontent.com/7927974/101943158-a00a8f80-3bb8-11eb-9cba-caf08c88e1a6.png">

**Comment by adamwathan** [comment]
Hey! Not every color is enabled by default. See the documentation on [customizing colors](https://tailwindcss.com/docs/customizing-colors), it explains the default palette and how the extended palette works.
