### ISSUE TITLE
Different gradient style on Safari to compare with Chrome

### ISSUE THREAD

**Issue by mossen** [tailwindlabs/tailwindcss#3071]
Please check this on Chrome and Safari.
https://play.tailwindcss.com/T33P50qJku?layout=horizontal

<img width="1184" alt="Screen Shot 2020-12-12 at 4 18 50 pm" src="https://user-images.githubusercontent.com/14992360/101976246-71171b00-3c97-11eb-8c0a-80de838dd894.png">

**Comment by adamwathan** [comment]
Hey! This is because of how Safari handles transparent gradients. Solution is to just remove "to-transparent", Tailwind will fade to transparent by default in an intelligent cross-browser way.

https://tailwindcss.com/docs/gradient-color-stops#starting-color
