### ISSUE TITLE
space-*-* & flex-*-reverse

### ISSUE THREAD

**Issue by rubybb** [tailwindlabs/tailwindcss#3078]
### Describe the problem:
`space-x-*` used with `flex-row-reverse` doesn't properly space as you'd expect it would.

### Link to a minimal reproduction:
https://play.tailwindcss.com/VDTZ7rAdIu

**Comment by Krutsch** [comment]
You also need to inverse the spacing in this case:
Try adding `space-x-reverse`

**Comment by simonswiss** [comment]
That's it - @Krutsch's answer is correct.

I will convert this to a GitHub discussion as some folks might find this one useful 👍
