### ISSUE TITLE
Tailwind 2.0 with Angular using ng-neat

### ISSUE THREAD

**Issue by MatthewLHolden** [tailwindlabs/tailwindcss#3085]
Hi Team,

I've just installed Tailwind 2.0 on my project and hit a number of errors. I've instead decided to create a new project from scratch to see if I can get it implemented into a fresh Angular project and work from there.

I created a new Angular project with the Angular CLI and then used `ng-neat` (https://github.com/ngneat/tailwind) to install the prerequisites to get going. The error received upon trying to build (`ng-serve`) is:

`Error: Cannot read property 'flags' of undefined`

Node is on version 14.15.1

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you create a reproduction repository that showcases the issue?

**Comment by MatthewLHolden** [comment]
Hi Robin - Thanks for the response. Seeing as the issue wasn't investigated yet, I updated the content of the issue so that it relates more closely to the reproduction repository i was trying to create here: https://github.com/MatthewLHolden/testing-ngneat

**Comment by hiepxanh** [comment]
You should open issues on ng-neat project instead, there is nothing here related with tailwind, I made an working repo with angular 11 and tailwind 2 by ng-neat/tailwind on here 

https://github.com/hiepxanh/ng-eleven-tailwind

**Comment by beeman** [comment]
> Hi Robin - Thanks for the response. Seeing as the issue wasn't investigated yet, I updated the content of the issue so that it relates more closely to the reproduction repository i was trying to create here: [MatthewLHolden/testing-ngneat](https://github.com/MatthewLHolden/testing-ngneat)
> 
> My actual live project is using ng-tailwindcss and i'm receiving different errors there. But I figured starting from the bottom might help pinpoint some issues :)

From looking at your reproduction, it looks like you're using Angular 9. If there is not a specific reason to use that version, I'd recommend using the latest version (Angular 11).

![image](https://user-images.githubusercontent.com/36491/102176024-901bd580-3e6e-11eb-8dcd-6d9fff692ade.png)

**Comment by MatthewLHolden** [comment]
> You should open issues on ng-neat project instead, there is nothing here related with tailwind, I made an working repo with angular 11 and tailwind 2 by ng-neat/tailwind on here
> 
> https://github.com/hiepxanh/ng-eleven-tailwind

Apologies. Thanks for the response. I should have emphasised it in the original post that I was using Angular 9 and ng-tailwindcss. That didn't work. I created a new project from scratch. That didn't work. Anything sub version 2 with tailwind worked fine. Everything else had errors on build time. Hence my response to Robin that I changed the original post to have something easier in the reproduction repo to investigate from the ground up, rather than include the 5 errors was actually getting. Thank you for providing your repo. I'll take a look now.

**Comment by MatthewLHolden** [comment]
> From looking at your reproduction, it looks like you're using Angular 9. If there is not a specific reason to use that version, I'd recommend using the latest version (Angular 11).

Thank you. A9 is what my production project is live on at the moment and I was hesitant about upgrading anything unnecessarily, especially if I'm not 100% sure it would resolve my errors with Tailwind. Do you think that's the cause here? If so, I'll try an update today 👍

**Comment by MatthewLHolden** [comment]
@RobinMalfait - The repo generated by @hiepxanh works (Thanks very much!), which is a great starting point for me (as all angular 9 ones failed from scratch). So feel free to close this issue and I'll work with that repo as a baseline for the project and try to figure out what went wrong. Thanks for the time and responses all, much appreciated.
