### ISSUE TITLE
Animations lack will-change directive

### ISSUE THREAD

**Issue by sergio-bravo** [tailwindlabs/tailwindcss#3086]
Hi,
I'm looking at https://tailwindcss.com/docs/animation and see no `will-change` directive on computed styles of an element

![image](https://user-images.githubusercontent.com/45559645/102083928-64c0c880-3e25-11eb-8f98-263af1a78df0.png)

I think animations should add `will-change` for smooth animations

**Comment by Krutsch** [comment]
> Important: will-change is intended to be used as a last resort, in order to try to deal with existing performance problems. It should not be used to anticipate performance problems. // https://developer.mozilla.org/en-US/docs/Web/CSS/will-change

Overusing it could in fact cause the page to be less performant. I think it should stay as it is

**Comment by adamwathan** [comment]
Hey! No plans to add this by default for the reasons mentioned above, can add it through your custom CSS for now if you are actually facing performance issues that this would solve.
