### ISSUE TITLE
Experimental features should be promoted to future

### ISSUE THREAD

**Issue by mgibas** [tailwindlabs/tailwindcss#3088]
With release of Tailwind 2.0 we know that most (all?) experimental features made it as a default so tailwind 1.X should promote them to future. It seems to be a logical step and we can suppress some unnecessary warnings during a build.

**Comment by adamwathan** [comment]
Not quite as simple as that, many of the experimental features changed slightly between what was in v1 and what's in v2. Recommendation is just upgrade to v2, we will not be releasing any new versions of v1.

**Comment by mgibas** [comment]
Understandable - locked to v1 for some time (IE11 support) so a bit of a bummer.
