### ISSUE TITLE
w-full triggers uncaught circular dependency

### ISSUE THREAD

**Issue by matt-dev2** [tailwindlabs/tailwindcss#3091]
### Description
Edit: Misleading title, might not be w-full specific. Sorry!

A circular dependency can be achieved using the following steps. [1] Create a generic HTML element applying a non-specific class name. [2] Using CSS, define that the element should now also `@apply w-full`. [3] Create a second CSS condition, using the non-specific class name and the newly applied w-full, and tell it to `@apply w-full`. The builder will now continue building until it runs out of RAM.

I came across this by accident after migrating to Tailwind 2 from my Tailwind 1 project. I followed the regular installation steps, as described by the official install documentation (https://tailwindcss.com/docs/installation). Using `npx tailwindcss init -p` and the compat build. 

**Image 1: normal circular dependency catching**
![circular1](https://user-images.githubusercontent.com/5623292/102147843-55607000-3e63-11eb-8249-91015c1e98bd.png)

**(Please be aware, the example is missing step [2])
Image 2: uncaught circular dependency injection. Eventually running out of RAM.**
![circular2](https://user-images.githubusercontent.com/5623292/102147847-572a3380-3e63-11eb-9e1b-ee97bbbec87c.png)

### Minimal reproduction
https://play.tailwindcss.com/h2jjqeCeQt?file=css

**Comment by adamwathan** [comment]
Thanks for this! Going to close and track circular dependency warning improvements in #2807 instead since that issue is older.
