### ISSUE TITLE
placeholder opacity is not supported by customize placeholder colors.

### ISSUE THREAD

**Issue by XShaoXin** [tailwindlabs/tailwindcss#3111]
### Describe the problem:
placeholder opacity is not supported by customize placeholder colors.

**Comment by XShaoXin** [comment]
![image](https://user-images.githubusercontent.com/46181284/102350093-53232080-3fdf-11eb-85c1-267b05998afe.png)

**Comment by XShaoXin** [comment]
"tailwindcss": "1.7.6"

**Comment by adamwathan** [comment]
Hey! I can't seem to reproduce this, it appears to work as expected in both 1.9.6 and 2.0.2:

https://play.tailwindcss.com/T3C7Unu20R
https://play.tailwindcss.com/OLVIgoGjmQ

So going to close this. If you are still having this issue after updating to the latest version, please open a new issue and include a reproduction.
