### ISSUE TITLE
Ring opacity is lost when setting colors with custom properties

### ISSUE THREAD

**Issue by tonifisler** [tailwindlabs/tailwindcss#3133]
### Describe the problem:

When setting theme colors with custom properties in the config, ring opacity is lost. 

```js
module.exports = {
  theme: {
    extend: {
      colors: {
        primary: {
          500: 'var(--color-primary-500)',
        },
      },
    },
  }
}
```

```html
<input type="text" class="ring ring-primary-500 ring-opacity-25" />
```

### Link to a minimal reproduction:

https://play.tailwindcss.com/NImz3J0nKE

**Comment by adamwathan** [comment]
Hey! This is a known limitation, you'll have to define your CSS variable based colors differently if you want them to work with any of the opacity utilities.

Here's a demo repo that explains what you need to do:

https://github.com/adamwathan/tailwind-css-variable-text-opacity-demo
