### ISSUE TITLE
Read only variant

### ISSUE THREAD

**Issue by weaversam8** [tailwindlabs/tailwindcss#3136]
There's currently no variant for `<input>` elements with the `readonly` attribute. I added this myself today following the [variant plugin documentation](https://tailwindcss.com/docs/plugins#adding-variants), but wanted to check whether this would be a good inclusion to the framework as a variant users can turn on.

Thoughts? If it's a good fit, I can probably do a PR relatively quickly.

**Comment by adamwathan** [comment]
Hey! No concrete plans to add this but since we already have `disabled` I suppose there's no reason to close a PR for it, especially since it would be disabled by default. Feel free to open a PR for it if you like 👍🏻 Closing this though as we only use issues for bug reports.

**Comment by TheCatLady** [comment]
@weaversam8 Are you still willing to submit a PR to add the `readonly` variant?  I would personally love to see this!

**Comment by weaversam8** [comment]
@TheCatLady - I actually no longer have the bandwidth to do this PR right now, sorry 😢 

If anyone else wants to tackle this, it probably isn't too hard. Some reference PRs you can take a look at are #3298, #2385, and #1824.

**Comment by jhubbardsf** [comment]
Still an issue. Might tackle it this weekend if nothing else is pressing.

**Comment by RobinMalfait** [comment]
@jhubbardsf we have a read-only variant: https://tailwindcss.com/docs/hover-focus-and-other-states#read-only

**Comment by jhubbardsf** [comment]
Oh, my bad. I was on a work call while reading through this and completely missed it. Figured out the issue was something else in the app now that I see this. Thanks.
