### ISSUE TITLE
Some selectors from tailwindcss kills postcss-csso parser with error "Unexpected input"

### ISSUE THREAD

**Issue by Semdevmaster** [tailwindlabs/tailwindcss#3141]
### Describe the problem:

Example selector:
`.sm\:focus-within\:text-opacity-5:focus-within{}`
Get in the console:
SyntaxError: Unexpected input
at Object.error (.........\node_modules\css-tree\lib\parser\create.js:240:19)

### Link to a minimal reproduction:

 1)default config tailwindcss (use only utilities)
 2)add postcss plugin "postcss-csso" in postcss.config.js
 3)get many errors in console

**Comment by adamwathan** [comment]
Hey! Does this same error happen if you just write that selector by hand without using Tailwind at all? If so this is an issue for for postcss-csso rather than Tailwind since that selector is perfectly valid CSS.

**Comment by Semdevmaster** [comment]
Hmm, without using Tailwind work fine!
I wrote to the plugin author about the problem. Hopefully he will release an update soon. Thank you for your feedback.

**Comment by adamwathan** [comment]
So if you write this exact CSS in a custom CSS file but don't install Tailwind it has no problem parsing it?

```css
.sm\:focus-within\:text-opacity-5:focus-within{}
```

**Comment by Semdevmaster** [comment]
Yes, at first I thought that the problem was in tilewindcss, but then I checked this selector in a clean file and all browsers worked correctly without problems. I temporarily removed all references to the focus-within property in the tailwind configuration file and it helped, the parser of postcss-csso does not see errors and works correctly, as before.

**Comment by adamwathan** [comment]
Ok thanks for the info! If I'm understanding correctly it's been verified that this is something that can only be resolved by postcss-csso rather than by us, so going to close.
