### ISSUE TITLE
Broken CSS output when using `config()` for adding new styles

### ISSUE THREAD

**Issue by KarthikeyanRanasthala** [tailwindlabs/tailwindcss#3145]
### Describe the problem:

When trying to add new styles to the `base` layer by using `config` function, the output of `config('theme.fontSize.5xl')` is of structure `['3rem', { line-height: '1' }]`. So when following [this](https://tailwindcss.com/docs/plugins#adding-base-styles), the resulting output css for `5xl` has `font-size:3rem; font-size:[object Object]`. The `line-height` property is not getting added.

### Link to a minimal reproduction:

https://github.com/KarthikeyanRanasthala/tw-extend-issue

You can inspect the `h1` element to see the `font-size:[object Object]`

**Comment by adamwathan** [comment]
Ah good catch, this should be written like this:

```
theme('fontSize.5xl')
```

The `theme` function is smarter about the value it returns, whereas `config` just returns the raw value. I've updated all of the references in the documentation to correct this 👍🏻
