### ISSUE TITLE
By default, the full color palette is not built, and there is a dearth of documentation code available

### ISSUE THREAD

**Issue by sebmellen** [tailwindlabs/tailwindcss#3178]
### Problem

The full range of colors in Tailwind 2.0 are not usable by default. When attempting to use colors like "teal" or "cyan", nothing shows up! I **do** understand that this is for a reason, given that the bundle size grows drastically as colors are added.

However, this arrangement causes significant confusion. Even _after_ reading through the color palette documentation on the website, and adding all the colors manually _**(a very tedious process)**_, the palette is not complete. This is because the `transparent`, `current`, `black`, and `white` "colors" are not included in the "color palette reference" code snippet available here: https://tailwindcss.com/docs/customizing-colors#color-palette-reference.

### Fix

I propose that you include a code snippet in the documentation with the full color palette reference available to copy and paste. 

I made a Gist which includes all the colors, which is available here: https://gist.github.com/sebmellen/e939ce8a29fd6cb611ef6f283f700f2c. 

If you simply copy and paste that code into the color palette documentation on the website, I believe you'll save a lot of peoples' time! 

Thanks :)

**Comment by adamwathan** [comment]
Hey! We don't want to encourage people to enable all colors, so I don't think I'd like to include this example in the documentation. Agree on the transparent/current/black/white stuff, we are exploring ways to make that easier to not forget.

Either way this belongs on the [tailwindlabs/tailwindcss.com](https://github.com/tailwindlabs/tailwindcss.com) repository, so going to close here.

**Comment by sebmellen** [comment]
Got it. Thanks, and sorry about using the wrong repo!
