### ISSUE TITLE
Dark variants are being purged by default even when dark mode is turned on

### ISSUE THREAD

**Issue by iamajvillalobos** [tailwindlabs/tailwindcss#3201]
### Describe the problem:

I enabled the `darkMode` in the tailwind config

```
darkMode: "class"
```

But when I deployed it to prod it's not working. I had to add this bit:

```
options: {
  safelist: ["dark"],
},
```

This wasn't in the documentation or might be I missed it? Or maybe this was really the intended behaviour.

### Link to a minimal reproduction:

1. Clone https://github.com/iamajvillalobos/personal-website/tree/dark-mode-not-working
2. npm install
3. NODE_ENV=production ember s

**Comment by adamwathan** [comment]
Hey! It sounds like you aren't including the file that toggles the "dark" class in your list of source templates you pass to PurgeCSS. What file is doing the toggling and what does the array of paths look like that you are passing to purge?

![image](https://user-images.githubusercontent.com/4323180/103170034-16d99680-480f-11eb-9348-0de238d4b8be.jpeg)

**Comment by adamwathan** [comment]
Just looked at the reproduction, you need to make sure you pass ALL files that reference CSS classes to PurgeCSS, including this one for example:

https://github.com/iamajvillalobos/personal-website/blob/dark-mode-not-working/app/components/toggle-night.js

PurgeCSS will remove any CSS it doesn't think is used, and if it doesn't see the word "dark" anywhere, it'll think you aren't using any of those classes 👍🏻

**Comment by iamajvillalobos** [comment]
Thanks @adamwathan, it's working properly now 👍
