### ISSUE TITLE
TailwindCSS - Purge Keyframes not supported

### ISSUE THREAD

**Issue by samtrion** [tailwindlabs/tailwindcss#3234]
When we use the following `tailwind.config.js`, no keyframes are removed...

```js
module.exports = {
    purge: {
        enabled: true,
        keyframes: true,
        content: ["./**/*.cshtml", "./**/*.html", "./**/*.razor"]
    }
};
```
If we use the same configuration within `postcss.config.js` for purgecss, the keyframes are removed, but so are all the html tags.

```json
{
  // Unnecessary information removed
  "devDependencies": {
    "autoprefixer": "^10.1.0",
    "gulp": "^4.0.2",
    "gulp-cli": "^2.3.0",
    "gulp-clone": "^2.0.1",
    "gulp-cssnano": "^2.1.3",
    "gulp-notify": "^3.2.0",
    "gulp-plumber": "^1.2.1",
    "gulp-postcss": "^9.0.0",
    "gulp-rename": "^2.0.0",
    "gulp-sourcemaps": "^3.0.0",
    "merge-stream": "^2.0.0",
    "postcss-focus": "^5.0.1",
    "postcss-import": "^14.0.0",
    "postcss-mixins": "^7.0.2",
    "postcss-sort-media-queries": "^2.3.17",
    "precss": "^4.0.0",
    "purgecss": "^3.1.3",
    "tailwindcss": "^2.0.2"
  },
  "peerDependencies": {
    "postcss": "^8.2.2"
  }
}
```

**Comment by adamwathan** [comment]
Hey! Your configuration is close is a tiny bit incorrect, needs to look like this:

```js
module.exports = {
    purge: {
        enabled: true,
        content: ["./**/*.cshtml", "./**/*.html", "./**/*.razor"],
        options: {
          keyframes: true,
        }
    }
};
```

Top-level options under "purge" are Tailwind's purge API, and any raw options you want to pass directly to PurgeCSS have to go under `options` 👍 Hope that helps!

**Comment by samtrion** [comment]
Oh man, found the [documentation ](https://tailwindcss.com/docs/optimizing-for-production#purge-css-options) about this.

Can you possibly expand the example here to make it a little more obvious?
A bit annoying because we have about 20 keyframes grinding along all the time.

**Comment by adamwathan** [comment]
Added a few more examples to hopefully make it more obvious, will be live after the deploy it done:

![image](https://user-images.githubusercontent.com/4323180/103411803-ef046e80-4b3f-11eb-99f0-bf322753033a.png)

**Comment by arashHasanzade** [comment]
> Hey! Your configuration is close but a tiny bit incorrect, needs to look like this:
> 
> ```js
> module.exports = {
>     purge: {
>         enabled: true,
>         content: ["./**/*.cshtml", "./**/*.html", "./**/*.razor"],
>         options: {
>           keyframes: true,
>         }
>     }
> };
> ```
> 
> Top-level options under "purge" are Tailwind's purge API, and any raw options you want to pass directly to PurgeCSS have to go under `options` 👍 Hope that helps!

Options for purge removed in version 3 and Keyframes not purged.
