### ISSUE TITLE
Custom container max-width doesn't work with custom container padding

### ISSUE THREAD

**Issue by mollerjorge** [tailwindlabs/tailwindcss#3235]
### Describe the problem:

When adding a custom container max-width and a custom horizontal padding for the container component, the custom padding is not taking effect for small and medium breakpoints. Tailwind picks up the default 1rem padding and also the lg padding but not the ones in the sm and md breakpoints.

When removing the screen key under the container object, it works just fine.

Here is a copy of the configuration file:

```
module.exports = {
  theme: {
    extend: {
      container: {
        center: true,
        padding: {
          DEFAULT: '1rem',
          sm: '1.5rem',
          md: '2rem',
          lg: '2.5rem',
        },
        screens: {
          lg: '1152px',
        },
      },
    },
  },
  variants: {},
  plugins: [],
}
```

### Link to a minimal reproduction:

https://play.tailwindcss.com/Xf59pTHKlm?file=config

**Comment by script-shop** [comment]
`screens: {
  lg: '1152px',
},`

cannot be within container or any other component for that matter
The below code works for me

`screens: {
  lg: '1152px',
},
container: {
  center: true,
  padding: {
    DEFAULT: '1rem',
    sm: '1.5rem',
    md: '2rem',
    lg: '2.5rem',
  },
},`

**Comment by mollerjorge** [comment]
I actually based my example on this 👉 https://github.com/tailwindlabs/tailwindcss/issues/1102#issuecomment-663754366

What I tried to achieve was to have both the max-width of the container and also de horizontal padding customized on each breakpoint.

If I move the screens key outside the container object, it changes the lg breakpoint to be 1152px instead of tailwinds default. I don't want to have that changed.

**Comment by script-shop** [comment]
Oh I see, now I have a better understanding.

**See this:**
[https://play.tailwindcss.com/fnKBh8Vs8n?file=config](url)

**Comment by RealChrisSean** [comment]
This is interesting I'll look into this.

**Comment by Haskins0202** [comment]
Use containers to keep your content centered and legible. Custom-width containers you want a wider container instead of the default maximum width (940 pixels). You can adjust the padding to give some nice breathing room.

**Comment by ncla** [comment]
Ran into this issue as well. 

tailwind.config.js

```
    container: {
      screens: {
        'sm': '100%',
        'md': '100%',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1580px'
      },
      padding: {
        DEFAULT: '0.875rem',
        sm: '1.125rem',
        md: '1.125rem',
        lg: '0.625rem',
        xl: '0.625rem',
        '2xl': '0.625rem',
      },
    },
```

For now I am using such LIDL workaround. Hooking into with `@layer` did not work as I wanted because the breakpoints have to be in ascending order with the min-widths. min-width and max-width is needed to not override other media queries for `.container`.

```
.container {
    @media (min-width: theme('screens.sm')) and (max-width: calc(theme('screens.md') - 1px)) {
        padding-left: theme('container.padding.sm');
        padding-right: theme('container.padding.sm');
    }

    @media (min-width: theme('screens.md')) and (max-width: calc(theme('screens.lg') - 1px)) {
        padding-left: theme('container.padding.md');
        padding-right: theme('container.padding.md');
    }
}
```

**Comment by stoplion** [comment]
Is there an official recommended way to do this? I'm seeing all kinds of different ways to do it on the interwebs. So far, none work

**Comment by stoplion** [comment]
Is there an official recommended way to do this? I'm seeing all kinds of different ways to do it on the interwebs. So far, none work

**Comment by adarsh4d** [comment]
Same issue, any alternate method??

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The `extend` doesn't work recursively, so when you override the nested `screens` property then you also have to make sure to spread in the "old" screens:

https://play.tailwindcss.com/IFgKBIpmuy?file=config

**Comment by ogheneovo12** [comment]
> Hey! Thank you for your bug report! Much appreciated! 🙏
> 
> The `extend` doesn't work recursively, so when you override the nested `screens` property then you also have to make sure to spread in the "old" screens:
> 
> https://play.tailwindcss.com/IFgKBIpmuy?file=config

this doesn't work for specifying width value of 100%, it ignores it

**Comment by mcamprecios** [comment]
Same here... following.

**Comment by jorgemasta** [comment]
Could we reopen this issue? 
It's still an issue. 
```
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem", // equivalent to px-4
        sm: "1.5rem", // equivalent to sm:px-6
        lg: "2rem", // equivalent to lg:px-8
      },
      screens: {
        "2xl": "1400px",
      },
    },
  ```
