### ISSUE TITLE
Way to define height for divide-x?

### ISSUE THREAD

**Issue by shivapoudel** [tailwindlabs/tailwindcss#3250]
Is there any way to maintain height for the `divide-x`. I wanted this to act as a button separator but also wanted to make it smaller in height too. How can I achieve this?

**Comment by adamwathan** [comment]
Hey! Issues are for bugs not for questions, please use our discussions forum for these sorts of things instead.

You can change the thickness of dividers using the divide width utilities:

https://tailwindcss.com/docs/divide-width
