### ISSUE TITLE
Solve the PostCSS plugin postcss-import not working when @import is placed inside a layer?

### ISSUE THREAD

**Issue by gremo** [tailwindlabs/tailwindcss#3257]
I've read [the documentation](https://tailwindcss.com/docs/using-with-preprocessors) and I know that:

> One important thing to note about postcss-import is that it strictly adheres to the CSS spec and disallows @import statements anywhere except at the very top of a file.

Is there any way to make it work with Tailwind CSS but inside a `@layer`? The reason is quite simple: **I'd like to purge only some external CSS placed inside `@layer`**, while keeping the top-level `@import` untouched.

1. I know I can set `mode: all` and move all `@import` at top-level, but this will purge the entire CSS, not something that I want. 
2. Most of the time, purging all stuff will break something, even if you point the `content` option to the right resources like JavaScript files
3. Another solution would be a custom function (how to implement it?) that just place the content of the CSS inside that layer, before Tailwind CSS do it's stuff. A plain copy & paste would work, I suppose.

Example configuration to better understand the issue:

```css
/** External imports (not purged) */
@import '@glidejs/glide/dist/css/glide.core.css';
@import '@glidejs/glide/dist/css/glide.theme.css';

@tailwind base;
@tailwind components;
@tailwind utilities;

/* Custom base styles */
@layer base {}

/* Custom components */
@layer components {
  /* Warning! this will not work, as @import doesn't work inside @layer */
  @import '@fortawesome/fontawesome-free/css/all.css';
}

/* Custom utilities */
@layer utilities {}

@import '@fortawesome/fontawesome-free/css/all.css';

```

**Comment by adamwathan** [comment]
Unfortunately nothing we can do here, `postcss-import` has to be the first plugin in your list so `@import` has to be used in a way that is compatible with that plugin (top of the file, not nested).

Your best bet is to probably use PurgeCSS's ignore comment syntax to mark when you want it to skip stuff:

https://purgecss.com/safelisting.html#in-the-css-directly

**Comment by Dozorengel** [comment]
Now I needed to insert some classes inside a `@layer` and `@responsive` to create responsive variants. I wanted to import all my classes from my custom files via `@import` to make them all responsive as well. But unfortunately I couldn't do that because of this incompatibility :( So, I had to copy-paste some classes and not import them.

**Comment by trusktr** [comment]
Where is `@layer` coming from? That's a new CSS spec that just came out, right? Is there a postcss plugin for that?

**Comment by Rasaf-Ibrahim** [comment]
### You can't @import inside a @layer but you can use @layer in a separate file and @import that. 

&nbsp;


#### **Example -** 

&nbsp;

```css

/* tailwind.css */

@import './button.css';
@import './scaling.css';



@tailwind base;
@tailwind components;
@tailwind utilities;


```

&nbsp;


```css

/* button.css */

@layer utilities {



.btn{
    @apply 
    cursor-pointer shadow hover:shadow-md outline-none focus:outline-none rounded
    py-2 px-4 text-center
    uppercase font-semibold
    transition ease-out
    duration-300;
 }


}

```

&nbsp;

```css

/* scaling.css */


@layer utilities {


.btn-scale-down{
    @apply
    transform
    active:scale-95;
    
}

.btn-scale-up{
    @apply
    transform
    active:scale-105;
    
 }

}

```
