### ISSUE TITLE
Has the api changed for extending backgroundImage in the tailwind.config.js file?

### ISSUE THREAD

**Issue by NiQ-B** [tailwindlabs/tailwindcss#3271]
### Describe the problem:
This code works in v1.9.6 but fails in 2.0.2 on tailwind play. 

### Link to a minimal reproduction: Just change the software release.

https://play.tailwindcss.com/0tuG4mv5X6

-->

**Comment by martinmilani** [comment]
Confirm not working on 2.0.2 on tailwind play or local environment

**Comment by aggreggator** [comment]
The CSS property got renamed in v2:
old: `--gradient-color-stops`
new: `--tw-gradient-stops`

Working example: https://play.tailwindcss.com/Ffo1y4ImPC?file=config

**Comment by adamwathan** [comment]
Yep @aggreggator nailed it, we namespaced all of our internal CSS variables in 2.0 to avoid accidental collisions with user code 👍🏻
