### ISSUE TITLE
Sharing Tailwind components in a monorepo

### ISSUE THREAD

**Issue by AlexBHarley** [tailwindlabs/tailwindcss#3277]
First of all thanks for the great tool. This is a report that something is not working right, but also a question on how you recommend to do this kind of thing. There are many tools at play here so hopefully you can point me in the right direction.

### Describe the problem:

I have a monorepo like this:

```
packages/
  app-1/
  app-2/
  ui/
```

My apps are a combination of create-react-app and Next.js, but for now I just want to get my demo working with two create-react-app applications.

Ideally I'd be able to have a `ui/common.css` file that I can import into my applications:

```
@import '@tailwind-test/ui/common.css';

/* ./src/index.css */
@tailwind base;
@tailwind components;
@tailwind utilities;
```

but that doesn't work. Additionally I'd like to be able to import components (e.g. `ui/button.tsx`) and have the Tailwind classes still autogenerated. ie. `ui/button.tsx` uses `bg-blue-500` and that CSS class is still generated in the application.

### Link to a minimal reproduction:

https://github.com/AlexBHarley/tailwind-shared-components-demo.

Right now I can't even get `@import` to work so I'm copy pasting my `common.css` file into the `tailwind.css` file of each of my three applications.

To run:

1. `yarn`
2. `yarn lerna bootstrap`
3. `yarn lerna run start --stream`

**Comment by TheBoringDude** [comment]
You should use `postcss-import`...
Since you are using the PostCSS7, install the `postcss-import@12`.

Then do this in your `.css` file where you import Tailwind's components.
```
/* ./src/index.css */
@import 'tailwindcss/base';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';

@import '@tailwind-test/ui/common.css';
```

**Comment by MaxChu23** [comment]
@AlexBHarley did you ever solve this? I'm having the same goal now.

**Comment by AlexBHarley** [comment]
@MaxChu23 unfortunately not + I'm no longer maintaining that project. However there are Tailwind wizards out there who can certainly help you.

**Comment by ANTARES-KOR** [comment]
One Solution is, to elaborate all file paths which uses tailwind in the tailwind.config.js

for example, if package structure is like this
```
packages
|--ui : @something/ui
app
```
and if you want to import component from your app project
tailwind.config.js should be somewhat like this :
```javascript
module.exports = {
  content: [
    "../packages/ui/**/*.{js,ts,jsx,tsx}"
    ...
  ],
  ...
}
```
I hope this might help someone.

**Comment by Manubi** [comment]
@ANTARES-KOR Can you elaborate a little bit please. I am new to monorepos.

My question is, if I have a ui package that uses tailwind, do I need to install tailwind in my app as well in order to use it? My idea would just be to import the /ui/button component and I should be able to use it in my app/vite_frontend/component without needing to install tailwind. Thanks!

**Comment by max-sym** [comment]
@Manubi I didn't find any way other than installing tailwind separately in each project that uses UI package, but having only the code in the UI package + tailwind configuration file. So would be something like this:

```
packages
  landing-page
    src
      index.js
  ui
    src
      button.js
    package.json
    tailwindcss.config.js
package.json
```

And then `landing-page` would have tailwindcss in it, but it would use the config from ui.
This is useful when there's, let's say another landing page that is supposed to use the same config as the first landing page.

The drawback is that we'd have to install tailwind in both of them. Your ui tailwindcss config file would have the base and the tailwindcss configs in the other packages can be defined as:

```js
const baseConfig = require("../ui/tailwind.config")

module.exports = {
  ...baseConfig,
  content: ["./src/**/*.{js,jsx,ts,tsx}", "../ui/src/**/*.{js,jsx,ts,tsx}"],
  plugins: [],
}
```

And then import the components from the ui as:

```jsx
import {Button} from "@my-app/ui"

const Page = () => (
  <Button> {"Hello"}</Button>
)
...
```

This worked perfectly for me.

**Comment by ANTARES-KOR** [comment]
> @ANTARES-KOR Can you elaborate a little bit please. I am new to monorepos.
> 
> My question is, if I have a ui package that uses tailwind, do I need to install tailwind in my app as well in order to use it? My idea would just be to import the /ui/button component and I should be able to use it in my app/vite_frontend/component without needing to install tailwind. Thanks!

Yes. you should install tailwind in your app. ( assuming that you are importing your ui package's code without build process)

Since ui component written with tailwind is just a piece of code with tailwind utility class in classNames, app needs tailwind to interpret those utility classes.

I think if you want to use your ui package without tailwind installed in your app, you should build your ui package and import the bundles generated from it.

**Comment by gtnbssn** [comment]
If i am not mistaken the solutions given here mean classes used in some components of the ui, but not in a given project, will end up in the css of that project (since tailwind is watching all the components of the ui). Maybe that is an acceptable compromise to make. Or is there a smarter solution?

**Comment by Manubi** [comment]
How I have it right now - and I am quiet happy with it - is like this:
I have a `packages/ui` where I have tailwind installed and also storybook and vitest. I use css-variables `color-primary` that I add in my `packages/ui/tailwindconfig.css` which changes the color in every project.
