### ISSUE TITLE
Minification affected when @apply is put on separate lines

### ISSUE THREAD

**Issue by rightaway** [tailwindlabs/tailwindcss#3287]
### Describe the problem:

`@apply py-2 px-4;` gets minimized to `padding:.4rem .8rem;` as expected.

But the following remains `padding-left:.4rem; padding-right:.4rem....` after minification in tailwind 2. Not sure why it's doing this because the minification in webpack happens after tailwind does its thing, so it shouldn't be having an effect.

```
@apply px-2;
@apply px-4;
```

Would be good if it worked the same way because for the purpose of git diffs it's cleaner to put each rule on its own line.

**Comment by adamwathan** [comment]
Can you create a simple project that reproduces the issue? We got a lot of issues that require me to manually recreate someone's project from scratch and I unfortunately just don't have time for that so things end up going unfixed. If you can provide something I can clone and start troubleshooting with right away it's much easier for me to find time to diagnose and fix the issue.

**Comment by adamwathan** [comment]
Closing as no reproduction has been provided and we've demonstrated things working as expected. Feel free to open another issue that includes a reproduction if you are still having problems with this.
