### ISSUE TITLE
Purgecss not removing cursor-move

### ISSUE THREAD

**Issue by rightaway** [tailwindlabs/tailwindcss#3288]
### Describe the problem:

I haven't used `cursor-move` anywhere in my html but all these are generated in the final bundle output. Looks like wrong defaultExtractor used for purgecss.

```
@media (min-width:640px) {
    .sm\:cursor-move,
    .sm\:disabled\:cursor-move:disabled {
        cursor: move;
    }
}
@media (min-width:768px) {
    .md\:cursor-move,
    .md\:disabled\:cursor-move:disabled {
        cursor: move;
    }
}
@media (min-width:1024px) {
    .lg\:cursor-move,
    .lg\:disabled\:cursor-move:disabled {
        cursor: move;
    }
}
@media (min-width:1280px) {
    .xl\:cursor-move,
    .xl\:disabled\:cursor-move:disabled {
        cursor: move;
    }
}
@media (min-width:1536px) {
    .\32xl\:cursor-move,
    .\32xl\:disabled\:cursor-move:disabled {
        cursor: move;
    }
}
```

**Comment by adamwathan** [comment]
Hey! Can you please create a simple project that reproduces the issue?

**Comment by rightaway** [comment]
Was a problem with my `safelist`, because I added `/move$/` pattern due to vue list transitions. Is it possible for a pattern to add everything except `cursor-move` to safelist?

**Comment by adamwathan** [comment]
Should be able to do it with regular regex stuff, something like this:

`/(?<!cursor-)move$/`
