### ISSUE TITLE
input text `placeholder-opacity-100` in Firefox looks lighter

### ISSUE THREAD

**Issue by rockmandash** [tailwindlabs/tailwindcss#3300]
### Describe the problem:

Firefox default makes `<input />` placeholder looks lighter, Tailwind class can't reset this behavior.

I know this is the browser default style, however, since people are explicitly saying `placeholder-opacity-100`, I think it should override those default style

### Link to a minimal reproduction:

[Link to Tailwind Play](https://play.tailwindcss.com/rywvxI2MAo)

#### Code

```html
<input
  class="w-full placeholder-red-500 placeholder-opacity-100"
  placeholder="I will look lighter in Firefox"
/>
```

#### Chrome Screenshot

![image](https://user-images.githubusercontent.com/7580792/103854138-b853c880-50ea-11eb-9077-f2409028c5b4.png)

#### Firefox Screenshot

![image](https://user-images.githubusercontent.com/7580792/103854162-c6094e00-50ea-11eb-91cd-2d83ab475ee1.png)

**Comment by adamwathan** [comment]
Fixed here, will probably tag a new release tomorrow:  https://github.com/tailwindlabs/tailwindcss/pull/3308
