### ISSUE TITLE
Incorrect creation of media queries

### ISSUE THREAD

**Issue by samtrion** [tailwindlabs/tailwindcss#3304]
On a whim, I played around a bit with creating media queries today. In doing so, I noticed some unattractive results, such as using `min` and `min-width` at the same time results in `(min-width: 640px) and (min-width: 640px)`. Here I would expect a cleanup of the string so that `(min-width: 640px)` is the result.

This error came from me deleting a second viewport here uncleanly.

```js
// tailwind.config.js
module.exports = {
  theme: {
    screens: {
      'md': {
        'min': '640px',
        'min-width': '640px'
      }
    },
  }
}
```

**Comment by adamwathan** [comment]
Hey! I don't really consider this a bug, it's invalid input so the output is really just undefined behavior. If you supply valid input it's not a problem, and even the output that's generated here is "correct" and functions properly.

Going to close but appreciate you sharing 👍🏻
