### ISSUE TITLE
Error: Expected an opening square bracket.

### ISSUE THREAD

**Issue by robksawyer** [tailwindlabs/tailwindcss#3314]
### Describe the problem:

The following tailwind config is being generated with the following and this is not allowing NextJS app to compile.

```
variants: {
    extend: [],
  },
```

It seems to possibly need content inside of extends or just the following allows it to compile.
```
variants: [],
```

### Link to a minimal reproduction:

Just start a new NextJS app using the latest docs and install Tailwind as the documentation states.

Run the following commands:
```
 yarn run build
yarn run v1.22.10
$ next build

warn - Tailwind is not purging unused styles because no template paths have been provided.
warn - If you have manually configured PurgeCSS outside of Tailwind or are deliberately not removing unused styles, set `purge: false` in your Tailwind config file to silence this warning.
warn - https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css
info  - Creating an optimized production build  
Failed to compile.

Error: Expected an opening square bracket.


> Build error occurred
Error: > Build failed because of webpack errors

```

**Comment by AadilMehrajBhat** [comment]
@robksawyer Can you please share your `tailwind.config.js` config file?

**Comment by adamwathan** [comment]
You must have a syntax error in your config file, this definitely works. This is the default config file in the docs:

```js
module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
```

Notice that that is already different than what you have shared (extend is an object, not an array) so you have made some changes to the file that are causing it not to compile.

Happy to help if you share the file but going to close as there are no syntax errors in the default Tailwind config file.

**Comment by alexcroox** [comment]
I too got this error after updating the version of `npm:@tailwindcss/postcss7-compat@2.0.3`and `@tailwindcss/postcss7-compat` to the latest
