### ISSUE TITLE
version 2 @apply directive not work in vue component

### ISSUE THREAD

**Issue by ShekhSaifuddin007** [tailwindlabs/tailwindcss#3324]
### Describe the problem:
I'm working on a project and this build with laravel inertiajs-vue. inside my component, I try to shorten my class list by `@apply` directive but it not working and it doesn't through any error also. I don't what is the problem

### Component

```html
<li v-for="(contact, index) in contacts" :key="contact.id"
    @click="selectContact(index, contact)"
    class="contact-row"
    :class="{'selected' : index == selected}">
 <div class="avatar">
   <img :src="contact.profile_photo_path" :alt="contact.name">
 </div>
 <div class="contact-info">
    <p class="name">{{ contact.name }}</p>
    <p class="email">{{ contact.email }}</p>
 </div>
</li>
```

```css
<style scoped>
.contact-row {
    @apply flex
}
</style>
```

#### Inside the browser it showing like this

![apply](https://user-images.githubusercontent.com/48278861/104133063-5675b600-53ab-11eb-9565-ff2bb55197be.PNG)

How to solve this problem?

**Comment by adamwathan** [comment]
Likely this is because Vue is not actually processing the CSS with PostCSS. Can you share your webpack.mix.js file?

**Comment by ShekhSaifuddin007** [comment]
@adamwathan yes sure here is my `webpack.mix.js` file

```javascript
const mix = require('laravel-mix');

mix.js('resources/js/app.js', 'public/js').vue()
    .postCss('resources/css/app.css', 'public/css', [
        require('postcss-import'),
        require('tailwindcss'),
        require('autoprefixer'),
    ])
    .webpackConfig(require('./webpack.config'));

if (mix.inProduction()) {
    mix.version();
}

```

**Comment by ShekhSaifuddin007** [comment]
@adamwathan if want to use it like that inside my vue component, then what can I do? should I remove `postCss` ..?

**Comment by adamwathan** [comment]
Try this instead, it will apply PostCSS plugins globally (including Vue style blocks)

```js
const mix = require("laravel-mix");

mix.js("resources/js/app.js", "public/js").vue()
  .postCss("resources/css/app.css", "public/css")
  .options({
    postCss: [
      require("postcss-import"),
      require("tailwindcss"),
      require("autoprefixer"),
    ],
  })
  .webpackConfig(require("./webpack.config"));

if (mix.inProduction()) {
  mix.version();
}

```
