### ISSUE TITLE
Extend colors: Not generating background of custom colors when it generates the final CSS. 

### ISSUE THREAD

**Issue by DanielRiveraHQ** [tailwindlabs/tailwindcss#3334]
### Describe the problem:

We are having issues with the final build, not adding some background of custom colors on production. We can see it running perfectly in the development environment, but as soon as we push it to netlify/gatsby cloud and generates a build, some colors don't work. 

Here is an example:
https://reverehealthfrontendstaging.gtsb.io/contact-us/

In the hero section, you can see the class "bg-accent-green" is not doing anything, but you can check the small subtitle above the hero title with the class "text-accent-green" and it works. 

The same thing happens in the blog tiles almost at the bottom of this page:
https://reverehealthfrontendstaging.gtsb.io/home-template/

This happens only after running the final build purging the no needed classes.

We can give you access to our repo if needed to reproduce it. Here is the config file we use:

```javascript
// See https://tailwindcss.com/docs/configuration for details
module.exports = {
	purge: ["./src/**/*.js"],
	theme: {
		container: {
			center: true,
			padding: {
				DEFAULT: "2rem",
				sm: "2rem",
				md: "2rem",
				lg: "4.5rem",
				xl: "4.5rem",
				"2xl": "4.5rem",
			},
		},
		fontFamily: {
			display: ["proxima-nova", "sans-serif"],
			body: ["proxima-nova", "sans-serif"],
		},
		extend: {
			colors: {
				"plum-dark": "#763576",
				"plum-bright": "#8F408F",
				"black-base": "#333333",
				pewter: "#5E7479",
				flint: "#91A8AD",
				"footer-light": "#344A4F",
				"footer-dark": "#293F44",
				"accent-blue": "#00A9D1",
				"gray-border": "#DEE5E7",
				"gray-light-border": "#F1F5F5",
				silver: "#F1F5F5",
				"silver-outlines": "#DEE5E7",
				"accent-forest": "#58A589",
				"accent-pink": "#EA7979",
				"accent-peach": "#F8A589",
				"accent-green": "#A2C93D",
			},
			opacity: {
				"05": "0.05",
				10: "0.1",
				20: "0.2",
				95: "0.95",
			},
			spacing: {
				72: "18rem",
				84: "21rem",
				96: "24rem",
				108: "27rem",
				120: "30rem",
				132: "33rem",
				144: "36rem",
				156: "39rem",
			},
			// eslint-disable-next-line no-unused-vars
			backgroundImage: (theme) => ({
				"hero-pattern-accent-blue": "url('../images/decorations/hero-pattern-accent-blue.svg')",
				"hero-pattern-accent-green": "url('../images/decorations/hero-pattern-accent-green.svg')",
				"hero-pattern-accent-forest": "url('../images/decorations/hero-pattern-accent-forest.svg')",
				"hero-pattern-no-image-accent-green":
					"url('../images/decorations/hero-pattern-no-image-accent-green.svg')",
			}),
		},
	},
	variants: {
		display: ["responsive", "hover", "group-hover", "group-focus"],
		width: ["responsive", "hover", "focus", "group-hover", "group-focus"],
		opacity: ["responsive", "group-hover", "focus-within", "hover", "focus"],
	},
	future: {
		removeDeprecatedGapUtilities: true,
		purgeLayersByDefault: true,
		defaultLineHeights: true,
		standardFontWeights: true,
	},
	// plugins: [require("tailwindcss-debug-screens"), require("@tailwindcss/custom-forms")],
};
```

Thank you for your help!

**Comment by adamwathan** [comment]
Sounds like maybe you are using interpolation in your templates, make sure to read the rules of writing purgeable HTML:

https://tailwindcss.com/docs/optimizing-for-production#writing-purgeable-html

**Comment by DanielRiveraHQ** [comment]
Hey Adam, 

Thank you for your prompt answer, a fan of your work here!  I removed the string concatenation from my hero component and still ignoring that specific color within the module.  Here is how it currently looks:

Code of the hero component where we are implementing the variable color in the background and text:
https://share.getcloudapp.com/Z4uqRbqO

Code and preview of the hero component in action failing for a specific project color only for the "bg-accent-green" property, but working for the "text-accent-green" one:
Code: https://share.getcloudapp.com/8LunABdL
Preview: https://reverehealthfrontendstaging.gtsb.io/contact-us/

Code of the hero component in action working well for both properties:
Code: https://share.getcloudapp.com/jkuYGdJn
Preview: https://reverehealthfrontendstaging.gtsb.io/home-template/

Here is an extract of our package.json file in case you want to take a look:Hey Adam, 

Thank you for your prompt answer, a fan of your work here!  I removed the string concatenation from my hero component and still ignoring that specific color within the module.  Here is how it currently looks:

Code of the hero component where we are implementing the variable color in the background and text:
https://share.getcloudapp.com/Z4uqRbqO

Code and preview of the hero component in action failing for a specific project color only for the "bg-accent-green" property, but working for the "text-accent-green" one:
Code: https://share.getcloudapp.com/8LunABdL
Preview: https://reverehealthfrontendstaging.gtsb.io/contact-us/

Code of the hero component in action working well for both properties:
Code: https://share.getcloudapp.com/jkuYGdJn
Preview: https://reverehealthfrontendstaging.gtsb.io/home-template/

Here is an extract of our package.json file in case you want to take a look:
```
{
  "dependencies": {
    "add": "^2.0.6",
    "dotenv": "^8.2.0",
    "gatsby": "^2.30.1",
    "gatsby-image": "^2.9.0",
    "gatsby-plugin-algolia": "^0.16.2",
    "gatsby-plugin-image": "^0.5.0",
    "gatsby-plugin-local-search": "^2.0.0",
    "gatsby-plugin-manifest": "2.10.0",
    "gatsby-plugin-netlify-cache": "^1.2.0",
    "gatsby-plugin-offline": "3.8.0",
    "gatsby-plugin-postcss": "3.3.0",
    "gatsby-plugin-react-helmet": "3.8.0",
    "gatsby-plugin-root-import": "^2.0.5",
    "gatsby-plugin-sharp": "^2.12.0",
    "gatsby-plugin-sitemap": "^2.10.0",
    "gatsby-plugin-web-font-loader": "^1.0.4",
    "gatsby-source-filesystem": "^2.9.0",
    "gatsby-source-wordpress-experimental": "^6.2.0",
    "gatsby-transformer-sharp": "^2.10.0",
    "gatsby-wordpress-experimental-inline-images": "0.0.3",
    "google-map-react": "^2.1.9",
    "prop-types": "15.7.2",
    "react": "17.0.1",
    "react-accessible-accordion": "^3.3.3",
    "react-dom": "17.0.1",
    "react-helmet": "6.1.0",
    "react-minimal-pie-chart": "^8.1.0",
    "react-paginate": "^7.0.0",
    "react-scroll-parallax": "^2.3.5",
    "react-tabs": "^3.1.2"
  },

  "devDependencies": {
    "autoprefixer": "10.1.0",
    "babel-eslint": "10.1.0",
    "cssnano": "4.1.10",
    "eslint": "7.16.0",
    "eslint-loader": "4.0.2",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-react": "7.21.5",
    "gatsby-plugin-eslint": "2.0.8",
    "postcss": "8.2.1",
    "prettier": "2.2.1",
    "tailwindcss": "2.0.2"
  },

}
```

**Comment by adamwathan** [comment]
Yep so looking at this image the problem is that you are dynamically creating class names like I suspected:

https://share.getcloudapp.com/Z4uqRbqO

PurgeCSS doesn't know to keep classes like "bg-red-500" because that string doesn't appear in your code, only "bg-" appears. You need to make sure any classes you want PurgeCSS to keep appear as complete strings in your css, they cannot be dynamically concatenated. Re-read the docs link I posted before in detail and hopefully it will click 👍🏻

**Comment by adamwathan** [comment]
This blog post might also help explain it:

https://link.medium.com/wVI4XAXd1cb

**Comment by DanielRiveraHQ** [comment]
The way I solved this, is by adding the colors I'm adding dynamically with the safelist option from PurgeCSS, here is an example:

```
	purge: {
		content: ["./src/**/*.js"],

		// These options are passed through directly to PurgeCSS
		options: {
			safelist: {
				standard: [/accent-green$/, /accent-peach$/, /accent-forest$/, /accent-pink$/, /accent-blue$/],
			},
		},
	}
```
