### ISSUE TITLE
Using @apply on group-hover styles in a stylesheet doesn't work #3339

### ISSUE THREAD

**Issue by gedi-t** [tailwindlabs/tailwindcss#3340]
Hey all, I am new to Tailwind but I get my head around how it works as its pretty much straightforward, but today I got stuck on a simple issue. 
Initially what I'm trying to achieve is to create a tooltip and it works if I use the TW classes in HTML, but I want to clean my code and create classes using @apply.

**Working HTML**
```
<div class="group cursor-pointer relative inline-block text-center">**Some text or item**
  <div class="opacity-0 w-72 overflow-ellipsis flex-wrap bg-white text-grey-1000 text-center text-md rounded-lg py-2 absolute z-10 group-hover:opacity-100 bottom-full -left-1/2 ml-14 px-3 pointer-events-none shadow-lg transition duration-700 ease-in-out">
    **Tooltip text**
</div>
```

What I like to have the **Some text or item** to be just one class .tooltip-box and the **Tooltip text** tooltip popup to be .top-tooltip

Please tell me what I'm doing wrong 

```

.tooltip-box {
  @apply group cursor-pointer relative inline-block;
}

.top-tooltip {
  @apply opacity-0 w-72 overflow-ellipsis flex-wrap bg-white text-grey-1000 text-center text-base rounded-lg py-2 absolute z-10 bottom-full -left-1/2 ml-14 px-3 pointer-events-none shadow-lg transition duration-700 ease-in-out;
  &:hover {
    @apply group-hover:opacity-100; **I also tried to put this without  &:hover.. but no luck**
  }
}
```

**Comment by gcavanunez** [comment]
Hi,

text-md and text-grey-1000 by default in tailwind  2 aren't out of the box classes you can have.

I  noticed that the issue is in regard the class generation of how group and group-hover overall work 

here is a tailwind play reproduction, and simple work around 

https://play.tailwindcss.com/RmKtGJcNnW

**Comment by gedi-t** [comment]
> wind play reproduction, and simple workaround

Hey text-grey-1000 is my created class, for extra color, don't mind that. 

Thanks for the idea to put the group in HTML, but was hoping we don't need that, hope in the future  Tailwind will allow the group in @apply css

**Comment by adamwathan** [comment]
Hey! This has been asked before, check out the answer here:

https://github.com/tailwindlabs/tailwindcss/issues/2848#issuecomment-734523233
