### ISSUE TITLE
<progress> element broken

### ISSUE THREAD

**Issue by LostKobrakai** [tailwindlabs/tailwindcss#3357]
### Describe the problem:

Part of tailwinds reset (see below, number 2) breaks `<progress></progress>` elements, as observed on FF Mac.

```
*,
::before,
::after {
  box-sizing: border-box; /* 1 */
  border-width: 0; /* 2 */
  border-style: solid; /* 2 */
  border-color: #e5e7eb; /* 2 */
}
```

### Link to a minimal reproduction:
https://play.tailwindcss.com/zrpcyfkwVU

**Comment by adamwathan** [comment]
Hey! This is a tough one, I think the way it "breaks" is really no different than how we "break" buttons, inputs, select menus, etc. Everything is unstyled by default. This behavior has existed for 3.5 years and this is the first time it's come up so I don't think I'm going to change this by default, as it brings to question how we should be handling many other elements as well.

Instead I would suggest throwing this in your CSS as a custom base style, which will undo the styles that override the default progress bar styles:

```css
@layer base {
  progress {
    border-width: revert;
    border-style: revert;
    border-color: revert;
  }
}
```

This will break the ability to use classes like `border-2` on progress elements though without manually adding `border-solid` as well, but that's just inevitable if you undo that part of the reset.
