### ISSUE TITLE
Tailwind+React setup- craco start - Assertion error

### ISSUE THREAD

**Issue by rash09** [tailwindlabs/tailwindcss#3364]
### While running the caraco start command, facing lot of compatibility issue

**Got the below error**

 (node:16728) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): AssertionError: missing path
(node:16728) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

_Note: Modified the below to resolve few initial errors_

_- downgraded Node version from 10.4 to 7.7.1 
- Converted spread operators (...context) in craco/creat-config-provide-proxy.js files to ES5 Object.assign() methods._

**Comment by richadr** [comment]
Node 10 is not supported in Tailwind 2, can you see if upgrading helps

**Comment by adamwathan** [comment]
As mentioned Tailwind requires Node v12+.

**Comment by ohidurbappy** [comment]
@rash09 

I ran into the same issue and added **Carco config path** in `package.json` and it was fixed


```
//package.json
{
...
"cracoConfig": "./carco.config.js",
...
}
```

Also, ensure you have the right version of **node** and **postcss**.
