### ISSUE TITLE
Variant order in configuration ignored for group-hover/group-focus

### ISSUE THREAD

**Issue by stusherwin** [tailwindlabs/tailwindcss#3376]
In the [docs on ordering variants](https://tailwindcss.com/docs/configuring-variants#ordering-variants) it says

> It's important to note that when overriding variants, variants are generated in the order you specify them, so variants at the end of the list will take precedence over variants at the beginning of the list.

However, this doesn't work with `group-hover` (and presumably `group-focus`). If you explicitly set `group-hover` to have lower precedence than another variant, e.g. `hover` e.g.:

```
// tailwind.config.js
module.exports = {
  variants: {
    backgroundColor: ['group-hover', 'hover', 'focus'],
  },
}
```

The actual css generated for `group-hover` has higher specificity than `hover` so it will always override the other variants in the list with lower specificity.

Generated CSS:
```
.group:hover .group-hover\:bg-blue-200{ // has more selectors so higher specificity even though defined before
  --tw-bg-opacity: 1;
  background-color: rgba(191, 219, 254, var(--tw-bg-opacity));
}

// [... few thousand lines]

.hover\:bg-blue-200:hover{
  --tw-bg-opacity: 1;
  background-color: rgba(191, 219, 254, var(--tw-bg-opacity));
}
```

I wanted to use this to reset any styles on a collection of elements whenever any one of them was being hovered over, and only apply a style to the actively hovered element - e.g. in a dropdown list where one element has a selected state, but I want to ignore that and only show the hovered item as being selected. I was applying these classes:

```
<ul>
  <li class="group-hover:bg-transparent hover:bg-blue-200">Item 1</li> 
  <li class="bg-blue-200 group-hover:bg-transparent hover:bg-blue-200">Item 2 (selected)</li>
  <li class="group-hover:bg-transparent hover:bg-blue-200">Item 3</li>
</ul>
```
But the result of this bug is that even if I configure `group-hover` with a higher precedence, whenever one of the items is hovered, all of them get a transparent background.

I work around it by manually adding extra CSS for every combination of these:
```
.group:hover .group-hover\:bg-transparent.hover\:bg-blue-200:hover{
  --tw-bg-opacity: 1;
  background-color: rgba(191, 219, 254, var(--tw-bg-opacity));
}
```

**Comment by adamwathan** [comment]
Unfortunately nothing we can really do about this — as you've mentioned the group-hover selector has a higher specificity, so even though Tailwind does generate the CSS following the order you configure, that order doesn't help in this case.

I would recommend working around this with additional markup or by writing custom CSS. Here's one approach using additional markup, probably what I would do:

https://play.tailwindcss.com/gxyIqNPIsn
