### ISSUE TITLE
Space between utils also applying margin to hidden element if its the first one.

### ISSUE THREAD

**Issue by JawadR1** [tailwindlabs/tailwindcss#3380]
When applying "space between" utils, i:e "space-y-6", if I hide the first element, margin top is still applied to 2nd element which I don't think is the expected behavior. I have attached a tailwind playground snippet for your reference.

https://play.tailwindcss.com/VIJY7bUo4O

**Comment by Horsed** [comment]
This also happens with a `<template>` element as the first element.

**Comment by adamwathan** [comment]
Hey! This has been discussed before, please see the following previous discussions:

https://github.com/tailwindlabs/tailwindcss/issues/2740
https://github.com/tailwindlabs/tailwindcss/issues/3112
https://github.com/tailwindlabs/tailwindcss/issues/3350

**Comment by JawadR1** [comment]
I looked through any open issues of this kind but didn't find any, guess should have dug a little further.

I actually thought it might not be possible but I know very little... hehe
Anyway, Thanks for clarification.
