### ISSUE TITLE
break-words overflows parent container

### ISSUE THREAD

**Issue by styxlab** [tailwindlabs/tailwindcss#3393]
### Describe the problem:

Tailwind `break-words` is not behaving as expected as it does not stop overflowing content. If I use the css styles directly it works as expected (see both cases in below reproduction).

### Link to a minimal reproduction:

https://play.tailwindcss.com/YzBNiPouAO

**Comment by styxlab** [comment]
Looks like this is a duplicate of #1229, so this has been answered but not solved. Note that `break-all` is not a solution to this problem: yes, it does prevent content overflow, but it behaves differently as you then get even small words wrapped where you want those to be whitespace pre-wrapped.

**Comment by adamwathan** [comment]
Add `min-w-0` to the child of the flex container to get the correct behavior:

https://play.tailwindcss.com/0B2Rw1e4gY

No plans to add support for `word-break: break-word` since it is deprecated and only behaves differently within flex containers which is solved by the fix mentioned above.
