### ISSUE TITLE
gap-* doesn't apply on iOS device

### ISSUE THREAD

**Issue by tom-adsfund** [tailwindlabs/tailwindcss#3394]
On a recent iPhone, the gap-* doesn't apply on a flex div.

This just presents the elements as right next to each other instead of with the gap.

Example:
```
<div class="flex gap-4">
  <input type="text">
  <button>Click here</button>
</div>

```

**Comment by adamwathan** [comment]
Hey! Safari doesn't support `gap` in flexbox yet, only in grid:

https://caniuse.com/flexbox-gap

Use the `space-x-` utilities until browser support is better 👍🏻

**Comment by tom-adsfund** [comment]
@adamwathan Great, thanks for the info!
