### ISSUE TITLE
font-medium on Chrome / Firefox

### ISSUE THREAD

**Issue by Sebastien-Ahkrin** [tailwindlabs/tailwindcss#3396]
### Describe the problem:
Hello everyone 👋 i hope you have a nice day.
i think i have found a "bug" in the "font" classname.

On Chrome everythink sems to be good
![image](https://user-images.githubusercontent.com/30870051/105068386-2bf9bc00-5a81-11eb-8da7-d8d601c9c826.png)

But on Firefox this class sems to break 😢 we don't have the style on the text
![image](https://user-images.githubusercontent.com/30870051/105068438-3ae06e80-5a81-11eb-9d1d-2839679c1d6e.png)

Do you have any reason for that ?

### Link to a minimal reproduction:
https://play.tailwindcss.com/QBZboDe7fB

thanks everyone i hope this will help you :)

**Comment by UltraCakeBakery** [comment]
Chrome and the new edge browser use Webkit](https://webkit.org/) while Firefox uses [Gecko](https://developer.mozilla.org/en-US/docs/Mozilla/Gecko). They both render fonts differently when the requested `font-weight` is not available. If I remember it correctly, Firefox does not emulate missing font weights (or at least not all of them). Chrome does.

If you do not have the full font package installed on your computer or imported through a `<link>` tag for example, firefox will use the default font-weight or the next fallback font if no font weights are found.

Check in the dev tools which font is actually being used. Maybe you can find it at fonts.google.com. From there you can select the missing font-weights and import them.

I didn't check your playground or look up if i'm right. I'm too lazy for that. I missed clicked on this issue while trying to create my own... so yeah.. this is the best I can do for ya haha.

**Comment by Sebastien-Ahkrin** [comment]
@UltraCakeBakery a friend has the same error with this playground so i don't know ... i will check that i think

**Comment by adamwathan** [comment]
Nothing we are doing here that is different than regular CSS so going to close. If `font-weight: 500` looks different between browsers we can't really do anything about that unfortunately — all we do is generate the `font-weight: 500` rule itself.
