### ISSUE TITLE
Syntax error: Selector "* *::after" is not pure (pure selectors must contain at least one local class or id) @tailwind base;

### ISSUE THREAD

**Issue by TheRafaelFarias** [tailwindlabs/tailwindcss#3399]
### Describe the problem:

I was trying to use TailwindCSS with a NextJS project, but when I use the @taiwlind component-here gives me this:

![image](https://user-images.githubusercontent.com/44478887/105086912-77f43300-5a78-11eb-9638-d2ec5147a066.png)

Code:

![image](https://user-images.githubusercontent.com/44478887/105087295-08327800-5a79-11eb-9c9f-ec93b31c8f34.png)

**Comment by TheRafaelFarias** [comment]
I was importing tailwind components into the wrong file (instead of globals.css was my module component)

**Comment by RezaAmd** [comment]
same

**Comment by RezaAmd** [comment]
Use this on top of your css:
`
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
`

**Comment by RezaAmd** [comment]
Use this on top of your css:
`
@import "tailwindcss/base";
`
`
@import "tailwindcss/components";
`
`
@import "tailwindcss/utilities";
`
