### ISSUE TITLE
Hidden elements add outside whitespace using Space Between

### ISSUE THREAD

**Issue by Vinnl** [tailwindlabs/tailwindcss#3413]
### Describe the problem:

When I use `space-x-<nr>` on an element, I'd expect that whitespace to only occur in between child elements. And generally, it does.

However, when a `hidden` element is present before the first element, that causes whitespace to also be added _before_ the first element.

### Link to a minimal reproduction:

https://play.tailwindcss.com/MmyASfKJ25

**Comment by adamwathan** [comment]
Hey! This is a duplicate of this issue:

https://github.com/tailwindlabs/tailwindcss/issues/3380

**Comment by Vinnl** [comment]
Oh whoops, should've searched closed issues as well. Shame it's [practically impossible to fix](https://github.com/tailwindlabs/tailwindcss/issues/2740#issuecomment-736711525), but that's life I guess :shrug: Thanks!

**Comment by abevoelker** [comment]
This is unfortunate. Ruby on Rails's form helpers automatically add a `<input type="hidden">` CSRF token as the very first sub-element of every generated `<form>`, so this behavior is occurring on every form that uses these space classes.
