### ISSUE TITLE
PostCSS 7 compatibility build Installation can not use 'Purge' option with ParcelJS

### ISSUE THREAD

**Issue by raffi-minassian** [tailwindlabs/tailwindcss#3415]
### The problem:

When using parceljs, it is necessary to follow Tailwind's PostCSS 7 compatibility build installation instructions to get around the PostCSS 8 compatibility issue which currently affects some tools like parceljs. **_However this solution only works if you set the Tailwind config's "purge" option to `enabled: false` and the docs do not mention this_**. 

If you try to use the purge option by setting `enabled: true`, then you get an error that reads: "_PostCSS plugin **postcss-purgecss** requires PostCSS 8_". There does not seem to be any good way to get around this. It's a shame because the effort to provide a PostCSS7 compatibility build is otherwise quite good and appreciated. 

The nightly v2 parceljs build has way to many other uncertainties to be a good solution at the moment. Wondering if there is some other way to circumvent this issue from this end? If not, then perhaps at least mention it in the docs. 😊

### Minimal reproduction:

Node version: v14.15.1
This is the resulting package.json `devDependencies` after following the installation instructions for the PostCSS7 compatibility build at https://tailwindcss.com/docs/installation#post-css-7-compatibility-build . There are no other `dependencies` in the project where I have found this issue.

```
"devDependencies": {
    "@tailwindcss/postcss7-compat": "^2.0.2",
    "autoprefixer": "^9.8.6",
    "parcel-bundler": "^1.12.4",
    "postcss": "^7.0.35",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.0.2"
  }
```

This is the tailwind.config.js ...

```
module.exports = {
  purge: {
    enabled: true,
    content: [
      './src/**/*.html'
    ],
    options: {
      whitelist: ['mode-dark'],
    }
  },
  darkMode: 'media',
  theme: {
    extend: {
      //etc
    }
  },
  variants: {
    opacity: ['disabled']
  },
  plugins: []
}

```

This is the postcss.config.js ...

```
module.exports = {
  plugins: [
    require('tailwindcss')
  ]
}
```

**Comment by adamwathan** [comment]
Not really sure what to do to fix this I'm afraid other than just wait for Parcel to support PostCSS 8. I'd be happy to look at a PR if someone has an idea for a solution that involves an actual change to the Tailwind codebase but otherwise not sure what to do, so going to close with no concrete plans to fix sorry 😞 Doing our best to support PostCSS 7 and 8 simultaneously but can't afford to spend time trying to work out small issues with specific build tools that are still using old versions of things.

**Comment by ryeenii** [comment]
@adamwathan currently the only workaround is to *specifically* call version 3.0 of the `@fullhuman/postcss-purgecss` dependency in package.json, as mentioned by @jorisnoo [here](https://github.com/tailwindlabs/tailwindcss/issues/3101#issuecomment-753853148). this should technically fix all the issues with postcss 7 compatibility for now while a more efficient solution isn't available.
