### ISSUE TITLE
How about adding Apline JS support? :-)

### ISSUE THREAD

**Issue by markfirmware** [tailwindlabs/tailwindcss#3416]
How about adding Apline JS support? :-)

_Originally posted by @dgwyer in https://github.com/tailwindlabs/tailwindcss/discussions/2511#discussioncomment-131571_

I did not see an answer in the discussions ...

https://tailwindui.com/documentation#js-alpine quote:

    It's what we use for the Tailwind UI site itself, and is without a doubt what I'd recommend if you'd otherwise be writing jQuery or vanilla JS.

**Comment by richadr** [comment]
I believe it is supported implicitly; the guides for React, Angular etc. are there to give the best practices for integrating Tailwind in an existing build configuration, but with Alpine you hardly have any prescribed build config.  You just slap on your css classes, so you can follow the https://tailwindcss.com/docs/installation#installing-tailwind-css-as-a-post-css-plugin guide until you get to the "Building your css" part.

**Comment by markfirmware** [comment]
Oh ok, the original post was in [this discussion](https://github.com/tailwindlabs/tailwindcss/discussions/2511) and was about adding alpinejs to the playground itself. So yes, there is not a lot of effort needed to use tw + alpine in the wild, but at the moment alpinejs is not included in the playground.

**Comment by adamwathan** [comment]
Hey! This is captured on the playground repo already here:

https://github.com/tailwindlabs/play.tailwindcss.com/issues/42
