### ISSUE TITLE
!important in Angular with tailwindCSS 2.0 now requires interpolation

### ISSUE THREAD

**Issue by AlexanderOpran** [tailwindlabs/tailwindcss#3437]
### Describe the problem:

Previously on TailwindCSS 1.9.6 I could use !import in SCSS files without interpolation.

### Link to a minimal reproduction:

Reproduced here: https://github.com/AlexanderOpran/angular-tailwind-debug/tree/ngneat (if we downgrade to tailwind 1.9.6 everything will work, including !Important with interpolation).

I don't necessarily look for a fix on this, I am just curios why this happened right now. Were there any changes done in this regard? Thanks!

**Comment by adamwathan** [comment]
No changes on our end here so not sure what could have caused this. If the error is happening during the SCSS part of your build then it must be SCSS related, and Tailwind wouldn't even be running before the error happens.

Going to close since nothing we can do about this.
