### ISSUE TITLE
Absolute positioning doesn't work in relative element

### ISSUE THREAD

**Issue by kkdima** [tailwindlabs/tailwindcss#3439]
### Describe the problem:

I have this code in my project:
```
    <div className="border border-black h-20 m-3 relative">
      <div className="border border-green-700 m-2 w-20 h-10 absolute bottom-0 right-0" />
    </div>
```
it gives me this output: 
<img width="779" alt="Screen Shot 2021-01-25 at 12 27 40 PM" src="https://user-images.githubusercontent.com/17368311/105762068-bec6aa80-5f08-11eb-9e67-fcc3b534daae.png">
I expect to move the div child as I want inside a container with the relative position. For some reason, I have working tailwind classes that ignoring rules when I'm trying to move absolute div giving it classes like bottom-0, right-0
I put the same piece of code in a [sandbox](https://codesandbox.io/s/immutable-voice-rsx2s) and it works perfectly fine.

**In other words, it's just ignoring either top, bottom, right, left, or absolute styling of my child div.**

So the issue is definitely somewhere in my setup.
Can someone point me to flaws? 

### Link to a minimal reproduction:

To reproduce my bug:
```
git clone https://kkdima:b599d55ef1659df77bbe9e5c65b6812a7830f8b6@github.com/kkdima/Sweet-Love-And-Roses.git
npm i
npm run dev
```

**(the issue would be inside `VideoSection.js ` component on the home page)**

My postcss.config.js:
``` module.exports = {
    plugins: {
        'postcss-import': {},
        tailwindcss: {},
        'postcss-flexbugs-fixes': {},
        'postcss-preset-env': {
            autoprefixer: {
                flexbox: 'no-2009',
            },
            stage: 3,
            features: {
                'custom-properties': false,
            },
        },
    },
};
```

**Comment by adamwathan** [comment]
Hey! Your issue is that you have overridden all of the top/right/bottom/left utilities in your Tailwind config. Make sure your `inset` settings are within the `extend` section, like here:

```js
module.exports = {
  future: {
      removeDeprecatedGapUtilities: true,
      purgeLayersByDefault: true,
  },
  purge: ['./components/**/*.{js,ts,jsx,tsx}', './pages/**/*.{js,ts,jsx,tsx}'],

  theme: {
      minWidth: {
          '200': '200',
      },
      zIndex: {
          '-10': '-10',
      },
      extend: {
          colors: {
              'accent-1': '#333',
              'background-1': '#F9F9F9',
              'button-dark': '#494949',
              'button-white': '#F9F6EF',
              'main-accent': '#98A9A9',
          },
          fontFamily: {
              logo: ['El Messiri'],
          },
          height: {
              px: '1px',
          },
          inset: {
              '-2': '-2px',
          },
      },
  },
  variants: {},
  plugins: [],
};
```

**Comment by kkdima** [comment]
@adamwathan thank you for pointing to this!
