### ISSUE TITLE
When you open the browser console and execute the css animation, the page animation will execute very slowly

### ISSUE THREAD

**Issue by hsiangleev** [tailwindlabs/tailwindcss#3454]
### Describe the problem:

1. When using css animation, open the browser console and select the node
2. If you execute the animation again, the animation will stuck, but after closing the browser console, the animation will not stuck
3. As shown in the figure below, first open the console, select the last node <span>, and then click "toggle" to execute the animation ![https://hsiangleev.github.io/tool/test/images/2.png](https://hsiangleev.github.io/tool/test/images/2.png)
4. When the node level is deep, the effect will be more obvious ![https://hsiangleev.github.io/tool/test/images/3.png](https://hsiangleev.github.io/tool/test/images/3.png)

### Link to a minimal reproduction:

[https://codesandbox.io/s/nostalgic-gould-599ox?file=/index.html](https://codesandbox.io/s/nostalgic-gould-599ox?file=/index.html)
[https://element-plus-admin.hsianglee.cn/](https://element-plus-admin.hsianglee.cn/)

**Comment by iantearle** [comment]
Is this really an issue with tailwind or something to do with resources on the local machine? Your also including the packaged tailwind css which is unpurged for your environment. Try using tailwind locally and purging off unused styles. I’ve crashed safari inspector before including a 5mb tailwind css file. Sometimes all those styles make the browser slow.

**Comment by adamwathan** [comment]
Nothing we can really change in Tailwind that would have any impact on this I'm afraid so going to close. @iantearle is correct that the large stylesheet Tailwind generates can cause performance issues in dev tools for some people, hopefully eventually browsers will find ways to manage large stylesheets better. Tough situation for sure but not anything we can do on our end without introducing a breaking change that removes a bunch of functionality from the framework or something.
