### ISSUE TITLE
divide classes not beging applied

### ISSUE THREAD

**Issue by gimyboya** [tailwindlabs/tailwindcss#3481]
### Describe the problem:

The divide width and divide color utilities are not having any effect on my design. the intellisense suggest them on my editor (i assume the class are loading) however they seem to have no actual CSS in them?

![image](https://user-images.githubusercontent.com/14952013/106339909-fea7dc00-62d2-11eb-8668-10d346e094b9.png)
above image shows working intellisense

![image](https://user-images.githubusercontent.com/14952013/106339939-167f6000-62d3-11eb-90a8-6dbb5e1d487e.png)
notice how the actual CSS properties are missing

![image](https://user-images.githubusercontent.com/14952013/106339972-2ac35d00-62d3-11eb-8f6e-938d4ffbb4d9.png)
event when hovered the divide class don't show anything

![image](https://user-images.githubusercontent.com/14952013/106340001-4dee0c80-62d3-11eb-8a03-26f4c1970018.png)
both `divide-x-2` and `divide-gray-700` are behaving like that.

and again it doesn't apply any changes on my design.

### Link to a minimal reproduction:

Currently the Repo is private but i can give access if the team is willing to look into this. I am hoping that someone somewhere has already faced this and found a solution to it.

`divide-x-{width}` and `divide-{color}-xxx` in the playground seems to work fine https://play.tailwindcss.com/

**Comment by w3bdesign** [comment]
@gimyboya 

Did a small test with no additional classes or CSS that overrides the design, and I had no issues.

Take a look at https://tailwindcss.com/docs/divide-width#class-reference

Got this code to work:

```javascript
    <div class="grid grid-cols-3 divide-x-2 divide-gray-700">
      <div>1</div>
      <div>2</div>
      <div>3</div>
    </div>
```

This gave me this:

![image](https://user-images.githubusercontent.com/45217974/106345753-b1b40d80-62b2-11eb-9e04-47330d1adaaf.png)

**Comment by gimyboya** [comment]
I found the problem. the borders where not showing because the elements where having a default value of `border-style: none;` applying `border-solid` class to the underlying elements fixed things. and i guess the intellisense for VS Code tailwind extension simply doesn't show when the class is more then one line?

**Comment by YeisonHunt** [comment]
Same problem here in Chrome, divide doesn't work :/

**Comment by awacode21** [comment]
Having the same issue!

**Comment by masterkain** [comment]
I found that applying a `.divide-y` on a `.table-row` only applies the styles to all rows but the first one

**Comment by josh-tt** [comment]
this worked for me:

  corePlugins: {
    divideStyle: true,
  }

**Comment by Gismo1337** [comment]
Still doenst work.
ubuntu 21
brave browser

**Comment by davide-casiraghi** [comment]
same problem here

**Comment by shinokada** [comment]
@Gismo1337 Did you add color?

```
class="divide-y divide-gray-200
```

Without color, it doesn't work.

**Comment by Tobeyforce** [comment]
> I found that applying a `.divide-y` on a `.table-row` only applies the styles to all rows but the first one

Did you ever solve this? I'm having all sorts of bugs with grid in tailwind with gaps & divide

**Comment by Y80** [comment]
try add base style:
```css
*, :after, :before {
  border: 0 solid #e0e0e0;
}
```

this should be added by '@tailwind base ; ' , but not.

**Comment by klavsbuss** [comment]
hacky, but best solution i could find:
![image](https://user-images.githubusercontent.com/18184893/192592095-9f86844b-34cd-46bc-be7f-d5adb4b32211.png)

**Comment by quantumwebco** [comment]
My divide classes aren't even being generated. They simply don't exist in the style sheet. Am I missing a plugin required for divide?

**Comment by aallnneess** [comment]
Same problem here, divider dont work:

```
<div class="grid grid-cols-1 divide-y">
  <div>01</div>
  <div>02</div>
  <div>03</div>
</div>
```

![image](https://user-images.githubusercontent.com/73443724/207610933-f945559c-ddb0-4856-bcc9-ea2768ebfc06.png)


![image](https://user-images.githubusercontent.com/73443724/207611080-69562611-698f-4c96-85da-09d4b21cde9b.png)

**Comment by aallnneess** [comment]
Okay, its because preflight was disabled !

**Comment by magalidefelippe** [comment]
Hey, today I had the same problem and I solved with
`divide-solid`
hope this help

**Comment by kacirekj** [comment]
Same problem here, nothing of the mentioned solutions worked for me. Divide-y is not applied on the first column of flex layout.

**Comment by vuduynhiennn** [comment]
```
<div class="divide-x divde-solid">
    <div class="border-y-0"> child </div>
    <div class="border-y-0"> child </div>
    <div class="border-y-0"> child </div>
</div>
```

**Comment by ChenaLee** [comment]
adding "border" worked for me. Thanks! For some reason divide-y worked without adding "border" but divide-x did not

**Comment by cloby99** [comment]
> Hey, today I had the same problem and I solved with `divide-solid` hope this help

Thanks, it worked!

**Comment by 0Chan-smc** [comment]
> ```
> <div class="divide-x divde-solid">
>     <div class="border-y-0"> child </div>
>     <div class="border-y-0"> child </div>
>     <div class="border-y-0"> child </div>
> </div>
> ```
After applying `divide-solid` I had to use `border-x-0` or `border-y-0`, which fixed it.

And it was definitely a `preflight: false` problem for me.

**Comment by mattiLeBlanc** [comment]
<img width="794" alt="image" src="https://github.com/tailwindlabs/tailwindcss/assets/5285035/33eabcc1-5228-4a44-9793-7b1ca5a75920">

It looks like this for me.  Using
```
</div>
<div class="divide-y divide-solid divide-gray-200">
  <div class="border-y-0">01</div>
  <div class="border-y-0">02</div>
  <div class="border-y-0">03</div>
</div>
```
Mind you that I have preflight set to false because I am using Angular Material Components and I noticed how preflight messes up the mat-form-fields.

Is there anyway to get this working with preflight off?
