### ISSUE TITLE
The prefers-color-scheme setting is not deleted.

### ISSUE THREAD

**Issue by l2zeo** [tailwindlabs/tailwindcss#3498]
Even if the dark mode setting is set to'class', the prefers-color-scheme is applied.

**tailwind.config.js**
```
const colors = require('tailwindcss/colors')
module.exports = {
  darkMode: 'class',
  future: {
    removeDeprecatedGapUtilities: true,
    purgeLayersByDefault: true,
  },
...

```

**postcss.config.js**

```
const purgecss = require('@fullhuman/postcss-purgecss')
const cssnano = require('cssnano')

module.exports = {
  plugins: [
    require('tailwindcss')('./tailwind.config.js'),
    process.env.NODE_ENV === 'production' ? require('autoprefixer') : null,
    process.env.NODE_ENV === 'production' ? cssnano({ preset: 'default' }) : null,
    purgecss({
      content: ['./public_html/**/*.php', './src/**/*.vue', './src/**/*.jsx', './node_modules/tailwindcss-dark-mode/prefers-dark.js'],
      defaultExtractor: content => content.match(/[\w-:./]+(?<!:)/g) || [],
      safelist: ['dark', 'text-black-300', 'shadow-btn-orange-hover', 'bg-alert', 'border-red-600', 'border-red-800', 'text-black-015','border-black-700', 'border-black-800', 'danger-btn', 'bottom-3', 'left-8', 'flex-33', 'outline-remove', 'left-0', 'bottom-1', 'text-center', 'bg-rental-orange']
    })
  ]
}
```

**Comment by adamwathan** [comment]
Can't reproduce this locally, using the "class" mode generates selectors with classes and no `prefers-color-scheme` media query. Please open a new issue and provide an actual reproduction (a GitHub repo I can clone down and see the behavior happen, not code snippets I need to use to try and recreate the project from scratch myself) if this is still a problem for you.

**Comment by danimalweb** [comment]
With class mode selected Tailwind is still generating `prefers-color-scheme` media query in my build. I'm looking into it to try and create a smaller test case. I'm sure this wasn't an issue a week or two ago.
