### ISSUE TITLE
Gradients inconsistent between Chrome and Safari

### ISSUE THREAD

**Issue by nickradford** [tailwindlabs/tailwindcss#3500]
### Describe the problem:
I'm using the following classes to define a background gradient on a div `bg-gradient-to-r from-blue-700 via-blue-100 to-transparent`, looks how I expect in Chrome, but Safari looks distinctly more gray.

Interestingly, I see that if I remove the `to-transparent`, it renders as expected in Safari too. Seeing as the default "to" value for a bg-gradient in tailwind is transparent, shouldn't it behave the same regardless if its provided or not?

#### Chrome
![image](https://user-images.githubusercontent.com/222221/106574922-566f5e80-64f0-11eb-8dec-25387b4de076.png)

#### Safari
![image](https://user-images.githubusercontent.com/222221/106574954-5ff8c680-64f0-11eb-8f78-ad75d0092c75.png)

### Link to a minimal reproduction:
Here's the [Codepen](https://codepen.io/nick_radford/pen/abBOwJX) I screenshotted above.

**Comment by nickradford** [comment]
I should have looked at closed issues, and I would have found #3071, sorry for the duplicate issue. It might be worth updating the docs to include something about this issue to prevent duplicate issues in the future.

**Comment by adamwathan** [comment]
Yeah don't use `to-transparent`, just leave it off. This is mentioned in the docs briefly but we could call it out more for sure.
