### ISSUE TITLE
bg-gray-400 Background Color is not present

### ISSUE THREAD

**Issue by deysarkarswarup** [tailwindlabs/tailwindcss#3504]
### Describe the problem: 
In Utilities for controlling an element's background color documentation page, there's a class called "bg-gray-400". But it's not working. 

### Link to a minimal reproduction: 
https://tailwindcss.com/docs/background-color

**Comment by yepes** [comment]
Can you please explain if you have modified something?

.bg-gray-400 is there:

https://play.tailwindcss.com/U5W06cyGxY

**Comment by deysarkarswarup** [comment]
yes. Its working in Tailwind Play.. But somehow its not working in my project.. My Fault.

**Comment by deysarkarswarup** [comment]
Its working fine.

**Comment by SkyfallWasTaken** [comment]
Mind explaining what the problem was? I'm having the same issue rn @deysarkarswarup

**Comment by WayneKim92** [comment]
I got the same issue
