### ISSUE TITLE
Plugin helper function `theme()` returns `function` for dotted key

### ISSUE THREAD

**Issue by royvanv** [tailwindlabs/tailwindcss#3505]
### Describe the problem:

The plugin helper function `theme()` returns a function instead of the value for a dotted key. 

### Link to a minimal reproduction:

Here's a minimal config with plugin to illustrate the problem.
```js
const plugin = require('tailwindcss/plugin');

module.exports = {
  theme: {
    thisWorks: theme => ({
      'black': theme('colors.black'),
    }),
    thisDoes: {
      notWork: theme => ({
        'black': theme('colors.black'),
      }),
    },
  },
  plugins: [
    plugin(function({ theme }) {

      console.log(theme('thisWorks', {})); // Okay, returns value.
      console.log(theme('thisDoes.notWork', {})); // => Returns function.
    }),
  ],
};
```

Check your dev tools console to see the logged values at this playground example: https://play.tailwindcss.com/3EZyUv8pvw?file=config

**Comment by fedeci** [comment]
Hi @royvanv, as you can see [here](https://tailwindcss.com/docs/theme) the `theme` function can only be used at the "top level" of your theme object.

```js
// this should work
theme: {
    thisWorks: theme => ({
      'black': theme('colors.black'),
    }),
    thisDoes: theme => ({
      notWork: {
        'black': theme('colors.black'),
      },
    }),

```

**Comment by royvanv** [comment]
@fedeci Thanks,your solution works for me. FYI: I just wanted to group my settings under a single top-level key.

> Note that you can only use this kind of closure with top-level theme keys, not the keys inside of each section.
I clearly did not read the docs properly 😇
