### ISSUE TITLE
Sizes not working on Google Maps Infowindow

### ISSUE THREAD

**Issue by eherediadev** [tailwindlabs/tailwindcss#3506]
As the title says, w-*, h-*, p*-* are not working when implemented on infowindow. text-blue-* not working neither.

This is the expected result:
![image](https://user-images.githubusercontent.com/58760422/106638402-35435800-655a-11eb-8192-ae50b5753e19.png)

The actual implementation:
![image](https://user-images.githubusercontent.com/58760422/106638537-5e63e880-655a-11eb-975f-4d32eca1f488.png)

Link to a minimal reproduction:
https://play.tailwindcss.com/heyK4AtitD

**Comment by richadr** [comment]
As you can see in your minimal reproduction, it works just fine.

Google Maps is probably settings widths, paddings etc. using selectors with a higher CSS specificity.  In other words, a selector `.poi-info-window .full-width` is more specific than `.w-64`, therefore it takes precedence.

On this page, a strategy to work around this is explained: https://tailwindcss.com/docs/configuration#important

**Comment by eherediadev** [comment]
Thanks @richadr. It seems like it's not possible to use all the utilities in google maps.
