### ISSUE TITLE
Unexpected input placeholder color on Firefox, macOS

### ISSUE THREAD

**Issue by tobx** [tailwindlabs/tailwindcss#3534]
### Describe the problem:

The placeholder classes (e.g. `placeholder-black` or `placeholder-opacity-100`) do not work as expected on *Firefox 85.0.1*, *macOS 11.1*. The placeholder always has some transparency (see screenshot below). This does not occur with vanilla CSS and neither on Chrome or Safari.

### Link to a minimal reproduction:

https://play.tailwindcss.com/jcuzc8F6D5

![screenshot](https://user-images.githubusercontent.com/6427718/107129998-e4b95b00-68c9-11eb-8f17-84887600bcd3.png)

**Comment by adamwathan** [comment]
Fixed in 2.0.3 👍🏻
