### ISSUE TITLE
what is x-state and x-description?

### ISSUE THREAD

**Issue by mouyong** [tailwindlabs/tailwindcss#3545]
### Describe the problem:

> Hello there! I digged into the tailwind ui select boxed - to get this work with my livewire alpinejs project. There are some strange attributes in there: 
>
>
```
<span x-state:on="Selected" x-state:off="Not Selected"
    :class="{ 'font-semibold': value === 0, 'font-normal': !(value === 0) }"
    class="block truncate font-normal">
    Wade Cooper
</span>
```
> I can not find out what this x-state:on is and how this should be connected with the whole system. In the alpineJs docs is no x-state mentioned.
>
> Sadly thats inbound with an iframe - so i can not see the proper methods like (onOptionSelect, onButtonClick, choose). 
Is there any documentation source where I can see this? I mean maybe I would discover this all by myself. But this is very time consuming and this all for a simple option select ;).

### Link to a minimal reproduction:

this is question: https://discord.com/channels/674983035946663957/683401626190610434/740214656471138365

this is answer: https://discord.com/channels/674983035946663957/674983036374220800/762971808600948756

> We use some extra non-official Alpine-y attributes to feed extra metadata to our comment transformation system, for example:
>
> - x-description is translated into a comment that labels that section of markup so people reading it can understand the code more quickly
> - x-state:on and x-state:off are used to label "on" and "off" states for dynamic classes
> So long story short, don't worry about it
> It generates this kind of comments
![image](https://user-images.githubusercontent.com/10336437/107177192-3538d180-6a0c-11eb-8472-6b255a7c3b3b.png)

**Comment by adamwathan** [comment]
Hey! Those are totally custom attributes that we parse out and use to generate the comments that go above the component. Just part of our custom build process, not an Alpine feature, feel free to ignore.

**Comment by mouyong** [comment]
Yes. But there are a lot of people looking for the h of these instructions. So i create this issue.

**Comment by mouyong** [comment]
requirejs components need our write javascript. It's a little difficult.

**Comment by mouyong** [comment]
requirejs components need our write javascript. It's a little difficult.

**Comment by adamwathan** [comment]
We are working on official support for popular JavaScript frameworks but right now the templates are targeted at people comfortable writing the JS themselves (think like the [Bulma](https://bulma.io) CSS framework). We try to be explicit about this in the FAQ and it's also outlined in the documentation:

https://tailwindui.com/documentation#integrating-with-javascript-frameworks

We can't provide detailed instructions for every JS framework out there unfortunately, the best we can do is provide comments in the HTML explaining what styles to use for what states, and point people to any relevant accessibility guidelines so they can implement the behavior robustly using whatever tools they prefer. Again we are working on official support (React and Vue to start) which will be available in a month or two. In the mean time, if you are not an experienced JavaScript developer Tailwind UI might not be a great fit for you yet, and you're welcome to contact support for a refund 👍🏻
