### ISSUE TITLE
Error getting color with resolveConfig in NodeJS script

### ISSUE THREAD

**Issue by javifm86** [tailwindlabs/tailwindcss#3562]
### Describe the problem:

I am using [resolveConfig](https://tailwindcss.com/docs/configuration#referencing-in-java-script) in a NodeJS script. In `tailwind.config.js` I have my custom colors:

```js
const colors = require('tailwindcss/colors');

module.exports = {
  purge: ['./public/**/*.html', './src/**/*.vue'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        blue: colors.lightBlue,
        yellow: colors.amber,
        green: colors.teal
      }
    }
  },
  variants: {},
  plugins: []
};
```

When I run the script, default blue colors are returned instead of lightBlue. This is not happening if I run resolveConfig in a Vue project for example.

Node script:

```js
const resolveConfig = require('tailwindcss/resolveConfig');

const fullConfig = resolveConfig('./tailwind.config.js');
console.log(fullConfig.theme.colors.blue); // returns wrong colors
```

I know the syntax in documentation is not for Node, just asking if this is intended or not.

### Link to a minimal reproduction:

https://github.com/javifm86/tailwindResolveConfig

```
npm install
node index.js
```
Result:

```
npm start

> tailwindresolveconfig@1.0.0 start C:\Users\tailwindResolveConfig
> node index.js

{
  '50': '#eff6ff',
  '100': '#dbeafe',
  '200': '#bfdbfe',
  '300': '#93c5fd',
  '400': '#60a5fa',
  '500': '#3b82f6',
  '600': '#2563eb',
  '700': '#1d4ed8',
  '800': '#1e40af',
  '900': '#1e3a8a'
}
```

Thanks a lot, best regards.

**Comment by debrice** [comment]
I believe you're missing the import/require part. 

You should import the `tailwind.config.js` and pass its values to `resolveConfig()`

```diff
diff --git a/index.js b/index.js
index a83a4e0..52371d7 100644
--- a/index.js
+++ b/index.js
@@ -1,4 +1,6 @@
 const resolveConfig = require('tailwindcss/resolveConfig');
 
-const fullConfig = resolveConfig('./tailwind.config.js');
+const config = require('./tailwind.config.js');
+
+const fullConfig = resolveConfig(config);
 console.log(fullConfig.theme.colors.blue);
```

**Comment by javifm86** [comment]
Yes, you are right! I mixed both syntaxes. I don´t know how I couldn't see it. Thanks @debrice.
