### ISSUE TITLE
transition property should transition also bg-opacity and text-opacity

### ISSUE THREAD

**Issue by minimit** [tailwindlabs/tailwindcss#3568]
### Describe the problem:

As subject the https://tailwindcss.com/docs/transition-property would be logic to transition also the tailwind css properties that sets the bg-opacity and text-opacity since it transitions color and background-color

```
transition-property: background-color, border-color, color, fill, stroke, opacity, box-shadow, transform; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-duration: 150ms;
```

**Comment by adamwathan** [comment]
This already works as far as I can tell:

https://play.tailwindcss.com/pqOfFu7WpY

**Comment by minimit** [comment]
Oh yes I had set it up wrong thanks adam
