### ISSUE TITLE
bug with grid and divide-y

### ISSUE THREAD

**Issue by ziaadini** [tailwindlabs/tailwindcss#3579]
### Describe the problem:

```
 <div class="grid grid-cols-2 divide-y divide-yellow-500">
      <div>1</div>
      <div>2</div>
      <div>3</div>
      <div>4</div>
 </div>

```
divide-y not working as expected while `grid-cols-1` it's okay, but with `grid-cols-2`...

``` 
"@tailwindcss/postcss7-compat": "^2.0.2", 
 "tailwind-config-viewer": "^1.4.0",
 "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.0.2",
```

**Comment by debrice** [comment]
I don't know if divide is supposed to work with grid but just in case, [that's a reproduction](https://play.tailwindcss.com/RR2RWOrsTe) where the 2nd cell gets a divider on a 2 column grid.

I've also added a hack that uses the background color and a pixel gap to reach what I believe was your expect result

**Comment by ziaadini** [comment]
thanks it's working i'll keep your example in my bookmarks

**Comment by devsquad-lfernandogunther** [comment]
I'm with the same problem here

tailwindcss v3.3.3

**Comment by codymullins** [comment]
Having the same issue with `grid grid-cols-2 gap-4 divide-y divide-gray-300`

<img width="963" alt="Screenshot 2024-03-22 at 2 26 46 PM" src="https://github.com/tailwindlabs/tailwindcss/assets/1738479/b13a80cc-3f3b-48c0-a5eb-66e93447b9b6">

**Comment by mustafaucardev** [comment]
It still gives [that](https://play.tailwindcss.com/vANtoF3wcU) error result.

![image](https://github.com/tailwindlabs/tailwindcss/assets/166290346/ac8ad6cb-91fb-407f-9c84-ab721daa9f52)
