### ISSUE TITLE
Ring offset color "bleeds" into element when background is transparent

### ISSUE THREAD

**Issue by gregorybolkenstijn** [tailwindlabs/tailwindcss#3595]
### Describe the problem:

A ring offset color "bleeds" into the element when it's background is transparent and it has a border radius. See the corners of the button in the screenshot and in the playground link.
```
<div class="min-h-screen bg-blue-900 p-40 text-white">
  <button class="px-8 py-4 bg-transparent hover:bg-blue-700 rounded-lg ring-2 ring-white ring-offset-blue-900 ring-offset-2">Ring Bleed Example</button>
</div>
```

![image](https://user-images.githubusercontent.com/683497/108043872-e4475f80-7041-11eb-8d7f-fcd0dc646402.png)

### Link to a minimal reproduction:

https://play.tailwindcss.com/mJYibBefhl

The styling of the button with a transparent background comes from our design where the background can be a gradient or any dark color. Any advice on how to solve this would also be welcome.

**Comment by debrice** [comment]
Hi @gregorybolkenstijn ,

I've been facing that issue a few time and while it's not always obvious your example does make it standout. 

If you really want to get rid of it, [I've created a snippet](https://play.tailwindcss.com/fg1EADTiPE) demonstrating how you can create an artificial offset of the ring by embedding a div inside the button and use padding to create the same effect. Note the addition of a new variant (`rounded-btn`) in tailwind config

```js
const colors = require('tailwindcss/colors')

module.exports = {
  theme: {
    extend: {
      colors: {
        'light-blue': colors.lightBlue,
        cyan: colors.cyan,
      },
      borderRadius: {
        btn: '.4rem',
      },
    },
  },
  variants: {},
  plugins: [],
}
```

![image](https://user-images.githubusercontent.com/56964/108418742-a55f0880-71ff-11eb-9c8d-5239db414196.png)

Hope that helps

**Comment by adamwathan** [comment]
This is just kinda how things work with CSS I'm afraid. Easiest work around is give the button a solid background color that matches the background behind it:

https://play.tailwindcss.com/W8RmIxpz0F

Not great when you are over an image or anything like that but just kinda is what it is.
