### ISSUE TITLE
addUtilities and addComponents bad escape when respectPrefix: false

### ISSUE THREAD

**Issue by minimit** [tailwindlabs/tailwindcss#3597]
### Describe the problem:

There's a bug on escaping classes when using `respectPrefix: false`.

The bug occurs in the output on classes generated with `addUtilities` or `addComponents`, but only in NOT variant classes.

This is the output, see link to minimal reproduction:

```
.custom-\31 {
  margin-top: -1rem;
  margin-left: -1rem;
}
.custom-\31\.5 {
  margin-top: -1rem;
  margin-left: -1rem;
}
```

Should be

```
.custom-1 {
  margin-top: -1rem;
  margin-left: -1rem;
}
.custom-1\.5 {
  margin-top: -1rem;
  margin-left: -1rem;
}
```

### Link to a minimal reproduction:

https://github.com/minimit/twbug-respectprefix-escape

**Comment by bradlc** [comment]
Hey @minimit. The escape function should be used on the **complete class** (without the `.`):

```js
// Will unnecessarily escape `1`
`.rotate-${e('1/4')}`
// => '.rotate-\31 \/4'

// Won't escape `1` because it's not the first character
`.${e('rotate-1/4')}`
// => '.rotate-1\/4'
```

Check out the documentation for more information: https://tailwindcss.com/docs/plugins#escaping-class-names

**Comment by minimit** [comment]
Thank you it was indeed the proble
