### ISSUE TITLE
Cannot overwrite theme fontFamily when using presets to override

### ISSUE THREAD

**Issue by terryupton** [tailwindlabs/tailwindcss#3612]
### Describe the problem:
I have moved some config into separate preset files. One of these preset files is called `tailwind.brand.js` and I am including this along with several others in my main `tailwind.config.js` file like so:

```
module.exports = {
  presets: [
    require('./src/tailwind/tailwind.brand.js'),
    // require('./src/tailwind/tailwind.project.js'),
    require('./src/tailwind/tailwind.colors.js'),
    require('./src/tailwind/tailwind.spacing.js'),
    require('./src/tailwind/tailwind.opacity.js'),
    require('./src/tailwind/tailwind.zindex.js'),
    require('./src/tailwind/tailwind.grid.js')
  ],
  purge: {
    mode: 'all',
    content: [
      './templates/**/*.html',
      './templates/**/*.php',
      './src/**/*.js'
    ],
    
    options: {
      whitelistPatterns: [/lazyload/, /grayscale-up/, /blur-up/],
    }
  },
  theme: {
    container: {
      center: true,
      padding: '1.5rem',
    },
  },
  variants: {
    extend: {
      // display: ['group-hover']
      // translate: ['group-hover']
    }
  },
  corePlugins: {},
  plugins: []
};

```

Within the `tailwind.brand.js` I am over-riding the font families and adding/extending some colours like so:

```
module.exports = {
  theme: {
    fontFamily: {
      'sans': ['Poppins', 'sans-serif'],
      'serif': [''],
      'brand': [],
    },
    extend: {
      colors: {
        // Extends one of new TailwindCSS colour schemes
        // lightblue: colors.lightBlue,
        
        'brand': {
          'orange': '#fe5b00',
          'red': '#ff0000'
        }
      },
    }
  }
};
```

However, on the buildCSS the fontFamily is not getting replaced and it is using the default family settings.
If I move the fontFamily code out of the `tailwind.brand.js`  and directly into the `tailwind.config.js` then it works ok.

```
    fontFamily: {
      'sans': ['Poppins', 'sans-serif'],
      'serif': [''],
      'brand': [],
    },
```

So it appears that the the defaults are not overridden when inside a preset.

**Comment by debrice** [comment]
Not sure if that can help your issue but this can happen if your main tailwind config re-define the `fontFamily` `sans` key (wether or not it overrides or extends it).

**Comment by bradlc** [comment]
Hey @terryupton, I am not able to reproduce this. Could you share a project which has this issue? Would make it much easier to debug 👍 

Here's a basic example which works on Tailwind Play: https://play.tailwindcss.com/y6aqV9ZlH8?file=config

**Comment by terryupton** [comment]
Thanks @bradlc. I have invited to you to a private repo on github, I will create a ticket on that repo to run through the details.
I thought this was the easiest way, but let me know if you have an alternative preferred approach. I don't think I can replicate the issue via Tailwind Play due tot he various presets.

**Comment by bradlc** [comment]
@terryupton Thanks! I set up your repo and ran the build, and Poppins is definitely being used in the CSS output:

![image](https://user-images.githubusercontent.com/2615508/109425153-e49b0f80-79de-11eb-95f5-50c80fbfbe98.png)

![image](https://user-images.githubusercontent.com/2615508/109425161-ef55a480-79de-11eb-86d2-cfb18958cc0a.png)

Are you not seeing this?

**Comment by terryupton** [comment]
Hey @bradlc - so the version of the repo is working as I moved the font stack into the main tailwind.config.js file.
I had not had the time to setup the broken version. Tomorrow I will setup a new branch to illustrate the problem and hopefully you'll be able to replicate it.

However, if you did want to test before I get the chance to set this up tomorrow.
If you simple remove the 
```
fontFamily: {
      'sans': ['Poppins', 'sans-serif'],
      'serif': [''],
      'brand': [],
    },
``` 
from the the `tailwind.config.js file` (top level) and move this into the `/src/tailwind/tailwind.brand.js`
```
theme: {
    fontFamily: {
      'sans': ['Poppins', 'sans-serif'],
      'serif': [''],
      'brand': [],
    },
 ```
 Notice this is not extending. This should overwrite the sans font stack.
 Then this should replicate the initial problem in my first thread.
 
 Thanks.

**Comment by terryupton** [comment]
Hey @bradlc - I have now setup a new branch `tailwind-presets-issue` that illustrates the issue.
I have rerun the build (using none production) and you can see that the 'Poppins' font stack is no longer used when it is called within `/src/tailwind/tailwind.brand.js`

Shout me if you need anything clarifying.

**Comment by bradlc** [comment]
Hey @terryupton thanks for that. After taking a closer look at this it seems that the presets are working as expected, although the behaviour may be a little unintuitive.

Basically each of your presets in turn extends from the default config. From [the docs](https://tailwindcss.com/docs/presets#creating-a-preset):

> By default, presets themselves extend Tailwind's default configuration just like your own configuration would.

You can think of it like this:

```js
let preset1 = [defaultConfig, customStuff1]
let preset2 = [defaultConfig, customStuff2]

let finalConfig = merge([...preset1, ...preset2, customStuff3])
// => merge([defaultConfig, customStuff1, defaultConfig, customStuff2, customStuff3])
```

So the font you're specifying in `customStuff1` is overridden by the default config that `preset2` extends. The solution is to set `presets` to an empty array in each of your presets:

> If you'd like to create a preset that completely replaces the default configuration, include an empty presets key in the preset itself

Then, to ensure that you still get the Tailwind defaults you can either leave the `presets` key off your first preset, or add it manually to your main config file:

```js
module.exports = {
  presets: [
    require('tailwindcss/defaultConfig'),
    require('./preset1.js'),
    require('./preset2.js'),
  ],
}
```

Hopefully that makes sense, and I have opened a pull request on your repo with the changes I described 👍
