### ISSUE TITLE
Grid columns showing in wrong order, also creating a second row

### ISSUE THREAD

**Issue by chadalen** [tailwindlabs/tailwindcss#3614]
### Describe the problem:

I define a grid with 1 row, 3 columns. I'm getting 2 rows 3 columns but the columns are all out of order.

For code [see here](https://github.com/syntaxrecall/syntaxrecall/blob/tailwind-issue/data/content/screen.html#L12)

**Expected**
* CLI Options & Accessibility should be in column 1
* Screens should be in column 2 in row 1
* Visual pleasure should be in column 3 in row 1
* There should only be 1 row

![Screen Shot 2021-02-18 at 10 04 00 AM](https://user-images.githubusercontent.com/12568665/108376304-decc4f80-71d0-11eb-9435-1507ed82038c.png)

### Link to a minimal reproduction:

1. Visit https://github.com/syntaxrecall/syntaxrecall
2. Check out branch "tailwind-issue"
3. Navigate to page http://localhost:3000/screen

**Comment by debrice** [comment]
Hi @chadalen,

I'm not totally sure what's the issue but I've [validated](https://validator.w3.org/nu/#textarea) your [source-code](https://raw.githubusercontent.com/syntaxrecall/syntaxrecall/tailwind-issue/data/content/screen.html) and it seems that you might have some hidden characters (error `Misplaced non-space characters inside a table`) in your source code. I've [purged your source code here](https://play.tailwindcss.com/53lfYKAjUn)  and things seem to be behaving then.

Hope that helps,

Source code: https://raw.githubusercontent.com/syntaxrecall/syntaxrecall/tailwind-issue/data/content/screen.html
HTML validator: https://validator.w3.org/nu/#textarea
Cleaned-up demo: https://play.tailwindcss.com/53lfYKAjUn

**Comment by chadalen** [comment]
> Hi @chadalen,
> 
> I'm not totally sure what's the issue but I've [validated](https://validator.w3.org/nu/#textarea) your [source-code](https://raw.githubusercontent.com/syntaxrecall/syntaxrecall/tailwind-issue/data/content/screen.html) and it seems that you might have some hidden characters (error `Misplaced non-space characters inside a table`) in your source code. I've [purged your source code here](https://play.tailwindcss.com/53lfYKAjUn) and things seem to be behaving then.
> 
> Hope that helps,
> 
> Source code: https://raw.githubusercontent.com/syntaxrecall/syntaxrecall/tailwind-issue/data/content/screen.html
> HTML validator: https://validator.w3.org/nu/#textarea
> Cleaned-up demo: https://play.tailwindcss.com/53lfYKAjUn

You fixed it! Sweet man thanks! That actually makes sense. I was manipulating some of the dom with Quokka.js then printed the dom in the console then I copied that. Still strange it did that but at least now I know exactly what the issue is. Thanks again I'll close this issue. :)
