### ISSUE TITLE
transition-all is animating rounded-3xl

### ISSUE THREAD

**Issue by ItzaMi** [tailwindlabs/tailwindcss#3624]
So, I'm using the PETAL stack on a project and I was styling a div and something weird happens

As you can see (gif below), the corners start straight and end up round when they should actually be round right out of the start. And I don't completely understand what's happening.

![behance](https://user-images.githubusercontent.com/30603437/108600056-9ce80880-738c-11eb-9284-6858472a3ca9.gif)

My code is looking like this:
```
<div class="w-64 h-40 relative flex justify-center items-center bg-gradient-to-tr from-blue-700 to-blue-100 ring-blue-500 rounded-3xl shadow-lg ring-8 ring-blue-500 ring-opacity-0 transition-all duration-500 ease-in-out hover:ring-opacity-10 hover:opacity-90 cursor-pointer">
      <%= if @behance == 0 do %>
        <div class="w-6/12 h-6 bg-white bg-opacity-50 rounded-full animate-pulse"></div>
      <% else %>
        <p class="text-white font-bold text-3xl cursor-pointer"><%= @behance %> likes</p>
      <% end %>
      <p class="absolute bottom-3 text-white font-extralight text-lg cursor-pointer">Behance</p>
</div>
```

I thought that the culprit could be the `if - else` but if I do this the same thing happens ([playground link](https://play.tailwindcss.com/KeJ4fcduJf))
```
<div class="w-64 h-40 relative flex justify-center items-center bg-gradient-to-tr from-blue-700 to-blue-100 ring-blue-500 rounded-3xl shadow-lg ring-8 ring-blue-500 ring-opacity-0 transition-all duration-500 ease-in-out hover:ring-opacity-10 hover:opacity-90 cursor-pointer">
      <div class="w-6/12 h-6 bg-white bg-opacity-50 rounded-full animate-pulse"></div>
</div>
```

It seems that if I remove the `transition-all` that it will work fine so I guess that this property is also making the transition for `border-radius` (?). I would like to keep my transitions on over for the `ring-opacity` and `opacity` but can't figure out how I can name both without using `transition-all`.
How can I work around this?

**Comment by debrice** [comment]
@ItzaMi I've tried the playground link you've provided but cannot see the bug you're reporting. What OS and browser are you using?

I've attempted to reproduce your bug without success on MacOS 11.2.1 (Big Sur) with:
- Chrome 88.0.4324.182
- Firefox 85.0.2
- Safari 14.0.3

**Comment by ItzaMi** [comment]
Using MacOS 10.15.5 (Catalina) on Chrome 88.0.4324.182. Also tested on Firefox Developer Edition 86.0
The playground link doesn't showcase this bug as well, I'm aware of that, but wanted to leave a bit of reproducible code with my issue.

Locally, if I increase the `duration` to `duration-1000` I can see, loading the page, the div with `rounded-3xl` takes a bit longer to become rounded.

I'm not really sure on out to report this any further, sadly, so if I could get a solution to transition both `opacity` and `ring-opacity` without using `transition-all`, I would be very happy

**Comment by Rebecca01013** [comment]
Not all of these are required to build a transition, with the first three are the most popular. In the example below the box will change its background color over the process.

**Comment by bradlc** [comment]
Hey @ItzaMi, "rings" in Tailwind CSS are achieved using the `box-shadow` CSS property. To transition `box-shadow` you would need to customise your `transitionProperty` config:

```js
module.exports = {
  theme: {
    extend: {
      transitionProperty: {
        custom: 'opacity, box-shadow',
      },
    },
  },
}
```

Then use it like this:

```html
<div class="ring ring-black ring-opacity-0 hover:opacity-90 hover:ring-opacity-10 transition-custom duration-1000"></div>
```

And here's a demo using your example, I have just changed `transition-all` to `transition-custom`: https://play.tailwindcss.com/PTQclPk5Sj (be sure to take a look at the config tab too!)

**Comment by adamwathan** [comment]
Just using the `transition` class should handle transitioning the ring for you:

https://play.tailwindcss.com/ONFppOucH4

It will transition box shadows already 👍🏻
