### ISSUE TITLE
Referencing values from the same top-level key doesn't work

### ISSUE THREAD

**Issue by micbra** [tailwindlabs/tailwindcss#3650]
I'm trying to modify my Tailwind config to create some custom classes. For example, I'd like to have a `primary` class, which itself references one of the predefined color values.

To do so, I want to utilize the `theme()` helper function and put the following inside my tailwind.config.js:
```javascript
  theme: {
    colors: theme => ({
      red: '#f00',
      primary: theme('colors.red')
    }),
  }
```

But it doesn't seem possible to reference a value from `colors` from inside the `colors` property.
All I get is a **Maximum call stack size exceeded** Error whichs boils down to the resolvePath function (tailwindcss/lib/util/resolveConfig.js:127:45) further down in the call stack.

Here is a [minimal repro case](https://play.tailwindcss.com/f1CbApqQWd?file=config)

**Comment by bradlc** [comment]
Hey @micbra. Unfortunately what you're trying to do is not possible because it results in infinite recursion. One solution is to define your colors at the top of your config file:

```js
const colors = {
  red: '#f00',
  green: '#0f0',
  blue: '#00f',
}

module.exports = {
  theme: {
    colors: {
      ...colors,
      primary: colors.red,
    },
  },
}
```

**Comment by NoelDeMartin** [comment]
Is there a way to reference default values when extending? 

I'd like to do this, but it doesn't work as reported in this issue:

```js
module.exports = {
  theme: {
    extend: {
        spacing: theme => ({
            13: `calc(${theme('spacing.12')} + ${theme('spacing.1')})`,
        }),
    },
};
```

I ended up doing it like this, but I don't like it as much:

```js
const { theme: { spacing } } = require('tailwindcss/defaultConfig');

module.exports = {
  theme: {
    extend: {
        spacing: theme => ({
            13: `calc(${spacing['12']} + ${spacing['1']})`,
        }),
    },
};
```
