### ISSUE TITLE
Safari: TextColor for disabled inputs not applied correctly

### ISSUE THREAD

**Issue by preeco-privacy** [tailwindlabs/tailwindcss#3683]
### Describe the problem:

There is a problem in Safari with disabled inputs and text color. Sometimes the text color is not applied correctly.

Example: 

```
<input class="bg-gray-30 text-gray-50 appearance-none" value="hello world" disabled> 
```
```
module.exports = {
  theme: {
    extend: {
      colors: {
        gray: {
          30: '#EDEEEE',
          50: '#D5D5D5',
        },
      },
    },
  },
  variants: {},
  plugins: [],
}
```

I expect the text color to be darker than the background. However, the text color is much more brighter, it looks like white. 

 
![Bildschirmfoto 2021-03-04 um 21 39 54](https://user-images.githubusercontent.com/60985974/110028259-50f57600-7d33-11eb-9379-f8ef0f236454.png)

It does not happen with most other combinations of background and text-color. Most of the combinations work fine, but the combination above doesn't. 

The problem only occurs on Safari. In Chrome and Firefox it works fine. 

### Link to a minimal reproduction:

See this link:  https://play.tailwindcss.com/5WeFgrDifM

### Possible solution: 

It works correctly if you add the following to your css: `-webkit-text-fill-color: #D5D5D5`. `#D5D5D5` is the gray of `gray-50` from the config.

**Comment by adamwathan** [comment]
Hey! Wow this is a truly weird one but I can reproduce this with just vanilla CSS without using Tailwind at all:

https://jsfiddle.net/gsb8twLk/3/

So unfortunately I think this is a Safari bug :( Going to close because I don't think there's much we can do without adding `-webkit-text-fill-color` everywhere which just feels too drastic to me :/
