### ISSUE TITLE
PurgeCSS upgrade necessary to avert FullHuman/purgecss#303

### ISSUE THREAD

**Issue by boardfish** [tailwindlabs/tailwindcss#3711]
### Describe the problem:

I'm trying to use `.checkbox_field input[type="checkbox"]` as a selector. The declaration is incorrectly purged by PurgeCSS.

### Link to a minimal reproduction:

To come if necessray, but I've established that an upgrade to the `postcss-purgecss` dependency will be the fix as discussed in FullHuman/purgecss#303.

For now, surrounding the style declaration in `/* purgecss start ignore */` `/* purgecss end ignore */` also works.

**Comment by adamwathan** [comment]
Should be fixed in next release (if not already) as we upgraded this dependency a while ago 👍🏻
