### ISSUE TITLE
`display: inline-grid` is missing

### ISSUE THREAD

**Issue by mikemaccana** [tailwindlabs/tailwindcss#3721]
### Describe the problem:

`display: inline-grid` is missing - see https://tailwindcss.com/docs/display

Just an FYI. Obviously I can work around this by not using Tailwind for `display`. 🙂

**Comment by alexanderbluhm** [comment]
@mikemaccana It is included 🤔 
![image](https://user-images.githubusercontent.com/6071634/110633191-c2587d00-81a8-11eb-9030-c5e08b1f07dd.png)

**Comment by mikemaccana** [comment]
hah didn't realise the list scrolled (and scrolling the mouse moved the page). here's what my browser window looked like:

![image](https://user-images.githubusercontent.com/172594/110653684-63e5cb80-81b5-11eb-8d8e-44ddce51be5d.png)
