### ISSUE TITLE
Stop adding automatic leading for font-size classes

### ISSUE THREAD

**Issue by wesleylopex** [tailwindlabs/tailwindcss#3722]
Stop adding automatic line-height for font-size classes please. WHen I want to add leading font titles, it already has an automatic line height so classes like "leading-8" do not work properly. Stop adding auto styles for this things please, it`s annoing. OMG!
If I want to automatic styles, I would use Bootstrap, I think Tailwind should not do that anymore.

**Comment by adamwathan** [comment]
No plans to change this, has been discussed tons of times before, please search.

**Comment by adamwathan** [comment]
Previous discussion: https://github.com/tailwindlabs/tailwindcss/issues/2603#issuecomment-711094158

**Comment by wesleylopex** [comment]
So what is the best solution when I want to add different line height?
For example `<h1 class="text-4xl leading-relaxed">Test</h1>`.

The example above will not work with the line height I specified.

**Comment by adamwathan** [comment]
Yes it does:

https://play.tailwindcss.com/wx5VjAMCEZ

**Comment by audacioustux** [comment]
@adamwathan it doesn't with screens (sm,md,lg..) https://play.tailwindcss.com/XGntKy3ZLV
![image](https://user-images.githubusercontent.com/7238675/112757705-bbd15e80-900c-11eb-805d-16a625012205.png)
