### ISSUE TITLE
Space utilities not working properly with `flex-row-reverse` and `flex-col-reverse`

### ISSUE THREAD

**Issue by GavHern** [tailwindlabs/tailwindcss#3724]
### Describe the problem:

When using the flex reverse utilities and the space utilities, the spacing added doesn't work properly. The first item (far right) has no margin while the last item (far left) has additional spacing where there shouldn't be. I'm running the latest version of Google Chrome.

![image](https://user-images.githubusercontent.com/47736824/110553898-a0022900-80ee-11eb-806f-ea88553a2a6b.png)

This div has the classes `flex`, `flex-row-reverse` and `space-x-8`; amongst other classes to make it look nicer

### Link to a minimal reproduction:

[Link to Tailwind Play](https://play.tailwindcss.com/1b66tCIX5g)

**Comment by adamwathan** [comment]
Hey! You'll want to use the `space-x-reverse` utility when switching the direction of the flex container:

https://tailwindcss.com/docs/space#reversing-children-order
