### ISSUE TITLE
Tailwind lodash vulnerability

### ISSUE THREAD

**Issue by bennetfabian** [tailwindlabs/tailwindcss#3757]
### Describe the problem:

When installing Tailwind using `npm install -D tailwindcss@latest postcss@latest autoprefixer@latest` as in the documentation on installing, it says there are **4 high severity vulnerabilities**.
When I run `npm audit` it outputs:

```
bennetfabian@MacBook-Pro-von-Bennet tailwind-demo % npm audit                                                           
npm audit report

lodash  <=4.17.18
Severity: high
Prototype Pollution - https://npmjs.com/advisories/1065
Prototype Pollution - https://npmjs.com/advisories/1523
Prototype Pollution - https://npmjs.com/advisories/782
No fix available
node_modules/datasette/node_modules/lodash
node_modules/lodash
  datasette  *
  Depends on vulnerable versions of lodash
  node_modules/datasette
  flaschenpost  <=2.1.0
  Depends on vulnerable versions of lodash
  node_modules/flaschenpost
  tailwind  *
  Depends on vulnerable versions of lodash
  node_modules/tailwind

4 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.
```

### Link to a minimal reproduction:

I'm running macOS Big Sur 11.2.1, NodeJS v15.11.0 and npm 7.6.3. If needed, I could also upload the whole repo but I don't think that's really necessary for this kind of issue.

**Comment by Anoroc** [comment]
Same issue. Updating to the latest version of lodash didn't provide a solution.

**Comment by bennetfabian** [comment]
Weird, I tried it again today in another directory and it worked without npm complaining about anything. Auditing now also shows zero vulnerabilities. 🤷🏼
