### ISSUE TITLE
Package installation size is growing quite big

### ISSUE THREAD

**Issue by Siilwyn** [tailwindlabs/tailwindcss#3765]
### Describe the problem:
The package install size is [35 MB](https://packagephobia.com/result?p=tailwindcss). Reducing the size will help install speed and save some bandwidth.
[![install size](https://packagephobia.com/badge?p=tailwindcss)](https://packagephobia.com/result?p=tailwindcss)

### Potential solutions:
1. The biggest directory is `tailwindcss/dist`: 30MB. Looks like it contains both source and minified CSS files, possible unneeded duplicates?
2. Lodash takes up 5MB which looking at `npm ls` is only directly being used, it's possible to only install the used lodash functions with subpackages like `lodash.merge`. For convenience these could all be imported in one file which exports all functions.

### Minimal reproduction:
Easy way to test locally is in a temporary directory:
```sh
cd /tmp
mkdir tailwindcss-size
cd tailwindcss-size
npm install tailwindcss
ls node_modules
```

**Comment by adamwathan** [comment]
Yeah the files in `dist` are the big culprit here, and unfortunately we can't remove those without it being a breaking change. Those files are effectively our CDN builds, and we rely on them being published to npm in order for people to use Tailwind via UNPKH or JSDelivr.

I think we can trim a lot of that down for v3.0 in the fall though. Added it to my list of breaking changes to make when the time comes, but going to close this as "actioned" for my own purposes.
