### ISSUE TITLE
Tailwind should issue a warning if purge globs don't match anything

### ISSUE THREAD

**Issue by travigd** [tailwindlabs/tailwindcss#3770]
Admittedly this straddles the line between bug report and feature request, so feel free to close if not appropriate.

### Describe the problem:

I just spent an embarrassing amount of time trying to figure out why my configuration was broken and the culprit ended up being bad globs in the `purge` field of `tailwind.config.js` (tl;dr: I said `./components/...` instead of `./src/components/...`).

It would be nice™ if Tailwind would warn on this.

### Link to a minimal reproduction:

I don't think a reproduction is necessary for this.

**Comment by cfurrow** [comment]
Not a bad idea, but I wonder if this is more of a [purgecss](https://github.com/FullHuman/purgecss) issue that could instead be bubbled up inside of tailwindcss. For example, purge, once it has its list of globs, tries to count the number of files across those blobs, and if 0, warn the user "hey, you wanted me to watch these places for file changes, but I don't see any files there".

FYI: Tailwind defers the purging to `purgecss` within `src/lib/purgeUnusedStyles.js`, if you wanted to see the code. I've not checked out the source for `purgecss` yet to see if there are easy inroads there for modifications like you mention.

**Comment by travigd** [comment]
Opened this on PurgeCSS. :)

https://github.com/FullHuman/purgecss/issues/642
