### ISSUE TITLE
Javascript created tailwind class not working in production

### ISSUE THREAD

**Issue by binoiii** [tailwindlabs/tailwindcss#3779]
![local-env](https://user-images.githubusercontent.com/54553660/111653069-90978400-8842-11eb-85f0-2d17a453bf5d.png)
![prod-env](https://user-images.githubusercontent.com/54553660/111653074-92614780-8842-11eb-9bd7-548fc53747dd.png)

### Describe the problem:

Code in creating tailwind class

const tailwindColor = color === "black" ? "bg-" + color : "bg-" + color + "-450"

    <button
      className={`${
        isActive && "ring-1 ring-gray-400 opacity-100"
      } ${tailwindColor} opacity-30 p-2 mx-1 rounded-full outline-none focus:outline-none text-xs`}
      onClick={() => handleSelected(option)}
      aria-label="color option"
    ></button>

The colors are added in tailwind.config.js

colors: {
        orange: {
          450: "#ca7919",
        },
        yellow: {
          450: "#FEF08A",
        },
        blue: {
          450: "#0C4A6E",
        },
        red: {
          450: "#EF4444",
        },

This works in local. However, it doesn't work in production.

### Link to a minimal reproduction:

Component Link: https://github.com/binoiii/hhmnl-app/blob/master/src/components/order/orderOptionsColor.js
Tailwind Config Link: https://github.com/binoiii/hhmnl-app/blob/master/tailwind.config.js

**Comment by royvanv** [comment]
Your code is not purgeable. Check out the [Writing purgeable HTML](https://tailwindcss.com/docs/optimizing-for-production#writing-purgeable-html) section for more information.

You need to either add them to the [`safelist` option of PurgeCSS](https://tailwindcss.com/docs/optimizing-for-production#purge-css-options) or add them to your code (for example in an array of allowed colors).

**Comment by bradlc** [comment]
@royvanv nailed it! 🙌

**Comment by binoiii** [comment]
thanks for the feedback @royvanv! appreciate it. 🙏
