### ISSUE TITLE
Default border colour opacity doesn't work with CSS variables when being grabbed via theme() helper

### ISSUE THREAD

**Issue by Cephyric-gh** [tailwindlabs/tailwindcss#3782]
### Describe the problem:

When using CSS variables to define colours (alongside the process to allow Tailwind's opacity classes to function with them) generates a broken default value for borders when 1 of those colours is grabbed via the `theme()` helper.

To cut down on a bunch of noise (as I am generating big colour maps dynamically, my tailwind config ends up looking something like:

```Javascript
module.exports = {
    theme: {
        colors: {
            gray: {
                ...
                300: ({opacityVariable, opacityValue}) => `rgba(var(--color-gray-300), ${typeof opacityValue !== 'undefined' ? opacityValue : `var(${opacityVariable}, 1)`})`
                ...
        },
        ...
        borderColor: theme => ({
            ...theme('colors'),
            DEFAULT: theme('colors.gray.300')
        }
    }
}
```

This causes the following to be generated in css:

```CSS
*, :after, :before {
    box-sizing: border-box;
    border: 0 solid rgba(var(--color-gray-300),var(undefined,1));
}
```

Which results in browsers ignoring it, and subsequently _a lot_ of things that previously had no border suddenly do. This seems to only affect 2.0.3+, as I have a different project with the exact same setup, but was done on 2.0.2 and it doesn't have a default colour attached to global borders (which I think is because there was a bug with the `theme()` helper and values being variables not being executed, which was fixed in 2.0.3).

To compound things, it also specifically seems to only happen when I have purge active, purge config being:

```Javascript
    purge: {
        enabled: guessProductionMode(),
        layers: ['components', 'utilities'],
        content: ['./projects/**/*.html', './projects/**/*.ts'],
        options: {
            fontFace: false,
            keyframes: false,
            variables: false,
            safelist: {
                greedy: [
                    /^(?:sm|md|lg|xl|2xl)?(?::)?(?:col|row|offset|order)(?:-)?(?:auto|[0-9]{1,2})?$/,
                    /^(?:sm|md|lg|xl|2xl)?(?::)?w-(?:auto|full|[0-9]{1,2}\/[0-9]{1,2}|[0-9]{1,3})$/,
                    /^(?:sm|md|lg|xl|2xl)?(?::)?bg-(?:[a-zA-Z]+)-(?:100|200|300|400|500|600|700|800|900)?$/,
                ],
            },
        },
    },
```

I'm currently having to force the default border colour by manually typing out the rgba value, but feels clunky doing that, as it otherwise seems to work elsewhere (that the correct opacity variable is being passed to the colour), for example using the border colour class explicitly (via `border-gray-300`) on an element correctly sets it

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

As @toothbrush7777777 mentioned, the issue is that in certain scenarios you create an invalid `undefined` value. 
Here is an updated play that should work how you want it to work: https://play.tailwindcss.com/XiK416PXdH?file=config
