### ISSUE TITLE
Supporting from Android V5

### ISSUE THREAD

**Issue by alikenski** [tailwindlabs/tailwindcss#3788]
There are some problem with supporting Android v5 and v6 smartphones. In some block the background is transparent.  In project included dark mode, but I can not understand is this reason.

For example div block has class bg-white. "white" is configured in tailwind.config.js file.

`module.exports = {
    purge: [],
  darkMode: 'media',
  theme: {
    boxShadow: {},
    colors: {
      white: '#ffffff',
    },
    extend: {}
  },
  variants: {
    backgroundColor: ['responsive', 'hover', 'focus', 'active', 'dark'],
  },
  plugins: []
};
`

**Comment by bradlc** [comment]
Closing this as it's dated and no reproduction was provided. Please open a new issue with a minimal reproduction if you're still having problems 👍
