### ISSUE TITLE
@tailwindcss/jit not working when configured in postcss.config.js

### ISSUE THREAD

**Issue by acatzk** [tailwindlabs/tailwindcss#3791]
### This is my dependencies and I already installed @tailwindcss/jit

![image](https://user-images.githubusercontent.com/38458781/111783946-bf226700-88f5-11eb-8d70-60ccc687bf48.png)

# I Followed the Instruction given by the
https://www.npmjs.com/package/@tailwindcss/jit

But when I try to replace  the **tailwindcss** object
```
 // postcss.config.js
  module.exports = {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
    }
  }
```
Inside the postcss.config.js 
INTO THIS **@tailwindcss/jit** object
```
  // postcss.config.js
  module.exports = {
    plugins: {
      '@tailwindcss/jit': {},
      autoprefixer: {},
    }
  }

```

and when I try again to run using 
yarn dev

**It got me this error**

```
error - ./src/styles/tailwind.css ((webpack)/css-loader/cjs.js??ref--5-oneOf-6-1!(webpack)/postcss-loader/cjs.js??ref--5-oneOf-6-2!./src/styles/tailwind.css)
Error: ENOENT: no such file or directory, stat '/media/acatzk/Hard%20Drive/backup/React-Projects/joshuagalit.com/src/styles/tailwind.css'
```

DOES IT EFFECT WHEN YOU TRY TO ADD jsconfig.json?
because i have this code and file structure 

![tempo](https://user-images.githubusercontent.com/38458781/111785410-884d5080-88f7-11eb-9a17-ed7c4fe1dec3.png)

PLEASE HELP ME I NEED THIS KIND OF FILE STRUCTURE

**Comment by acatzk** [comment]
By the way I am using Next.js

**Comment by cfurrow** [comment]
I created a sample NextJS project similar to what I could see from your screenshots, and I do not get an error when starting `next dev`. 

See the sample app here: https://github.com/cfurrow/tailwindcss-issue-3791

**Comment by acatzk** [comment]
try import your globals.css with '~/styles/global.css' because we are
trying to use jsconfig.json are we not to do that?

**Comment by cfurrow** [comment]
Is your current project located here?

`/media/acatzk/Hard%20Drive/backup/React-Projects/joshuagalit.com` 

How are you importing tailwindcss into your nextjs app?  Looks like you have an `_app.js`--is that where you're doing it? What does your `import` string look like?

**Comment by acatzk** [comment]
It shows an error to me again... I think i have a problem with my machine

**Comment by acatzk** [comment]
I put my files inside my hard drive that located here
/media/acatzk/Hard%20Drive/backup/React-Projects/joshuagalit.com

I think i need to move my files in my bootable drive ssd

**Comment by cfurrow** [comment]
Yeah, I think it would be best for all your files to exist in the same project directory, not be spread across multiple drives. I would suggest doing that first, and then see if you still have the error once your files are organized.

**Comment by acatzk** [comment]
I moved my project files in the bootable drive... and it works... HAHA
