### ISSUE TITLE
@variants is not working

### ISSUE THREAD

**Issue by christhofer** [tailwindlabs/tailwindcss#3816]
### What version of Tailwind CSS are you using?

2

### What version of Node.js are you using?

15

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://play.tailwindcss.com/LOerLp6NgN?file=css

So I was looking around the documentation and want to try this directive
https://tailwindcss.com/docs/functions-and-directives#variants

The style just applied right away, not just on hover.

I expect the `Button 1` should work like the `Button 2`

**Comment by adamwathan** [comment]
Hey! I think you have the wrong understanding of what `variants` does, it doesn't style something for a specific state like you are suggesting, it creates a variant of that class that only applies at a specific state.

For example, you have `opacity-50` and `focus:opacity-50` in Tailwind. `opacity-50` applies opacity all the time. `focus:opacity-50` only applies opacity when the element is focused.

Using `variants` creates new versions of your classes like that.

So this code:

```css
@variants hover {
  .btn {
    @apply bg-gray-100 text-black;
  }
}
```

Generates this output:

```css
.btn {
  background: #F3F4F6;
  color: black;
}
.hover\:btn:hover {
  background: #F3F4F6;
  color: black;
}
```

It doesn't add hover styles to your button, it gives you a new class that lets you make something look like `btn` but only when that element is hovered.

Hope that's clear, you're not the first person to ask this and it's a bit of a mental shift at first!

**Comment by christhofer** [comment]
I see
Thank you for the explanation.
