### ISSUE TITLE
Error on build when using a plugin and attempting to extend with a custom variant

### ISSUE THREAD

**Issue by andybee** [tailwindlabs/tailwindcss#3830]
### What version of Tailwind CSS are you using?

2.0.3

### What version of Node.js are you using?

12.21.0

### What browser are you using?

N/A

### What operating system are you using?

macOS

### Reproduction repository

https://www.youtube.com/watch?v=5Tdokh1KYuQ

With the following config:

```
variants: {
    extend: {
      block: ['target'],
    },
  },
  plugins: [
    plugin(({ addVariant, e }) => {
      addVariant('target', ({ modifySelectors, separator }) => {
        modifySelectors(({ className }) => `.${e(`target${separator}${className}`)}:target`);
      });
    }),
  ],
```

I get `🚫 TypeError: variantsValue is not iterable` when trying to build.

My goal is just to add a `target:block`, just in case this is completely the wrong way to do it!

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The `block` utility is part of the `display` utilities https://tailwindcss.com/docs/display
Therefore your config should look like this instead:

```diff
 variants: {
   extend: {
-    block: ['target'],
+    display: ['target'],
   }
 }
```

More information on extending this: https://tailwindcss.com/docs/display#customizing
