### ISSUE TITLE
"Unknown error from PostCSS plugin." after enabling JIT 

### ISSUE THREAD

**Issue by aamibhoot** [tailwindlabs/tailwindcss#3831]
### What version of Tailwind CSS are you using?

2.0.4

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Brave, Safari

### What operating system are you using?

macOS

### Reproduction repository

NaN

Hi, 
I was just tried to use JIT with NextJs but It always crashes when I use `img`. 

**ERROR 👇**
`Unknown error from PostCSS plugin. Your current PostCSS version is 8.1.7, but postcss-preset-env uses 7.0.35. Perhaps this is the source of the error below.
error - ./styles/globals.css ((webpack)/css-loader/cjs.js??ref--5-oneOf-6-1!(webpack)/postcss-loader/cjs.js??ref--5-oneOf-6-2!./styles/globals.css)
RangeError: Maximum call stack size exceeded
    at Function.keys (<anonymous>)
`

**postcss.config.js 👇**
`module.exports = {
  plugins: [
    "@tailwindcss/jit",
    [
      "postcss-preset-env",
      {
        autoprefixer: {
          flexbox: "no-2009",
        },
        stage: 3,
        features: {
          "custom-properties": false,
        },
      },
    ],
  ],
};
`

**package.json 👇**
`
"devDependencies": {
    "@tailwindcss/jit": "^0.1.3",
    "autoprefixer": "^10.2.5",
    "postcss": "^8.2.8",
    "tailwindcss": "^2.0.4"
  }
`

Am I doing something wrong?

**Comment by adamwathan** [comment]
Should be fixed in more recent versions of the JIT library, make sure you `npm install @tailwindcss/jit@latest`.
