### ISSUE TITLE
Variant cannot be generated because selector contains no classes. When using [attribute] in post css

### ISSUE THREAD

**Issue by terryupton** [tailwindlabs/tailwindcss#3837]
### What version of Tailwind CSS are you using?

^2.0.3

### What version of Node.js are you using?

v15.5.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://www.youtube.com/watch?v=NbVJU1CuM0Q

I have the following postCSS file called `xcloak.pcss` and this is being imported into my main style.pcss like so:
```
@import "tailwindcss/base";
@import "./base/framework.pcss";
@import "./base/legacy.pcss";

@import "./base/xcloak.pcss";
@import "./base/helpers.pcss";

@import "tailwindcss/components";
@import "./components/outdated-browser-notice.pcss";

@import "tailwindcss/utilities";

```

Within my `xcloak.pcss` file is the following css:
```
@layer utilities {
    @responsive {

        [x-cloak] {
            display: none;
        }

        [x-cloak] .x-cloak--hidden {
            display: none;
        }

        [x-cloak] .x-cloak--block {
            display: block;
        }

        [x-cloak] .x-cloak--inline {
            display: inline;
        }

        [x-cloak] .x-cloak--inlineBlock {
            display: inline-block;
        }

        [x-cloak] .x-cloak--invisible {
            visibility: hidden;
        }
    }
}
```

I have the following inside my `postcss.config.j` file:
```
module.exports = {
  plugins: [
    require('postcss-import'),
    require('postcss-nested'),
    require('tailwindcss'),
    require('autoprefixer'),
  ]
};
```
I have tried the postcss-nested package both before and after the tailwindcss.
However, I keep hitting the same issue/error:
```
/src/css/base/xcloak.pcss Variant cannot be generated because selector contains no classes.

 @responsive {
  18 | 
> 19 |         [x-cloak] {
     |         ^
  20 |             display: none;
  21 |         }
```

Thank you.

**Comment by adamwathan** [comment]
Hey! This just doesn't really make sense when you actually think about how it would have to work. A responsive version of an attribute would have to look like this:

```
<div sm:x-cloak>
```

Alpine won't actually respect that or know what it means.

Variants can only work on classes I'm afraid, just the only thing that makes any technical sense.

**Comment by terryupton** [comment]
Hey @adamwathan you are completely right! 
Sorry about that. I should have thought about for a bit longer 😂
