### ISSUE TITLE
Enabling variants in Nuxtjs environement don't work (+opacity values ignored)

### ISSUE THREAD

**Issue by Velka-DEV** [tailwindlabs/tailwindcss#3838]
### What version of Tailwind CSS are you using?

3.4.3

### What version of Node.js are you using?

14.15.4

### What browser are you using?

Edge, Fire, Opera

### What operating system are you using?

Windows 10

### Reproduction repository

https://www.youtube.com/watch?v=uD4izuDMUQA

Hi, i'm trying to enable the tailwinds css variants in a nuxt website but that don't work at all.

Here is my tailwindcss.config.js file:

`module.exports = {
  important: true,
  future: {
    // removeDeprecatedGapUtilities: true,
    // purgeLayersByDefault: true,
  },
  purge: [],
  theme: {},
  variants: {
    extend: {
      backgroundColor: ['even'],
      backgroundColor: ['odd'],
      visibility: ['hover', 'focus'],
      opacity: ['hover', 'focus']
    }
  },
  plugins: []
}
`

For example i try to use them as here:
`
<div class="bg-black opacity-0 hover:opacity-70 h-full w-full"> 
    <h3 class="text-center">I'm a title</h3>
</div>
`

I noticed when i try the opacity-70 without the hover:, the element is fully black, so the opacity don't work also.

even: & odd: not working also

If someone can help me i will really appreciate

**Comment by adamwathan** [comment]
Hey! There is no such version as Tailwind v3.4.3, the latest version is v2.0.4. Are you perhaps on v1.x? If so the `extend` option under `variants` was only added in v2.0. Also none of the `future` stuff exists in v2.0, which is what made me think perhaps you're on v1.x still.

**Comment by Velka-DEV** [comment]
Thanks for your help ! 

I was looking the package version of the Nuxt Tailwindcss module. After updating postcss and tailwind, the variants works but that broked a lot my UI. 

Thanks for your help again
