### ISSUE TITLE
-mt-14 does not apply 

### ISSUE THREAD

**Issue by eevanwong** [tailwindlabs/tailwindcss#3844]
### What version of Tailwind CSS are you using?

v1.8.12

### What version of Node.js are you using?

v11.11.3

### What browser are you using?

Firefox

### What operating system are you using?

Windos

### Reproduction repository

https://www.youtube.com/watch?v=5HFehFpU_8M 

Hey, this is a very minor issue but I haven't been able to find a solution to this so perhaps it might be a bug? I'm trying to fine tune my frontend using `-mt-14` in my css classes, but it does not seem to apply 

I believe this means that there is no existing class? Or there is something wrong locally that I'm not seeing.

![image](https://user-images.githubusercontent.com/71536798/112532153-ddb5b180-8d7e-11eb-95e3-0b65a077cf66.png)

![image](https://user-images.githubusercontent.com/71536798/112532566-59176300-8d7f-11eb-9f72-b7584c8efd9d.png)

**Comment by fedeci** [comment]
Hi @eevanwong, if you are not extending the default tailwind configuration `-mt-14` is not a class.

**Comment by eevanwong** [comment]
Ah actually it may have been due to it being an older version of tailwind. 14 was not found in the spacing object in the tailwind css node module. I'll update the library and see how it works out.

**Comment by eevanwong** [comment]
Yeap it works. Closing thread.
