### ISSUE TITLE
BOX ALIGNMENT - Justify Items : justify-items-auto not supported by google chrome

### ISSUE THREAD

**Issue by devhoussam** [tailwindlabs/tailwindcss#3855]
### What version of Tailwind CSS are you using?

v2.0.4

### What version of Node.js are you using?

v12.0.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### Reproduction repository

https://i.imgur.com/Pl7I3Gv.png

![Image](https://i.imgur.com/Pl7I3Gv.png)

**Comment by fedeci** [comment]
Hi @devhoussam, what version of chrome are you using? Can you share a reproduction repo or the affected code, please?

**Comment by devhoussam** [comment]
> Hi @devhoussam, what version of chrome are you using? Can you share a reproduction repo or the affected code, please?

**Google Chrome Version : 89.0.4389.90**
**Windows 10**

![Image](https://i.imgur.com/k0r7dxI.png)

as you can see in this example the `place-items-auto` Utility class not supported on chrome.

```
.place-items-auto {
    place-items: auto;
}
```

**Comment by fedeci** [comment]
I think that since `auto` does not apply any specific behavior it is considered as invalid property (is like specifying nothing).

**Comment by devhoussam** [comment]
> I think that since `auto` does not apply any specific behavior it is considered as invalid property (is like specifying nothing). Not sure though.

maybe maybe not so what is the solution because it is an Utility class supported by Tailwind CSS so I will keep searching to find how can I fix it.

**Comment by adamwathan** [comment]
Yep looks like MDN lies about this, as far as I can tell in my own testing there is no actual `auto` value unless it's just in the spec and no browsers support it.

I would just not use it, we'll likely just remove it from Tailwind since it does nothing.

**Comment by fedeci** [comment]
Isn't it useful with breakpoints?
eg.
`sm:align-items-left md:align-items-auto`

**Comment by adamwathan** [comment]
Well it doesn't exist so it can't really be useful 😅  `align-items: auto` isn't understood by the browser:

<img width="183" alt="image" src="https://user-images.githubusercontent.com/4323180/112723327-3a7eac80-8ee4-11eb-9c62-dadef5b58864.png">

Instead you just want to explicitly set it to the value you want, like `align-items: start` which is the default 👍

**Comment by fedeci** [comment]
> The value used is the value of the justify-items property of the parents box, unless the box has no parent, or is absolutely positioned, in these cases, auto represents normal.

From [mozilla docs](https://developer.mozilla.org/en-US/docs/Web/CSS/place-items) 🤔

**Comment by adamwathan** [comment]
Yeah but those docs are wrong which is what we have learned in this issue 😅 I added it originally because it was included in MDN, but it doesn't actually work in any browser as evident in the screenshot, hah.

**Comment by devhoussam** [comment]
> Yeah but those docs are wrong which is what we have learned in this issue 😅 I added it originally because it was included in MDN, but it doesn't actually work in any browser as evident in the screenshot, hah.

This is what it looks like to me too, so I think it would be better if it were removed from the doc

**Comment by fedeci** [comment]
> Yeah but those docs are wrong which is what we have learned in this issue 😅 I added it originally because it was included in MDN, but it doesn't actually work in any browser as evident in the screenshot, hah.

Well yes😁, but if the default behavior is the one specified there (where normaly it is `start` but if the box is absolutely positioned it is `normal`) then we can't just expect the users to adopt `start` as the default value because the default value is relative to the context. I don't know if I explained well or if my thoughts have sense😂.

**Comment by alpadev** [comment]
> Yep looks like MDN lies about this, as far as I can tell in my own testing there is no actual `auto` value unless it's just in the spec and no browsers support it.
> 
> I would just not use it, we'll likely just remove it from Tailwind since it does nothing.

`auto` isn't even mentioned in the specs. https://drafts.csswg.org/css-align/#justify-items-property

**Comment by alpadev** [comment]
> Well it doesn't exist so it can't really be useful 😅 `align-items: auto` isn't understood by the browser:
> 
> <img alt="image" width="183" src="https://user-images.githubusercontent.com/4323180/112723327-3a7eac80-8ee4-11eb-9c62-dadef5b58864.png">
> 
> Instead you just want to explicitly set it to the value you want, like `align-items: start` which is the default 👍

In regards to the spec https://www.w3.org/TR/css-align-3/#align-items-property. Looks like `align-items: normal` is the initial value. 😊

**Comment by alpadev** [comment]
> Well it doesn't exist so it can't really be useful 😅 `align-items: auto` isn't understood by the browser:
> 
> <img alt="image" width="183" src="https://user-images.githubusercontent.com/4323180/112723327-3a7eac80-8ee4-11eb-9c62-dadef5b58864.png">
> 
> Instead you just want to explicitly set it to the value you want, like `align-items: start` which is the default 👍

In regards to the spec https://www.w3.org/TR/css-align-3/#align-items-property. Looks like `align-items: normal` is the initial value. 😊

**Comment by devhoussam** [comment]
so the tailwind css core team should update the documentation

**Comment by adamwathan** [comment]
Removed `justify-auto` and `place-items-auto` for the next version since they do nothing, and removed from docs. They will disappear from the class table in the docs when we publish the next version 👍🏻

**Comment by devhoussam** [comment]
> Removed `justify-auto` and `place-items-auto` for the next version since they do nothing, and removed from docs. They will disappear from the class table in the docs when we publish the next version 👍🏻

@adamwathan amazing 👍
