### ISSUE TITLE
text-white is not being applied properly

### ISSUE THREAD

**Issue by jerodion** [tailwindlabs/tailwindcss#3856]
### What version of Tailwind CSS are you using?

2

### What version of Node.js are you using?

15

### What browser are you using?

safari

### What operating system are you using?

Big Sur

### Reproduction repository

http://seeexampleindescription.com

`text-white` is not working despite being the last class declared in the element:

    <a href="#" class="text-gray-300 rounded-md space-x-2 p-2 bg-gray-900 hover:bg-gray-900 text-white">
        Dashboard
    </a>

Dev tools tells me that `text-white` is overridden by `text-gray-300`. Why?

**Comment by adamwathan** [comment]
Hey! This is just how CSS works, the order of classes in the `class` attribute means nothing, what matters is the order of the CSS in the stylesheet itself:

```html
<style>
  .text-red {
    color: red;
  }
  .text-blue {
    color: blue;
  }
</style>

<p class="text-red text-blue">This is blue</p>
<p class="text-blue text-red">This is also blue</p>
```
