### ISSUE TITLE
space-x-* does not work properly with "hidden" children

### ISSUE THREAD

**Issue by michael** [tailwindlabs/tailwindcss#3857]
### What version of Tailwind CSS are you using?

v2.0.4

### What version of Node.js are you using?

v12.0.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

sorry ;)

```html
<div class="flex items-center px-8 py-9 space-x-8">
   <div class="hidden sm:block"><img class="block w-20" src="/images/ken-logo-white.svg" alt="Ken"></div>
   <div class="text-white flex-1">Triff alle Ken Autoren und lass dich inspirieren.</div>
   <div><a class="bg-white rounded-md text-pink px-4 py-3" href="/explore">Stöbern</a></div>
</div>
```

Leads to this display on small screens (space-x-8 is applied for the hidden element still):

![image](https://user-images.githubusercontent.com/2931/112722417-c48d3c00-8f09-11eb-9b4f-2c2b6c770e8e.png)

If the element is removed from the DOM completely, it displays correctly.

```html
<div class="flex items-center px-8 py-9 space-x-8">
   <div class="text-white flex-1">Triff alle Ken Autoren und lass dich inspirieren.</div>
   <div><a class="bg-white rounded-md text-pink px-4 py-3" href="/explore">Stöbern</a></div>
</div>
```

![image](https://user-images.githubusercontent.com/2931/112722426-cfe06780-8f09-11eb-8f09-e9ab2c8f64b4.png)

Or am I overlooking something and this is intended behavior? Thanks for the help!

**Comment by adamwathan** [comment]
Hey! This is intended behavior just because of how complex it would be to make it any "smarter", can read about it in previous discussions:

https://github.com/tailwindlabs/tailwindcss/issues/3350#issuecomment-759762455
https://github.com/tailwindlabs/tailwindcss/issues/2740#issuecomment-736711525

**Comment by michael** [comment]
Thank you @adamwathan. Fair enough, and not Tailwinds fault. :) Btw thanks to you and your team for breaking me free of CSS (almost ;)) - Tailwind is such an intuitive approach!

Inspiring is also your way of sustaining open source with products on top of it (Tailwind UI). Great model and execution. Congrats! :)
