### ISSUE TITLE
Can you provide more styles about flex、padding、margin、height、width、size、text？

### ISSUE THREAD

**Issue by social-uni** [tailwindlabs/tailwindcss#3877]
### What version of Tailwind CSS are you using?

 v2.0.4

### What version of Node.js are you using?

v12.0.0

### What browser are you using?

n

### What operating system are you using?

n

### Reproduction repository

n

Can you provide more styles about flex、padding、margin、height、width、size、text？

Refer to the following

### flex: reference： https://gitee.com/social-uni/qing-css/blob/master/base/flex.scss

.row-col-end {
  display: flex;
  flex-direction: row;
  align-items: flex-end;
}

.row-col-center {
  display: flex;
  flex-direction: row;
  align-items: center;
}

.col-row-center {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.row-all-center {
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
}

There are many kinds of things, the comprehensive combination does not exceed 100 groups, and it is still within the controllable range.

### margin: reference： https://gitee.com/social-uni/qing-css/tree/master/base/margin

mg-1(vh|px|p(%):{margin: 1(vh|px|p(%))} .... mg-10000(vh|px|p(%):{margin: 1(vh|px|p(%)}
m{l|r|t|b}-1(vh|px|p(%):{margin: 1(vh|px|p(%)} .... mg-100(vh|px|p(%):{margin-{left|right|top|bottom}: 1(vh|px|p(%)}

### padding:  reference：https://gitee.com/social-uni/qing-css/tree/master/base/padding

pd-1(vh|px|p(%){margin: 1(vh|px|p(%)} .... pd-100(vh|px|p(%):{margin: 1(vh|px|p(%)}
p{l|r|t|b}-1(vh|px|p(%):{margin: 1(vh|px|p(%)} .... p{l|r|t|b}-100(vh|px|p(%):{margin-{left|right|top|bottom}: 1(vh|px|p(%)}

### height  reference ：https://gitee.com/social-uni/qing-css/blob/master/base/height.scss

h1(vh|px|p(%):{height: 1(vh|px|p(%))} .... h10000(vh|px|p(%):{height: 1(vh|px|p(%)}

### width  reference ：https://gitee.com/social-uni/qing-css/blob/master/base/width.scss

w1(vh|px|p(%):{width: 1(vh|px|p(%))} .... w10000(vh|px|p(%):{width: 1(vh|px|p(%)}

### size:  reference ：https://gitee.com/social-uni/qing-css/blob/master/base/size.scss

size1(vh|px|p(%):{height+width: 1(vh|px|p(%))} .... h10000(vh|px|p(%):{height+width: 1(vh|px|p(%)}

### text:

text-sm-px  xs/sm/lg/md/sl...  =12px\14\16\18px
text-12px 12/14/16/18 px...

**Comment by adamwathan** [comment]
Stuff like this should be handled by combining existing utilities:

```
.row-col-center {
  display: flex;
  flex-direction: row;
  align-items: center;
}
```

Write this instead `class="flex flex-row items-center"`.

For the other stuff, you can customize the margin/padding/width/height/etc scales however you like:

https://tailwindcss.com/docs/theme#customizing-the-default-theme
