### ISSUE TITLE
Disabled not working on anchors

### ISSUE THREAD

**Issue by royduin** [tailwindlabs/tailwindcss#3891]
### What version of Tailwind CSS are you using?

2.0.4

### What version of Node.js are you using?

v12.21.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/hRcWTicx5Y

Currently `:disabled` is used for the disabled variants but with `[disabled]` it's working. Maybe change that?

Most likely the issue here is that `<a>` doesn't support the disabled attribute `disabled` so the browser doesn't set `:disabled` but there are libraries that use a `disabled` attribute on anchors.

**Comment by mjtbkh** [comment]
HTML anchor tag has no "disabled" attribute, you need to define a custom class like "disabled" or whatever you want, and then style that specific class using tailwind:
```
.disabled {
    @apply bg-blue-500
}
```

**Comment by CODEheures** [comment]
> HTML anchor tag has no "disabled" attribute, you need to define a custom class like "disabled" or whatever you want, and then style that specific class using tailwind:
> 
> ```
> .disabled {
>     @apply bg-blue-500
> }
> ```

This thread is old but my solution with tailwind 4 is: `@custom-variant disabled (&[disabled], &.disabled);
`
