### ISSUE TITLE
Doesn't work with Vue 3 / Vite

### ISSUE THREAD

**Issue by Dagge1** [tailwindlabs/tailwindcss#3906]
### What version of Tailwind CSS are you using?

2.0.4

### What version of Node.js are you using?

14.15.4

### What browser are you using?

Windows 10

### What operating system are you using?

Windows 10

### Reproduction repository

https://www.blablabla.com

It doesn't work with Vue 3 and VIte. I tried all but no help.

**Comment by adamwathan** [comment]
It does actually! You just need to blablablah 👍

**Comment by adamwathan** [comment]
Here's a Vite + Tailwind project you can reference to find out what you configured incorrectly:

https://github.com/tailwindlabs/tailwindcss-from-zero-to-production/tree/main/01-setting-up-tailwindcss
