### ISSUE TITLE
md:text-size rewrite leading-[x] class

### ISSUE THREAD

**Issue by nekooee** [tailwindlabs/tailwindcss#3928]
### What version of Tailwind CSS are you using?

2.0.3

### What version of Node.js are you using?

14.15.4

### What browser are you using?

chrome

### What operating system are you using?

windows

### Reproduction repository

https://i.ibb.co/1TJwpYg/2021-04-04-13-54-29-GBSC.png

when I use md:text-size class and leading-[x] class, line-height rewrite by text-size

![image](https://user-images.githubusercontent.com/6003803/113504498-b4024480-954d-11eb-904f-914857169a8f.png)

**Comment by jtormey** [comment]
I'm seeing this for other text size / screen variant combinations as well. Using `@tailwindcss/jit`, it's possible to get around this using the `!important` syntax:

```html
<h1 class="lg:text-5xl !leading-snug">My header</h1>
```

**Comment by adamwathan** [comment]
Hey! This is by design, see previous discussions:

https://github.com/tailwindlabs/tailwindcss/issues/2603
https://github.com/tailwindlabs/tailwindcss/issues/3722

**Comment by nekooee** [comment]
> Hey! This is by design, see previous discussions:
> 
> #2603
> #3722

thank you. 
1. #2603 : Adding in config is not a good idea. Because my site is multilingual and requires different line-height in different languages that can be managed dynamically.
2. #3722 this guide doesn't work for a live custom leading, example leading-[3rem]
I will try to use @jtormey solution and add ! for important ...

**Comment by adamwathan** [comment]
The solution in #2603 will work perfectly for you, it _removes_ the default line-heights which means that `leading-*` will always be respected even as font size changes.
