### ISSUE TITLE
Postccs-mixin Variable Usage in @apply

### ISSUE THREAD

**Issue by avinashvalluru** [tailwindlabs/tailwindcss#3931]
### What version of Tailwind CSS are you using?

2.0.4

### What version of Node.js are you using?

12.16.1

### What browser are you using?

N/A

### What operating system are you using?

macOS

### Reproduction repository

N/A

```
@define-mixin icon $network, $color {
  &.icon.is-$(network) {
     @apply cui-bg-$(color)-50;
  }
}
@layer components {
  .cui-btn {
    @mixin icon twitter, blue;
  }
}
```

postcss.config.js

```
module.exports = {
    plugins: [
        require('postcss-import'),
        require('postcss-mixins'),
        require('postcss-simple-vars'),
        require('tailwindcss'),
        require('postcss-nested'),
        require('autoprefixer')
    ]
}
```
**Error:**
CssSyntaxError: /Users/cbsmobility/Documents/tailwind/tailwind/tailwind.scss:3:12: The cui-bg-$color-50 class does not exist, but cui-bg-danger-50 does. If you're sure that cui-bg-$color-50 exists, make sure that any @import statements are being properly processed before Tailwind CSS sees your CSS, as @apply can only be used for classes in the same CSS tree.

**Comment by avinashvalluru** [comment]
**Error:**
CssSyntaxError: /Users/cbsmobility/Documents/avinash/Cargill/tailwind/tailwind/tailwind.scss:3:12: The `cui-bg-$color-50` class does not exist, but `cui-bg-danger-50` does. If you're sure that `cui-bg-$color-50` exists, make sure that any `@import` statements are being properly processed before Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

It looks like your mixin/simple-vars are not actually executed _before_ tailwind. That error is coming from tailwind and it still has the non-resolved variables in it.

Some plugins in PostCSS 8 are written using a new "Visitor" API, this also means that some code can run whenever it visits a certain (postcss) node.

One thing you can do is wrap the first 3 plugins into a single plugin that ensure everything is executed before tailwind runs. You should be able to do that like this: 

```js
let postcss = require('postcss')

module.exports = {
  plugins: [
    {
      postcssPlugin: 'grouped',
      Once(root, { result }) {
        return postcss([
          require('postcss-import'),
          require('postcss-mixins'),
          require('postcss-simple-vars'),
        ]).process(root, result.opts)
      },
    },
    require('tailwindcss'),
    require('postcss-nested'),
    require('autoprefixer'),
  ],
}
```

If you are still having issues with this, please open a new issue with a minimal reproduction repository so that we can take a look.

**Comment by avinashvalluru** [comment]
Thank you so much for your response

It working great but one small thing is that after changing to this postCSS watch is not working. Can you please have a look

**Comment by KarelJanVanHaute** [comment]
@ai Can you give an example of this AtRule or AtRuleExit? I'm having the same watch problem. But I'm not really getting the postcss stuff. Thanks

**Comment by ai** [comment]
Plugin

```js
module.exports = {
  postcssPlugin: 'postcss-example',
  AtRule (atRule) {
    console.log('AtRule ', atRule.toString())
  },
  Declaration (decl) {
    console.log('Declaration', decl.toString())
    decl.value = 'red'
  },
  DeclarationExit (decl) {
    console.log('DeclarationExit', decl.toString())
    decl.value = 'red'
  },
  AtRuleExit (atRule) {
    console.log('AtRuleExit ', atRule.toString())
  }
}
module.exports.postcss = true
```

For CSS:

```css
@media screen { color: green }
```

Will output:

```
AtRule @media screen { color: green }
Declaration color: green
DeclarationExit color: red
AtRuleExit @media screen { color: red }
```
