### ISSUE TITLE
Slow build times with Webpack after Tailwind insert

### ISSUE THREAD

**Issue by iwandejong** [tailwindlabs/tailwindcss#3939]
### What version of Tailwind CSS are you using?

v2.0.4

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://www.youtube.com/watch?v=Tn6-PIqc4UM

I inserted Tailwind via PostCSS and npm into my empty project.
I also use Webpack as my bundler. 
Before Tailwind, the total build time was 2-3 seconds and a mere 800kb.
Now, with Tailwind, the total build time is 18 seconds and 5 megabytes. 
How should I deal with this and is there a solution?

**Comment by danielstaleiny** [comment]
I am not a mantainer, but I think you can update tailwindcss and use the new feature called mode: 'jit' in config, which will reduce build time in development significatly.

**Comment by adamwathan** [comment]
Yeah this is just a limitation of webpack struggling with large CSS files I'm afraid, and is the main motivation for building the JIT engine mentioned above 👍🏻 

https://tailwindcss.com/docs/just-in-time-mode

**Comment by zhouJiecode** [comment]
对于无法升级到最新版本tailwind的可以通过webpack插件解决这个问题：
https://juejin.cn/post/6956424977184718856
