### ISSUE TITLE
Rails (Webpacker) doesn't like this

### ISSUE THREAD

**Issue by wdiechmann** [tailwindlabs/tailwindcss#3946]
### What version of @tailwindcss/jit are you using?

v0.1.3

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS 10.15.7

### Reproduction repository

https://gist.github.com/wdiechmann/1a5baa91b880005c6a9edbcca938616f

Adam,

I'm in awe of the work you're doing - and a customer to TailwindUI which is brilliant!

Couldn't help but try out the new JIT - but as it turns out, my 'stack' doesn't quite tackle it too good 😢 

You most certainly have bigger fish to fry - just wanted to let you know the work is appreciated!

/Walther

**Comment by TimSullivan** [comment]
I was able to get JIT working with puma-dev without upgrading webpacker by adding this line to config/webpack/development.js:

    process.env.TAILWIND_MODE = process.env.TAILWIND_MODE || 'build'

**Comment by nikgoy** [comment]
this helped me
https://github.com/rails/webpacker/blob/4af3db06fcada9c025e1e3f3d84504ed0d169bc4/docs/v6_upgrade.md

**Comment by mcmire** [comment]
Reviewing the OP's post, I am wondering whether the issue at the time was that `@tailwindcss/jit` was not PostCSS 7 compatible. Now that it is integrated into Tailwind, you may be able to use `@tailwindcss/postcss7-compat` just fine.

**Comment by bradlc** [comment]
Please can someone provide a reproduction repository with Rails/webpacker already set up, otherwise it's not going to be possible to debug the issue, thanks!

**Comment by adamwathan** [comment]
Going to close this as there hasn't been any activity on it in a while and lots of stuff has changed that sounds like it might have resolved it. If this is still an issue for anyone please feel free to open a new issue with a reproduction and we can figure it out 👍 

_Please note that we do not monitor closed issues, so if you comment here after this issue has been closed we won't see it and you won't get a reply. Instead just open a new issue — we will see that for sure! ❤️_
