### ISSUE TITLE
11ty with TailwindCSS Jit and PostCSS

### ISSUE THREAD

**Issue by juanfernandes** [tailwindlabs/tailwindcss#3952]
### What version of @tailwindcss/jit are you using?

v0.1.5

### What version of Node.js are you using?

v14.15.1

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### Reproduction repository

https://gitlab.com/juanfernandes/11ty-tailwind-jit-postcss

When I run `npm run start` it just hangs and 11ty serve doesn't run so when I open http://localhost:8080/ in my browser its not running.

I have tried the following: 

"start": "TAILWIND_MODE='watch' NODE_ENV='development' npm-run-all postcss --parallel watch:*",
"start": "TAILWIND_MODE=watch NODE_ENV=development npm-run-all postcss --parallel watch:*",

"start": "NODE_ENV='development' npm-run-all postcss --parallel watch:*",
"start": "NODE_ENV=development npm-run-all postcss --parallel watch:*",

"start": "npm-run-all postcss --parallel watch:*",

And neither work. 

I have it working without JIT with the exact config in my main repo.

Thanks in advance.

**Comment by bradlc** [comment]
Hey @juanfernandes. It looks like maybe this issue is outdated as your project seems to be working fine now? Going to close this but please open a new issue if you're still having problems 👍
