### ISSUE TITLE
`leading-` doesn't accept a unitless value as arbitrary value

### ISSUE THREAD

**Issue by binotaliu** [tailwindlabs/tailwindcss#3957]
### What version of @tailwindcss/jit are you using?

0.1.17

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

N/A

### What operating system are you using?

macOS

### Reproduction repository

N/A

[line-height accept a value that doesn't have a unit.](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height)

Tailwindcss' class also include like `leading-loose` that uses this kind of value.

When using a code like 
```css
.my-leading {
   @apply leading-[1.9];
}
```

Compiler complains that such class doesn't exists:

```
content.css The `leading-[1.9]` class does not exist. If `leading-[1.9]` is a custom class, make sure it is defined within a `@layer` directive.
```

**Comment by bradlc** [comment]
This will be fixed in the next release. In the meantime you can use our preview build: `npm install -D tailwindcss@canary` 👍
