### ISSUE TITLE
VS Code Live Server Problem

### ISSUE THREAD

**Issue by mcajongbah** [tailwindlabs/tailwindcss#3958]
### What version of @tailwindcss/jit are you using?

0.1.17

### What version of Node.js are you using?

14.15.3

### What build tool (or framework if it abstracts the build tool) are you using?

postcss-cli

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### Reproduction repository

https://github.com/mcajongbah/tailwind-jit.git

When the HTML file is updated, the compiler updates the classes but the browser just flickers but doesn't apply the related changes. I'm not sure whether it's a tailwind jit plugin problem(doesn't happen with the tailwind plugin itself) or that of the live server extension. Changes only apply after you manually reload the page

**Comment by OmkarK45** [comment]
> For what it's worth I have this same sort of issue and I don't use a VSCode live server (not sure what that is?). I run a webpack dev server as part of a Rails app and the majority of the time I need to save the file to trigger the compilation, but the browser seems to reload before the new styles are done. I have to trigger another save in VSCode to trigger another refresh, and things seem to go through and change the second time.
> 
> EDIT: HMR when reloading stylesheet changes directly seems to work fine for me so I'm not sure if this isn't just a Rails related issue, unrelated to tailwind JIT. Only happens when a full page refresh is triggered.
> 
> EDIT2: Nope this is a result of me adding my view files to the dev server watch path. I directly trigger a "content-changed" when a file is modified and the content-changed was too quick. Adding a little setTimeout delay to wait for JIT to finish solved my problem.

Hey how do you add setTimeout to JIT ?

**Comment by taylorthurlow** [comment]
> Hey how do you add setTimeout to JIT ?

I haven't actually added a timeout to the JIT compilation. I had added an additional file watcher for some extra directories, and that file watcher was triggering an update as soon as the changes were seen. This update was happening before the JIT was finished compiling.

As far as I can tell there is no legitimate reason to need to delay the JIT compilation, so if you're trying to solve a problem that way, it's probably not the right way to solve it.

**Comment by harvanchik** [comment]
Is there any progress or more information on how to resolve this?

**Comment by Arnold474** [comment]
I had this problem and I solved it by changing the port number in the settings.json file to an opened one.

To get to the settings.json file you just click CTRL+SHIFT+P, then type "settings", click the "Preferences: Open Settings (JSON)", then paste this inside the { }:

`"liveServer.settings.port": 0`
This will randomly pick an opened port each time. This is how my JSON file looks like:

```
{
    "liveServer.settings.port": 0
}
```

**Comment by Oppfinnaren** [comment]
The problem was solved form to set `liveServer.settings.fullReload": true` in /.vscode/settings.json.

**Comment by UCYT5040** [comment]
If this is solved, shouldn't it be closed?

**Comment by harvanchik** [comment]
Yes, it should.  This solution solved my problem.

> The problem was solved for me by setting `liveServer.settings.fullReload": true` in /.vscode/settings.json.

**Comment by onkmade** [comment]
I'm having a problem; I'm using Tailwind, and I need to save it twice to see the change on the live server. How do I fix it?
