### ISSUE TITLE
There is a magic bug with webpack and windows

### ISSUE THREAD

**Issue by deleonio** [tailwindlabs/tailwindcss#3960]
### What version of @tailwindcss/jit are you using?

v0.1.3

### What version of Node.js are you using?

v14.0.0

### What build tool (or framework if it abstracts the build tool) are you using?

webpack + postcss-loader

### What browser are you using?

N/A

### What operating system are you using?

Windows

### Reproduction repository

-

You can reproduce it like that:

```
mkdir reproduce
cd reproduce
npm i @leanup/cli@next @leanup/cli-react@next
npx react create
npm run build
```

![image](https://user-images.githubusercontent.com/6279703/112941329-b10eea80-912e-11eb-912e-004c0b7409b2.png)

**Comment by bradlc** [comment]
Closing this as it looks like your reproduction doesn't use Tailwind anymore. Please open a new issue with a reproduction if you're still having problems 👍
