### ISSUE TITLE
JIT is not working in a Vite - React project

### ISSUE THREAD

**Issue by carlitorweb** [tailwindlabs/tailwindcss#3962]
### What version of @tailwindcss/jit are you using?

0.1.17

### What version of Node.js are you using?

v14.16.0

### What build tool (or framework if it abstracts the build tool) are you using?

postcss: "8.2.8", react: "17.0.0", vite: "^2.1.3"

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/carlitorweb/react-burger

Variants like **focus-visible, active, disabled**, and others do not work. Not even the Tailwind IntelliSense autocomplete (have the last version of it). 

Styles generated on demand do not work too. Something like `shadow-[inset -15px 0 #c15711]` or others similar do not make the job. 

## The repo I listed here, was working with the follow config:

```js
module.exports = {
  purge: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      transitionProperty: {
        height: "height",
      },
      fontFamily: {
        sans: ["Open Sans", "sans-serif", ...defaultTheme.fontFamily.sans],
      },
      maxWidth: {
        "1/4": "25%",
        "1/2": "50%",
        "3/4": "75%",
      },
      height: {
        "1/8": "13%",
        "1/12": "8%",
        "1/14": "7%",
        "1/22": "4.5%",
        "1/30": "3%",
        120: "400px",
      },
      width: {
        "1/10": "10%",
        "9/10": "90%",
        "6/7": "85%",
        150: "500px",
      },
      boxShadow: {
        inner2: "inset -15px 0 #c15711",
        inner3: "inset -2px -3px #c9c9c9",
        inner4: "inset -3px 0 #c9c9c9",
      },
      margin: {
        "1/45auto": "2% auto",
      },
      borderRadius: {
        "1/2": "50%",
        "2/5": "40%",
      },
      rotate: {
        "-20": "-20deg",
        10: "10deg",
      },
      colors: {
        cheese: {
          light: "#f4d004",
          DEFAULT: "#e9c917",
          dark: "#d6bb22",
        },
        toolbar: "#703B09",
        navigationLink: "#8F5C2C",
      },
    },
  },
  variants: {
    extend: {
      backgroundColor: ["active", "disabled"],
      outline: ["active"],
      cursor: ["disabled"],
      borderColor: ["active"],
    },
  },
  plugins: [],
};
```
## Fresh start

I created a new project with Vite for react, and just copy the **src** folder to there. The project work good, just the new JIT is not working in my case. 
Not sure what I doing wrong, even when the setting are pretty simple to do/follow.

**Comment by bradlc** [comment]
Hey @carlitorweb, this issue is a bit outdated now that the JIT engine has been merged into the `tailwindcss` module, but even in your repo that uses `@tailwindcss/jit` everything seems to be working fine. The `active` and `disabled` classes you have used are working as far as I can tell. Can you be more specific about what isn't working?

Regarding the `shadow-[inset -15px 0 #c15711]` class, classes cannot have spaces in them, but also I think the `boxShadow` module doesn't currently support arbitrary values, so that's something we need to add 👍

**Comment by carlitorweb** [comment]
@bradlc Yes is now working, I forgot comment and close here after the updates. Thank you for the `boxShadow` detail.
