### ISSUE TITLE
Next.js Enable Source maps?

### ISSUE THREAD

**Issue by surjithctly** [tailwindlabs/tailwindcss#3968]
### What version of @tailwindcss/jit are you using?

0.1.18

### What version of Node.js are you using?

14.16.0

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js 10.1.3

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/vercel/next.js

When using Tailwind JIT with Next.js, the source map is not enabled. Instead, it shows `<no source>` while inspecting. 

It would be great if we could see the source while developing.

**Comment by adamwathan** [comment]
Hey! This will be fixed in the next version: https://github.com/tailwindlabs/tailwindcss/commit/2f1541123dea29d8a2ab0f1411bf60c79eeb96b4

Thanks!
