### ISSUE TITLE
Storybook support

### ISSUE THREAD

**Issue by l0st0** [tailwindlabs/tailwindcss#3971]
### What version of @tailwindcss/jit are you using?

v0.1.18

### What version of Node.js are you using?

v14.16.0

### What build tool (or framework if it abstracts the build tool) are you using?

"next": "10.1.3", "@storybook/react": "^6.2.2", "postcss": "^8.2.9"

### What browser are you using?

Brave, Safari

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/l0st0/tailwind-storybook

Hi, I was able to work with storybook no config required without JIT in postcss. If I add it, no bugs in console but styles are not  working. Hope you can fix it. Have a great day. Thanks :)

**Comment by danielritter** [comment]
The same here, but also without JIT mode I've got the same issues with storybook und updating the classes.

My postcss.config.js file looks like:

```
module.exports = {
	plugins: {
        tailwindcss: { config: './path/to/tailwind.config.js' },
        autoprefixer: {},
        'postcss-flexbugs-fixes': {}
    }
};
```

and 

```
module.exports = {
	plugins: {
        '@tailwindcss/jit': { config: './path/to/tailwind.config.js' },
        autoprefixer: {},
        'postcss-flexbugs-fixes': {}
    }
};
```

both does not work.

If I add something like this:

```
module.exports = {
	plugins: {
	    tailwindcss: {},
        '@tailwindcss/jit': { config: './libs/shared/ui/tailwind/src/lib/config/tailwind.config.js' },
        autoprefixer: {},
        'postcss-flexbugs-fixes': {}
    }
};
```

all classes get loaded, but with this setup my frontend application gets broken.

My main.js file looks like:

```
module.exports = {
	stories: ['../**/*.stories.mdx', '../**/*.stories.@(js|jsx|ts|tsx)'],
	addons: [
		'@storybook/addon-a11y',
		'@storybook/addon-actions',
		'@storybook/addon-backgrounds',
		'@storybook/addon-docs',
		'@storybook/addon-essentials',
		'@storybook/addon-links',
        {
            name: '@storybook/addon-postcss',
            options: {
                postcssLoaderOptions: {
                    implementation: require('postcss')
                }
            }
        },
		'@storybook/addon-storysource',
		'@storybook/addon-viewport'
	]
};
```

**Comment by l0st0** [comment]
Well that is weird, it should work with normal setup. Did you tried this npx sb upgrade --prerelease?

**Comment by danielritter** [comment]
Thank you for the command. Yes, right before, but unfortunately it doesn't work with that either.

**Comment by danielritter** [comment]
My node version is: v12.16.1

**Comment by danielritter** [comment]
You're right, it works with normal setup. The problem was with the content settings at purge in my config file. Thanks!

**Comment by bradlc** [comment]
Hey @l0st0. I have submitted a [pull request](https://github.com/l0st0/tailwind-storybook/pull/1) on your reproduction repository that enables JIT mode and it seems to be working fine. Here's what I did:

- Upgrade `tailwindcss` to the latest version
- Set `mode: "jit"` in the Tailwind config
- Configured the `purge` paths to cover the `pages` and `stories` directories – this needs to cover all of the files where you will be using Tailwind classes, so that Tailwind knows which classes to generate

If you run into any other problems please open a new issue with a reproduction, thanks!
