### ISSUE TITLE
grid-cols[repeat] and grid-cols[minmax] not working expected

### ISSUE THREAD

**Issue by pluscda** [tailwindlabs/tailwindcss#3974]
### What version of @tailwindcss/jit are you using?

0.1.18

### What version of Node.js are you using?

v14.0.0

### What build tool (or framework if it abstracts the build tool) are you using?

vite2 , @tailwindcss/jit

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### Reproduction repository

https://github.com/tailwindlabs/tailwindcss-jit.git

As long as it contains "," in custom grid-cols-xxx, it will not work using grid-cols-[repeat(num, 100px)] or grid-cols-[minmax(x, y)]

**Comment by mnlfischer** [comment]
`col-start-x` has also no effect.

**Comment by bradlc** [comment]
Hey @pluscda. You need to remove the spaces from the classes, for example `grid-cols-[repeat(3,100px)]` or `grid-cols-[minmax(50px,100px)]`
