### ISSUE TITLE
Hover state isn't working when using text-gray-400 through text-gray-700 classes

### ISSUE THREAD

**Issue by kmt6352** [tailwindlabs/tailwindcss#3976]
### What version of Tailwind CSS are you using?

v2.0.1

### What version of Node.js are you using?

v14.15.4

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://www.youtube.com/watch?v=m7wGr5nRraQ&ab_channel=TheVoice

I could definitely be doing something wrong, but I'm running into a problem when I try to hover over a link. It happens when the original text color is text-gray-400, text-gray-500, text-gray-600, or text-gray-700. When I try to change the text color when the user hovers over the link it doesn't work. The hover will work for changing the background color though, just not the text color. I placed an example below where this is happening in my code.

`<p class="py-2 text-sm text-white">Some text about benefits and such <inertia-link class="text-gray-400 hover:text-gray-800" href="/benefits">(click here for a list of benefits)</inertia-link></p>`

**Comment by bradlc** [comment]
Please can you provide a repository which reproduces the issue @kmt6352? Otherwise it is not going to be possible for us to help you debug this. Thanks!
