### ISSUE TITLE
Unable to @apply the "group" class in SCSS module with JIT enabled.

### ISSUE THREAD

**Issue by developer-haku** [tailwindlabs/tailwindcss#3980]
### What version of Tailwind CSS are you using?

v2.1.0

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/developer-haku/tw-jit-gp-err-rpd

### Error

> Syntax error: <some_dir>\tw-jit-gp-err-rpd\TestDiv.module.scss The \`group\` class does not exist. If \`group\` is a custom class, make sure it is defined within a \`@layer\` directive.

So I used the example ([Group-hover](https://tailwindcss.com/docs/hover-focus-and-other-states#group-hover)) from the Tailwind documentation to reproduce this error. 

In the reproduction repository, I created two components, one is just copied from the documentation example without any changes, another one is using CSS module, styles are applied from the `TestDiv.module.scss` file, the tailwind classes are the same in both components.

If I remove the `group` class from `.parent` in the scss file, there won't be any errors but group hover will not work, obviously.

If I remove `mode: "jit"` from the `tailwind.config.js` file, the syntax error will not pop up, but the group hover is still not working, maybe the way that I `@apply` these tailwind classes incorrectly?

I also tried add the following to the `tailwind.config.js` file but it is also not working somehow...
```js
module.exports = {
  // mode: "jit",
  // ...
  variants: {
    extend: {
      textColor: ['group-hover'],
    }
  },
}
```

I am not sure it is a Tailwind bug or Sass bug, I just jumped into the Tailwind rabbit hole not long a ago. If the way that I use the Tailwind classes in Sass is incorrect, great appreciation if anyone can point that out for me.

**Comment by sotirislp** [comment]
having the exact same issue with JIT mode in **Laravel + Tailwind.** project.
 When using `group` and `group-hover` on html elements everything works as expected.
When using @apply in .css file, webpack throws following error:
`"The `group` class does not exist. If `group` is a custom class, make sure it is defined within a `@layer` directive."`


**What version of Tailwind CSS are you using?**
v2.1.1
**What version of Node.js are you using?**
v14.15.4
**What browser are you using?**
Firefox Developer Edition 88.0b8 
**What operating system are you using?**
Ubuntu 20.04.2 LTS

**Comment by schradert** [comment]
Same issue here using @apply with ```group-hover``` in SCSS bundled with Webpack.
I am NOT using Tailwind in JIT mode.
I have explicitly defined and extended ```group-hover``` variants for default and additional property plugins.
Same as @sotirislp noted, inline HTML classes work as expected.

Tailwind: v2.1.1
Node: v14.16.0
Browser: Chrome, Firefox
OS: Debian GNU/Linux 10 (buster)

**Comment by bradlc** [comment]
Hey @developer-haku. As @schradert pointed out, you can't `@apply` the `group` class. Check out [Simon's comment](https://github.com/tailwindlabs/tailwindcss/issues/2848#issuecomment-734523233) over on #2848 for more information. One option is to remove `group` from the `@apply` and use `group` in your HTML instead, like Simon suggests:

```html
<div class="parent group">
  <p>...</p>
</div>
```

Or you could change your CSS to not use the `group` functionality at all:

```diff
  .parent {
-   @apply group
-     px-6
+   @apply px-6
      py-5
      max-w-full
      mx-auto
      w-72
      border
      border-indigo-500
      border-opacity-25
      cursor-pointer
      rounded-lg
      select-none
      overflow-hidden
      space-y-1
      hover:bg-white
      hover:shadow-lg
      hover:border-transparent;

    & > p:first-child {
      @apply font-semibold
        text-lg
        text-indigo-600
-       group-hover:text-gray-900;
    }

+   &:hover > p:first-child {
+     @apply text-gray-900;
+   }

    & > p:last-child {
      @apply text-indigo-500
-       group-hover:text-gray-500;
    }

+   &:hover > p:last-child {
+     @apply text-gray-500;
+   }
  }
```
