### ISSUE TITLE
Plugin Tailwind of Webstorm not work after update to Tailwind v2.1.1

### ISSUE THREAD

**Issue by vunamhung** [tailwindlabs/tailwindcss#3982]
### What version of Tailwind CSS are you using?

2.1.1

### What version of Node.js are you using?

v15.13.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

I add screenshot in below

Hi Tailwind Team,
After update to Tailwind v2.1.1, plugin Tailwind of Webstorm don't work anymore, it not suggest tailwind classes.
This is screenshot.
https://cloudup.com/cBgx3t1gAP1
I hope you can check this probem soon.
Thank you very much.

**Comment by thebuilder** [comment]
I can confirm this - But most likely this is something that should be fixed by InteliJ. I've created an issue on their issue tracker.
https://youtrack.jetbrains.com/issue/WEB-50318

**Comment by domosedov** [comment]
Plugin for VS Code has same problem

**Comment by AndrisBorbas** [comment]
VSCode's prettier plugin tailwind fails here: tailwindcss/lib/plugins/backdropBlur.js:26:7 saying that matchUtilities is not a function

**Comment by thebuilder** [comment]
The prettier-plugin is using [tailwind-classes-sorter](https://github.com/Acidic9/tailwind-classes-sorter), which is where the error happens. Seems to only occur when JIT mode is enabled.

I've also created an issue for that: https://github.com/Acidic9/tailwind-classes-sorter/issues/4

**Comment by wsydney76** [comment]
Using PhpStorm 2020.3.3 with Tailwind CSS  plugin 203.7717.64, it seems like it still works as expected for me with JIT not enabled.

![image](https://user-images.githubusercontent.com/60010597/113724172-5eb36800-96f2-11eb-804c-59e2b164ffbd.png)

However if JIT is enabled, only classes that are already used in the project will be suggested. So guessing it needs some kind of new interaction between the two to allow the plugin to do a full build behind the scenes.

PS. 
Also classes from node_modules/tailwindcss/jit/tests are suggested, which i think will no longer be the case in a final version, and it's safe to delete this folder in the meantime?

**Comment by thebuilder** [comment]
`tailwindcss/jit/tests` seems like something that should be added to an `.npmignore` file.

**Comment by vunamhung** [comment]
A temporary fix for getting classes when running in JIT mode, by forcing it to only use JIT when compiling the css.

**tailwind.config.js**

```
module.exports = {
  // This "hack" ensures your IDE detects all normal Tailwind classes, while JIT is used when compiling the project.
  // All the normal Tailwind classes should show up in code completion. It can't show all the new classes generated by JIT.
  mode: process.env.NODE_ENV ? 'jit' : undefined,
};
```

**Comment by domosedov** [comment]
> A temporary fix for getting classes when running in JIT mode, by forcing it to only use JIT when compiling the css.
> 
> **tailwind.config.js**
> 
> ```
> module.exports = {
>   // This "hack" ensures your IDE detects all normal Tailwind classes, while JIT is used when compiling the project.
>   // All the normal Tailwind classes should show up in code completion. It can't show all the new classes generated by JIT.
>   mode: process.env.NODE_ENV ? 'jit' : undefined,
> };
> ```
> 
> I tested with webstorm and it work.

thank you.
Works in VS Code

**Comment by gbreux** [comment]
I have the same issue with vscode, using the `process.env.NODE_ENV` hack work with the prettier cli, but not with the vscode prettier plugin :s 

Disabling the JIT mode "fix" this.
