### ISSUE TITLE
Tailwind not work as exepted with Webpack with JIT

### ISSUE THREAD

**Issue by jbty** [tailwindlabs/tailwindcss#4000]
### What version of Tailwind CSS are you using?

2.1.1

### What version of Node.js are you using?

14

### What browser are you using?

Chrome

### What operating system are you using?

Mac os

### Reproduction repository

https://github.com/jbty/html-starter-typscript-scss-tailwind

The tailwind classes which are already in my html are working but I cannot add new ones.

I don't understand where this came from. If I desete JIT everythings work as exepted but hot reload with webpack dev server is so long.

**Tailwind config:**
```
const colors = require('tailwindcss/colors');

module.exports = {
  mode: 'jit',

  purge: ['./dist/*.html', './dist/*.js'],

  darkMode: false,

  theme: {
    screens: {
      print: { raw: 'print' },
      sm: '640px',
      // => @media (min-width: 640px) { ... }
      md: '768px',
      // => @media (min-width: 768px) { ... }
      lg: '1024px',
      // => @media (min-width: 1024px) { ... }
      xl: '1280px',
      // => @media (min-width: 1280px) { ... }
      '2xl': '1536px',
      // => @media (min-width: 1536px) { ... }
    },

    extend: {
      fontFamily: {},
      colors: {
        transparent: 'transparent',
        current: 'currentColor',
        black: colors.black,
        white: colors.white,
        gray: colors.trueGray,
        indigo: colors.indigo,
        red: colors.rose,
        yellow: colors.amber,
      },
      fontSize: {},
    },
  },

  variants: {
    extend: {},
  },

  plugins: [],
};
```

**Postcss config:**
```
module.exports = {
  plugins: [require('autoprefixer'), require('@tailwindcss/jit')],
};

```

**Webpack config:**
```
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CopyPlugin = require('copy-webpack-plugin');

module.exports = {
  entry: './src/app.ts',
  target: 'web',
  cache: true,

  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: '[name].[fullhash:8].js',
    sourceMapFilename: '[name].[fullhash:8].map',
    chunkFilename: '[id].[fullhash:8].js',
    clean: true,
  },

  module: {
    rules: [
      {
        test: /\.(sa|sc|c)ss$/,
        use: [
          {
            loader: 'style-loader',
          },
          {
            loader: 'css-loader',
          },
          {
            loader: 'postcss-loader',
          },
          'sass-loader',
        ],
      },
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      },
      {
        test: /\.(jpe?g|png|gif|svg)$/i,
        loader: 'file-loader',
        options: {
          name: '[name].[hash].[ext]',
          outputPath: 'assets/images',
          esModule: false,
        },
      },
      {
        test: /\.(woff|woff2|eot|ttf|otf)$/i,
        loader: 'file-loader',
        options: {
          outputPath: 'assets/fonts',
        },
      },
    ],
  },

  resolve: {
    extensions: ['.ts', '.js'],
  },

  plugins: [
    new HtmlWebpackPlugin({
      template: 'src/index.html',
      title: 'Webpack Starter',
      description: 'Webpack Starter',
    }),
    new CopyPlugin({
      patterns: [{ from: 'src/public' }],
    }),
  ],

 devServer: {
    contentBase: path.resolve(__dirname, 'dist'),
    watchContentBase: true,
    writeToDisk: true,
    hot: true,
  },
};

```

**Comment by samadadi** [comment]
I should also mention that using tailwind in jit mode, compiltion happens twice (two round). I do not know anybody else noticed this problem.

**Comment by ervwalter** [comment]
As of Tailwind 2.1, you should not use `'@tailwindcss/jit'` in your postcss config.  Just use plain `'tailwindcss'`.  Your double compilation is probably because you are still using the separate jit package _and_ are also setting `mode: 'jit'` in the tailwind config.  I'm not sure what other problems that configuration could cause either.

**Comment by samadadi** [comment]
As in this page mentioned [v2.1.0](https://github.com/tailwindlabs/tailwindcss/releases/tag/v2.1.0), if I want jit compilation I should set **mode** config value to **jit**. After setting this configuration value almost everything works fine but I am getting dual compilation problem. Without **jit mode**  there is no dual compilation problem but the css output is almost 4MB file and I can't use features that **jit mode** brings to us (stackable variants, arbitrary value support, ...).

**Comment by samadadi** [comment]
I should mention that with enabling jit mode, beside dual compilation problem, when I set new specific class It works fine but when I remove this class, the output related to this class name remains there. For example if I use **'filter blur-md'** in my element, tailwind generate related output correctly but when I remove this class names, It is still in there.

**Comment by ervwalter** [comment]
Sorry I wasn't clear.  The problem is your postcss config. Keep mode: 'jit'. Remove require('@tailwindcss/jit'). Add require('tailwindcss').

**Comment by samadadi** [comment]
yes. i am using 'tailwindcss' in my postcss configuration.

**Comment by ervwalter** [comment]
According to your original post and this line in your repro repository, you are not:  https://github.com/jbty/html-starter-typscript-scss-tailwind/blob/main/postcss.config.js#L2

**Comment by jbty** [comment]
> Sorry I wasn't clear. The problem is your postcss config. Keep mode: 'jit'. Remove require('@tailwindcss/jit'). Add require('tailwindcss').
> 
> require('@tailwindcss/jit') was the old way before 2.1. It's built in now and that special package is no longer needed. Remove it.

Thanks it's work for me

**Comment by samadadi** [comment]
I uploaded my starter project to this github repository [rollup-solid-tailwind-starter](https://github.com/samadadi/rollup-solid-tailwind-starter)

**Comment by ervwalter** [comment]
Apologies @samadadi, I incorrectly thought this was _your_ issue all this time.  It didn't notice that it was @jbty who had the original issue.  All my comments were about _his_ issue and it looks like his is solved.

Regarding your first issue, I don't have any specific advice because I have not got much rollup experience.  It might be related to Rollup somehow, but I can't say for certain.  

Is your second issue only happening in development mode?  If so, I'm not sure that is a bug and it might be by just how it works.  There is no real downside, right? It's just an idiosyncrasy of JIT in dev mode.  I would expect you get the correct, optimized CSS when you do your production build and the old class names are no longer present in your codebase.

I'd probably suggest you create a couple new issues in this repo with your specific details to get some guidance on both double compiles and on the removal of unused classes at dev time.  Mostly because, since @jbty's original issue is resolved, this might get closed.

**Comment by samadadi** [comment]
Thank you so much. I will create new issues to these two problems. But I don't think that rollup is the problem, because with disabling jit mode every thing is working fine. But as I said in this case there is no jit compilation benefits.

**Comment by Manoz** [comment]
@samadadi remove Tailwind rules in your `/src/tailwind.css` file. You don't need them anymore with JIT. That's why you have double compilation and probably why your compiled file is over 4mb.
Be careful tho you might have other issues like code not recompiling after that :(

**Comment by nauvalazhar** [comment]
I also faced the same problem. I solve the problem by adding `TAILWIND_MODE=watch`.

**Comment by adamwathan** [comment]
Sounds like this is resolved, if not don't hesitate to open a new issue! Thanks.

**Comment by arye-dov-eidelman** [comment]
Had the same issue, Fixed by adding TAILWIND_MODE=watch as @nauvalazhar said.
More specifically (for windows support) by: `yarn add cross-env --dev` and replacing `craco start` with `cross-env TAILWIND_MODE=watch craco start` in the package.json start script.
