### ISSUE TITLE
CLI not confirming when file has changed

### ISSUE THREAD

**Issue by conormcafee** [tailwindlabs/tailwindcss#4003]
### What version of Tailwind CSS are you using?

2.1.1

### What version of Node.js are you using?

14.0.0

### What browser are you using?

Chrome

### What operating system are you using?

Mac OS Big Sur

### Reproduction repository

-

My CLI does not update whenever a new class gets added to my CSS file.  I can see the file changes as expected, but  I don't get any indication that it has changed on my CLI.  Below gets rendered whenever I run `npm run dev` and doesn't update (even when the CSS file updates).

```
eamli-marketing git:(3529-set-up-tailwind-css) ✗ npm run dev  

> xxx@1.0.0 dev /Users/conormcafee/Documents/Sites/xxx
> postcss tailwindcss.css -o templates/styles/style.css -w


warn - You have enabled the JIT engine which is currently in preview.
warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.
```

Other relevant files for clarity:

Package.json
```
{
  "name": "xxxx,
  "version": "1.0.0",
  "description": "",
  "main": "postcss.config.js",
  "scripts": {
    "dev": "postcss tailwindcss.css -o templates/styles/style.css -w",
    "build": "postcss tailwindcss.css -o templates/styles/style.css"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "autoprefixer": "^10.2.5",
    "postcss": "^8.2.9",
    "tailwindcss": "^2.1.1"
  }
}
```

tailwind.config.js
```
module.exports = {
  mode: "jit",
  purge: ["./templates/**/*.twig"],
  darkMode: false,
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
```

postcss.config.js
```
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};

```

**Comment by conormcafee** [comment]
Just tried this again on my personal computer.  Set up a brand project, installed tailwind as per the docs (had to install postcss and postcss-cli (`npm i -D postcss postcss-cli`) also as I only have used `npx tailwind build` in the past).  I still get the same issue where my CLI doesn't update whenever JIT is running.  Wondering if there is anything obivious that I do not have installed that may be missing from the docs?

**Comment by mhatvan** [comment]
I experience the same thing, also had to double check the actual code output to see that it works fine. Cli message would be helpful!

**Comment by rhukster** [comment]
Tired the command with `--verbose` ?

```
"dev": "postcss tailwindcss.css -o templates/styles/style.css --watch --verbose"
```

**Comment by conormcafee** [comment]
Thanks @rhukster - that gives me what I was expecting!
