### ISSUE TITLE
NextJS build purges some of the classes in use within the code

### ISSUE THREAD

**Issue by bardiaheshmati** [tailwindlabs/tailwindcss#4009]
### What version of Tailwind CSS are you using?

2.0.3

### What version of Node.js are you using?

14.15

### What browser are you using?

Chrome, Safari

### What operating system are you using?

Mac OS

### Reproduction repository

https://

In some of the pages, some of the classes that i used is being purged after build is done. i'm not sure if this is something from tailwind or NextJs.

This is in development env.
<img width="409" alt="Screenshot 2021-04-08 at 2 07 34 PM" src="https://user-images.githubusercontent.com/3595255/113976715-11f79a80-9874-11eb-8c94-8fbe139c35ac.png">
and this is after build is done
<img width="414" alt="Screenshot 2021-04-08 at 2 09 36 PM" src="https://user-images.githubusercontent.com/3595255/113976741-19b73f00-9874-11eb-9a01-a7d2e06fa7ac.png">

this is what i can confirm from the video that the classes are purged for some reason.

https://user-images.githubusercontent.com/3595255/113976326-8c73ea80-9873-11eb-81f8-4ba23162d73b.mov

**Comment by moonRider** [comment]
I have same issue

**Comment by bardiaheshmati** [comment]
for those who are wondering, i ended up writing separate purges for different folders in the application and solved the issues. this also resolved the issues with my custom fonts not loading too.

**Comment by enkhee-Osiris** [comment]
```js

const fg = require('fast-glob');

const purgeFiles = fg.sync(['./src/pages/**/*.jsx', './src/components/**/*.jsx'], { dot: false });

module.exports = {
  purge: purgeFiles,
  ...
}
```
this worked for me.
