### ISSUE TITLE
extend:{width:{1_3}}，can't use '_'，'_' is invalid

### ISSUE THREAD

**Issue by 2896726646** [tailwindlabs/tailwindcss#4016]
### What version of Tailwind CSS are you using?

v2.1.0

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Microsoft Edge

### What operating system are you using?

Windows

### Reproduction repository

https

v2.1.0 bug
extend: {
       width: {
         '1_3': '33.3333333%',
       }
      }
I can't use '_'，it is invalid,but 'v2.0.3' can

**Comment by adamwathan** [comment]
Appears to work here:

https://play.tailwindcss.com/4Rq7kQqs7N

Please open a new issue with a reproduction if this is still a problem.
