### ISSUE TITLE
[JIT] Styles not being picked at all after migrating from package

### ISSUE THREAD

**Issue by raulfdm** [tailwindlabs/tailwindcss#4039]
### What version of Tailwind CSS are you using?

2.1.1

### What build tool (or framework if it abstracts the build tool) are you using?

NextJS 10.1.3 (with webpack 5), PostCSS 8.2.9, 

### What version of Node.js are you using?

14.15.1

### What browser are you using?

N/A

### What operating system are you using?

Ubuntu

### Reproduction repository

https://github.com/raulfdm/raulmelo-studio/pull/151

- Live version of that branch: https://raulmelo-dev-git-upgrade-tailwind-jit-raulfdm.vercel.app/en/blog
- production using `@tailwindcss/jit`: https://raulmelo.dev

### Describe your issue

Hey guys... First, thanks for the JIT mode. It's just awesome.

I have been using the package (`@tailwindcss/jit`) since the announcement and it does solve all my DX problems.

I'm having a bit trouble to do the migration itself.

In the branch I've just shared, you can notice that I've removed the package from PostCSS and add the "jit" mode. But as you can see in the preview URL, it's totally broken and it does not pick ANY style.

I'm not sure if I'm missing something, if my purge links are not being found by `tailwindcss`. I'm not even sure if it's an issue or more a guidance needed.

Anyways, hope you can help me out.

Cheers.

**Comment by adamwathan** [comment]
Hey! Commented in your repo but you removed `@tailwindcss/jit` and forgot to add `tailwindcss` instead. Should work then.

**Comment by raulfdm** [comment]
Hey @adamwathan , thanks man. I missed that.

For those who have the same problem, after adding `tailwindcss` to your PostCSS config, don't forget to remove `.next` folder and then running it over again.
