### ISSUE TITLE
JIT not creating properly classes when classes are inside a component exporting an SVG

### ISSUE THREAD

**Issue by filliperomero** [tailwindlabs/tailwindcss#4047]
### What version of Tailwind CSS are you using?

2.1.1

### What build tool (or framework if it abstracts the build tool) are you using?

postcss 8.2.10 nextjs 10.1.3

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/filliperomero/nextjs-template

### Describe your issue

The Repository provided is a boilerplate that I created for nextjs. Has more stuff than needed but is a repository that you can find the bug.

The problem that I'm facing right now is when I use a component to return an SVG (that way I don't need to use any external package) and put some tailwind classes in svg tag.

Tailwind jit is not creating the css class correct when I put classes inside the SVG. It will only work if these classes are being used in another component.

For example:
If my component exporting svg has something like that:
```
const Sun = () => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" className="h-16 w-16">
  </svg>
)
export default Sun
```
And I'm not using "h-16 w-16" anywhere in the code, tailwind will not create this classes for me. BUT if I'm using these classes anywhere in the code, than it will work.

Maybe tailwind jit is not looking for this type of files? Or I'm doing something wrong here?

To reproduce the problem, simple run the boilerplate and go to **Moon.tsx**. You can change the classes to "h-16 w-16". This will work since h-16 and w-16 are being used in **index.jsx**. But if you change to "h-24 w-24" for example, it will not work.

**Comment by adamwathan** [comment]
Hey! You are missing your src/assets directory in your purge config 👍🏻

**Comment by filliperomero** [comment]
> Hey! You are missing your src/assets directory in your purge config 👍🏻

My Bad @adamwathan. Forgot a simple step =P
Just made the change and now it is working. Thanks
