### ISSUE TITLE
matchUtilities is not a function in Just-in-Time Mode

### ISSUE THREAD

**Issue by Demetryi** [tailwindlabs/tailwindcss#4050]
### What version of Tailwind CSS are you using?

2.1.1

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js 10.1.3, @emotion 11.x, xwind 0.8.0

### What version of Node.js are you using?

v14.5.3

### What browser are you using?

Chrome

### What operating system are you using?

macOs

### Reproduction repository

https://github.com/Demetryi/TailwindJITBug

### Describe your issue

When I start using mode: "jit" I get
```javascript"
matchUtilities is not a function
```
error, removing jit no error.

**Comment by Demetryi** [comment]
tailwind config:

```
const colors = require("tailwindcss/colors");

module.exports = {
    // darkMode: "class",
    mode: "jit",
    theme: {
        fontFamily: {
            sans: ["SuisseIntl", "sans-serif", "serif"],
        },
        colors: {
            ...colors,
            textPrimary: "#212934",
            textSecondary: "#6E7A8A",
            textDisabled: "#929FB1",
            lineBG: "#CCD4DB",
            grayBG: "#f5f5f5",
            primary: "#0F66C4",
            secondary: "#606060",
            primaryHover: "#0D54A0",
            disabled: "#528CCB",
            buttonText: "#F9F9F9",
            linkHover: "#143C8A",
            linkLine: "#1D68BA",
            transparent: "transparent",
        },
        fontWeight: {
            hairline: 100,
            thin: 200,
            light: 300,
            regular: 400,
            book: 450,
            medium: 500,
            semibold: 600,
            bold: 700,
            black: 900,
        },
        rotate: {
            "-225": "-225deg",
            "-180": "-180deg",
            "-135": "-135deg",
            "-90": "-90deg",
            "-45": "-45deg",
            0: "0",
            45: "45deg",
            90: "90deg",
            135: "135deg",
            180: "180deg",
            225: "225deg",
        },
        extend: {
            width: {
                "50gap": "calc(50% - 20px)",
                "10px": "10px",
                "16px": "16px",
                "27px": "27px",
                "32px": "32px",
                "48px": "48px",
                "64px": "64px",
                "150px": "150px",
                "256px": "256px",
                "287px": "287px",
                "320px": "320px",
                "367px": "367px",
                "384px": "384px",
                "434px": "434px",
                "885px": "885px",
                "1342px": "1342px",
                "1444px": "1444px",
                screen15: "115vw",
            },
            maxWidth: {
                "1/4": "25%",
                "1/2": "50%",
                "3/4": "75%",
            },
            minHeight: {
                0: "0",
                "50px": "50px",
                "1/4": "25%",
                "1/2": "50%",
                "3/4": "75%",
                full: "100%",
                75: "75vh",
                85: "85vh",
                95: "95vh",
                screen: "100vh",
                "150px": "150px",
                "210px": "210px",
                "285px": "285px",
                "495px": "495px",
                "585px": "585px",
            },
            minWidth: {
                "434px": "434px",
            },
            screens: {
                mc: "1400px",
                "3xl": "1920px",
            },
            fontSize: {
                "5.5xl": "3.45rem",
            },
            listStyleType: {
                square: "square",
            },
        },
    },
    variants: {
        extend: {
            textDecoration: ["focus-visible"],
        },
    },
    plugins: [require("xwind/plugins/base"), require("@tailwindcss/aspect-ratio")],
    xwind: {
        mode: "objectstyles",
    },
    corePlugins: {
        float: false,
    },
    purge: {
        content: ["./src/**/*.tsx"],
        options: {
            keyframes: true,
            fontFace: true,
        },
    },
};
```
package.json :
```
{
    "name": "fidelit-stroy",
    "version": "0.1.2",
    "private": true,
    "scripts": {
        "dev": "next dev",
        "build": "next build",
        "bundleAnalyze": "ANALYZE=true next build",
        "postbuild": "next-sitemap",
        "start": "next start",
        "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
        "format": "prettier --write \"**/*.{js,ts,tsx,scss,json,css}\""
    },
    "resolutions": {
        "webpack": "^5.3.2"
    },
    "dependencies": {
        "@emotion/react": "^11.1.5",
        "@emotion/styled": "11.3.0",
        "dotenv": "^8.2.0",
        "next": "10.1.3",
        "react": "17.0.2",
        "react-dom": "17.0.2",
        "react-focus-lock": "^2.5.0",
        "react-hook-form": "^7.0.6",
        "swiper": "^6.5.6"
    },
    "devDependencies": {
        "@babel/core": "^7.13.15",
        "@babel/plugin-proposal-export-namespace-from": "^7.12.1",
        "@babel/preset-react": "^7.13.13",
        "@babel/runtime": "^7.13.10",
        "@emotion/babel-plugin": "11.3.0",
        "@emotion/server": "^11.0.0",
        "@next/bundle-analyzer": "^10.1.3",
        "@tailwindcss/aspect-ratio": "^0.2.0",
        "@types/node": "^14.14.37",
        "@types/react": "^17.0.3",
        "@types/react-dom": "^17.0.3",
        "@typescript-eslint/eslint-plugin": "^4.21.0",
        "@typescript-eslint/parser": "^4.21.0",
        "autoprefixer": "10.2.5",
        "babel-jest": "^26.6.1",
        "babel-plugin-module-resolver": "^4.0.0",
        "eslint": "^7.24.0",
        "eslint-config-prettier": "^8.1.0",
        "eslint-import-resolver-babel-module": "^5.2.0",
        "eslint-plugin-import": "^2.22.1",
        "eslint-plugin-prettier": "^3.1.4",
        "eslint-plugin-react": "^7.23.2",
        "next-compose-plugins": "^2.2.1",
        "next-pwa": "^5.2.9",
        "next-seo": "^4.23.0",
        "next-sitemap": "^1.6.25",
        "postcss": "8.2.10",
        "prettier": "^2.2.1",
        "purify-amp-css": "^1.1.1",
        "react-google-recaptcha-v3": "^1.9.0",
        "tailwindcss": "^2.1.1",
        "terser-webpack-plugin": "^5.1.1",
        "typescript": "^4.2.4",
        "typescript-xwind-plugin": "^0.8.0",
        "xwind": "0.8.0"
    }
}

```

**Comment by adamwathan** [comment]
Hey! Your reproduction is private so we're not able to troubleshoot it, please make it public so we can look 👍🏻

**Comment by Demetryi** [comment]
Updated with new repo

**Comment by Demetryi** [comment]
I created a new repository, removed almost everything from it and left the config files untouched
it reproduces the problem, and if you disable JIT, then everything starts as intended

**Comment by adamwathan** [comment]
Sorry I can't even get the dependencies to properly install in this project. Am I missing any important steps other than just `npm install`?

I'm seeing this after running `npm install` then trying to run `npm run dev`:

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/4323180/114391314-541b2780-9b65-11eb-81dd-6238545f9b6e.png">

**Comment by Demetryi** [comment]
> Sorry I can't even get the dependencies to properly install in this project. Am I missing any important steps other than just `npm install`?
> 
> I'm seeing this after running `npm install` then trying to run `npm run dev`:
> 
> <img alt="image" width="1008" src="https://user-images.githubusercontent.com/4323180/114391314-541b2780-9b65-11eb-81dd-6238545f9b6e.png">

Sorry, I forgot to remove the use of .env variables from the config.
i removed them and also disabled jit
now everything will start for you, and it will break as soon as you add JIT

**Comment by adamwathan** [comment]
Still getting the same error about `chalk` when trying to run `npm run dev`, even though I can see it in `node_modules`. Not sure what's up here, any chance you can reproduce in a totally vanilla fresh Next.js project/

**Comment by Demetryi** [comment]
Updated repo again, removed almost everything...
I have no idea what might be going wrong with you, and from what this problem appeared, but as you can see, only babel config, next config, tailwind and tsconfig are left here.
my project is still starting and I still get an error if I enable JIT
I also removed almost all custom dependencies.
could there be any problem with my local environment?

**Comment by adamwathan** [comment]
Ah got it building, had to remove package-lock.json because it was pointing to a private NPM cache or something.

The problem is [xwind](https://github.com/Arthie/xwind), it hasn't been updated to understand the new APIs we are using in JIT mode in 2.1+. They must be invoking our internal plugin objects and passing in their own version of the plugin API, but not providing the new `matchUtilities` function.

Unfortunately nothing we can do here, you'll have to open an issue on that project :(

**Comment by estubmo** [comment]
I'm getting errors regarding `matchUtilities` too both from `pretty-quick` and `eslint` while jit is enabled.


"eslint": "^7.25.0",
"prettier": "^2.2.1",
"pretty-quick": "^3.1.0",
"tailwindcss": "^2.1.2"

**Comment by marshal-yurii** [comment]
> I'm getting errors regarding `matchUtilities` too both from `pretty-quick` and `eslint` while jit is enabled.
> 
> "eslint": "^7.25.0",
> "prettier": "^2.2.1",
> "pretty-quick": "^3.1.0",
> "tailwindcss": "^2.1.2"
> 
> Not sure why eslint and pretty-quick cares about something in node_modules, but somehow the error triggers.
> 
> UPDATE: The problem was actually due to `prettier-plugin-tailwind`. Removing that fixed the issue.

IDK how did you catch this dependency, just thanks

**Comment by merelinguist** [comment]
> I'm getting errors regarding `matchUtilities` too both from `pretty-quick` and `eslint` while jit is enabled.
> 
> "eslint": "^7.25.0",
> "prettier": "^2.2.1",
> "pretty-quick": "^3.1.0",
> "tailwindcss": "^2.1.2"
> 
> Not sure why eslint and pretty-quick cares about something in node_modules, but somehow the error triggers.
> 
> UPDATE: The problem was actually due to `prettier-plugin-tailwind`. Removing that fixed the issue.

This was the problem for me too. I suggest replacing it with `eslint-plugin-tailwindcss`.
