### ISSUE TITLE
Style file lacks lots of settings

### ISSUE THREAD

**Issue by lironmo** [tailwindlabs/tailwindcss#4055]
### What version of Tailwind CSS are you using?

2.0.4

### What build tool (or framework if it abstracts the build tool) are you using?

tailwind build 

### What version of Node.js are you using?

v12.0.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/creativetimofficial/notus-react

### Describe your issue

Hi,
I am using the following projects https://github.com/creativetimofficial/notus-react, 
and it seems that they are using a different method to use tailwind.
first, they use tailwind build command to build the stylesheet CSS (https://github.com/creativetimofficial/notus-react/blob/main/src/assets/styles/tailwind.css), and then they imported it to the react project.

it seems that the build process creates a stylesheet file that missing lots of settings (the list is huge: float-right, capitalize , etc).

i tried to rebuild with no success. 

you can see also https://github.com/creativetimofficial/notus-react/issues/8

**Comment by adamwathan** [comment]
Hey, they are purging unused styles as configured here:

https://github.com/creativetimofficial/notus-react/blob/main/tailwind.config.js#L6

Please [read the documentation on optimizing for production](https://tailwindcss.com/docs/optimizing-for-production) for more information.

No bug or anything in Tailwind itself here so closing.

**Comment by kuzdogan** [comment]
Take a look here if you want to avoid building the `tailwind.css` too frequently.

https://github.com/creativetimofficial/notus-react/issues/8#issuecomment-831889534
