### ISSUE TITLE
[JIT] Can't set arbitrary value for transform origin

### ISSUE THREAD

**Issue by mokhosh** [tailwindlabs/tailwindcss#4079]
### What version of Tailwind CSS are you using?

v2.1.0

### What build tool (or framework if it abstracts the build tool) are you using?

laravel mix

### What version of Node.js are you using?

14.15.1

### What browser are you using?

chrome

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/mokhosh/tailwindcss-jit-transform-origin-arbitrary-value

### Describe your issue

You can set many arbitrary values when JIT is enabled which is super awesome, but setting arbitrary values for `transform-origin` doesn't seem to work:
```
origin-[35% 80%]
```
produces nothing.

**Comment by mokhosh** [comment]
The example repo uses Vite btw

**Comment by adamwathan** [comment]
Try using canary build, should be supported now!

`npm install -D tailwindcss@canary`

Will be out proper in v2.2 👍🏻

**Comment by impcyber** [comment]
tailwindcss@2.2.12
still not workinging:
![Screenshot_20210908_150541](https://user-images.githubusercontent.com/1425691/132506728-fe468e0d-acfa-446d-9183-f5b98e788fa0.png)
![Screenshot_20210908_150955](https://user-images.githubusercontent.com/1425691/132506819-8d481565-0213-4fed-b4f2-90b016e70b9d.png)
