### ISSUE TITLE
media query partially broken for absolute positioning

### ISSUE THREAD

**Issue by pdevito3** [tailwindlabs/tailwindcss#4089]
### What version of Tailwind CSS are you using?

2.1.1

### What build tool (or framework if it abstracts the build tool) are you using?

play.tailwind

### What version of Node.js are you using?

play.tailwind

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### Reproduction repository

https://play.tailwindcss.com/EhKZ5Gop25

### Describe your issue

I noticed this when working with the dropdown component from TUI. In an effort to save time and not have to deal with popperjs, I am adjusting the `origin-top-XXX` `XXX-0` positions with a media query.

If I do this, the media query works as expected and the dropdown shifts sides depending on screen size:
`origin-top-right absolute right-0 mt-2 w-56 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 focus:outline-none md:origin-top-left md:left-0`

but if I switch it to have it be left by default and right with md+, it doesn't work anymore:
`origin-top-left absolute left-0 mt-2 w-56 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 focus:outline-none md:origin-top-right md:right-0`

If you resize the preview page in the twplay link, you'll see one dropdown change and the other stay the same

**Comment by alexanderbluhm** [comment]
@pdevito3 Hi! You have to set `md:left-auto` in order to bring this to work. https://play.tailwindcss.com/MMV0ucSKZ2?size=758x720
I am not sure 100% sure why this is the case so I will not try to explain it but sometimes you have to kinda _reset_ utilities when resizing.

**Comment by pdevito3** [comment]
huh, interesting. weird that you have to reset for one side but not the other. regardless, thanks for the response!
