### ISSUE TITLE
Compiler freezes when declaring custom components with name collisions

### ISSUE THREAD

**Issue by benknight** [tailwindlabs/tailwindcss#4101]
### What version of Tailwind CSS are you using?

2.1.1

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js 10.0.4

### What version of Node.js are you using?

14.15.0

### What browser are you using?

Not relevant

### What operating system are you using?

macOS

### Reproduction repository

Not relevant

### Describe your issue

This code causes the compiler to go down in flames:

```css
@layer components {
  .block {
    @apply block;
  }
}
```

Once I realized the issue it's obvious that this would cause an infinite loop however I was puzzled for a long time before I realized my mistake, especially because it was failing in ways I didn't expect.

My suggestion is to put some protection in place to prevent declaring custom components with name collisions so that it's obvious to developers when they've made a mistake.

Note: Didn't make a repro repo because this bug seems pretty straightforward to describe and reproduce. Just trying to help out by reporting the issue.

**Comment by thecrypticace** [comment]
As of Tailwind CSS v3.0.1+ we direct cases like this and will now throw an error when `@apply` is used and it results in a circular dependency which would otherwise cause infinite loops. Thanks for the report!
