### ISSUE TITLE
[JIT]: FLEX CLASS NOT WORKING 

### ISSUE THREAD

**Issue by maupeon** [tailwindlabs/tailwindcss#4131]
### What version of Tailwind CSS are you using?

v2.1.0

### What build tool (or framework if it abstracts the build tool) are you using?

"postcss-cli": "^8.3.1"

### What version of Node.js are you using?

v12.19.0

### What browser are you using?

Chrome

### What operating system are you using?

macOs

### Describe your issue

I am adding "flex" class in my react app project and for some reason, it doesn't read it, I changed to JIT mode and some styles are not working as they used to.

**Comment by maupeon** [comment]
![Captura de Pantalla 2021-04-20 a la(s) 3 01 36 p m](https://user-images.githubusercontent.com/17842403/115456898-53c7ff80-a1e9-11eb-8912-e40945eb0762.png)

**Comment by maupeon** [comment]
It has a flex class, but the icon is not moving

**Comment by adamwathan** [comment]
Hey! Unfortunately we can't help without a reproduction. You don't need to share your actual project, you just need to make a new sample project that includes whatever is required to reproduce the bug.

This is likely due to you missing things in your `purge` configuration, but impossible to tell without a reproduction.

**Comment by maupeon** [comment]
@adamwathan Thanks a lot ! I will try to reproduce it and come back.

**Comment by unigazer** [comment]
This happens with "create-react-app", but everything is ok with "Next.js". Not sure about other SSR React libraries.

**Comment by maupeon** [comment]
@adamwathan  I have just reproduced the issue in this repository : https://github.com/maupeon/example-tailwind

**Comment by maupeon** [comment]
> This happens with "create-react-app", but everything is ok with "Next.js". Not sure about other SSR React libraries.

@unigazer Thanks for the answer!  But for now I am using create-react-app and I need a solution

**Comment by bradlc** [comment]
Thanks for providing a reproduction! I have confirmed that #4078 fixes your issue. If you update to `v2.1.2` it should work fine 👍
