### ISSUE TITLE
why css is not overriding class='bg-blue-500 bg-white' then element css applying bg-blue-500 should be bg-white

### ISSUE THREAD

**Issue by gauravverma029** [tailwindlabs/tailwindcss#4143]
### What version of Tailwind CSS are you using?

v2.0.4

### What build tool (or framework if it abstracts the build tool) are you using?

 postcss-cli 8.3.1,

### What version of Node.js are you using?

12

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://tailwindcss.com/

### Describe your issue

<img width="1440" alt="Screen Shot 2021-04-21 at 14 47 27" src="https://user-images.githubusercontent.com/4488516/115556061-85f06480-a2b0-11eb-849a-8a2743007cc6.png">

See i am trying to override css class="bg-blue-500 bg-white rounded-r-xl sm:rounded-xl overflow-hidden p-8 text-center"

bg-blue-500  bg-white (bg-white class should apply)

**Comment by quick007** [comment]
Css classes might be applied based on the order that the browser gets them versus what order they are in `className=`

**Comment by forsigner** [comment]
CSS priority is not binded with CSS class order, it base on css rule's registered order.

For example, if you have some css rule like below:
```css
.red {
  color: red;
}
.blue {
  color: blue;
}
```
```html
<span className="red blue">I am blue </Text>
<span className="red blue">Will be blue, too</span>
```
If you need a intuitive way to override style, you can try something like: https://fower.vercel.app/docs/predictable-style

**Comment by liho00** [comment]
having this issue as well, look like tailwind css do not have this feature yet https://github.com/tailwindlabs/tailwindcss/discussions/1446
