### ISSUE TITLE
[Bug]: Inconsistent Fractional Units

### ISSUE THREAD

**Issue by cryptus-neoxys** [tailwindlabs/tailwindcss#4166]
### What version of Tailwind CSS are you using?

v2.1.1

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js 10.1.3

### What version of Node.js are you using?

v14.16.1

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu 20.04, Windows 10

### Reproduction repository

https://github.com/0x-45/saaraansh

### Describe your issue

The relative units provided as fractions have internal inconsistencies:

h-1/2 | height: 50%;
-- | --
h-1/3 | height: 33.333333%;
h-2/3 | height: 66.666667%;
h-1/4 | height: 25%;
h-2/4 | height: 50%;
h-3/4 | height: 75%;
h-1/5 | height: 20%;
h-2/5 | height: 40%;
h-3/5 | height: 60%;
h-4/5 | height: 80%;
h-1/6 | height: 16.666667%;
h-2/6 | height: 33.333333%;
h-3/6 | height: 50;
h-4/6 | height: 66.666667%;
h-5/6 | height: 83.333333%;
h-full | height: 100%;

whereas every other property like translate, top, inset, etc provide a different set, which has redundant implementations as well as misses some:

translate-x-1/2 | --tw-translate-x: 50%;
-- | --
translate-x-1/3 | --tw-translate-x: 33.333333%;
translate-x-2/3 | --tw-translate-x: 66.666667%;
translate-x-1/4 | --tw-translate-x: 25%;
translate-x-2/4 | --tw-translate-x: 50%;
translate-x-3/4 | --tw-translate-x: 75%;
translate-x-full | --tw-translate-x: 100%;

These are the redundant classes

**h-1/2  height: 50%;**
**h-2/4  height: 50%;**
**h-3/6  height: 50;**

These are the missing classes:

**h-1/6  height: 16.666667%;**
**h-1/5 | height: 20%;**
**h-2/5 | height: 40%;**
**h-3/5  height: 60%;**
**h-4/5  height: 80%;**
**h-5/6  height: 83.333333%;**

**Comment by adamwathan** [comment]
Hey! This is by design to reduce the file size of the CDN build. The width/height values have more options as people often use them for grids. The redundant values weren't there originally but people asked but people asked for them because it was annoying to build grids where you were mixing the denominator.

You can add any extra values you need in your config file 👍🏻
