### ISSUE TITLE
[Bug]: Tailwind JIT props bug

### ISSUE THREAD

**Issue by quick007** [tailwindlabs/tailwindcss#4172]
### What version of Tailwind CSS are you using?

v2.1.1

### What build tool (or framework if it abstracts the build tool) are you using?

Postcss v8.2.10, Nextjs v10.1.3

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/quick007/quartzstudios.net/commit/a049cd958cb9ebe65e0a4b409c63c493992aa1f8?branch=a049cd958cb9ebe65e0a4b409c63c493992aa1f8&diff=unified#diff-d57061008add8908d8dbf1d5c0d9b867f90af31ebe64bc219e1859f8933a104fR13

### Describe your issue

No idea how to make a minima reproduction repo, but that should work for an example. Basically, if you use tailwind jit with props, it doesn't render. Here's an example of what I mean: `"bg-[" + props.roleColor +"]"`.

**Comment by cossssmin** [comment]
It's not exactly a bug, purgecss needs to 'see' the class name in full, have a look at:

https://tailwindcss.com/docs/optimizing-for-production#writing-purgeable-html

**Comment by quick007** [comment]
> It's not exactly a bug, purgecss needs to 'see' the class name in full, have a look at:
> 
> https://tailwindcss.com/docs/optimizing-for-production#writing-purgeable-html

Ah right, thank you.
