### ISSUE TITLE
[Bug]: fontFamily doesn't have quotes around values with spaces

### ISSUE THREAD

**Issue by vladdu** [tailwindlabs/tailwindcss#4173]
### What version of Tailwind CSS are you using?

2.1.0

### What build tool (or framework if it abstracts the build tool) are you using?

mix 6.0.18, postcss 8.2.9

### What version of Node.js are you using?

14.16.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

N/A

### Describe your issue

The values for fontFamily that have spaces don't get quotes around them. In the default configuration, you can see that for "Times New Roman".

**Comment by adamwathan** [comment]
Hey! Not sure what your problem actually is here, font families preserve any quotes you include. Here's a screenshot from our CDN build:

<img width="958" alt="image" src="https://user-images.githubusercontent.com/4323180/115990824-62b90400-a593-11eb-8360-4836d6c59c14.png">


Just make sure you include the quotes yourself if you want them in the output, like we do in the default config (notice the extra pair of quotes for fonts with spaces):

<img width="662" alt="image" src="https://user-images.githubusercontent.com/4323180/115990834-719fb680-a593-11eb-9597-6144cd94bf9f.png">

Please open a new issue with a reproduction if you're still having an issue, it's a required field.

**Comment by vladdu** [comment]
You are right, I apologize for not checking in a clean repo. It was cssnano, but to my defense it was installed as a third party dependency.
