### ISSUE TITLE
[jit]: not generate class .backdrop-*

### ISSUE THREAD

**Issue by kenhyuwa** [tailwindlabs/tailwindcss#4175]
### What version of Tailwind CSS are you using?

^2.1.2-compact

### What build tool (or framework if it abstracts the build tool) are you using?

nuxtjs

### What version of Node.js are you using?

^12.0.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

N/A

### Describe your issue

all class .backdrop-* not generating properly if tailwind.config.js `mode: 'jit` or nuxt.config.js `jit: true`

**Comment by adamwathan** [comment]
> Unfortunately we can't provide support without a reproduction, and your issue will be closed and locked with no comment if this is not provided.

Please open a new issue with a reproduction.
