### ISSUE TITLE
[Bug]: space-x- uses marginLeft so elements aren't aligned when wrapped

### ISSUE THREAD

**Issue by alicerocheman** [tailwindlabs/tailwindcss#4226]
### What version of Tailwind CSS are you using?

2.1.1

### What build tool (or framework if it abstracts the build tool) are you using?

next 10.0.8

### What version of Node.js are you using?

14.16.0

### What browser are you using?

chrome

### What operating system are you using?

macOS

### Reproduction repository

---

### Describe your issue

`space-x-4` adds left margin except on first element, which breaks alignement when wrapped on several rows

Use Case:
```tsx
<div className="flex flex-row items-baseline flex-nowrap space-x-3 space-y-2">
  {elements.map(e => <Tag tag={e} />}
</div>
```

Result: elements are not aligned on the left when wrapped on several rows
<img width="425" alt="Screenshot 2021-05-03 at 08 24 05" src="https://user-images.githubusercontent.com/21168856/116848579-2e75c100-abed-11eb-9c6b-ca342f6bf9eb.png">

**Comment by alexanderbluhm** [comment]
@alicerocheman This is no bug, this is intentional.
Until `flex-gap` has better browser support you can use this trick with _negative margins_ to achieve what you are looking for:
```html
<div class="flex flex-wrap -m-2">
  <span class="bg-green-600 m-2 text-white font-medium text-sm rounded-full px-2 py-1">Test</span>
  <span class="bg-green-600 m-2 text-white font-medium text-sm rounded-full px-2 py-1">Test</span>
  ```

**Comment by neupauer** [comment]
Safari (14.1) finally supports `gap` property for flexbox elements, so you can use `gap` (`gap-x` / `gap-y`) utils.

Links:
[New WebKit Features in Safari 14.1](https://webkit.org/blog/11648/new-webkit-features-in-safari-14-1/)
[`gap` property for Flexbox](https://caniuse.com/?search=gap)

**Comment by adamwathan** [comment]
Yeah as mentioned this is just an annoying limitation of the solutions available to us in a pre-`gap` era 😅  You can use @alexanderbluhm's solution if you need to worry about Safari < 14.1, or use `gap` if you only need to support super modern browsers.

**Comment by alicerocheman** [comment]
Thank you for your answers!
