### ISSUE TITLE
[Bug]: Spacing inheritance in maxWidth

### ISSUE THREAD

**Issue by Atakku** [tailwindlabs/tailwindcss#4235]
### What version of Tailwind CSS are you using?

v2.0.4

### What build tool (or framework if it abstracts the build tool) are you using?

tailwindcss-cli

### What version of Node.js are you using?

v15.14.0

### What browser are you using?

N/A

### What operating system are you using?

Linux

### Reproduction repository

N/A

### Describe your issue

It seems that in the default full `tailwind.config.js`, `maxHeight` inherits `spacing` values but `maxWidth` doesn't. Is this a bug or intended feature? Also `minWidth` and `minHeight` don't seem to inherit `spacing` as well.

**Comment by adamwathan** [comment]
Hey! Yep these are all deliberate decisions to try and make things as useful as possible while still keeping the the file size as low as possible in development to avoid performance problems in the browser. You can edit your config if you'd like to add those extra values though 👍🏻 

We may enable more stuff by default in v3.0 when JIT mode is the default.
