### ISSUE TITLE
[Bug]: Issue with `select` and `color: inherit` in MS Edge

### ISSUE THREAD

**Issue by ecrmnn** [tailwindlabs/tailwindcss#4240]
### What version of Tailwind CSS are you using?

2.0.3

### What build tool (or framework if it abstracts the build tool) are you using?

Mix

### What version of Node.js are you using?

12

### What browser are you using?

Edge

### What operating system are you using?

MacOS 10.15.7

### Reproduction repository

https://play.tailwindcss.com/xbTHOeKYGG

### Describe your issue

`select` don't work properly in MS Edge (v.90.0.818.51) when parent element has `text-white` due to `color: inherit`.

[Working example](https://play.tailwindcss.com/xbTHOeKYGG)

![xxs](https://user-images.githubusercontent.com/1481696/117000003-b983b380-ace0-11eb-809f-73eab6e6eca4.gif)

**Comment by adamwathan** [comment]
Hey! This is by design for better or for worse. You can override this by adding a text color utility to the select element:

```html
<select class="text-black">
```

Relevant PR where this was originally added: https://github.com/tailwindlabs/tailwindcss/pull/741
