### ISSUE TITLE
[Bug]: With jit mode enabled, classes with arbitrary value containing calc and css variables doesn't work as expected

### ISSUE THREAD

**Issue by AhmedSayed77** [tailwindlabs/tailwindcss#4241]
### What version of Tailwind CSS are you using?

2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js 10.2.0, postcss 8.2.13

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Firefox, Chrome

### What operating system are you using?

ubuntu 20.04

### Reproduction repository

https://github.com/AhmedSayed77/tailwind-hit-issue-reproduction

### Describe your issue

I have a div which has a height calculated from 2 css variables. When I tried to use the `Arbitrary values` feature, I wrote the class like this `h-[calc(var(--first-variable) - var(--second-variable))]`, and I found that the class was not generated at all
![Screenshot from 2021-05-04 16-40-37](https://user-images.githubusercontent.com/15085304/117021742-e68f9080-acf7-11eb-8356-425f056afda1.png)
when I tried to remove the spaces that surrounds the subtraction sign `h-[calc(var(--first-variable)-var(--second-variable))]`, the class was generated correctly, and the spaces were inserted in the value, but variable names contained spaces too, and they were invalid

![Screenshot from 2021-05-04 16-40-24](https://user-images.githubusercontent.com/15085304/117022044-33736700-acf8-11eb-943d-acfa95f0e235.png)

the code can be found in the reproduction repo, in the `pages` folder, in the `index` file

**Comment by adamwathan** [comment]
Hey! This should be fixed in the next release, try installing our preview build in the mean time 👍 

`npm install -D tailwindcss@canary`
