### ISSUE TITLE
[Bug]: Preflight semantic tag HR include visible line

### ISSUE THREAD

**Issue by Triloworld** [tailwindlabs/tailwindcss#4249]
### What version of Tailwind CSS are you using?

v2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

N/A

### What version of Node.js are you using?

v16.1.0

### What browser are you using?

N/A

### What operating system are you using?

N/A

### Reproduction repository

N/A

### Describe your issue

This pull request was by mistake added to core:
https://github.com/tailwindlabs/tailwindcss/issues/979

From HTML5 Standard: https://html.spec.whatwg.org/multipage/grouping-content.html#the-hr-element

> The hr element represents a paragraph-level thematic break, e.g. a scene change in a story, or a transition to another topic within a section of a reference book.

From MDN: https://developer.mozilla.org/pl/docs/Web/HTML/Element/hr

> Historically, this has been presented as a horizontal rule or line. While it may still be displayed as a horizontal rule in visual browsers, this element **is now defined in semantic terms**, rather than presentational terms, so if you wish to draw a horizontal line, you should do so using appropriate CSS.

Right now, people add "hr" to use as a VISUAL rather than SEMANTIC line between paragraphs and this border suggest wrong use as documentation say. Understand some margin but not line in default scenario. It create new pages in wrong way and this library have impact how elements are used.

Can someone point my WHY this border is added in preflight? 
What standard is used for preflight to align to if someone find error like this.
Yes: Can have border. No: This library don't need to advocate that type of usage

In global: What is ok in preflight to be and what not? That's a question before find another error like this one from Semantic perspective.

**Comment by adamwathan** [comment]
You can remove the border if you don't want it there by adding the `border-0` utility or adding your own custom base style to override the default base styles we include for `hr` elements. Not changing this as it would be a breaking change.
