### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Danon** [tailwindlabs/tailwindcss#4258]
### What version of Tailwind CSS are you using?

2.1.0

### What build tool (or framework if it abstracts the build tool) are you using?

webpack

### What version of Node.js are you using?

14.16.1

### What browser are you using?

Chrome 89.0.4389.128, 64-bit

### What operating system are you using?

Windows 10

### Reproduction repository

https://github.com/Danon/tailwind-em-issue

### Describe your issue

Tailwind offers `space-y-4` utility classes, that should put vertical spaces between elements. And it works, quite well, except when used with `order`.

```
<div className="flex space-y-4">
  <p className="order-last md:order-first"/>
  <p/>
</div>
```

If we change the order, there's space on one configuration and no space on the other, instead margin above the first is added.

**Comment by adamwathan** [comment]
Hey! This is just a limitation of the feature I'm afraid, and it would be extremely complicated to make it work in situations like this. The space utilities are just a shortcut for "add margin to every item except the first one", so if that's not the behavior you need it's better to rely on manual margins, or `gap` if you you're using grid.

**Comment by Danon** [comment]
@adamwathan Perhaps describe it on https://tailwindcss.com/docs/space ?

**Comment by adamwathan** [comment]
Good idea, added a limitations section 👍🏻
