### ISSUE TITLE
[Bug]: Grayscale functions as a "switch, whereas is should have percentage values

### ISSUE THREAD

**Issue by rowild** [tailwindlabs/tailwindcss#4288]
### What version of Tailwind CSS are you using?

2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

postcss 7

### What version of Node.js are you using?

12

### What browser are you using?

Chrome

### What operating system are you using?

macOS 10.15.7

### Reproduction repository

https://codepen.io/rowild/pen/ZEeGKMQ

### Describe your issue

The "vanilla" CSS grayscale filter allows usage with percentage values:
https://developer.mozilla.org/en-US/docs/Web/CSS/filter

Tailwind, however, only switches it on or off.

Is this a feature that will be implemented in future? Or did I miss something else?

Thank you!

**Comment by adamwathan** [comment]
Hey! You can add whatever extra values you want by editing the "grayscale" key in your Tailwind config file. We just ship with 0% and 100% by default to keep things simple and keep the CDN file size under control.

**Comment by rowild** [comment]
Ah, ok. Understood! (I would have expected "grayscale-100" as it is the standard with others.)
Thanks!
