### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by PatrickJoannisse** [tailwindlabs/tailwindcss#4304]
### What version of Tailwind CSS are you using?

2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

Laravel Mix 6.0.16

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

N/A

### What operating system are you using?

Windows (using WSL2)

### Reproduction repository

https://github.com/PatrickJoannisse/laravel-jit-bug

### Describe your issue

When I run `npm run dev` or `npm run watch` in a fresh install of Laravel using the latest instructions from tailwindcss.com and laravel.com, everything works fine. Like so

![image](https://user-images.githubusercontent.com/2472370/117722861-9c9f2280-b1af-11eb-9b85-eac5c274c1b0.png)

But when I enable **JIT mode,** the job never ends. Like it would when you run watch, except it does it for dev as well. Like this.

![image](https://user-images.githubusercontent.com/2472370/117723036-e25beb00-b1af-11eb-8470-9dfe6b1a4b8d.png)

**Comment by adamwathan** [comment]
Hey! This is expected unless you have set the `TAILWIND_MODE=build` env variable if `NODE_ENV=development`, see the docs:

https://tailwindcss.com/docs/just-in-time-mode#watch-mode-and-one-off-builds

**Comment by PatrickJoannisse** [comment]
I'm so angry at myself. I've been scratching my head for weeks and looking at Laravel Mix issues and Tailwind issues here trying to find the problem. Hopefully someone will stumble here and find my stupid question useful. Thanks @adamwathan !
