### ISSUE TITLE
[Bug]: Tailwindcss JIT doesn't add new classes when files change [watch mode cache issue]

### ISSUE THREAD

**Issue by okikio** [tailwindlabs/tailwindcss#4320]
### What version of Tailwind CSS are you using?

v2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

gulp 4.0.2, browser-sync 2.26.14, gulp-postcss 9.0.0, postcss 8.2.15, @csstools/postcss-sass 4.0.0, postcss-scss 3.0.5

### What version of Node.js are you using?

v15.11.0

### What browser are you using?

Edge Beta v91.0.864.19

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/okikio/native/tree/gitpod-test

### Describe your issue

When I edit my pug files e.g. I changing the padding or margin, tailwind jit mode doesn't update the css styles, but when I run the build script from scratch the new class will then appear. My build tool is gulp with browsersync, gulp-postcss, tailwindcss in jit mode, postcss-sass, and postcss-scss as the parser. 

My gulp build script watches for any change made to pug, sass, and/or typescript and builds the files correspondingly, for the pug build task, gulp is set to build the html and css (tailwind and sass) tasks in sequential order, but in actual practice tailwinds watch mode doesn't add new classes to the build, it requires me to completely cancel the gulp build script, and run it again (its rather frustrating).

**Note**: For testing purposes I removed the sass build component (I manually converted sass into css and removed sass from my css build task), and I have determined the issue to be with Tailwind itself.

The github repo is rather dense, so the parts you need to worry about are the /build/pug/index.pug file, and /build/sass/ folder, as well as the tailwind.cjs, and gulpfile.js files.

For verifying the issue you can view this error with Gitpod.

[![Edit with Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/okikio/native/blob/gitpod-test/build/pug/index.pug)

By default Gitpod will start the dev script for you, but if you need to restart the dev script you can do so by typing into the terminal.

```bash
pnpm demo
```

**Comment by okikio** [comment]
I have removed all unnecessary files, try it again. 

**Note**: The link I posted in the initial issue description allows you to view the project online without needing to clone the repo. 

Here is an updated Gitpod link.

[![Edit with Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/okikio/native/blob/gitpod-test/build/pug/index.pug)

**Comment by adamwathan** [comment]
This appears to be a bug with `gulp-postcss` — it looks like it doesn't support the PostCSS dependency message API which means we can't trigger rebuilds from within Tailwind itself.

One work around that seemed to work for me in your project was just watching the pug files instead of the HTML files:

```js
module.exports = {
    darkMode: 'class',
    mode: "jit",
    purge: [
        './build/**/*.pug'
    ],
    // ...
}
```

I suspect this works because Gulp is triggering the rebuild when those files change already.

Going to close as unfortunately not something we can fix within Tailwind itself, but have opened an issue for you on `gulp-postcss`:

https://github.com/postcss/gulp-postcss/issues/173

**Comment by okikio** [comment]
Thanks for your response. I initially tried using Pug but the issue occurred, so I switched to html hoping it might fix the bug but I guess all we can do is wait for the postcss bug to be fixed first.

**Comment by sebastianbaumann** [comment]
As the opened `gulp-postcss` issue by @adamwathan was closed already with no solution, is there any chance JIT will work with Gulp?

Right now I'm having the same issue as @okikio 
When enabling  `mode: 'jit'` the CSS file is not rebuild if I add any tailwind classes to my template files.

`tailwind.config.js`
```
 purge: {
    enabled: true,
    content: [
      './../templates/**/*.html.twig',
    ],
    ...
 }
```

`gulpfile.js`
```
watch(
  ['tailwind.config.js','./css/**/*.css','./../templates/**/*.html.twig'],
  series(processCSS)
);
```

**Comment by adamwathan** [comment]
My understanding is that you need to configure gulp to watch your templates manually as mentioned by the maintainer of gulp-postcss here:

https://github.com/postcss/gulp-postcss/issues/173#issuecomment-840107910

**Comment by okikio** [comment]
I'm confused, so in order to solve this issue I need to use a .txt dependency file?

**Comment by sebastianbaumann** [comment]
Thanks for your fast response! Really appreciate.

This also was my understanding, but as you can see in my comment above I already configured gulp to watch the template files for changes.

`watch(
   [… './../templates/**/*.html.twig'],
   series(processCSS)
);
`

So if I change anything in my templates, the `processCSS` task is triggered and running fine, but `tailwindcss` does not actually rebuild the css.

For example:

Add a class, which was not used before to any template file:  `<div class="bg-green-400">…</div>` .
The gulp task recognises the changes inside the templates file and runs my css task
```
[17:09:39] Starting 'processCSS'...
[17:09:39] Finished 'processCSS' after 202 ms
```
But the CSS itself does not contain any tailwind styles for the above specified class `bg-green-400`

Please note: this is only an issue when using `mode: 'jit'`.
If JIT is disabled this works fine.

Idk if this helps but:
- Here's my complete `gulpfile.js` : https://pastebin.com/U5cF0mDB
- This is my used `tailwind.config.js` https://pastebin.com/G0f12KCe

**Comment by sebastianbaumann** [comment]
I'm not sure if I'm understanding you correctly, but isn't your suggestion for the watch task the same as mine already is?
Please see my first comment or pastebin link.
 
 ```
watch(
            ['tailwind.config.js','./css/**/*.css','./../templates/**/*.html.twig'],
            series(processCSS)
    );
```
I'm watching the tailwind config file, my css files and the template files.

**Comment by okikio** [comment]
I don't know why your project isn't working, but when I tested it, it worked for me.

This is the tailwind config I used for my test, <https://pastebin.com/TRSSr7bF>,
This is the full gulpfile I used for my test, <https://pastebin.com/PZpquSH8>.
