### ISSUE TITLE
[Bug]: JIT not working with unitless line-height values

### ISSUE THREAD

**Issue by th-km** [tailwindlabs/tailwindcss#4326]
### What version of Tailwind CSS are you using?

v2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

next.js

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

Chrome, Firefox, Safari

### What operating system are you using?

macOs

### Reproduction repository

https://github.com/th-km/jit-issue

### Describe your issue

Using JIT with unitless line-height doesn't work. The code below won't produce a class:
```html
<h1 className="text-6xl leading-[1.125]">My title</h1>
```
While using `@apply` in a `@layer` directive will generate this error:
`If leading-[1.125] is a custom class, make sure it is defined within a @layer directive.`

**Comment by bradlc** [comment]
Hey @th-km. This should be fixed in the next release. In the meantime you can use the preview release if you like: `npm install -D tailwindcss@canary` 👍
