### ISSUE TITLE
[Bug]: sr-only causes whitespace in flex with overflow-scroll

### ISSUE THREAD

**Issue by timgoeller** [tailwindlabs/tailwindcss#4330]
### What version of Tailwind CSS are you using?

v.2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

vite

### What version of Node.js are you using?

v12.9.0

### What browser are you using?

Chrome / Safari

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/UXr9hDHS4z

### Describe your issue

Adding a `sr-only` element to a div inside a flex container with an `overflow-scroll` causes the overflow to not be visible but still take up space because of the absolute position of `sr-only`. This leads to a scrollbar at page level in the playground-example. A quick fix for this would be to add `top-0 left-0` to the element with `sr-only`, but this solution doesn't feel very intuitive or self-explanatory to someone else looking at the code.

**Comment by adamwathan** [comment]
Hey! This is annoying for sure when it shows up, my solution is always to just add `relative` to the container with the `sr-only` items though. Hesitant to change this implementation as it has lots of accessibility implications if you get it wrong and this is the same implementation used in other super battle-tested frameworks like Bootstrap.

https://play.tailwindcss.com/qBnoqIfVTe

So no plans to change this currently and recommend working around it in userland in the rare situations it shows up 👍🏻
