### ISSUE TITLE
JIT doesn't give a confirmation message after building and it doesn't watch

### ISSUE THREAD

**Issue by ralphjsmit** [tailwindlabs/tailwindcss#4345]
### What version of Tailwind CSS are you using?

v2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

"postcss": "^8.2.15", "postcss-cli": "^8.3.1",

### What version of Node.js are you using?

16.0.0 (also tested on 14.16.1)

### What browser are you using?

Safari

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/ralphjsmit/ralphjsmitcom

### Describe your issue

I've started building a Ghost theme and I want to use Tailwind CSS for this project. I followed the instructions from the TailwindCSS docs to install it and create a config file. After that I installed postCSS and added a script to my `package.json`.

I enabled the JIT engine and added the files to the `purge`. 

1. When I do a one-off build, I do not get the usual message from Tailwind with the things like 'Compiled in x seconds'. I only see the below message and after the generate is complete, the process in the CLI finishes. The generated file is correct.
```shell
warn - You have enabled the JIT engine which is currently in preview.
warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.
```

2. When I set the `NODE_ENV=development`, the file watching does not work. It seems stuck on the above two warnings and doesn't do anything when I make changes to files.

I already removed the Git repo from my computer, cloned it again, installed all dependencies, tested it – it didn't work.
The build command is (currently) `npm run build:css`. Below I added the configurations.

It'd be awesome if you could help me pinpoint the issue!

Many thanks, 
Ralph

<br>
<hr>
<br>

**tailwind.config.js**
```js
module.exports = {
  mode: "jit",
  purge: [
    '*.hbs',
    'partials/*.hbs'
  ],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
```

**postcss.config.js** 
```js
module.exports = {
	plugins: {
	  tailwindcss: {},
	  autoprefixer: {},
	}
  }
```

**package.json**
```js
	"devDependencies": {
		"autoprefixer": "^10.2.5",
		"postcss": "^8.2.15",
		"tailwindcss": "^2.1.2"
	},
	"scripts": {
		"build:css": "NODE_ENV=development postcss resources/css/tailwind.css -o assets/css/tailwind.css"
	},
	"dependencies": {
		"watch": "^0.13.0"
	}
```

**Comment by adamwathan** [comment]
Hey! To run the watcher you need to pass the `-w` flag to postcss-cli.

Personally I'd set up the scripts something like this:

```
"scripts": {
  "build:css": "NODE_ENV=production postcss resources/css/tailwind.css -o assets/css/tailwind.css"
  "watch:css": "NODE_ENV=development postcss resources/css/tailwind.css -o assets/css/tailwind.css -w"
},
```

**Comment by ralphjsmit** [comment]
Hey Adam, thanks a lot for coming back to me. I did change my scripts and they are now the following:

```js
	"scripts": {
		"dev": "NODE_ENV=development TAILWIND_MODE=build postcss assets/css/tailwind.css -o assets/css/dist/tailwind.css",
		"watch": "NODE_ENV=development postcss assets/css/tailwind.css -o assets/css/dist/tailwind.css -w",
		"prod": "NODE_ENV=production postcss assets/css/tailwind.css -o assets/css/dist/tailwind.css"
	}
```

For some reason it can't get it to work 100%. For example, it doesn't generate every class. Simple classes like `font-serif` are not being generated, whilst others are.

I've no idea what's been causing this, but I think that I'll switch to `npx` for now and give up on the idea of using JIT 🙃

**Comment by adamwathan** [comment]
Can you open a new issue with a reproduction? The existing one is 404ing for me so can't look. My guess is you are missing something in your `purge` config.

**Comment by ralphjsmit** [comment]
Hey Adam, I found the culprit – which was unwillingly caused by me. 

I changed the file structure at some point earlier. I reused a wrong `postcss` command at some point, so that the `@tailwind` declarations were overridden and thus they disappeared from the file. This caused the problems that occurred later, so totally my fault 😊

Thanks a lot for thinking along and advising those three scripts!
