### ISSUE TITLE
[Bug]: tailwindcss + Angular 12 - cannot put tailwind.config.js in subfolder

### ISSUE THREAD

**Issue by danilokorber** [tailwindlabs/tailwindcss#4355]
### What version of Tailwind CSS are you using?

v2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

postcss 8.2.14, angular 12.0.0

### What version of Node.js are you using?

v14.15.1

### What browser are you using?

Chrome, Edge (browser independent)

### What operating system are you using?

macOS Catalina

### Reproduction repository

https://github.com/danilokorber/ng12

### Describe your issue

I want to use a custom path for my tailwind.config.js file with Angular 12 in postcss.config.js:

```
module.exports = {
  plugins: {
    tailwindcss: { config: "./config/tailwind.config.js" },
    autoprefixer: {},
  },
};
```

When I run `ng server` no error occurs, but tailwind is not loaded. Then I stop the dev server, move tailwind.config.js out of /config to the root folde, run `ng serve` again and tailwind starts working.

**Comment by itisparas** [comment]
Hey could not find the reproduction repository. Can you make sure the repo you mentioned is public?

**Comment by danilokorber** [comment]
> Hey could not find the reproduction repository. Can you make sure the repo you mentioned is public?

Sorry about that. It's public now.

**Comment by bradlc** [comment]
Hey @danilokorber. It looks like your `postcss.config.js` file is not being read at all. You can see this yourself by introducing a syntax error and verifying that your build still works. It seems like _something_ is enabling Tailwind when it sees a `tailwind.config.js` file in the project root. I am not familiar with Angular so I don't know what that could be. Can you think of anything that might be doing that?

**Comment by danilokorber** [comment]
You're right, @bradlc . Apparently Angular 12 supports Tailwind without the need of postcss. Question is then how to change the default path for the ```tailwind.config.js``` file....

**Comment by bradlc** [comment]
@danilokorber It looks like it needs to be in the "project or workspace root": https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/webpack/configs/styles.ts#L125-L135
