### ISSUE TITLE
[Bug]: Adding new utilites with Vue3 + Vite

### ISSUE THREAD

**Issue by LouisMazel** [tailwindlabs/tailwindcss#4378]
### What version of Tailwind CSS are you using?

2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

Vue.JS 3.0.11

### What version of Node.js are you using?

14

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### Reproduction repository

https://codesandbox.io/s/vue3-vite-typescript-tailwindcss-o5ks0?file=/src/App.vue

### Describe your issue

Hi,

Adding some new utilities classes not working with Vue 3 + Vite (+ Typescript) 

Reproduction link: [codesandbox](https://codesandbox.io/s/vue3-vite-typescript-tailwindcss-o5ks0?file=/src/App.vue)

Like the [documentation](https://tailwindcss.com/docs/adding-new-utilities) say, in my `tailwind.css` : 

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer utilities {
  .bg-overlay {
    background-color: red;
  }
}
```

In `App.vue`:

```html

<style lang="postcss">
  #app {
    @apply bg-overlay;
  }
</style>
```

The error returns by Vite in the terminal (available from the codesandbox.io):

```bash
The `bg-overlay` class does not exist. If you're sure that `bg-overlay`
 exists, make sure that any `@import` statements are being properly processed before Tai
lwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.
```

Thanks for your help

**Comment by ShookLyngs** [comment]
In my case, if I don't edit `dev` script in `package.json` to this: `"dev": "cross-env NODE_ENV=development vite --host"`, then changes in class attribute won't update anyway.

**Comment by adamwathan** [comment]
Hey! This is unfortunately expected due to the way bundlers process CSS — Vite processes every CSS block independently so they can't "see" other blocks of CSS. When Vite processes the CSS in `App.vue`, it has no idea that the `bg-overlay` class exists because it's in `tailwind.css` and Vite is processing those two blocks of CSS in total isolation.

In your case you have two options:

1. Move that class to a Tailwind plugin — if it's a plugin Tailwind will always know about it and it will work in Vue style blocks.
2. Use the JIT engine — it converts `@layer` blocks into plugins automatically which should fix this as well.

Hope that helps!

**Comment by Jak3b0** [comment]
Hi @adamwathan ,

I have the same issue but I am using JIT. Is there anything special I need to set in my config file to make it work? Here is my config file excluding the theme part...

```
module.exports = {
  mode: 'jit',
  purge: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  darkMode: 'class', // or 'media' or 'class',
  ...
}
``` 

Thanks!

**Comment by mjcadz** [comment]
@Jak3b0 did you find an answer?

**Comment by Jak3b0** [comment]
@mjcadz No...  I am currently using plugins for this. It's working great but you loose syntax coloring and no code completion (in the plugin) :(

**Comment by madebyfabian** [comment]
Hi @adamwathan, I am also currently using the JIT engine with vite + vue3 and it's also not working when using `@layer`. Are we missing something to configure? Would be very helpful to have an answer here! Thanks in advance.
