### ISSUE TITLE
Does the tailwindcss package need to include jit/tests/ folder?

### ISSUE THREAD

**Issue by alexander-doroshko** [tailwindlabs/tailwindcss#4393]
### What version of Tailwind CSS are you using?

2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

n/a

### What version of Node.js are you using?

14.17.0

### What browser are you using?

n/a

### What operating system are you using?

Windows

### Reproduction repository

n/a

### Describe your issue

Hi from JetBrains. Our IDEs index `tailwindcss` package files, including the ones from the `jit/tests/` folder. As a result, CSS classes used in `*.css` test data files may appear in code completion.

We can fix this on our end. I just wanted to ask whether you are going not to include this test data folder in the `tailwindcss` release, so that we don't need to hardcode technology-specific exclusions.

**Comment by adamwathan** [comment]
Hey! Nah definitely doesn't need to be included, oversight on my part. The next release won't contain those files 👍🏻

**Comment by adamwathan** [comment]
I would recommend playing with our canary release of 2.2 if you are making changes to how Tailwind support works in JetBrains IDEs too:

`npm install tailwindcss@canary`

We're doing a bunch of internal refactoring lately and I expect the support in JetBrains products _probably_ relies on some internals? If it would be helpful I'd be happy to work more closely with your team on some of this stuff going forward and make sure we don't put out new releases that break JetBrains support before you have a chance to make any necessary changes for stuff that depends on internals. Shoot me an email if you like at adam@hey.com and we can figure out a way to stay in better communication, super grateful for the work your team has done to add awesome Tailwind support to JetBrains products 🙏

**Comment by alexander-doroshko** [comment]
Wonderful, I'll write to you in a minute!

**Comment by adamwathan** [comment]
Going to close since these files will be gone in the next release 👍🏻

**Comment by engpakravan** [comment]
thanks @adamwathan 
but still it's not working in version ^3.0.23 ...
 i use below instead...
```    "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.2.16" ```
