### ISSUE TITLE
[Bug]: JIT doesn't work as expected with multiple entry points importing CSS in Webpack

### ISSUE THREAD

**Issue by leobauza** [tailwindlabs/tailwindcss#4400]
### What version of Tailwind CSS are you using?

v2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

Webpack 5.27.2

### What version of Node.js are you using?

14.16.0

### What browser are you using?

all

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/leobauza/tw-jit-bug

## The Problem:

When there are multiple entry points that import css in Webpack, JIT does not behave as expected.

## Context:

I ran into this problem trying to set up a Craft CMS site where we have a need for multiple entry points, each with their own CSS. After a lot of trial and error we noticed that whenever we have multiple entry points JIT seems to not update the css file until we hit save on a `.css` file. That's a ok workaround, but I am wondering if I am doing something wrong or if this is a bug in Tailwind JIT.

Removing JIT also works, but I like the JIT experience too much so saving a `.css` file is my workaround.

## To reproduce the problem in the reproduction repository:

1. Start dev server with `yarn start`
2. Open `tailwind.config.js`
3. Change the value of `spacing[150]`
4. There will be no change until the `src/css/styles.css` file is saved
5. Open `./src/js/second.js`
6. Comment out the line: `import '../css/second.css'`
7. Doing step 2 and 3 results in a normal HMR update

Thanks! Love the JIT improvements!

## A video of all of the above in action:

https://user-images.githubusercontent.com/1823027/118910693-ee078a00-b8f2-11eb-834e-447d1c1ac0cf.mov

**Comment by bbelcherocv** [comment]
Same here as well, not sure how to actually fix this
