### ISSUE TITLE
[Bug]: Using Array.flatMap instead of lodash.flatMap caused the project to fail to start, and it ran after the replacement under Nodejs v11

### ISSUE THREAD

**Issue by xlzy520** [tailwindlabs/tailwindcss#4402]
### What version of Tailwind CSS are you using?

2.0.4

### What build tool (or framework if it abstracts the build tool) are you using?

"postcss": "^8.2.9",

### What version of Node.js are you using?

9

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### Reproduction repository

https://github.com/xlzy520/uniapp-tailwind-uview-starter

### Describe your issue

![image](https://user-images.githubusercontent.com/28336270/118964072-b1db3480-b999-11eb-9708-dcb97ea8cf42.png)

it is work if I use lodash.flatmap

![image](https://user-images.githubusercontent.com/28336270/118964172-cdded600-b999-11eb-967e-4ddc0d232f7e.png)

**Comment by xlzy520** [comment]
_Lodash.default.flatMap is used in other parts of the library, not here

**Comment by xlzy520** [comment]
![image](https://user-images.githubusercontent.com/28336270/118965194-fa472200-b99a-11eb-852f-2c8539acf98e.png)

**Comment by xlzy520** [comment]
https://github.com/tailwindlabs/tailwindcss/blob/93cfe978472800dd5fc9d09f1f0bb2f0643ab017/src/util/flattenColorPalette.js#L4

**Comment by xlzy520** [comment]
https://github.com/tailwindlabs/tailwindcss/blob/93cfe978472800dd5fc9d09f1f0bb2f0643ab017/src/util/parseObjectStyles.js#L11

**Comment by xlzy520** [comment]
If it is confirmed to be a bug, can I submit a PR？

**Comment by adamwathan** [comment]
Hey! Tailwind v2.0+ doesn't support Node 11, we only support Node 12+ which includes a native flatMap.

https://github.com/tailwindlabs/tailwindcss/blob/master/package.json#L123
https://node.green/#ES2019-features-Array-prototype--flat--flatMap-

**Comment by xlzy520** [comment]
How should I use the babel plug-in to solve this problem during development, after all, I am only affected by this line of code

**Comment by adamwathan** [comment]
Hey! You should update to a newer version of Node. Node 11 is not maintained or supported by the Node team.

https://nodejs.org/en/about/releases/
