### ISSUE TITLE
after installing tailwind in vue 3 + vite + typescript the initial project load is extremely slow[Bug]: 

### ISSUE THREAD

**Issue by eRendon** [tailwindlabs/tailwindcss#4405]
### What version of Tailwind CSS are you using?

v^2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

postcss: ^8.2.15  and vite: ^2.2.3,

### What version of Node.js are you using?

v15.0.0

### What browser are you using?

Brave

### What operating system are you using?

Windows 10

### Reproduction repository

https://github.com/eRendon/vite-vue3-tailwind

### Describe your issue

I instaled tailwind to vue 3, but after `import './assets/styles/index.css';` to file main.ts,  the proyecto load is very slow and the inspection of code in borwser it freezes.

I activated de `mode: jit` but this not inyect the files of tailwind styles.

Thanks!

**Comment by adamwathan** [comment]
Hey! Yeah this is the exact problem the JIT engine is meant to solve 👍🏻 The reason it didn't work for you is that you are not on the latest version of Tailwind.

Run this, then add `mode: 'jit'` to your `tailwind.config.js` file:

`npm install -D tailwindcss@latest`

You were pinned to Tailwind v2.0.4 which didn't include the JIT mode yet.

I've made these changes to a local copy of your project and confirmed it works as expected 🥳

**Comment by eRendon** [comment]
I update to 2.1.12 version of tailwind, but this not recognize the css properties.

![image](https://user-images.githubusercontent.com/36104986/119394390-bb191980-bc97-11eb-9878-15225d127223.png)

in other proyect, this is the problem

![image](https://user-images.githubusercontent.com/36104986/119394575-f1ef2f80-bc97-11eb-9f1e-dfdb00bcb748.png)

![image](https://user-images.githubusercontent.com/36104986/119394610-fe738800-bc97-11eb-88e9-c301e6a398bb.png)

![image](https://user-images.githubusercontent.com/36104986/119394641-07645980-bc98-11eb-850c-11237f751bcf.png)

in styles of inspection browser, not see the properties `bg-gray-400 ring-offset-black ring-black border-transparent ring-offset-0 ring-1`

this happens when activate the mode jit in the version 2.1.12

Thanks for your answer.

**Comment by adamwathan** [comment]
Hey! Please open a new issue with a proper reproduction or I can't help I'm afraid.

Here is a demo using JIT mode with the same classes that works as expected:

https://play.tailwindcss.com/Gxhf1f8yHd

**Comment by zhouJiecode** [comment]
对于无法升级到最新版本tailwind的可以通过webpack插件解决这个问题：
https://juejin.cn/post/6956424977184718856
