### ISSUE TITLE
[Bug]: JIT compiler is not working in Ubuntu 20.04 

### ISSUE THREAD

**Issue by BlueZ-95** [tailwindlabs/tailwindcss#4414]
### What version of Tailwind CSS are you using?

v2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js 10.2.0

### What version of Node.js are you using?

v14.17.0

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### Reproduction repository

https://github.com/BlueZ-95/team-calendar

### Describe your issue

The project runs perfectly in Windows while JIT is enabled, but When I run the project in Ubuntu 20.04 JIT mode is not working and prevents any styling in the project.

**Comment by cloudagon** [comment]
Is it because your Components folder is capitalized but you specified the lowercase one (components) for purging?

**Comment by BlueZ-95** [comment]
It works.... Thank you very much

**Comment by jagdishmehra123** [comment]
> Is it because your Components folder is capitalized but you specified the lowercase one (components) for purging? This might make sense because Windows is case insensitive while Linux is case sensitive.
> 
> I cloned your repo and tested on Ubuntu 20.04, can confirm that the JIT mode works (and the page loads much faster!) after lowercasing the `Components` folder name to `components`.

Thank you so much, you saved my life because i have to fix this within 5 mins and i felt like we needed to do some configuration for ubuntu. But i was wrong.
