### ISSUE TITLE
[Bug]: JIT: Compiling multiple files concurrently

### ISSUE THREAD

**Issue by kaleidografik** [tailwindlabs/tailwindcss#4416]
### What version of Tailwind CSS are you using?

2.1.1

### What build tool (or framework if it abstracts the build tool) are you using?

postcss-cli 8.3.1

### What version of Node.js are you using?

12.0.0

### What browser are you using?

N/A

### What operating system are you using?

macOS

### Reproduction repository

n/a

### Describe your issue

Hi all. Using the new JIT mode, is it possible to 'watch' multiple style files concurently? I need to continually process multiple stylesheets, but the 'dev' script below only continues to watch the second file. I'ma ssuming it's to do with the long-running watch process, but is there any way to watch both indefinately?

Thanks!

```
"scripts": {
    "style": "postcss src/styles/style.scss -o style.css -w",
    "style-editor": "postcss src/styles/style-editor.scss -o style-editor.css -w",
    "dev": "NODE_ENV=development npm run style & NODE_ENV=development npm run style-editor",
    "build": "NODE_ENV=production npm run style & NODE_ENV=production npm run style-editor"
  },
```

**Comment by bradlc** [comment]
Hey @kaleidografik. I'm not sure why your example with `&` doesn't work as I'm not too familiar with bash. But I can recommend using [npm-run-all](https://www.npmjs.com/package/npm-run-all) or [concurrently](https://www.npmjs.com/package/concurrently) to run multiple npm scripts in parallel in a cross-platform way:

```bash
# npm-run-all
npm-run-all --parallel style style-editor

# concurrently
concurrently "npm:style" "npm:style-editor"
```

I have verified that this works fine with postcss-cli 👍

**Comment by kaleidografik** [comment]
Thank you @bradlc - npm-run-all works like a charm.
