### ISSUE TITLE
[Bug]: className does not work （next.js）

### ISSUE THREAD

**Issue by MoonCheung** [tailwindlabs/tailwindcss#4436]
### What version of Tailwind CSS are you using?

v2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js 10.2.0

### What version of Node.js are you using?

v12.22.1

### What browser are you using?

Chrome, Safari

### What operating system are you using?

macOS

### Reproduction repository

className does not work （next.js）

### Describe your issue

className fails to work in my project. I tried `rm -rf ./next/cache`, but it is still not solved. Please help me solve it

![image](https://user-images.githubusercontent.com/19801190/119244460-8fb50280-bba3-11eb-85cf-5c99effc684b.png)
Please look at the `tailwind.config.js`
```javascript
const colors = require('tailwindcss/colors');
const tailwindForms = require('@tailwindcss/forms');
const plugin = require('tailwindcss/plugin');

module.exports = {
  mode: 'jit',
  purge: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'media', // or 'media' or 'class'
  theme: {
    colors: {
      primary: '#03a9f4',
      gray: colors.blueGray,
      blue: colors.lightBlue,
      red: colors.rose,
      green: colors.lime,
      yellow: colors.amber
    },
    fontFamily: {
      sans: [
        'BlinkMacSystemFont',
        '-apple-system',
        '"Segoe UI"',
        '"Roboto"',
        '"Oxygen"',
        '"Ubuntu"',
        '"Cantarell"',
        '"Fira Sans"',
        '"Droid Sans"',
        '"Helvetica Neue"',
        '"Helvetica"',
        '"Arial"',
        'sans-serif'
      ]
    },
    extend: {}
  },
  variants: {
    extend: {}
  },
  plugins: [tailwindForms]
};
```
Please look at the `index.scss`
```css
@charset "UTF-8";
// tailwindcss style
@import 'tailwindcss/base';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';
// base style
@import './base.scss';
```

**Comment by amantiwari1** [comment]
I think it is working fine because it shows you put the wrong CSS which caused to wrong style nav

**Comment by MoonCheung** [comment]
> I think it is working fine because it shows you put the wrong CSS which caused to wrong style nav

This makes me write painfully, is there a better way to do it than this? What's the problem with positioning?

**Comment by amantiwari1** [comment]
try to add `flex` and remove `right-0` in `nav`

**Comment by MoonCheung** [comment]
> try to add `flex` and remove `right-0` in `nav`

While Flex works, fixed CSS doesn't work, which makes me write in pain

**Comment by amantiwari1** [comment]
What exactly do you want? 
Or 
Learn about fixed in css

**Comment by MoonCheung** [comment]
> What exactly do you want?
> Or
> Learn about fixed in css

`tailwind.config.js` is temporarily used with `mode: 'jit'` annotation, including `postcss.config.js`. That's the reason. It's been solved
![image](https://user-images.githubusercontent.com/19801190/119264366-7351ae00-bc15-11eb-92dd-cb9d1da6df72.png)

**Comment by MoonCheung** [comment]
I'm sorry, I misread it，not a problem with  `mode:'jit'`，Instead, the directory path of the file was not introduced in the `pure` option
