### ISSUE TITLE
[Bug]: Tailwind classes does not workl

### ISSUE THREAD

**Issue by soaresmilton** [tailwindlabs/tailwindcss#4449]
### What version of Tailwind CSS are you using?

2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

NEXT JS 10.2.2

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### Reproduction repository

https://github.com/soaresmilton/huluclone

### Describe your issue

Adding tailwind classes to my "HeaderItem.js" component has no effect

**Comment by bradlc** [comment]
Hey @soaresmilton. Your `purge` paths are incorrect. They should be `./src/pages/**/*.{js,ts,jsx,tsx}` and `./src/components/**/*.{js,ts,jsx,tsx}`

**Comment by soaresmilton** [comment]
Hey @bradlc thanks for answering. But, the purge path, I copy from tailwind Next getting start https://tailwindcss.com/docs/guides/nextjs

🤔

**Comment by bradlc** [comment]
The `purge` config defines the files where Tailwind classes are used. By default Next.js creates a `pages` directory at the project root, so the `purge` paths in the documentation are correct. Your React components are in `./src/pages` and `./src/components` though, so the `purge` config needs updating to reflect this 👍

**Comment by soaresmilton** [comment]
Awesome @bradlc . Thanks a lot!
