### ISSUE TITLE
Grid utility class not applying properly at different breakpoints in NextJS project's production build (Vercel deploy)

### ISSUE THREAD

**Issue by Eikix** [tailwindlabs/tailwindcss#4459]
### What version of Tailwind CSS are you using?

v2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js 10.2.2

### What version of Node.js are you using?

v14.15.3

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/Eikix/micheltazartes

### Describe your issue

Hi all,

I encountered a weird bug after I deployed my website through Vercel's deployment platform: the grid utility class is no longer functioning.

To be clear, in localhost:3000, my app renders properly the grid layout and adapts to breakpoints (md:grid-cols-3, lg:grid-cols4, etc.). Nevertheless, when I deploy the app on vercel.app domain, it no longer works. Every other utility class seems to be working except this one (NB: I've noticed that the Navbar is also slightly pushed to the left for no reason in production).

Summarised: TailwindCSS Grid layout and different breakpoints on grid column numbers does not work properly in production but works fine in localhost runs.

Utility classes that do not work in production: grid grid-cols-1 md:grid-cols-3 md:gap-6 lg: grid-cols-4, etc.

![image](https://user-images.githubusercontent.com/66871571/119527665-d449c500-bd80-11eb-8754-9e948e4fa8d3.png)
![image](https://user-images.githubusercontent.com/66871571/119527805-f8a5a180-bd80-11eb-86ee-829dfa03774f.png)

Thank you for your help ! Have a good one.

**Comment by adamwathan** [comment]
Hey! I think this might have something to do with a caching issue in your Vercel deployments or something, because I forked your site and deployed it myself and the grid classes are working:

https://micheltazartes-ten.vercel.app/services

Can you try redeploying with a clear cache?

**Comment by Eikix** [comment]
Hey Adam, thanks a lot for your fast reply, how does one deploy the same website with a clear cache?

**Comment by adamwathan** [comment]
Hey! Just go to the deployments page and click the button on the right, and choose redeploy. Make sure you leave "include build cache" unchecked:

https://user-images.githubusercontent.com/4323180/119532922-5622f980-bd53-11eb-9cb8-692902966e69.mov

**Comment by Eikix** [comment]
It works!!! Thank you so much for your help:). Have a great one
