### ISSUE TITLE
Safari browser doesn't apply object-cover on images

### ISSUE THREAD

**Issue by ibrent** [tailwindlabs/tailwindcss#4462]
### What version of Tailwind CSS are you using?

2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

Gatsby

### What version of Node.js are you using?

16.1.0

### What browser are you using?

Safari

### What operating system are you using?

mac OS

### Reproduction repository

https://tailwindcss.com/docs/responsive-design

### Describe your issue

In your responsive documentation, you show and give code that displays an image using object-cover and the wrapping div with rounded corners.  The image cover only works on Chrome, not Safari.  See screenshots of both browsers.   Paste your own code and test in both browsers.
https://tailwindcss.com/docs/responsive-design

<img width="742" alt="mac-safari" src="https://user-images.githubusercontent.com/351251/119565449-cdaa5600-bd5e-11eb-9cb7-97fce5c9636a.png">

<img width="735" alt="mac-chrome" src="https://user-images.githubusercontent.com/351251/119565467-d3a03700-bd5e-11eb-8e62-3afa830c1def.png">

**Comment by jacobthesheep** [comment]
I am using Safari and it shows rounded corners.

**Comment by ibrent** [comment]
Urughhh, I think this has something to do with using a very simple static image using gatsby-plugin-image.  It's really difficult to reproduce due to the stack.  urughh.

**Comment by ibrent** [comment]
OK tailwind works fine with direct images or linked from unsplash etc.  But going through the gatsby-plugin-image is just a mess.  Really inconsistent behavior.  I'm not sure what is exactly happening.  Maybe gatsby is removing a css class or something, but the rendered code looks the same.  This is unfun to mess with.

**Comment by ibrent** [comment]
Followup:  Tailwind works fine.  If using React/Gatsby.js + Tailwind.css, the gatsby-plugin-image doesn't work correctly with the rounded corners for some reason on Safari.  I fixed this by putting the images into a static folder and referencing them directly in the HTML using an IMG tag, not the Gatsby Static Image tag.

**Comment by mrv1k** [comment]
I know it's a solved issue but it appears first on Google.
Static folder is not a good solution. Proper solution is to apply `rounded` class to the image directly instead of a wrapper.

Use: `StaticImage imgClassName="rounded"  .../>`
instead of: `StaticImage className="rounded"  .../>`

**Comment by ibrent** [comment]
I tried this again with the same result.  The HTML shows the class, but the browser never applies it - or something.  Gatsby.js StaticImage is doing something here.  This is not solved for me.  I still see it in both Safari and Chrome using latest Tailwind and Gatsby.

**Does anyone have a sample of it working that I can see in the wild?**  I see the 'rounded' class in the code, but the image definitely has no rounding in the browser.  I CAN get it to apply using a static image that doesn't use Gatsby's StaticImage.

My tag:
`     <StaticImage
        imgClassName="rounded"
        src="../images/clear-old-installer.jpg"
        width={300}
        quality={95}
        alt="clear installer"
      />`

Output from browser HTML inspection:
(wrapped in a PICTURE tag which won't render in this code window)
`<source type="image/webp" srcset="/static/e011d18b99f31d3b464df51e3d00cb07/19084/clear-old-installer.webp 75w,
/static/e011d18b99f31d3b464df51e3d00cb07/bb989/clear-old-installer.webp 150w,
/static/e011d18b99f31d3b464df51e3d00cb07/7ffa1/clear-old-installer.webp 300w,
/static/e011d18b99f31d3b464df51e3d00cb07/a9664/clear-old-installer.webp 600w" sizes="(min-width: 300px) 300px, 100vw">
<img width="300" height="191" class="rounded" data-main-image="" sizes="(min-width: 300px) 300px, 100vw" decoding="async" loading="lazy" alt="clear installer" src="/static/e011d18b99f31d3b464df51e3d00cb07/736c6/clear-old-installer.jpg" srcset="/static/e011d18b99f31d3b464df51e3d00cb07/2aecc/clear-old-installer.jpg 75w,
/static/e011d18b99f31d3b464df51e3d00cb07/7d824/clear-old-installer.jpg 150w,
/static/e011d18b99f31d3b464df51e3d00cb07/736c6/clear-old-installer.jpg 300w,
/static/e011d18b99f31d3b464df51e3d00cb07/e023b/clear-old-installer.jpg 600w" style="object-fit: cover; opacity: 1;">
`

The result is no rounded corners ONLY when using Gatsby's StaticImage.

**Comment by ibrent** [comment]
The code that I posted above does not work for me.  I cannot get the 'rounded' class to work when using Gatsby.js and their StaticImage tag.  I see it in the HTML on inspect, but in both Chrome and Safari, there are no rounded corners.  I can get it to work using images in my static folder, that are not processed through Gatsby.  

So I know it's not Tailwind.  I must have something wrong with my config somewhere.  I get no errors.

I'm going to create a new project from scratch, very minimal, and see what happens.   I'll use the code sample you sent me @mrv1k and see what I can reproduce.  Thanks for your help.  I send you virtual drinks of choice 🍻.

**Comment by mrv1k** [comment]
Thanks for the virtual drink 😄 Minimal reproducible is a great idea.

You asked for a sample. I guess I can use myself as example, rather literally...
Picture of me on the right https://mrv1k.me/about is rounded for me in Chrome, Firefox, Safari, Safari Mobile
Source code for it https://github.com/mrv1k/garage/blob/master/car/src/pages/about.tsx#L38-L46
`image-of-me` & `aside` are empty classes. I just forgot to remove them

Maybe you have some CSS that's overriding tailwind?
