### ISSUE TITLE
Negative margin does not allow arbitrary values

### ISSUE THREAD

**Issue by 2ne** [tailwindlabs/tailwindcss#4467]
### What version of Tailwind CSS are you using?

v2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

Tailwind Play

### What version of Node.js are you using?

-

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://play.tailwindcss.com/fbselPAgJp

### Describe your issue

Negative margins do not support arbitrary values but normal margins do.

**Comment by bradlc** [comment]
Hey @2ne. This is by design, and negative arbitrary values can be used like this: `mt-[-5rem]` 👍
