### ISSUE TITLE
adding "hidden sm:block" cause wrap child items, removing them child items are aligned ok 

### ISSUE THREAD

**Issue by eriknyk** [tailwindlabs/tailwindcss#4476]
### What version of Tailwind CSS are you using?

2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

sandbox

### What version of Node.js are you using?

15

### What browser are you using?

chrome

### What operating system are you using?

macos

### Reproduction repository

https://play.tailwindcss.com/hMdqaefh4d

### Describe your issue

Adding "hidden sm:block" cause wrap child items, removing them child items are aligned ok 

![image](https://user-images.githubusercontent.com/205721/119681478-ba06fa00-be07-11eb-8a49-f5ca00ed9a09.png)

technically I want green item hidden only in mobile devices but I got this weird behavior

you can see in the sandbox:
https://play.tailwindcss.com/hMdqaefh4d

**Comment by bradlc** [comment]
Hey @eriknyk, it should be `sm:flex` instead of `sm:block`: https://play.tailwindcss.com/2nPrhvHVU0

**Comment by eriknyk** [comment]
Thank @bradlc, yeap technically it works but conceptually it can be a little bit confused.

Regards.
