### ISSUE TITLE
Updates to the tailwind.config.js aren't being reflected until after restarting Angular 11 app (JIT)

### ISSUE THREAD

**Issue by Jacob-Mahoney** [tailwindlabs/tailwindcss#4493]
### What version of Tailwind CSS are you using?

2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

postcss 8.2.15

### What version of Node.js are you using?

14.15.4

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/Jacob-Mahoney/tailwind-test

### Describe your issue

`ng new tailwind-test`
`cd tailwind-test`
`npm i --legacy-peer-deps` (because I'm using npm 7.13.0)
`ng add ngx-tailwind`
`npm i --legacy-peer-deps`
`ng serve`

As you can see from the repository, I have created a single configured width (for example) in the `tailwind.config.js` file. After my Angular project is up and serving locally, and then after modifying the config file, the page refreshes but it doesn't reflect my changes. My changes to the `tailwind.config.js` file only seem to be realized when I completely restart my Angular app.

I imagine, I'm just forgetting something... any ideas?

**Comment by bradlc** [comment]
Hey @Jacob-Mahoney. The JIT engine has two modes, "watch" and "build". Watch mode is enabled by default if the `NODE_ENV` environment variable is set to `development`, but in your project that doesn't seem to be the case. You can explicitly enable watch mode by setting the `TAILWIND_MODE` environment variable. For example if you change your `start` script to `TAILWIND_MODE=watch ng serve` the issue is resolved 👍 

Relevant documentation: https://tailwindcss.com/docs/just-in-time-mode#watch-mode-and-one-off-builds

**Comment by Jacob-Mahoney** [comment]
```
H:\Projects\Development\Websites\tailwind-test>npm run start

tailwind-test@0.0.0 start
TAILWIND_MODE=watch ng serve

'TAILWIND_MODE' is not recognized as an internal or external command,
operable program or batch file.
```

I get the above error when trying that @bradlc

**Comment by bradlc** [comment]
Sorry I missed that you are on Windows. I think it would be `set TAILWIND_MODE=watch && ng serve`? Alternatively you can use [`cross-env`](https://npm.im/cross-env) which is cross-platform: `cross-env TAILWIND_MODE=watch ng serve`

**Comment by Jacob-Mahoney** [comment]
I tried changing my `start` script to both `set TAILWIND_MODE=watch && ng serve` and `cross-env TAILWIND_MODE=watch ng serve`, and both didn't work. After my project was up and running, I tried changing that configured `width` value in my `tailwind.config.js` file, and it looks like it recompiled and the webpage refreshed, but it didn't take the updated value.

**Comment by bradlc** [comment]
Hey @Jacob-Mahoney. I can reproduce the issue when updating the config file, but it looks like this is resolved in the latest `canary` release 👍 You can install this with `npm install tailwindcss@canary`
