### ISSUE TITLE
Filter on parent div, with nested fixed child not breaking out

### ISSUE THREAD

**Issue by merijnponzo** [tailwindlabs/tailwindcss#4501]
### What version of Tailwind CSS are you using?

2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

8.3.0

### What version of Node.js are you using?

v14.15.3

### What browser are you using?

firefox * chrome

### What operating system are you using?

macOs

### Reproduction repository

https://github.com/merijnponzo/tailwind-boilerplate-master

### Describe your issue

When i use the filter option within a parent div, and nest a fixed child div the fixed child isn't breaking out it's parent.

I know this can happen with transform or filter properties on parent elements. 
My workaround is to create a before element with the filter, and the shadow on it's parent element, i guess.

https://stackoverflow.com/questions/52937708/why-does-applying-a-css-filter-on-the-parent-break-the-child-positioning

A regular case is when I create a desktop parent toolbar with shadow, with a submenu fixed in the bottom for mobile.

**Comment by merijnponzo** [comment]
I can use 'shadow-lg' as well ;-)

**Comment by adamwathan** [comment]
Hey! Like you've discovered this is just a behavior of CSS and not something that is possible for us to change with Tailwind. Tailwind is really just an API for CSS, so all the regular rules of CSS apply with Tailwind classes as well.

**Comment by merijnponzo** [comment]
True story, my guess is that how the filter property affects the position property can be easily missed while frontending with the lightspeed of tailwind.

Maybe a simple dialog within the documentation on filters is enough

<img width="957" alt="Screenshot 2021-05-31 at 14 46 56" src="https://user-images.githubusercontent.com/23075300/120195848-7ce3a300-c21f-11eb-9285-bfb41e50c2c1.png">

Thanks!
