### ISSUE TITLE
JIT Mode

### ISSUE THREAD

**Issue by CanKolay5677** [tailwindlabs/tailwindcss#4517]
### What version of Tailwind CSS are you using?

v2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js 10.2.3

### What version of Node.js are you using?

v14.15.4

### What browser are you using?

Brave nightly

### What operating system are you using?

Linux (termux)

### Reproduction repository

.

### Describe your issue

JIT Mode not works on react with classnames.

When I use classnames, the classes I write in the cn() function are not processed.

**Comment by adamwathan** [comment]
Hey! Sorry but please open a new issue with a reproduction, this definitely does work when configured correctly.
