### ISSUE TITLE
Issue with flex and breakpoints

### ISSUE THREAD

**Issue by deshiloh** [tailwindlabs/tailwindcss#4527]
### What version of Tailwind CSS are you using?

2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

postcss, laravel-mix (all latest)

### What version of Node.js are you using?

16.2.0

### What browser are you using?

Firefox, Chrome, Safari 

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/deshiloh/cliniquedusouffle

### Describe your issue

On the header, I put flex-col and md:flex-row 
```
<header class="container flex flex-col md:flex-row">
```
Flex stay stuck with flex-col. 
I saw in the inspector that the rule md:flex-row is overwride with flex-col. 
i don't think that's normal, maybe i'm doing anything wrong. 

Thanks for the help. 
Kinds regards.

**Comment by adamwathan** [comment]
Hey! Issue is in [this file](https://github.com/deshiloh/cliniquedusouffle/blob/master/assets/css/app.css#L3), you are explicitly rendering the `screens` CSS _before_ `utilities`. Make sure you put the screen after:

```diff
  @tailwind base;
  @tailwind components;
- @tailwind screens;
  @tailwind utilities;
+ @tailwind screens;
  
  .container {
    @apply px-3;
    @screen md {
      @apply px-0;
    }
  }
```
