### ISSUE TITLE
Plugins styles dont load if JIT mode are enabled

### ISSUE THREAD

**Issue by josuesan** [tailwindlabs/tailwindcss#4544]
### What version of Tailwind CSS are you using?

npm:@tailwindcss/postcss7-compat@2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

postcss 7.0.35 nextjs 9.4.4

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Chrome, Opera

### What operating system are you using?

Windows

### Reproduction repository

The repository is private

### Describe your issue

When enable the jit mode, the css of custom plugins dont load.

**Comment by adamwathan** [comment]
Hey! Please open a new issue and include a reproduction repository, we don't need your actual private one, what we really want is just a minimal reproduction that doesn't have any extra noise or anything. Unfortunately impossible to help without a reproduction 🙏
