### ISSUE TITLE
list-inside does not handle "hanging indent" (list-outside does) - simply view your doc page with narrow window

### ISSUE THREAD

**Issue by jpwynn** [tailwindlabs/tailwindcss#4549]
### What version of Tailwind CSS are you using?

2.0.4

### What build tool (or framework if it abstracts the build tool) are you using?

play.tailwindcss.com

### What version of Node.js are you using?

play.tailwindcss.com

### What browser are you using?

Chrome90 and firefox 88

### What operating system are you using?

mac catalina

### Reproduction repository

https://play.tailwindcss.com/lDSLiFbftS

### Describe your issue

Repo not needed, your online "play.tailwindcss.com" illustrates bug perfectly as does your own doc page (see below)

`list-inside` does NOT handle "hanging indent" at all; `list-outside` is OK.

Reproduce bug example #1 - TW playground:
https://play.tailwindcss.com/lDSLiFbftS

Reproduce bug example #2 - simply view your doc page

Your "samples" for list style position fail to include any samples "long enough to wrap" which is probably how this bug escaped detection so long.

But if you view your doc page https://tailwindcss.com/docs/list-style-position with the browser window narrow enough for the sample text to wrap, you can reproduce the bug there:

![List_Style_Position_-_Tailwind_CSS](https://user-images.githubusercontent.com/446451/120558669-85f97f00-c39b-11eb-934f-ce95b995d350.jpg)

**Comment by adamwathan** [comment]
Hey! This isn't a bug actually, that's just how the CSS `list-style-position: inside` feature works.

Here's a demo using vanilla CSS with no Tailwind at all:

https://jsfiddle.net/uLyq7jmt/

Check out the MDN documentation on this property to learn more: https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-position
