### ISSUE TITLE
Jit is not working with next js with jsconfig.json

### ISSUE THREAD

**Issue by SahasSaurav** [tailwindlabs/tailwindcss#4562]
### What version of Tailwind CSS are you using?

2.1.4

### What build tool (or framework if it abstracts the build tool) are you using?

Next js

### What version of Node.js are you using?

14.16.0

### What browser are you using?

crome

### What operating system are you using?

window 10 

### Reproduction repository

https://github.com/SahasSaurav/jit-jsonconfig.json

### Describe your issue

When turning  on jit mode with jsconfig.json file no tailwind css  style is applied to Hello component 

```js
import React from 'react'

const Hello = () => {
  return (
    <div className="container mx-auto max-w-screen-xl  text-4xl">
      hello World
    </div>
  )
}

export default Hello
```
###the Screenshoot of component
![Screenshot (161)](https://user-images.githubusercontent.com/60291223/120841815-9a02d380-c589-11eb-9963-e1536d29ca38.png)

**Comment by adamwathan** [comment]
Hey! Can you provide a real reproduction? The link you've provided goes to a private Slack or something.

**Comment by SahasSaurav** [comment]
https://github.com/SahasSaurav/jit-jsonconfig.json

**Comment by adamwathan** [comment]
Hey! Looks like the issue is that your purge paths are configured wrong, you have your stuff in `src` but your purge paths don't include `src`. Update your `tailwind.config.js` file to this:

```diff
  module.exports = {
    mode:'jit',
-   purge: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
+   purge: ['./src/pages/**/*.{js,ts,jsx,tsx}', './src/components/**/*.{js,ts,jsx,tsx}'],
    darkMode: false, // or 'media' or 'class'
    theme: {
      extend: {},
    },
    variants: {
      extend: {},
    },
    plugins: [],
  }
```
