### ISSUE TITLE
Jit mode not working in next.js

### ISSUE THREAD

**Issue by chhpt** [tailwindlabs/tailwindcss#4566]
### What version of Tailwind CSS are you using?

2.1.4

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js 10.2.3

### What version of Node.js are you using?

v14

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/chhpt/tailwind-jit-report

### Describe your issue

In next.js, tailwindcss will not working when enable jit mode

Reproduciton demo: https://stackblitz.com/edit/github-svb2nh

![image](https://user-images.githubusercontent.com/19288423/120897827-aacf4a00-c65a-11eb-9224-ce45dab26e8f.png)

**Comment by adamwathan** [comment]
Hey! Your purge config is incorrect, you are looking directly in `./pages` and `./components` but you've moved those directories under `src` so you need to update those paths:

```diff
  module.exports = {
    darkMode: false,
    mode: 'jit',
-   purge: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
+   purge: ['./src/pages/**/*.{js,ts,jsx,tsx}', './src/components/**/*.{js,ts,jsx,tsx}'],
    theme: {
      extend: {},
    },
    variants: {
      extend: {},
    },
    plugins: [],
  }
```

Tested that change locally and it works as expected 👍
