### ISSUE TITLE
Follow XDG specification on Linux

### ISSUE THREAD

**Issue by lunush** [tailwindlabs/tailwindcss#4569]
### What version of Tailwind CSS are you using?

v2.1.2

### Describe your issue

On Linux, there is [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) that almost all modern software follow. The specification helps declutter the home directory and manage program-specific files more easily.

When using tailwind, it creates a folder `~/.tailwindcss` with what I believe are cache-related files. If I am correct, the files should be located at `~/.cache/tailwindcss`.

**Comment by frankdugan3** [comment]
TLDR: For cache, the spec defines
```
$XDG_CACHE_HOME defines the base directory relative to which user-specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used.
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

There is a probably going to be a time in the future where we don't even need this folder anymore, now that tools are shipping with the latest postcss version that supports better dependency tracking. 

That said, I opened a pr (#4650) that changes the default folder for this. 
Once that PR is merged, this issue will be closed.

Thanks!
