### ISSUE TITLE
--tw-bg-opacity not defined when compiled for production 

### ISSUE THREAD

**Issue by deshiloh** [tailwindlabs/tailwindcss#4579]
### What version of Tailwind CSS are you using?

2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

postcss, laravel-mix (all latest)

### What version of Node.js are you using?

16.2.0

### What browser are you using?

Firefox, Chrome, Safari

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/deshiloh/cliniquedusouffle

### Describe your issue

Hi ! 

On the front page in the slider. Under the title of the slide there is the pagination of the slide generate by Tiny Slider (.slide-nav)
As you can see, the slide pagination is not visisible, looking in the inspector give me that the variable --tw-bg-opacity is not defined. Maybe that's why button are here but not visible. 
It work with `npx mix watch ` and `npx mix ` but doesn't work with `--production`.
Maybe am I doing wrong ? 

Thanks in advance for the help.

**Comment by adamwathan** [comment]
Hey! Can you make the repo public so we can see it? ❤️

**Comment by deshiloh** [comment]
Done !

**Comment by deshiloh** [comment]
https://github.com/deshiloh/cliniquesouffle

**Comment by deshiloh** [comment]
Hi ! anything about my opened issue ?

**Comment by adamwathan** [comment]
Hey! You opened it yesterday, it can take weeks before we get time to look at issues unfortunately.

**Comment by deshiloh** [comment]
Sure ! Apologies

**Comment by adamwathan** [comment]
Alright so this is effectively the same as the bug reported here, and has to do with weird interactions between postcss-nested, `@apply`, and some bugs in postcss-nested:

https://github.com/tailwindlabs/tailwindcss/issues/3964

Tailwind CSS v2.2 is going to make this better by introducing some specific features that improve compatibility with nesting plugins, but in the mean time you can solve your problem by updating your `postcss.config.js` file to this:

```js
const postcss = require('postcss')
const postcssNested = require('postcss-nested')

module.exports = {
  plugins: [
    require('postcss-import'),
    function (root, result) {
      root.walkAtRules('screen', (rule) => {
        rule.name = 'media'
        rule.params = `screen(${rule.params})`
      })

      root.walkAtRules('apply', (rule) => {
        rule.before(postcss.decl({ prop: '__apply', value: rule.params }))
        rule.remove()
      })

      postcss([postcssNested()]).process(root, result.opts).sync()

      root.walkDecls('__apply', (decl) => {
        decl.before(postcss.atRule({ name: 'apply', params: decl.value }))
        decl.remove()
      })

      return root
    },
    require('tailwindcss'),
    require('autoprefixer'),
  ],
}
```

That little inline plugin there does some intermediate transformations to fix the compatibility issues.

Importantly, you will also need to install the latest canary release of Tailwind until v2.2 is actually released:

`npm install -D tailwindcss@canary`

I've opened a pull request to your repo with the necessary changes 👍🏻 

https://github.com/deshiloh/cliniquesouffle/pull/1

**Comment by timmyrosen** [comment]
@adamwathan  I'm having the same issue. I've tried installing the latest canary build (2.2.0-canary.15) and added the postcss-snippet pasted above but the issue remains.

Here is a screenshot of the styles applied in development:
![Skärmavbild 2021-06-14 kl  16 25 19](https://user-images.githubusercontent.com/2311633/121908531-649a7a80-cd2d-11eb-9984-5f6ba9dbde94.png)

And here is the same element in production:
![Skärmavbild 2021-06-14 kl  16 25 39](https://user-images.githubusercontent.com/2311633/121908599-72e89680-cd2d-11eb-8c4a-7e24b8efc28c.png)

The background-color uses hex instead of rgba.

**Comment by adamwathan** [comment]
@timmyrosen Can you open a new issue with a reproduction? This feels like a different issue, possibly a minifier or postcss-preset-env related problem.

**Comment by timmyrosen** [comment]
@adamwathan Ok, after a bit more investigation the issue is solved. I first excluded tailwind from the equation by setting the rgba style manually and that also got converted to hex. So I updated postcss from 8.3.0 to 8.3.4 and that fixed the issue.
