### ISSUE TITLE
TailwindCSS WebKit Group Hover Glitch

### ISSUE THREAD

**Issue by connorstevens** [tailwindlabs/tailwindcss#4594]
### What version of Tailwind CSS are you using?

2.1.4

### What build tool (or framework if it abstracts the build tool) are you using?

PostCSS 8.3.0, NextJS 10.2.3, Autoprefixer 10.2.6

### What version of Node.js are you using?

14.15.5

### What browser are you using?

Chrome, Safari

### What operating system are you using?

macOS, Windows

### Reproduction repository

https://github.com/connorstevens/tailwind-issue

### Describe your issue

I have a custom component that relies on `group-hover` to produce a brighter glow effect when a user hovers. This effect works perfectly on Chrome for Windows and macOS. When viewing the page in Safari, the effect is not achieved. It's rather inconsistent, but one of a few things happens:

- Square corners glow
- Sides glow
- Nothing glows
- The transition doesn't apply

I seem to believe this is a Tailwind/WebKit issue, since I've only successfully reproduced it on Safari, I've tested on at least 5 browsers across macOS and Windows. Any help is appreciated!

I've attached below 3 screenshots, 2 error cases and my expected output (achieved on Win10 Chrome and macOS Chrome)

![Error1](https://user-images.githubusercontent.com/25255502/121298220-8032fa80-c8c1-11eb-9ac3-d6b9a23ac204.png)
![Error2](https://user-images.githubusercontent.com/25255502/121298216-7f01cd80-c8c1-11eb-8f17-1a858c005ccb.png)
![Expected](https://user-images.githubusercontent.com/25255502/121298222-81642780-c8c1-11eb-9410-193be5b8b871.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I'm afraid this is a Safari bug and not a Tailwind bug.

Here is a very drilled down example without Tailwind https://jsfiddle.net/17gajLcq/

If Safari is an important browser to support, one thing you can do is to create multiple images that you can swap on hover so that you don't need a `filter blur` at all.
