### ISSUE TITLE
npm install from repo on Termux ENOENT chmod cli.js

### ISSUE THREAD

**Issue by Leif-W** [tailwindlabs/tailwindcss#4599]
### What version of Tailwind CSS are you using?

GitHub master HEAD

### What build tool (or framework if it abstracts the build tool) are you using?

postcss 8.3.0, next 10.2.3

### What version of Node.js are you using?

14.15.4

### What browser are you using?

Brave

### What operating system are you using?

Android/Linux/Termux

### Reproduction repository

git init; npm init; npm install -D tailwindlabs/tailwindcss

### Describe your issue

It is platform specific, not project related.  The reproduction repo does not apply.  On Android, download F-Droid, install Termux, do NOT use Google Play Termux as it is no longer updated.  Use either pkg, apt, or apt-get to update sources and install latest version of package nodejs, upgrade npm globally.

This is a new project from scratch, hence the only reproduction step is `git init; npm init; npm install -D tailwindlabs/tailwindcss`.

I can install `npm i -D tailwindcss` ok, but it is stuck on v2.1.4 with glob-parent outdated dependency, hence the attempt to pull directly from GitHub.  Did I do it wrong?

**Comment by adamwathan** [comment]
Hey! The code on GitHub is not transpiled or anything so won't work. If you want to use a pre-release build, you can install our latest canary:

`npm install -D tailwindcss@canary`

...which is usually only a handful of commits behind master.

**Comment by Leif-W** [comment]
Ok, that makes sense.  I can find the specific commit where the dependency was removed.  It was committed 2-ish weeks ago, but still not in 2.1.4 which was released a few days ago.  Maybe it's in canary.  Ahh, going to canary gets rid of 4 medium security warnings, in exchange for 7 high severity warnings.  Yikes!

**Comment by adamwathan** [comment]
Just so we're on the same page, any warning is a false positive in a tool like Tailwind because it does not run outside of your own computer — you don't ship Tailwind itself to production, just the CSS it generates. Will look into the warnings but it's nothing to be afraid of.

**Comment by Leif-W** [comment]
Thank you!
