### ISSUE TITLE
Impending name clash with `overflow-clip`

### ISSUE THREAD

**Issue by valtism** [tailwindlabs/tailwindcss#4622]
### Reproduction repository

www.IUnderstandWhyYouRequireThisButInMyCaseItsNotReallyNecessary.com

### Describe your issue

There is a new overflow type being adopted by browsers, `overflow: "clip"`. You can see it picking up adoption here: https://caniuse.com/mdn-css_properties_overflow_clip

The idea of it is to fix issues with `overflow: "hidden"` where it does a similar thing but does not break any `position: "sticky"`'d elements inside it. 

RIght now, tailwind defines the class of `overflow-clip` as `text-overflow: "clip"`, so you can see that this will become a problem when the overflow spec is more widely adopted and used.

**Comment by reinink** [comment]
Hey thanks for making us aware of this, we've gone ahead and renamed `overflow-clip` to `text-clip`, and now are using `overflow-clip` for `overflow: clip` 👍 

https://github.com/tailwindlabs/tailwindcss/pull/5630
