### ISSUE TITLE
group-hover variants not working when adding other values in theme

### ISSUE THREAD

**Issue by ovesco** [tailwindlabs/tailwindcss#4638]
### What version of Tailwind CSS are you using?

v2.1.4

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js 10.2.3

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/ovesco/improbable-test

### Describe your issue

The linked repo illustrates the problem, tested with `scale` and `group-hover`.

Adding new variants and extending theme with new values works as expected if used independently (not both at the same time in the config file).

For example this scale theme config:
```js
module.exports = {
  theme: {
    scale: {
      '-1': '-1',
    },
  },
  // ...
}
```

Or this variants config:
```
module.exports = {
  theme: {
  },
  variants: {
    extend: {
      scale: ['group-hover'],
    },
  },
}
```

But when using both the theme value will be taken into account (results in multiple classes, for example `-scale-1`), but group-hover wont be generated for scale (`group-hover:scale-105` won't work anymore), as if defining new theme values remove the possibility from adding new variants.

Removing the `-1: -1` from theme.scale doesn't solve the problem, you actually have to remove theme.scale from the config file for the `group-hover` to work as expected.

**Comment by adamwathan** [comment]
Hey! This is because you are overriding the entire set of default `scale` values. You need to put your custom values under `extend` if you want to keep the defaults:

```js
module.exports = {
  theme: {
    extend: {
      scale: {
        '-1': '-1',
      },
    },
  },
  // ...
}
```
