### ISSUE TITLE
Using `!text-center` breaks normal `text-center` (JIT)

### ISSUE THREAD

**Issue by ilya-vasilyev** [tailwindlabs/tailwindcss#4639]
### What version of Tailwind CSS are you using?

postcss7-compat@^2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

webpack 4.46.0

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### Reproduction repository

-

### Reproduction steps:

- have a `text-center` class
- add `!` in front of it, to make it important: `!text-center`
- save
- remove `!` to get back to normal: `text-center`
- save
- **`text-center` class no longer exists**, only restarting a dev server helps

NOTE: if both `text-center` and `!text-center` exist when dev server is started, only the important one will be present - they cannot coexist.

**Comment by adamwathan** [comment]
This should be fixed now, you'll have to install the `canary` build to use it before we release the next proper version though:

```
npm i -D @tailwindcss/postcss7-compat@canary
```

Thanks for reporting!
