### ISSUE TITLE
[Bug]: JIT: prefix key gets appended twice 

### ISSUE THREAD

**Issue by gcavanunez** [tailwindlabs/tailwindcss#4641]
### What version of Tailwind CSS are you using?

v2.1.4

### What build tool (or framework if it abstracts the build tool) are you using?

@vue/cli 4.5.12 | postcss 7

### What version of Node.js are you using?

v15.6.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/gcavanunez/tailwindcss-jit-prefix-vue-sample

### Describe your issue

Describe the bug
When enabling the JIT mode and when setting the purge mode to scan certain components, an odd behavior occurs that the prefix key gets added twice. I've isolated the error to a single component to reproduce a single error, but when using it in a large project, the issue is much more present with classes like block, flex getting the double, triple or quadruple prefix.   

Additional context
I'm using postcss to compile to further isolate the issue, some of the code from the component I've extracted contains vuetify components, but bringing it on board to demonstrate  the issue is not necessary.  

Also I've added an example component where the issue doesn't occur which is the App.vue file under src, currently the tailwind.config.js is set to purge the bug error component alone.

To Reproduce
1. yarn dev-tw-sample
2. view the tw.build.css under src directory 

Screenshots
![image](https://user-images.githubusercontent.com/9332696/121827248-ea142100-cc80-11eb-96ff-1a24c93307e1.png)

**Comment by kytosai** [comment]
Me too,
when i build production i don't have this problem.
Only when running in development and in jit mode enabled !

**Comment by adamwathan** [comment]
This should be fixed now, you'll have to install the `canary` build to use it before we release the next proper version though:

```
npm i -D @tailwindcss/postcss7-compat@canary
```

Thanks for reporting!
