### ISSUE TITLE
JIT not working/classes not created with webpack-dev-server

### ISSUE THREAD

**Issue by brunottonurb** [tailwindlabs/tailwindcss#4660]
### What version of Tailwind CSS are you using?

2.1.4

### What build tool (or framework if it abstracts the build tool) are you using?

webpack 5.39.0, webpack-dev-server 3.11.2, postcss 8.3.4

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

Chrome, Firefox

### What operating system are you using?

Ubuntu 20.04.2

### Reproduction repository

https://github.com/brunottonurb/debug_tailwind_jit

### Describe your issue

1. Start dev server, open localhost:3000
2. See red square
3. Edit code from `bg-red-800` to `bg-green-400` in `app.js`
4. Do not see green square
5. Stop dev server & restart
6. See green square

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

There are a few ways you can fix this, but the easiest way for you right now would be to use the canary version. We will release a new version very soon anyway!

Running `npm install tailwindcss@canary` in your repo, and restarting the `npm run start` script should do the trick.

**Comment by greg-owl** [comment]
@RobinMalfait - what if you are running compatibility mode?
