### ISSUE TITLE
[2.2.0] jit mode not working properly in svelte-kit

### ISSUE THREAD

**Issue by ksmsk** [tailwindlabs/tailwindcss#4683]
### What version of Tailwind CSS are you using?

2.2.0

### What build tool (or framework if it abstracts the build tool) are you using?

svelte@next

### What version of Node.js are you using?

14.17.1

### What browser are you using?

N/A

### What operating system are you using?

linux

### Reproduction repository

https://github.com/ksmsk/tailwindcss-sveltekit-bug

### Describe your issue

Honestly i don't know if it's about tailwindcss or svelte-kit or vite but it was working perfectly at 2.1.2. tailwindcss generates initial classes after starting dev server then stops generating changes. No error messages in console. While dev server is running If i make any changes in tailwind config file and save, it makes tailwindcss to generate new classes.

**Comment by f-elix** [comment]
Saving a .css files will also generate the new classes. The .svelte files seem to be ignored on save.

**Comment by adamwathan** [comment]
Hey! Check the troubleshooting guide in the docs:

https://tailwindcss.com/docs/just-in-time-mode#styles-don-t-update-when-saving-content-files

Vite currently has bugs that make it incompatible with v2.2 out of the box, but adding `TAILWIND_MODE=watch` should get things working the way they did in 2.1.

**Comment by f-elix** [comment]
Thanks for the quick reply Adam!

I did try that solution, but when Tailwind is in watch mode (I can confirm it by the different console output), I get the following error on the browser page (but not in the console):

```json
TypeError: Cannot read property 'replace' of null
    at slash$3 (B:\web\projects\mtlp\mtlp-website-v2\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:4033:14)
    at normalizePath$4 (B:\web\projects\mtlp\mtlp-website-v2\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:4080:56)
    at ModuleGraph.createFileOnlyEntry (B:\web\projects\mtlp\mtlp-website-v2\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:59584:16)
    at B:\web\projects\mtlp\mtlp-website-v2\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:23096:84
    at Array.map (<anonymous>)
    at TransformContext.transform (B:\web\projects\mtlp\mtlp-website-v2\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:23096:58)
    at async Object.transform (B:\web\projects\mtlp\mtlp-website-v2\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:44765:30)
    at async transformRequest (B:\web\projects\mtlp\mtlp-website-v2\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:59029:29)
    at async instantiateModule (B:\web\projects\mtlp\mtlp-website-v2\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:68641:10)
```

This is such an unhelpful and cryptic error message, so I don't really expect you to debug it for me. It might also be a particular Svelte-kit bug (which uses Vite under the hood).

**Comment by anncwb** [comment]
vue3 vite has the same error as this, it doesn't work anymore

**Comment by anncwb** [comment]
This way solved my problem
```bash
"dev": "npm-run-all --parallel dev:*",
 "dev:server": "vite",
"dev:css": "tailwindcss -o src/tailwind.css -w",
```

**Comment by ksmsk** [comment]
> Hey! Check the troubleshooting guide in the docs:
> 
> https://tailwindcss.com/docs/just-in-time-mode#styles-don-t-update-when-saving-content-files
> 
> Vite currently has bugs that make it incompatible with v2.2 out of the box, but adding `TAILWIND_MODE=watch` should get things working the way they did in 2.1.

This did the trick, thanks Adam! So problem was vite not supporting 2.2 yet.

**Comment by f-elix** [comment]
@anncwb Thanks for this solution. It's not as straightforward in Svelte-kit, so here is how I solved it, if this helps anybody:

```json
"dev": "npm-run-all --parallel dev:*",
"dev:kit": "svelte-kit dev",
"dev:css": "tailwindcss -i ./src/lib/css/tailwind.css -c ./tailwind.config.cjs -o ./src/lib/css/main.css -w",
```

You can then import the `main.css` file in your `__layout.svelte` file:

```html
<script>
   import '$lib/css/main.css';
</script>
```

You can of course adapt the css file paths to your project structure.

You also have to explicitely tell the Tailwind CLI what config file to use, even if it's at the root of your project, since most config file in a Svelte-kit project use the `.cjs` extension.

**Comment by foundationframework** [comment]
workarounds dont work for me (vite + svelte) it works on first run (yarn dev) but on hmr, it crashes.

**Comment by adamwathan** [comment]
This should work now if you can upgrade the underlying Vite version to v2.3.8 👍🏻
