### ISSUE TITLE
Error while compiling: "TypeError: Cannot read property 'theme' of undefined"

### ISSUE THREAD

**Issue by rushenn** [tailwindlabs/tailwindcss#4706]
### What version of Tailwind CSS are you using?

2.2.1

### What build tool (or framework if it abstracts the build tool) are you using?

postcss-cli 8.3.1, craco 6.1.2

### What version of Node.js are you using?

v14.17.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

-

### Describe your issue

I'm getting the following error:
```
"TypeError: Cannot read property 'theme' of undefined"
```
when I try to compile using the script: 

```
postcss ./tailwind.css -c ./tailwind.config.js -o ./utilities.css --verbose
```

My configs:

**postcss.config.js**
```
module.exports = {
  plugins: {
    "@tailwindcss/jit": {},
    autoprefixer: {}
  }
}
```

**tailwind.config.js**
```
module.exports = {
  mode: "jit",
  purge: [
    "./*.html"
  ],
  darkMode: false,
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
```

**Comment by slauzinho** [comment]
I had the same issue and I fixed it by changing my `postcss.config.js` to
```javascript
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {}
  }
}
```

Their [docs](https://tailwindcss.com/docs/just-in-time-mode) no longer reference any change needed to the postcss config file

**Comment by adamwathan** [comment]
Yeah `@tailwindcss/jit` was a temporary package while we iterated on it before incorporating it directly into Tailwind, you should be good if you just move over to Tailwind itself now! 👍
