### ISSUE TITLE
[JIT] Layers are not loaded

### ISSUE THREAD

**Issue by DarkGhostHunter** [tailwindlabs/tailwindcss#4712]
### What version of Tailwind CSS are you using?

v2.2

### What build tool (or framework if it abstracts the build tool) are you using?

Laravel Mix v6.0.23

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

N/A

### What operating system are you using?

macOS, Windows, Ubuntu 21.14

### Reproduction repository

https://github.com/DarkGhostHunter/tailwindbug/

### Describe your issue

When using Laravel Mix (Webpack made simple), an error occurs when trying to add something into any Tailwind CSS layer, like _base_ or _components_, when using `mix`.

The `watch` command watches code changes and updates the code, which BrowserSync catches and reloads the page. 

The CSS on question is something like this:

```postcss
@import "tailwindcss/base"
@layer base {
    p { 
        @apply pb-3;
    }
}
```

You will receive an error like this when calling `yarn watch`.

```
ERROR in ./resources/css/app.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(1:1) \projects\TailwindBug\resources\css\base.css `@layer base` is used but no matching `@tailwind base` directive is present.

   at processResult (\projects\TailwindBug\node_modules\webpack\lib\NormalModule.js:701:19)
    at \projects\TailwindBug\node_modules\webpack\lib\NormalModule.js:807:5
    at \projects\TailwindBug\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at \projects\TailwindBug\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (\projects\TailwindBug\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.loader (\projects\TailwindBug\node_modules\postcss-loader\dist\index.js:140:7)

```

I'm JavaScript noob so I can't help but say that building the CSS on development or production doesn't return the error, using `yarn dev` or `yarn prod`, respectively.

Note that this doesn't happen with JIT disabled:

```
/* tailwind.config.js */
module.exports = {
    mode: 'jit',
    /* ... */
}
```

I can only presume [loader-runner](https://www.npmjs.com/package/loader-runner) is the culprit.

**Comment by adamwathan** [comment]
Briefly looked at this — there is something super weird going on where it builds the CSS twice, and on the second build the output of the first build is used as the input, but with the contents of your custom `base.css` file appended to the end. _Very_ weird behavior, hoping it's maybe a bug in Mix that we can figure out how to fix.

Messaged @thecrypticace about it since he does a lot to maintain Mix, maybe he will have some ideas 🤞

**Comment by adamwathan** [comment]
Hey! So we've narrowed this down to an issue in Mix when using a separate `postcss.config.js` file, which me and @thecrypticace are hoping we can figure out.

But in the mean time, the best option is to just put your PostCSS config inside `webpack.mix.js`, and things will work properly:

```js
// webpack.mix.js
mix.postCss('resources/css/app.css', 'public/css', [
    require("postcss-import"),
    require('tailwindcss/nesting')(require('postcss-nesting')),
    require('tailwindcss')('./tailwind.config.js'),
]);
```

...and just delete your `postcss.config.js` file. Going to close because nothing we can do to fix this in Tailwind itself, has to be resolved in Mix.

**Comment by DarkGhostHunter** [comment]
Got it. I’ll pass the ball to the Mix repository if it’s not already there. 

Italo Baeza C.

**Comment by JeffreyWay** [comment]
Heads up that Jordan fixed this in the Mix repo last night, and we've tagged a patch release just now.

**Comment by adamwathan** [comment]
Last night?! I didn't even tell him about it until this morning! 🤯

**Comment by DarkGhostHunter** [comment]
INCEPTION. 

This brings a new hindrance: if you DARE to call a non existing component or utility, Mix will error and won’t work anymore. 

Italo Baeza C.

**Comment by thecrypticace** [comment]
Adam, didn't you hear I'm a time traveler?! :D

**Comment by thecrypticace** [comment]
@DarkGhostHunter Can you provide more details on what it is? And it sounds like an issue for the Mix repo.

**Comment by JeffreyWay** [comment]
Haha - sorry. I saw a message today asking for a new tagged release. Assumed he worked on it last night. Jordan is awesome. 👍

**Comment by DarkGhostHunter** [comment]
It says the offending component doesn’t exist, and if it is a layer it wasn’t declared. But then, any code change or fix is moot.  

Italo Baeza C.

**Comment by DarkGhostHunter** [comment]
[Further discussion](https://github.com/JeffreyWay/laravel-mix/issues/3020)

**Comment by helhum** [comment]
I'm having the exact same issue with a plain webpack config with tailwindcss 2.2 and the jit engine.

```css
@import "tailwind.css"; /* only three lines with the @tailwind directives */

@layer base {
    body {
        display: block;
    }
}
```

css loader config

```js
                {
                    test: /\.css$/,
                    use: [
                        {
                            loader: MiniCssExtractPlugin.loader
                        },
                        {
                            loader: 'css-loader',
                            options: {importLoaders: 1}
                        },
                        {
                            loader: 'postcss-loader',
                            options: {
                                postcssOptions: {
                                    plugins: [
                                        require('tailwindcss'),
                                        require('autoprefixer'),
                                    ],
                                },
                            },
                        }
                    ],
                },
```

```
ERROR in ./src/css/styles.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(3:1) /path/frontend/src/css/styles.css `@layer base` is used but no matching `@tailwind base` directive is present.

1 | @import "tailwind.css";
2 |
> 3 | @layer base {
| ^
    4 |     body {/
        5 |         display: block;

        at processResult (/path/frontend/node_modules/webpack/lib/NormalModule.js:703:19)
        at /path/frontend/node_modules/webpack/lib/NormalModule.js:809:5
        at /path/frontend/node_modules/loader-runner/lib/LoaderRunner.js:399:11
        at /path/frontend/node_modules/loader-runner/lib/LoaderRunner.js:251:18
        at context.callback (/path/frontend/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
        at Object.loader (/path/frontend/node_modules/postcss-loader/dist/index.js:94:7)
    @ ./src/javascript/index.js 1:0-27

        1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
        webpack 5.38.1 compiled with 2 errors in 369 ms
        ℹ ｢wdm｣: Failed to compile.
```

The compilation works without jit, but obviously other things are broken then.

Any hints?

**Comment by adamwathan** [comment]
@helhum I  think you need to add postcss-import to your plugins list 👍🏻

**Comment by helhum** [comment]
@adamwathan ah, ok. My css structure was easy enough until recently, that I could rely on webpack resolving those for me.

Adding postcss-import to the plugin list, resolved the issue for me as well. Thanks.

**Comment by daugaard47** [comment]
I keep getting this Error in JIT mode only. If I remove JIT it compiles fine. I've been trying to figure this out for hours. Could someone please help me correct my error? I don't understand what this postcss-loader issue is.

**BUILD ERROR:**
```
ERROR in ./resources/css/app.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
RangeError: Maximum call stack size exceeded
    at candidatePermutations .... etc...
```

**Webpack.mix.js file:**

```
let mix = require('laravel-mix');

mix.js('resources/js/app.js', 'public/js')
    .postCss('resources/css/app.css', 'public/css')
        .options({
                processCssUrls: false,
                postCss: [
                    require('css-declaration-sorter')({order: 'smacss'}) 
                ],
            autoprefixer: {
                options: {
                    browsers: [
                        'last 4 versions',
                    ]
                }
            }
            });
mix.browserSync('mysite.oo/');

if (mix.inProduction()) {
    mix.version();
}
```
**Postcss.config.js:**
```
module.exports = {
    plugins: {
        tailwindcss: {},
        autoprefixer: {}
    }
}
```
**Tailwind.config.js:**
```
const defaultTheme = require('tailwindcss/defaultTheme');
const colors = require('tailwindcss/colors')
module.exports = {
    mode: 'jit',
    purge: [
        './public/**/*.html',
        './src/**/*.{js,jsx,ts,tsx,vue}',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/sass/**/*.scss',
        './resources/css/**/*.css',
    ],
    darkMode: false, // or 'media' or 'class'
    theme: {
        extend: {
            fontFamily: {
                sans: ['Nunito', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                transparent: 'transparent',
                current: 'currentColor',
               // etc...
            },
        },
    },
    variants: {
        ringWidth: ['hover', 'active'],
        extend: {}
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/typography'),
        require('@tailwindcss/aspect-ratio'),
    ],
}

```
Package.json:
```
{
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "npx mix",
    "watch": "npx mix watch",
    "prod": "npm run production",
    "production": "npx mix -p"
  },
  "devDependencies": {
    "@tailwindcss/aspect-ratio": "^0.2.0",
    "@tailwindcss/forms": "^0.3.2",
    "@tailwindcss/typography": "^0.4.0",
    "alpinejs": "^3.2.1",
    "autoprefixer": "^10.2.5",
    "axios": "^0.21.1",
    "browser-sync": "^2.26.14",
    "browser-sync-webpack-plugin": "^2.3.0",
    "cross-env": "^7.0.3",
    "css-declaration-sorter": "^6.0.3",
    "dayjs": "^1.10.6",
    "jquery": "^3.6.0",
    "laravel-mix": "^6.0.25",
    "lity": "^2.4.1",
    "lodash": "^4.17.21",
    "postcss": "^8.3.5",
    "postcss-import": "^14.0.2",
    "postcss-loader": "^6.1.1",
    "postcss-nested": "^5.0.5",
    "resolve-url-loader": "^4.0.0",
    "tailwindcss": "^2.2.4",
    "vue": "2.6.12",
    "vue-loader": "^15.9.6",
    "vue-loading-overlay": "^3.4.2",
    "vue-router": "^3.5.1",
    "vue-template-compiler": "^2.6.12",
    "webpack": "^5.44.0"
  }
}
```

**Comment by adamwathan** [comment]
Please open a new issue, we don't monitor closed issues.

My gut is that your purge config is causing all of your problems, because it includes your CSS files and it's only supposed to include template files.

**Comment by daugaard47** [comment]
@adamwathan I'll open an issue in the help discussion since this probably isn't a bug.
One thing tho.. If I remove `'./resources/views/**/*.blade.php',` from purge it compiles.  Does that give you any ideas?
Thanks!
