### ISSUE TITLE
New opacity shortcut not working with custom colors

### ISSUE THREAD

**Issue by lilnoes** [tailwindlabs/tailwindcss#4716]
### What version of Tailwind CSS are you using?

v2.2.2

### What build tool (or framework if it abstracts the build tool) are you using?

tailwindcss cli

### What version of Node.js are you using?

v16.3.0

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu 20

### Reproduction repository

https://github.com/lilnoes/tailwindbug

### Describe your issue

tailwindcss v2.2 introduced a new way to add opacity to color utilities like
bg-white/20, but "bg-[wheat]/20" is not working, background color is not changing. I expected "bg-[wheat]/20" to work like "bg-[wheat] bg-opacity-20"

**Comment by adamwathan** [comment]
Hey, should be fixed here!

https://github.com/tailwindlabs/tailwindcss/pull/4723

Can test it out using `npm install tailwindcss@insiders`, fix will land in v3.
