### ISSUE TITLE
set TAILWIND_MODE=watch, then project will rebuild slowly [hmr]

### ISSUE THREAD

**Issue by growuper** [tailwindlabs/tailwindcss#4732]
### What version of Tailwind CSS are you using?

"tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.2.2"

### What build tool (or framework if it abstracts the build tool) are you using?

"webpack": "^4.41.5", "postcss": "^7.0.35", "@pmmmwh/react-refresh-webpack-plugin": "^0.4.3"

### What version of Node.js are you using?

v12.18.2

### What browser are you using?

chrome

### What operating system are you using?

macOS

### Reproduction repository

*

### Describe your issue

JIT mode when set TAILWIND_MODE=watch and modify just little class (ex: add bg-[#fff]), the project will rebuild slowly with react-refresh-webpack-plugin

**Comment by adamwathan** [comment]
Hey! Please open a new issue with a reproduction. From the issue template:

> Unfortunately we can't provide support without a reproduction, and your issue will be closed and locked with no comment if this is not provided.
