### ISSUE TITLE
keyframes from animations with var missing from v2.2.0 

### ISSUE THREAD

**Issue by hug963** [tailwindlabs/tailwindcss#4737]
### What version of Tailwind CSS are you using?

2.2.2

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js 11.0.0

### What version of Node.js are you using?

v14.17.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/cF9YjsPwu9

### Describe your issue

Since v2.2.0, keyframes from animations with a var() in the definition are missing.
The animation is there, only the keyframes are missing.

From  the example on Tailwind Play, the first logo only moves when switching back to v1.9.6 but doesn't in the latest version.

It is working fine on v2.1.4

**Comment by adamwathan** [comment]
Hey! This is fixed in 2.2.16 tagged this morning 👍🏻 

https://github.com/tailwindlabs/tailwindcss/pull/5602

Thanks 🍻
