### ISSUE TITLE
Webpack Encore - JiT

### ISSUE THREAD

**Issue by seb-jean** [tailwindlabs/tailwindcss#4742]
### What version of Tailwind CSS are you using?

2.2.0

### What build tool (or framework if it abstracts the build tool) are you using?

Webpack Encore

### What version of Node.js are you using?

12.13

### What browser are you using?

N/A

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/seb-jean/tailwind

### Describe your issue

Hi,
I have a bug with JiT.
CSS classes are not added in my CSS file.

**Comment by bradlc** [comment]
Hey @seb-jean. You need to upgrade `postcss-loader` to version `5.3.0`, which added support for the PostCSS `dir-dependency` messages that Tailwind uses:

```diff
- "postcss-loader": "5.0.0",
+ "postcss-loader": "5.3.0",
```

**Comment by seb-jean** [comment]
It's works :).
Thanks @bradlc
