### ISSUE TITLE
Infinite recompile loop because of greedy purge

### ISSUE THREAD

**Issue by RSO** [tailwindlabs/tailwindcss#4753]
### What version of Tailwind CSS are you using?

v2.2.2

### What build tool (or framework if it abstracts the build tool) are you using?

webpack 5.39.1, @rails/webpacker 6.0.0-beta.7, postcss 8.3.5

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/RSO/tailwind-purge-bug

### Describe your issue

(I am using the JIT mode).

After upgrading tailwindcss from 1.1 to 2.2.2 I've encountered an infinite recompile bug. After some debugging I found that the recompiling is triggered because of the following purge rule: `"./public/*.html"`. Ruby on Rails comes with a public folder that both contains compiled files and static files. My gut feeling says that the problem comes from the fact that upon compilation, webpack writes a `manifest.json` file to `"./public/packs/manifest.json"` which somehow might trigger Tailwind JIT to recompile because of the purge rule for `"./public/*.html"`, although I'm not 100% certain.

# To Reproduce
Clone the reproduction repository
```bash
cd tailwind-purge-bug
bundle
yarn
bin/webpack-dev-server
```

Let me know if there's anything more that I can do to help figure out what is wrong!

**Comment by haipham** [comment]
Me too.

**Comment by tleish** [comment]
see: https://github.com/tailwindlabs/tailwindcss/issues/4701

**Comment by RSO** [comment]
Duplicate of #4701
