### ISSUE TITLE
Issue with theme colors

### ISSUE THREAD

**Issue by Avratz** [tailwindlabs/tailwindcss#4758]
### What version of Tailwind CSS are you using?

v2.2.2

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js 11

### What version of Node.js are you using?

v14.17.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### Reproduction repository

https://github.com/Avratz/

### Describe your issue

The colors in the theme are not working properly.

I have this setup:
  ```
theme: {
    extend: {
      colors: { 
        secondary: {
                  50: '#E5F5FF',
                  100: '#B7E3FF',
                  200: '#8AD1FF',
                  300: '#5CBEFF',
                  400: '#2EACFF',
                  500: '#0095F6',
                  600: '#007CCD',
                  700: '#0064A4',
                  800: '#004B7C',
                  900: '#003253',
                },
        }
   }
}
```
And any color after 500 wont work.

Any suggestions?

**Comment by adamwathan** [comment]
Hey! I can't reproduce here:

https://play.tailwindcss.com/7HxuZpAC4Z

Can you explain what you mean by "won't work" and give an example?

**Comment by Avratz** [comment]
> Hey! I can't reproduce here:
> 
> https://play.tailwindcss.com/7HxuZpAC4Z
> 
> Can you explain what you mean by "won't work" and give an example?

Im using this setup https://github.com/Avratz/basic-nextjs11-typescript-tailwind. 
I think the problem is something related with nextjs 11, because in this other repo https://github.com/Avratz/i-love-tailwind I have the exact same setup, but with nextjs 10  and tailwind 2.0.4.
