### ISSUE TITLE
JIT + --watch not rebuilding when running via PostCSS CLI

### ISSUE THREAD

**Issue by domchristie** [tailwindlabs/tailwindcss#4763]
### What version of Tailwind CSS are you using?

2.2 - 2.2.2 (working on v2.1.4)

### What build tool (or framework if it abstracts the build tool) are you using?

postcss-cli 8.3.1, postcss 8.3.5

### What version of Node.js are you using?

v14.15.3

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/domchristie/tailwind-jit-watch-test

### Describe your issue

From Tailwind version 2.2, with a vanilla PostCSS build process (`postcss ./tailwind.css -o ./styles.css --watch`), rebuilds are not triggered when watched files are changed.

To reproduce, clone the demo:
```
git clone https://github.com/domchristie/tailwind-jit-watch-test.git
```

Set up:

```
cd tailwind-jit-watch-test
npm i
```

Start the PostCSS watcher:

```
npm start
```

Open `tailwind-jit-watch-test/index.html` in your browser. The text should be blue.

Change the class to `text-green-600`, and refresh.

Tailwind CLI works as expected, but thought it was worth raising.

**Comment by sachinraja** [comment]
Check out [this section in the docs](https://tailwindcss.com/docs/just-in-time-mode#styles-don-t-update-when-saving-content-files). Looks like you have to add `TAILWIND_MODE=watch` before it:
`TAILWIND_MODE=watch postcss ./tailwind.css -o ./styles.css --watch`.

**Comment by domchristie** [comment]
Thanks @sachinraja 🙏

**Comment by htulipe** [comment]
Hi there. 

Replying to this closed issue because I don't understand why one would need to change the watch mode when using postcss-cli.

The JIT doc says it relies on postcss "directory dependency messages" to function, feature that may not been supported by some build tool. But here, we are directly using postcss/postcss-cli, how could it not work ?

Thks

**Comment by sachinraja** [comment]
Dependency message support has been added to `postcss-cli` but a new version of the package has not been published yet.

**Comment by htulipe** [comment]
Thx @sachinraja I missed that info

**Comment by sachinraja** [comment]
Also keep in mind that `postcss` and `postcss-cli` are two different packages. Just because `postcss` has a feature, it doesn't mean `postcss-cli` will support it.
