### ISSUE TITLE
Tailwind JIT fails to generate classes in hot reload for React

### ISSUE THREAD

**Issue by rojasdiegopro** [tailwindlabs/tailwindcss#4768]
### What version of Tailwind CSS are you using?

npm:@tailwindcss/postcss7-compat@^2.2.2

### What build tool (or framework if it abstracts the build tool) are you using?

craco

### What version of Node.js are you using?

craco ^6.1.2

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### Reproduction repository

https://github.com/rojasdiegopro/tailwind-react-issue

### Describe your issue

The reproduction repository features a simple React application that I setup with the [tailwind create-react-app tutorial](https://tailwindcss.com/docs/guides/create-react-app).

I then switched to JIT mode by editing the `tailwind.config.js`.

I created a simple `App` component which displays some red text. I ran the application in development mode using `npm run start`. Everything worked fine. Without closing the development server I changed the color of the text to `text-blue-900` inside my `App` component and saved the file.

I expected the colour to change to blue, instead the text went black. This lets me think that using this configuration, tailwind does not re-generate the styles in hot reload mode. When I close the dev server and run it again, the text is displayed in blue just fine.

**Comment by bradlc** [comment]
Hey @rojasdiegopro. Create React App does not currently support PostCSS `dir-dependency` messages, so you need to set the `TAILWIND_MODE` environment variable to `watch` in your `start` script, for example:

```diff
  "scripts": {
-   "start": "craco start",
+   "start": "TAILWIND_MODE=watch craco start",
    "build": "craco build",
    "test": "craco test",
    "eject": "react-scripts eject"
  },
```

You can read more about this here: https://tailwindcss.com/docs/just-in-time-mode#styles-don-t-update-when-saving-content-files

**Comment by Miyan0** [comment]
This don't work for me. I use Windows 10, Yarn 1.22.5 and PowerShell 7.1.3.
I tried;
1. Custom PowerShell script
```
$Env:TAILWIND_MODE="watch";
yarn start
```  
with  
```
  "scripts": {
   "start": "craco start",
    ...
```

I get (replacing my username with `<MyUserName>`

```
D:\myproject\node_modules\react-scripts\scripts\start.js:19
  throw err;
[Error: ENOENT: no such file or directory, stat 'C:\Users\<MyUserName>\AppData\Local\Temp\TmP18pnl05b-b'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'C:\\Users\\<MyUserName>\AppData\\Local\\Temp\\TmP18pnl05b-b'
}
```
2. Installed cross-env with
```
  "scripts": {
   "start": "cross-env TAILWIND_MODE=watch && craco start",
    ...
```
No errors but the JIT does not generate classes in hot reload.

Any ideas?

Thanks
