### ISSUE TITLE
Outdated `button:focus` makes buttons less accessible

### ISSUE THREAD

**Issue by LeoniePhiline** [tailwindlabs/tailwindcss#4769]
### What version of Tailwind CSS are you using?

v2.2

### What build tool (or framework if it abstracts the build tool) are you using?

vite 2

### What version of Node.js are you using?

14

### What browser are you using?

Firefox

### What operating system are you using?

OpenSUSE Tumbleweed

### Reproduction repository

https://codepen.io/rickymetz/pen/ZrbXqJ

### Describe your issue

TailwindCSS Preflight adds a fairly visually inaccessible `outline: 1px dotted;` to `button:focus`, which can be seen as a regression towards the newer and much more accessible Firefox form element default focus style.

https://github.com/tailwindlabs/tailwindcss/blob/ea3892fc9167cece4a1d3aab2c342bf791baea7e/src/plugins/css/preflight.css#L32-L40

Open the linked reproduction codepen in Firefox and use the tab key to focus a button. You will see that the inaccessible `1px dotted` focus outline is no longer the browser default style:

![image](https://user-images.githubusercontent.com/22329650/123085965-2a169900-d423-11eb-910a-b36603d789a1.png)

Related to https://github.com/sindresorhus/modern-normalize/issues/55 where the same inaccessible legacy focus ring is applied to form text input elements, after Firefox switched to better default focus styles.

Relevant links:
- https://design.firefox.com/photon/components/input-fields.html#behaviors
- https://bugzilla.mozilla.org/show_bug.cgi?id=1284235

**Comment by adamwathan** [comment]
Should be good in v2.2.3!

**Comment by LeoniePhiline** [comment]
That was fast. 🚀 (*You can only feel the tailwind*)

**Comment by adamwathan** [comment]
@LeoniePhiline Did you notice that Firefox still uses the dotted outline for links? Wonder why that is.

<img width="357" alt="image" src="https://user-images.githubusercontent.com/4323180/123266096-b2e81000-d4c9-11eb-84da-811e9329b3c8.png">

**Comment by LeoniePhiline** [comment]
This is indeed quite weird. ~~Should we report a bug?~~
There are some bugs about the subject: https://bugzilla.mozilla.org/buglist.cgi?quicksearch=link+focus+outline
