### ISSUE TITLE
Tailwind escaped classes are not purged

### ISSUE THREAD

**Issue by AadilMehrajBhat** [tailwindlabs/tailwindcss#4771]
### What version of Tailwind CSS are you using?

v2.0.1

### What build tool (or framework if it abstracts the build tool) are you using?

postcss-cli 8.3.0, tailwindcss 2.0.1, postcss 8.1.14, autoprefixer 10.0.4

### What version of Node.js are you using?

v12.22.1

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### Reproduction repository

https://github.com/AadilMehrajBhat/tailwindcss-purge

### Describe your issue

I have a use case in which I need to persist previous build CSS for backward compatibility, in order to achieve the same I was adding the previous bundle CSS as one of the purge path entries to retain those tailwind classes, which worked very well. But for the tailwind classes that are escaped,  are not getting added in the resulting bundle.

E.g.
Previous CSS bundle:
```
.text-sm{font-size:.875rem;line-height:1.25rem}

.md\:order-last{order:9999}
```

When I add this file in the purge path:
```
 purge: ['./dist/**/*.css', ...]
```

The resulting bundle only includes the not escaped classes and ignores the escaped class, like this:
```
.text-sm{font-size:.875rem;line-height:1.25rem}
```

After I change `.md\:order-last` to `.md:order-last` in the original file, it is being added to the resulting bundle:
```
@media (min-width: 768px) {
  .md\:order-last {
    order: 9999
  }
}
```

Is there any way by which I can unescape the CSS classes while the content gets purged?

**Comment by sachinraja** [comment]
> I have a use case in which I need to persist previous build CSS for backward compatibility

If you don't mind me asking, what is that use case?

**Comment by AadilMehrajBhat** [comment]
> > I have a use case in which I need to persist previous build CSS for backward compatibility
> 
> If you don't mind me asking, what is that use case?

Well there are HTML pages that are already In the system (database) with the old classes and all of them share the same CSS file,  for that reason I need to persist already used classes for the backward compatibility.

**Comment by sachinraja** [comment]
How did you generate the old CSS build file?

**Comment by adamwathan** [comment]
Hey! This isn't really a bug, it's working correctly because PurgeCSS expects to be looking at HTML, not at CSS, so it thinks the classes with escaped characters just contain slashes, like if they were in HTML like this:

```html
<div class="md\:order-last">
```

I would recommend just keeping the old CSS file and not running PurgeCSS against that one at all, or using their control comments to preserve parts of your CSS:

https://purgecss.com/safelisting.html#in-the-css-directly

Going to convert this to a discussion for you since it's not a bug in Tailwind or anything 👍
