### ISSUE TITLE
Error while compiling: "Error: true is not a PostCSS plugin"

### ISSUE THREAD

**Issue by rushenn** [tailwindlabs/tailwindcss#4790]
### What version of Tailwind CSS are you using?

2.2.2

### What build tool (or framework if it abstracts the build tool) are you using?

postcss 8.3.5, craco 6.1.2

### What version of Node.js are you using?

v14.17.0

### What browser are you using?

Chrome, Safari

### What operating system are you using?

macOS

### Reproduction repository

-

### Describe your issue

I'm getting the following error:
```
./node_modules/prism-themes/themes/prism-ghcolors.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./node_modules/prism-themes/themes/prism-ghcolors.css)
Error: true is not a PostCSS plugin
```

My configs:

*postcss.config.js*

```
module.exports = {
  plugins: {
    tailwindcss": {},
    autoprefixer: {}
  }
}
```

*tailwind.config.js*

```
module.exports = {
  mode: "jit",
  purge: [
    "./*.html"
  ],
  darkMode: false,
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
```

**Comment by adamwathan** [comment]
Hey! Please include a repository demonstrating the issue. It's a required field, thanks.

**Comment by rushenn** [comment]
It was an issue with Autoprefixer. Updating the Autoprefixer to the most recent version, fixed the error. Thank you @adamwathan.
