### ISSUE TITLE
Denial of service  /  Css-what 

### ISSUE THREAD

**Issue by STEVETENAS** [tailwindlabs/tailwindcss#4794]
### What version of Tailwind CSS are you using?

2.0.4

### What build tool (or framework if it abstracts the build tool) are you using?

Laravel 8

### What version of Node.js are you using?

14.17.1

### What browser are you using?

Brave

### What operating system are you using?

Windows 10

### Reproduction repository

None

### Describe your issue

![20210624_115851](https://user-images.githubusercontent.com/46106643/123252898-b1781100-d4e4-11eb-958e-ca0c5a104dc7.jpg)

Please for help

**Comment by adamwathan** [comment]
Hey! Upgrade to the latest version of Tailwind.
