### ISSUE TITLE
Postcss ignored by CLI

### ISSUE THREAD

**Issue by sanderjn** [tailwindlabs/tailwindcss#4804]
### What version of Tailwind CSS are you using?

v2.2

### What build tool (or framework if it abstracts the build tool) are you using?

Tailwind-cli

### What version of Node.js are you using?

v14.15.1

### What browser are you using?

Brave, Firefox

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/sanderjn/tailwind-postcss-test

### Describe your issue

I'm using the new TailwindCSS v2.2 CLI combined with JIT mode. To enable nested CSS I followed the setup as described in the [installation guide](https://tailwindcss.com/docs/installation#using-a-custom-post-css-configuration).

I created a postcss.config.js to enable tailwindcss/nesting, but it seems to be ignored by the Tailwind CLI. I've tried to install other PostCSS plugins, but they don't seem to work either.

postcss.config.js:
```
module.exports = {
  plugins: [
    require('tailwindcss/nesting'),
    require('tailwindcss'),
    require('autoprefixer'),
  ]
}
```

Input src/tailwind.css:
```
[...]
@layer components {
  h1 {
      @apply text-red-600;
      span {
          @apply text-3xl;
      }
  }
}
```

Output tailwind.css:
```
[...]
h1 {
  --tw-text-opacity: 1;
  color: rgba(220, 38, 38, var(--tw-text-opacity));
  span {
    font-size: 1.875rem;
    line-height: 2.25rem;
  }
}
```

Expected output tailwind.css
```
h1 {
  --tw-text-opacity: 1;
  color: rgba(220, 38, 38, var(--tw-text-opacity));
}
h1 span {
    font-size: 1.875rem;
    line-height: 2.25rem;
}
```

**Comment by allmarkedup** [comment]
I've just come here as I am seeing this exact issue too.

The tailwind CLI is not even loading the postcss config file as far as I can tell - I've even put a bunch of intentional syntax errors into it and it still runs just fine.

The command I'm using to build my CSS is: `npx tailwindcss -i ./path/to/app.css -o ./public/app.css --watch`

**Comment by bradlc** [comment]
Hey @sanderjn. You need to use the `--postcss` flag to enable your custom PostCSS config:

```
npx tailwindcss -i src/tailwind.css -o tailwind.css -w --postcss
```

This is missing from the docs but we will get that updated 👍

**Comment by allmarkedup** [comment]
That works! Thank you @bradlc :-)

**Comment by sanderjn** [comment]
This is working, indeed. Solved my issue. Thanks!
