### ISSUE TITLE
Emoji not rendering properly in Chrome

### ISSUE THREAD

**Issue by hognevevle** [tailwindlabs/tailwindcss#4826]
### What version of Tailwind CSS are you using?

2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

Vue 3, postcss 8.2.10, webpack 5

### What version of Node.js are you using?

v15.3.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/B4CNAvFZnO?file=config

### Describe your issue

Certain emojis (such as ☺️) will not render properly in Chrome. It appears to be caused by the order in which the fonts are defined in the [default fontFamily](https://github.com/tailwindlabs/tailwindcss/blob/ff64417ff7b1a920e7c0dea06800a62826e18419/stubs/defaultConfig.stub.js?fbclid=IwAR1fyXr5R76XDT5RjubNz3Jt_MByKnaVosSd5w-OTKxlDtX3zypxyNrGVVo#L252). 

In my case, I've found that if I override `theme.extend.fontFamily.sans` and move `sans-serif` to the end, the emoji will render as expected.

Swap out the comments in the config in the provided playground URL, and hopefully you should see the issue (and workaround).

**Comment by jacobthesheep** [comment]
adding `@tailwind base;
* {
  font-family: font-sans;
}
@tailwind components;
@tailwind utilities;
`
fixed it

**Comment by adamwathan** [comment]
Hey! So it looks like the problem with this solution is that it breaks the rendering of all text if regular text isn't caught by any of the other font families at the beginning (notice all the weird spacing):

https://play.tailwindcss.com/D4Y4c9bmiT?file=config

<img width="526" alt="image" src="https://user-images.githubusercontent.com/4323180/124358105-cba0a600-dbec-11eb-8e4a-bc990b630374.png">

I checked a bunch of references and our approach is still the one used by other popular frameworks like Bootstrap for example by default, so I'm hesitant to change it.

I think for now best bet is to just change the font stack yourself for your own projects if this is important to you, as I worry there are other unintended side-effects of changing this that I don't fully understand but explain why it's setup the way it is in other popular projects.

I tested many sites that support user-generated content (like Medium for example) and they all render that emoji as the old-school glyph like you're seeing. The only one that didn't was GitHub, and they handle it by wrapping all emojis in a `<span>` with a custom class that assigns the emoji font:

<img width="574" alt="image" src="https://user-images.githubusercontent.com/4323180/124358283-96488800-dbed-11eb-8886-82304fbd0455.png">

So I think this is unfortunately a complex problem to solve that I'm guessing can't be solved by just changing the font stack, and is probably best done at the project-level so you can handle it however you feel is appropriate.

Sorry, hopefully there's a good solution for this in the future and we can re-visit then!

**Comment by jasonmhlaw** [comment]
Hi @adamwathan I am seeing the same issue. Would you mind to explain more about why it is more complex problem if changing the order of `sans-serif` to the end can show the proper emoji? And should I use this method to solve my issue?
