### ISSUE TITLE
list-decimal not working with JIT.

### ISSUE THREAD

**Issue by SchneckDigital** [tailwindlabs/tailwindcss#4842]
### What version of Tailwind CSS are you using?

2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

11.0.1

### What version of Node.js are you using?

14.15.4

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### Reproduction repository

https://github.com/SchneckDigital/list-decimal-issue

### Describe your issue

The `list-decimal` class does not work when using JIT.

**Comment by adamwathan** [comment]
Hey! It does work you just can't see it because the browser renders it outside of the element by default, and your list is right up against the edge of the screen.

See here:

https://play.tailwindcss.com/476929MbVc
