### ISSUE TITLE
Wrong rules order for filter utility with only one filter enabled

### ISSUE THREAD

**Issue by Djules** [tailwindlabs/tailwindcss#4849]
### What version of Tailwind CSS are you using?

v2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

webpack 4.46.0

### What version of Node.js are you using?

v14.1.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS Mojave

### Reproduction repository

none

### Describe your issue

In an attempt to ship only plugins I need, I disabled every filter but one in my config file, so I set every filter to `false` in `corePlugins` section, except for `filter` and `invert` (for example).

The issue is the `.filter {}` rule is printed AFTER the one for `.invert {}`.

It's always be as long as you enabled only one filter at a time. As soon as you enabled at least twice, the order is fine, the `.filter {}` rule is printed first.

And it's a problem because the `.filter {}` rule reset all CSS variables for filters…

**Comment by adamwathan** [comment]
Thanks, fixed! Will try to tag a patch this morning.

**Comment by Djules** [comment]
Awesome! 👏
