### ISSUE TITLE
variantOrder not respecting default order

### ISSUE THREAD

**Issue by ahuggins** [tailwindlabs/tailwindcss#4865]
### What version of Tailwind CSS are you using?

2.1.4

### What build tool (or framework if it abstracts the build tool) are you using?

webpack 4.46.0

### What version of Node.js are you using?

15.4.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/XkHxP2YoJ4?file=config

### Describe your issue

If I read the docs correctly, the default order for `variantOrder` should be:

```
variantOrder: [
    'first',
    'last',
    'odd',
    'even',
    'visited',
    'checked',
    'group-hover',
    'group-focus',
    'focus-within',
    'hover',
    'focus',
    'focus-visible',
    'active',
    'disabled',
  ]
```

Then for something like `textColor`: https://tailwindcss.com/docs/text-color

The docs say 

```
For example, this config will also generate active variants:

  // tailwind.config.js
  module.exports = {
    variants: {
      extend: {
        // ...
       textColor: ['active'],
      }
    }
  }
```

In the Play (https://play.tailwindcss.com/XkHxP2YoJ4?file=config) I made, with `jit` enabled, this works correctly (as I would expect), but when `jit` is disabled, the active state is never reflected.

The only work around I see is to go outside of the "extend" block and actually write a whole new order for the `textColor` variant:

```
textColor: [
            'responsive',
            'dark',
            'group-hover',
            'focus-within',
            'hover',
            'focus',
            'active',
            'group-active',
        ],
```

This seems to be the case for other properties (borderColor, backgroundOpacity). I think I read somewhere that TW always adds user supplied variants _after_ its own defaults...which I think makes sense except in this case where you want `active:` to take precedence over `hover:`.

What seems weird is that if the order was matched to the default `variantOrder` then I think this would work.

So I am thinking if as the docs say the only textColor variants generated by default are:

`responsive, dark mode, group-hover, focus-within, hover, focus`

And a user (config) has `extend: { textColor: ['active'] }` would it be possible to merge the order of the default variantOrder?

Like if `defaultVariantOrder.includes('active')` then 

```
textColor: [
    'responsive',
    'dark mode',
    'group-hover',
    'focus-within',
    'hover',
    'focus',
    'active',
]
```

or am I correct in thinking it basically does this:

```
textColor: [
    'active',
    'responsive',
    'dark mode',
    'group-hover',
    'focus-within',
    'hover',
    'focus',
]
```

I do think it's possible to handle better:

```js
// Default from Tailwind...or if user provides a custom variantOrder in config
const variantOrder = [
    'first',
    'last',
    'odd',
    'even',
    'visited',
    'checked',
    'group-hover',
    'group-focus',
    'focus-within',
    'hover',
    'focus',
    'focus-visible',
    'active',
    'disabled',
  ];
 
 // comes from Tailwind defaults I think 
  const textColor = [
    'responsive',
    'dark mode',
    'group-hover',
    'focus-within',
    'hover',
    'focus',
];

// override from config (if the user extends)
const extendTextColor = ['active'];

// merge default and config values
const merged = extendTextColor.concat(textColor);
// should be `["active", "responsive", "dark mode", "group-hover", "focus-within", "hover", "focus"]`

// separate variants that are not included in variantOrder
const noDefaultOrder = textColor.filter(v => !variantOrder.includes(v))
// should be `["responsive", "dark mode"]

// get the order of variants that we have in merged
const ordered = variantOrder.filter(v => !merged.includes(v));

// concat "noDefaultOrder" and "ordered"
const variantsInOrder = noDefaultOrder.concat(ordered);
// should be ["responsive", "dark mode", "group-hover", "focus-within", "hover", "focus", "active"]
```

Typing this out, probably see that it is not worth it, but essentially, if you follow the docs (not using the jit) then Tailwind won't really reflect what the docs say. Because the order of variants doesn't seem to allow things to work properly.

I am aware there may be very good reason for not doing this, but I'm going to submit this issue anyway just in case.

**Comment by adamwathan** [comment]
Hey! The real issue in your Play is just that you didn't enable `active` for `backgroundColor` or `borderColor`:

https://play.tailwindcss.com/HcBJoGAbXi?file=config

It merges them and preserves the order like you are expecting already, you just need to enable the variants. You were using `active:bg-gray-500` and `active:border-gray-500` but only had `active` enabled for `textColor`.

**Comment by ahuggins** [comment]
🤦 You are correct. So, the reason I thought this was an issue, my webpack build takes a while...let's say around 30 seconds. I was moving too fast and wasn't seeing things reflected.

Then I moved too quickly to try to build a Play and didn't think about if I was adding the right thing to config.

Sorry to take your time on this.

**Comment by adamwathan** [comment]
All good man no worries! Sorry you blew so much time on it 😅  Cheers 👊
