### ISSUE TITLE
Gridsome Tailwind Just-In-Time

### ISSUE THREAD

**Issue by DidelisMiksas** [tailwindlabs/tailwindcss#4928]
### What version of Tailwind CSS are you using?

npm:@tailwindcss/postcss7-compat@^2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

Gridsome

### What version of Node.js are you using?

v12.20.2

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/DidelisMiksas/tailwind-gridsome-jit

## Description

Can't get Tailwind JIT properly working using `gridsome-plugin-tailwindcss`
I know this isn't the plugins repo, but the plugin repo has issues tab disabled so I don't know where else to ask. 

I've installed the plugin as described (using compatibility build) and it works fine until I try to add `mode: "jit"` in `tailwind.config.js`. 

JIT itself does work, classes like `pt-[20px]` are being applied, but only after I manually save `tailwind.config.js` file. If I don't - add classes, save .vue file, reload browser - nothing happens until I save config file, then browser reloads and styles applies. Also, everything works fine if I delete classes - changes are applied automatically, but if classes are being added, then nothing happens. 

What am I missing?  Thanks a lot.
Here's my Tailwind config file 

```
module.exports = {
  mode: "jit",
  purge: ["src/**/*.{js,jsx,ts,tsx,vue}"],
};

gridsome.config.js

module.exports = {
  plugins: [
    {
      use: "gridsome-plugin-tailwindcss",
    },
    {
      use: "@gridsome/source-filesystem",
      options: {
        path: "src/pages/markdown/**/*.md",
        typeName: "Post",
      },
    },
    {
      use: "@gridsome/source-wordpress",
      options: {
        baseUrl: "http://vsbl-be.test", // required
        apiBase: "wp-json",
        typeName: "WordPress",
        perPage: 100,
        concurrent: 10,
      },
    },
  ],
  templates: {
    WordPressPost: "/:slug",
  },
};`

And package.json 

{
  "name": "...",
  "private": true,
  "scripts": {
    "develop": "gridsome develop",
    "explore": "gridsome explore",
    "build": "gridsome build"
  },
  "dependencies": {
    "@gridsome/source-filesystem": "^0.6.2",
    "@gridsome/source-wordpress": "^0.5.3",
    "@gridsome/transformer-remark": "^0.6.4",
    "gridsome": "^0.7.0"
  },
  "devDependencies": {
    "autoprefixer": "^9.8.6",
    "axios": "^0.21.1",
    "gridsome-plugin-tailwindcss": "^4.1.1",
    "postcss": "^7.0.36",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.2.4"
  }
}

**Comment by bradlc** [comment]
Hey @DidelisMiksas. Gridsome does not support PostCSS `dir-dependency` messages because it uses an old version of `postcss-loader`. You can work around this by setting the `TAILWIND_MODE` environment variable to `watch` as part of your `develop` script:

```diff
 "scripts": {
-  "develop": "gridsome develop",
+  "develop": "TAILWIND_MODE=watch gridsome develop",
   "explore": "gridsome explore",
   "build": "gridsome build"
 },
```

Check out the Tailwind docs for more information: https://tailwindcss.com/docs/just-in-time-mode#styles-don-t-update-when-saving-content-files

**Comment by paragchirde** [comment]
> ### What version of Tailwind CSS are you using?
> "tailwindcss": "^3.0.13"
> 
> ### What build tool (or framework if it abstracts the build tool) are you using?
> Gridsome
> 
> ### What version of Node.js are you using?
> v16.13.2
> 
> ### What browser are you using?
> Chrome
> 
> ### What operating system are you using?
> macOS M1 pro
> 
> ### Reproduction repository
> https://github.com/paragchirde/Tailwind-v3-gridsome-sample-repo
> 
> ### Describe your issue
> ## Description
>I just upgraded my project to Tailwind v3 and ran it on M1 (pro) mac. Only if I am saving the tailwind.config.js file or restarting the project, it reflects the change.
I also tried doing the follows:
A. Add a .env file with TAILWIND_MODE=watch
AND
B. adding the same in my dev script
gridsome develop TAILWIND_MODE=watch

Although this worked on my intel based mac but the same project is not working on new M1 mac.
