### ISSUE TITLE
Divide not working in dark mode

### ISSUE THREAD

**Issue by muarachmann** [tailwindlabs/tailwindcss#4933]
### What version of Tailwind CSS are you using?

2.0.2

### What build tool (or framework if it abstracts the build tool) are you using?

webpack

### What version of Node.js are you using?

16.4.2

### What browser are you using?

Chrome, Safari

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/fsU6Aw5AAt

### Describe your issue

Divide works well but however not in dark mode. My code
```
divide-y mb-5 divide-gray-100 dark:divide-green-500
```
Style keeps applying the `gray-100`

**Comment by adamwathan** [comment]
Hey! Just need to actually enable dark mode in your config:

https://play.tailwindcss.com/hyx7qN2Fhz?file=config

```diff
  const colors = require('tailwindcss/colors')
  
  module.exports = {
    mode: 'jit',
+   darkMode: 'media',
    theme: {
      extend: {
        colors: {
          sky: colors.sky,
          cyan: colors.cyan,
        },
      },
    },
    variants: {},
    plugins: [],
  }
```

**Comment by muarachmann** [comment]
Hi @adamwathan thanks for your prompt response, I do have darkMode enabled and all other stuffs work
like `dark:border-red-500` , `dark:hover-bg-red-500` etc, but this particular case doesn't work with config also I have added the following but no results
```
  divideColor: ['hover', 'focus'],
  divideStyle: ['hover', 'focus'],
```

<img width="394" alt="Screen Shot 2021-07-09 at 16 13 42" src="https://user-images.githubusercontent.com/16350814/125100618-37917b80-e0d1-11eb-93c4-edfc337a6c59.png">

**Comment by muarachmann** [comment]
@adamwathan Could this have to do with my version perhaps? I am on `^2.0.2` while the playground is `2.2.4`
