### ISSUE TITLE
Next js and Tailwind css - npm run build is failing

### ISSUE THREAD

**Issue by RajsuthanG** [tailwindlabs/tailwindcss#4945]
### What version of Tailwind CSS are you using?

^2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

Nextjs

### What version of Node.js are you using?

v14.16.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/timlrx/tailwind-nextjs-starter-blog

### Describe your issue

![error](https://user-images.githubusercontent.com/70739571/125242340-2c756000-e30a-11eb-83e9-b827fdb5223e.png)

When running npm run build when deploying the website on AWS, this is the error that I am getting.

Could anyone suggest a fix for this? or why is this happening?

**Comment by anhzf** [comment]
> ### What version of Tailwind CSS are you using?
> ^2.2.4
> 
> ### What build tool (or framework if it abstracts the build tool) are you using?
> Nextjs
> 
> ### What version of Node.js are you using?
> v14.16.1
> 
> ### What browser are you using?
> Chrome
> 
> ### What operating system are you using?
> macOS
> 
> ### Reproduction repository
> https://github.com/timlrx/tailwind-nextjs-starter-blog
> 
> ### Describe your issue
> ![error](https://user-images.githubusercontent.com/70739571/125242340-2c756000-e30a-11eb-83e9-b827fdb5223e.png)
> 
> When running npm run build when deploying the website on AWS, this is the error that I am getting.
> 
> Could anyone suggest a fix for this? or why is this happening?

yeah I've got this error too
just got this on the internet https://github.com/vercel/next.js/discussions/11938?sort=new#discussioncomment-841900

**Comment by bradlc** [comment]
Hey @RajsuthanG. Are you absolutely certain that **the AWS environment** is running Node.js v14.16.1? `Object.fromEntries` was added in Node.js v12 so it sounds like it might be using a version prior to that.

**Comment by RajsuthanG** [comment]
Hey @bradlc thanks for your feedback. Right after posting this issue I figured the node.js version issues. Once I changed it to version 12 and redeployed it, it successfully worked. Anyway Really appreciate your feedback. 🙏🏻
