### ISSUE TITLE
Vue-Nuxt Hot reloading JIT mode does not work via Nuxt Module comments

### ISSUE THREAD

**Issue by productfrontenddeveloper** [tailwindlabs/tailwindcss#4962]
### What version of Tailwind CSS are you using?

2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

nuxt 2.15.6

### What version of Node.js are you using?

node 14

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/nuxt-community/tailwindcss-module/issues/357#issue-904148760

### Describe your issue

Reproduction1: https://github.com/nuxt-community/tailwindcss-module/issues/357#issue-904148760

Reproduction2: https://github.com/nuxt-community/tailwindcss-module/issues/357#issuecomment-876986636

I also live in my own project.

**Comment by productfrontenddeveloper** [comment]
iam change scss to css and fixed my problem interested. scss very slow 
```
tailwindcss: {
    cssPath: '~/assets/styles/tailwind.css',
    viewer: false,
  },

```
![CleanShot_2021-07-14_at_11 03 13](https://user-images.githubusercontent.com/38668796/125586634-9e15fe30-e02a-41aa-85ec-618c13874521.png)

**Comment by productfrontenddeveloper** [comment]
cc: @atinux

**Comment by productfrontenddeveloper** [comment]
> Hey @productfrontenddeveloper. We have looked into the hot reload problem and tracked it down to an issue when using PostCSS 8 with Nuxt. You can see details and a reproduction of the issue here: https://github.com/nuxt/postcss8/issues/18 – this issue is not Tailwind-specific and happens with any CSS file.
> 
> 
> 
> Unfortunately we won't be able to fix this within the `tailwindcss` package, but there is a workaround if hot reloading is important to you:
> 
> 
> 
> 1. Don't use `@nuxtjs/tailwindcss`. Instead setup the [Tailwind PostCSS 7 compatibility build](https://tailwindcss.com/docs/installation#post-css-7-compatibility-build) manually and add it to your [`postcss` config](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-build#postcss)
> 
> 2. Set the `TAILWIND_MODE` environment variable to `watch` in your `dev` script. This is required because Nuxt uses an old version of `postcss-loader`. You can read more about this here: https://tailwindcss.com/docs/just-in-time-mode#styles-don-t-update-when-saving-content-files
> 
> 
> 
> Here's a basic setup for reference: https://github.com/bradlc/jit-nuxt
> 
> 
> 
> Going to close this because it isn't an issue with Tailwind, but hopefully the above is helpful!

cc: @atinux

**Comment by modex98** [comment]
there is a way but i don't know how to do it , we can register a listner on the reload (save) and we save the index.scss or any scss file this will force the browser to show changes
