### ISSUE TITLE
Storybook 2.2.4 breaks when JIT mode and Watch mode are both enabled.

### ISSUE THREAD

**Issue by codemile** [tailwindlabs/tailwindcss#4965]
### What version of Tailwind CSS are you using?

2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

create-react-app 4.0.3

### What version of Node.js are you using?

v14.15.4

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/codemile/storybook-tailwindcss-react

## Summary

If you have Storybook configured with TailwindCSS where JIT mode and also watch mode are enabled, then it will not compile `@layer` directives found in CSS.

Here is a sample CSS file:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
@tailwind screens;
@layer base {
    html,
    body {
        @apply block relative h-full m-0 p-0 overflow-hidden font-bold;
    }
}
```

Here is an image of the compile error, but look closely and you'll see the line above `@layer base` has output from the TailwindCSS compiler (I don't know if that means anything).

![image](https://user-images.githubusercontent.com/50146659/125448684-226fbaca-67cc-4c0b-aafa-ad82a68005e7.png)

If you run the configuration but just disable watch mode, then Tailwind compiles everything fine. Alternatively you can disable JIT mode and enable watch mode and it also works fine. It's the combination of JIT and Watch that seems to be an issue.

There could be other factors such as my setup for Storybook, and so I've created a sample repo that reproduces the problem.

```
git clone https://github.com/codemile/storybook-tailwindcss-react.git
cd storybook-tailwindcss-react
yarn install

## runs with watch mode but build fails
yarn storybook:broken

## runs without watch mode and build success
yarn storybook:works
```

This is a deceptive problem because when you're working on a Storybook project and run into this issue. It's not obvious that it's watch mode causing the problem and you spent a lot of time trying to fix your configuration.

**Comment by codemile** [comment]
Also, I forgot to mention that I was able to reproduce this problem by downgrading to `2.2.0` but when I degraded to `2.1.4` it seemed to go away.

**Comment by codemile** [comment]
Following up, I've now played with Storybook with JIT mode turned on and watch mode turn off, but it now seems that TailwindCSS is not updating CSS when Storybook hot reloads changes.

Has anyone got a proper setup for Storybook + Tailwind + React with latest version of Tailwind?

**Comment by sklawren** [comment]
I have the same issue with Gatsby. Storybook works fine, but Gatsby it throws this error.

**Comment by sklawren** [comment]
@codemile I made a simple repo to replicate it and it has now been fixed in the latest version of Tailwind.

https://github.com/tailwindlabs/tailwindcss/issues/5030#issuecomment-884708096

@adamwathan Once @codemile confirms this fix, you can close this ticket, too.

**Comment by codemile** [comment]
I'll try the latest today and let you know. Thanks!

**Comment by codemile** [comment]
@sklawren this like it's fixed! I'm so happy that I can work in Storybook with Tailwind JIT mode now!

Thank you everyone for the hard work.
