### ISSUE TITLE
HMR not working with vite

### ISSUE THREAD

**Issue by carlosbtlr** [tailwindlabs/tailwindcss#4970]
### What version of Tailwind CSS are you using?

v2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

vite 2.3.8

### What version of Node.js are you using?

v16.0.0

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/carlosbtlr/vite-react

### Describe your issue

HMR stops working when JIT mode is enabled.

**Comment by bradlc** [comment]
Hey @carlosbtlr. Update `vite` to the latest version and you should be good to go 👍 `npm install -D vite@latest`
