### ISSUE TITLE
JIT yields invalid grid-auto-rows value when using multiple values

### ISSUE THREAD

**Issue by t6d** [tailwindlabs/tailwindcss#4972]
### What version of Tailwind CSS are you using?

2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

Tailwind Playground v2.2.4

### What version of Node.js are you using?

n/a

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/CZI1wKZmam?file=css

### Describe your issue

Using

```css
@apply auto-rows[auto,min-content]
```

yields

```css
grid-auto-rows: auto,min-content
```

However, I'd expect it to produce

```css
grid-auto-rows: auto min-content
```

I was able to reproduce the issue with Tailwind 2.2.4 in the Playground: https://play.tailwindcss.com/CZI1wKZmam?file=css

**Comment by thesrs02** [comment]
Running into a similar issue but with grid-cols.

I can't seem to use multiple values for Grid Cols. 

This Works:
class="grid gap-4 grid-cols-[50%]"

This Doesn't: 
class="grid gap-4 grid-cols-[50% 50%]"

I don't know if I'm not doing it right or there's a different format that I need to use but I'll appreciate anyone pointing me into the right direction.=

**Comment by adamwathan** [comment]
Hey! This is fixed here:

https://github.com/tailwindlabs/tailwindcss/pull/5460

So you'll be able to write it like this:

```
<div class="auto-rows-[auto_min-content]">
```

This is targeted for the v3.0 release since that's what we're working on now but we may backport to 2.0, not sure. In the mean time if you want to play with it right away you can use the (unstable) insiders build:

```
npm install -D tailwindcss@insiders
```
