### ISSUE TITLE
JIT install  / usage documentation for those of us who don't truly 'get' Postcss :)

### ISSUE THREAD

**Issue by MattAppleton** [tailwindlabs/tailwindcss#4982]
### What version of Tailwind CSS are you using?

2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

"postcss": "^8.3.5", "postcss-cli": "^8.1.0",

### What version of Node.js are you using?

12.16.1

### What browser are you using?

n/a

### What operating system are you using?

macOS

### Reproduction repository

n/a

### Describe your issue

We have been using tailwind css for a few years — and love it! Postcss is generally a bit tricky to get right, but now with JIT we are struggling to get it to work when following the fairly sketchy introduction on the tailwind site.

This is more of a general query / request for clearer documentation. 

For example if I follow the intro video[ here](https://tailwindcss.com/docs/just-in-time-mode), Adam calls tailwind JIT with `@tailwindcss/jit` in his postcss file — If I try this I get `TypeError: Cannot read property 'theme' of undefined`

Whereas if I revert to my older postcss config

```
const cssnano = require('cssnano')({
    preset: 'default',
})

module.exports = {
  plugins: [
    require('postcss-import'),
    require('tailwindcss'),
    require('autoprefixer'),
    ...process.env.NODE_ENV === 'production'
            ? [cssnano]
            : []
  ]
}

```
JIT seems to work fine!

It would be great if there was a **sample repo available with a working JIT setup** with build and watch scripts, to help unpick stuff, ideally alongside simple, **idiot-proof install instructions** for JIT beginners / mid-level users...

Tailwind CSS is fantastic, and JIT seems extra-fantastic so far, thanks as ever for the great tools.

**Comment by adamwathan** [comment]
Yeah the video was recorded before we merged the JIT engine into core. All you need to do is follow the instructions as explained here for enabling it:

https://tailwindcss.com/docs/just-in-time-mode#enabling-jit-mode

Everything else about setting up Tailwind remains unchanged 👍🏻  The hard part about providing sample repos is there are so many different tools to integrate with and it would be hard to maintain all of those examples :/ But I think a super basic example just showing the Tailwind CLI setup would be a good idea, will make a note of it as a docs improvement we can make, thanks.

**Comment by sebastienbarre** [comment]
What is unclear to me from the documentation, is if `cssnano` is actually needed for production builds.
Isn't the JIT *only* production the Tailwind CSS classes being used?
Thank you
