### ISSUE TITLE
"max-w-8xl" is no longer available

### ISSUE THREAD

**Issue by horans** [tailwindlabs/tailwindcss#4985]
### What version of Tailwind CSS are you using?

v2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

vue-cli v5.0b2

### What version of Node.js are you using?

v16.3.0

### What browser are you using?

Chrome v91

### What operating system are you using?

Window 10 21H1

### Reproduction repository

https://github.com/tailwindlabs/tailwindcss.com/

### Describe your issue

The `max-w-8xl` class is used on official document page for content container, and it works as:

```css
.max-w-8xl {
    max-width: 90rem;
}
```

However it is no longer available as default, and it's not mentioned in `Max-Width` [section](https://tailwindcss.com/docs/max-width) as well.

**Comment by adamwathan** [comment]
Hey! There is no `max-w-8xl` class included by default, we've added it to our own config for the Tailwind site but the Tailwind site doesn't rely on just defaults.

Can see the extra values here:

https://github.com/tailwindlabs/tailwindcss.com/blob/master/tailwind.config.js#L163-L166

It's never been included as a default in the framework but you can add it yourself if needed 👍🏻
