### ISSUE TITLE
JIT does not watch for changes unless each file is listed (Laravel Mix)

### ISSUE THREAD

**Issue by mauriciomateus** [tailwindlabs/tailwindcss#4986]
### What version of Tailwind CSS are you using?

npm:@tailwindcss/postcss7-compat@^2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

Laravel Mix

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### Reproduction repository

No repo, code snippet below

### Describe your issue

Basically, you need to write the file name of each file to watch. Using '\*\*' and '\*' for directories and '\*' for the filename does not work.

```
mode : 'jit',
    purge: [
//Next line works
         './resources/purge-markup/purge.html',
//Next lines do not work
        './resources/**/*.{js,vue,blade.php}',
        // './resources/views/*/*.blade.php',
        // './resources/views/*.blade.php',
        // './resources/views/templates/some-template.blade'
//Next line works
        'resources/views/templates/full-template-file-name.blade.php',
    ],

```

Thanks in advance

**Comment by neupauer** [comment]
Hey @mauriciomateus 👋

In your path patterns is probably missing `*` character.  The `purge` config uses `glob` to  match files.

```js
purge: [
    './resources/**/*.{js,vue,blade.php}'
],
```

https://tailwindcss.com/docs/optimizing-for-production#purge-css-options

**Comment by adamwathan** [comment]
Hey! Please open a new issue and include a real reproduction, it's required for us to troubleshoot problems. 

Thanks ❤️
