### ISSUE TITLE
mode: 'jit' - "@apply is not supported within nested at-rules like @screen" 

### ISSUE THREAD

**Issue by Florian-crg** [tailwindlabs/tailwindcss#4995]
### What version of Tailwind CSS are you using?

2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

nextjs 11

### What version of Node.js are you using?

v12.22.1

### What browser are you using?

N/A

### What operating system are you using?

macOS 

### Reproduction repository

--

### Describe your issue

Enabling JIT doesn’t allow us to use this syntax : 
```

.class {
  @apply bg-white
}

  @screen md {
    @apply bg-black
  }
}

```

The following error appear 
`Syntax error: /path/file.css @apply is not supported within nested at-rules like @screen. We suggest you write this as @apply md:bg-black instead.`

**Comment by adamwathan** [comment]
Hey! Yep not a bug, explicitly thrown error with instructions on what you should do instead. Tailwind doesn't understand nested CSS, so if you want to nest you should make sure your CSS gets un-nested before Tailwind sees it.

Here are our docs on nesting:

https://tailwindcss.com/docs/using-with-preprocessors#nesting

Alternatively just do what the error says:

```
.class {
  @apply bg-white md:bg-black;
}
```

**Comment by Florian-crg** [comment]
It works for tailwindcss classes, what about native css in my @screen ?

For exemple : 
```

@screen md {
  .thumb:hover {
    transform: scale(1.02);
    background-color: rgba(255, 255, 255, 0.08);
   min-height: 36px;
  }
}
```

**Comment by evenfrost** [comment]
@adamwathan This happens as well with PostCSS nesting enabled (`nesting-rules: true` in `postcss-preset-env` config) when `jit` is enabled in Tailwind config. When `jit` is disabled, everything processes correctly, and the error is not thrown.

**Comment by jhealey5** [comment]
@adamwathan this seems awfully awkward, is there no way to get this to work with JIT? 

Did you refer to un-nesting before tw as in it would fix this? Are you able to provide an example that would do that if so please? I've been trying bunch of different configurations to get this to work without using the `@apply md:class` syntax but no luck.

**Comment by jaoxford** [comment]
Also just experienced this. 

Something like this used to work in older versions of tailwind / postcss.

It's especially useful when you have a lot of things targeting the medium breakpoint and above and you don't want to keep writing `md:XYZ`

```scss
    @media(min-width: theme('screens.md')) {
      @apply w-full;
      @apply fixed;
      @apply z-50;
      @apply top-0;
      @apply bg-white;
      @apply left-0;
      @apply overflow-x-hidden;
      @apply overflow-y-hidden;
      @apply pt-0;
      @apply md:pt-4;
      @apply border-r-2;
      @apply border-secondary-grey;
      @apply h-full;
      @apply w-60;
      @apply block;
    }
```

**Comment by Nagell** [comment]
For me it was about postcss config and a 'bug' in tailwind
and something like this was a solution:

```js
let postcss = require('postcss')

module.exports = {
  plugins: [
    {
      postcssPlugin: 'grouped',
      Once(root, { result }) {
        return postcss([
          require('postcss-import'),
          require('postcss-mixins'),
          require('postcss-simple-vars'),
        ]).process(root, result.opts)
      },
    },
    require('tailwindcss'),
    require('postcss-nested'),
    require('autoprefixer'),
  ],
}
```

Grabbed from: https://giters.com/tailwindlabs/tailwindcss/issues/3931

I hope it will help. Good luck guys!
