### ISSUE TITLE
JIT + dark + arbitrary value is not working

### ISSUE THREAD

**Issue by phuctm97** [tailwindlabs/tailwindcss#5006]
### What version of Tailwind CSS are you using?

v2.2.2

### What build tool (or framework if it abstracts the build tool) are you using?

Webpack

### What version of Node.js are you using?

v14.17.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/bQUf4HyGrG

### Describe your issue

When using `darkMode: 'class'`, `dark:text-[rgb(217,217,217)]` won't work. If I define the color in theme then use the color name, then it works.

Reproduce: 
Search for line with `dark:dop-text-[rgb(217,217,217)]` you will see there is no effect.
https://play.tailwindcss.com/bQUf4HyGrG

Not sure why it is not working either. The editor suggested correctly but there is no class generated.

**Comment by peteretelej** [comment]
interestingly, works if you specify the hex, or name, but not rgb/a
![image](https://user-images.githubusercontent.com/2271973/126066851-81c5b406-f13f-474a-8961-e3e2f40b5bc4.png)

![image](https://user-images.githubusercontent.com/2271973/126066862-0260bc88-d5d2-4853-b97a-4344e780f453.png)

**Comment by FallDownTheSystem** [comment]
It seems to work if you drop the dop- prefix, so I guess some kind of issue with prefixes and JIT.

**Comment by phuctm97** [comment]
Seem like the issue is because of these patterns are missing `rgb(...)`:

https://github.com/tailwindlabs/tailwindcss/blob/a23065353a4c726d4067e43b92e4c4887be548aa/src/jit/lib/expandTailwindAtRules.js#L9-L16

**Comment by Noitidart** [comment]
Hi there,

This is not working for ring opacity on text inputs. There is a Stackoverflow topic here - https://stackoverflow.com/a/71168939/1828637

A Tailwind Play shows this is still an issue - https://play.tailwindcss.com/Tv8lkLkkLn
