### ISSUE TITLE
Cannot read property 'theme' of undefined | ViteJS + React + Tailwind JIT

### ISSUE THREAD

**Issue by theMarinac** [tailwindlabs/tailwindcss#5009]
### What version of Tailwind CSS are you using?

v2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

vite: 2.4.2, postcss: 8.3.5, postcss-cli: 8.3.1, react: 17.0.0

### What version of Node.js are you using?

v14.15.1

### What browser are you using?

Chrome

### What operating system are you using?

Linux Ubuntu 20.04 LTS

### Reproduction repository

https://github.com/theMarinac/vite-react-tailwind_jit

### Describe your issue

When trying to run 
```bash
npm run dev
```
Vite starts properly but the tailwind throws error
```bash
File: /path-to-project/vite-react-tailwind_jit/src/index.css
  at _default (/path-to-project/vite-react-tailwind_jit/node_modules/tailwindcss/lib/lib/substituteScreenAtRules.js:16:5)
  at /path-to-project/vite-react-tailwind_jit/node_modules/@tailwindcss/jit/src/index.js:50:11
  at LazyResult.runOnRoot (/path-to-project/vite-react-tailwind_jit/node_modules/postcss/lib/lazy-result.js:339:16)
  at LazyResult.runAsync (/path-to-project/vite-react-tailwind_jit/node_modules/postcss/lib/lazy-result.js:391:26)
  at LazyResult.async (/path-to-project/vite-react-tailwind_jit/node_modules/postcss/lib/lazy-result.js:221:30)
  at LazyResult.then (/path-to-project/vite-react-tailwind_jit/node_modules/postcss/lib/lazy-result.js:206:17)
```

**Comment by bradlc** [comment]
Hey @theMarinac. It looks like you are using `@tailwindcss/jit`, which is an old package that is no longer required. You should uninstall `@tailwindcss/jit` and use `tailwindcss` instead:

```diff
  module.exports = {
    plugins: {
-     '@tailwindcss/jit': {},
+     tailwindcss: {},
      autoprefixer: {},
    }
  }
```

Also, you should configure the `purge` option in your `tailwind.config.js` file so that the CSS can be generated correctly. For example you might configure it like this:

```js
module.exports = {
  mode: "jit",
  purge: ["./src/**/*.jsx"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
```

Check out the documentation for more information: https://tailwindcss.com/docs/just-in-time-mode#enabling-jit-mode

**Comment by alvis** [comment]
@bradlc Thx for the tips. Yes, I can confirm that the problem is rooted from the now depreciated `@tailwindcss/jit` package.
I think we should mark the old package as depreciated so that it will give a warning and people will know how to resolve the issue straight ahead.
