### ISSUE TITLE
JIT purge does not exclude node_modules

### ISSUE THREAD

**Issue by josh-attwood** [tailwindlabs/tailwindcss#5014]
### What version of Tailwind CSS are you using?

2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

postcss 8.3.5, webpack 5.21.2

### What version of Node.js are you using?

16.5.0

### What browser are you using?

Chrome, Safari

### What operating system are you using?

MacOS

### Reproduction repository

N/A

### Describe your issue

I was having an issue with JIT's purge in that it wasn't purging unused classes and was allowing !important classes to sneak in and override a lot of the styling.

After a fair bit of debugging it seems that JIT's purge does not exclude node_modules from the files it is watching when using a fairly wide reaching wildcards.

I had copied this from my PostCSS file which usually ignores node_modules so isn't a problem. With JIT's purge it includes node_modules in its content watch so seems to look at it's own files which is obviously not very helpful.

`'./**/*.html',
                './**/*.php',
                './**/*.twig',
                './**/*.vue',
                './**/*.jsx',
                './**/*.js',],`

It would be great if we could get node_modules excluded for an easier migration!

**Comment by ianhernandez** [comment]
Hey Josh why not just be more specific in your paths?

Although it sounds like your having completely different issues have a look at this point:
https://tailwindcss.com/docs/just-in-time-mode#styles-rebuild-in-an-infinite-loop

**Comment by josh-attwood** [comment]
Hey Ian, that’s what I have done for the minute and it is now working perfectly. I guess this is more of a feature request than anything. Other tools like purgeCSS ignore node_modules so would be great to bring it in line, especially to smooth out the migration.

**Comment by jamesamuel** [comment]
I am experiencing the same issue. If node_modules is present within the directory, TW is scanning those files.

Currently using TW 2.2.4

**Comment by Morton78** [comment]
I am also encountering this issue. Don't know why its happening!!

**Comment by Triloworld** [comment]
I don't see that will help - If I need I can include some node_modules libraries, after patch It won't have that option
Solution:
### First
> './X/**/*.html', './X/**/*.php', './X/**/*.twig', './X/**/*.vue', './X/**/*.jsx', './X/**/*.js',],

Using "**" is expected to use any folder, even:
-  .git
-  .history
-  .github

Or any package like:
-  vendors (PHP)
-  node_modules (JS)

And important one like:
-  cache (Using to get web builder class)
-  db (to scan sql files)

### Second:
Maybe one option for something like `Include node_modules into scanned directories` 
By default option disabled.

**Comment by thecrypticace** [comment]
Hey, thanks for the report! This is expected behavior. When you say something like `./**/*.html` you are asking Tailwind CSS to scan every single directory and look for HTML files. Additionally, Tailwind CSS may even _need_ to scan content inside `node_modules` when using certain libraries if they're using Tailwind classes — for instance if your company has a design system and it is included as a separate package present in `node_modules`.  If you want Tailwind CSS to not scan those files you will need to use more specific content paths.

**Comment by phillt** [comment]
Looks like we're using glob pattern here. You should be able to just do this:

`!./**/node_modules/**`

It seems to be working on my config. Include that pattern along your paths.
