### ISSUE TITLE
rotate-* doesn't work when transformOrigin=false and mode != 'jit'

### ISSUE THREAD

**Issue by antoinebrault** [tailwindlabs/tailwindcss#5019]
### What version of Tailwind CSS are you using?

2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

angular 12.x

### What version of Node.js are you using?

14.17.x

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://play.tailwindcss.com/pWv0EW5Wnr

### Describe your issue

generated styles are in the wrong order when transformOrigin=false for transform and rotate-* styles.

![image](https://user-images.githubusercontent.com/852552/126340092-91b5ed3f-83da-465c-9cef-4b7d76ab5ab6.png)

**Comment by adamwathan** [comment]
Hey! Should be fixed in v2.2.5, test it out and please close if so 👍🏻

**Comment by antoinebrault** [comment]
thx appreciate the quick fix!
