### ISSUE TITLE
Tailwind 2.2 introduced error `@layer base` is used but no matching  `@tailwind base` directive is present

### ISSUE THREAD

**Issue by sklawren** [tailwindlabs/tailwindcss#5030]
### What version of Tailwind CSS are you using?

2.2.x

### What build tool (or framework if it abstracts the build tool) are you using?

Gatsby 2.32.9

### What version of Node.js are you using?

v12.8.3 and v14.17.3

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/sklawren/gatsby-tailwind-issue

### Describe your issue

As reported on [Discord](https://discord.com/channels/486935104384532500/486935482656227339/857260936396800050)

Gatsby throws the following error when developing locally after updating to Tailwind 2.2.x and using JIT.
```
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Module build failed (from ./node_modules/gatsby-plugin-postcss/node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(5:1) /Users/steven/Development/project/src/styles/tailwind.css `@layer base` is used but no matching
 `@tailwind base` directive is present.

  3 | @tailwind utilities;
  4 |
> 5 | @layer base {
    | ^
  6 |     html {
  7 |         @apply bg-white text-gray-800;
```
If I  use`TAILWIND_MODE=watch`, it happens immediately on build. If I do not, it happens as soon as I save any file in the src folder (js, ts, tsx, css, anything).

When this happens, the web page turns black. I have to kill and restart the Gatsby process.

I have created a minimal reproduction repository so you can see this issue for yourself.

Use `npm start` and once it's running, try changing anything in the `pages/index.jsx` file or the `styles/tailwind.css` file and you'll see the above crash.

Use `npm run watch` and it will crash at the end of the build process.

This does not happen in Tailwind 2.1.4. It only started after the 2.2.0 release.

It also happens in NextJS, and some people are reporting this issue with Storybook.

**Comment by adamwathan** [comment]
Hey! Can you test v2.2.5 and see if this is resolved?

**Comment by sklawren** [comment]
@adamwathan Updated to latest 2.2.6 and that fixed it! THANK YOU!
