### ISSUE TITLE
2.2.0 release note - invalid link and header

### ISSUE THREAD

**Issue by michalbundyra** [tailwindlabs/tailwindcss#5031]
### What version of Tailwind CSS are you using?

2.2.0

### What build tool (or framework if it abstracts the build tool) are you using?

na

### What version of Node.js are you using?

na

### What browser are you using?

na

### What operating system are you using?

na

### Reproduction repository

na

### Describe your issue

https://github.com/tailwindlabs/tailwindcss/releases/tag/v2.2.0

in the new features list we have link:

https://github.com/tailwindlabs/tailwindcss/releases/tag/v2.2.0#before-and-after-variants

with text: "Before and after variants"

but the actual section below has header:

> Before and after pseudo-element variants

so the link should be:

https://github.com/tailwindlabs/tailwindcss/releases/tag/v2.2.0#before-and-after-pseudo-element-variants

**Comment by adamwathan** [comment]
Fixed, thanks.
