### ISSUE TITLE
Tailwind is not regenerating styles on Eleventy build (only in development)

### ISSUE THREAD

**Issue by kylesloper** [tailwindlabs/tailwindcss#5036]
### What version of Tailwind CSS are you using?

2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

Eleventy

### What version of Node.js are you using?

14.15.1

### What browser are you using?

Chredge

### What operating system are you using?

Win 10

### Reproduction repository

https://github.com/kylesloper/tailwind-003

### Describe your issue

I am using Eleventy and Tailwind to build my site. In production everything works as it should including Tailwind, however in development, styles added are not generated by tailwind and added to `_output.css`.

Here are my npm scripts:

```
    "build": "rm -rf .www && set NODE_ENV=production&&tailwindcss -i ./styles/tw.css -c ./styles/tailwind.config.js -o ./styles/_output.css && set ELEVENTY_ENV=production&&eleventy",
    "start": "rm -rf .www && eleventy --serve & tailwindcss -i ./styles/tw.css  -c ./styles/tailwind.config.js -o ./styles/_output.css --watch",
```

If you need anymore information/examples on the situation then feel free to ask.

Thanks for your help.

**Comment by jlangeveld** [comment]
Start script has a single & between eleventy and tailwind.
Can't check your repo - github shows 404...

**Comment by bradlc** [comment]
Can you make your reproduction repository public please @kylesloper?

**Comment by kylesloper** [comment]
Hello there. The issue has been resolved, I will post my solution in the coming days.

Thanks for your help.

**Comment by bradlc** [comment]
Brilliant, I'll close this then. Glad you found a solution! 💪 Definitely feel free to share your solution here though, in case it's useful for others 👍

**Comment by jugheadjones10** [comment]
Hi @kylesloper can you post how you figured it out? I’m facing a similar problem…

**Comment by kylesloper** [comment]
> Hi @kylesloper can you post how you figured it out? I’m facing a similar problem…

Hi there, my team eventually decided this Eleventy x Tailwind setup is too unstable and a little frankenstein like. We are now using a super cool project called Slinkity. It's currently in early alpha but after conversations with its owner, the Eleventy, Vite and Tailwind setup is production ready and works like a charm.

I recommend you check it out.
https//github.com/Slinkity/slinkity
