### ISSUE TITLE
Shadow from modal inherited on inputs inside that modal

### ISSUE THREAD

**Issue by SimonPrague** [tailwindlabs/tailwindcss#5042]
### What version of Tailwind CSS are you using?

2.2.6

### What build tool (or framework if it abstracts the build tool) are you using?

vue-cli

### What version of Node.js are you using?

latest

### What browser are you using?

Chromium

### What operating system are you using?

Fedora

### Describe your issue

Everything work fine but after the latest release things got weir all over our project. We have pretty standard installation of Tailwind and CSS so I thought I should report this.

We had to go back to 2.2.4 so the problem might be already at 2.2.5

This is what's happening:

![Screenshot from 2021-07-22 13-12-09](https://user-images.githubusercontent.com/47515740/126630910-3de6612a-d050-4a80-836a-0b489243ae20.jpg)

When I focus on element in modal it suddenly inherits a `shadow-xl` style. Which is on parent modal. It's pretty weird.

![Screenshot from 2021-07-22 13-12-09 (1)](https://user-images.githubusercontent.com/47515740/126631313-a964eeb0-32c3-496b-b345-d23aa60e26e4.jpg)

**Comment by rainerborene** [comment]
I think this is related to #5039 and recent performance changes which broke some stuff.

**Comment by adamwathan** [comment]
Hey! Any reason you deleted the reproduction field rather than providing one? That makes it extremely hard for me to be able to help.

**Comment by SimonPrague** [comment]
I'm really sorry I'm not able to provide a reproduction repo. If this problem lasts longer than a week I will find the time and do this for you. Our startup is growing too fast and things are pretty intense so I apologize for not having the time to set this up. I felt that it's work reporting even without that.

**Comment by adamwathan** [comment]
@SimonPrague I understand — can you at least tell me what classes are on the input and whether or not you have the forms plugin installed?

**Comment by adamwathan** [comment]
I am trying to recreate the problem not but seeing it, what am I doing differently than you?

![image](https://user-images.githubusercontent.com/4323180/126774319-99373510-3ea7-4b38-88d7-c3d40b825751.png)

**Comment by adamwathan** [comment]
Reverted the main piece of the changes that cause this stuff for v2.2.7, check that out and see if it helps. Hopefully can resolve the underlying issues and bring these improvements back soon.

**Comment by mxlje** [comment]
Hi, I have the same problem and have reproduced it with `v2.2.6` here: https://codepen.io/mxlje/pen/KKmbRGZ

While it seems fixed in `v2.2.7`, the underlying issue actually comes from tailwind-forms. As you can see in the example, the input itself doesn’t have any classes applied except for the default styles that come from tailwind-forms.

The example was created with tailwind `v2.2.6` and tailwind-forms `v0.3.3`.
