### ISSUE TITLE
Enabling JIT breaks sourcemaps in webpack + PostCSS project

### ISSUE THREAD

**Issue by evenfrost** [tailwindlabs/tailwindcss#5043]
### What version of Tailwind CSS are you using?

2.2.6

### What build tool (or framework if it abstracts the build tool) are you using?

webpack 5.46.0, postcss 8.3.6

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### Reproduction repository

⠀

### Describe your issue

When using Tailwind's JIT option for processing PostCSS in the webpack project, source maps are not being shown in the Chrome DevTools (but still generated in the output CSS file). The value of `devtool` option in the webpack config doesn't matter, the result is the same.

With config like this:
```
  purge: [
    './src/**/*.tsx',
  ],
  mode: 'jit',
```
Source maps don't get processed:
![Screenshot from 2021-07-22 16-36-57](https://user-images.githubusercontent.com/3055750/126648794-ffeed31f-df8c-4cf5-a6b7-20c2ac834799.png)

When disabling the JIT option:
```
  purge: false,
```
Source maps are being processed properly, and the original file is shown in Chrome DevTools:
![Screenshot from 2021-07-22 16-30-51](https://user-images.githubusercontent.com/3055750/126649229-f6154cf6-42b1-4b5f-9d6b-35366f31de8f.png)

I'll bootstrap a repro repo if a more thorough investigation is needed.

**Comment by halkhalil** [comment]
**here is a workaround until JIT and sourcemaps work ( it is breaking as of v2.2.7) **

- need two config files (tailwind.config.js) one file with JIT enabled the other disabled. 
- tailwind.css <  @tailwind components; @tailwind utilities; 
- styles.scss < @tailwind base;  import xyz // and Load SCSS via globing / scss can have  @apply 
- and run two tasks to process style sheets

`  return src(${options.paths.src.css}/tailwind.css)
    .pipe(postcss([
      require('postcss-import'),
      tailwindcss(options.config.tailwindjs)
    ]))`

`  return src(${options.paths.src.css}/**styles.scss**)
    .pipe(sourcemaps.init()) 
    .pipe(sass().on('error', sass.logError))
    .pipe(postcss([
      tailwindcss(options.config.tailwindnoJIT)
    ]))`

and voila sourcemaps are working working with JIT and  is blazing fast, styles sheets small as well :)

**Comment by evenfrost** [comment]
@adamwathan FYI, sourcemaps still not working with JIT enabled in `2.2.7`.
![Screenshot from 2021-08-04 11-53-26](https://user-images.githubusercontent.com/3055750/128153175-4e19701c-9d06-4f4f-82f3-832caf38a382.png)
![Screenshot from 2021-08-04 11-55-11](https://user-images.githubusercontent.com/3055750/128153176-674af11f-e275-452f-a526-09a138269358.png)

**Comment by donaldhubduck** [comment]
Same here. Source maps won't work in JIT mode. I just tried to make a new simple project with webpack and tailwind just to try it out. If I dont use JIT then the source maps works. If I use the mode JIT then the source maps wont work.

I use Tailwind together with some CMS and some elements I cant add css classes to, so I have to use @apply to style those elements.

I added some screenshots down below to show my project and how it looks in firefox dev tools.


**working source maps in firefox dev tools (JIT disabled)**
![working source maps in firefox dev tools (JIT disabled)](https://user-images.githubusercontent.com/43706427/133685149-91b845ed-1da5-447d-8839-5bf691f76a86.jpg)


**broken source maps in firefox dev tools (JIT enabled)**
![broken source maps in firefox dev tools (JIT enabled)](https://user-images.githubusercontent.com/43706427/133684908-94e542da-65cb-4b63-b438-b4a66faed743.jpg)


**error message in firefox dev tools (JIT enabled)**
![error message in friefox dev tools (JIT enabled)](https://user-images.githubusercontent.com/43706427/133684978-95795b5b-c1b0-4f89-bdba-0325276a0ab1.jpg)


**how I import tailwind files to my css**
![how I import tailwind to my css](https://user-images.githubusercontent.com/43706427/133685039-c4586cf2-b47f-42ef-8745-d454795f1857.jpg)


**index.js in vscode**
![index js in vscode](https://user-images.githubusercontent.com/43706427/133685082-0343fd06-e715-4def-84b2-47f84f9374fa.jpg)


**typography.css in vscode**
![typography css in vscode](https://user-images.githubusercontent.com/43706427/133685119-44ce11bf-a043-4ec9-8410-0b859f9cbfe4.jpg)

**Comment by fishmi** [comment]
Same here.
Is there any prospect of fixing this problem. We would not like to do without the JIT, because we now also use arbitrary value support that only works with the JIT.
But working without SourceMap is also tedious.

**Comment by Frulko** [comment]
Same here too,
I tried some different configurations with different builder or method but I not found any solution and my comprehension about how jit works with sourcemaps is so limited that i cannot deep dive into code to inspect and get a solution to help :(

**Comment by Xeevis** [comment]
I believe issue with sourcemaps stems from lack of any relevant content when `@apply` is used, PostCSS probably thinks they are just empty rules and won't generate any mappings. Adding any regular css rule or even a simple comment will generate sourcemaps correctly.

```html
<div class="with-sourcemap"></div>
<div class="with-another-sourcemap"></div>
<div class="no-sourcemap-here"></div>
```

```pcss
.with-sourcemap {
  background-color: red;
  @apply h-4 w-4 bg-green-500;
}

.with-another-sourcemap {
  /* sourcemap will work here too */
  @apply h-4  w-4 bg-red-500;
}

.no-sourcemap-here {
  @apply h-4  w-4 bg-black;
}
```

![image](https://user-images.githubusercontent.com/5835044/151717106-64a76fe6-8f28-4052-95e3-2ade4f71c1d4.png)
![image](https://user-images.githubusercontent.com/5835044/151717114-b88e7e6d-0597-4624-9758-0ec267fc7752.png)
![image](https://user-images.githubusercontent.com/5835044/151717126-b132a0be-c401-43df-9543-24995b6efb9f.png)

**Comment by MichaelRushton** [comment]
Source maps are also not working properly in 3.0.19.

`src/css/app.css`
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

`src/js/app.js`
```
import '../css/app.css'
```

`webpack.config.js`
```
const path = require('path')
const MiniCssExtractPlugin = require('mini-css-extract-plugin')
const CssMinimizerPlugin = require('css-minimizer-webpack-plugin')

module.exports = (env, argv) =>
{

  process.env.NODE_ENV = argv.mode

  return {
    devtool: 'source-map',
    entry: {
      app: '/src/js/app.js'
    },
    module: {
      rules: [
        {
          test: /\.js$/,
          exclude: /node_modules/,
          use: 'babel-loader'
        },
        {
          test: /\.css$/,
          exclude: /node_modules/,
          use: [
            MiniCssExtractPlugin.loader,
            'css-loader',
            'postcss-loader',
          ],
        }
      ]
    },
    optimization: {
      minimize: true,
      minimizer: [
        `...`,
        new CssMinimizerPlugin(),
      ],
    },
    output: {
      chunkFilename: '[name].[contenthash].js',
      clean: true,
      filename: '[name].js',
      path: path.resolve(__dirname, 'public/dist')
    },
    plugins: [
      new MiniCssExtractPlugin({filename: '[name].css'})
    ]
  }

}
```

The generated `public/dist/app.css.map` includes this section:
```
"sources":["webpack://@test/test/./src/css/app.css","webpack://@test/test/./src/css/%3Cinput%20css%20doRbU6%3E","webpack://@test/test/<no source>"]
```

Using Chrome DevTools all the Tailwind CSS rules show as `<no source>:1`
