### ISSUE TITLE
TypeError: ...Object.frontEntries is not a function

### ISSUE THREAD

**Issue by tpush** [tailwindlabs/tailwindcss#5052]
### What version of Tailwind CSS are you using?

2.2.6

### What build tool (or framework if it abstracts the build tool) are you using?

nodejs

### What version of Node.js are you using?

v10.19.0

### What browser are you using?

Brave

### What operating system are you using?

Debian Linux

### Reproduction repository

tpush/issues-tailwindcss-TypeError

### Describe your issue

Read, 
README.md
To know more.

**Comment by adamwathan** [comment]
Hey! Tailwind requires node v12 or higher which include this method, you must be on an old version of node.
