### ISSUE TITLE
tailwindcss build failed

### ISSUE THREAD

**Issue by nothinghalosix** [tailwindlabs/tailwindcss#5053]
### What version of Tailwind CSS are you using?

2.2.6

### What build tool (or framework if it abstracts the build tool) are you using?

node

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Firefox

### What operating system are you using?

macOS 11.5

### Reproduction repository

company private account, not allowed this time

### Describe your issue

my build process gives me an error, other projects too

it is a WP application
**build command** -> npx tailwindcss-cli@latest build themes/nothing/css/tailwind.css -o themes/nothing/scss/partials/tailwind-styles.scss -c themes/nothing/tailwind.config.js

**error**
npx: installed 136 in 17.378s
[deprecation] Running tailwindcss without -i, please provide an input file.
(node:74080) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at matchUtilities (/Users/edv004/.npm/_npx/74080/lib/node_modules/tailwindcss-cli/node_modules/tailwindcss/lib/util/processPlugins.js:131:37)
    at /Users/edv004/.npm/_npx/74080/lib/node_modules/tailwindcss-cli/node_modules/tailwindcss/lib/util/createUtilityPlugin.js:30:7
    at /Users/edv004/.npm/_npx/74080/lib/node_modules/tailwindcss-cli/node_modules/tailwindcss/lib/util/processPlugins.js:99:5
    at Array.forEach (<anonymous>)
    at _default (/Users/edv004/.npm/_npx/74080/lib/node_modules/tailwindcss-cli/node_modules/tailwindcss/lib/util/processPlugins.js:93:11)
    at /Users/edv004/.npm/_npx/74080/lib/node_modules/tailwindcss-cli/node_modules/tailwindcss/lib/processTailwindFeatures.js:64:54
    at LazyResult.runOnRoot (/Users/edv004/.npm/_npx/74080/lib/node_modules/tailwindcss-cli/node_modules/tailwindcss/peers/index.js:61625:16)
    at LazyResult.runAsync (/Users/edv004/.npm/_npx/74080/lib/node_modules/tailwindcss-cli/node_modules/tailwindcss/peers/index.js:61677:26)
    at LazyResult.async (/Users/edv004/.npm/_npx/74080/lib/node_modules/tailwindcss-cli/node_modules/tailwindcss/peers/index.js:61507:30)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:74080) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:74080) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by adamwathan** [comment]
Impossible to help without a reproduction sorry. The issue template explicitly explains what to do when your project is private:

> A public GitHub repo that includes a minimal reproduction of the bug. Please do not link to your actual project, what we need instead is a minimal reproduction in a fresh project without any unnecessary code. **This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways.** Unfortunately we can't provide support without a reproduction, and your issue will be closed and locked with no comment if this is not provided.

Please open a new issue and include a reproduction.

**Comment by nothinghalosix** [comment]
sorry.

open new issue with link to gitlab repo
