### ISSUE TITLE
JIT resolveDefaultsAtRules crash: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by dfalling** [tailwindlabs/tailwindcss#5088]
### What version of Tailwind CSS are you using?

2.2.7

### What build tool (or framework if it abstracts the build tool) are you using?

Vite

### What version of Node.js are you using?

v15.5.1

### What browser are you using?

Firefox Developer Edition

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/dfalling/tailwind_bug_demo

### Describe your issue

Since Tailwind @2.2.6, my CSS has failed to compile. I know it compiled fine in @2.2.4, but didn't try in @2.2.5.

The exception is
```
9:41:47 PM [vite] Internal server error: Cannot read property 'filter' of undefined
  Plugin: vite:css
  File: /Users/dfalling/Code/tailwind-troubleshooting/style.css
      at /Users/dfalling/Code/tailwind-troubleshooting/node_modules/tailwindcss/lib/jit/lib/resolveDefaultsAtRules.js:37:60
      at Array.map (<anonymous>)
      at Root.map (/Users/dfalling/Code/tailwind-troubleshooting/node_modules/postcss-selector-parser/dist/selectors/container.js:347:23)
      at Processor.func (/Users/dfalling/Code/tailwind-troubleshooting/node_modules/tailwindcss/lib/jit/lib/resolveDefaultsAtRules.js:36:20)
      at Processor._runSync (/Users/dfalling/Code/tailwind-troubleshooting/node_modules/postcss-selector-parser/dist/processor.js:102:26)
      at Processor.transformSync (/Users/dfalling/Code/tailwind-troubleshooting/node_modules/postcss-selector-parser/dist/processor.js:171:17)
      at extractElementSelector (/Users/dfalling/Code/tailwind-troubleshooting/node_modules/tailwindcss/lib/jit/lib/resolveDefaultsAtRules.js:45:47)
      at /Users/dfalling/Code/tailwind-troubleshooting/node_modules/tailwindcss/lib/jit/lib/resolveDefaultsAtRules.js:78:30
      at /Users/dfalling/Code/tailwind-troubleshooting/node_modules/tailwindcss/lib/jit/processTailwindFeatures.js:64:50
      at /Users/dfalling/Code/tailwind-troubleshooting/node_modules/tailwindcss/lib/jit/index.js:25:56
```

I boiled it down to a [really slim example](https://github.com/dfalling/tailwind_bug_demo):
```css
@layer components {
  .rainbow-link {
    &:hover::after {
      @apply border border-purple-700 border-b;
    }
  }
}

.fc-dayGridMonth-button {
  &.fc-button-active {
    @apply rainbow-link;
  }
}
```

If I get rid of different bits of the complexity there (`@layer`, `&:hover:;after`, `@apply border...`) it will compile fine.

**Comment by adamwathan** [comment]
Hey! Make sure you use our official nesting plugin that wraps `postcss-nested`:

https://tailwindcss.com/docs/using-with-preprocessors#nesting

That should resolve this for you.

**Comment by dfalling** [comment]
Thanks, that got it! I was using `postcss-nested` which worked before 2.2.5, so I guess that's no longer an adequate solution for Tailwind?

**Comment by adamwathan** [comment]
Ever since they moved to the visitor API there have been a lot of little issues because there's no longer any guarantee about the order that the plugin runs in. So what is ultimately happening is that you are unknowingly feeding CSS into Tailwind that is still nested, and Tailwind doesn't understand nested CSS properly. Our wrapper mostly just guarantees the nesting is processed first so Tailwind only ever sees flat CSS 👍🏻

**Comment by dfalling** [comment]
Awesome, thanks for the explanation and help!
