### ISSUE TITLE
postcss/nesting breaks modern es-module setups like sveltekit

### ISSUE THREAD

**Issue by benbender** [tailwindlabs/tailwindcss#5089]
### What version of Tailwind CSS are you using?

2.2.7

### What build tool (or framework if it abstracts the build tool) are you using?

sveltekit, vite

### What version of Node.js are you using?

v14

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

n/a

### Describe your issue

The main postcss-plugin of tailwind has a "hack" in place to support es-module and commonjs environments (https://github.com/tailwindlabs/tailwindcss/blob/master/plugin.js).

The same "hack" is missing for the `tailwindcss/nesting` export so it fails to be imported in es-module-environments like `sveltekit` with the following error:

```
info => Adding stories defined in "sveltekit-minimal/.storybook/main.js"
ERR! Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import 'sveltekit-minimal/node_modules/tailwindcss/nesting' is not supported resolving ES modules imported from sveltekit-minimal/svelte.config.js
ERR! Did you mean to import tailwindcss@2.2.7_7b69a43ec4689fa7484dee35f79a7806/node_modules/tailwindcss/nesting/index.js?
ERR!     at finalizeResolution (internal/modules/esm/resolve.js:267:17)
ERR!     at moduleResolve (internal/modules/esm/resolve.js:694:10)
ERR!     at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:805:11)
ERR!     at Loader.resolve (internal/modules/esm/loader.js:88:40)
ERR!     at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)
ERR!     at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:72:40)
ERR!     at link (internal/modules/esm/module_job.js:71:36)
ERR!  Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import 'sveltekit-minimal/node_modules/tailwindcss/nesting' is not supported resolving ES modules imported from sveltekit-minimal/svelte.config.js
ERR! Did you mean to import tailwindcss@2.2.7_7b69a43ec4689fa7484dee35f79a7806/node_modules/tailwindcss/nesting/index.js?
ERR!     at finalizeResolution (internal/modules/esm/resolve.js:267:17)
ERR!     at moduleResolve (internal/modules/esm/resolve.js:694:10)
ERR!     at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:805:11)
ERR!     at Loader.resolve (internal/modules/esm/loader.js:88:40)
ERR!     at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)
ERR!     at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:72:40)
ERR!     at link (internal/modules/esm/module_job.js:71:36) {
ERR!   code: 'ERR_UNSUPPORTED_DIR_IMPORT',
ERR!   url: 'file://sveltekit-minimal/node_modules/tailwindcss/nesting'
ERR! }
```

**Comment by Assuntaa** [comment]
It is NOT Vite's goal to completely replace webpack. There are probably a small number of features/capabilities that some existing webpack projects rely on that doesn't exist in Vite, but those features are in the long tail and are only needed by a small number of power users who write bespoke webpack configuration

**Comment by benbender** [comment]
@Assuntaa I'm not quite sure what you are trying to say and how it is related to the issue... Is there anything I'm missing?

**Comment by bradlc** [comment]
Hey @benbender. I see what you mean about the "hack," but the actual issue you're running into is that [file extensions are required when using `import` in Node](https://nodejs.org/api/esm.html#esm_mandatory_file_extensions):

> A file extension must be provided when using the `import` keyword to resolve relative or absolute specifiers. Directory indexes (e.g. `'./startup/index.js'`) must also be fully specified.

The solution is described in the error message: you should import `tailwindcss/nesting/index.js` instead. I have tested this in SvelteKit and it works fine so I'm going to close this. Please open a new issue with a reproduction if you run into any other problems though 👍
