### ISSUE TITLE
[jit] Animation not working in Next.js

### ISSUE THREAD

**Issue by nghiepit** [tailwindlabs/tailwindcss#5112]
### What version of Tailwind CSS are you using?

2.2.7

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js 10 and 11

### What version of Node.js are you using?

14

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://codesandbox.io/s/tailwind-jit-animation-bug-s5tf8?file=/tailwind.config.js:88-174

### Describe your issue

The problem only occurs when I use `Next.js`.
With the same config, https://play.tailwindcss.com/62JGXA2J1r works ok.

```jsx
export default function IndexPage() {
  return <div className="animate-bounce">Hello World</div>;
}
```

**Comment by sachinraja** [comment]
You haven't specified any files to purge in `tailwind.config.js`. It is still necessary with the JIT (see [docs](https://tailwindcss.com/docs/just-in-time-mode#enabling-jit-mode)) and [the official next.js tailwind example](https://github.com/vercel/next.js/blob/canary/examples/with-tailwindcss/tailwind.config.js). Here's the same code sandbox but with `purge` configured: https://codesandbox.io/s/tailwind-jit-animation-bug-forked-r79tw.

**Comment by nghiepit** [comment]
@sachinraja Thank you!!
