### ISSUE TITLE
tailwind Configuration issue

### ISSUE THREAD

**Issue by GAYATHIRI31** [tailwindlabs/tailwindcss#5139]
### What version of Tailwind CSS are you using?

v2.2.7

### What build tool (or framework if it abstracts the build tool) are you using?

postcss-cli

### What version of Node.js are you using?

v14.17.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/GAYATHIRI31/myblog

### Describe your issue

'sleep' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-blog@0.1.0 react-scripts:start: `sleep 5 && react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-blog@0.1.0 react-scripts:start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gayathri\AppData\Roaming\npm-cache\_logs\2021-08-02T12_14_51_692Z-debug.log
ERROR: "react-scripts:start" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-blog@0.1.0 start: `run-p watch:css react-scripts:start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-blog@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by GAYATHIRI31** [comment]
> ### What version of Tailwind CSS are you using?
> v2.2.7
> 
> ### What build tool (or framework if it abstracts the build tool) are you using?
> postcss-cli
> 
> ### What version of Node.js are you using?
> v14.17.1
> 
> ### What browser are you using?
> Chrome
> 
> ### What operating system are you using?
> Windows
> 
> ### Reproduction repository
> https://github.com/GAYATHIRI31/myblog
> 
> ### Describe your issue
> 'sleep' is not recognized as an internal or external command,
> operable program or batch file.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! my-blog@0.1.0 react-scripts:start: `sleep 5 && react-scripts start`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the my-blog@0.1.0 react-scripts:start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\Gayathri\AppData\Roaming\npm-cache_logs\2021-08-02T12_14_51_692Z-debug.log
> ERROR: "react-scripts:start" exited with 1.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! my-blog@0.1.0 start: `run-p watch:css react-scripts:start`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the my-blog@0.1.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by adamwathan** [comment]
Hey! The issue here is described in the error:

> 'sleep' is not recognized as an internal or external command,
operable program or batch file

Your package.json script has `sleep 5` at the beginning for some reason and that isn't a command. Closing as not really Tailwind related, hope that helps though.
