### ISSUE TITLE
Keyframes don't seem to be working in theme extend

### ISSUE THREAD

**Issue by tk-bitio** [tailwindlabs/tailwindcss#5176]
### What version of Tailwind CSS are you using?

2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

N/A

### What version of Node.js are you using?

N/A

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/dJVWgoFnat

### Describe your issue

Keyframe extension doesn't seem to work in the config? This is how I used it, as specified in the tailwind documentation:
```js
extend: {
    keyframes: {
        flash: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
      },
      animation: {
        flash: 'flash 2s ease-in-out infinite;',
      },
}
 ```

as specified in the docs here: https://tailwindcss.com/docs/animation#customizing

**Comment by tk-bitio** [comment]
Expected behavior: for the div with classname "animate-flash" to flash. 

Observed behavior: it does not flash. 

Expected behavior is seen when css is extended with 
```css
@keyframes flash {
  50% {
    opacity: 0;
  }
}
```
so keyframes in the config are not correctly working.

**Comment by adamwathan** [comment]
Hey! Typo in your config, you have a dangling semicolon inside your config value that's breaking it:

```diff
  // tailwind.config.js
  module.exports = {
    theme: {
      extend: {
        keyframes: {
          flash: {
            "0%, 100%": { opacity: "1" },
            "50%": { opacity: "0" },
          },
        },
        animation: {
-         flash: "flash 2s ease-in-out infinite;",
+         flash: "flash 2s ease-in-out infinite",
        },
      },
    },
  };
```

Here's a working Play:

https://play.tailwindcss.com/Z4UWCensEq
