### ISSUE TITLE
Object Position in JIT mode

### ISSUE THREAD

**Issue by nfq** [tailwindlabs/tailwindcss#5177]
### What version of Tailwind CSS are you using?

2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

Vite (with SvelteKit)

### What version of Node.js are you using?

v14.17.3

### What browser are you using?

Safari, Firefox

### What operating system are you using?

macOS Big Sur

### Reproduction repository

N/A

### Describe your issue

Using dynamic values on Object Position (top, bottom etc.) doesn't work as expected.
I want to do this: `object-top-[30%]`
Seems to be a bug:

`object-[30%]` works but `object-[0,30%]` should compile to `object-position: 0 30%` but right now it compiles to `object-position: 0,30%`.

**Comment by adamwathan** [comment]
Will be fixed in the next patch release, hopefully Monday or Tuesday 👍  Thanks!

**Comment by nfq** [comment]
Thanks for the quick fix!

**Comment by MaluNoPeleke** [comment]
I have updated to the latest 2.2.10 release but cannot make it work with this class: object-[76%, 51%]
I see no change in the CSS applied to the img element.

**Comment by calvinballing** [comment]
Ensure that the `content` array in your `tailwind.config.js` file includes the file where you have included the arbitrary value.  I was having trouble with an arbitrary value, until I realized I had made this mistake.
