### ISSUE TITLE
Tailwind not working with next@11.1.0

### ISSUE THREAD

**Issue by MauriceArikoglu** [tailwindlabs/tailwindcss#5193]
### What version of Tailwind CSS are you using?

2.2.7

### What build tool (or framework if it abstracts the build tool) are you using?

all standard from create-next-app

### What version of Node.js are you using?

14.16.1

### What browser are you using?

FF, Chromium, Safari

### What operating system are you using?

macOS

### Reproduction repository

npx create-next-app -e with-tailwindcss my-project

### Describe your issue

Tailwind not working with most recent version of next.js

**Comment by MauriceArikoglu** [comment]
11.0.1 is the last compatible working version for me. Solution is to stick to that.

**Comment by bradlc** [comment]
Hey @MauriceArikoglu. It seems to be working fine as far as I can tell. If you're having issues please open a new issue and provide a public GitHub repo that includes a minimal reproduction of the bug, as mentioned in the "new issue" template. Thanks!

**Comment by MauriceArikoglu** [comment]
For everyone stumbling upon this issue, here is a splendid explanation on how the tech behind this "issue" works: https://tailwindcss.com/docs/just-in-time-mode
