### ISSUE TITLE
Directives are not working in imported CSS files

### ISSUE THREAD

**Issue by dospolov** [tailwindlabs/tailwindcss#5194]
### What version of Tailwind CSS are you using?

2.2.7

### What build tool (or framework if it abstracts the build tool) are you using?

"gatsby": "^3.11.1", "gatsby-plugin-postcss": "^4.11.0", "postcss": "^8.3.6",

### What version of Node.js are you using?

v14.16.1

### What browser are you using?

Chrome 92.0.4515.131

### What operating system are you using?

Windows 10

### Reproduction repository

https://github.com/dospolov/tailwindcss-directives-issue

### Describe your issue

`@apply` and `@screen` directives are not working in the imported CSS file

**Comment by Allender-585** [comment]
Our recommendation is to not import .css files. I work on a few projects which import css files directly from npm modules because they arent.

[prepaidcardstatus](https://www.prepaidcardstatus.kim/)

**Comment by quantuminformation** [comment]
I'm finding that @apply doesn't work with the imported css files in the cli. It just ignroes them:
```
    "build": "npx tailwindcss app.css -o ./build/tailwind.css -w"
```

**Comment by adamwathan** [comment]
Hey! If you want Tailwind to process your imports you'll need to use postcss-import to actually do the importing, otherwise what you end up with client side imports:

https://github.com/tailwindlabs/tailwindcss/issues/5397#issuecomment-916984422

Hope that helps!
