### ISSUE TITLE
Stroke utilities don't support `url()` type as arbitrary values

### ISSUE THREAD

**Issue by slavarazum** [tailwindlabs/tailwindcss#5197]
### What version of Tailwind CSS are you using?

2.2.7

### What build tool (or framework if it abstracts the build tool) are you using?

PostCSS with Laravel Mix

### What version of Node.js are you using?

v14.17.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

Reproduces on every environment

### Describe your issue

JIT engine have already successfully handle custom values for fill utility like this: `fill-[url(#icon-gradient)]` (it's useful for gradients on svg icons).

Output CSS:
```css
.fill-[url(#icon-gradient)] {
    fill: url(#icon-gradient);
}
```

But it doesn't work for stroke: `stroke-[url(#icon-gradient)]`.

No output.

**Comment by adamwathan** [comment]
Hey @slavarazum! This is on our radar to make "just work" but in the mean time you can get around it like this:

```
<div class="stroke-[color:url(#icon-gradient)]">
```

Will leave open until we implement URL handling for strokes properly 👍🏻
