### ISSUE TITLE
Including Tailwind CSS changed the design automatically

### ISSUE THREAD

**Issue by moshfiqrony** [tailwindlabs/tailwindcss#5201]
### What version of Tailwind CSS are you using?

2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js 11.1.0

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Firefix

### What operating system are you using?

Ubuntu 20

### Reproduction repository

https://github.com/moshfiqrony/nextjs-tailwindcss-imdb

### Describe your issue

I created the nextJS app using the tailwindcss template. My tailwind was imported directly by default like below in the `_app.js` file
```
import 'tailwindcss/tailwind.css'
```
till now my design looks something like this
![image](https://user-images.githubusercontent.com/26689488/129370777-099c87ab-9117-42aa-8cf4-e3e8cf463607.png)
When I remove the direct import and use the Include process described in the doc like this below 
```
@tailwind base;
@tailwind components;
@tailwind utilities;

@import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap');

*{
    font-family: 'Roboto', sans-serif;
}
```
My design automatically gets changed like this 
![image](https://user-images.githubusercontent.com/26689488/129371053-42acff7c-46df-47e1-a754-8f5c86f099a8.png)
Why this is happening. I have imported the css file in my `_app.js` so no problem in the import. Everything works fine but the inputs automatically reduced it's width. I can fix it using classes but I wanted to know why this is happening.

**Comment by bradlc** [comment]
Hey @moshfiqrony. I can't reproduce this and your design looks the same (apart from the font) with either method. However, the reason your inputs are not full width is because you don't have a space between `w-full` and `${className}` in your `Input` component:

```diff
  const Input = ({
      type = 'text',
      name = '',
      className = '',
      placeholder = '',
      ...props
  }) => {
      return <input
          type={type}
          name={name}
-         className={`p-2 rounded shadow-inner-2 w-full${className}`}
+         className={`p-2 rounded shadow-inner-2 w-full ${className}`}
          placeholder={placeholder}
          {...props}
      />
  }
  
  export default Input
```

Tailwind scans your files for used classes to generate, and currently the [extractor](https://github.com/tailwindlabs/tailwindcss/blob/master/src/jit/lib/expandTailwindAtRules.js#L9-L25) cannot find `w-full` as a standalone class, and so it is not generated. Adding the space allows the extractor to find the class successfully 👍 

Hope that helps!

**Comment by moshfiqrony** [comment]
Thanks @bradlc I also saw it in my local machine. Surprisingly it was full width before. May be If I had given a hard refresh then the problem will also arise. But that was only happening when I did what I describe in my question. Thank you so much. Now everything makes sense. :+1:
