### ISSUE TITLE
README.md logo looks bad in darkmode

### ISSUE THREAD

**Issue by JamesGelok** [tailwindlabs/tailwindcss#5233]
### What version of Tailwind CSS are you using?

latest

### What build tool (or framework if it abstracts the build tool) are you using?

not relevant

### What version of Node.js are you using?

not relevant

### What browser are you using?

not relevant

### What operating system are you using?

not relevant

### Reproduction repository

not relevant

## Problem

It's pretty hard to read the logo in dark mode on the repo.

![darkmode](https://user-images.githubusercontent.com/23425952/129637621-f739a073-e706-4e86-a2f6-3ca5975c5362.png)

## Possible Solution

Use `prefers-color-scheme` in your svg.

```svg
<svg viewBox="0 0 273 64" fill="none" xmlns="http://www.w3.org/2000/svg">
  <style>
    .user-content-svg-tailwind {
      fill: #161C28;
    }
    @media (prefers-color-scheme: dark) {
      .user-content-svg-tailwind {
        fill: #A3B1BF;
      }
    }
  </style>
  <title>
    Tailwind CSS
  </title>
  <path fill-rule="evenodd" clip-rule="evenodd" d="M32 16C24.8 16 20.3 19.6 18.5 26.8C21.2 23.2 24.35 21.85 27.95 22.75C30.004 23.2635 31.4721 24.7536 33.0971 26.4031C35.7443 29.0901 38.8081 32.2 45.5 32.2C52.7 32.2 57.2 28.6 59 21.4C56.3 25 53.15 26.35 49.55 25.45C47.496 24.9365 46.0279 23.4464 44.4029 21.7969C41.7557 19.1099 38.6919 16 32 16ZM18.5 32.2C11.3 32.2 6.8 35.8 5 43C7.7 39.4 10.85 38.05 14.45 38.95C16.504 39.4635 17.9721 40.9536 19.5971 42.6031C22.2443 45.2901 25.3081 48.4 32 48.4C39.2 48.4 43.7 44.8 45.5 37.6C42.8 41.2 39.65 42.55 36.05 41.65C33.996 41.1365 32.5279 39.6464 30.9029 37.9969C28.2557 35.3099 25.1919 32.2 18.5 32.2Z" fill="#16BDCA"/>
  <path class="user-content-svg-tailwind" fill-rule="evenodd" clip-rule="evenodd" d="M85.996 29.652H81.284V38.772C81.284 41.204 82.88 41.166 85.996 41.014V44.7C79.688 45.46 77.18 43.712 77.18 38.772V29.652H73.684V25.7H77.18V20.596L81.284 19.38V25.7H85.996V29.652ZM103.958 25.7H108.062V44.7H103.958V41.964C102.514 43.978 100.272 45.194 97.308 45.194C92.14 45.194 87.846 40.824 87.846 35.2C87.846 29.538 92.14 25.206 97.308 25.206C100.272 25.206 102.514 26.422 103.958 28.398V25.7ZM97.954 41.28C101.374 41.28 103.958 38.734 103.958 35.2C103.958 31.666 101.374 29.12 97.954 29.12C94.534 29.12 91.95 31.666 91.95 35.2C91.95 38.734 94.534 41.28 97.954 41.28ZM114.902 22.85C113.458 22.85 112.28 21.634 112.28 20.228C112.28 18.784 113.458 17.606 114.902 17.606C116.346 17.606 117.524 18.784 117.524 20.228C117.524 21.634 116.346 22.85 114.902 22.85ZM112.85 44.7V25.7H116.954V44.7H112.85ZM121.704 44.7V16.96H125.808V44.7H121.704ZM152.446 25.7H156.778L150.812 44.7H146.784L142.832 31.894L138.842 44.7H134.814L128.848 25.7H133.18L136.866 38.81L140.856 25.7H144.77L148.722 38.81L152.446 25.7ZM161.87 22.85C160.426 22.85 159.248 21.634 159.248 20.228C159.248 18.784 160.426 17.606 161.87 17.606C163.314 17.606 164.492 18.784 164.492 20.228C164.492 21.634 163.314 22.85 161.87 22.85ZM159.818 44.7V25.7H163.922V44.7H159.818ZM178.666 25.206C182.922 25.206 185.962 28.094 185.962 33.034V44.7H181.858V33.452C181.858 30.564 180.186 29.044 177.602 29.044C174.904 29.044 172.776 30.64 172.776 34.516V44.7H168.672V25.7H172.776V28.132C174.03 26.156 176.082 25.206 178.666 25.206ZM205.418 18.1H209.522V44.7H205.418V41.964C203.974 43.978 201.732 45.194 198.768 45.194C193.6 45.194 189.306 40.824 189.306 35.2C189.306 29.538 193.6 25.206 198.768 25.206C201.732 25.206 203.974 26.422 205.418 28.398V18.1ZM199.414 41.28C202.834 41.28 205.418 38.734 205.418 35.2C205.418 31.666 202.834 29.12 199.414 29.12C195.994 29.12 193.41 31.666 193.41 35.2C193.41 38.734 195.994 41.28 199.414 41.28ZM223.278 45.194C217.54 45.194 213.246 40.824 213.246 35.2C213.246 29.538 217.54 25.206 223.278 25.206C227.002 25.206 230.232 27.144 231.752 30.108L228.218 32.16C227.382 30.374 225.52 29.234 223.24 29.234C219.896 29.234 217.35 31.78 217.35 35.2C217.35 38.62 219.896 41.166 223.24 41.166C225.52 41.166 227.382 39.988 228.294 38.24L231.828 40.254C230.232 43.256 227.002 45.194 223.278 45.194ZM238.592 30.944C238.592 34.402 248.814 32.312 248.814 39.342C248.814 43.142 245.508 45.194 241.404 45.194C237.604 45.194 234.868 43.484 233.652 40.748L237.186 38.696C237.794 40.406 239.314 41.432 241.404 41.432C243.228 41.432 244.634 40.824 244.634 39.304C244.634 35.922 234.412 37.822 234.412 31.02C234.412 27.448 237.49 25.206 241.366 25.206C244.482 25.206 247.066 26.65 248.396 29.158L244.938 31.096C244.254 29.614 242.924 28.93 241.366 28.93C239.884 28.93 238.592 29.576 238.592 30.944ZM256.11 30.944C256.11 34.402 266.332 32.312 266.332 39.342C266.332 43.142 263.026 45.194 258.922 45.194C255.122 45.194 252.386 43.484 251.17 40.748L254.704 38.696C255.312 40.406 256.832 41.432 258.922 41.432C260.746 41.432 262.152 40.824 262.152 39.304C262.152 35.922 251.93 37.822 251.93 31.02C251.93 27.448 255.008 25.206 258.884 25.206C262 25.206 264.584 26.65 265.914 29.158L262.456 31.096C261.772 29.614 260.442 28.93 258.884 28.93C257.402 28.93 256.11 29.576 256.11 30.944Z" fill="#161E2E"/>
</svg>
```

**Now the image shows up on dark-mode:**

<img alt="Tailwind CSS" width="350" src="https://gist.githubusercontent.com/JamesGelok/2b0159432edb9ca66ad682e33b2fe0d9/raw/93f22c3bc4c66fc2b4ec7bae2fd294fef160d5c8/tailwind.svg">
      
❗ NOTE: I'm using gist to store the svg and so if you switch to dark mode to check you should know: Github is caching it because gist isn't sending rules to disable caching in their headers. So in order to see it you need to hard refresh (this doesn't happen every time, [you can store it elsewhere with no-caching headers](https://github.community/t/how-to-prevent-github-from-caching-images-in-markdown-files/1868/2) and I think GitHub will respect it).

## Other possible solutions

Maybe doing something fancy with a filter or `feColorMatrix`

**Comment by adamwathan** [comment]
Nice trick! Is there anything that can be done if the user just manually enables dark mode on GitHub rather than following their system preferences?

**Comment by JamesGelok** [comment]
> Nice trick! Is there anything that can be done if the user just manually enables dark mode on GitHub rather than following their system preferences?

Short answer is not with direct GitHub support yet, but there may be other workarounds that would get the logo to look better in darkmode.

<details><summary><code># Pasting my notes for when I tried to get my SVG's CSS to read GitHub's HTML tags. Expand for too many details about GitHub's dark/light mode implementation:#</code></summary><br/>

<hr/>
The color modes for github are controlled by 3 attributes on the html tag: `data-color-mode`, `data-light-theme`, and `data-dark-theme`

The theme values they all accept are `light`, `dark`, and `dark_dimmed`. 


The attribute `data-color-mode` accepts `auto` as one additional value


<ul>
<li>
<p><g-emoji class="g-emoji" alias="brain" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f9e0.png">🧠</g-emoji> <code>data-color-mode="____"</code>:</p>
<ul>
<li><g-emoji class="g-emoji" alias="robot" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f916.png">🤖</g-emoji> <code>auto</code>: Detects the system theme, and sets it to <code>data-dark-theme</code>'s theme if the system is in dark mode and <code>data-light-theme</code>'s theme if it's in light mode (an unchecked assumption is that it defaults to <code>data-light-theme</code> if <code>prefers-color-scheme</code> is unavailable in the case of old browsers or <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme#browser_compatibility" rel="nofollow">ofc ie</a>)</li>
<li><g-emoji class="g-emoji" alias="sunny" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/2600.png">☀️</g-emoji> <code>light</code> : traditional light mode (ignore system theme &amp; other attributes, just do this mode)</li>
<li><g-emoji class="g-emoji" alias="full_moon_with_face" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f31d.png">🌝</g-emoji> <code>dark</code> : dark mode (ignore system theme &amp; other attributes, just do this mode)</li>
<li><g-emoji class="g-emoji" alias="new_moon_with_face" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f31a.png">🌚</g-emoji> <code>dark_dimmed</code> : darker mode (ignore system theme &amp; other attributes, just do this mode)</li>
</ul>
</li>
<li>
<p><g-emoji class="g-emoji" alias="city_sunrise" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f307.png">🌇</g-emoji> <code>data-light-theme="____"</code>:</p>
<ul>
<li><g-emoji class="g-emoji" alias="sunny" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/2600.png">☀️</g-emoji> <code>light</code> : traditional light mode</li>
<li><g-emoji class="g-emoji" alias="full_moon_with_face" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f31d.png">🌝</g-emoji> <code>dark</code> : dark mode</li>
<li><g-emoji class="g-emoji" alias="new_moon_with_face" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f31a.png">🌚</g-emoji> <code>dark_dimmed</code> : darker mode</li>
</ul>
</li>
<li>
<p><g-emoji class="g-emoji" alias="milky_way" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f30c.png">🌌</g-emoji> <code>data-dark-theme="____"</code>:</p>
<ul>
<li><g-emoji class="g-emoji" alias="sunny" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/2600.png">☀️</g-emoji> <code>light</code> : traditional light mode</li>
<li><g-emoji class="g-emoji" alias="full_moon_with_face" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f31d.png">🌝</g-emoji> <code>dark</code> : dark mode</li>
<li><g-emoji class="g-emoji" alias="new_moon_with_face" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f31a.png">🌚</g-emoji> <code>dark_dimmed</code> : darker mode</li>
</ul>
</li>
</ul>
<hr/>

</br></details>

### Ideas/Other dark mode workarounds

**`For a simple way to force dark-mode visibility`** a white glow, border, or something like that would allow the logo to be visible in dark mode and if it's 

**`For no glow or border`**, an svg color inversion filter that inverts the background color might work. Possibly it could arrive at the same color for the text of the logo in the readme right now (![#161C28](https://via.placeholder.com/15/161C28/000000?text=+) `#161C28`), and maybe their inversions would look good in the two darkmode colors but I'm not sure because I haven't checked.

**Comment by laSinteZ** [comment]
Even though it is doable with something like @media (prefers-color-scheme: dark) in the svg file itself (like here: https://github.com/laSinteZ/fastify/commit/248e4f7f0015623a9efad068be303b8415bd2e31#diff-f54e40e3b9ed9396c40ee19b1fb8bca05b610544f3d4c17949f0ac08b2b473cbR7), I wouldn't recommend doing that.

I was exploring this question to help with the same problem in https://github.com/fastify/fastify but we decided to roll with white outlined border.

The problem arises when user has dark mode for system, but light mode in GH (and vice-versa)
Example: 
https://github.com/fastify/fastify/issues/2779#issuecomment-825638310

**Comment by patrickhill** [comment]
You can use a combination of multiply and overlay blend modes to achieve an auto adapting SVG logo.
Working demo: https://codepen.io/patrickhill/pen/gORWmZr

**Comment by ram-you** [comment]
I'm using this css solution:
`   .dropShadow {
     filter: drop-shadow(2px 4px 6px rgb(199, 199, 199));
     transition: filter .8s ease-in;
   }
   .dark .dropShadow {
     filter: drop-shadow(2px 4px 6px #1a202c);
     transition: filter .8s ease-in;
   }`

**Comment by patrickhill** [comment]
One more note, the problem could also be fixed with a simple color change. If you pick a middle gray for the wordmark or make the whole logo the brand color, it would show up in light and dark modes.

![tailwind logo - light_dark](https://user-images.githubusercontent.com/2302078/132955703-da5302ff-1488-4285-bd58-7f57ba619765.png)

**Comment by adamwathan** [comment]
Thanks for the suggestions everyone! For dark mode we went ahead and kinda made it look like a die cut sticker, think it turned out cool 👍🏻 

![image](https://user-images.githubusercontent.com/4323180/133316684-003d9c62-6a53-48c5-84e9-ea6cbc36103c.png)

**Comment by andreasbhansen** [comment]
Now there's official support for it: https://twitter.com/ashtom/status/1463554157932023808
