### ISSUE TITLE
Missing form styles when following Next.js setup

### ISSUE THREAD

**Issue by Ne-Ne** [tailwindlabs/tailwindcss#5269]
### What version of Tailwind CSS are you using?

2.2.7

### What build tool (or framework if it abstracts the build tool) are you using?

autoprefixer: ^10.3.2, postcss: ^8.3.6

### What version of Node.js are you using?

12.13.0

### What browser are you using?

Brave, Chrome, Safari

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/Ne-Ne/tailwindcss-example-nextjs-project

### Describe your issue

Following [Tailwind docs to setup Next.js](https://tailwindcss.com/docs/guides/nextjs), I get the following missing styles:

<img width="1552" alt="Screenshot 2021-08-22 at 14 17 16" src="https://user-images.githubusercontent.com/2177851/130356743-1a6ef2b7-a007-4e8c-bb84-6d1f324eae84.png">

I cannot get the input styles to render. To re-create the issue I have copied the example React component `<Example />` from the [form-layouts](https://tailwindui.com/components/application-ui/forms/form-layouts) docs.

**Comment by bradlc** [comment]
Hey @Ne-Ne. Some Tailwind UI components require changes to be made to your config file, and these are detailed in a comment at the top of the component code. In this case you need to install [the `@tailwindcss/forms` plugin](https://github.com/tailwindlabs/tailwindcss-forms) and add it to your config file:

```bash
yarn add -D @tailwindcss/forms
```

```diff
  module.exports = {
    mode: 'jit',
    purge: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
    darkMode: false, // or 'media' or 'class'
    theme: {
      extend: {},
    },
    variants: {
      extend: {},
    },
-   plugins: [],
+   plugins: [require('@tailwindcss/forms')],
  }
```

Hope that helps!

**Comment by Ne-Ne** [comment]
@bradlc thanks for getting back to me, worked like a charm 🥳 

Is there a particular reason why the NextJS docs omitted this info? I have found the [dependency docs](https://tailwindui.com/documentation#react-installing-dependencies), which I believe you were referring to. I read the docs thinking I could grab and go with the React `className`'s.

In future is there any other gotcha's that I should be aware of?
