### ISSUE TITLE
@apply not compiled - Syntaxerror "unknown word" @apply

### ISSUE THREAD

**Issue by Ernestopheles** [tailwindlabs/tailwindcss#5273]
### What version of Tailwind CSS are you using?

2.2.7

### What build tool (or framework if it abstracts the build tool) are you using?

tailwindcss

### What version of Node.js are you using?

16.7.0

### What browser are you using?

brave

### What operating system are you using?

Kubuntu

### Reproduction repository

https://github.com/Ernestopheles/tailwind

### Describe your issue

npx tailwindcss -i ./css/styles.css -o ./css/tailwind.css Syntaxerror because of unknown word @apply

`...@...:~/tailwind2$ npx tailwindcss -i tailwind.css -o styles.css
/home/.../tailwind2/node_modules/tailwindcss/peers/index.js:57624
      result = new CssSyntaxError(
               ^

CssSyntaxError: /home/.../tailwind2/tailwind.css:7:5: Unknown word
    at Input.error (/home/.../tailwind2/node_modules/tailwindcss/peers/index.js:57624:16)
    at Parser.unknownWord (/home/.../tailwind2/node_modules/tailwindcss/peers/index.js:59549:22)
    at Parser.other (/home/.../tailwind2/node_modules/tailwindcss/peers/index.js:59180:12)
    at Parser.parse (/home/.../tailwind2/node_modules/tailwindcss/peers/index.js:59090:16)
    at parse (/home/.../tailwind2/node_modules/tailwindcss/peers/index.js:58992:12)
    at new LazyResult (/home/.../tailwind2/node_modules/tailwindcss/peers/index.js:57858:16)
    at Processor.process (/home/.../tailwind2/node_modules/tailwindcss/peers/index.js:59896:12)
    at /home/.../tailwind2/node_modules/tailwindcss/lib/cli.js:582:39 {
  reason: 'Unknown word',
  file: '/home/.../tailwind2/tailwind.css',
  source: '@tailwind base;\n' +
    '@tailwind components;\n' +
    '@tailwind utilities;\n' +
    '\n' +
    '@layer base​ {\n' +
    '    h1 {\n' +
    '    ​@apply text-5xl;\n' +
    '    }\n' +
    '    h2 {\n' +
    '    @apply text-3xl;\n' +
    '    }\n' +
    '    h3 {\n' +
    '    @apply text-2xl;\n' +
    '    }\n' +
    '}',
  line: 7,
  column: 5,
  input: {
    line: 7,
    column: 5,
    source: '@tailwind base;\n' +
      '@tailwind components;\n' +
      '@tailwind utilities;\n' +
      '\n' +
      '@layer base​ {\n' +
      '    h1 {\n' +
      '    ​@apply text-5xl;\n' +
      '    }\n' +
      '    h2 {\n' +
      '    @apply text-3xl;\n' +
      '    }\n' +
      '    h3 {\n' +
      '    @apply text-2xl;\n' +
      '    }\n' +
      '}',
    url: 'file:///home/.../tailwind2/tailwind.css',
    file: '/home/.../tailwind2/tailwind.css'
  }
}`

**Comment by Ernestopheles** [comment]
Found another way to get things running

**Comment by jq-87** [comment]
@Ernestopheles [Ernestopheles](https://github.com/Ernestopheles) how did you resolve this?

**Comment by Ernestopheles** [comment]
Sorry, do not remember, actually it works fine with the npx command
npx tailwindcss -i ../projects/contao/files/themes/css/twi.css -o ../projects/contao/files/themes/css/two.css
