### ISSUE TITLE
Borders added when pasting into Microsoft Word/Outlook

### ISSUE THREAD

**Issue by PaddyMann** [tailwindlabs/tailwindcss#5274]
### What version of Tailwind CSS are you using?

2.2.7

### What build tool (or framework if it abstracts the build tool) are you using?

twin

### What version of Node.js are you using?

n/a

### What browser are you using?

Chrome

### What operating system are you using?

macOs

### Reproduction repository

n/a

### Describe your issue

Tailwind current adds `border: 0 solid` to every element.

While this works fine in most scenarios, it unfortunately causes issues for anyone copy and pasting content into Microsoft Word or Outlook. Word decides to always display a border around an element that has a `solid` border, even if the `border-width` is set to 0.

Here's a Loom video demonstrating the bug by copy and pasting content from your own website: https://www.loom.com/share/165d1aee8ca14c2489bd554bdb0d4025

While I appreciate it's really a bug in Microsoft Word/Outlook, it'd be great if we could fix it in Tailwind. This would be achieved by only adding `border-style: solid` to elements that actually have a border.

**Comment by Mancuso-585** [comment]
Describes the table border is missing when you paste a table in email in Outlook for Mac. Provides a solution.

**Comment by PaddyMann** [comment]
I'm not sure what you're referring to Mancuso-585? 

The issue you describe is not the one I've shared in this issue: I'm referring to a border being _added_ to _all_ elements.

**Comment by adamwathan** [comment]
Hey! Try this experimental feature (with JIT mode enabled):

```js
// tailwind.config.js
module.exports = {
  mode: 'jit',
  experimental: {
    optimizeUniversalDefaults: true,
  },
}
```

Might help by coincidence. Unfortunately this isn't really a problem I care to optimize for and I don't think there's anything I can change here for this other than what that feature does without it having a negative impact on the developer experience for everyone else, so no plans to really do anything about this I'm afraid. Hope that's understandable!

**Comment by tiagov8** [comment]
As per https://tailwindcss.com/docs/preflight#border-styles-are-reset-globally

This can be fixed by adding the following to CSS:

```
*, ::before, ::after {
  border-style: none;
}
```

**Comment by jjenzz** [comment]
we removed the border style as @tiagov8 suggested, but also needed to add a plugin to reapply the border style when the various classes are used (in case it helps anyone)

```tsx
 plugin(({ addUtilities, theme }) => {
  const borderWidths = theme('borderWidth');
  if (!borderWidths) return;

  const newUtilities: Record<string, Record<string, string>> = {
    '.border': { borderStyle: 'solid' },
    '.border-t': { borderTopStyle: 'solid' },
    '.border-r': { borderRightStyle: 'solid' },
    '.border-b': { borderBottomStyle: 'solid' },
    '.border-l': { borderLeftStyle: 'solid' },
    '.border-x': { borderLeftStyle: 'solid', borderRightStyle: 'solid' },
    '.border-y': { borderTopStyle: 'solid', borderBottomStyle: 'solid' },
  };

  for (const key in borderWidths) {
    if (key === 'DEFAULT') continue;

    newUtilities[`.border-${key}`] = { borderStyle: 'solid' };
    newUtilities[`.border-t-${key}`] = { borderTopStyle: 'solid' };
    newUtilities[`.border-r-${key}`] = { borderRightStyle: 'solid' };
    newUtilities[`.border-b-${key}`] = { borderBottomStyle: 'solid' };
    newUtilities[`.border-l-${key}`] = { borderLeftStyle: 'solid' };
    newUtilities[`.border-x-${key}`] = {
      borderLeftStyle: 'solid',
      borderRightStyle: 'solid',
    };
    newUtilities[`.border-y-${key}`] = {
      borderTopStyle: 'solid',
      borderBottomStyle: 'solid',
    };
  }

  addUtilities(newUtilities);
}),
```
