### ISSUE TITLE
CLI --watch not working in docker

### ISSUE THREAD

**Issue by ShaneBurkhart** [tailwindlabs/tailwindcss#5324]
### What version of Tailwind CSS are you using?

2.2.8

### What build tool (or framework if it abstracts the build tool) are you using?

Vanilla CLI

### What version of Node.js are you using?

12

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### Reproduction repository

Compile in docker using cli with watch without a tty

### Describe your issue

A recent update made changes to detect if there is a stdin or not when watching. With docker, there is no stdin when using something like docker-compose up. The process exits with code 0.

For now, I am going back to 2.2.7.  I might be able to spoof stdin for my container. Still working on that. 

Here is the code that is causing the issue. 

<img width="775" alt="Screen Shot 2021-08-27 at 6 58 29 PM" src="https://user-images.githubusercontent.com/2678773/131199399-96eaf2d0-8666-4aca-9c70-9da071dfeb59.png">

**Comment by ShaneBurkhart** [comment]
Adding `tty` to docker compose file for the service fixed the issue. I would not consider this a tailwind issue. 

![image](https://user-images.githubusercontent.com/2678773/131200077-d86680f4-7953-4b23-afaf-90bffd845990.png)

It's a simple config to fix and hopefully this saves someone time.

**Comment by ShaneBurkhart** [comment]
I found a docker compose config solution. This is not a tailwind problem.

**Comment by TheJazzDev** [comment]
@ShaneBurkhart God bless you. You just save me from 48 hours of debugging!
