### ISSUE TITLE
tailwind jit arbitrary values not wroking for shadow

### ISSUE THREAD

**Issue by ahmedzu** [tailwindlabs/tailwindcss#5335]
### What version of Tailwind CSS are you using?

 v2.0.4

### What build tool (or framework if it abstracts the build tool) are you using?

 postcss-cli 8.3.1,

### What version of Node.js are you using?

v14.17.5

### What browser are you using?

chrome

### What operating system are you using?

windows 10

### Reproduction repository

--

### Describe your issue

arbitrary values not wroking for shadow 

for example:

shadow-[0px,1px,2px,0px,#ccc]
not working

shadow-[0px,0px,5px,rgba(87,87,87,0.39)]
not working

**Comment by Raven-585** [comment]
js for you people again than I am about actually using the feature. And I'm really excited about the feature, so that says something. Extended arbitrary value

**Comment by dcastil** [comment]
Hey @ahmedzu! I'm afraid Tailwind doesn't support custom values for shadows at the moment. Just found out myself through this comment from a Tailwind-maintainer: https://github.com/tailwindlabs/tailwindcss/issues/5142#issuecomment-891578190

**Comment by adamwathan** [comment]
Hey! We've actually just made this possible here:

https://github.com/tailwindlabs/tailwindcss/pull/5460

It won't be available in a 2.x release, but as of 3.0 you will be able to use underscores to represent spaces and do arbitrary box shadows:

```html
<div class="shadow-[0px_0px_5px_rgba(87,87,87,0.39)]">
```

If you want to start playing with it now you can use our `insiders` build, just keep in mind it's not stable and changes rapidly:

```
npm install -D tailwindcss@insiders
```
