### ISSUE TITLE
space-y utility not producing expected results

### ISSUE THREAD

**Issue by ksnyde** [tailwindlabs/tailwindcss#5357]
### What version of Tailwind CSS are you using?

2.1.7

### What build tool (or framework if it abstracts the build tool) are you using?

Tailwind Play

### What version of Node.js are you using?

Tailwind Play

### What browser are you using?

Chrome and Firefox

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/xJyZL91FNc

### Describe your issue

I have a grid layout and am using both `space-x` and `space-y` utilities. However the first element (upper left) does _not_ receive any styling from the `space-y` utility whereas all the rest do. 

## Overview
<img width="1397" alt="2021-09-01_08-29-55" src="https://user-images.githubusercontent.com/980757/131702696-38d356f2-6c7c-45f8-b509-96870521e916.png">

## Works
<img width="1470" alt="2021-09-01_08-06-55 (1)" src="https://user-images.githubusercontent.com/980757/131702734-b7a8fdc6-d2e1-4073-8bdd-a85e44644759.png">

## Does Not Work
<img width="1465" alt="2021-09-01_08-06-55 (3)" src="https://user-images.githubusercontent.com/980757/131702765-4f1a8446-0d95-4df8-b849-162b4ca033ac.png">

**Comment by adamwathan** [comment]
Hey thanks for the detailed issue! This is just a limitation of how the space utilities work, they are really just meant for simple lists that only go in one direction:

https://tailwindcss.com/docs/space#limitations

In your case you want to use the `gap` utilities to take advantage of the gap feature that's part of CSS grid:

https://tailwindcss.com/docs/gap

Hope that helps!
