### ISSUE TITLE
JIT mode issues with background color

### ISSUE THREAD

**Issue by Florian-crg** [tailwindlabs/tailwindcss#5381]
### What version of Tailwind CSS are you using?

2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js 11.0.0,      postcss: 8.3.5

### What version of Node.js are you using?

v12.22.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS M1

### Reproduction repository

--

### Describe your issue

Using the syntax with brackets to create backgrounds like `bg-[#000]` works statically but not dynamically.

This does not work : 
`var bg = "#000"`
`<span className={"bg-[" + bg + "]"}>`

While this does : 
`<span className={"bg-[#000]"}>`

What I did for the moment : 
`<span style={{ backgroundColor: bg }}>`

**Comment by reinink** [comment]
The way JIT mode works is by scanning your templates for instances of Tailwind classes, and then generating the appropriate styles based on those classes. For arbitrary values, Tailwind isn't evaluating them, as technically these templates could be done in any programming language, not just JavaScript. Meaning, whatever value you include within an arbitrary class *must be valid CSS*.

With Tailwind you generate your CSS at compile time (your build step), not at run time. Meaning any totally dynamic, unpredictable styles, such as the colors in your example, won't work.

Of course if you know what all the colors are ahead of time, you could create a lookup table with the proper class names, and Tailwind will see those. For example:

```jsx
let colors = [
  black: 'bg-[#000000]',
  red: 'bg-[#922B21]',
  yellow: 'bg-[#F4D03F]',
  // ...
];

<span className={colors[myColor]}>
```

However, if you wanted to support any possible color (ie. a user can provide their own hex color), then your style tag workaround is the better solution, as generating all the possible colors in your Tailwind CSS file wouldn't be realistic (it would be a massive file).

I hope that helps! 💪
