### ISSUE TITLE
List Markdown issues in React

### ISSUE THREAD

**Issue by CloudDrivenSolutions** [tailwindlabs/tailwindcss#5385]
### What version of Tailwind CSS are you using?

2.2.9

### What build tool (or framework if it abstracts the build tool) are you using?

postcss-7.0.35, React  17.0.2

### What version of Node.js are you using?

v12.16.3

### What browser are you using?

Chrome

### What operating system are you using?

macOs

### Reproduction repository

https://github.com/CloudDrivenSolutions/markdown

### Describe your issue

When rendering markdown in react it's removing parts of the markdown.  I've tested without tailwind and it works as expected.

Markdown:
`Well I'm attempting Something
  - Like an Ordered List
  - ***With Bold and Italics***
  1. Testing with numbers too
  `

![Screen Shot 2021-09-03 at 3 13 20 PM](https://user-images.githubusercontent.com/66493677/132061071-e7ace218-3979-4501-92b5-3105d26aa093.png)

**Comment by CloudDrivenSolutions** [comment]
I tried disabling the core plugins in the tailwind config:

`corePlugins: {
    listStyleType: false,
    listStylePosition: false,
  },`

But the index.css was still generating core properties for ol and ul.

I had to go into the core css file and apply settings to base to resolve the issue but that will then effect everything in the whole project.

`
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
    ul {
        display: block !important;
        list-style-type: disc !important;
        padding-inline-start: 40px;
    }
    ol {
        display: block !important;
        list-style-type: decimal !important;
        padding-inline-start: 40px;
    }
}`

**Comment by CloudDrivenSolutions** [comment]
I solved it.  I added rendering custom components into the markdown package.

`
<ReactMarkdown
        children={markdown}
        components={{
          ul: ({ node, ...props }) => (
            <ul
              style={{
                display: "block",
                listStyleType: "disc",
                paddingInlineStart: "40px",
              }}
              {...props}
            />
          ),
          ol: ({ node, ...props }) => (
            <ul
              style={{
                display: "block",
                listStyleType: "decimal",
                paddingInlineStart: "40px",
              }}
              {...props}
            />
          ),
        }}
      />`

**Comment by adamwathan** [comment]
Hey! What you are seeing are the typography resets applied by our Preflight base styles:

https://tailwindcss.com/docs/preflight#lists-are-unstyled

If you want to style content like markdown, you're encouraged to either write your own CSS that styles it the way you want, or to use an existing solution like our official typography plugin which is designed for this purpose:

https://github.com/tailwindlabs/tailwindcss-typography

Hope that helps!
