### ISSUE TITLE
v2.2.8 & v2.2.9 have no changelog

### ISSUE THREAD

**Issue by napei** [tailwindlabs/tailwindcss#5386]
### Describe your issue

It appears that there are no change notes for v2.2.8 or v2.2.9.

I've checked the following:
https://github.com/tailwindlabs/tailwindcss/releases
https://github.com/tailwindlabs/tailwindcss/blob/master/CHANGELOG.md

**Comment by adamwathan** [comment]
Will add this when I get a chance, in the mean time can see the changes between 2.2.7 and 2.2.9 here:

https://github.com/tailwindlabs/tailwindcss/compare/v2.2.7...v2.2.9

**Comment by jacobthesheep** [comment]
now it does so no longer an "issue"...
