### ISSUE TITLE
Can't chain checked and first variants

### ISSUE THREAD

**Issue by itmecho** [tailwindlabs/tailwindcss#5404]
### What version of Tailwind CSS are you using?

v2.2.9

### What build tool (or framework if it abstracts the build tool) are you using?

NextJS (also tailwind playground)

### What version of Node.js are you using?

v12.22.4

### What browser are you using?

Firefox

### What operating system are you using?

Linux

### Reproduction repository

https://play.tailwindcss.com/Rpfi6jx1MX

### Describe your issue

I'm trying to create a custom checkbox/toggle element by using adding the `peer` class to a hidden checkbox input and the using `peer-checked:<classes>` to style the custom checkbox. It works just using it like that but when I want to change the position of the first child in the sibling element using `peer-checked:first:ml-3`, it doesn't work. I can see at the bottom of the generated stylesheet that it's using a weird selector:

```
.peer:checked ~ .peer-checked\:first\:ml-3:first-child {
	margin-left: 0.75rem;
}
```

I'm using jit mode so I didn't think I needed any special configuration to get it working?

The playground I attached should hopefully show the issue

**Comment by rktjmp** [comment]
`:first` should be applied to the child.

```
<div>
  <p class="first:bg-red-400">first</p>
  <p class="first:bg-red-400">middle</p>
  <p class="first:bg-red-400">last</p>
</div>

```
You can do what you want with without `:first` and with `p-n` 

https://play.tailwindcss.com/cIoQOPvui9

**Comment by rktjmp** [comment]
https://tailwindcss.com/docs/hover-focus-and-other-states#first-child `:first` should be applied to to the children. 

```
<div>
<p class="first:bg-red-400">First with highlight</p>
<p class="first:bg-red-400">Middle without</p>
<p class="first:bg-red-400">Last without</p>
</div>
```

You can do what you want with `pl-3` instead. https://play.tailwindcss.com/cIoQOPvui9

**Comment by itmecho** [comment]
Ah so I was using it incorrectly anyway!

Thanks, that works for the positioning but I'm also trying to change the colour of nested div when the checkbox is checked. Maybe I'll just have to conditionally add the class when the value is true

**Comment by adamwathan** [comment]
Hey! As mentioned this is just a misunderstanding of how this feature works so going to close. Feel free to open a discussion or join our Discord server if you want to work through your specific design implementation questions with others in the community though 👍🏻

**Comment by brycewray** [comment]
Just a note from the peanut gallery . . . it would be nice if there were a thoroughly Tailwind way to do things like these (i.e., sibling items that likely aren't close enough to work with `peer` but are otherwise "connected"):

```css
#nav-Checkbox:checked ~ ul.nav-Menu li, #nav-Checkbox:checked ~ label#nav-Toggle #svg-close {
  @apply block;
}
#nav-Checkbox:checked ~ label#nav-Toggle #svg-menu {
  @apply hidden;
}
#nav-Checkbox:checked ~ ul.nav-Menu {
  @apply pb-4;
}
```
