### ISSUE TITLE
Terminal build error: "Cannot find module 'is-color-stop'"

### ISSUE THREAD

**Issue by jacobthesheep** [tailwindlabs/tailwindcss#5411]
### What version of Tailwind CSS are you using?

v.2.2.10

### What build tool (or framework if it abstracts the build tool) are you using?

postcss

### What version of Node.js are you using?

v14.17.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/jacobthesheep/personal-website

### Describe your issue

npm run build gives out this error: `(node:4808) UnhandledPromiseRejectionWarning: Error: Cannot find module 'is-color-stop'`
<img width="934" alt="Screen Shot 2021-09-06 at 13 53 38" src="https://user-images.githubusercontent.com/44789941/132260009-83afd294-6641-41a9-9b58-60223b6181f1.png">

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This issue has been fixed, I opened a PR on your repo that bumps tailwind to 2.2.11 which fixes the issue: https://github.com/jacobthesheep/personal-website/pull/2
