### ISSUE TITLE
Jit & webpack sass loader

### ISSUE THREAD

**Issue by gepopp** [tailwindlabs/tailwindcss#5427]
### What version of Tailwind CSS are you using?

2.2.10

### What build tool (or framework if it abstracts the build tool) are you using?

webpack 4.46.0

### What version of Node.js are you using?

12.18.3

### What browser are you using?

Chrome 

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/gepopp/SocialLoginAndRegister.git

### Describe your issue

Whenever i enable the JIT mode in my tailwind.js file i get the error as follows:
`
ERROR in ./assets/scss/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: expected ";".
    ╷
886 │     width: this-is\\]w-\\[weird-but-valid;
    │                     ^
    ╵
  assets\scss\styles.scss 886:18  root stylesheet
`

My tailwind.js file:

`
```
module.exports = {
    mode: "jit",
    purge: {
        enabled: true,
        content: [
            './**/*.php',
            './**/*.js'
        ]
    },
    theme: {},
    variants: {},
    plugins: [],
}
```
`

My webpack.config file:

```
const path                 = require('path');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const isProduction         = 'production' === process.env.NODE_ENV;

// Set the build prefix.
let prefix = isProduction ? '.min' : '';

const config = {
	entry: {
		main: './assets/js/main.js',
	},
	output: {
		filename: `[name]${prefix}.js`,
		path: path.resolve(__dirname, 'dist')
	},
	mode: process.env.NODE_ENV,
	module: {
		rules: [
			{
				test: /\.js$/,
				loader: 'babel-loader',
				options: {
					presets: [
						[
							"@babel/preset-env"
						]
					]
				}
			},
			{
				test: /\.s[ac]ss$/i,
				use: [MiniCssExtractPlugin.loader, 'css-loader', 'sass-loader',
					{
						loader: 'postcss-loader',
						options: {
							postcssOptions: {
								plugins: [
									require('postcss-import'),
									require('tailwindcss')('tailwind.js'),
									require('postcss-nested'),
									require('autoprefixer'),
								]
							}
						}
					}
				],
			},
		]
	},
	plugins: [new MiniCssExtractPlugin()]
}
module.exports = config
```

i have absolute no idea how to go about this, without jit mode enabeld everything compiles fine.

**Comment by adamwathan** [comment]
Hey! The issue here is your purge config:

```js
module.exports = {
    mode: "jit",
    purge: {
        enabled: true,
        content: [
            './**/*.php',
            './**/*.js'
        ]
    },
}
```

You are scanning _all_ JS files in the whole folder which is including `node_modules`. You'll want to make your config more specific so it is only catching your files. Right now it's seeing the actual tests in Tailwind itself in your `node_modules` folder which includes that bad value you're seeing which is breaking your CSS.

I can't tell where your content files are in your project but you probably want something more like this:

```js
module.exports = {
    mode: "jit",
    purge: {
        enabled: true,
        content: [
            './index.php',
            './SocialLoginAndRegister.php',
            './src/**/*.php',
            './assets/**/*.js'
        ]
    },
}
```

**Comment by gepopp** [comment]
Bam @adamwathan u are my hero, daved my day, thanks and friendy regards from vienna :)
