### ISSUE TITLE
Tailwind PostCSS plugin incompatible with postcss-use

### ISSUE THREAD

**Issue by weaversam8** [tailwindlabs/tailwindcss#5429]
### What version of Tailwind CSS are you using?

v2.2.11 (@latest)

### What build tool (or framework if it abstracts the build tool) are you using?

postcss-cli 8.3.1

### What version of Node.js are you using?

v15.13.0

### What browser are you using?

N/A

### What operating system are you using?

macOS Big Sur 11.5.1

### Reproduction repository

https://github.com/weaversam8/tailwind-postcss-use-bug

### Describe your issue

[postcss-use](https://github.com/postcss/postcss-use) is a PostCSS plugin that allows users to import other PostCSS plugins (from [a safelist](https://github.com/weaversam8/tailwind-postcss-use-bug/blob/4cd1160aa8290b575fb5c1b989ee719b01ec8c4b/postcss.config.js#L8)) from within CSS itself, by using an @use directive.

I tried to use this to import Tailwind (in order to [customize the `config` option of Tailwind's PostCSS plugin](https://tailwindcss.com/docs/configuration#using-a-different-file-name) on a per-file level), but Tailwind doesn't seem to function correctly in this scenario.

**Expected behavior:** Tailwind runs correctly and provides the correct generated CSS to PostCSS to output to the `/dist` directory.
**Actual behavior:** The plugin imports in some way but doesn't correctly compile / generate CSS. [The CSS generated in the `/dist` directory](https://github.com/weaversam8/tailwind-postcss-use-bug/blob/main/dist/default.css) includes raw Tailwind directives such as `@tailwind`, rather than preflight or any of the classes that passed purge.

I know that the plugin imports in some way, since validation is performed on the `config` option to ensure its a valid file path.

**Comment by adamwathan** [comment]
Hey! I cloned this down and tried really hard to debug it and no matter what I do, Tailwind itself is never even invoked.

I then tested with another PostCSS plugin (`postcss-discard-comments`, which is mentioned in the `postcss-use` docs) and that plugin doesn't work either.

It's looking to me like perhaps `postcss-use` just doesn't work anymore? It hasn't been updated in 3 years which is several major versions of PostCSS ago.

Here's a repo showing that `postcss-discard-comments` doesn't work either:

https://github.com/adamwathan/postcss-use-bug

I was able to get `postcss-discard-comments` to work by downgrading every dependency to their PostCSS 7 compatible versions, but I couldn't get it to build with our PostCSS 7 version of Tailwind :/

There might be something we could do to fix this for PostCSS 7 but ultimately this looks to me like a postcss-use/postcss issue, and as of next month we will be dropping support for PostCSS 7 entirely so I can't prioritize vs. other work unfortunately.

We've talked about adding support for per-file configs before as a first-class Tailwind feature though, and I'd rather solve this problem for you that way so hopefully that's something we can look at in the future.

Thanks for the well-presented issue ❤️ Sorry that I can't do more on this.

**Comment by weaversam8** [comment]
> Thanks for the well-presented issue ❤️ Sorry that I can't do more on this.

No problem, thanks for giving it a solid look! I think I'll try this using Mix like you suggested in #1489 for now. I also created an issue (postcss/postcss-use#43) reporting the PostCSS incompatibility in the postcss-use repo.
