### ISSUE TITLE
Invalid CSS being built because Tailwind includes `node_modules` in purge config

### ISSUE THREAD

**Issue by dcastil** [tailwindlabs/tailwindcss#5437]
### What version of Tailwind CSS are you using?

v2.2.10

### What build tool (or framework if it abstracts the build tool) are you using?

tailwindcss

### What version of Node.js are you using?

v14.17.5

### What browser are you using?

Chrome

### What operating system are you using?

Mac OS 11.5.2

### Reproduction repository

https://github.com/dcastil/tailwindcss-bug-weird-but-valid

### Describe your issue

I'm reopening https://github.com/tailwindlabs/tailwindcss/issues/5415 here as I think I've been misunderstood and that there is a real bug here (explanation in https://github.com/tailwindlabs/tailwindcss/issues/5415#issuecomment-914219720).

Here comes the original issue description 👇 

---

Since I upgraded from Tailwind `v2.2.7` to `v.2.2.10` I can't build my app anymore because Tailwind produces the invalid CSS

```css
.w-\[this-is\\\\\]w-\\\\\[weird-but-valid\] {
  width: this-is\\]w-\\[weird-but-valid;
}
```

This class doesn't exist in the project I'm working on. After a little digging, I found the class here: https://github.com/tailwindlabs/tailwindcss/blob/v2.2.10/src/jit/lib/setupContextUtils.js#L143

In the output CSS there are also other unrelated classes, so my theory is that Tailwind is accidentally searching the `node_modules` directory for Tailwind-classes.

**How to reproduce:**

1. Clone the repo https://github.com/dcastil/tailwindcss-bug-weird-but-valid and don't change the name of the created repo directory.
2. `yarn && yarn build`
3. Inspect `tailwind-out.css`

I added some comments to the `tailwind.config.js` which might help. The issue is connected to parent directory paths in the purge config.

**Comment by adamwathan** [comment]
Hey sorry for misunderstanding! Right now we don't support excluded paths, so the `!./node_modules` bit just doesn't do anything. I think we can probably at a bare minimum throw an error explaining that, and maybe one day we can actually work towards supporting it.

**Comment by dcastil** [comment]
Oh, I somehow assumed it would work. 😅 Now I checked the output css file and indeed there are a couple custom values which aren't present in the project even on `v2.2.7`. Sorry for the misunderstanding from my side. Closing this as resolved. Thanks! 🙏
