### ISSUE TITLE
Without a break-words equivalent, w-full resulting in different container sizes with a really long word

### ISSUE THREAD

**Issue by FullStackJohnMack** [tailwindlabs/tailwindcss#5446]
### What version of Tailwind CSS are you using?

2.2.7

### What build tool (or framework if it abstracts the build tool) are you using?

Tailwind Play

### What version of Node.js are you using?

Tailwind Play

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://play.tailwindcss.com/ErK7bni2bc

### Describe your issue

I can't get w-full to result in consistent widths when trying to break a REALLY long word. When I use break-all, it works correctly but chops off short words in the middle too. I tried to apply the min-w-0 tricks mentioned in other closed issues but couldn't figure it out.

Please see my Tailwind Play link to see the issue... the middle div shows the wider than normal container.

Is there a way to force this consistent width without having to chop words in the middle or specify a fixed width? I know its deprecated but break-words seems to be the thing that would work.

[https://play.tailwindcss.com/ErK7bni2bc](https://play.tailwindcss.com/ErK7bni2bc)

**Comment by adamwathan** [comment]
Hey @FullStackJohnMack! As you alluded to, I think the best fix here is `min-w-0` — you just have to add it to any flex child that needs to fill the available space.

I've made the change for you here:

https://play.tailwindcss.com/B0iRGVc24q

You can see here is where it was added:

![image](https://user-images.githubusercontent.com/4323180/132897053-ce945a2a-f644-4332-9d32-ee1239b1645d.png)

You'll probably find yourself needing this _lots_ even in situations not related to break words stuff, super common annoying little flex issue.

Hope that helps!

**Comment by FullStackJohnMack** [comment]
Wow, I tried lots of combinations of that min-w-0... there it is. Also, thanks for the tip in general. It's always interesting Googling generic CSS stuff versus Tailwind specific stuff but this really helps. Love what you're building! Thanks!

**Comment by myregistration** [comment]
I'm glad I ran across the hack of adding min-w-0.  I hope they figure out a better solution.
