### ISSUE TITLE
mode JIT doesn't auto generate classes. It only generates classes on initial launch

### ISSUE THREAD

**Issue by rromikas** [tailwindlabs/tailwindcss#5459]
### What version of Tailwind CSS are you using?

npm:@tailwindcss/postcss7-compat@^2.2.7"

### What build tool (or framework if it abstracts the build tool) are you using?

craco: "^6.2.0" in react app

### What version of Node.js are you using?

v14.16.1

### What browser are you using?

chrome

### What operating system are you using?

windows

### Reproduction repository

github.com

### Describe your issue

mode JIT doesn't auto generate classes. It only generates classes on initial launch

**Comment by harvanchik** [comment]
I thought I was alone.  This also started happening to me just recently.  Nothing changed in my project, but suddenly, the styles were not being generated.

**Comment by reinink** [comment]
Hey thanks for reporting, are you able to provide a reproduction repository?

**Comment by adamwathan** [comment]
Hey! I created a new CRA project and was able to reproduce using the default setup. The trick to getting it to work is to add the `TAILWIND_MODE=watch` environment variably, which we explain in the JIT troubleshooting guide here:

https://tailwindcss.com/docs/just-in-time-mode#styles-don-t-update-when-saving-content-files

I've created a demo repo showing things working that you can look at here:

https://github.com/adamwathan/tailwind-jit-cra-example

This is currently a CRA issue I'm afraid, and has to do with the fact that the latest CRA release is still very old with very old dependencies. Once CRA has been updated for webpack 5, things will work a lot more smoothly.

I would recommend switching from CRA to Vite for new projects, as it does everything CRA does but is faster and more modern.

Hope that helps!

**Comment by rromikas** [comment]
Hi,
I tried to set TAILWIND_MODE=watch when launching app, but it's still not working. When I change class in app component from  "w-[768px]" to "w-[876px]" it doesn't auto-generate new class. Here is the repository [https://github.com/rromikas/jit-not-working](https://github.com/rromikas/jit-not-working)

**Comment by harvanchik** [comment]
> Hi,
> It's not working. Repository https://github.com/rromikas/jit-not-working

Since the issue is closed, Adam likely will not reply.

The difference between your project and the example he made is your start script.
In his, he only has `TAILWIND_MODE=watch craco start`, but yours is `set PORT=3012 && set TAILWIND_MODE=watch && craco start`.  Have you tried using his start script, and did it still not work?  If so, you should re-open this issue.

**Comment by reinink** [comment]
Hey thanks for jumping in here @harvanchik. Does that help @rromikas?

**Comment by rromikas** [comment]
No, that doesn't help

**Comment by shameekbaranwal** [comment]
Hi @rromikas, as mentioned by Adam [here](https://github.com/tailwindlabs/tailwindcss/issues/4023#issuecomment-836908441), 

> Using `&&` starts a separate command and the environment variable isn't actually applied. Without setting `NODE_ENV=development`, Tailwind won't start watching for template changes.

So try using `PORT=3012 TAILWIND_MODE=watch craco start` as your start script. I was having a similar issue, but this solved it for me.
