### ISSUE TITLE
after change className, the style didn't show

### ISSUE THREAD

**Issue by suhaotian** [tailwindlabs/tailwindcss#5475]
### What version of Tailwind CSS are you using?

2.2.14

### What build tool (or framework if it abstracts the build tool) are you using?

create-react-app

### What version of Node.js are you using?

v12.18.2

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

no

### Describe your issue

after upgrade tailwindcss version, change className, the style didn't work. before I use 2.2.10, it's ok

**Comment by timvandaatselaar** [comment]
I had the same kinda problem after updating Tailwind, in some cases you need to add `TAILWIND_MODE=watch` to your run script in package.json: 

**For example**
"start": "TAILWIND_MODE=watch react-scripts start"

**Comment by suhaotian** [comment]
@timvandaatselaar good, thanks man
