### ISSUE TITLE
Laravel Mix HMR CSS and Tailwind class generation breaks when compiling 2 JS files

### ISSUE THREAD

**Issue by sebastiaanluca** [tailwindlabs/tailwindcss#5477]
### What version of Tailwind CSS are you using?

2.2.15

### What build tool (or framework if it abstracts the build tool) are you using?

Laravel Mix 6.0.6

### What version of Node.js are you using?

v14.17.0

### What browser are you using?

Firefox Developer Edition, Chrome, …

### What operating system are you using?

macOS Big Sur

### Reproduction repository

https://github.com/sebastiaanluca/tailwind-hmr-bug

### Describe your issue

In a fresh Laravel application served with Valet, Tailwind JIT mode doesn't create classes or update `app.css` **for classes used in Vue components** when using hot reload (`mix watch --hot` or `TAILWIND_MODE=watch mix watch --hot`) **in combination with compiling 2 JS files** (as far as I was able to reproduce). The watcher runs fine and it builds the files, but it won't create and inject the CSS.

It works fine in Blade views because BrowserSync refreshes the page for you, but not in Vue components where the CSS is injected when using hot reload. It'll also create them when running `npm run watch`, `npm run dev`, or `npm run production`.

It took a while to find the issues, but I've successfully reproduced the bug in a fresh Laravel app: https://github.com/sebastiaanluca/tailwind-hmr-bug

I had this issue in my main app and thought the cause was BrowserSync or some odd configuration, but I followed the installation instructions from scratch (https://tailwindcss.com/docs/guides/laravel) and updated it to use JIT mode (https://tailwindcss.com/docs/just-in-time-mode).

Similar issue to https://github.com/tailwindlabs/tailwindcss/issues/4978, https://github.com/tailwindlabs/tailwindcss/issues/5135, and https://github.com/tailwindlabs/tailwindcss/issues/4833.

**Comment by gcavanunez** [comment]
Hi, not sure if it may be a limitation/error on the tailwindcss side nor if this would be of aid in any way but have you tried changing the configuration of the css file that's importing tailwindcss to be as such. 

```js
  .postCss("resources/css/app.css", "public/css", [
    require("postcss-import"),
    require("tailwindcss"),
    require("autoprefixer"),
  ]) 
```

Also does the issue continue if not using the tailwindcss css import file?

**Comment by sebastiaanluca** [comment]
@gcavanunez No change with the sorted require statements nor with the way Tailwind is imported (i.e. using `@tailwind base` instead of `@import 'tailwindcss/base'`).

**Comment by sebastiaanluca** [comment]
I set up my project using Vite now and am encountering the same issue. Newly used styles are not generated, only previously used ones. I have to restart the dev/build process for them to be generated. Maybe related to https://github.com/vitejs/vite/issues/4150

**Comment by adamwathan** [comment]
Gonna try and look into this for you tomorrow ❤️

**Comment by sebastiaanluca** [comment]
Thanks, man! Whenever you have time. If you need anything from me, let me know.

Currently trying out some combinations and figuring out why this doesn't work with Vite either. Not making much progress.

1. Vite + JIT off = HMR works fine, styles are updated, editing `tailwind.config.js` detects the change but doesn't update anything
2. Vite + JIT on = HMR works fine, styles are **not** generated and updated, editing `tailwind.config.js` detects the change but doesn't update anything

Same with Webpack.

I have tried:
- Clearing npm cache
- Removing and reinstalling node_modules
- Quitting any file sync app that might interfere with fsevents
- Fixing my drives and permissions
- Renaming and moving the project
- Setting up a totally unrelated reproduction project
- Using 1 JS input file
- Following the installation guide
- Using the most basic setup
- And so on, you get the gist 😄

So on the one hand you've got HMR that works, but doesn't generate styles when JIT mode is enabled. On the other, changing the Tailwind configuration file doesn't trigger any changes. Maybe we need to focus on one here. Don't really care I can't edit the config on-the-fly when JIT mode works.

**Comment by gcavanunez** [comment]
@sebastiaanluca any chance you could put together a minimal reproduction repo showing the vite setup you got going?

**Comment by sebastiaanluca** [comment]
I'll try to do so asap, but currently short on time. I've reverted my active setup to not use JIT, but not having that nor HMR when editing the Tailwind config is a bit annoying.

**Comment by sebastiaanluca** [comment]
We've set up a new project with Webpack and multiple devs in our team have the issue where Tailwind doesn't generate new classes that aren't already in `public/app.css` or memory.

I have noticed there are 2 (related?) issues at play here:

**HMR does not reload the view**, only a manual reload uses the new classes. I believed this was due to having 2 `mix.js()` calls in `webpack.mix.js`. Reproducible in https://github.com/sebastiaanluca/tailwind-hmr-bug.

HMR reloads, but **Tailwind CSS JIT did not generate the new classes** (like as if it didn't scan the files or did not find the new classes). Using already generated classes works fine. Reproducible in https://github.com/sebastiaanluca/tailwind-hmr-bug-2.

These only started happening with Tailwind JIT (alpha), regardless if using Webpack or Vite. I haven't been able to pinpoint the exact issue, as it works in some projects, but not in others. Previously didn't work for my own site, but a Vite upgrade then fixed it. I'm assuming it's something in the JS or CSS setup, app.js or app.css.

So yeah 😅 Hope someone can find some time to look into it, can't be the only one having this?

**Comment by thecrypticace** [comment]
I've opened https://github.com/laravel-mix/laravel-mix/issues/3225 to track this and will handle it over there.

**Comment by sebastiaanluca** [comment]
I did have it with Vite too, not using Laravel Mix or Webpack at all, so that's why I believed it was a Tailwind bug. But hopefully someone will pick it up over there. Although with ~160 open issues, there's little progress and I don't think it'll get sorted soon 😬  Thanks for checking and opening the issue there!

**Comment by plumduffer** [comment]
This is also happening with me on the latest Laravel Mix and Tailwindcss.
