### ISSUE TITLE
impossible to have `disabled` state lighter than the base

### ISSUE THREAD

**Issue by tvardy** [tailwindlabs/tailwindcss#5479]
### What version of Tailwind CSS are you using?

2.2.14

### What build tool (or framework if it abstracts the build tool) are you using?

CRA + Storybook

### What version of Node.js are you using?

14.x

### What browser are you using?

All modern

### What operating system are you using?

macOS, Windows, Linux

### Reproduction repository

none

### Describe your issue

If I set up a dark button:

```
<button type="button" class="py-3 px-8 border-2 rounded-full font-medium hover:border-black focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-black bg-gray-900 text-white border-black disabled:border-gray-600 disabled:bg-gray-600 disabled:cursor-default disabled:text-gray-200" disabled="">Primary Button</button>
```

then only text color changes as it goes from `white` to `gray-200`, but unfortunately, the `bg-gray-900` takes precedence over `disabled:bg-gray-600`

**Comment by adamwathan** [comment]
Hey! I pasted your exact code into a Tailwind Play and it works as expected:

https://play.tailwindcss.com/3rtncBaam4

Hopefully you can figure out the difference between what I've done and your own project, but if still an issue please open a new issue and include a reproduction. As we mention in the issue template, a minimal reproduction is required when submitting an issue, thanks.
