### ISSUE TITLE
how to use tailwinds @apply with @layer directive from a Svelte component

### ISSUE THREAD

**Issue by opensas** [tailwindlabs/tailwindcss#5493]
### What version of Tailwind CSS are you using?

"tailwindcss": "^2.2.4"

### What build tool (or framework if it abstracts the build tool) are you using?

SvelteKit

### What version of Node.js are you using?

v14.17.6

### What browser are you using?

Firefox, chrome

### What operating system are you using?

Linux xps 5.4.0-84-generic #94~18.04.1-Ubuntu

### Reproduction repository

https://github.com/opensas/tailwind-apply

### Describe your issue

I want to use apply to define some css setting on a component, and I also want to be able to overwrite it, like this:

```svelte
<!-- CustomButton.svelte -->
<script>
    let className = '';
    export { className as class };
    export let label = 'Click me!';
</script>

<button class="custom-button {className}">{label}</button>

<style lang="postcss">
.custom-button {
    @apply bg-blue-400 font-bold text-white rounded-lg p-4;
}
</style>
```

And I want to use it like this:

```svelte
<script>
    import CustomButton from './CustomButton.svelte';
</script>

<div class="w-screen h-screen flex justify-center items-center">
    <CustomButton class="bg-red-800" label="This is my button" />
</div>
```

That is, I want to be able to override my @applied settings

The problem is that the settings from the `@apply` directives cannot be overriden by this line

```svelte
<button class="custom-button {className}">{label}</button>
```

I understand that in order to do that I have to tell tailwind to generate the corresponding css in the components layer, that is, before the utilities.

If I enter the same css directive in my app.post.css file, before the @tailwind utilities line, or using the @layer components directives it works ok:

```css
/* app.post.css */

@tailwind base;
@tailwind components;
@tailwind utilities;

/* This works ok! */
@layer components {
  .custom-button {
    @apply bg-blue-400 font-bold text-white rounded-lg p-4;
  }
}
```

So, what I want is some way to tell tailwind to add the `.custom-button` setting I defined in my `CustomButton.svelte` component to the components layer, so that it could be overriden with inline clases.

If I try to do this in my CustomButton.svelte file

```svelte
<style lang="postcss">
    @layer components {
        .custom-button {
            @apply bg-blue-400 font-bold text-white rounded-lg p-4;
        }
    }
</style>
```

I get the following error:

```
9:13:34 PM [vite] Internal server error: /home/sas/devel/apps/glas-it/apps/wingback/end-user-portal/src/routes/CustomButton.svelte?svelte&type=style&lang.css:1:1: `@layer components` is used but no matching `@tailwind components` directive is present.
  Plugin: vite:css
```

This issue is preventing me from using the @apply directive from any component.

Is there some way to achieve this?

Steps to reproduce

open: https://gitpod.io#github.com/opensas/tailwind-apply

```
npm install
npm run dev
```

click on `http://localhost:3000`

Allow popups from...

This is the result:

![image](https://user-images.githubusercontent.com/481687/133160683-2331404d-4305-4b96-a014-753bb80e14a8.png)

Expected behaviour:

I'd like to be able to define @apply commands that should go to the @component layer from a svelte component, so that I can override it with inline styles.

---

see also: this question at [SO](https://stackoverflow.com/questions/69059757/how-to-use-tailwinds-apply-with-layer-directive-from-a-svelte-component)

**Comment by nbgoodall** [comment]
Correct me if I'm wrong but this doesn't seem like an issue with Tailwind, perhaps something for the [discussions board](https://github.com/tailwindlabs/tailwindcss/discussions), or SO as you already mentioned?
