### ISSUE TITLE
Background image not working

### ISSUE THREAD

**Issue by tengkuzulfadli** [tailwindlabs/tailwindcss#5505]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/5504

<div type='discussions-op-text'>

<sup>Originally posted by **tengkuzulfadli** September 15, 2021</sup>
Hi,

I already followed all the instructions that related to my issue and  I also installed the latest version, but the background image is still not working.

Can anyone spot any mistakes that I made, maybe from the project folders arrangement or wrongly used the src link on the config file?

Appreciate your assistance!!
![Screenshot (105)](https://user-images.githubusercontent.com/62935899/133374522-0274828e-f4d3-423c-854e-d2737052b7a3.png)
![Screenshot (106)](https://user-images.githubusercontent.com/62935899/133374527-2f2dc578-4afe-4c52-b2a1-1a6c5b234606.png)
</div>

**Comment by adamwathan** [comment]
Closing in favor of https://github.com/tailwindlabs/tailwindcss/discussions/5504
