### ISSUE TITLE
Generated negative classes with custom prefixes aren't formatted correctly

### ISSUE THREAD

**Issue by kburke-tp** [tailwindlabs/tailwindcss#5513]
**What version of Tailwind CSS are you using?**

v2.2.7

**What build tool (or framework if it abstracts the build tool) are you using?**
```
        "postcss": "^8.3.6",
        "postcss-cli": "^6.1.3",
```

**What version of Node.js are you using?**

v12.x

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/VXNRuw7mJ6

**Describe your issue**

The negative classes generated by Tailwind are formatted as `u--m-3` when designating `u-` as a custom prefix. Per https://tailwindcss.com/docs/margin#negative-values, the assumed formatting is `-u-m-3`. Barebones reproduction linked below.

**Comment by adamwathan** [comment]
Hey! For better or for worse this is how it's been for several years, and changing it would be a really painful breaking change for existing users so no plans to change this unfortunately. It might feel a bit less awkward if you use a prefix that doesn't contain a dash, like `u_-mt-3` or `u/-mt-3`.
