### ISSUE TITLE
Performance regression from version 1 to 2

### ISSUE THREAD

**Issue by johanobergman** [tailwindlabs/tailwindcss#5524]
**What version of Tailwind CSS are you using?**

v2.2.15

**What build tool (or framework if it abstracts the build tool) are you using?**

Doesn't matter, provided example using CDN.

**What version of Node.js are you using?**

N/A

**What browser are you using?**

Tested on Safari 14.1.2

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/johanobergman/tailwind-perf-regression
https://tailwind-perf.netlify.app

**Describe your issue**

The browser has to spend a lot more time recalculating styles on Tailwind 2 compared to Tailwind 1. I have a calendar UI which uses quite a bit of flexbox utilities, and it takes my computer about 5 times longer to transition to that page on Tailwind 2.

When profiling using the timeline in Safari dev tools there's a significant increase in time for "Recalculate styles" under  "Layout and rendering", and the delay in my application can add up to several hundred milliseconds, making it feel noticeably slower. The same happens in Chrome but is less noticeable.

I think I've been able to narrow it down to the flex utilities (although there may be more classes affected). The reproduction only uses `flex` and `flex-1` along with some heights, widths and borders for illustration purposes.

**Comment by adamwathan** [comment]
Can you try adding this to your config file:

```js
// tailwind.config.js
module.exports = {
  experimental: {
    optimizeUniversalSelectors: true
  },
  // ...
}
```

Requires latest version of Tailwind (2.2.15) but fingers crossed it solves this problem for you.

**Comment by johanobergman** [comment]
That didn't fix it - but it led me to inspect the purged css file further, and I found one css declaration that seems to cause the issue (at least in my reproduction, there might be other cases with classes I didn't use).

```css
*,
::before,
::after {
  --tw-border-opacity: 1;
  border-color: rgba(229, 231, 235, var(--tw-border-opacity)); /* This line */
}
```

I used a lot of borders in the reproduction, but removing them made no difference. But when I comment out the line above (regardless of border classes in the html), everything renders as quickly as in Tailwind 1.

Commenting out the same line in my real app does improve rendering quite a bit, but still far from Tailwind 1. My guess is that there are more global "star"-declarations that somehow slow things down.

**Comment by adamwathan** [comment]
Ah I made a mistake, the flag is `optimizeUniversalDefaults` — can you try that?

**Comment by johanobergman** [comment]
That worked out better! I had to turn on `mode: 'jit'` for it to take effect, but now the `border-color` declaration looks like this instead:

```css
.border {
  --tw-border-opacity: 1;
  border-color: rgba(229, 231, 235, var(--tw-border-opacity));
}
```

and in my reproduction it's now slightly faster than Tailwind 1!

Tested in my real project using a real world scenario:

Tailwind 1: 65ms
Tailwind 2: 520ms
Tailwind 2 + optimization: 85ms

So it seems like we're good again (slightly slower in my app so I guess there's some more room for optimization).

One issue I had in my real app (not in the repro) was that the generated border selector began with a comma, so I had to manually remove that from the generated css.

```
warnings when minifying css:
 > <stdin>:581:0: warning: Unexpected ","
    581 │ , .border, .border-2, .border-l-4, .border-b, .border-t, .border-b-...
        ╵ ^
```

**Comment by adamwathan** [comment]
Great glad that helps! Can you provide a reproduction for that comma issue? Would like to track that down and fix, haven't seen that in our own use.

**Comment by adamwathan** [comment]
Going to mark this as resolved for now, if you do end up being able to provide a reproduction for the comma thing that would be helpful. If not I'm sure it will pop up through someone else soon!

**Comment by johanobergman** [comment]
It's happening when `border-b` (again, could be others as well) and `divide-y` are both included, but only when `optimizeUniversalDefaults` is on.

See repro: https://github.com/johanobergman/tailwind-class-bug, the unwanted comma appears here: https://github.com/johanobergman/tailwind-class-bug/blob/master/tailwind.css#L598
