### ISSUE TITLE
Tailwind doesn't style my page when I enable jit mode

### ISSUE THREAD

**Issue by k4l3b-plo** [tailwindlabs/tailwindcss#5532]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/5531

<div type='discussions-op-text'>

<sup>Originally posted by **k4l3b-plo** September 17, 2021</sup>
I started a React project from scratch(without create-react-app) after configuring tailwindcss all seems to work fine but when I enable jit mode my page reverts to an unstyled plain HTML page.

**What version of Tailwind CSS are you using?**
2.2.6

**What build tool (or framework if it abstracts the build tool) are you using?**
webpack 5.53.0, postcss 8.3.6

**What version of Node.js are you using?**
14.17.0

**What browser are you using?**
Chrome(Brave)

**What operating system are you using?**
Windows

**Reproduction repository**
https://github.com/k4l3b-plo/tailwind-myissue
</div>

**Comment by adamwathan** [comment]
Closing in favor of the original discussion thread.
