### ISSUE TITLE
[JIT] make JIT mode parse lit-html template too

### ISSUE THREAD

**Issue by beebole** [tailwindlabs/tailwindcss#5557]
**What version of Tailwind CSS are you using?**

2.2.9

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite 2.5.3

**What version of Node.js are you using?**

14.17.5

**What browser are you using?**

Chrome, Firefox

**What operating system are you using?**

macOS

**Reproduction URL**

N/A

**Describe your issue**

Would it be possible to have JIT mode to take into account classes defined in lit-html templates ?
Shadow DOM being turned off.

By detecting the syntax:
``html`<button class="bg-blue-400 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded">${data.title}</button>
`;``

Anyone could guide me to the source file/function where this should be implemented, so I could try to make it myself ?

**Comment by adamwathan** [comment]
Hey! This should work already, here's a test I just added for it (ignore the CI failure, that's a different test that I fixed right after):

https://github.com/tailwindlabs/tailwindcss/commit/b7d2c8f11e44351373760736bcbf34a24d0f42ad

![image](https://user-images.githubusercontent.com/4323180/134212633-246f2c21-e078-44e1-bbcf-348e62997d8b.png)

Going to move this to discussions as it sounds like you just need help getting your specific project setup and that this isn't actually a Tailwind bug 👍
