### ISSUE TITLE
CDN file size 2.9MB

### ISSUE THREAD

**Issue by bigskillet** [tailwindlabs/tailwindcss#5573]
**What version of Tailwind CSS are you using?**

v2.2.15

**What build tool (or framework if it abstracts the build tool) are you using?**

CDN

**Reproduction URL**

https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css

**Describe your issue**

The documentation says that the minified CDN is around 71.4kB, but if you download the file, you'll see that it's actually 2.9MB.

**Comment by adamwathan** [comment]
Hey! The docs are correct, it is about 71kb when compressed at the max rate with Brotli. It's 2.9mb minified but _uncompressed_.

From the docs:

![image](https://user-images.githubusercontent.com/4323180/134438268-2ac313c6-bfed-415f-90a7-d3edca8d323c.png)

Don't use the CDN, it's huge 😜🍻

**Comment by joshxyzhimself** [comment]
Hi, is it possible to produce this minified builds on 3.x branch?

It's kinda useful for one-pager static sites
