### ISSUE TITLE
Issue using tailwind in an external repository

### ISSUE THREAD

**Issue by kurt-hardy** [tailwindlabs/tailwindcss#5608]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/5084

<div type='discussions-op-text'>

<sup>Originally posted by **kurt-hardy** July 26, 2021</sup>
Hi

I have about 7 different repos which all have there own tailwind setup (EG 7 different repos with 7 different versions of the same button)

I have thus created a private repo to remove this duplication but I'm having issues with JIT and purging. If I remove the purge, it works. Is there a way I can tell tailwind to include the classes from my external repo?

eg ` <Button colour="brand" size={ButtonSize.sm} className="my-8">Sign in</Button>`

Thanks</div>

-----------------------------------------------------------------
I thought this was working but its not 100% right.

My button has these classes
`inline-flex justify-center items-center border font-medium rounded focus:outline-none focus:ring-2 focus:ring-opacity-30 transition text-base px-4 py-2 cursor-not-allowed border-transparent text-gray-200 bg-primary-700 shadow-sm rounded mr-4
`

But only the classes I have used in the site are applied.
EG My page uses `mr-4`, my button uses `mr-4` and `py-2` but the button only has the `mr-4` class applied.

I have this in my purge content: '.node-modules/\@company/react-tailwind/lib/**/*.{ts,tsx}'

Any ideas?
Thanks

**Comment by adamwathan** [comment]
Closing in favor of original discussion since not a Tailwind bug and just a request for help 👍🏻

**Comment by kurt-hardy** [comment]
Hi @adamwathan 

Is this not an issue? I got the help from the originally discussion and I have the recommended purge content but its not working as expected. 

Thanks 
Kurtis
