### ISSUE TITLE
Why order of classes changed?

### ISSUE THREAD

**Issue by hta218** [tailwindlabs/tailwindcss#5797]
**What version of Tailwind CSS are you using?**

`v2.2.7` (updated to `v3.0.0-alpha.1`) but still the same

**What build tool (or framework if it abstracts the build tool) are you using?**

webpack `5.24.3`

**What version of Node.js are you using?**

`v14.17.0`

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS BigSur 11.6

**Reproduction URLs**

Now (**unexpected**): [https://hta218.myshopify.com/products/yoga-a-manual-for-life?variant=41044203864234](https://hta218.myshopify.com/products/yoga-a-manual-for-life?variant=41044203864234)
Before (**expected**): [https://demo.minimog.co/](https://demo.minimog.co/)

**Describe your issue**

I don't know what the reason is but the order of classes just changed

What it was before:
![image](https://user-images.githubusercontent.com/24975260/137426571-aa8d38a2-c95a-4e9c-a86c-f033005df648.png)

Now:
![image](https://user-images.githubusercontent.com/24975260/137426602-4677f2b8-9585-4128-b65e-eacdbf760eea.png)

As you see, the `.opacity-100` now come before `.opacity-0`, which makes all nodes like `<div class="opacity-0 opacity-100"></div>` has the opacity `0` now (which was `1` before)

Do you know what the reason is? If it's a bug, please help to fix it 🙏

My current version is `2.2.x`, tried to update to `3.` but still the same. You can take a look at the order of the CSS built in the **Reproduction URLs** above (see `theme.css` file in **Network** tab and search for `opacity-100`)

**Comment by adamwathan** [comment]
Hey! This is a change in the JIT engine, the order of classes within the same category isn't guaranteed anymore for performance reasons. You shouldn't have `opacity-0` and `opacity-100` on the same element at the same time regardless though, our VS Code extension for example has marked this as an error for a long time:

![image](https://user-images.githubusercontent.com/4323180/137586571-7e41b925-03d2-4522-b4f9-6dbdddeedd24.png)

If you are conditionally adding one class, make sure to conditionally remove the other class as well.
