### ISSUE TITLE
`<dfn>` default style isn't reset

### ISSUE THREAD

**Issue by felixdorn** [tailwindlabs/tailwindcss#5805]
**What version of Tailwind CSS are you using?**

v2.2.17

**What browser are you using?**

Firefox 

**What operating system are you using?**

Linux

**Reproduction URL**

https://play.tailwindcss.com/MliDYmADzm

**Describe your issue**

The reset does not remove the italic style applied to `dfn` element by every user agent I could test (Firefox, Chrome).

**Comment by adamwathan** [comment]
See comment here: https://github.com/tailwindlabs/tailwindcss/pull/5810#issuecomment-945090978

Thanks either way 🍻
