### ISSUE TITLE
Normalize the scales of max width and max height with their width and height counterparts

### ISSUE THREAD

**Issue by Soviut** [tailwindlabs/tailwindcss#5811]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/4937

<div type='discussions-op-text'>

<sup>Originally posted by **Soviut** July  9, 2021</sup>
With the advent of JIT mode, it is no longer necessary to save space by having different scales for max width/max height and width/height.

Ideally, I should be able to take any width `w-1/2` and add the `max-` prefix to it without having to consult the documentation.

This could also mean giving `sm`, `md`, `lg`, `xl`, `2xl`, etc. lengths that max-width has to width (and height).</div>

**Comment by velocity23** [comment]
@Soviut I had a little look into it... I was going to standardize all of the `maxHeight`, `minHeight`, `maxWidth`, `minWidth`, `height`, and `width` properties so that in theory you can add/remove/change the `min-` and `max-` prefixes like you described. Pretty much a case of just copy and pasting the values from the height and width properties in the default config.

**Comment by Soviut** [comment]
@velocity23 excellent! please add me to any PR you set up. I'd be happy to do some review. Theoretically we should be able to establish a single list of heights and a single list of widths and just add just run them through a prefixing step.

**Comment by velocity23** [comment]
Great! Before I do go ahead and open a PR though, just want to confirm that it is something that the team is willing to add? Feels wrong to tag Adam here, will they just get around to looking at this issue when they get a chance?

**Comment by Soviut** [comment]
@velocity23 I'm not sure how long it would take for them to get a look at it. I figure the PR would be a good opportunity to gamble in order to accelerate the process.

Just to be clear, you're just looking at adding more options to the defaultConfig, right?
https://github.com/tailwindlabs/tailwindcss/blob/master/stubs/defaultConfig.stub.js

**Comment by henningway** [comment]
I am currently updating our project to Tailwind 3.0 and I have stumbled over this. Great to see this is being addressed already! Thanks for the effort.

**Comment by sijo-neoito** [comment]
Haai can i get a offer with work with you

**Comment by adamwathan** [comment]
Hey folks! Going to close this in favor of discussing it in the PR since this is more of a feature request than a bug 👍
