### ISSUE TITLE
PostCSS compilation returns "TypeError: Cannot read property 'filter' of undefined" after an npm update

### ISSUE THREAD

**Issue by EmperorKonstantin** [tailwindlabs/tailwindcss#5850]
**What version of Tailwind CSS are you using?**

For example: v2.2.17

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: postcss-js 8.3.11

**What version of Node.js are you using?**

For example: v12.21.0

**What operating system are you using?**

For example: Pop_OS! (Ubuntu / Debian distro)

**Describe your issue**

Doing an `npm update` broke tailwindcss JIT compilation. If i remove `mode: 'jit',` from tailwind.config.js it compiles normally.

```bash
➜  tailwind git:(main) ✗ npm run prod

> NODE_ENV=production postcss tailwind-source.css -o ../css/styles.css && npm run minify && npm run output-success

TypeError: Cannot read property 'filter' of undefined
    at /home/ant/dev/app/tailwind/node_modules/tailwindcss/lib/jit/lib/resolveDefaultsAtRules.js:39:60
    at Array.map (<anonymous>)
    at Root.map (/home/ant/dev/app/tailwind/node_modules/postcss-selector-parser/dist/selectors/container.js:347:23)
    at Processor.func (/home/ant/dev/app/tailwind/node_modules/tailwindcss/lib/jit/lib/resolveDefaultsAtRules.js:38:20)
    at Processor._runSync (/home/ant/dev/app/tailwind/node_modules/postcss-selector-parser/dist/processor.js:102:26)
    at Processor.transformSync (/home/ant/dev/app/tailwind/node_modules/postcss-selector-parser/dist/processor.js:171:17)
    at extractElementSelector (/home/ant/dev/app/tailwind/node_modules/tailwindcss/lib/jit/lib/resolveDefaultsAtRules.js:47:47)
    at /home/ant/dev/app/tailwind/node_modules/tailwindcss/lib/jit/lib/resolveDefaultsAtRules.js:82:30
    at /home/ant/dev/app/tailwind/node_modules/tailwindcss/lib/jit/processTailwindFeatures.js:64:50
    at /home/ant/dev/app/tailwind/node_modules/tailwindcss/lib/jit/index.js:25:56
```

Anyone have any idea what could be causing this?

**Comment by arvindanta** [comment]
@EmperorKonstantin  I am also facing the same issue. Did u find a way to make it work?

**Comment by EmperorKonstantin** [comment]
Nothing yet aside from commenting out these 2 broken classes.

**Comment by EmperorKonstantin** [comment]
Nothing yet aside from commenting out these 2 broken classes. I rely pretty heavily on the JIT engine for custom classes so I can't use the legacy engine.

**Comment by adamwathan** [comment]
Thanks for the reproduction! I haven't had a chance to clone and test but a quick peak makes me think this is related to how you have nesting set up, try switching things to match the instructions here:

https://tailwindcss.com/docs/using-with-preprocessors#nesting

**Comment by EmperorKonstantin** [comment]
Looks like your right Adam! 

Changing postcss.config.js from

```js
module.exports = {
    plugins: [
        require('postcss-import'),
        require('tailwindcss'),
        require('postcss-nested'),
        require('autoprefixer'),
    ]
}
```

to 

```js
module.exports = {
    plugins: [
        require('postcss-import'),
        require('tailwindcss/nesting'),
        require('tailwindcss'),
        require('autoprefixer'),
    ]
}
```

Resolves the issue and it no longer errors out with TypeError. I wonder if there's a way to make the error clearer, but I suppose once google indexes this issue others will be able to find the solution to it.

**Comment by RobinMalfait** [comment]
Glad it's working @EmperorKonstantin!
