### ISSUE TITLE
Media Queries not working well

### ISSUE THREAD

**Issue by realdev04** [tailwindlabs/tailwindcss#5856]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/5852

<div type='discussions-op-text'>

<sup>Originally posted by **realdev04** October 22, 2021</sup>
Media Queries in TailWind CSS are not working Well.<br/>

*My Code is this*
``` html
<img src={MYIMAGE} alt="Test Image" className="h-6 w-8 rounded-md gfold:h-8 gfold:w-14 gfold:rounded-xl sm:h-16 sm:w-24 " />
```
`gfold` -> `(400px)` - A Media Size included by me in the `tailwind.config.js` file. <br/>
`sm` -> `(640px)` - A Default Media Size that Comes with Tailwind.

This is the Code in [Tailwind Play](https://play.tailwindcss.com/KAYPfXUSwO?size=332x720)

When Media Size is below `sm` size is correct, But when my screen is greater than the `sm` size the ***Size is not Changing***.

**I want to Change the Image Size when the Screen Size Changes**

Now what should I do? *Please help me*, I am new to Tailwind CSS.</div>

**Comment by adamwathan** [comment]
Closing in favor of original discussion.
