### ISSUE TITLE
vite `server.origin` breaks tailwind JIT HMR

### ISSUE THREAD

**Issue by leevigraham** [tailwindlabs/tailwindcss#5877]
**What version of Tailwind CSS are you using?**

2.2.17

**What build tool (or framework if it abstracts the build tool) are you using?**

vite 2.6.10

**What version of Node.js are you using?**

12

**What browser are you using?**

Firefox / Chrome / Safari

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/leevigraham/vite-hmr-issue-repro

**Describe your issue**

Vite added a new server.origin property to it's config which: "Defines the origin of the generated asset URLs during development.". This is required for laravel or other backend rendered sites.

Setting the server.origin property breaks tailwind JIT HMR when editing templates. It looks like tailwind isn't even re-rendering the CSS. Editing the .pcss file works as expected.

Repro README has steps to reproduce the issue: https://github.com/leevigraham/vite-hmr-issue-repro/blob/main/README.md

My gut feeling is that this issue is more Vite than Tailwind.

Related vite issue: https://github.com/vitejs/vite/issues/5408

**Comment by khalwat** [comment]
Looks like they've fixed it (no release cut yet tho): https://github.com/vitejs/vite/pull/5571

**Comment by leevigraham** [comment]
Closing this because it's an upstream vite issue and likely fixed in vitejs/vite#5571
