### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by tengkuzulfadli** [tailwindlabs/tailwindcss#5973]
Hi,

I'm having an issue now;

--> When I set a style for a sm screen, it changes to all screen sizes.
--> I tried to override with a plain css or even using classes, still not working
--> I reinstalled using the latest version of Nextjs and Tailwindcss, still not working

How can I solve this issue?

_Originally posted by @tengkuzulfadli in https://github.com/tailwindlabs/tailwindcss/discussions/5972_

**Comment by adamwathan** [comment]
Closing, the original discussion thread is a better place for this.
