### ISSUE TITLE
compiler doesn't render interpolated values

### ISSUE THREAD

**Issue by alaadahmed** [tailwindlabs/tailwindcss#6020]
**What version of Tailwind CSS are you using?**

TailwinCSS: __`v3.0.0-alpha.2`__
esbuild: __`0.13.12`__
nodejs: __`v16.13.0`__
browsers: __Chrome, Safari, Firefox__
macOS: __`11.6.1`__

This is Elixir/PhoenixLiveView code, here I made `button` component that takes two attributes and then I use them to render different buttons with different `color` and `type`

```elixir
def button(assigns) do
    assigns =
      assigns
      |> assign_new(:type, fn -> [] end)
      |> assign_new(:color, fn -> [] end)

    ~H"""
    <button type={@type} class={"px-3 py-2 font-semibold bg-#{@color}-300 border border-#{@color}-400 rounded text-slate-900 hover:bg-#{@color}-400 hover:border-#{@color}-500"}>
      <%= render_slot(@inner_block) %>
    </button>
    """
  end
```

I use this component in html file like so
```elixir
<.button type="submit" color="teal">
      Log in
 </.button>
```
I expect the button color to be as I specified in the `color` attribute for the `.button` component, and actually when I inspect in the browser I see the button got the color, but compiler doesn't render it as you can see in html code, the `teal` color I specified in `.button` component is evaluated correctly in the html output, but it is not rendered correctly, just blank button and sometimes it picks only border color.
```html
<button type="submit" class="px-3 py-2 font-semibold bg-teal-300 border border-teal-400 rounded text-slate-900 hover:bg-teal-400 hover:border-teal-500">Log in</button>
```

**Comment by adamwathan** [comment]
Hey! Yep this is expected behavior and is covered in the documentation:

https://tailwindcss.com/docs/optimizing-for-production#writing-purgeable-html

Should find everything you need to understand what's happening and what the solution is there 👍  Hope that helps!

**Comment by alaadahmed** [comment]
Ya I read that part of documentation before, and actually Purge didn't remove the class and this is the issue that I speak about, I see the classes in the output html file, but they don't work or have no effect.
