### ISSUE TITLE
JIT mode doesn't work with Gatsby

### ISSUE THREAD

**Issue by ShaunDychko** [tailwindlabs/tailwindcss#6068]
**What version of Tailwind CSS are you using?**

2.2.19 or 3.0.0-alpha.2

**What build tool (or framework if it abstracts the build tool) are you using?**

gatsby 4.1.3

**What version of Node.js are you using?**

v14.17.6

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/ShaunDychko/tailwindcssjit

**Describe your issue**

CSS doesn't get generated when the `jit` mode is enabled. With tailwindcss 2.2.19, setting `mode: 'jit'` in `tailwind-config.js`, as it is in the repo, prevents generation of CSS during development. To reproduce the issue, clone the repo linked above, run `gatsby develop` and try adding a tailwindcss class to, say, `./src/pages/index.js`, such as `<p className="bg-red-500">Welcome to your new Gatsby site.</p>`. The background will not be red. However, if you edit `tailwind-config.js` and remove the line `mode: 'jit'`, then run `gatsby develop`, the background of that paragraph will be red and everything works as expected including hot reloading.

Using tailwind 3.0.0-alpha.2 results in the same issue, even without `mode: 'jit'` since `jit` is the only option in tailwindcss 3.

**Comment by ShaunDychko** [comment]
https://github.com/tailwindlabs/tailwindcss/issues/5986 might be related.

**Comment by DennisKraaijeveld** [comment]
Not really related. You havent set your `purge` correctly. You have writting: 

`[".src/**/*.{js,jsx,tx,tsx}", "./public/**/*.html"],`

But you need to write:

`["./src/**/*.{js,jsx,tx,tsx}", "./public/**/*.html"],`


JIT is working fine on Gatsby, but with theme development, JIT does need a different setup. Bit within your repo, everything should be fine. Just make sure you set purge correctly.
@ShaunDychko

**Comment by ShaunDychko** [comment]
Oh, thank you so much @DennisKraaijeveld, that fixed it. I wish I had copy/pasted from https://tailwindcss.com/docs/guides/gatsby instead of typed it by hand!
