### ISSUE TITLE
How to override built-in darkVariants?

### ISSUE THREAD

**Issue by lianghx-319** [tailwindlabs/tailwindcss#6123]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/6099

<div type='discussions-op-text'>

<sup>Originally posted by **lianghx-319** November 16, 2021</sup>
I want to integrate third-party UI library and tailwindcss. And make a same dark mode selector. Either `class` `.dark` or `media`</div>

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

We'll keep this in the discussions section 👍
