### ISSUE TITLE
TW 3 - DEFAULT on text and background colors 

### ISSUE THREAD

**Issue by mgibas** [tailwindlabs/tailwindcss#6138]
**What version of Tailwind CSS are you using?**

v3.0.0-alpha.2

**What build tool (or framework if it abstracts the build tool) are you using?**

Tailwind play

**What version of Node.js are you using?**

Tailwind play

**What browser are you using?**

Chrome, Safari

**What operating system are you using?**

macOS

**Reproduction URL**
https://play.tailwindcss.com/s4D4akwztn

**Describe your issue**

Setting `DEFAULT` on text/background colors seems to override each other WHEN same color is defined under `colors`. Not sure that description is clear but in the repro you can clearly see that background should have a `light` variant of `disabled` colors, but its `dark` instead.

**Comment by adamwathan** [comment]
Ah yeah definitely looks like a bug! Here's another demo that made it more obvious to me:

https://play.tailwindcss.com/xynKxQLXDp?file=config

Seems like we're mutating a reference somewhere that should be on a copy.

**Comment by florianbouvot** [comment]
I discover the DEFAULT setting, is there more info in the documentation about that?

**Comment by mgibas** [comment]
@florianbouvot take a look at this: https://tailwindcss.com/docs/customizing-colors#color-object-syntax

**Comment by AdrienLemaire** [comment]
Looks like DEFAULT got removed from the doc, strange that it wasn't mentioned in release notes and the upgrade guide.

**Comment by thecrypticace** [comment]
Just took a look and this is no longer a problem as of Tailwind v3.0.7. It was resolved here: https://github.com/tailwindlabs/tailwindcss/pull/6546

Thanks for the report!
