### ISSUE TITLE
Background Opacity not apply when using gradient 

### ISSUE THREAD

**Issue by HeroinGyrl** [tailwindlabs/tailwindcss#6152]
hello. when i use `bg-gradient` i cant use `bg-opacity` 

```html
        <div class="rounded-xl  bg-gradient-to-r from-red-400 to-orange-200 bg-opacity-50 p-10">
          test 
      </div
```
is that not a issue from tailwind?
regarding.

**Comment by adamwathan** [comment]
Hey! bg-opacity sets the opacity of background colors, but gradients are background *images*. If you are using JIT mode, use the opacity shorthand instead:

```
<div class="rounded-xl  bg-gradient-to-r from-red-400/50 to-orange-200/50 p-10">
    test 
</div>
```

**Comment by iosiflivadaru** [comment]
@adamwathan what if I'm not using the JIT mode? Is there any other way to lower the opacity or will I have to make a specific gradientColorStops that already has the opacity down?
