### ISSUE TITLE
`npx tailwindcss` doesn't work in Docker (ubuntu)

### ISSUE THREAD

**Issue by simonacca** [tailwindlabs/tailwindcss#6153]
**What version of Tailwind CSS are you using?**

N/A

**What build tool (or framework if it abstracts the build tool) are you using?**

N/A

**What version of Node.js are you using?**

N/A

**What browser are you using?**

N/A

**What operating system are you using?**

Linux

**Reproduction URL**

https://github.com/simonacca/tailwind-repro

**Describe your issue**

When running `npx tailwindcss init` inside an ubuntu docker image, I get "Invalid or unexpected token". I would expect the tool to run normally instead. See below:

```bash
$ docker build -t mybuild .       
Sending build context to Docker daemon  2.048kB
Step 1/5 : FROM ubuntu
 ---> ba6acccedd29
Step 2/5 : ARG DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> d9b519298586
Step 3/5 : RUN apt-get update && apt-get install -y npm
 ---> Using cache
 ---> 4cf1ee63bea7
Step 4/5 : WORKDIR /app
 ---> Using cache
 ---> eec1b83a93df
Step 5/5 : RUN npx tailwindcss init
 ---> Running in aed188ea75a1
npx: installed 130 in 7.225s
Invalid or unexpected token
The command '/bin/sh -c npx tailwindcss init' returned a non-zero code: 1
```

**Comment by simonacca** [comment]
Works fine from the [`node:latest`](https://github.com/simonacca/tailwind-repro/tree/node-latest) image

**Comment by adamwathan** [comment]
Sounds like you were using an old version of Node (Tailwind is 12+ only), glad that resolved it.
