### ISSUE TITLE
`optimizeUniversalDefaults` make borders black in TailwindPlay too but only at development time!

### ISSUE THREAD

**Issue by frederikhors** [tailwindlabs/tailwindcss#6156]
**What version of Tailwind CSS are you using?**

2.2.19

**What build tool (or framework if it abstracts the build tool) are you using?**

SvelteKit (Vite) with "postcss": "8.3.11"

**What version of Node.js are you using?**

node 16.13.0

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction URL**

https://play.tailwindcss.com/NSyUv6w2Ad?file=config

**Describe your issue**

If you open the reproduction URL you'll see the border color "GRAY", not black like in the screenshot below.

![image](https://user-images.githubusercontent.com/41120635/142762563-ab8f9192-b248-48d4-b246-6b2116d9c8e3.png)

If you start a new TailwindPlayground project and write that config before and then write the html the border is "**BLACK**"!

This is what is happening in my develop environment.

I was using Tailwind without `optimizeUniversalDefaults` until today.

But I had a problem because after build the class `after:-translate-x-1/2` was not working (in dev yes). [The code is here](https://github.com/tailwindlabs/tailwindcss/discussions/6148#discussioncomment-1675313).

After `optimizeUniversalDefaults` the code works but in development I have those black borders all around!

Can you please help understand me what is wrong?

Thanks!

**Comment by adamwathan** [comment]
Can you help me understand exactly how to reproduce this? I tried following your steps but it's still gray.

https://user-images.githubusercontent.com/4323180/142764357-ccfb5c56-cd97-4975-9473-1f9898cc968d.mov

**Comment by adamwathan** [comment]
Might also be worth just trying out v3, we've improved the optimizeUniversalDefaults stuff there (it's actually not an option anymore and enabled by default). There are definitely some bugs in the v2 implementation, hence it being marked as experimental.

**Comment by frederikhors** [comment]
![issue](https://user-images.githubusercontent.com/41120635/142764625-8227ecdd-6d2b-4627-b6da-2dcc08f33d7e.gif)

**Comment by frederikhors** [comment]
> Might also be worth just trying out v3

I'm scared about trying v3.

By the way I can ask you how to avoid using `optimizeUniversalDefaults` entirely by solving the problem I have with `after:-translate-x-1/2`?

**Comment by adamwathan** [comment]
> I'm scared about trying v3.

I can't really help with this I guess. It's the actively developed version, will be released in like 2 weeks, and v2 is already no longer being actively developed. All bugfixes go to v3, not v2 at this point.

> By the way can I ask you how to avoid using optimizeUniversalDefaults entirely by solving the problem I have with after:-translate-x-1/2?

I'm not sure what the problem is, can you actually describe it? You just said "not working" but it appears to work in Tailwind Play. If it only happens in production please create a GitHub repo that reproduces the issue and link that here.

**Comment by frederikhors** [comment]
> I'm not sure what the problem is

The problem is `--tw-transform` is undefined in production.

**Comment by adamwathan** [comment]
I reproduced the issue in Tailwind Play but only when using cmd+V to paste stuff in. After making any change to the config (like deleting a comma and retyping it) everything works as expected, so I'm suspecting it's more to do with how the change events are firing in Tailwind Play.

Can you please create an actual GitHub project that reproduces your issues so I can actually see the development environment and inspect your build process? I can't help without that man.

**Comment by frederikhors** [comment]
I'm trying v3. In case I still have problems I will create a reproducible repo. Thanks.

**Comment by adamwathan** [comment]
Here's a demo showing that the borders are fixed (for good) as soon as you do something that triggers a fresh build (like changing the config or changing your CSS file):

https://user-images.githubusercontent.com/4323180/142765605-75dc5a52-2dca-41f7-8d88-2dfa01b1cc85.mov

Not sure how this would happen in a development environment but if you can actually provide the development environment I am happy to look into it. As it stands I have no idea if you are using Tailwind CLI, postcss-cli, webpack, Rollup, Vite, or what you are using for the actual web server so it's very hard to provide any help.

**Comment by frederikhors** [comment]
I can confirm v3 works wonderfully.

Now I have a problem with this code I was using.

```js
import { PurgeCSS, defaultOptions } from "purgecss";
import { tailwindExtractor } from "tailwindcss/lib/lib/purgeUnusedStyles";

const purgeCSSOptions = {
	content: ["./build/app/**/*.js", "...others..."],
	css: ["./build/app/**/*.css"],
	defaultExtractor: (content) => [
		...defaultOptions.defaultExtractor(content),
		...tailwindExtractor(content),
	]
};

// PurgeCSS()...
```

I cannot find `tailwindExtractor` anymore now with v3.

How to fix this, @adamwathan?

**Comment by adamwathan** [comment]
I'm not sure what you are trying to do there but you are importing internal code that isn't public API. Please start a help discussion for help with using custom extractors if you need help, and make sure to explain what you are actually trying to do. There should be no reason to need to customize how that works at all.

**Comment by frederikhors** [comment]
@adamwathan I opened this: https://github.com/tailwindlabs/tailwindcss/discussions/6162.
