### ISSUE TITLE
space-x not working with flex-row-reverse

### ISSUE THREAD

**Issue by chemiadel** [tailwindlabs/tailwindcss#6166]
**What version of Tailwind CSS are you using?**

For example: v2.2.19

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: postcss-cli 8.3.11, Next.js 12.0.4

**What version of Node.js are you using?**

For example: v14.18.1

**What browser are you using?**

For example: Chrome, Safari, or N/A

**What operating system are you using?**

For example: macOS, Windows

**Describe your issue**

`space-x-8` not working with `flex-row-reverse` but it does working with `flex-row`

**Sample**

```
        <div className="flex flex-row-reverse py-4 px-8 space-x-8">
            <button className="border bg-green-600 hover:bg-green-700 text-white font-semibold rounded-lg px-4 py-2"> Publish </button>
            <button className="border bg-gray-600 hover:bg-gray-700 text-white font-semibold rounded-lg px-4 py-2"> Preview </button>
        </div>
```

**Comment by adamwathan** [comment]
See docs here: https://tailwindcss.com/docs/space#reversing-children-order
