### ISSUE TITLE
The style for [type='button'] is not reset

### ISSUE THREAD

**Issue by rehos** [tailwindlabs/tailwindcss#6180]
The style for [type='button'] is not reset

**What version of Tailwind CSS are you using?**

v2.2.15

**What build tool (or framework if it abstracts the build tool) are you using?**

N/A

**What version of Node.js are you using?**

N/A

**What browser are you using?**

Safari

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/oNdodS9QBi

**Describe your issue**

The following div is rendered with the default browser style in Safari.

```
        <div type="button">
          <img src="/img/logo.svg" class="h-7 sm:h-8" />
        </div>
```

**Comment by rehos** [comment]
![Screenshot 2021-11-23 at 09 30 35](https://user-images.githubusercontent.com/454303/142993909-57ae00f0-75a3-40a8-b71a-2c45a23b35f4.png)

**Comment by adamwathan** [comment]
Hey! Yep our preflight styles include that style which will target anything with `[type='button']`. No plans to change this as it would be a breaking change. You can use the `appearance-none` class to override this when needed.

**Comment by rehos** [comment]
Sorry, I missed that it was in the preflight styles, totally agree. Thanks for building tailwindcss.
