### ISSUE TITLE
Vite + Tailwind automatic full page reload

### ISSUE THREAD

**Issue by TomDeSmet** [tailwindlabs/tailwindcss#6181]
I'm not sure if this is a Vite or Tailwind issue, so I'm linking this here too. The complete explanation and issue is described here: https://github.com/vitejs/vite/issues/5808

**Comment by adamwathan** [comment]
Hey! Going to close this in favor of the Vite issue, Tailwind has no control over reloading the browser window so there is nothing we could change in the framework that would affect this behavior.
