### ISSUE TITLE
`<menu>` element is not reset

### ISSUE THREAD

**Issue by dorianmariefr** [tailwindlabs/tailwindcss#6191]
**What version of Tailwind CSS are you using?**

2.2.15

**What build tool (or framework if it abstracts the build tool) are you using?**

tailwindcss cli

**What version of Node.js are you using?**

v17.0.1

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/Sf1b5Bt88T

**Describe your issue**

There is spacing around the `<menu>` element

**Comment by dorianmariefr** [comment]
<img width="227" alt="Screenshot 2021-11-23 at 22 25 05" src="https://user-images.githubusercontent.com/58794487/143131728-616fad97-f35c-42bf-9cf1-1e9d3557c2a7.png">
<img width="205" alt="Screenshot 2021-11-23 at 22 25 17" src="https://user-images.githubusercontent.com/58794487/143131735-8aafa02b-0434-4fa3-b1bd-95f420058d6c.png">
<img width="688" alt="Screenshot 2021-11-23 at 22 25 23" src="https://user-images.githubusercontent.com/58794487/143131737-a7bd3c82-f956-408b-a04d-4b1a847100f3.png">

**Comment by dorianmariefr** [comment]
```
menu {
  @apply m-0 p-0;
} 
```

fixes it

**Comment by adamwathan** [comment]
This is fixed in v3, thanks!
