### ISSUE TITLE
Animation rendering error on the tailwind homepage

### ISSUE THREAD

**Issue by seabasss** [tailwindlabs/tailwindcss#6205]
I opened up my brand new super shiny maxed out MacBook and browsed to the Tailwind site in Safari and the animations leave ghost marks. No biggie and probably a Safari render issue rather than tailwind or css, but thought I'd put it out there if anyone knows what it is.

Edit // I guess it was possibly an old version of tailwind:
https://v1.tailwindcss.com

See the avatar and the floating m:

<img width="715" alt="Screen Shot 2021-11-26 at 10 06 06 AM" src="https://user-images.githubusercontent.com/5251896/143618491-c531cf25-94b5-4c01-adfc-1676dd217d9e.png">
<img width="701" alt="Screen Shot 2021-11-26 at 10 06 33 AM" src="https://user-images.githubusercontent.com/5251896/143618495-258c1c45-3815-45d7-ac5e-1ce9382bcda0.png">

**Comment by adamwathan** [comment]
Ah weird! Yeah unfortunately not likely to do anything about this at this point, we're about to ship v3 in a couple of weeks with a new website yet again so going back and making changes to the v1 docs likely isn't going to happen. Thanks for pointing it out though.

**Comment by seabasss** [comment]
Totally understand. I also didn't realize I ended up in the v1 doc. No worries.

Excited about v3! Happy TG Adam.
