### ISSUE TITLE
Tailwind classes don't work

### ISSUE THREAD

**Issue by tuncayofficial** [tailwindlabs/tailwindcss#6210]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/6208

<div type='discussions-op-text'>

<sup>Originally posted by **tuncayofficial** November 27, 2021</sup>
I have problem with Tailwind Create React App project. I did everything on [Tailwind React App setup](https://tailwindcss.com/docs/guides/create-react-app). But when I add some classes like `delay-200`, `bg-blue` and etc., project doesn't apply it. I have no idea why it happens to me.

![image](https://user-images.githubusercontent.com/68643463/143685477-22f0501c-1417-4a37-9c82-b734e51c4c96.png)
 
Any help appreciated, thanks!</div>

**Comment by jeffehogg** [comment]
Can you post your file structure and global css file?

**Comment by aliveli186** [comment]
Same here, on react changes are not picked up.
