### ISSUE TITLE
Transition-opacity does not apply a transition when used with background-opacity

### ISSUE THREAD

**Issue by CarbonGhost** [tailwindlabs/tailwindcss#6211]
**What version of Tailwind CSS are you using?**

- Tailwind v2.2.16

**What build tool (or framework if it abstracts the build tool) are you using?**

- PostCSS v8.3.9
- NextJS v11.1.2

**What version of Node.js are you using?**

- Node v16.5.0

**What browser are you using?**

- Firefox v94.0.1

**What operating system are you using?**

- Windows 10

**Reproduction URL**

https://play.tailwindcss.com/TZpIVMrmFQ

**Describe your issue**

When using a `transition-opacity` class with a `bg-opacity-[n]` class, no transition is applied. As opposed to the expected behavior, where the opacity transition would apply only to the background opacity, no transition is applied whatsoever.  

In the reproduction code, you can see that the green element has a transition from 50 to 100 opacity, including both the text and background. The red element has that same transition code, where only the background has a modified opacity value, and no transition is applied.

**Comment by adamwathan** [comment]
Hey! In your case you want just `transition` or `transition-colors` — `transition-opacity` only transitions the literal `opacity` CSS property and the way background opacity works in Tailwind is by changing the background _color_, by changing the alpha value (the `a` in `rgba`).

Here's a demo:

https://play.tailwindcss.com/PzCuJ2YDrs

Hope that helps!
