### ISSUE TITLE
Using `0` as arbitrary value doesn't work for for some properties

### ISSUE THREAD

**Issue by arzatskis** [tailwindlabs/tailwindcss#6227]
**What version of Tailwind CSS are you using?**

v2.2.19

**Reproduction URL**

https://play.tailwindcss.com/eOQOc2klvH

**Describe your issue**

Trying to apply custom value as `0` for border width Tailwind JIT doesn't generate the selector. E.g. using `border-[0]` does nothing, even though `border-width: 0` is valid CSS expression. Same for font size with `text-[0]` (`font-size: 0` is valid CSS). Haven't checked other properties.

This doesn't happen and when applying `w-[0]` - selector / style is applied as expected.

<img width="1392" alt="Screen Shot 2021-12-01 at 11 44 19" src="https://user-images.githubusercontent.com/687133/144212018-40501079-583c-419d-9b66-f9cfa4345f3a.png">

**Comment by AviAvinav** [comment]
I checked this out, it seems it is working when you use text-[0px] or border-[0px], it seems to need a unit. Hope it helps for now.

**Comment by arzatskis** [comment]
Yeah, I figured out, that it works with units set / as workaround. Probably this still should work / be consistent with other properties (e.g. `w-[0]` / `h-[0]`) and work with just `0`?

**Comment by AviAvinav** [comment]
Yeah, it seems that setting the unit works with all utilities but just "0" works with only some.

**Comment by adamwathan** [comment]
Think we can probably support this, should just be a matter of adding a check for `0` here:

https://github.com/tailwindlabs/tailwindcss/blob/master/src/util/dataTypes.js#L80-L85

Happy to take a look at a PR if someone wants to give it a shot and add some tests 👍🏻

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed, and will be available in Tailwind v3.
