### ISSUE TITLE
Dependency Issue - Acorn

### ISSUE THREAD

**Issue by slakbal** [tailwindlabs/tailwindcss#6236]
**What version of Tailwind CSS are you using?**

Latest

**What build tool (or framework if it abstracts the build tool) are you using?**

Laravel Mix - latest

**What version of Node.js are you using?**

Latest, but issue also on earlier version.

**What browser are you using?**

Chrome

**What operating system are you using?**

Ubuntu

**Reproduction URL**

https://laracasts.com/discuss/channels/javascript/tailwindlaravel-mix-dependency-tree-error

**Describe your issue**

Normal working flow on my project is to at least once a week run "npm update" to get the latest dependency updates. Since the last update the build started to fail. After some research I found that the issue is creeping up for other people. The way to solve the issue was to install v8 of the Acorn dependency.

![Screenshot from 2021-12-02 10-26-45](https://user-images.githubusercontent.com/4387265/144385579-397a8b83-cb2d-431c-99ce-1a46f37eae40.png)

**Comment by MartinHughes-BPC** [comment]
I updated to the latest version of npm which fixed this for me.

**Comment by reinink** [comment]
Hey, without a reproduction repo these kinds of issues are really hard to figure out.

That said, sounds like you have a couple options here:

1. Update to the latest version of npm (as suggested by @MartinHughes-BPC)
2. Manually install acorn: `npm i acorn --dev` (as suggested on Laracasts)

Another thing to try is to just delete your `yarn.lock`/`package-lock.json` file and `node_modules` folder, and do a fresh install. That's helped me numerous times in the past.

Hope that works! If not, please provide a minimum reproduction repo and I'll have another look 👍
