### ISSUE TITLE
@layer components does not work with Svelte

### ISSUE THREAD

**Issue by shahul01** [tailwindlabs/tailwindcss#6270]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/6263

<div type='discussions-op-text'>

<sup>Originally posted by **shahul01** December  4, 2021</sup>
Everything works in Tailwind except @layer...
Here are the codes : 

HTML / Svelte:

```
.component {
    @apply egfcc;
}
```

CSS:

```
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer components {
  .egfcc {
    @apply flex justify-center items-center;
  }

}
```

Simple code but does not work, tried restarting and hard refreshing, nothing works.
 
Throws error: `The egfcc class does not exist. If egfcc is a custom class, make sure it is defined within a @layer directive.`

I also added `postcss-import` plugin in postcss.config.js file as suggested by @adamwathan in another post just in case.

also added the class to purge safelist but nothing seems to work and there is no answers anywhere...

</div>

<br />

### (added it here, so they might fix this in future versions)

Solution:

> The problem is Svelte processes all of your CSS files in complete isolation, so the file where you are trying to apply that class is using a different instance of Tailwind than the file where that class is defined.
> 
> The easiest solution is to define any classes you want to apply across files using Tailwind’s plugin system instead of using CSS. Unfortunately nothing we can do about it because of how these build tools have decided to handle per component CSS. Same problem exists in Vue projects for example.

Implementation:
```
// tailwind.config.js

   
  plugins: [
    plugin(
      function({ addUtilities, addComponents, e, prefix, config }) {

        const myComponents = {

          '.shfcs': {
            'display': 'flex',
            'justify-content': 'center',
            'align-items': 'start',
          },



        }


        addComponents(myComponents)
      }
    ),

  ],
```

**Comment by adamwathan** [comment]
Closing since the answer was provided in the original discussion, nothing we can do on our end about this.
