### ISSUE TITLE
Classes not applied in safari (v3)

### ISSUE THREAD

**Issue by luknl** [tailwindlabs/tailwindcss#6282]
**What version of Tailwind CSS are you using?**

v3.0.0-alpha.2

**What build tool (or framework if it abstracts the build tool) are you using?**

NA

**What version of Node.js are you using?**

NA

**What browser are you using?**

- Chrome Version 96.0.4664.55
- Safari Version 12.0.1

**What operating system are you using?**

macOS

**Reproduction URL**

https://codepen.io/luknl/pen/LYzGJxZ

**Describe your issue**

Classes are not applied on safari. If you check the reproduction link in chrome, the background color is red, but in safari, nothing happens.
Also, https://play.tailwindcss.com/ gives this error on safari: "An unexpected error has occurred." (`ReferenceError: Can't find variable: ResizeObserver`)

**Comment by jacobthesheep** [comment]
This shouldn't be happening. And probably a bug that can't be fixed internally because this bug does not occur on Safari Version 15.1

**Comment by adamwathan** [comment]
Hey! Tailwind Play only supports Safari >= 13.1 and Tailwind v3 in general targets Safari 14+.
