### ISSUE TITLE
Animation keyframes should be preserved in JIT mode

### ISSUE THREAD

**Issue by maxweldsouza** [tailwindlabs/tailwindcss#6302]
**What version of Tailwind CSS are you using?**
v2.2.19

**What build tool (or framework if it abstracts the build tool) are you using?**
Next.js

**What version of Node.js are you using?**
v14

**What browser are you using?**
Firefox

**What operating system are you using?**
Ubuntu

**Reproduction URL**
https://play.tailwindcss.com/gMEjZPSxjt

**Describe your issue**

Tailwind removes keyframes when JIT mode is enabled. As per the documentation it should not remove keyframes unless specified. https://tailwindcss.com/docs/optimizing-for-production#removing-unused-keyframes.
The animation in the reproduction url should play correctly. It works only when jit mode is disabled https://play.tailwindcss.com/zBhgNHTr0C.

**Comment by reinink** [comment]
Hey! So the new JIT engine works a little different than the previous engine in Tailwind CSS. Previously, Tailwind generated all the possible CSS, and then we used PurgeCSS to remove unused CSS.

In JIT mode, which is now the default in Tailwind CSS v3.0, Tailwind scans all your template files for class name matches, and then only generates the necessary CSS (utility classes) for your project.

If you want to take advantage of Tailwind's "pulse" keyframes, you'll need to use the `animate-pulse` utility in your project, like this:

```html
<div class="bg-black w-10 h-10 animate-pulse"></div>
```

You can see this working on Tailwind Play, which is running on v3.0.1:

https://play.tailwindcss.com/4tv0XskBeY

It's worth noting that if you add your own custom keyframes, Tailwind will not remove those — it will only exclude keyframes from Tailwind itself which are not used. For example:

https://play.tailwindcss.com/DknN9HQYeO

(notice how I've manually added the pulse keyframes in the "CSS" tab)

I hope that helps! 💪
