### ISSUE TITLE
Native aspect ratio not working on Iframe 

### ISSUE THREAD

**Issue by krishnaTORQUE** [tailwindlabs/tailwindcss#6303]
**What version of Tailwind CSS are you using?**

For example: v3.0.0

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: postcss-cli 9.0.2

**What version of Node.js are you using?**

For example: v16.13.1

**What browser are you using?**

For example: Chrome, Firefox

**What operating system are you using?**

For example: Debian

**Describe your issue**

I am unable to get native aspect ratio work.

`<iframe class="aspect-video" src="URL"></iframe>`
OR 
`<div class="aspect-video"><iframe src="URL"></iframe></div>`

Both are not working

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

This should definitely work, here is an example: https://play.tailwindcss.com/bwS0rhd38Q
