### ISSUE TITLE
v3 release note contains broken link

### ISSUE THREAD

**Issue by ACPK** [tailwindlabs/tailwindcss#6304]
Congrats on the launch of v3!

I viewed https://github.com/tailwindlabs/tailwindcss/releases, and clicked on the link for "Read the announcement post".

This link goes to a blog post that is not live yet :)

https://blog.tailwindcss.com/tailwindcss-v3

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed now!
