### ISSUE TITLE
Not building for me after following 3.0 upgrade guide

### ISSUE THREAD

**Issue by slikk66** [tailwindlabs/tailwindcss#6308]
Followed instructions and removed all my old tailwind/postcss/autoprefixer packages and installed

````
yarn add -D tailwindcss@latest \
@tailwindcss/typography@latest \
@tailwindcss/forms@latest \
postcss@latest \
autoprefixer@latest
````

Now when I build I get:

````
yarn build
yarn run v1.22.17
$ craco build
Creating an optimized production build...
Failed to compile.

./src/index.css
Error: PostCSS plugin tailwindcss requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
````

My package json has:
````
        "autoprefixer": "^10.4.0",
        "postcss": "^8.4.4",
        "tailwindcss": "^3.0.0",
````

And index.css is:
````
@tailwind base;
@tailwind components;
@tailwind utilities;
````

I followed through the upgrade guide also but not sure what else I need to change.  I even deleted `node_modules` and tried reinstalling everything from scratch.

Thanks!

**Comment by slikk66** [comment]
Looks like this is my reason, I'm using a older version of Create React App that doesn't support postCSS8 but there seems to be a beta/upcoming version that does - instructions to upgrade here: https://github.com/facebook/create-react-app/discussions/11278

**Comment by iwasherefirst2** [comment]
Hey I am facing the same issue, but I have a vue-2 dependency. If your package has post-css 8.4.4, why would tailwind fail if it does not work with react? Shouldn't there be an error message from react during your build (or during installation, a  dependecy conflict)?
