### ISSUE TITLE
Accent colors not working on iOS

### ISSUE THREAD

**Issue by Xenfo** [tailwindlabs/tailwindcss#6316]
**Describe your issue**

Accent colors in checkboxes aren’t working on iOS 15.1.1 Safari.

![0BE1B99D-5C98-49BE-80B5-E217EB09D112](https://user-images.githubusercontent.com/46873232/145495562-1925a165-46a0-47c4-a348-202160fbdfdb.png)
![E1594872-644C-4853-A89D-D201E454B9F0](https://user-images.githubusercontent.com/46873232/145495567-a63f5162-a6e2-4d27-b8ec-048dbe2589a2.png)

**Comment by adamwathan** [comment]
Hey! This is expected, Safari doesn’t support this CSS feature yet. Hopefully in the future but in the mean time you can think of it as progressive enhancement 👍🏻
