### ISSUE TITLE
Tailwind version 3 not working with TypeScript

### ISSUE THREAD

**Issue by cagrisayir** [tailwindlabs/tailwindcss#6318]
I am using macOS, Chrome, NodeV17.0.1, tailwindcss V3.0.0

I am using TypeScript in my current project. I installed tailwind v3.0.0 following the documentation. I only changed 'npx create-react-app@next --scripts-version=@next --template=typescript@next my-ts-app
' part for TypeScript. After that, I tried to add '.ts,.tsx' part in the content part. However, when I tried to change something via className it doesn't affect the style.

**Comment by JoseGarciaM** [comment]
Me neither, some plugins that requiere lodash stopped working =/

**Comment by lifedup** [comment]
If you're using SCSS this might help...

I'm using SCSS, Next, typescript, and all the official tailwind plugins.  I successfully upgraded from v2 to v3 with only two changes.  


1.  Rename `purge` to `content` in `tailwind.config.js`

2. In my `global. scss` this is imported in my `_app.TSX` I had to update `@imports` with `@tailwind`.

```
// @import 'tailwindcss/base';
// @import 'tailwindcss/components';
// @import 'tailwindcss/utilities';
@tailwind base;
@tailwind components;
@tailwind utilities;
```

**Comment by cagrisayir** [comment]
I changed content as content: [ './src/**/*.{html,js}', './src/**/*.{html,ts}', './src/**/*.{html,tsx}', ], and its worked!
