### ISSUE TITLE
URGENT: Unpkg link not working, maybe has to do with your publish on npm an hour ago

### ISSUE THREAD

**Issue by adam993** [tailwindlabs/tailwindcss#6355]
What version of Tailwind CSS are you using?

v3.0.0

What build tool (or framework if it abstracts the build tool) are you using?

N/A

What version of Node.js are you using?

N/A

What browser are you using?

N/A

What operating system are you using?

N/A

Reproduction URL

https://unpkg.com/tailwindcss@3.0.0/dist/tailwind.min.css

Describe your issue

File not found @ https://unpkg.com/tailwindcss@3.0.0/dist/tailwind.min.css , maybe has to do with your publish on npm an hour ago because they pull data from npmjs.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The new v3 version doesn't have a CDN link like it used to do on version 2. We have a new CDN for this: https://tailwindcss.com/docs/installation/play-cdn

The CDN was never recommended to use in production: https://v2.tailwindcss.com/docs/installation#using-tailwind-via-cdn
This new CDN is also not recommended to use in production.

We highly recommend to use the Tailwind CLI instead: https://tailwindcss.com/docs/installation

**Comment by samant-rags** [comment]
hi Robin

some frameworks and their plugins dont allow  usage of script tags .. only link tags with CSS are allowed.
Can tailwind support css from 3x onwards for such cases ?

regards
Samant
