### ISSUE TITLE
Vendor prefix can break the generated css

### ISSUE THREAD

**Issue by Prashank25** [tailwindlabs/tailwindcss#6360]
**What version of Tailwind CSS are you using?**

v3.0.0

**What build tool (or framework if it abstracts the build tool) are you using?**

webpack 5.60.0 and play.tailwind.com

**What version of Node.js are you using?**

v16.13.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

Try this in any browser except firefox:
https://play.tailwindcss.com/YkD75GMXHs?file=css

**Describe your issue**

If I @apply border class inside my custom CSS, and it just happens to be a vendor-prefixed, and the current browser doesn't support it then that invalidates all the CSS after that vendor-prefix.

Any vendor-prefixed classes will need to be separated into their own blocks and not merged in the comma-separated list. This does happen in my webpack setup as well but I suspect that's not relevant.

**Comment by adamwathan** [comment]
Ah great catch, this is an important one and will prioritize, thank you 👍🏻
