### ISSUE TITLE
Accent colors not working when using @tailwindcss/forms plugin

### ISSUE THREAD

**Issue by robinsonjohn** [tailwindlabs/tailwindcss#6367]
**What version of Tailwind CSS are you using?**

`3.0.0`

**What build tool (or framework if it abstracts the build tool) are you using?**

`postcss 8.4.4`

**What version of Node.js are you using?**

`16.13.0`

**What browser are you using?**

Multiple (same results)

**What operating system are you using?**

macOS

**Describe your issue**

Utilizing the `accent-{color}` classes has no effect when using the `@tailwindcss/forms` plugin.

Using the documentation's [basic usage example](https://tailwindcss.com/docs/accent-color#basic-usage) has no effect on the accent color. When the `@tailwindcss/forms` plugin is removed, the accent color is styled as expected.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The accent-color sets the actual `accent-color` property. However, when you are using the `@tailwindcss/forms` plugin, then we remove the default appearance and replace it with a styleable checkbox with a custom svg.

If you want to use the same accent color, then you can use the text color classes instead: https://play.tailwindcss.com/oigBo8s03D
The code example contains this example: https://github.com/tailwindlabs/tailwindcss-forms#basic-usage

**Comment by robinsonjohn** [comment]
@RobinMalfait Awesome, I didn't realize that. Thank you!

**Comment by lucasvieluz** [comment]
I solve this problem using the class strategy:

```
plugins: [
 require("@tailwindcss/forms")({
   strategy: 'class',
 }),
],
```

**Comment by skanderKha** [comment]
Hi , the text-[color] did the job but actually , if i need to change the color of the "tick" symbol what should i use ...

**Comment by vekkon** [comment]
I also have this issue and cant find a solution to change the color of the tick
