### ISSUE TITLE
Tailwind v3 build with tailwind-cli throws `fill-current` is a custom class`

### ISSUE THREAD

**Issue by caneco** [tailwindlabs/tailwindcss#6371]
### Local information 

- **Build tool** : `tailwind-cli`
- **TailwindCSS --version**: `v3.0.0`
- **Node --version**: `v16.2.0`
- **Browser**: N/A
- **OS**: macOS

---

I have on my `app.css` the following code:

```CSS
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
    svg[role=img] { @apply flex-none fill-current; }
}
```

…and somehow if I've try to `watch` or `build` my tailwind file I get the following output:

```
Rebuilding...
CssSyntaxError: tailwindcss: ../resources/styles/app.css:5:21:
The `fill-current` class does not exist. If `fill-current` is a custom class,
make sure it is defined within a `@layer` directive.

> 5 |     svg[role=img] { @apply flex-none fill-current; }
    |                     ^
  6 |
```

I know how to solve it… but it's bit weird Tailwind is giving that error since `flex-none` has no issue and `fill-current` it exists on tailwind core.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The `current` part in `fill-current` is coming from your `colors` in the `tailwind.config.js`. If you overrode the `colors` section in your theme, then this won't be available anymore.

You can fix this by:
- Adding the `current: 'currentColor'` to your colors
- Or by extending your colors instead of overriding them

**Comment by caneco** [comment]
So the [`fill-current` utility class](https://tailwindcss.com/docs/fill) it's only best used in the HTML?

Thanks for the suggestion! Just added that to the `colors:` and worked like a charm.

**Comment by allmarkedup** [comment]
I also had this issue and this fix works for me. It is a breaking change from v2 however - maybe worth adding to the upgrade guide color palette docs?
