### ISSUE TITLE
Cannot compile with multiple @apply - Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by senordelaflor** [tailwindlabs/tailwindcss#6376]
**What version of Tailwind CSS are you using?**

3.0.0

**What build tool (or framework if it abstracts the build tool) are you using?**

Postcss 8.4.4, webpack 5.36.1, Sass

**What version of Node.js are you using?**

v12.22.1

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/i3Ja7ZD819?file=css

**Describe your issue**

Tailwind cannot compile and hangs when multiple @apply are used. This is happening in both SCSS and CSS. This is the error:

![CleanShot 2021-12-10 at 12 42 54@2x](https://user-images.githubusercontent.com/10679537/145618581-336eac32-41bd-42e2-85b2-cc2ac90dca6e.png)

I can see that this is also happening in play.tailwindcss.com

Thanks so much for looking into this. We've been loving Tailwindind and can't wait to use v3!

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

You have a circular dependency:

```css
.button.hidden {
  @apply hidden;
}
```

You are trying to apply hidden in a selector that uses hidden.
