### ISSUE TITLE
`content-none` does not correctly render `content: "";`

### ISSUE THREAD

**Issue by jacobthesheep** [tailwindlabs/tailwindcss#6387]
**What version of Tailwind CSS are you using?**

Tailwind CSS v3.0.1

**What build tool (or framework if it abstracts the build tool) are you using?**

Snowpack v3.8.8

**What version of Node.js are you using?**

Node.js v14.17.1

**What browser are you using?**

For example: Chrome, Safari, or N/A

Chrome: 96, Safari 15.1, Firefox 95

For example: macOS, Windows

**Reproduction URL**

https://github.com/jacobthesheep/jacoblamb.me

(couldn't recreate an example in https://play.tailwindcss.com even using `content: ""` and not `content-none`)

**Describe your issue**

Replaced `content: ""` with `content-none` from https://tailwindcss.com/docs/content but does not render expected `content: "";` because in the browser inspect element console, the code is `--tw-content: none;` not `content: "";`
<img width="483" alt="Screen Shot 2021-12-10 at 21 48 24" src="https://user-images.githubusercontent.com/44789941/145665744-75e9cb4a-1b42-4d86-bf74-881bd4923917.png">

**Comment by Trendymen** [comment]
This is still not correct.

**Comment by tremby** [comment]
I just stumbled on this. Definitely seems broken. The docs say it applies `content: ""` but it does not. Either a documentation bug or a code bug.
