### ISSUE TITLE
New content property in tailwind.config does not work if only one extension (.tsx) is provided

### ISSUE THREAD

**Issue by jvidalv** [tailwindlabs/tailwindcss#6394]
**What version of Tailwind CSS are you using?**
v3.0.1

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite 2.6.10
Postcss 8.3.11

**What version of Node.js are you using?**

v14.6.X

**What operating system are you using?**

MacOS

**Describe your issue**

So, I have a React + TypeScript project, this morning I moved into Tailwind v3 and changed purge to content. My surprise came when classes disappeared. Felt like Tailwind was not parsing the files in search for the classNames.

First, ALL my classes are inside `.tsx` files. 

This is my config file that does not work (And did work prior to v3):

![image](https://user-images.githubusercontent.com/27777508/145675278-a9b38855-9e1a-4cdb-9186-8f1fa7f4c75b.png)

This is the config file that DOES work:

![image](https://user-images.githubusercontent.com/27777508/145675259-62780290-acc7-4fa9-864d-9621e35938e0.png)

For `content` to work as before, It must have more than one extension, it does not matter which, but must be more than one, see this example, this also works:

![image](https://user-images.githubusercontent.com/27777508/145675345-f60a1193-057b-4753-bcaf-42302ff7a1c7.png)

Seems like a big bug to me.

**Comment by bolshoytoster** [comment]
Does it work when you remove the curly brackets?

i.e. `"./src/**/*.tsx"`
