### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '700')

### ISSUE THREAD

**Issue by samehsy** [tailwindlabs/tailwindcss#6398]
**What version of Tailwind CSS are you using?**
 "tailwindcss": "^3.0.1",
 
**What build tool (or framework if it abstracts the build tool) are you using?**
 "postcss": "^8.3.11", Angular 13 ,

**What version of Node.js are you using?**
node : v16.13.0

**What browser are you using?**
 Chrome,

**What operating system are you using?**
Ubuntu 20.04

 
**Describe your issue**
after I update Tailwindcss on my angular 13 project I  get the below error when I try to run the project  I try to look into these files  I found that the gray color has problems or is even not found also  I  have a  custom tailwind.config

`TypeError: Cannot read properties of undefined (reading '700') 
    at module.exports ( node_modules/@tailwindcss/typography/src/styles.js:16:65)
    at value ( node_modules/tailwindcss/lib/util/resolveConfig.js:68:41)
    at  node_modules/tailwindcss/lib/util/resolveConfig.js:132:24
    at Array.map (<anonymous>)
    at Object.typography ( node_modules/tailwindcss/lib/util/resolveConfig.js:132:15)
    at node_modules/tailwindcss/lib/util/resolveConfig.js:155:57
    at Array.reduce (<anonymous>)
    at resolveFunctionKeys (node_modules/tailwindcss/lib/util/resolveConfig.js:152:32)
    at Object.resolveConfig [as default] (node_modules/tailwindcss/lib/util/resolveConfig.js:224:16)
    at Object.resolveConfig [as default] (node_modules/tailwindcss/lib/public/resolve-config.js:15:39)
`

here is the code where styles.js  throw  error:

`module.exports = (theme) => ({
  DEFAULT: {
    css: [
      {
        color: theme('colors.gray.700', defaultTheme.colors.gray[700]),
      }]}`

**Comment by bolshoytoster** [comment]
Could you change the `colors.gray.700` to just `colors.gray`?

**Comment by bolshoytoster** [comment]
Could you change the `colors.gray.700` to just `colors.gray`?

**Comment by nbgoodall** [comment]
This seems to be an issue with the `defaultTheme` import, where [`colors` is a function](https://github.com/tailwindlabs/tailwindcss/blob/8a4b2f0627126d5ff160540f52d848ebec0c9cd7/stubs/defaultConfig.stub.js#L13):

```js
const { colors } = require('tailwindcss/defaultTheme')

colors() // <= expects a { colors: … } object.
```

Whereas it should now be `const colors = require('tailwindcss/colors')`.

This is causing issues with [`@tailwindcss/forms`](https://github.com/tailwindlabs/tailwindcss-forms) as well.

**Comment by samehsy** [comment]
@nbgoodall thank you I appreciate your  help  ...you are  right  I  forgot  to  update  @tailwindcss/typography 
@bolshoytoster  also  thanks

**Comment by vahnmarty** [comment]
I'm having this issue (in Laravel), what is the solution for this? 

```
ERROR in ./resources/css/app.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read properties of undefined (reading '700')
    at Object.module.exports [as typography] (C:\laragon\www\lasinja-payroll\node_modules\@tailwindcss\typography\src\styles.js:16:65)
    ```

**Comment by nbgoodall** [comment]
> I'm having this issue (in Laravel), what is the solution for this?
> 
> ```
> ERROR in ./resources/css/app.css
> Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
> ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
> TypeError: Cannot read properties of undefined (reading '700')
>     at Object.module.exports [as typography] (C:\laragon\www\lasinja-payroll\node_modules\@tailwindcss\typography\src\styles.js:16:65)
>     
> ```

https://github.com/tailwindlabs/tailwindcss/issues/6398#issuecomment-991688905

**Comment by vahnmarty** [comment]
@nbgoodall  Which version should I use? This is what my *package.json* looks like.

```
"devDependencies": {
        "@tailwindcss/forms": "^0.3.1",
        "@tailwindcss/typography": "^0.4.0",
        "alpinejs": "^3.0.6",
        "axios": "^0.21",
        "laravel-mix": "^6.0.6",
        "lodash": "^4.17.19",
        "mix-tailwindcss": "^1.3.0",
        "postcss": "^8.1.14",
        "postcss-import": "^14.0.1",
        "tailwindcss": "^3.0.2"
    },
    
 ```

**Comment by nbgoodall** [comment]
Try the latest: `npm I @tailwindcss/typography@latest` :)

**Comment by vahnmarty** [comment]
> npm i @tailwindcss/forms@latest

Thanks, It fixed the problem. :)

**Comment by mklueh** [comment]
Same problem, upgrading / adding tailwindcss forms not working

**Comment by nwilging** [comment]
default nuxt3 installation here with `tailwindcss ^3.0.7`:
```
"devDependencies": {
    "autoprefixer": "^10.4.0",
    "nuxt3": "latest",
    "postcss": "^8.4.5",
    "sass": "^1.45.0",
    "sass-loader": "^12.4.0",
    "tailwindcss": "^3.0.7"
  },
  "dependencies": {
    "@headlessui/vue": "^1.4.2",
    "@tailwindcss/aspect-ratio": "^0.4.0",
    "@tailwindcss/forms": "^0.4.0",
    "@tailwindcss/line-clamp": "^0.3.0",
    "@tailwindcss/typography": "^0.5.0",
    "@tailwindcss/ui": "^0.7.2"
  }
```

It appears `^0.5.0` and `^0.4.0` are latest for typography and forms respectively. Still receiving this error on build:
```
11:45:56 AM [vite] Internal server error: Cannot read property '700' of undefined                                                                                                                                                        11:45:56
  Plugin: vite:css
  File: ./assets/tailwind.scss
      at Object.<anonymous> (.\node_modules\@tailwindcss\ui\node_modules\@tailwindcss\typography\src\styles.js:15:40)
```

Tailwind config js:
```
const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
    purge: {
        content: [
            `components/**/*.{vue,js}`,
            `layouts/**/*.vue`,
            `pages/**/*.vue`,
            `plugins/**/*.{js,ts}`,
            `nuxt.config.{js,ts}`,
        ],
    },
    darkMode: 'class', // or 'media' or 'class'
    mode: 'jit',
    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
            },
            overflow: ['hover', 'focus'],
            typography: {
                '3xl': {
                    css: {
                        fontSize: '1.875rem',
                        h1: {
                            fontSize: '4rem',
                        },
                    },
                },
            },
        },
    },
    variants: {
        extend: {
            backgroundColor: ['active', 'focus', 'hover'],
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/ui'),
    ],
};
```

I've attempted to downgrade typography to 0.4.1 with no luck.

**Comment by spock123** [comment]
Google brought me here with the same issue - and same embarrassing omission on my part: had forgotten to update typography . thanks a bunch

**Comment by tarikhamilton** [comment]
I had this issue too after installing `@tailwind/typography`, but I had forgotten to update Tailwind to version 3 from 2 in an old project. Tailwind 3 came out in November 2021, so I'm sure I'm not the only one. 😅

**Comment by f-ricci** [comment]
I'm experiencing the same issue related to the '700' property.

`/node_modules/@tailwindcss/ui/node_modules/@tailwindcss/typography/src/styles.js:15:40`

This seems like to be an outdated dependency in the `@tailwind/ui` package. I have explored the package and noticed it uses `"@tailwindcss/typography": "^0.2.0"` and tailwind 3.0 only works with `"@tailwindcss/typography": "^0.5.0"`.

**Comment by cbloss** [comment]
So google lead me here also and I haven't quite figured out what I need to do to fix my issues. I was having the same 700 issue that everyone else had and once I updated both typography and forms, now I'm getting just a little different error: 

`Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read properties of undefined (reading 'type')`

I have updated forms and typography:

Forms: 0.4.0
Typography: 0.5.0
Tailwind 3

I'm also using Laravel.

Here's the package.json:
```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "mix",
        "watch": "mix watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "hot-tw": "cross-env THEME=tw mix watch --hot",
        "hot-rw": "cross-env THEME=rw mix watch --hot",
        "prod": "mix --production",
        "production": "mix --production"
    },
    "devDependencies": {
        "axios": "^0.21",
        "browser-sync": "^2.26.13",
        "browser-sync-webpack-plugin": "^2.2.2",
        "cross-env": "^7.0",
        "laravel-mix": "^6.0.0-beta.11",
        "lodash": "^4.17.20",
        "postcss": "^8.1.4",
        "resolve-url-loader": "^3.1.2",
        "sass": "^1.28.0",
        "sass-loader": "^10.0.5",
        "tailwindcss": "^3.0.11",
        "tailwindcss-plugins": "^0.3.0",
        "vue-loader": "^15.9.5",
        "vue-template-compiler": "^2.6.12"
    },
    "dependencies": {
        "@tailwindcss/forms": "^0.4.0",
        "@tailwindcss/typography": "^0.5.0",
        "@tailwindcss/ui": "^0.7.2",
        "svg4everybody": "^2.1.9",
        "vue": "^2.6.12",
        "vue-recaptcha-v3": "^1.9.0",
        "vuelidate": "^0.7.6"
    }
}

```

I tried removing the plugins part that nwilging suggested out of the tailwind conf file but I got different compiling errors. Anyone else get an undefined error message when compiling?

**Comment by ramonfritsch** [comment]
Can we re-open this issue? It's still happening.

`@tailwind/ui` needs to update the `@tailwind/typography` dependency to `^0.5.0` in order to fix the issue and work with v3, otherwise we can't use `@tailwind/ui` on v3 yet.

**Comment by JamieShelley** [comment]
None of the highest voted answered fix this for me.
As mklueh stated: '"@tailwindcss/typography": "^0.4.1",'

**Comment by adamwathan** [comment]
Remove `@tailwindcss/ui`, that package was made obsolete when Tailwind CSS v2.0 was released back in 2020 👍🏻

**Comment by tianzhou** [comment]
Hit the same issue and reverted the upgrade fixed it 

The before & after package.json change is in the commit https://github.com/bytebase/bytebase.com/commit/5e4e3b855c337462d2701f3c56869d9b5b654435

BTW, our project enables synk and it suggested the upgrade https://github.com/bytebase/bytebase.com/pull/33

**Comment by mzalevski** [comment]
I do not have tailwindcss/ui dependency but I still have this issue in typography pugin version above 0.4.1 :/

**Comment by Decipher** [comment]
I also found this issue in 0.5.2, so I have also downgraded to 0.4.1 to resolve it.

**Comment by dinta0623** [comment]
> I also found this issue in 0.5.2, so I have also downgraded to 0.4.1 to resolve it.

same here

**Comment by AlejandroBec94** [comment]
> I specifically had the problem using nuxt/tailwindcss-module with `"@tailwindcss/typography": "^0.5.0",` , which seems to not be compatible anymore with tailwindcss < 3.0.0.
> 
> The Nuxt TailwindCSS module uses tailwind:"^2.0.4" and is not upgraded yet to Tailwind 3, see [nuxt-modules/tailwindcss#407](https://github.com/nuxt-modules/tailwindcss/pull/407)
> 
> **Downgrading to `"@tailwindcss/typography": "^0.4.1",` works for me!**

Thats works for me
