### ISSUE TITLE
Style parser doesn't pick up values in array

### ISSUE THREAD

**Issue by aliveli186** [tailwindlabs/tailwindcss#6418]
If values are in an array `["text-[10px]", "lg:text-[14px]"]` they are not picked up by the parser. Probably due to square brackets used in the array notation which cause the regex parser to fail.
They need to be converted to string and back to array `"text-[10px] lg:text-[14px]".split(" ")` to be picked up by the parser.

Fails:
```
export function getDetailSize(size, count) {
    return formatSizes([
        ["text-[10px]", "lg:text-[14px]"],
        ["text-[12px]", "lg:text-[16px]"]
    ], size, count);
}
```

Works:
```
export function getDetailSize(size, count) {
    const s0 = "text-[10px] lg:text-[14px]".split(" ");
    const s1 = "text-[12px] lg:text-[16px]".split(" ");

    return formatSizes([s0, s1], size, count);
}
```

**Comment by thecrypticace** [comment]
Fixed in #6590
