### ISSUE TITLE
"blur-x" and "backdrop-blur-x" does not work 

### ISSUE THREAD

**Issue by mobayen** [tailwindlabs/tailwindcss#6437]
**What version of Tailwind CSS are you using?**

^3.0.1

**What build tool (or framework if it abstracts the build tool) are you using?**

Nuxt.js ^2.15.7
@nuxt/postcss8 ^1.1.3
postcss ^8.4.5

**What version of Node.js are you using?**

node: '14.17.1',

**What browser are you using?**

I've checked it in chrome, and safari
Images are attached

chrome
![chrome](https://user-images.githubusercontent.com/29548601/145757829-2b7c8240-1365-47db-ac6d-e8bc79dc12b1.png)

safari
![safari](https://user-images.githubusercontent.com/29548601/145757832-3958a4c2-d864-40d0-a7a9-3812080fe180.png)

**What operating system are you using?**

macOS

**Reproduction URL**

https://gist.github.com/mobayen/f877f9f3bb14a968cbe4c02c548a832f

**Describe your issue**

I just upgrades to v3.0.0. Everything seems working fine but the blur 
The backdrop-blur-x and blur-x classes do not work if I put them in the <style> tag of a page

BTW, awesome work 
Keep it up, guys!

**Comment by ivan-bragin** [comment]
Can you please check if the required --tw CSS variables are defined?

**Comment by ivan-bragin** [comment]
@finkrer Oh well, I guess I can just put backdrop-filter as a class to explicitly add --tw-backdrop-filter variable in the flow for now until it gets fixed.

**Comment by adamwathan** [comment]
Thanks for reporting this, this is caused by the same thing internally as https://github.com/tailwindlabs/tailwindcss/issues/6409 so going to close and consolidate there 👍🏻

**Comment by mobayen** [comment]
Awesome, 
it's fixed in 3.0.2

Thanks @adamwathan
