### ISSUE TITLE
Not getting all components on installation

### ISSUE THREAD

**Issue by allthingsdev** [tailwindlabs/tailwindcss#6457]
When I run the install instructions on the installation page [this page](https://tailwindcss.com/docs/installation) I end up with an unminified css file which is only about 400 lines long. I'm trying out tailwind and I get the sense this is not the whole thing. I have cleared my npm cache a few times and it still keeps happening. What am I missing? Or as far as though instructions go, what I'm getting is complete?

**Comment by adamwathan** [comment]
Hey! You need to configure your content paths:

![image](https://user-images.githubusercontent.com/4323180/145828540-3f25d599-8126-4ca9-89bb-58d2aa7571bf.png)

Tailwind only generates the CSS you actually use, so if you don't tell it what files to look at to figure out what classes you are using, the CSS file will be basically empty.

More information here: https://tailwindcss.com/docs/content-configuration
