### ISSUE TITLE
Background color fails to compile when some other selector has the same color prefix 

### ISSUE THREAD

**Issue by davidwebca** [tailwindlabs/tailwindcss#6478]
**What version of Tailwind CSS are you using?**
3.0.1

**What build tool (or framework if it abstracts the build tool) are you using?**
Reproducible on Tailwind CLI and Laravel mix / Webpack

**What version of Node.js are you using?**
For example: v14.18.2

**What browser are you using?**
Chrome

**What operating system are you using?**
macOS

**Reproduction URL**
Fully reproduced bug here, look at the input.css file with the @apply rule
https://github.com/davidwebca/tailwindcss-v3-bg-color-bug

**Describe your issue**
If one of my custom selectors in my stylesheet contains ".bg-green a", the color "bg-green-light" doesn't compile at all. I'm wondering if this is a regex matching issue, but it seems other color utilities work fine.

**Comment by davidwebca** [comment]
Just to be clear, the class "bg-green" doesn't exist per Tailwind's configuration, but it could exist per other tools or framework specifics and once it's included in my code, there's no error, no message from compilation and background color utilities don't compile past that.

**Comment by BakiVernes** [comment]
Same thing happening in my project with the class "text-green-base"

**Comment by davidwebca** [comment]
Thank you for the quick resolve! 🔥

**Comment by staniboy** [comment]
This is an issue in 3.2.4. Using it with vue with postcss. Other bg classes work however bg-green-* doesn't.
