### ISSUE TITLE
Extending multiple color plugins using the same color name causes incorrect colors.

### ISSUE THREAD

**Issue by stefanfisk** [tailwindlabs/tailwindcss#6503]
**What version of Tailwind CSS are you using?**

3.0.2

**What build tool (or framework if it abstracts the build tool) are you using?**

Playground

**What version of Node.js are you using?**

n/a

**What browser are you using?**

n/a

**What operating system are you using?**

n/a

**Reproduction URL**

https://play.tailwindcss.com/v7qgUeljBK?file=config

**Describe your issue**

Extending multiple color plugins using the same color name causes incorrect colors.

See https://play.tailwindcss.com/v7qgUeljBK?file=config for a failing case.

It works when using the same name multiple times directly https://play.tailwindcss.com/qaS9VP8AHE?file=config

**Comment by EdwinFajardoBarrera** [comment]
I would like to work on this, is required to fork the project or just create a branch and a PR is ok?

**Comment by thecrypticace** [comment]
I've worked on a fix but want to do some testing before we merge & release it. In the mean time you should be able to work around this problem by making colors a function that returns an object instead of just a plain object: https://play.tailwindcss.com/QmDTUap8m2?file=config
