### ISSUE TITLE
textAlign isn't configurable

### ISSUE THREAD

**Issue by stefanfisk** [tailwindlabs/tailwindcss#6505]
**What version of Tailwind CSS are you using?**

3.0.2

**What build tool (or framework if it abstracts the build tool) are you using?**

Play

**What version of Node.js are you using?**

n/a

**What browser are you using?**

n/a

**What operating system are you using?**

n/a

**Reproduction URL**

https://play.tailwindcss.com/WxrE0LmdoC?file=config

**Describe your issue**

I cannot configure custom text alignments. Currently I need both `inherit` and once based on custom properties.

As a workaround I am generating then via `@layer utilities`, but these days I almost feel a bit dirty when I create an actual CSS file 😺

**Comment by reinink** [comment]
Hey! So Tailwind doesn't offer any way to customize properties that are hard coded in. This includes things like text align, position, visibility, float, box-sizing, display, and many other core plugins in Tailwind. You can find a complete list of all these in [corePlugins.js](https://github.com/tailwindlabs/tailwindcss/blob/master/src/corePlugins.js) by searching for "addUtilities".

To make this work we'd have to make everything in Tailwind configurable, which feels like a dramatic shift from how we're currently doing things.

That said, adding custom CSS in this way is *totally fine*. Of course, if you have a lot of these, it could become a challenge to manage.

Another option is to use an arbitrary property, for example:

```html
<div class="[text-align:var(--theme-text-align)]">I should be right aligned.</div>
```

You may also want to have a look at the [new RTL support](https://tailwindcss.com/docs/hover-focus-and-other-states#rtl-support) that was added in Tailwind CSS v3.0. Not sure exactly what you're trying to do, but these modifiers might be a good alternative to the approach you're taking.

I hope that helps! 💪
