### ISSUE TITLE
Prefix breaks the build

### ISSUE THREAD

**Issue by zoran-tietoevry** [tailwindlabs/tailwindcss#6513]
**What version of Tailwind CSS are you using?**
- v3.0.2

**What build tool (or framework if it abstracts the build tool) are you using?**
- Tailwind CLI

**What version of Node.js are you using?**
- v17.2.0

**What operating system are you using?**
- macOS

**Reproduction URL**
- [tailwindcss.com (playground)](https://play.tailwindcss.com/mb9g5EZdCS?file=config)

**Describe your issue**

Using prefix in the tailwind.config.js will make the build to not generate classes. Removing prefix and it works again.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

If you are using the prefix, then you have to make sure that you actually prefix the usage of it as well: 

- https://tailwindcss.com/docs/configuration#prefix
- https://play.tailwindcss.com/21iL2vG1zB

**Comment by zoran-tietoevry** [comment]
Such a miss from my part. Thanks for the fast feedback.

**Comment by Steffi3rd** [comment]
> Hey! Thank you for your question! Much appreciated! 🙏
> 
> If you are using the prefix, then you have to make sure that you actually prefix the usage of it as well:
> 
> * https://tailwindcss.com/docs/configuration#prefix
> * https://play.tailwindcss.com/21iL2vG1zB

Hope we can have prefix on post build without rewrite every classNames 🙏
