### ISSUE TITLE
Error: Cannot find module 'anymatch' on npx tailwindcss init

### ISSUE THREAD

**Issue by subramanya4shenoy** [tailwindlabs/tailwindcss#6514]
**What version of Tailwind CSS are you using?**
v3.0.2

**What build tool (or framework if it abstracts the build tool) are you using?**
reactJS

For example: postcss-cli 8.3.1, Next.js 10.0.9, webpack 5.28.0

**What version of Node.js are you using?**
v14.15.1

**What browser are you using?**
chrome

**What operating system are you using?**
Mac (M1 chip)

**Reproduction URL**

A Tailwind Play link or public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.

**Describe your issue**

npm install -D tailwindcss
npx tailwindcss init

the init is failing with below error:
`npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/annymatch - Not found
npm ERR! 404 
npm ERR! 404  'annymatch@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/subu/.npm/_logs/2021-12-14T19_14_17_587Z-debug.log
Subramanyas-MacBook-Pro-2:client subu$ npx tailwindcss init
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'anymatch'
Require stack:
- /Users/subu/exp/textGradient/client/node_modules/chokidar/index.js
- /Users/subu/exp/textGradient/client/node_modules/tailwindcss/lib/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/subu/exp/textGradient/client/node_modules/chokidar/index.js:8:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/subu/exp/textGradient/client/node_modules/chokidar/index.js',
    '/Users/subu/exp/textGradient/client/node_modules/tailwindcss/lib/cli.js'
  ]
}`

Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead.

**Comment by reinink** [comment]
Hey! Without a minimal reproduction repo this is basically impossible for us to help with. I just ran the two commands you provided without any issues:

```sh
➜  test-anymatch npm install -D tailwindcss

added 112 packages, and audited 113 packages in 7s

20 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
➜  test-anymatch npx tailwindcss init

Created Tailwind CSS config file: tailwind.config.js
```

Feel free to post a minimal reproduction repo here, and I'd be happy to have another look 👍

**Comment by subramanya4shenoy** [comment]
This was a fresh react app and just added tailwind 3.0.0. Anyways I fell back to tailwind 2.2.9 and its will do for me.
