### ISSUE TITLE
Preflight: `li` should also receive `list-style: none;`

### ISSUE THREAD

**Issue by TheDutchCoder** [tailwindlabs/tailwindcss#6518]
This could be seen as a feature I guess, though technically I would consider it a bug (albeit a super minor one).

**What version of Tailwind CSS are you using?**

2.2.19

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite 2.6.14

**What version of Node.js are you using?**

16.0.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/9gvJvK1z7S

**Describe your issue**

`ul` and `ol` are styled with `list-style: none;`, which is great, but `list-style` is actually applied to list items, which means that an `li` outside of a list will still render with the defaults.

This seems arbitrary but for example in a component test, where a component (like a `MenuItem`) is extracted as just an `li`, the visual tests will not be 100% accurate.

Contrived Example:
```html
<SomeMenu> <!-- contains ul or ol wrapper -->
  <SomeMenuItem>Item 1</SomeMenuItem> <!-- this will look correct, because it's inside the ul/ol -->
  <SomeMenuItem>Item 2</SomeMenuItem>
</SomeMenu>
```

Test:
```ts
mount(() => <MenuItem>Item 1</MenuItem>) // this will look incorrect because it's isolated
```

I know this is super edge-case-y, but it would be great to have just for visual regression testing of individual component (for example with Cypress).

**Comment by reinink** [comment]
Yeah, screw it, why not lol 👉 https://github.com/tailwindlabs/tailwindcss/commit/00f60e61013c6e4e3419e4b699371a13eb30b75d

**Comment by TheDutchCoder** [comment]
Haha thanks!

**Comment by reinink** [comment]
So we we published this change earlier today and already started getting reports of [issues caused by it](https://github.com/tailwindlabs/tailwindcss/issues/6527), so [we had to revert this](https://github.com/tailwindlabs/tailwindcss/commit/9777562da37ee631bbf77374c0d14825f09ef9af), sorry!

**Comment by TheDutchCoder** [comment]
Ok, no worries, I understand.
Maybe something for v4 ;)
