### ISSUE TITLE
tailwindcss v3.0.2 not working in CRA with typescript template

### ISSUE THREAD

**Issue by mubarakn** [tailwindlabs/tailwindcss#6521]
**What version of Tailwind CSS are you using?**
v3.0.2

**What build tool (or framework if it abstracts the build tool) are you using?**
autoprefixer: "^10.4.0",
postcss: "^8.4.5",
react: "^17.0.2",
react-dom: "^17.0.2",
react-scripts: "5.0.0",
typescript: "^4.5.4"

**What version of Node.js are you using?**
v14.16.0

**What browser are you using?**
Chrome

**What operating system are you using?**
Windows 10

**Reproduction URL**
https://codesandbox.io/s/fragrant-cache-6doxm?file=/src/App.tsx

When tailwindcss is added to the create react app with typescript template it is not working at all

**Comment by waveiron** [comment]
Could not setup with the documentation: 
https://tailwindcss.com/docs/guides/create-react-app

package.json

```json
"dependencies": {
    "autoprefixer": "^10.4.0",
    "postcss": "^8.4.5",
    "tailwindcss": "^3.0.3",
    ...
}
```

craco.config.js

```js
module.exports = {
  style: {
    postcss: {
      plugins: [require('tailwindcss'), require('autoprefixer')],
    },
  },
};
```

Result:

```sh
npm start

Failed to compile.

./src/index.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./src/index.css)
Error: PostCSS plugin tailwindcss requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
```

**Comment by reinink** [comment]
@waveiron Have you tried using a `postcss.config.js` config instead of `craco.config.js`? That's our recommended approach, and what's explained in our guide.

Your `postcss.config.js` should look like this:

```
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
```

Let me know if that helps 👍

**Comment by reinink** [comment]
@mubarakn I was able to get this project working locally with a few changes:

I added a `postcss.config.js` config file, which looks like this:

```js
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
```

I updated `react-scripts` from `4.0.3` to `5.0.0`. You mentioned that you're using version `5.0.0`, but the CodeSandbox had `4.0.3` set.

I updated the `tailwind.config.js` to include `tsx` files, which now looks like this:

```js
module.exports = {
  content: ["./src/**/*.{js,jsx,tsx}"],
  theme: {
    extend: {}
  },
  plugins: []
};
```

With those changes, I was able to get this working locally. It's not working on CodeSandbox — not sure what I'm doing wrong there. I don't use CodeSandbox all that much. Maybe it still just needs to be updated for the latest version of CRA.

Hope that helps 👍

**Comment by mubarakn** [comment]
@reinink Thanks for helping me out.
Few things I was doing wrong.
I was using node v14.x.x so most of the plugins that tailwindcss uses is not installed by default so I had to bump my node.js version to v16
and also I forgot to add "tsx" in tailwind.config.js
I hope this helps others experiencing the same problem.

**Comment by waveiron** [comment]
After several hours of struggling, I found the real reason here is react-script version!

```
npm i react-scripts@5
```

@reinink Thanks for your quick response.

**Comment by geniusit** [comment]
Please update the documation and TRY it, because to me it still not works

**Comment by D4ITON** [comment]
My error was I had wrote 'color' instead 'colors':
`module.exports = {
  theme: {
    extend: {
      colors: {
        'regal-blue': '#243c5a',
      },
    }
  }
}`
