### ISSUE TITLE
components and utilities are empty when using @import

### ISSUE THREAD

**Issue by harisadam** [tailwindlabs/tailwindcss#6530]
**What version of Tailwind CSS are you using?**

tailwindcss@^3.0.3

**What build tool (or framework if it abstracts the build tool) are you using?**

Ember.js postcss-scss/postcss-import

**What version of Node.js are you using?**

For example: v12.0.0

**Reproduction URL**
https://github.com/harisadam/ember-tailwind-3-example

installation steps:
- clone the repo
- run `yarn`
- run `ember s`
- visit http://localhost:4200
- 

**Describe your issue**

I'm using the following imports:
```
@import "tailwindcss/base.css";
@import "tailwindcss/components.css";
@import "tailwindcss/utilities.css";

//scss test
$green: #abc123;

.c-header {
  p {
    color: $green;
  }
}
```

The problem is that only base.css contains css code, both components and utilities are empty so my built css starts with the content of the base.css and ends with the scss test code (green variable and c-header class) – it works fine with Tailwind v2.2.16

https://github.com/harisadam/ember-tailwind-3-example/blob/master/app/styles/app.scss

**Comment by adamwathan** [comment]
Hey! Your `content` configuration is empty so this is expected, Tailwind 3 only generates the CSS you actually use and you haven’t told Tailwind where your template files are.

This is explained in the upgrade guide here:

https://tailwindcss.com/docs/upgrade-guide#configure-content-sources

**Comment by harisadam** [comment]
Oops, It seems that i missed that part of docs, thank you @adamwathan
