### ISSUE TITLE
border-b-4 not longer working after upgrading to version 3, tested on 3.0.3 and 3.0.5

### ISSUE THREAD

**Issue by acostaf** [tailwindlabs/tailwindcss#6532]
Hi Team

Just upgraded to version 3.0.3 from 2.2.19 and all my borders are gone, I can see the css used but cannot see the border anymore.

**What version of Tailwind CSS are you using?**

For example: v3.0.3 and 3.0.5

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss-cli 8.4.5

**What version of Node.js are you using?**

v14 and v16

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Describe your issue**

<div class="flex justify-between border-b-2 border-gray-300 mb-4 cursor-pointer"... does not longer render any border.

**Comment by reinink** [comment]
Hey! I just tried this, and it seems to work. Here's a Tailwind Play illustrating this:

https://play.tailwindcss.com/VE835TgwD5

In these situations we *really need* a minimal reproduction as required in the issue template:

> A Tailwind Play link or public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.

I am going to close this — but feel free to provide a minimal reproduction, and I'd be happy to have another look 👍
