### ISSUE TITLE
Flex Box Naming Conventions

### ISSUE THREAD

**Issue by Gyekye** [tailwindlabs/tailwindcss#6576]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/6575

<div type='discussions-op-text'>

<sup>Originally posted by **Gyekye** December 17, 2021</sup>
I think it would be really cool if we could use the naming convention for your flexbox justify properties: justify-center, justify-evenly etc for the flexbox align properties: align-center, align-start instead of using items-start, items-center, I think it will make it much easier to remember.</div>

**Comment by adamwathan** [comment]
Issues are for bug reports, please don’t convert feature request discussions to issues.
