### ISSUE TITLE
HeadlessUI Popover Panel (PopperJS) jumps position when using Tailwind v2/3 in JIT mode

### ISSUE THREAD

**Issue by tonyclemmey** [tailwindlabs/tailwindcss#6597]
**What version of Tailwind CSS are you using?**

v3.0.6 and previously v2.2.19

**What build tool (or framework if it abstracts the build tool) are you using?**

Gatsby v4.4.0

**Reproduction URL**

Fork of "gatsby-starter-default" with TailwindCSS / HeadlessUI

https://github.com/tonyclemmey/gatsby-starter-default
https://codesandbox.io/s/gatsby-tailwind-headlessui-popover-test-2tzfe?file=/src/components/popover.js

**Describe your issue**

When previously using Tailwind v2.2.19, HeadlessUI Popover (PopperJS) component appeared to be correctly positioned but when switching to JIT mode the position will initially be correct but then jump to the top left corner / off screen, until scroll then it will position correctly again.

Not sure what is causing the issue between switching to JIT mode and the component code https://github.com/tonyclemmey/gatsby-starter-default/blob/master/src/components/popover.js

**Comment by thecrypticace** [comment]
Hey, appreciate the report. This one is super weird but I believe it is an issue with Popper as I can get the same thing to happen in Tailwind CSS v2 with or without JIT.  In your example the `enter="…"` and `leave="…"` props are missing the `transition` class. This was required in Tailwind v2 w/o JIT. If you add that you will see that it exhibits the same broken behavior.

As a further step, I removed Tailwind CSS from the equation entirely and went down to just some basic CSS and it appears that applying a translate to an element breaks popper's positioning some how. I also want to note that the behavior is different (but still wrong) in Chrome vs Safari which leads me even further to believe that it could be a combination of a Popper and browser issue.
