### ISSUE TITLE
String interpolation doesn't work in TailwindCSS v3

### ISSUE THREAD

**Issue by johackim** [tailwindlabs/tailwindcss#6607]
**What version of Tailwind CSS are you using?**

v3.0.7

**What build tool (or framework if it abstracts the build tool) are you using?**

Next.js 12.0.7

**What version of Node.js are you using?**

v16.13.1

**What browser are you using?**

Chromium

**What operating system are you using?**

Linux

**Reproduction URL**

https://codesandbox.io/s/github/johackim/bug-tailwind

**Describe your issue**

I can't use String Interpolation on TailwindCSS v3 :

```js
// https://github.com/johackim/bug-tailwind/blob/master/pages/index.js

const Index = ({ color }) => (
    <button className={`bg-${color}-600`}>
        Hello world
    </button>
);

Index.defaultProps = {
    color: 'gray',
};

export default Index;
```

The button is not gray on TailwindCSS v3 and it work on [TailwindCSS v2](https://githubbox.com/johackim/bug-tailwind/tree/work/).

**Comment by adamwathan** [comment]
Hey! This is covered in the docs:

https://tailwindcss.com/docs/content-configuration#class-detection-in-depth

This was true in v2 as well if you were purging unused styles, which you definitely should be otherwise you are shipping a 3mb CSS file.
