### ISSUE TITLE
The base style `abbr[title]` has high specificity

### ISSUE THREAD

**Issue by neupauer** [tailwindlabs/tailwindcss#6623]
**What version of Tailwind CSS are you using?**

v3.0.1

**What build tool (or framework if it abstracts the build tool) are you using?**

_doesn't matter_

**What version of Node.js are you using?**

_doesn't matter_

**What browser are you using?**

_applies to all_

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/vZuq40tVV7

**Describe your issue**

The base style `abbr[title]` has high specificity and cannot be modified with utilities like `.decoration-solid` etc.

https://github.com/tailwindlabs/tailwindcss/blob/e8e64f0ff4ccb3393f099c716c142b6e06718bb5/src/css/preflight.css#L57-L63

It's necessary to reduce the specificity with e.g. `:where`

**Comment by reinink** [comment]
Hey thanks for bringing this to our attention. I've made a little tweak to Preflight as you suggested, using `:where()` 👍
