### ISSUE TITLE
Box Shadow Color needs to be set for each breakpoint?

### ISSUE THREAD

**Issue by 22289d** [tailwindlabs/tailwindcss#6642]
**What version of Tailwind CSS are you using?**

3.0.5 

**What build tool (or framework if it abstracts the build tool) are you using?**

webpack@5.65.0

**What version of Node.js are you using?**

17.0.1

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/22289d/boxshadow/blob/main/index.html

**Describe your issue**

In the docs[1], it says "Note that if you change the box shadow size at a different breakpoint, or on another state like hover, it will override any existing shadow colors. To preserve the shadow color in these states, it needs to be respecified" 

And the example given is:

`class="shadow-lg shadow-red-500 md:shadow-xl md:shadow-red-500"
`

To me - logically and based on what the docs say -- this means that if you write it like this, everything should have shadow-red-500 box shadow, as shadow-red-500 is last.  

`class="shadow-sm sm:shadow-lg md:shadow-2xl shadow-red-500"
`

There is nothing to 'override' - as the docs say, I didn't set the color until the end.

However, if you write it like that, only shadow-sm will have a box shadow color. It gets overwritten by shadow-lg and stays that way for shadow-2xl. The only way to get the desired behavior here is to write it like this:

`class="shadow-sm shadow-red-500 sm:shadow-lg sm:shadow-red-500 md:shadow-2xl md:shadow-red-500"
`

This seems like a bug. If it's not, the docs should be updated to make it clear this is what you need to do. And it would obviously be better to have a method which is not so verbose.

[1]https://tailwindcss.com/docs/box-shadow-color

**Comment by adamwathan** [comment]
Hey! The docs are correct, this is the only way to make it possible for you to change the shadow color back to the default shadow color.

For example, say I want a `lg` shadow that is `red-500` by default, but on medium screens I want it to be the default shadow color again. This is how you do that:

```html
<div class="shadow-lg shadow-red-500 md:shadow-lg">
```

This isn't possible if the color is automatically preserved as the breakpoints change. Agree it's slightly annoying when you are changing the size and want to preserve the color, but it's not possible to support both cases, and making the color preserved actually makes the case above completely impossible, whereas not preserving the color doesn't stop you from re-adding the color class.

> everything should have shadow-red-500 box shadow, as shadow-red-500 is last

The order of your classes in your HTML doesn't matter to the browser, the only thing that matters is the order of the declarations in your CSS file.

These are both blue:

```
<style>
.text-red {
  color: red;
}

.text-blue {
  color: blue;
}
</style>

<div class="text-red text-blue">Hello world</div>
<div class="text-blue text-red">Hello world</div>
```

Nothing we can do to change that, that's just standard browser/CSS behavior.

**Comment by 22289d** [comment]
@adamwathan i learned something about CSS today, thank you :)

in any event, as i know you know and agree, it's super verbose as is.

it seems like an additional class could solve the problem you're describing.

`class="shadow-lg md:shadow-xl shadow-lime-300 sm:shadow-default"`

Where the presence of the 'shadow-default' class only impacts the specified breakpoint and no others. This makes it very verbose to make lots of changes at different breakpoints, which i think is better than it being very verbose out of the box.
