### ISSUE TITLE
Syntax Error: Error: PostCSS plugin tailwindcss requires PostCSS 8.

### ISSUE THREAD

**Issue by craigp1231** [tailwindlabs/tailwindcss#6651]
package.json devDependencies
```
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-airbnb": "^5.0.2",
    "autoprefixer": "^10.4.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-vue": "^7.0.0",
    "postcss": "^8.4.5",
    "tailwindcss": "^3.0.7"
```

**What version of Tailwind CSS are you using?**

3.0.7

**What build tool (or framework if it abstracts the build tool) are you using?**

@vue/cli 4.5.15   
NPM 8.1.2

**What version of Node.js are you using?**

v16.13.1

**What browser are you using?**
N/A

**What operating system are you using?**

Windows

**Describe your issue**

When attempting to build, the following error appears

`Syntax Error: Error: PostCSS plugin tailwindcss requires PostCSS 8.`

As you can see in my package.config, postcss is 8.4.5. I am not sure what the issue is here? Is the Node version too high?

**Comment by craigp1231** [comment]
This was caused by @vue/cli-service using PostCSS 7 instead of 8. I had to use the next version of the cli-service

**Comment by megasanjay** [comment]
> This was caused by @vue/cli-service using PostCSS 7 instead of 8. I had to use the next version of the cli-service

Quick question but would you mind stating which version of the CLI you ended up moving to?

**Comment by craigp1231** [comment]
> > This was caused by @vue/cli-service using PostCSS 7 instead of 8. I had to use the next version of the cli-service
> 
> @craigp1231 Quick question but would you mind stating which version of the CLI you ended up moving to? Using the CLI in a electron project but all the versions I keep trying seem to break something else.

I ended up using "@vue/cli-service": "5.0.0-rc.1"

**Comment by megasanjay** [comment]
@craigp1231 Thank you. I found out that the issue was with my ESlint installation. It seems like I had to update to ESlint 7 with that version of the vue/cli. Thanks for the help. Cheers :)
