### ISSUE TITLE
Gatsby Webpack Cache Not Resolving  postcss-loader/dist/cjs

### ISSUE THREAD

**Issue by LinnJS** [tailwindlabs/tailwindcss#6669]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/6370

<div type='discussions-op-text'>

<sup>Originally posted by **LinnJS** December 10, 2021</sup>
[webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Resolving 'postcss-loader/dist/cjs'

I have been having this error since Tailwind V2 and just upgraded to V3 hoping this was something that would just go away hoping it was a dependency bug or something but its still happening and I am tired of seeing it. Does anyone know how to fix this?

Here is a [link](https://github.com/LinnJS/suncoast-masons) to the open source project

![image](https://user-images.githubusercontent.com/23741323/145601590-554797e8-55b1-4aed-9130-455adfba494c.png)
</div>

**Comment by reinink** [comment]
Hey! At first glance I don't think that this is a Tailwind CSS issue. Our discussions is a better place to work through questions like this. Closing in favor of the existing discussion 👍
