### ISSUE TITLE
arbitrary values not working with @apply

### ISSUE THREAD

**Issue by kavience** [tailwindlabs/tailwindcss#6698]
**What version of Tailwind CSS are you using?**

v3.0.7

**What build tool (or framework if it abstracts the build tool) are you using?**

 webpack 5.28.0

**What version of Node.js are you using?**

For example: v14.17.6

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

A Tailwind Play link or public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.

**Describe your issue**
It looks like arbitrary values not working with @apply in less file.

```less
.root {
    @apply h-[500px];
}
```
The error is: 

**The `h-` class does not exist. If `h-` is a custom class, make sure it is defined within a `@layer` directive.**

everything is ok but this.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We can't help you without a reproduction repo / Tailwind Play link.
Here is a working Tailwind Play link: https://play.tailwindcss.com/erESL2rdNu?file=css
