### ISSUE TITLE
HSL no longer works in JIT

### ISSUE THREAD

**Issue by agusterodin** [tailwindlabs/tailwindcss#6709]
**What version of Tailwind CSS are you using?**

v3.0.7

**What build tool (or framework if it abstracts the build tool) are you using?**

Next 12.0.7, VSCode 1.63.2, latest version of Tailwind IntelliSense plugin

**What version of Node.js are you using?**

v16.13.0

**What browser are you using?**

N/A

**What operating system are you using?**

macOS

**Reproduction URL**

The `bg-[hsl(202deg,96%,16%)]` class name.

**Describe your issue**

This used to work in previous Tailwind 2.x versions but `bg-[hsl(202deg,96%,16%)]` but no longer works.

**Comment by adamwathan** [comment]
Thanks! Looks like we need to account for the unit on the first value in our parser, because using `rad`, `grad`, or `turn` also doesn't work.

One temporary workaround is to add a type hint:

```
bg-[color:hsl(202deg,96%,16%)]
```

...or remove the `deg`:

```
bg-[hsl(202,96%,16%)]
```

Will leave this open until we get a chance to fix though 👍🏻

**Comment by adamwathan** [comment]
Will be fixed in next release, can use `tailwindcss@insiders` in the mean time if you like 👍🏻
