### ISSUE TITLE
Group Hover with prefix config doesn't work

### ISSUE THREAD

**Issue by namcodes** [tailwindlabs/tailwindcss#6716]
a have  issue with prefix config and group hover
```
prefix: 'tw-'

```
parent : group
children: group-hover:tw-scale-100

can't work with the prefix!

```
<div class="tw-flex tw-items-center tw-rounded tw-cursor-pointer group">
  <div class="">Nam Ng</div>
  <div class="tw-flex tw-items-center tw-transition-all tw-duration-100 tw-scale-0 group-hover:tw-scale-100">
    <div class="tw-text-xs">Edit name</div>
  </div>
</div>
```

**Comment by adamwathan** [comment]
Hey! Needs to be `tw-group`: https://play.tailwindcss.com/by3qjyXoia

**Comment by aryan-myrtle** [comment]
@adamwathan thanks bruvvvvv

**Comment by designbyadrian** [comment]
It's Feb 15th 2023 and I was still stumped on this again until I remembered there was something about group-hover and prefixed Tailwind.

**Comment by vityapro** [comment]
Hey what about `group-[.class]:tw-bg-blue-500` for some reason it's not working for me: https://play.tailwindcss.com/cxSWYn1qBg

**Comment by isarikaya** [comment]
> 

Hey .lol it needs prefix in it.
https://play.tailwindcss.com/u9ab4poHKQ
