### ISSUE TITLE
Default colour not applied to ring when using function to generate it

### ISSUE THREAD

**Issue by villekivela** [tailwindlabs/tailwindcss#6748]
**What version of Tailwind CSS are you using?**
v3.0.5

**What build tool (or framework if it abstracts the build tool) are you using?**
postcss-cli 8.4..5

**What version of Node.js are you using?**
v16.13.1

**What browser are you using?**
Chrome

**What operating system are you using?**
macOS

**Reproduction URL**
[Repo te reproduce bug](https://github.com/villekivela/tailwind3-bug)

**Describe your issue**
Default colour is not applied when using a function to generate default colour for ring. Works for border. Was working v2.2.19.

**Comment by prakhart111** [comment]
@villekivela I worked in this, didn't got the solution, but will like to add something I figured out.
It does with functions with hard coded colour values, the issue lies in doing the same variably.
A simple hard coded colour returning function
`const col = () => {return "#FF0000";}`
and calling part

**Comment by rmartin177** [comment]
> @villekivela I worked in this, didn't got the solution, but will like to add something I figured out. It does work with functions with hard coded colour values, the issue lies in doing the same variably. A simple hard coded colour returning function `const col = () => {return "#FF0000";}` and calling part `ringColor: { DEFAULT: col(), }` This works perfectly

i have the same problem but it curious how with colors like bg-sky-700 work but with another no, can you check if for this color  work in your proyect?
