### ISSUE TITLE
Arbitrary value for `.grid-span` doesn't work

### ISSUE THREAD

**Issue by arzatskis** [tailwindlabs/tailwindcss#6752]
**What version of Tailwind CSS are you using?**

For example: v3.0.1

**Reproduction URL**

https://play.tailwindcss.com/9TfkbefkXH

**Describe your issue**

Using arbitrary values for `.grid-span-[*]` doesn't generate any CSS. Even though `.grid-span-2` and `.grid-span-[2]` wouldn't be the same, This should output `.grid-span-\[2\] { grid-columns: 2 }` (which is valid CSS expression)

Another case: V3.0.1 introduced underscores as workaround for spaces in arbitrary sizes (e.g. `w-[calc(100px_+_200px)]` /  `shadow-[0_5px_10px_red]`). Yet this also doesn't work when applying for grid span utilities. E.g. `.grid-span-[span_2_/_span_2]` also doesn't generate any CSS.  My expectation would be that all utilities should work the same and using `grid-span-[span_2_/_span_2]` would generate `.grid-span-\[span_2_span_2\] { grid-columns: span 2 / span 2 }`

**Comment by adamwathan** [comment]
Hey! There are no utilities named `grid-span` in Tailwind, just [`col-span-*`](https://tailwindcss.com/docs/grid-column) and [`row-span-*`](https://tailwindcss.com/docs/grid-row). The prefix for the `col-span-*` is just `col-*` so any arbitrary values for that look like `col-[span_2_/_span_2]` for example.

Switching `grid` to `col` generates the CSS as expected:

![image](https://user-images.githubusercontent.com/4323180/147485343-f66aa6b5-2c4f-4fc5-b086-b8b0abdd77a7.png)

https://play.tailwindcss.com/o5qOYtKfto

Hope that helps.

**Comment by ahsath** [comment]
hey @adamwathan the docs for `col-span-*` is using `col-span-[*]` for arbitrary values, realized it wasn't working for me and came across this closed issue

![image](https://user-images.githubusercontent.com/37009121/150693668-20aa86cf-8100-4599-8ee7-b7d22e654e13.png)
