### ISSUE TITLE
DEBUG environment variable

### ISSUE THREAD

**Issue by arcanis** [tailwindlabs/tailwindcss#6769]
**What version of Tailwind CSS are you using?**

2.x, 3.x

**What build tool (or framework if it abstracts the build tool) are you using?**

n/a

**What version of Node.js are you using?**

n/a

**What browser are you using?**

n/a

**What operating system are you using?**

n/a

**Reproduction URL**

Any project can be used to reproduce the issue. Just add `DEBUG=something` in the environment.

**Describe your issue**

The JS ecosystem, pushed by the [`debug`](https://github.com/debug-js/debug) package (625M dl / month 🔥), defined the `DEBUG` environment variable as a comma-separated list of tags. This lets multiple tools write their own debug messages, letting the user pick the ones they want to show.

Tailwind doesn't follow this pattern (it just checks [whether the value is anything other than 0](https://github.com/tailwindlabs/tailwindcss/blob/de1bdb4f5df663c10fb641deeb331f36daf2d7ae/src/lib/sharedState.js#L4)), causing Tailwind to print a large amount of unwanted logs if we attempt to print debug logs for anything else.

For instance, I get the following logs after each rebuild in a Next.js application (which I run with `DEBUG='postgraphile:*'` in order to get some debug information I care about); as you can see, two lines are for Webpack, and 22 are for Tailwind:

![image](https://user-images.githubusercontent.com/1037931/147571730-9acde10e-7424-4aa5-a436-c9d04dd8859f.png)

Tailwind should instead respect the `DEBUG` comma-separated-tags convention, and only print debug logs if DEBUG contains something `tailwind` in its tags (ie `DEBUG=tailwind`, `DEBUG=postgraphile,tailwind`, etc).

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

I've added a PR that improves the parsing of the `DEBUG` environment variable.
It will be available in the next version, but you can already try it using the `@insiders` build.
