### ISSUE TITLE
Can't use `<` character for custom screens

### ISSUE THREAD

**Issue by mitchuman** [tailwindlabs/tailwindcss#6778]
**What version of Tailwind CSS are you using?**

v3.0.7

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.5, gatsby 4.4.0

**What version of Node.js are you using?**

v14.15.4

**What browser are you using?**

irrelevant

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/Meb9gStW4l?size=398x720

**Describe your issue**

Not able to use `<` character for custom screens (regardless of extending or not).

**Possible feature request** to have `(max-width: *px)` media queries set by default with this `<` character setup (eg. `<md`, `<3xl`), similar to [how Windi CSS does their setup](https://windicss.org/features/responsive-design.html#custom-range).

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This has been fixed and will be released later today. In the meantime you can already try it using the insiders build `npm install tailwindcss@insiders`.
