### ISSUE TITLE
Previous change to "abbr[title]" causing warning from angular

### ISSUE THREAD

**Issue by Cephyric-gh** [tailwindlabs/tailwindcss#6805]
**What version of Tailwind CSS are you using?**

3.0.8

**What build tool (or framework if it abstracts the build tool) are you using?**

Angular 13.1.2 (with scss as the style option)

**What version of Node.js are you using?**

16.13.0

**What browser are you using?**

N/A

**What operating system are you using?**

MacOS

**Reproduction URL**

My codebase is private, however I believe a basic angular setup with tailwind in it will work.

**Describe your issue**

A change was made in response to https://github.com/tailwindlabs/tailwindcss/issues/6623 to change the preflight selector for abbr to `abbr:where([title])`, which seems to not play well with angular. When it gets to outputting the CSS file into the index file it outputs the following warning:
```
1 rules skipped due to selector errors:
  abbr:where([title]) -> unmatched pseudo-class :where
```

It doesn't stop the build or anything, but seems to be under the impression the pseudo-selector doesn't exist. The warning is output based on the following browserslist optimization:
```
last 1 Chrome version
last 1 Firefox version
last 2 Edge major versions
last 2 Safari major versions
last 2 iOS major versions
Firefox ESR
not IE 11
```

**Comment by adamwathan** [comment]
Hey! Seems like something is outdated in whatever is linting that, because at a quick glance it seems supported in all of those browsers:

![image](https://user-images.githubusercontent.com/4323180/147772173-6b61c26d-4ef6-4d19-ba81-3e309e037dd3.png)

No plans to change this I'm afraid.

**Comment by Cephyric-gh** [comment]
Fair enough, I will open an issue Angular's end to see what I can do with it
