### ISSUE TITLE
Media queries missing in production build when prefix is used

### ISSUE THREAD

**Issue by danielehrhardt** [tailwindlabs/tailwindcss#6828]
**What version of Tailwind CSS are you using?**

For example: v3.0.8

**What build tool (or framework if it abstracts the build tool) are you using?**
Angular 13.1.1
For example: postcss-cli 8.3.1, Next.js 10.0.9, webpack 5.28.0

**What version of Node.js are you using?**
16
For example: v12.0.0

**What browser are you using?**
N/A
For example: Chrome, Safari, or N/A

**What operating system are you using?**
macOS / Windows
For example: macOS, Windows

**Reproduction URL**

A Tailwind Play link or public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.

**Describe your issue**
When i use a prefix in the tailwind config. For example tw- and run a Production build then all the Media Queries are missing.

**Comment by danielehrhardt** [comment]
Not related to the prefix. But i still do not understand why the media queries are missing in my production build.

**Comment by josephbona** [comment]
How was this resolved?

**Comment by joergrech** [comment]
I have the same problem. Maybe next.js "optimizes" it out of the final files?
