### ISSUE TITLE
Angular 13 Tailwind 3 jit not updating.

### ISSUE THREAD

**Issue by Deegiimurun** [tailwindlabs/tailwindcss#6847]
What version of Tailwind CSS are you using?

v3.0.8

What build tool (or framework if it abstracts the build tool) are you using?

Angular 13.1.2

What version of Node.js are you using?

16.13.1

What browser are you using?

Chrome

What operating system are you using?

Windows 10

Describe your issue

1. SImply create new angular project and add tailwind, tailwind configuration. 
2. Change app.component.html with ` <div class="h-[100px] w-[100px] bg-red-100"></div>`
3. Run first time with ng serve.(It works fine).
4. Stop dev server
5. Change app.component.html with `<div class="h-[200px] w-[200px] bg-blue-100"></div>`
7. Start dev server again
Problem: angular-cli says tailwind is in watch mode but its not refreshing or adding new class. Not only changing classes cause this error. From time to time tailwind just stopped generating style for classes.

**Comment by thecrypticace** [comment]
Hi, thanks for the report. After investigating I've discovered that this stems from two things:
- Angular CLI setting `TAILWIND_MODE=watch`
- Angular build caching

Basically using `TAILWIND_MODE=watch` causes files to be watched outside of angular and as such it doesn't know to invalidate the cached CSS when the html files have changed.

In the short term:
1. Remove your `.angular` folder
2. Run the dev server in powershell with an overridden env var like so: `$env:TAILWIND_MODE = "build"; ng serve` (I think I've got the syntax right there)

I've got a PR open to fix this on the angular CLI side: https://github.com/angular/angular-cli/pull/22447

**Comment by Deegiimurun** [comment]
HI, Thanks for quick fix. I find it more easier just update update angular environment file to
```
export const environment = {
  production: false,
  TAILWIND_MODE: 'build'
};
```

**Comment by alk841** [comment]
Just-in-Time build css still not working in Angular v13 and Tilewindcss v3.0.15. Can help me someone?

This not work for me.
export const environment = {
  production: false,
  TAILWIND_MODE: 'build'
};

Build with firs change save in home component works. Another save not works.

**Comment by zajcman** [comment]
you must upgraded from Angular 13.0 to 13.2.2 via the Angular CLI command ng update ( this is solution from Angular: https://github.com/angular/angular-cli/pull/22447 )

**Comment by na-95** [comment]
As @zajcman said, updating my project to 13.2 solved the issues. Tailwind CSS is now rebuilt each time I add a new class to my html files.

**Comment by draganpodvezanec** [comment]
Here is the workaround if still doesn't work for you:

https://stackoverflow.com/a/73446036/7556720

**Comment by IgorKurkov** [comment]
last link doesn't work for me, next one works - try https://github.com/nrwl/nx/issues/4775#issuecomment-996151678

**Comment by martonsimon** [comment]
I was having the same problem where updating the tailwind classes on an html element didn't get reflected in watch mode, except if I reloaded the server or modified a css/scss file or config file.
To solve it, you should enable **ESBuild** on the project (but be aware that it is still in development https://angular.io/guide/esbuild), by modifying the **architect.build.builder** attribute inside **angular.json**, like so:
```
...
"architect": {
  "build": {
    "builder": "@angular-devkit/build-angular:browser-esbuild",
...
```
