### ISSUE TITLE
Problem with Tailwind in combination with react-markdown

### ISSUE THREAD

**Issue by jakeherp** [tailwindlabs/tailwindcss#6874]
**What version of Tailwind CSS are you using?**

For example: v3.0.8

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.5, Next.js 12 (latest), React 17.0.2

**What version of Node.js are you using?**

16.13.0

**What browser are you using?**

Brave / Chrome 96.0.4664.110, Safari 15.2, Firefox Developer Edition 96.0b8

**What operating system are you using?**

macOS 12.1

**Describe your issue**

I have a problem with Tailwind and react-markdown, where some styles just won't appear, even though the classes are set correctly. Wondering if this could be a postcss issue?
For my ReactMarkdown component I have the following list of components that I export and reuse wherever I use react-markdown:

```typescript
export const mdxComponents: Components = {
    ul: ({ children }) => <ul className="list-disc ml-4 mt-4">{children}</ul>,
    li: ({ children }) => <li className="mt-1">{children}</li>,
    img: ({ alt, src }) => (
        <div className="relative w-full aspect-video drop-shadow-xl">
            <Image
                src={src}
                alt={alt}
                layout="fill"
                objectFit="cover"
                className="mt-4 mb-4"
            />
        </div>
    ),
    // ...
};
```

(shortened a bit to exclude the elements I have no issues with)

For the `ul`, `li` and `img` elements I have the issue, that the classes are there in the markup, but the styles are not applied for whatever reason. See the screenshot attached:

![Screenshot_2022-01-04_at_12 13 39](https://user-images.githubusercontent.com/17340718/148083788-6bef0c1c-1e33-4a4b-b3f5-3f39d9e11c94.png)

**Comment by jakeherp** [comment]
Hah, I actually did not include it - moved the file out of the components folder and my config only covered components and pages folders 🤦‍♂️ Thanks for your help!

Closing this issue!

**Comment by NatumanyaGuy** [comment]
Hello, thanks for opening this issue. I am using svelte-markdown and I solved it by extending "Preflight" on Tailwind via tailwind.cjs. Please see the docs here: https://tailwindcss.com/docs/preflight#extending-preflight
Happy Coding

**Comment by MatthewTt** [comment]
You can try `@tailwindcss/typography` this plugin
[https://tailwindcss.com/docs/typography-plugin](https://tailwindcss.com/docs/typography-plugin)

**Comment by NatumanyaGuy** [comment]
Thanks a lot @MatthewTt !

**Comment by joel-lyzr** [comment]
I couldn't get typography plugin to work.

**Comment by Malith-Rukshan** [comment]
> I couldn't get typography plugin to work.

Add the plugin to your `tailwind.config.js` file :

```typescript
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    // ...
  },
  plugins: [
    require('@tailwindcss/typography'),
    // ...
  ],
}
```

**Comment by Abhishek21k** [comment]
https://github.com/tailwindlabs/tailwindcss/discussions/17645#discussioncomment-13035026

for anyone having issue in markdown not rendering see this issue
