### ISSUE TITLE
svg fill color not working with tailwindcss v3.0.11

### ISSUE THREAD

**Issue by aestheticsdata** [tailwindlabs/tailwindcss#6910]
**What version of Tailwind CSS are you using?**

v3.0.11

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.5

**What version of Node.js are you using?**

v16.3.1

**What browser are you using?**

Brave Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (arm64)

**What operating system are you using?**

macOS

**Describe your issue**

with tailwindcss v2.2.19, changing the svg color was working fine,  using eg: "fill-current text-green-600" as in the docs.
with tailwindcss v3.0.11, changing the svg color is not working anymore, using eg: "fill-green-600" as in the docs.

**Comment by adamwathan** [comment]
Guessing you have a custom color palette that doesn't include `current`:

https://tailwindcss.com/docs/upgrade-guide#fill-and-stroke-use-color-palette

This does work out of the box unless you have customized your color palette 👍🏻 

https://play.tailwindcss.com/jVGZRp8vlw

**Comment by getnashty** [comment]
@adamwathan I'm seeing the same problem - https://play.tailwindcss.com/oZkcmFq0C1 - anything obviously wrong? if you remove the `stroke="black"` attribute, the stroke will disappear.

this is using an icon from Iconic.app

**Comment by getnashty** [comment]
I did fix this if anyone hits it, it just had to do w/ the SVG code itself..

**Comment by amscher** [comment]
I'm running into the same issue... <svg class="fill-blue-800">...</svg>
It doesn't actually fill using the correct color. Any suggestions?

**Comment by getnashty** [comment]
@amscher here is how I'm using it (my SVGs are components in React, so the attributes are camelCased) - but this works for me...

For Stroke:
```
    <svg
      className="stroke-current"
      width="100%"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
        d="M18.25 11.5V19.25M5.75 19.25V11.5M9.75 19.25V11.5M14.25 19.25V11.5"
      ></path>
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
        d="M12 4.75L19.25 11.25H4.75L12 4.75Z"
      ></path>
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
        d="M4.75 19.25H19.25"
      ></path>
    </svg>
```

For Fill:
```
    <svg
      className={"fill-current"}
      width="100%"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M13.1205 6.19308C12.6597 5.27305 11.3466 5.27285 10.8855 6.19267L10.8855 6.19268L5.62247 16.6897L4.95202 16.3535L5.62247 16.6897C5.20573 17.5209 5.81006 18.4999 6.73989 18.4999H17.2611C18.1907 18.4999 18.795 17.5213 18.3787 16.6902L18.3787 16.6901L13.1206 6.19309L13.1205 6.19308ZM9.54457 5.52038C10.5592 3.49668 13.4478 3.49725 14.4617 5.52127L14.4617 5.52128L19.7199 16.0183L19.7199 16.0184C20.6358 17.8468 19.3063 19.9999 17.2611 19.9999H6.73989C4.69427 19.9999 3.36472 17.846 4.28157 16.0174L9.54457 5.52039L9.54457 5.52038ZM12 9C12.5523 9 13 9.44772 13 10V12C13 12.5523 12.5523 13 12 13C11.4477 13 11 12.5523 11 12V10C11 9.44772 11.4477 9 12 9ZM13 16C13 16.5523 12.5523 17 12 17C11.4477 17 11 16.5523 11 16C11 15.4477 11.4477 15 12 15C12.5523 15 13 15.4477 13 16Z"
      />
    </svg>
```

**Comment by takumaterada** [comment]
いいね

**Comment by JwanKhalaf** [comment]
@getnashty with this SVG:

```
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M3 12H21M3 6H21M3 18H15" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
```

Even when I change to:

```
          <svg
            width="24"
            height="24"
            class="fill-gray-50"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M3 12H21M3 6H21M3 18H15"
              fill-rule="evenodd"
              clip-rule="evenodd"
            />
          </svg>
```

It still doesn't fill the color!

**Comment by getnashty** [comment]
there is no “fill-gray-50”… you want “fill-current text-gray-50”
