### ISSUE TITLE
Potential Bug: After Pseudo Element Content Strips '_'

### ISSUE THREAD

**Issue by TheDolentCity** [tailwindlabs/tailwindcss#6915]
I am using Google Material Icons which require strict names like `check_box_outline_blank` to render icons. I was trying to render a checkbox outline icon as a pseudo element, but the generated CSS strips the `_` character from the content causing a misrender. I can correct it manually and confirm that version works, but it is overwritten every time Tailwind CSS runs. I'm not sure if there is a reason that these underscores are stripped and replaced with whitespace, but it appeared like a potential bug to me since there is no way to use Tailwind CSS + Google Material Icons in pseudo elements if this is the case.

**To Reproduce:**

The inline style: `after:content-['check_box_outline_blank']`

The compiled CSS:
```
.after\:content-\[\'check_box_outline_blank\'\]::after {
  --tw-content: 'check box outline blank';
  content: var(--tw-content);
}
```

**Project:** .NET 5 Blazor WebAssembly
**Tailwind CSS Version:** 3.0.11

**Comment by adamwathan** [comment]
Hey! This is by design as there's no other way to put spaces in. If you need to keep underscores though you can escape them like this:

```
after:content-['check\_box\_outline\_blank']
```

Docs here: https://tailwindcss.com/docs/adding-custom-styles#handling-whitespace
