### ISSUE TITLE
Accent colors are not working in safari

### ISSUE THREAD

**Issue by dheeraj-murali** [tailwindlabs/tailwindcss#6945]
**What version of Tailwind CSS are you using?**
v3.0.7

**What build tool (or framework if it abstracts the build tool) are you using?**
 Next.js 11.1.2

**What version of Node.js are you using?**
v16.13.1

**What browser are you using?**
Safari Version 15.2

**What operating system are you using?**
macOS

**Reproduction URL**
https://play.tailwindcss.com/WEInXiEoD9

**Describe your issue**
Accent color for checkbox is not working in safari.
The issue is also visible in the documentation.

![Screenshot 2022-01-07 at 1 12 22 PM](https://user-images.githubusercontent.com/17213265/148510361-bafb8cbc-0c8d-49cb-85c6-124b574040b9.png)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

There is unfortunately nothing we can do here. This is a browser issue and not a Tailwind issue, we have to wait until Safari has `accent-color: ...` support.

It looks like they have support for it in their Technology Preview version: https://caniuse.com/?search=accent-color
