### ISSUE TITLE
Tailwind not generating styles in ESM project.

### ISSUE THREAD

**Issue by jcbbb** [tailwindlabs/tailwindcss#6971]
**What version of Tailwind CSS are you using?**

v3.0.12

**What build tool (or framework if it abstracts the build tool) are you using?**

None.

**What version of Node.js are you using?**

v15.8.0

**What browser are you using?**

Brave

**What operating system are you using?**

macOS

**Reproduction URL**

[https://github.com/jcbbb/scroll-animation](https://github.com/jcbbb/scroll-animation)

**Describe your issue**

Right now, when you try to run `pnpm tailwind`, it is not generating any classes defined in `home.html` but defaults (in `main.min.css`). Classes are not getting picked up from html but only from css file (`main.css`).
But if I change `tailwind.config.cjs` to `tailwind.config.js` and remove `type: module` from `package.json`, everything works as expected. There are no errors, it's just not generating styles.

**Comment by adamwathan** [comment]
Hey! We only look for `tailwind.config.js` by default, so if you are using a different file name you need to specify the config file manually and it'll work:

```
npx tailwindcss -c tailwind.config.cjs -i ./src/public/css/main.css -o ./src/public/css/main.min.css --watch
```

Hope that helps!
