### ISSUE TITLE
[Bug] - Border and Divider not working while switching preflight to false

### ISSUE THREAD

**Issue by phatify** [tailwindlabs/tailwindcss#6979]
**What version of Tailwind CSS are you using?**

3.0.11

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss (8.3.11), React 17.0.0, Vite (2.6.4)

**What version of Node.js are you using?**

v12.22.0

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Describe your issue**

I think this is bug and not the feature. Currently **Border** and **Divider** in TailwindCSS not working while i switching `preflight` in `corePlugins `to false. Please fix this bug.

A specific example:

The code below will works if `preflight` to true and **not works** if `preflight` to false:
`<div class="border border-gray-300 w-[50px] h-[50px]"></div>
`

**Comment by chu121su12** [comment]
I'm sure this is due to the base border stye is in preflight.css

https://github.com/tailwindlabs/tailwindcss/blob/d06c9d6aa940ad5a2b9fea1f8a36872c4eeba256/src/css/preflight.css#L6-L13

**Comment by tinhthatbonglai** [comment]
> **What version of Tailwind CSS are you using?**
> 
> 3.0.11
> 
> **What build tool (or framework if it abstracts the build tool) are you using?**
> 
> postcss (8.3.11), React 17.0.0, Vite (2.6.4)
> 
> **What version of Node.js are you using?**
> 
> v12.22.0
> 
> **What browser are you using?**
> 
> Chrome
> 
> **What operating system are you using?**
> 
> Windows
> 
> **Describe your issue**
> 
> I think this is bug and not the feature. Currently **Border** and **Divider** in TailwindCSS not working while i switching `preflight` in `corePlugins `to false. Please fix this bug.
> 
> A specific example:
> 
> The code below will works if `preflight` to true and **not works** if `preflight` to false: `<div class="border border-gray-300 w-[50px] h-[50px]"></div> `

same issue, we will wait for the next fix update

> **What version of Tailwind CSS are you using?**
> 
> 3.0.11
> 
> **What build tool (or framework if it abstracts the build tool) are you using?**
> 
> postcss (8.3.11), React 17.0.0, Vite (2.6.4)
> 
> **What version of Node.js are you using?**
> 
> v12.22.0
> 
> **What browser are you using?**
> 
> Chrome
> 
> **What operating system are you using?**
> 
> Windows
> 
> **Describe your issue**
> 
> I think this is bug and not the feature. Currently **Border** and **Divider** in TailwindCSS not working while i switching `preflight` in `corePlugins `to false. Please fix this bug.
> 
> A specific example:
> 
> The code below will works if `preflight` to true and **not works** if `preflight` to false: `<div class="border border-gray-300 w-[50px] h-[50px]"></div> `

same issue, how to fix this issue at v3.0.12?

**Comment by tinhthatbonglai** [comment]
same issue, how to fix this issue at v3.0.12?

**Comment by chu121su12** [comment]
Simplest one is to add your own css:

```css
*, ::before, ::after {
  border-width: 0;
  border-style: solid;
  border-color: currentColor /* or gray-DEFAULT / gray-400 */;
}
```

**Comment by reinink** [comment]
Hey!

So this isn't an issue per se, as making the border class work as expected is just one of the jobs of Preflight. You can read more about this in the Tailwind CSS documentation here:

https://tailwindcss.com/docs/preflight#border-styles-are-reset-globally

If you disable Preflight you need to use `border border-solid border-gray-200` to get the same results.

Alternatively, you can add the Preflight border reset to your own CSS, as suggested by @chu121su12 👍
