### ISSUE TITLE
Just-In-Time build css not work in ionic / angular 13 app

### ISSUE THREAD

**Issue by alk841** [tailwindlabs/tailwindcss#6983]
**What version of Tailwind CSS are you using?**

3.0.12

**What build tool (or framework if it abstracts the build tool) are you using?**

"postcss": "^8.4.5","postcss-scss": "^4.0.2",  npm v8..1.2, 

**What version of Node.js are you using?**

v16.13.1

**What browser are you using?**

Chrome

OS

macOS

A Tailwind Play link or public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.

**Describe your issue**

CSS styles are build only if I start app with ionic serve and after first save. Another save not build css and new added styles not work. I have to turn off app, Turn on app and works only firs save.

Can you help me.

Thanks.

**Comment by alk841** [comment]
I'll just add, in verson tailwindcss v2 everything work fine.

**Comment by reinink** [comment]
Hey!

This is a known issue with Angular and Tailwind CSS v3.0. You can find more information about it in #6847, including a workaround in the short term. We also have an open PR on the Angular CLI repo to fix this: https://github.com/angular/angular-cli/pull/22447

Hope that helps! 👍

**Comment by zajcman** [comment]
you must upgraded from Angular 13.0 to 13.2.2 via the Angular CLI command ng update ( this is solution from Angular: https://github.com/angular/angular-cli/pull/22447 )
