### ISSUE TITLE
@apply breaks @media queries

### ISSUE THREAD

**Issue by GuillaumeAmat** [tailwindlabs/tailwindcss#6986]
**What version of Tailwind CSS are you using?**

3.0.12 (latest as of today)

**Reproduction URL**

https://play.tailwindcss.com/Hs3b6gCqaN?file=css

**Describe your issue**

With Tailwind 3.0.12, `@apply` keywords break the media queries declared in the `@layer base` bloc.

For the record, I didn't test any other scenario. And it works as expected with Tailwind 3.0.11.

In the reproduction playground above, you can see that:

- ❌ The text is red, even though it's defined inside a `@media print` bloc
- ❌ The text is also `2rem`, even though it's defined inside a `@media print` bloc AND not declared using `@apply`
- ✅ If you comment/remove the line 16 `@apply`, the `font-size` is not overridden anymore

**Comment by thecrypticace** [comment]
This got fixed as a side effect of merging #6999. We'll aim to cut a release tomorrow morning/afternoon.

**Comment by GuillaumeAmat** [comment]
My pleasure @thecrypticace, and thanks for the fix.
