### ISSUE TITLE
Min-h-[50vh] arbitrary values on min-height not working

### ISSUE THREAD

**Issue by nolafs** [tailwindlabs/tailwindcss#6995]
**What version of Tailwind CSS are you using?**

v3.0.12

**What build tool (or framework if it abstracts the build tool) are you using?**

 webpack 5.28.0

**What version of Node.js are you using?**

 v14.0.0

**What browser are you using?**

 N/A

**What operating system are you using?**

macOS

**Describe your issue**

It seems vh arbitrary values do not work at all on min-height.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We can't help you without a reproduction. Here is a working version: https://play.tailwindcss.com/smJI6TV9cq

**Comment by nolafs** [comment]
Hi,

thanks for getting back to me. That test works perfectly fine and previously I had no problems. Perhaps daisyUI is doing something strange.

![test](https://user-images.githubusercontent.com/8676371/148751811-9435ec2e-2736-4f37-8fe3-efd219e31e8d.png)

https://sleepy-keller-131ccf.netlify.app

I pretty new to tailwind, still learning. h-[50vh] is working perfectly fine. 

Cheers
Olaf

**Comment by KadenZipfel** [comment]
@RobinMalfait I'm getting the same issue on arbitrary values for width and height styles. Can't reproduce with the tailwind play but worked fine on v2 and after migrating to v3 and following the upgrade guide closely it doesn't work

**Comment by LucaRed** [comment]
Old issue, but adding a comment for people arriving here from Google: you shouldn't use PurgeCSS with Tailwind.

The purge feature is now provided directly by Tailwind, using PurgeCSS messes with classes with [arbitrary values](https://tailwindcss.com/docs/adding-custom-styles#using-arbitrary-values).
