### ISSUE TITLE
`content-none` does not render `content: ""` like the docs say it should

### ISSUE THREAD

**Issue by tremby** [tailwindlabs/tailwindcss#7006]
**What version of Tailwind CSS are you using?**

v3.0.11

**What build tool (or framework if it abstracts the build tool) are you using?**

Webpack 5.65.0

**What version of Node.js are you using?**

16.13.1

**What browser are you using?**

N/A

**What operating system are you using?**

N/A

**Reproduction URL**

https://play.tailwindcss.com/1TelpYInIR?file=css

**Describe your issue**

Previously reported as https://github.com/tailwindlabs/tailwindcss/issues/6387 and it hasn't been fixed but the reporter closed it.

The docs say that `content-none` produces `content: ""` but I'm not seeing that, and the browser isn't rendering the pseudoelement.

I'm not sure if this is a code bug (it should render `content: ""` but doesn't) or a documentation bug (it should render `content: none` and the docs should say so).

**Comment by thecrypticace** [comment]
This is a bug in the docs which I've just fixed. Thanks for the catch. You can use `content-[""]` to get `content: ""`.
