### ISSUE TITLE
border color on focus not working

### ISSUE THREAD

**Issue by aestheticsdata** [tailwindlabs/tailwindcss#7018]
**What version of Tailwind CSS are you using?**

v3.0.9 (same problem with 3.0.13)

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.5

**What version of Node.js are you using?**

v16.3.1

**What browser are you using?**

Brave Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (arm64)

**What operating system are you using?**

macOS 11.6

**Describe your issue**

I have a Storybook component with a button and custom classes with variables:

```
let borderBaseColor = "border-blue-custom";
let borderFocusColor = "border-green-custom";

<button className={`
   ${borderBaseColor}
   focus:border-2
   focus:border-dotted
   focus:${borderFocusColor}
`}>
  my button
</button>
```

there is a blue border, but when the button is focused, the green color is not applied. The border is dotted as intended but still blue. When I downgrade tailwindcss to 2.2.19, the color change is working (but not the dotted border). If I hardcode the focus color without a variable, it's working.

**Comment by aggreggator** [comment]
It does not work because the string will be concatenated. `focus:${borderFocusColor}`
Take a look at the documentation:
https://tailwindcss.com/docs/content-configuration#class-detection-in-depth
Section: Don't construct class names dynamically
