### ISSUE TITLE
[Utility class] class doesn't exist. If `[Utility class]` is a custom class, make sure it is defined within a `@layer` directive.

### ISSUE THREAD

**Issue by Rolanddoda** [tailwindlabs/tailwindcss#7055]
I have created a [StackBlitz reproduction of the issue](https://stackblitz.com/edit/vitejs-vite-rdaewu?file=src/components/HelloWorld.vue).

**Describe the bug:**

I had TailwindCSS version `^3.0.5` and wanted to upgrade to `^3.0.13`. After upgrade, I saw a couple of errors in my console.
Specifically, Tailwind is not able to recognize @layer utilities with `@apply` anymore.

**Steps to reproduce:**
1. Open the minimal reproduction
2. See in `HelloWorld.vue` that I have `@apply my-custom-class`
3. Then open `src/css/tailwind.css` and see that `my-custom-class` is defined under `@layer utilities`
4. Run the app and Observe the error

**Comment by adamwathan** [comment]
Hey! See docs: https://tailwindcss.com/docs/functions-and-directives#using-apply-with-per-component-css

**Comment by Rolanddoda** [comment]
Hey Adam!

In the docs it says:

> when you try to @apply card in Card.svelte it fails, because Tailwind has no idea that the card class exists

In `3.0.5` though, Tailwind had the idea that this class exists! So the behavior was purposely changed in later versions.

Also says:

> Honestly though the best solution is to just not do weird stuff like this at all.

I honestly don't understand why what I am doing is weird:

I am creating utility classes for fonts so I don't have to repeat classes for (font-size, font-weight etc) all over again. Plus, those fonts are specified as they are below from the designer in the style guide.

```css
@layer utilities {
  .h1 { @include DMSans($size: 35px, $line-height: 42px, $font-weight: 700, $letter-spacing: -0.02em); }
  .h2 { @include DMSans($size: 30px, $line-height: 38px, $font-weight: 700, $letter-spacing: -0.02em); }
  .h3 { @include DMSans($size: 22px, $line-height: 32px, $font-weight: 700, $letter-spacing: -0.02em); }
  .h4 { @include DMSans($size: 18px, $line-height: 26px, $font-weight: 700, $letter-spacing: -0.02em); }
  .h5 { @include DMSans($size: 14px, $line-height: 20px, $font-weight: 700, $letter-spacing: -0.02em); }
  .h6 { @include DMSans($size: 12px, $line-height: 18px, $font-weight: 700, $letter-spacing: -0.02em); }
 //...
}
```

And I am creating those under `@layer utilities` because:
1. I want those classes to have higher specificity because I am using a CSS Component Library and some font classes might clush
2.  I want to take advantage of Tailwind’s modifier syntax for handling things like hover states, responsive breakpoints, dark mode, and more

The reason why I am using `@apply` instead of just using the HTML markup, is because I don't have access to that.
The element I am targeting is inside the Component Framework:

```css
  :deep(.q-tab__label) {
    @apply h4 t-text-dust;
  }
```

So personally I think, you have to bring back the ability to allow `@layer utilities` to get accessed by `@apply`.

**Comment by nemanjam** [comment]
I also have broken classes from `@layer utilities` in `@apply` after upgrading from `"tailwindcss": "^3.0.8"` to `"tailwindcss": "^3.0.15"`. 

Why is such big breaking change introduced in such minor patch? Or is it a bug?

```
The `link-primary` class does not exist. If `link-primary` is a custom class, make sure it is defined within a `@layer` directive.
```

**Comment by Areskul** [comment]
Same probleme here... let's downgrade :(

**Comment by JamieGarcia123** [comment]
encountering as well today using border-solid. tailwind v 3.0.23

**Comment by JamieGarcia123** [comment]
deleted my comment- it was user error. no issue

**Comment by LobodaAndreyEK** [comment]
Have the same issue when tried to set colors in tailwind config as css variables.
Seems that things like `text-primary-700/30` does not work with css vars

**Comment by leonhma** [comment]
Just in case someone comes across this issue while using tailwind with `@nuxt/ui` and `@nuxtjs/color-mode`: Try moving `@nuxt/ui` above `@nuxtjs/tailwindcss` and `@nuxtjs/color-mode`. This solved the issue for me.

*nuxt.config.ts*
```js
...
modules: [
    '@nuxt/ui',
    '@nuxtjs/tailwindcss',
    '@nuxtjs/color-mode',
    ...
],
...
```

**Comment by mikemrg17** [comment]
@leonhma, did you get this error with the @nuxt/ui?: 

The bg-primary/40 class does not exist. If bg-primary/40 is a custom class, make sure it is defined within a @layer directive.

**Comment by StefanFlaschko** [comment]
> sing the "extend" property, so It overwrote the whole b



> I honestly don't understand why what I am doing is weird:

I also don't understand what is weird about using @apply. What is the alternative? Putting the tailwind class on every element?

**Comment by JeremieV** [comment]
> I also don't understand what is weird about using @apply. What is the alternative? Putting the tailwind class on every element?

I think this sentence in the docs could be rephrased. The alternatives are to either declare your class globally in a layer, or to write a plugin.

I don't think they suggest that there is anything weird about using `@apply`, but the tailwind maintainers expect you to declare your classes globally. It's a limitation of the tool that you can't use `@apply` in component-scoped styles, not a weird intent from the developer.

**Comment by cn-2k** [comment]
> Just in case someone comes across this issue while using tailwind with `@nuxt/ui` and `@nuxtjs/color-mode`: Try moving `@nuxt/ui` above `@nuxtjs/tailwindcss` and `@nuxtjs/color-mode`. This solved the issue for me.
> 
> _nuxt.config.ts_
> 
> ```js
> ...
> modules: [
>     '@nuxt/ui',
>     '@nuxtjs/tailwindcss',
>     '@nuxtjs/color-mode',
>     ...
> ],
> ...
> ```

This worked for me, but... WHY? hahahaha
There's a way to make nuxt/ui load first than the others by default after installing (without need to put him manually)?

**Comment by phamquocbuu** [comment]
> Just in case someone comes across this issue while using tailwind with `@nuxt/ui` and `@nuxtjs/color-mode`: Try moving `@nuxt/ui` above `@nuxtjs/tailwindcss` and `@nuxtjs/color-mode`. This solved the issue for me.
> 
> _nuxt.config.ts_
> 
> ```js
> ...
> modules: [
>     '@nuxt/ui',
>     '@nuxtjs/tailwindcss',
>     '@nuxtjs/color-mode',
>     ...
> ],
> ...
> ```

This worked for me 😍

**Comment by scottonanski** [comment]
So, what's the solution for people are aren't professional developers? The docs are written for people trying to learn.  I'm trying to learn Tailwind, and I'm getting this error trying to follow along;

```
 The `font-secondary` class does not exist. If `font-secondary` is a custom class, make sure it is defined within a `@layer` directive.
 source: '@tailwind base;\r\n' +
    '@tailwind components;\r\n' +
    '@tailwind utilities;\r\n' +
    '\r\n' +
    'body {\r\n' +
    '    @apply font-secondary text-[22px] text-secondary;\r\n' +
    '}\r\n' +
    '\r\n' +
    '/* .font-secondary {\r\n' +
    "    font-family: 'Jost', sans-serif;\r\n" +
    '} */\r\n',
  line: 6,
  column: 5,
  endLine: 6,
  endColumn: 54,
  input: {
    column: 5,
    endColumn: 54,
    endLine: 6,
    line: 6,
    source: '@tailwind base;\r\n' +
      '@tailwind components;\r\n' +
      '@tailwind utilities;\r\n' +
      '\r\n' +
      'body {\r\n' +
      '    @apply font-secondary text-[22px] text-secondary;\r\n' +
      '}\r\n' +
      '\r\n' +
      '/* .font-secondary {\r\n' +
      "    font-family: 'Jost', sans-serif;\r\n" +
      '} */\r\n',
```

**Comment by TonnyMusembi** [comment]
> 
> '@nuxt/ui',
>     '@nuxtjs/tailwindcss',
>     '@nuxtjs/color-mode',
> ```

this worked for me !

**Comment by bigyanse** [comment]
I was using `underscoretw(_tw)` with custom tailwind config and had this error. It was due to bad tailwind config.

You need to move everything that you want to extend inside `extend` property. Placing it outside overrides all the defaults and hence the error. I was using `fontSize` property outside extend so, it replaced default tailwind `text-3xl` causing the error. If you move your config fields inside `extend`, it will solve the error.

Reference: [1091338461](https://github.com/tailwindlabs/tailwindcss/issues/7055#issuecomment-1091338461)

**Comment by adancabanas** [comment]
In my case I already had a webpack config before bundling my files, just installed tailwind postcss and autoprefixer, instead of using postcss inside of mix I configured webpack.config.js ProvidePlugin arguments, like so:

`
const webpack = require('webpack');

module.exports = {
    ...
    plugins: [
        new webpack.ProvidePlugin({
            ...
            tailwindcss: {},
            autoprefixer: {},
        }),
    ],
    ...
};
`

**Comment by zaadevofc** [comment]
so how to solve?

**Comment by zaadevofc** [comment]
> I have created a [StackBlitz reproduction of the issue](https://stackblitz.com/edit/vitejs-vite-rdaewu?file=src/components/HelloWorld.vue).
> 
> **Describe the bug:**
> 
> I had TailwindCSS version `^3.0.5` and wanted to upgrade to `^3.0.13`. After upgrade, I saw a couple of errors in my console. Specifically, Tailwind is not able to recognize @layer utilities with `@apply` anymore.
> 
> **Steps to reproduce:**
> 
>     1. Open the minimal reproduction
> 
>     2. See in `HelloWorld.vue` that I have `@apply my-custom-class`
> 
>     3. Then open `src/css/tailwind.css` and see that `my-custom-class` is defined under `@layer utilities`
> 
>     4. Run the app and Observe the error

i have been solve by removing classes that contain responsive or state prefixes in css. i have no idea why but worked for me

**Comment by DonAyers** [comment]
Leaving this comment in case it helps anyone. I was getting this error with all of the text-wrap classes when using with @apply and css modules. The fix for my setup (webpack build / yarn workspace monorepo) was to update `postcss-importer`.

**Comment by miljkovic5** [comment]
> Just in case someone comes across this issue while using tailwind with `@nuxt/ui` and `@nuxtjs/color-mode`: Try moving `@nuxt/ui` above `@nuxtjs/tailwindcss` and `@nuxtjs/color-mode`. This solved the issue for me.
> 
> _nuxt.config.ts_
> 
> ```js
> ...
> modules: [
>     '@nuxt/ui',
>     '@nuxtjs/tailwindcss',
>     '@nuxtjs/color-mode',
>     ...
> ],
> ...
> ```

It doesn't work for me. I'm using https://frontends.shopware.com/ and I removed UnoCSS and installed NextUI and it doesn't work..

**Comment by eric-gitta-moore** [comment]
I just wanted to use `@apply` alone in the style section, but it didn't work.
```vue
<template>
  <h1 class="my-custom-class">Heading</h1> // work
</template>

<style>
h1 {
  @apply my-custom-class; // bad
}
</style>
```
