### ISSUE TITLE
Build is différent Tailwindcss v2 to Tailwindcss v3

### ISSUE THREAD

**Issue by gabi77** [tailwindlabs/tailwindcss#7061]
**What version of Tailwind CSS are you using?**

v2.2.19 and upgrade to version v3.0.13

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss-cli 9.1.0, yarn 1.22.17

**What version of Node.js are you using?**

v14.18.0

**What browser are you using?**

Firefox

**What operating system are you using?**

kubuntu

*My code* 

**Input**

```
@layer base {

    .product-info-main {
        @apply bg-blue-highlight p-4 pb-0;
        h1.page-title {
            @apply mt-0 pt-0 text-2xl uppercase font-bold tracking-normal;
        }
    }
}
```

**Output Tailwind v2.2.19**

```
.product-info-main {
  background-color: var(--blue-high-pale);
  padding: 1rem;
  padding-bottom: 0px;
}

.product-info-main h1.page-title {
  margin-top: 0px;
  padding-top: 0px;
  font-size: 1.5rem;
  line-height: 2rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0em;
}
```

**Output Tailwind v3.0.13**

```
.product-info-main h1.page-title {
    margin-top: 0px;
    padding-top: 0px;
    font-size: 1.5rem;
    line-height: 2rem;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0em;

}
```

When building the css file the parent values are not present on tailwindcss v3.
It works on tailwindcss v2 see example for the same code

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Unfortunately we can't help you without a **minimal** reproduction repo.

Since you are using nesting, make sure that you setup the nesting plugin correctly: https://tailwindcss.com/docs/using-with-preprocessors#nesting
