### ISSUE TITLE
For some reason, ring-inset does not work on the fieldset element in Firefox

### ISSUE THREAD

**Issue by devcustrom** [tailwindlabs/tailwindcss#7067]
**What version of Tailwind CSS are you using?**

v3

**What browser are you using?**

Firefox

**What operating system are you using?**

Windows

**Reproduction URL**

[https://play.tailwindcss.com/uXo1LukhRr](https://play.tailwindcss.com/uXo1LukhRr)

**Describe your issue**

For some reason, ring-inset does not work on the fieldset element in Firefox

**Comment by adamwathan** [comment]
Hey! This appears to be a Firefox bug, it just doesn't support inset box shadows on `fieldset` elements. Here's a demo that just uses plain CSS:

https://play.tailwindcss.com/aWFBA6nbQU

I would recommend wrapping the fieldset with a `div` and adding the styles there. Nothing we can do about this in Tailwind I'm afraid.

**Comment by devcustrom** [comment]
Opened a bug on their website https://bugzilla.mozilla.org/show_bug.cgi?id=1750276
