### ISSUE TITLE
JIT is not working with tailwind 3.08 and postcss 8.4.5

### ISSUE THREAD

**Issue by devLeopar** [tailwindlabs/tailwindcss#7090]
**What version of Tailwind CSS are you using?**

"tailwindcss": "^3.0.8"
"postcss": "^8.4.5"

**What build tool (or framework if it abstracts the build tool) are you using?**

"next": "10.1.3"

**What version of Node.js are you using?**

v16.13.1

**What browser are you using?**

Chrome

**What operating system are you using?**

Linux Mint

Hey folks,
There weren't any issue while I was starting my nextjs app with the command below in terms of JIT mode;

`"dev": "TAILWIND_MODE=watch next dev"`

After updating postcss to the latest with the tailwind together. Postcss is starting displaying warning message like below:

```
(node:10073) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at .../node_modules/next/node_modules/postcss/package.json.
Update this package.json to use a subpath pattern like "./*".
```

Even though the JIT message needs to be appeared after starting the app, there is nothing related to watch css hence any of update in classes on development is not reflected locally.

How can it be solved?

Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The warning you are receiving looks like a Next.js issue and not a Tailwind issue.
That said, without a minimal reproduction repo we can't help you.

**Comment by devLeopar** [comment]
Hey Robin;

While postcss was giving that warning, I was able to watch changes with tailwind on localhost. How did you decide that this is only nextjs issue?

**Comment by RobinMalfait** [comment]
Because the warning points to files in the `next` package folder of node_modules:

```
(node:10073) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at .../node_modules/next/node_modules/postcss/package.json.
                                                                                                                                                             ---- Here
Update this package.json to use a subpath pattern like "./*".
```

**Comment by devLeopar** [comment]
Do you think that warning prevents tailwind to watch css changes on files? 

_While postcss was giving that warning, I was able to watch changes with tailwind on localhost_

**Comment by adamwathan** [comment]
@devLeopar Please open a new issue but include a reproduction this time if this is still an issue for you and you believe it's a bug in Tailwind. The reproduction field is required, we simply can't provide help without one.
