### ISSUE TITLE
Ring shadow artifacts when using ring-offset and rounded-full

### ISSUE THREAD

**Issue by lupinitylabs** [tailwindlabs/tailwindcss#7107]
**What version of Tailwind CSS are you using?**

v3.0.15

**What build tool (or framework if it abstracts the build tool) are you using?**

webpack 5.65.0

**What version of Node.js are you using?**

v17.3.1

**What browser are you using?**

Firefox v96.0.1, Chrome v97.0.4692.71

**What operating system are you using?**

Windows

**Reproduction URL**

[Tailwind Playground to reproduce issue](https://play.tailwindcss.com/F2WvU56KH3)

**Describe your issue**

As it seems, Tailwind's ring-offset actually increases the width of the border and then uses `--tw-ring-offset-shadow` with the `--tw-ring-offset-color` to overlay the inner radius of the ring to fake an offset. In both Firefox and Chrome, this leaves an artifact that looks like anti-aliasing remains, and the overlay seems to be 1px too small to cover that up.

So far, we could reproduce that on every system we checked it on, so it doesn't seem to be directly related to system, or graphics card driver settings.

![screenshot](https://user-images.githubusercontent.com/17774818/149866998-b69e2f6d-c611-4499-ae86-3ab48ca59c2e.png)

**Comment by adamwathan** [comment]
Yeah unfortunately this is just what happens with CSS when trying to implement this trick on an element with a transparent background. The fix is to give the element an explicit background color:

https://play.tailwindcss.com/BRuhf5BWee

Nothing else we can do about this that isn’t super hacky with other bad consequences I’m afraid. Hopefully Safari follows suit with Chrome and Firefox soon and starts supporting border radius on custom outlines and we can move away from this trick completely.

**Comment by lupinitylabs** [comment]
Nice, thanks for the explanation. The background color might work for me!

**Comment by lupinitylabs** [comment]
Sorry to bother you again @adamwathan ... the background fix does not seem to change anything for me - here's a screenshot from your playground:

![grafik](https://user-images.githubusercontent.com/17774818/149992036-9fc8ac9f-c474-4d7a-bf91-d5ad26b890b5.png)

The anti-aliasing seems to be outside of the element, not inside 🤔

**Comment by TastyPi** [comment]
Just wanted to add here before someone gets lost trying to figure this out that adding a background does work (at least, it does for this case) https://play.tailwindcss.com/BRuhf5BWee

**Comment by lupinitylabs** [comment]
It does work for Chrome, but it still does not for Firefox. Seems to be related to the way the anti-aliasing is done by the engine 🤷 
![grafik](https://user-images.githubusercontent.com/17774818/221967516-56528c8f-e9db-4040-bd4b-086540065d99.png)

**Comment by TastyPi** [comment]
I have two alternatives, one using a wrapper `div` and another using the `::after` pseudo element https://play.tailwindcss.com/DsSesreDe6.

I quite like the `::after` solution as it avoids wrapping the `div` with another element that you need to take into account.

I'm not sure if there's some accessibility issue that could cause problems, but I think this is also a nicer way to implement an offset ring as it doesn't use the workaround of drawing a "background" shadow on top of the real ring, so you get the actual background colour for free.
