### ISSUE TITLE
group-focus-within + dark mode does not have consistent ordering between darkMode settings

### ISSUE THREAD

**Issue by Cephyric-gh** [tailwindlabs/tailwindcss#7111]
**What version of Tailwind CSS are you using?**

3.0.14

**What build tool (or framework if it abstracts the build tool) are you using?**

Whatever playground uses as am able to repro there

**What version of Node.js are you using?**

Whatever playground uses as am able to repro there

**What browser are you using?**

Chrome

**What operating system are you using?**

MacOS

**Reproduction URL**

https://play.tailwindcss.com/JIvIMyNrCc

**Describe your issue**

When darkMode is enabled in "class" mode Tailwind seems to be really picky about the ordering of group-focus-within and dark variants when used in combination. `group-focus-within:dark:text-red-500` will not work in class mode whilst `dark:group-focus-within:text-red-500` does. The ordering of these 2 variants are not an issue when darkMode is set up in the default media query mode

**Comment by adamwathan** [comment]
Hey! The way ordering modifiers works is explained in the documentation and actually uses this very example, worth a read:

https://tailwindcss.com/docs/hover-focus-and-other-states#ordering-stacked-modifiers

**Comment by Cephyric-gh** [comment]
I honestly don't know why I didn't find that in the docs, thanks for the link! This doesn't quite explain why it works when you have `darkMode: 'media'` in the config, is this because media queries are always elevated to the top of the stack order?
