### ISSUE TITLE
Missing `overflow: overlay`

### ISSUE THREAD

**Issue by windyclory** [tailwindlabs/tailwindcss#7122]
```
.overflow-overlay {
  overflow: overlay;
}
```
Check out [the playground](https://play.tailwindcss.com/cNJrTsjM5s?file=css) to see why it's useful. Remove the `overflow: overlay` style in the playground and you will see the problem and the use case.
Thanks

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

This feature only works for WebKit and Blink-based browsers which is fine. My only concern is that the `overflow: overlay` is marked as deprecated https://developer.mozilla.org/en-US/docs/Web/CSS/overflow so you probably don't want to depend on that property.

I would suggest to add this to your css:
```css
@layer utilities {
  .overflow-overlay {
    overflow: overlay;
  }
}
```
if you want to make use of this feature.

**Comment by windyclory** [comment]
> the overflow: overlay is marked as deprecated

🤦‍♀️unbelievable
