### ISSUE TITLE
Esmodule breaks, cljs config extension is recommended but not found

### ISSUE THREAD

**Issue by janat08** [tailwindlabs/tailwindcss#7153]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/7150

<div type='discussions-op-text'>

<sup>Originally posted by **janat08** January 21, 2022</sup>
I have package.json that says I’m working on esmodule. I got warning that config extension needs to change after reading docs I believe i must also specify new config location when running jit compilation because none of content is detected. Am I right?</div>

**Comment by molenick** [comment]
I think I'm having the same issue:
```sh
npx tailwindcss build -i demo/tailwind-base.css -o demo/style.css

warn - The `content` option in your Tailwind CSS configuration is missing or empty.
warn - Configure your content sources or your generated CSS will be missing styles.
warn - https://tailwindcss.com/docs/content-configuration
```

I do have a content tag in tailwind.config.cjs, but when I look at `demo/style.css` it's missing most of what I expect.

**Comment by molenick** [comment]
In my project, I was able to get it to build without a config file with this:
```sh
npx tailwindcss build -i demo/tailwind-base.css -o demo/style.css --content "./demo/index.html"
```

It seemed like build wasn't picking up my config with a cjs extension, but specifying the content using --content seems to build as I expect.

**Comment by Xeevis** [comment]
CLI defaults to `./tailwind.config.js` https://github.com/tailwindlabs/tailwindcss/blob/ce987357de6abcd76f2312ec8ab9de686098c1a0/src/cli.js#L388-L392

There [used to be support](https://github.com/tailwindlabs/tailwindcss/pull/3181/files) for detecting cjs, but for some reason that was removed.

Just pass in `--config ./tailwind.config.cjs` as command argument.

**Comment by janat08** [comment]
Then this should be included in terminal prompt to rename file
