### ISSUE TITLE
Custom configuration file name doesn't work

### ISSUE THREAD

**Issue by pasqualevitiello** [tailwindlabs/tailwindcss#7166]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/7158

<sup>Originally posted by **pasqualevitiello** January 21, 2022</sup>

----

**What version of Tailwind CSS are you using?**

v3.0.15

**What build tool (or framework if it abstracts the build tool) are you using?**

CRA v5.0.0

**What version of Node.js are you using?**

v15.14.0

**What browser are you using?**

Chrome

**What operating system are you using?**

MacOS

**Describe your issue**

Trying to use a custom file name for Tailwind config file with PostCSS, like explained in the docs: https://tailwindcss.com/docs/configuration#using-a-different-file-name

For some reason it doesn't work, am I missing anything?

**Steps to reproduce the issue:**

- [Install a CRA app](https://tailwindcss.com/docs/guides/create-react-app)

- Rename `tailwind.config.js` to `tailwindcss-config.js`

- Configure template paths:

```
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

- Edit postcss.config.js:

```
module.exports = {
  plugins: {
    tailwindcss: { config: './tailwindcss-config.js' },
    autoprefixer: {},
  },
}
```

- `npm start`

----

**Result is:**

<img width="1457" alt="Screenshot 2022-01-21 at 16 36 02" src="https://user-images.githubusercontent.com/2683512/150555330-dfc80993-263b-45a4-9838-748d7a9810c8.png">

**Comment by adamwathan** [comment]
Closing in favor of discussion.
