### ISSUE TITLE
The correct command is `npx tailwindcss init`.

### ISSUE THREAD

**Issue by droidlinies** [tailwindlabs/tailwindcss#7175]
The correct command is `npx tailwindcss init`.
still not working

_Originally posted by @adamwathan in https://github.com/tailwindlabs/tailwindcss/discussions/7160#discussioncomment-2019205_

**Comment by adamwathan** [comment]
Closing in favor of discussion, this is user error as mentioned in the comments there, you don't have `npm` installed.
