### ISSUE TITLE
Specificity

### ISSUE THREAD

**Issue by AverTry** [tailwindlabs/tailwindcss#7176]
Using the latest Cli install of tailwind 3.0.15 and Forms plugin installed 
and following this tutorial https://youtu.be/pONeWAzDsQg?t=70 from Tailwind

With `space-y-6` on the `<form>` tag to separate the components which also includes the label's
To bring the labels closer to the inputs, a div with `mt-1` is used. 
This `mt-1` only works with `!mt-1` 
**so the specificity of `space-y-6` is too high**?

**Comment by adamwathan** [comment]
Hey! Yep you're not meant to try and use margin utilities to override the margins on individual elements within a container that has a `space-*` utility because they will conflict with each other like you're discovering.

Do something like this instead:

```html
<form class="space-y-6">
  <div>
    <label>...</label>
    <input class="mt-1">
  </div>
  <div>
    <label>...</label>
    <input class="mt-1">
  </div>
</div>
```

**Comment by AverTry** [comment]
It didn't work Adam.
