### ISSUE TITLE
divide not exactly between flex box sub items in RTL language

### ISSUE THREAD

**Issue by stifler97** [tailwindlabs/tailwindcss#7179]
Tailwind v3.0.15
Node.js v16.13.2
Browser FireFox
Operating system Ubuntu

[Reproduction URL](https://codepen.io/alisamie97/pen/ZEazpNG)

[Tailwind Play link](https://play.tailwindcss.com/WQp0ltZw2a)

Issue:
I used `divide-x` for `li` elements in a flex `ul` element. It does not get well centered for RTL languages like Farsi.
I also need to add `divide-x-reverse` because other wise the `border-left` is used to divide and its no good in RTL.

**Comment by stifler97** [comment]
OK i solved it
Just changed the `ul` from `flex` to a `grid` for md screens.
And added a `text-center and grid-col-6` to `ul`
[Tailwind Play link](https://play.tailwindcss.com/0Z4Dud0QK3)

**Comment by abdelhak002** [comment]
> Tailwind v3.0.15 Node.js v16.13.2 Browser FireFox Operating system Ubuntu
> 
> [Reproduction URL](https://codepen.io/alisamie97/pen/ZEazpNG)
> 
> [Tailwind Play link](https://play.tailwindcss.com/WQp0ltZw2a)
> 
> Issue: I used `divide-x` for `li` elements in a flex `ul` element. It does not get well centered for RTL languages like Farsi. I also need to add `divide-x-reverse` because other wise the `border-left` is used to divide and its no good in RTL.

@stifler97 
Why don't you add `px-4` to `li` elements ??

**Comment by stifler97** [comment]
> Why don't you add `px-4` to `li` elements ??

I do not know if this works or not, but that was for my first try in using tailwind and I just made it work in this way. If your idea works please add a demo link so others can make use of that. Thanks
