### ISSUE TITLE
Something wrong after build css file

### ISSUE THREAD

**Issue by kotsh23** [tailwindlabs/tailwindcss#7182]
**What version of Tailwind CSS are you using?**

v3.0.15

**What build tool (or framework if it abstracts the build tool) are you using?**

plain html file , tailwind cli installation 

**What version of Node.js are you using?**

v16.13.0

**What browser are you using?**

Chrome

**What operating system are you using?**

 Windows

**Describe your issue**

i try to install tailwindcss and run this command

`npx tailwindcss -i ./cssFile.css -o ./src/css/style.css --watch`

the output file have issue at line 713

```
.w-\[this-is\\\\\]w-\\\\\[weird-but-valid\] {
  width: this-is\\]w-\\[weird-but-valid;
}
```

When i change it to 

```
.w-\[this-is\\\\\]w-\\\\\[weird-but-valid\] {
  width: this-is\\w-\\[weird-but-valid];
}
```
working fine but when it rebuild back again

this issue make any class after this line wont work
sorry for my bad english ;)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The problem is your `content ` configuration is matching `node_modules` — make sure you use a more specific configuration:

https://tailwindcss.com/docs/content-configuration#pattern-recommendations

**Comment by kotsh23** [comment]
Thank you! 
```
module.exports = {
  content: ["./src/**/*.{html,js}"],
  theme: {
    extend: {},
  },
  plugins: [],
};
```
i created src folder and put my index.js and index.html inside
