### ISSUE TITLE
CLI --content option shows warning

### ISSUE THREAD

**Issue by EatonZ** [tailwindlabs/tailwindcss#7210]
**What version of Tailwind CSS are you using?**

v3.0.16

**What version of Node.js are you using?**

v17.4.0

**What operating system are you using?**

Windows 11

**Reproduction**

[Sample Download Link](https://github.com/tailwindlabs/tailwindcss/files/7939046/TW.Repro.zip)

1. Use npm to run css-build-dev in package.json, preferably on Windows.
2. Observe the warning.

**Describe your issue**

Tailwind v3.0 deprecated the CLI's `--purge` option and replaced it with `--content`. That's fine, but it doesn't work. I get the following:
```
warn - The `content` option in your Tailwind CSS configuration is missing or empty.
warn - Configure your content sources or your generated CSS will be missing styles.
warn - https://tailwindcss.com/docs/content-configuration
```
The issue can indeed be solved by adding `content` to `tailwind.config.js`, but since the option still exists in the CLI, it should also be possible there. Important to note is that `--purge` using the CLI worked fine in v2.x. There is clearly a bug with the new replacement `--content` option.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #7720, and should be available already!
