### ISSUE TITLE
! important not working as expected with the matchUtilities

### ISSUE THREAD

**Issue by mohamedcherifmo** [tailwindlabs/tailwindcss#7226]
**What version of Tailwind CSS are you using?**
Tailwind v3.0.14

**What build tool (or framework if it abstracts the build tool) are you using?**
postcss-cli 8.3.1

**What browser are you using?**
Chrome,

**What operating system are you using?**
Windows

**Reproduction URL**.
https://play.tailwindcss.com/zEL8hw6BSy

**Describe your issue**

Creating a match utilities that has subclasses isn't working correctly with !important.
I created the following matchUtilities to enable editing the title font-size from the parent (for headless CMS scenario)
`'card-title-text': (value) => ({'.card-title': {'font-size': value,}}),`

Doing so worked as expected for normal classes and generated the following class:
`.card-title-text-4xl .card-title {
  font-size: 2.25rem/* 36px */;
  font-size: [object Object];
}`
but for !card-title-text-4xl it applied the ! to all subclasses as well generating the following css

```
.\!card-title-text-4xl .\!card-title {
  font-size: 2.25rem/* 36px */ !important;
  font-size: [object Object] !important;
}
```
The \! prefix before the card-title i believe shouldn't exist

**Comment by vitorrd** [comment]
Hey @mohamedcherifmo. The ! prefix is intended to show this is an important rule. You can read more [here](https://tailwindcss.com/docs/configuration#important-modifier).

**Comment by adamwathan** [comment]
Hey thanks! Fixed this in https://github.com/tailwindlabs/tailwindcss/pull/7664, can use it now by installing `tailwindcss@insiders` if needed.

**Comment by mohamedcherifmo** [comment]
Thanks :)
