### ISSUE TITLE
Bug: important setting gets not applied to .container

### ISSUE THREAD

**Issue by jonnitto** [tailwindlabs/tailwindcss#7283]
* Tailwind CSS: 3.0.18
* NodeJS: 16.13.0
* OS: MacOS 12.2
* Build Tool: tailwindcss

**Reproduction URL**

With `important` setting with string: https://play.tailwindcss.com/HUNzL4gXbB?file=config
With `important` setting with true: https://play.tailwindcss.com/6eDkBSrLLh?file=config

**Issue**

If you set a value on the property `important` (string or true) in the tailwindcss.config.js, this setting gets not applied to the `.container` class

**Comment by adamwathan** [comment]
Hey! This is by design and not a bug, the important option only affects classes in the `utilities` layer, not the `components` layer.

**Comment by jonnitto** [comment]
Thank you for your answer. Which classes will be added with `@tailwind components`? Is this just this `.container` class?
