### ISSUE TITLE
dont change webkit button bg color 

### ISSUE THREAD

**Issue by productdevbook** [tailwindlabs/tailwindcss#7306]
```
  <a class="bg-red-500 m-4 p-2" type="button" disabled="false" data-v-6d4d3e56=""
    >Register for beta access</span
    ></a

>
``` 

  
![image](https://user-images.githubusercontent.com/38668796/152161246-54ea572c-e44c-427f-b6fd-8695919c4945.png)

please test webkit browser safari or ubuntu web

https://play.tailwindcss.com/xDrLtv00TI

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is not a Tailwind issue. You are telling the `<a>` tag that it should render as a button using `type=button`. This is something you probably never want to do.

A few solutions:
1. Remove the `type=button`
2. Change `<a>` to `<button>`
3. If you _really_ want to keep the `<a type="button">` which is not recommended, but if you really want to. Then add `appearance-none` as a class.
