### ISSUE TITLE
transition-all does not affect animations when combined with first-letter selector

### ISSUE THREAD

**Issue by moishinetzer** [tailwindlabs/tailwindcss#7315]
**What version of Tailwind CSS are you using?**

v3.0.14

**What build tool (or framework if it abstracts the build tool) are you using?**

Regular HTML CSS as per Tailwind Play

**What browser are you using?**

Chrome + Firefox

**What operating system are you using?**

Windows

**Reproduction URL**

https://play.tailwindcss.com/y2EPCqYC8d

**Describe your issue**

transition-all does not affect animations when combined with the first-letter selector.

Note as per the reproduction link above, how all transitions apart from the letter S which instantly changes as opposed to the transition

**Comment by adamwathan** [comment]
Hey! This is just a CSS limitation, browsers don't support this. Here's a quick relevant SO question I found:

https://stackoverflow.com/questions/12982213/css-transition-of-first-letter-on-hover
