### ISSUE TITLE
Using custom colors are not being generated if used  as template literals inside vue3 component script

### ISSUE THREAD

**Issue by mentorkadriu** [tailwindlabs/tailwindcss#7326]
**What version of Tailwind CSS are you using?**

3.0.18

**What build tool (or framework if it abstracts the build tool) are you using?**

"vite": "^2.7.2", "vue": "^3.2.25"

**What version of Node.js are you using?**

v14.16.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS,

**Reproduction URL**

https://stackblitz.com/edit/vitejs-vite-hasnvk?file=src%2FApp.vue&terminal=dev

**Describe your issue**

When [extending tailwind colors](https://tailwindcss.com/docs/customizing-colors#color-object-syntax), they are generated and work fine if used inside vue `<template>` as `<h2 class="text-tahiti-500">Lorem Ipsum</h2>`. The problem happens when I need to use template literals inside `<script>` like: `text-${colorName}-600` and then use this  variable inside `<template>` as `<h2 :class="[textColor, 'text-2xl', 'font-bold']">Lorem Ipsum</h2>`. Somehow `text-tahiti-500` works, because it finds it inside html comment. In this triage bug, my opinion is that tailwind process should look for purging styles after vue complies components (I can be totally wrong on this).

**Comment by adamwathan** [comment]
Hey! See docs:

https://tailwindcss.com/docs/content-configuration#dynamic-class-names
