### ISSUE TITLE
following next-js guide results in: Parsing error: Cannot find module 'next/babel':

### ISSUE THREAD

**Issue by jobe451** [tailwindlabs/tailwindcss#7335]
**What version of Tailwind CSS are you using?**

3.0.18

**What build tool (or framework if it abstracts the build tool) are you using?**

don't know, just running the base nextjs setup guide from
https://tailwindcss.com/docs/guides/nextjs

**What version of Node.js are you using?**

For example: v14.19.0

**What browser are you using?**

Chrome latest

**What operating system are you using?**

Ubuntu

**Describe your issue**

I follow the guideline on https://tailwindcss.com/docs/guides/nextjs

I run:
```
npx create-next-app frontend
cd frontend
npm install -D tailwindcss postcss autoprefixer
npx tailwindcss init -p
```
I change tailwind.config.js to
```Javascript
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
```
Error: Parsing error: Cannot find module 'next/babel':
![image](https://user-images.githubusercontent.com/910027/152639425-bef4cd32-39f3-4679-86eb-c43b7a19ae40.png)

I tried to follow these instructions, they did not help:
https://stackoverflow.com/questions/68163385/parsing-error-cannot-find-module-next-babel

Looks to me as if something is not getting installed

**Comment by jobe451** [comment]
This solved it for me:
https://stackoverflow.com/questions/60178254/vscode-eslint-configuration-for-a-two-projects-workspace/61619698#61619698

Apparently I had to modify vscode workspace settings for the eslint plugin

**Comment by adamwathan** [comment]
Glad you figured it out!
