### ISSUE TITLE
Colored Shadows don't work with modifiers like `hover:`

### ISSUE THREAD

**Issue by akshatmittal** [tailwindlabs/tailwindcss#7344]
**What version of Tailwind CSS are you using?**
v3.0.18

**What build tool (or framework if it abstracts the build tool) are you using?**

Next.js v12.0.9

**What version of Node.js are you using?**

Node v16.13.2

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS, Windows

**Reproduction URL**

https://play.tailwindcss.com/kv6kfIvTsz

**Describe your issue**

Shadow size modifiers do not work with colored shadows, such as `shadow-md hover:shadow-xl shadow-blue-500`. The specificity of the hover rule overrides `--tw-shadow` variable. See line 1 in the example. Temporary solution is to use the important `!` rule with the color.

**Comment by adamwathan** [comment]
Hey! This is by design, `shadow-xl` resets the color back to the default color, so you have to re-specify the color as well:

```
shadow-md shadow-blue-500 hover:shadow-xl hover:shadow-blue-500
```

If it didn't work this way there would be no way to reset the shadow color back to the default. Somewhat annoying I agree but felt like the right decision.
