### ISSUE TITLE
"text-inherit" class not recognized

### ISSUE THREAD

**Issue by 0kMike** [tailwindlabs/tailwindcss#7357]
### What version of Tailwind CSS are you using?

```3.0.19```

### What build tool (or framework if it abstracts the build tool) are you using?

```Next.js 12.0.10``` (issue also occurs with `Angular 13.1.0` and latest Remix)
```postcss 8.4.6```
```autoprefixer 10.4.2```

### What version of Node.js are you using?

```v16.13.2```

### What browser are you using?

- Ungoogled ```Chromium 97.0.4692.71```
- Issue also occurs on ```Chrome 98.0.4758.81``` and ```Firefox 96.0.3```

### What operating system are you using?

```Window 10 64-bit 19043.1466```

### Reproduction URL

[Link to minimalistic repo](https://github.com/0kMike/graph)

### Describe your issue

The Tailwind CSS class `text-inherit` described [in the docs here](https://tailwindcss.com/docs/text-color) is not recognized and the compile process fails:

```
wait  - compiling...
error - ./styles/globals.css:14:3
Syntax error: C:\Users\Michael Naumann\OneDrive\projects\graph\styles\globals.css The `text-inherit` class does not exist. If `text-inherit` is a custom class, make sure it is defined within a `@layer` directive.

  12 | 
  13 | a {
> 14 |   @apply
     |   ^
  15 |   text-inherit
  16 | }
```

Please note that the documentation mentions version `3.0.18` but an automatic install of Tailwind CSS provided me with version `3.0.19`. I encounter the same issue with Angular and Remix.

Please let me know, if any additional information would be helpful. Thanks in regards!

**Comment by thecrypticace** [comment]
I'm not seeing this in 3.0.18 or 3.0.19. It appears your reproduction is likely a private repo so I'm unable to access it. Could you prep a reproduction that is in a public repo?

**Comment by 0kMike** [comment]
My apologies, the repo is set to public now

**Comment by thecrypticace** [comment]
It's happening because you've overridden the color palette (see: https://github.com/0kMike/graph/blob/8ca402aefda80f5bb3ffc4481c41dccf3a487d10/tailwind.config.js#L11). The default palette includes `inherit` here: https://github.com/tailwindlabs/tailwindcss/blob/2250e1bacd4a35f8fcff6925a72df7752deafd55/stubs/defaultConfig.stub.js#L13-L15

You can fix this by adding `inherit: 'inherit'` to your colors object.

**Comment by stephent** [comment]
FWIW - without `inherit: 'inherit'` in the colors object, I was seeing various unexpected styles for basic text and anchors. Adding it fixed those issues as well as the missing `text-inherit`
