### ISSUE TITLE
duration-X property not recognized on @layer scope

### ISSUE THREAD

**Issue by DavidIsrawi** [tailwindlabs/tailwindcss#7360]
**What version of Tailwind CSS are you using?**
v3.0.7

**What build tool (or framework if it abstracts the build tool) are you using?**
autoprefixer: 10.4.0,
postcss: 8.4.5,
tailwindcss: 3.0.7

**What version of Node.js are you using?**
v14.15.4

**What browser are you using?**
Edge Chromium

**What operating system are you using?**
MacOS

**Repro link**
https://play.tailwindcss.com/vYOdy7iCZC

**Describe your issue**
I am trying to create a custom style for hyperlinks, part of the custom style is a `duration-400` property. This property is not being recognized by the compiler.

When I add this property to a custom class under a @layer, I get the following error

> The `duration-400` class does not exist. If `duration-400` is a custom class, make sure it is defined within a `@layer` directive.

**Comment by miraj09** [comment]
You might have missed this line
> Use @apply to inline any **existing** utility classes into your own custom CSS.
`duration-400` does not exist in tailwind's default utilities. Extend this class under `transitionDuration` in tailwind config file to make this class work. You may also face same issue with `hover:border-accent` class
https://tailwindcss.com/docs/transition-duration#changing-transition-duration
https://tailwindcss.com/docs/functions-and-directives#apply

**Comment by thecrypticace** [comment]
Hey, appreciate the report. As @miraj09 said above, `duration-400` is not a utility in Tailwind's default config.

You can add it by customizing your theme:
```js
module.exports = {
  theme: {
    extend: {
      transitionDuration: {
        '400': '400ms',
      }
    }
  }
}
```

Alternatively, you may use arbitrary values instead of adding an entry to your theme: `duration-[400ms]`

**Comment by DavidIsrawi** [comment]
Perfect – I definitely missed that info.

Thank you both!
