### ISSUE TITLE
After upgrade from v2 till v3... Dark Theme not working

### ISSUE THREAD

**Issue by Bobetti** [tailwindlabs/tailwindcss#7383]
Version of Tailwind CSS: v3.0.19
Build tool: postcss@8.4.6
Node.js: 14.17.3
Browser: Chrome
Operating system: Windows

After upgrading from Tailwindcss v2. till v3 using this guide: https://tailwindcss.com/docs/upgrade-guide#remove-dark-mode-configuration  Dark theme is not working anymore. 

Tried to replicate in TailwinPlay, but not working:
https://play.tailwindcss.com/2gIMCfKFVA?size=540x720

**tailwind.config.js contains (part of the content):**

```
module.exports = {
    important: false,
    darkMode: 'class',
    content: [
        './**/*.html',
        './**/*.razor',
        './**/*.cs'
    ],
    safelist: [
        "dark",
        "minWidth",
        '3xl'
    ],
  theme: {
     extend: {
          colors: {
             'my-gray': {
                    '1': '#EDEDED',
                    '2': '#3F424D',
                    '3': '#383A44',
                    '4': '#30323E',
                    '5': '#25252B',
                    '6': '#A1A1A1',
                },      
          }
     }
  }
}
```

**tailwind.css contains (part of the content):**

```
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer components {
  .dark-bg {
     @apply dark:bg-my-gray-2;
  }
  .bg-white-dark {
     @apply bg-white dark-bg;
   }
}
```

**My html code was** 
 `<html lang="en" class="dark"> <div class="bg-white-dark"> ...   </div> </html> `

**In version 2, generated tailwind.min.css content was:**

```
.dark .bg-white-dark {
  --tw-bg-opacity: 1;
  background-color: rgba(63, 66, 77, var(--tw-bg-opacity));
}

@media (prefers-color-scheme: dark) {
  .bg-white-dark {
    --tw-bg-opacity: 1;
    background-color: rgba(63, 66, 77, var(--tw-bg-opacity));
  }
}

.bg-white-dark {
  --tw-bg-opacity: 1;
  background-color: rgba(255, 255, 255, var(--tw-bg-opacity));
}
```

**In version 3, generated tailwind.min.css content is**

```
@media (prefers-color-scheme: dark) {
  .bg-white-dark {
    --tw-bg-opacity: 1;
    background-color: rgb(63 66 77 / var(--tw-bg-opacity));
  }
}

.bg-white-dark {
  --tw-bg-opacity: 1;
  background-color: rgb(255 255 255 / var(--tw-bg-opacity));
}
```

Because the block  ` .dark .bg-white-dark  `  does not exists anymore - dark theme not working... 

Any suggestions what to do?

Thank you

**Comment by motahharm** [comment]
hey @Bobetti 
Are you using `dark:<CLASS-NAME>`??
can you send screen shot?with code??

**Comment by Bobetti** [comment]
Don't follow you. Which screenshot do you need? Everything is in description - all code + TailwindPlay contains full code...

**Comment by adamwathan** [comment]
@Bobetti the problem is you have a custom dark variant defined that is overriding the default one:

```
    screens: {
      'dark': { 'raw': '(prefers-color-scheme: dark)' },
      // ...
    },
```

Delete that line and it works:

https://play.tailwindcss.com/LtFBM6SmCJ?size=540x720

**Comment by Bobetti** [comment]
@adamwathan Thank you so much. I think you should add this to the upgrade specification. This line was needed for v2 to work properly, found this in several tutorials for v2 - but who remembers this :)
