### ISSUE TITLE
Background image arbitrary values dynamic update doesn't work

### ISSUE THREAD

**Issue by sasafister** [tailwindlabs/tailwindcss#7396]
**What version of Tailwind CSS are you using?**

v3.0.16

**What build tool (or framework if it abstracts the build tool) are you using?**

Angular 13

**What version of Node.js are you using?**

v16.3.1

**What browser are you using?**

Chrome

**What operating system are you using?**

macOs

**Describe your issue**

This works 
```
<div
  class="h-72 bg-cover bg-center"
  style="background-image: url('{{ data.image }}')"
></div>
```

This doesn't work

```
<div
  class="h-72 bg-cover bg-center bg-[url(' {{ data.image }} ')"
></div>
```

**Comment by adamwathan** [comment]
Hey! This is covered in the docs: https://tailwindcss.com/docs/content-configuration#dynamic-class-names
