### ISSUE TITLE
safelist error with double underscore

### ISSUE THREAD

**Issue by charliezstong** [tailwindlabs/tailwindcss#7432]
What version of Tailwind CSS are you using?
3.0.19

What build tool (or framework if it abstracts the build tool) are you using?
none (pug,js,css)

What version of Node.js are you using?
v14.17.1

What browser are you using?
Chrome

What operating system are you using?
Windows 10

Describe your issue
The safelist pattern not working with intlTelInput.css ( https://github.com/jackocnr/intl-tel-input/blob/master/build/css/intlTelInput.css  ) can't extract selector with double underscore "__". 

`
safelist:[
{pattern: /^iti/, variants: ['__']}
]
`

**Comment by adamwathan** [comment]
Closing in favor of your original discussion:

https://github.com/tailwindlabs/tailwindcss/discussions/7431
