### ISSUE TITLE
Resizing Icons with TailWindCss & React-Icons breaks with 3.0.22

### ISSUE THREAD

**Issue by n1xn** [tailwindlabs/tailwindcss#7433]
**What version of Tailwind CSS are you using?**

3.0.22

**What build tool (or framework if it abstracts the build tool) are you using?**

NextJs @v12

**What version of Node.js are you using?**

v12.0.0

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction URL**

Not needed.

**Describe your issue**

While using `react-icons`  @4.3.1 and `tailwindcss` @3.0.0 we were able to size the icons with `w-` and `h-`, which was nice because you could resize based on screensize without js. Unfortunatelly using `tailwindcss` @3.0.22 this does not have any effect. U have to evade by using react `height` and `width` properties. Downgrading from 3.0.22 to 3.0.0 solves the issue.

**Comment by adamwathan** [comment]
Hey! Sorry but a reproduction URL is definitely needed, we don’t have time to setup reproductions from scratch for every issue. Please give us something we can clone down and see the issue ourselves otherwise we just aren’t able to help.
