### ISSUE TITLE
Flex space-x problem when working on RTL layout

### ISSUE THREAD

**Issue by AliMosbah** [tailwindlabs/tailwindcss#7445]
**What version of Tailwind CSS are you using?**

: v3.0.0

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: postcss-cli 8.2.13 , webpack 5.28.0

**What version of Node.js are you using?**

For example: v12.0.0

**What browser are you using?**

For example: Chrome, Safari, mozilla

**What operating system are you using?**

For example: macOS
 

**Describe your issue**

There is a problem using Flex space-x when working on an RTL design
It is not applied to the first element and always starts from the second element
But when RTL is removed from dir and flex-row-reverse is added, it starts from the first element without any problem from right to left
But when working in the direction RTL and working normally flex-row, the first element is ignored, i.e. the first and second elements do not have a space between them, and the distance between the second element and the next is given

**Comment by adamwathan** [comment]
Hey! The answer is here in the docs: https://tailwindcss.com/docs/space#reversing-children-order

If you only need to support modern browsers, you can also just use `gap` which is simpler.
