### ISSUE TITLE
Tailwind is compiling with a bug

### ISSUE THREAD

**Issue by aodamuz** [tailwindlabs/tailwindcss#7457]
Tailwind CSS Version: v3.0.22
Node Version: v14.16.1
NPM Version: 6.14.12
Autoprefixer Version: 10.4.2
Laravel Mix Version: 6.0.42
PostCss Version: 8.4.6
Postcss Import Version: 14.0.2
Browser: Chrome - Versión: 98.0.4758.82 (64 bits)
OS: Windows 10

My TailwindCSS configuration
![image](https://user-images.githubusercontent.com/69234452/153912498-e4316ff1-8856-4954-915e-105132b52d60.png)
![image](https://user-images.githubusercontent.com/69234452/153912593-1b4caf6b-d4a4-4004-adf1-cf03246750dd.png)

webpack.mix.js
![image](https://user-images.githubusercontent.com/69234452/153911078-3f6dcf54-3d26-481d-8327-8ea9e07738b2.png)

app.css
![image](https://user-images.githubusercontent.com/69234452/153911237-17752dfa-397b-4691-999e-2bbad526ae0c.png)

The build output is normal, but in some CSS variables, the value is empty.
![image](https://user-images.githubusercontent.com/69234452/153911503-be2a486a-03cf-420f-ac6d-94b035b62c07.png)
![image](https://user-images.githubusercontent.com/69234452/153911711-26f93261-e402-465f-b864-c677dd47b84e.png)

And the CSS variable --tw-shadow-color is not defined.
![image](https://user-images.githubusercontent.com/69234452/153911908-cceb00ed-e1b9-4365-97b7-05abf3861d95.png)

I would like to know if this should be reported as a bug or if it is a compatibility problem with the versions of the dependencies or NodeJS since the only thing that I have changed recently is the version of NodeJS.

**Comment by adamwathan** [comment]
Hey! Not a bug, that is totally valid CSS and deliberate. Empty CSS variables are really useful for making chunks of a composed value optional.

Check out this blog post I wrote about how we do this sort of thing in Tailwind a while ago:

https://adamwathan.me/composing-the-uncomposable-with-css-variables/

The only issue here is that whatever you are using for linting thinks this is invalid but is wrong — consider opening an issue on that project to get them to fix that 👍

**Comment by aodamuz** [comment]
Thanks for the info Adam! I know it's valid for the browser, but I hadn't seen something like that in TailwindCSS and thought it might be a bug.
