### ISSUE TITLE
HMR is really slow when there are a lot of Vue components with `<style>`

### ISSUE THREAD

**Issue by hivokas** [tailwindlabs/tailwindcss#7480]
**What version of Tailwind CSS are you using?**

3.0.22

**What build tool (or framework if it abstracts the build tool) are you using?**

vite 2.8.2

**What version of Node.js are you using?**

16.13.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

With `<style>` tags (slow): https://github.com/hivokas/laravel-vue-vite-tailwind-slow/tree/with-style-tags
With `<style>` tags, without Tailwind (fast): https://github.com/hivokas/laravel-vue-vite-tailwind-slow/tree/without-tailwind
Without `<style>` tags, with Tailwind (fast): https://github.com/hivokas/laravel-vue-vite-tailwind-slow/tree/without-style-tags

How to run the reproduction:
1. Clone the repo
2. Run `npm install`
3. Run `composer install`
4. Open `laravel-vue-vite-tailwind-slow.test` if you're using Valet
5. Run `npm run dev` to start the Vite dev server 
6. Switch between `with-style-tags`, `without-tailwind` and `without-style-tags` to see the difference 

**Describe your issue**

HMR works really slow when there are a lot of Vue components with `<style>`.

Here is the detailed demo:

https://user-images.githubusercontent.com/22997803/154132172-ba7933d6-2693-499a-bf34-90e2b0877dbb.mp4

**Comment by gufoe** [comment]
I am having the same issue on a large project:
The HMR is reloading ALL vue components that are using the @apply directive in the style section, instead of just loading the one that has changed.
My very basic reproduction repo is [this](https://github.com/gufoe/tailwind-vue-issue) where you can easily see that editing comp1.vue will trigger the hmr for comp2.vue which is totally unrelated.

**Comment by calmyournerves** [comment]
Hey there!

I have described a performance regression we have experienced in https://github.com/tailwindlabs/tailwindcss/discussions/7454 (discussion). The change that caused this for us was introduced in 3.0.9 (PR #6580). I could reproduce your problem with the reproduction repo of @gufoe. When downgrading `tailwindcss` to 3.0.9 there, it seemed to work as expected.

**Comment by hivokas** [comment]
> When downgrading `tailwindcss` to 3.0.9 there, it seemed to work as expected.

Thanks for mentioning that! I'll downgrade to `3.0.9` until this issue is fixed.
