### ISSUE TITLE
addComponents strips out classes when using media queries and breakpoint prefixes.

### ISSUE THREAD

**Issue by LucidNinja** [tailwindlabs/tailwindcss#7486]
**What version of Tailwind CSS are you using?**

3.0.22

**What build tool (or framework if it abstracts the build tool) are you using?**

Next.js 12.0.10

**What version of Node.js are you using?**

v14.18.1

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/HlaH3fi18G?file=config

**Describe your issue**

I'm trying to update my plugin to fix some bugs and support version 3 (https://www.npmjs.com/package/tailwind-container-break-out), but it seems that the `addComponents` and `addUtiliites` methods aren't working with media queries? I've done endless debugging and still can't pinpoint it, but I'm thinking it might have something to do with the classes' `prefixedIdentifier` not being unique?

Using the `addUtilties` method adds the multiple versions of the CSS declarations with nested media queries, and using `addComponents` seems to strip out other versions of the class if they are prefixed with `.sm:\\` , `.md:\\` etc.

I have basically replicated the way that the `.container` class works in TailwindCSS core, but adding media queries. It seemed to work in the previous version, although I was using `addUtilities`, and this was still adding nested media queries.

**Comment by LucidNinja** [comment]
Also @adamwathan - I wouldn't be opposed to this functionality being in core - so many sites I build have a split container, and using a 'negative margin hack' like this seems to be the best way of pulling inner content outside of the container. Here's an example: https://www.sah2h.org/ - just sayin - it would be nice. But, I'm happy for this to remain a plugin.

**Comment by adamwathan** [comment]
Hey! The code you shared is quite big and complex, can you provide a much simpler reproduction that shows an example of one static rule that doesn't work the way you'd expect?

**Comment by LucidNinja** [comment]
Hi @adamwathan - thanks so much for your response. I appreciated that managing such a huge and popular package (which I love by the way!) means that there are so many issues to tackle. 

If this is out of scope, then I understand, but it would be such nice functionality to have. I have created a very simplified version of the issue here: https://play.tailwindcss.com/vHcW0xJsk4.

Let me know if you need more clarity on this - if you clearly understand the issue and choose not to tackle it, I understand, but as long as I've got my concept across clearly enough for you!

**Comment by LucidNinja** [comment]
I guess I'm also wondering whether I have a syntax issue that's breaking it? Like with the double backslashes??

**Comment by LucidNinja** [comment]
To get to the point of my requirement: I want to be able to create classes that are based on the max-width of the container at each breakpoint (even if user-configured), and there doesn't seem to be another way of attaining this? Unless I've missed something?

**Comment by adamwathan** [comment]
Thanks for creating that! So looking at that, to me the right change is just to not bake in the modifiers into your plugin, like this:

https://play.tailwindcss.com/TCgZ4Nezmn

Tailwind handles applying them conditionally automatically. Does this help? You definitely never want to be putting stuff like `md:` right in your `addComponents` calls.

**Comment by LucidNinja** [comment]
Ok perfect! This has definitely solved my problem. That said - even in your example it seems to be producing nested media queries, which I'm not sure is intended behaviour (even though it's working). If you inspect the md:container-half or lg:container-half classes, you'll see that it's producing something like this:

```
@media (min-width: 768px)
@media (min-width: 1024px)
.md\:container-half {
    width: calc(1024px / 2);
}
```

However, this is the same if you use Tailwind's core container class when prefixed with a breakpoint:

```
@media (min-width: 1024px)
@media (min-width: 1536px)
.lg\:container {
    max-width: 1536px;
}
```

I'm not sure if this is intended?

**Comment by adamwathan** [comment]
Yeah that's intended in the sense that we haven't bothered to optimize it away 👍🏻 It is still totally valid CSS and does what you'd expect.
