### ISSUE TITLE
Class (same) not generated during :class binding in v-for

### ISSUE THREAD

**Issue by ivanchenhz** [tailwindlabs/tailwindcss#7487]
**What version of Tailwind CSS are you using?**

^3.0.22

**What build tool (or framework if it abstracts the build tool) are you using?**

"vite": "^2.8.0"

**What version of Node.js are you using?**

v14.17.5

**What browser are you using?**

Chrome

**What operating system are you using?**

macOs

**Reproduction URL**

https://github.com/ivanchenhz/tailwind_classBinding

**Describe your issue**

I found an intersecting issue, the 'SAME' class will not generate properly when using class binding in for loop, have tried both vue and angular ( I guess the reason is the same, the repeated class have been ignored ? )

<img width="2048" alt="class_binding_issue" src="https://user-images.githubusercontent.com/2640513/154185174-9211bb2f-5166-45d5-bfd7-98cc92bfea72.png">

**Comment by thecrypticace** [comment]
This is because, in JS, using the same key more than once in an object will overwrite earlier keys.

So the expression `{ 'bg-pink-300': s.on, 'bg-pink-300': !s.on }` is the same as `{ 'bg-pink-300': !s.on }` which is why you're seeing the behavior you are.
