### ISSUE TITLE
Preflight not working as expected

### ISSUE THREAD

**Issue by tonytoth** [tailwindlabs/tailwindcss#7490]
**What version of Tailwind CSS are you using?**

3.0.23

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss-cli 8.2.12

**What version of Node.js are you using?**

16.13.1

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Describe your issue**

I am not sure if I undestand what preflight does but, in documentation says that we should use `@tailwind base;` in our css file and use preflight to disable it but it's not working as expected. 
For example I'm having troubles with input border as it still includes some css so I have to comment `/* @tailwind base */` to get the result I want.
I'm extending an existing tailwind config and import an existing css from a library, so I don't need the tailwind base twice.

**Comment by adamwathan** [comment]
Hey! I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction — a [Tailwind Play](https://play.tailwindcss.com) if the issue can be reproduced there, or a GitHub repository where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
