### ISSUE TITLE
Wrong compiled order

### ISSUE THREAD

**Issue by coder054** [tailwindlabs/tailwindcss#7514]
Tailwind 3.0.18

Code: 
```
<div className="grid grid-cols-1 xs:grid-cols-2 
      sm:grid-cols-2  md:grid-cols-3 gap-[20px]
      md:border md:border-red-500 p-4 m-4
      ">           
      <div className="border p-4 ">1</div> 
      <div className="border p-4 ">2</div>
      <div className="border p-4 ">3</div>
      <div className="border p-4 ">4</div> 
</div>

```

// tailwind.config.js
```
module.exports = {
  theme: {
    extend: {
       screens: {
        xs: '375px',
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
        '3xl': '1800px'
      },
    },
  },
  plugins: [],
}
```

//
Expect: got 3 column at 1920 x 1080

//
Reality: got 2 column at 1920 x 1080

//
My guess: the compiled css file got this line at the end
```
@media (min-width: 375px) {
  .xs\:grid-cols-2 {
    grid-template-columns: repeat(2, minmax(0, 1fr)) !important;
  }
}
```
it will override this code
```
@media (min-width: 768px) {
  .md\:grid-cols-3 {
    grid-template-columns: repeat(3, minmax(0, 1fr)) !important;
  }
}
```

**Comment by adamwathan** [comment]
Hey! I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction — a [Tailwind Play](https://play.tailwindcss.com) if the issue can be reproduced there, or a GitHub repository where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
