### ISSUE TITLE
Background Opacity does not work when color relies on css variable

### ISSUE THREAD

**Issue by HuiiBuh** [tailwindlabs/tailwindcss#7575]
**What version of Tailwind CSS are you using?**
For example: v3.0.18

**What build tool (or framework if it abstracts the build tool) are you using?**
Tailwind play, Nx

**What browser are you using?**
Chrome, Firefox

**What operating system are you using?**
Linux

**Reproduce**
When you add your own color key in the colors object and make the color a css variable the opacity modifier i.e. `/50` is not working anymore. If you don't use a css variable it is working.

Create the html and try to use the opacity modifier at a custom color
```html
<div style="--custom-color: #123" class="h-52 w-52 bg-custom-color/50"></div>
```

```javascript
module.exports = {
  theme: {
    extend: {
      colors:{
        // Reference a css variable, otherwise it will work
        "custom-color": "var(--custom-color)"
      }
    },
  },
  plugins: [],
}
```

**Comment by adamwathan** [comment]
Hey! See the docs to learn how to make this work: https://tailwindcss.com/docs/customizing-colors#using-css-variables

**Comment by ahmed-esmail-1** [comment]
I have this exact problem, did you solve it ?

**Comment by ahmed-esmail-1** [comment]
It only took me 15 minutes of reading the docs you sent and trying, ty !

**Comment by raducostea** [comment]
Ok, also make sure you don't use comma

This will work
```
--secondary: 210 40% 96.1%;
```

This will not work, i wasted about an hour not understanding why its not working before i saw i was using comma
```
--secondary: 210, 40%, 96.1%;
```

**Comment by ankitjena** [comment]
@raducostea your comment saved me scratching my head. Thanks

**Comment by hakkm** [comment]
But this solution causes IDEs like vscode to not display the color, this is so annoying for me.

**Comment by sfilzek** [comment]
For anyone stumbling across this in the future.. Just a small clarification which was messing me around for a while:

As per the docs: (https://tailwindcss.com/docs/customizing-colors#using-css-variables) you need to define the variables correctly (ie without color space) to make the opacity modifiers work.

HOWEVER, the only way to modify opacity on a color defined in a CSS variable is to use the slash notation, eg:

```html
<div class="text-primary/10">This text will be 10% opaque</div>
``` 

If you try to use the opacity classes, they will not work:

```html
<div class="text-primary text-opacity-10">This text will not have opacity applied</div>
```

Hint: Use a nicely crafted regex to update your codebase for this change! :)

**Comment by enix79** [comment]
@sfilzek, same for me here at the end of 2024...I would rather classify this as bug?

**Comment by mariasimo** [comment]
Agree with @enix79. This is working as expected when you use an hex value directly in the theme, but if you use that same value through a css variable it won't. So it looks like a bug.

✅ this works:
```
    extend: {
      colors: {
        green: "#00cc30",
      },
``

```
<div className="text-green/50">Opacity text</div>
```

❌ but this don't

```
:root {
  --green: #00cc30;

```

```
    extend: {
      colors: {
        green: "var(--green)",
      },
``

```
<div className="text-green/50">Opacity text</div>
```

in both cases, this works:
```
<div className="text-green">Normal text</div>
```

**Comment by adamfratino** [comment]
the steps in [this guide](https://tailwindcss.com/docs/customizing-colors#using-css-variables) don't work with `oklch`

**Comment by King-OJ** [comment]
> Agree with @enix79. This is working as expected when you use an hex value directly in the theme, but if you use that same value through a css variable it won't. So it looks like a bug.
> 
> ✅ this works:
> 
> ```
>     extend: {
>       colors: {
>         green: "#00cc30",
>       },
> ```
> 
> ```
> <div className="text-green/50">Opacity text</div>
> ```
> 
> ❌ but this don't
> 
> ```
> :root {
>   --green: #00cc30;
> }
> ```
> 
> ```
>     extend: {
>       colors: {
>         green: "var(--green)",
>       },
> ```
> 
> ```
> <div className="text-green/50">Opacity text</div>
> ```
> 
> in both cases, this works:
> 
> ```
> <div className="text-green">Normal text</div>
> ```

This worked for me. Totally thank you for this solution

**Comment by jasper-clarke** [comment]
This is still an issue!
I cannot find the solutions and the original page on how to fix this in the docs is removed.
Can somebody please help!!!

```css
@layer base {
  :root {
    --text: 20 21 14;
    --background: 240 240 240;
    --primary: 126 186 120;
    --secondary: 154 185 152;
  }
  .dark {
    --text: 240 241 234;
    --background: 15 15 15;
    --primary: 74 135 69;
    --secondary: 72 103 70;
  }
}
```

```js
export default {
  darkMode: 'class',
  content: ['./src/**/*.{html,js,svelte,ts}'],

  theme: {
    extend: {
      colors: {
        text: 'var(--text)',
        background: 'var(--background)',
        primary: 'var(--primary)',
        secondary: 'var(--secondary)',
      },
    },
    fontFamily: {
      sans: ['Inter', 'sans-serif'],
      serif: ['Syne', 'serif'],
    },
  },

  plugins: [forms],
} satisfies Config;
```

**Comment by jonshipman** [comment]
@jasper-clarke 
https://v3.tailwindcss.com/docs/customizing-colors#using-css-variables

**Comment by jasper-clarke** [comment]
@jonshipman 
I've already tried all of those alternatives and they do not work for me.
After a lot of researching I found that using the color mix function with hex values is what works.
https://github.com/tailwindlabs/tailwindcss/issues/9143#issuecomment-1946755547

**Comment by rnyell** [comment]
This is really disgusting. It's 2025 and this stpd bug still exists.
