### ISSUE TITLE
tailwindcss3.x setting color in IOS12 does not display

### ISSUE THREAD

**Issue by GOGOGOSIR** [tailwindlabs/tailwindcss#7604]
**What version of Tailwind CSS are you using?**

For example: v3.0.23

**What build tool (or framework if it abstracts the build tool) are you using?**

vite 2.x

**What version of Node.js are you using?**

For example: v14.18.0

**What browser are you using?**

Safari

**What operating system are you using?**

iphone

**Describe your issue**

rgb (12 256 44/var(--tw-bg-opacity)) is not displayed under IOS12

**Comment by GOGOGOSIR** [comment]
I want to set rgb to the previous value through the postcss-color-rgb plugin, but the result still doesn't work

**Comment by GOGOGOSIR** [comment]
I really want to use tailwindcss3.x, if there is no way to solve it, I can only use 2.x, I hope the author can be compatible, thank you

**Comment by adamwathan** [comment]
Hey! Unfortunately Tailwind CSS v3 does not support old browsers like iOS Safari 12. If you need to support older browsers you’ll have to stick with v2.

**Comment by flyfinec** [comment]
@GOGOGOSIR postcss-color-rgb I tried it and it doesn't work, maybe it's the reason why postcss 8 is not supported, this library has not been updated for a long time

try postcss-preset-env
https://github.com/csstools/postcss-preset-env
https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-color-functional-notation

1. npm install postcss-preset-env --save-dev
2. Add plugin configuration to postcss.config.js, like:

```js
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
    'postcss-preset-env': {
      browsers: 'chrome >= 50', // configure a compatible browser version
    },
  },
};
```
If you use **nextjs**, delete the **.next** directory first, and then execute **npm run dev** to test

The plugin for postcss-preset-env will automatically convert CSS Colors 4 notation to compatible notation:
```css
css colors 4 notation:
rgb(245 247 255 / var(--tw-bg-opacity))

compatible notation:
rgba(245, 247, 255, var(--tw-bg-opacity))
```
