### ISSUE TITLE
Npm Run Watch issue with JIT using Laravel Mix with Tailwind

### ISSUE THREAD

**Issue by chrisgrim** [tailwindlabs/tailwindcss#7662]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/7589

<div type='discussions-op-text'>

<sup>Originally posted by **chrisgrim** February 22, 2022</sup>
"laravel-mix": "^6.0.6",
"laravel-mix-tailwind": "^0.1.2",
"postcss": "^8.4.6",
"postcss-import": "^12.0.1",
"tailwindcss": "^3.0.21",

I recently discovered tailwind and I can't explain how much I love it. I set it up for one of my WordPress projects and the JIT compiler was amazing. I recently have tried to set it up with Laravel mix and I am not having much luck.
When I run npm run watch it works, however if I save a Vue file in my project it looks like it recompiles but if I created a custom class like h-[43rem] it won't be there. I have to cancel npm run watch and then run it again. This does work but it gets tedious to have to cancel the npm run watch every time I add a new class. 

I am using Laravel mix tailwind and in my webpack.mix.js file I have 
```
const mix = require('laravel-mix');

require('laravel-mix-tailwind');

mix.sass('resources/sass/app-create.scss', 'public/assets')
    .sass('resources/sass/app-admin.scss', 'public/assets')
    .sass('resources/sass/app-lite.scss', 'public/assets')
    .postCss('resources/css/app.css', 'public/assets', [
        require('tailwindcss'),
    ])
    .js('resources/js/app.js', 'public/assets')
    .extract(['vue'])
    .webpackConfig({
        output: {
            chunkFilename: '[name].js?id=[chunkhash]',
        }
    })
    .tailwind()
    .vue();
```
In my tailwind.js file (this is what laravel mix tailwind uses instead of the tailwind.config.js)
```
module.exports = {
    mode: 'jit',
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    theme: {
        fontSize: {
            'xs': '.75rem',
            'sm': '.875rem',
            'tiny': '.875rem',
            'base': '1rem',
            'lg': '1.125rem',
            'xl': '1.25rem',
            '1xl': '1.35rem',
            '2xl': '1.5rem',
            '3xl': '1.875rem',
            '4xl': '2.25rem',
            '5xl': '3rem',
            '6xl': '4rem',
            '7xl': '5rem',
        },
        extend: {
            spacing: {
                '128': '32rem',
            }
        }
    },
    plugins: [],
}
```

and in my package.json I have
```
    "scripts": {
        "dev": "npm run development",
        "development": "TAILWIND_MODE=build NODE_ENV=development mix",
        "watch": "TAILWIND_MODE=watch NODE_ENV=development mix watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "prod": "npm run production",
        "production": "mix --production"
    },
```
Thanks so much!!

</div>

**Comment by adamwathan** [comment]
Hey! Going to close this in favor of the original discussion as my gut is this isn't a bug but just something we have to figure out and help you configure correctly.
