### ISSUE TITLE
Remove img height rule from @tailwind base;

### ISSUE THREAD

**Issue by oskarleonard** [tailwindlabs/tailwindcss#7739]
This prevents one from specifying height on img tags, so the height attribute basically becomes worthless. It would be much better to only specify it for img tags that doesnt have a height attribute `img:not([height]){...}`. 

Is there otherwise a way to remove specific rules from the base?

**Comment by reinink** [comment]
Closing this as per my comments here: https://github.com/tailwindlabs/tailwindcss/pull/7742#issuecomment-1061332148
