### ISSUE TITLE
Path with & and space results in "Cannot find module"

### ISSUE THREAD

**Issue by codestylist** [tailwindlabs/tailwindcss#7746]
Hi there.
I have an installation path on Windows like this: `E:\services\my company GmbH & Co. KG\domain.tld\donain.tld\wp-content\themes\companys-name`.
Running `npm install -D tailwindcss` works as exprected.
When I run `npx tailwindcss init` I get the error message:
```
The command "Co." is wrong or couldn't be found
node:internal/modules/cjs/loader:936
  throw err;
  ^
```
```
Error: Cannot find module 'E:\services\tailwindcss\lib\cli.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
I figured out the error comes in combination with `&` and spaces in my path.

Would appriciate if someone can double check and fix it, if possible. Thank you!

**Comment by thecrypticace** [comment]
I'm pretty sure this is an issue with `npx` and would advise you open an issue there. I can reproduce the same problem using an entirely unrelated package:
```
npm I gulp gulp-cli
npx gulp
```

**Comment by Isaacjon** [comment]
wow i removed "&" from my main folder name and it workend
