### ISSUE TITLE
prose-p:empty:after:content-['\00A0'] appears not to work

### ISSUE THREAD

**Issue by AndreasHald** [tailwindlabs/tailwindcss#7811]
**What version of Tailwind CSS are you using?**

v3.0.23 (play.tailwindcss.com)

**What build tool (or framework if it abstracts the build tool) are you using?**
Unsure what play.tailwindcss.com uses

**What version of Node.js are you using?**
Unsure what play.tailwindcss.com uses

**What browser are you using?**
Reproducible in both chrome and safari

**What operating system are you using?**
macOS

**Reproduction URL**
https://play.tailwindcss.com/hpqmEFfGs2

**Describe your issue**
I'm attempting to insert an ``::after`` element on empty ``p`` tags inside the typography prose plugin. 
This class works fine as expected ``prose-p:after:content-['\00A0']`` however if I add the ``:empty`` it stops working ``prose-p:empty:after:content-['\00A0']``

I gladly admit I may be pushing the chaining thing a bit much 😀 I just love tailwind.

**Comment by thecrypticace** [comment]
I *think* this will do what you're attempting: `after:empty:prose-p:content-['\00A0']`

Does that work for you?

**Comment by AndreasHald** [comment]
That actually works exactly as it should, I'm still confused as to why that order works. But it's clearly not a bug, i apologise for the issue. And thanks for the help :)
