### ISSUE TITLE
input type="search" properties are not reset on iPhone

### ISSUE THREAD

**Issue by aliveli186** [tailwindlabs/tailwindcss#7816]
**What version of Tailwind CSS are you using?**
v3.0.23

**Describe your issue**

On iPhone the input **type="search"** properties are not reset by default and components are rendered differently from desktop browsers.
When the type is changed to **input type="text"** the rendering is identical.

Visuals:
**input type="search"**
![input_search](https://user-images.githubusercontent.com/8914034/157868368-47a57700-ca29-41ad-931d-d6bb91912783.jpeg)

**input type="text"**
![input_text](https://user-images.githubusercontent.com/8914034/157868390-37e7d4f3-496b-4c7b-b145-dc2f6c748891.jpeg)

**Comment by josephriosIO** [comment]
what does this have to do with tailwind exactly? @aliveli186

**Comment by aliveli186** [comment]
> what does this have to do with tailwind exactly? @aliveli186

The desktop and mobile browsers render the type="search" differently probably because tailwind doesn't reset the type="search" properties like it does with type="text" thus different default style is enforced on mobile.
Border radius and background color (maybe more properties as well) are inconsistent on mobile as you can see from the visuals. 

Again from the visuals above; if I change type="search" to type="text" mobile browsers start to render it as desired like it is rendered on desktop browsers but I lose the clear content icon (X) when I change it to type="text".
I want to keep the clear content icon (x) and have the default input properties on type="search".

**Comment by AviAvinav** [comment]
Is this problem still persisting? If yes, I would like to give a try at fixing it. I think it might be a problem with the preflight styles, I am not sure though.

**Comment by aliveli186** [comment]
> Is this problem still persisting @aliveli186 ? If yes, I would like to give a try at fixing it. I think it might be a problem with the preflight styles, I am not sure though.

Adding the following fixed my issue:
```
    input[type="search"] {
        -webkit-appearance: none !important;
    }
```

**Comment by AviAvinav** [comment]
I see, that's good. I will still open a pr with that fix, just in case, for future users who might encounter this problem.

**Comment by thecrypticace** [comment]
@aliveli186 Hey! Thanks for opening this issue. Can you provide a link to a reproduction (preferably on Tailwind Play if you can) as well as information about which version of iOS you're using? The forms plugin is resetting input styles even for search inputs.

See a rough example of what I put together here: https://play.tailwindcss.com/B2rKsVb2gk?file=config

You'll see that the form style is reset on the search input — at least on my phone that is currently on iOS 15.4.1.

**Comment by adamwathan** [comment]
Hey! I don't think we can really change this without it being a breaking change, and we don't apply `appearance: none` to inputs out of the box so I think just going to close this one.

I would recommend just adding the `appearance-none` utility any time you have a search input to handle the iOS case, and maybe we can consider being more heavy-handed with this type of reset in v4.

You already have to do other stuff `rounded-none` to remove the default iOS border radius on inputs too, so it's not super unusual to have to consider different browsers when building things with Tailwind.

Again not opposed to thinking about this in the future but my opinion today at least is this is just something people should handle in their own projects at the HTML level 👍🏻 If we changed anything it would be a breaking change, and who knows what other issues would show up by trying to fix this one 😕

**Comment by aliveli186** [comment]
> You already have to do other stuff `rounded-none` to remove the default iOS border radius on inputs too, so it's not super unusual to have to consider different browsers when building things with Tailwind.
> 
> Again not opposed to thinking about this in the future but my opinion today at least is this is just something people should handle in their own projects at the HTML level 👍🏻 If we changed anything it would be a breaking change, and who knows what other issues would show up by trying to fix this one 😕

I understand your concerns but I also think that as a framework it's more of your task to make the visuals to look as similar as possible across the browsers.
This issue exists only in iPhone, on desktop and android it looks identical.
I also see from the generated styles that you're indeed overriding some properties to make them look similar. For example the `::-webkit-search-decoration` property. If desktop and android look similar for `type=search` why iPhone wouldn't?

```
[type=search] {
    -webkit-appearance: textfield;
    outline-offset: -2px
}

::-webkit-search-decoration {
    -webkit-appearance: none
}

::-webkit-file-upload-button {
    -webkit-appearance: button;
    font: inherit
}
```
