### ISSUE TITLE
New installation results in invalid CSS output

### ISSUE THREAD

**Issue by mcgraphix** [tailwindlabs/tailwindcss#7830]
**What version of Tailwind CSS are you using?**
3.0.23

**What build tool (or framework if it abstracts the build tool) are you using?**

None yet

**What version of Node.js are you using?**

14.16.1

**What browser are you using?**

Chrome

**What operating system are you using?**

MacOS

**Reproduction URL**

A Tailwind Play link or public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.

**Describe your issue**

Using the instructions found here:
https://tailwindcss.com/docs/installation

The resulting CSS output includes this resulting in any class defined after that failing to work
```

.w-\[this-is\\\\\]w-\\\\\[weird-but-valid\] {
  width: this-is\\]w-\\[weird-but-valid;
}
```

**Comment by adamwathan** [comment]
Hey! Your `content` is misconfigured to include `node_modules` and is scanning some of Tailwind’s own test files.

Previous discussion: https://github.com/tailwindlabs/tailwindcss/discussions/5781
