### ISSUE TITLE
Tailwindcss v3.0.23 generates broken classes

### ISSUE THREAD

**Issue by Code-Mythos** [tailwindlabs/tailwindcss#7843]
I recently installed the latest version (**v3.0.23**) of **Tailwind CSS** as suggested in its [document](https://tailwindcss.com/docs/installation/using-postcss) (webpack v5.70.0, node v16.14.0, postcss-cli v9.1.0, Chrome v99.0.4844.51, Windows 10 64bit).

After linking the HTML file to generated .css file, and adding a simple "bg-blue-800" class to the body of the HTML file, there were not any changes in the background color.
**Visual Studio Code** indicates that there is a  problematic class in the .css file. The class looks like as following: 
`.w-\[this-is\\\\\]w-\\\\\[weird-but-valid\] {
     width: this-is\\]w-\\[weird-but-valid;`

Although my problem is resolved by installing the previous version of Tailwind CSS (v2.2.7), I think the problem should be taken into consideration. Because there are considerable features and fixes in the latest versions that can be helpful in many projects.
Best regards.

**Reproduction URL**
[Github Repository](https://github.com/Code-Mythos/TailwindCSS-Hands-On-Project)

**Comment by aggreggator** [comment]
https://github.com/tailwindlabs/tailwindcss/issues?q=weird

**Comment by Code-Mythos** [comment]
Thanks for your reply.
I tried to change the content path in tailwind.config.js to only **"./dist/index.html"** which is my **only** file in the format of .html and .js. But it only produced 400 lines of styles in the target .css file.
However, when I've tried the exact same configuration (content path) with v2.2.7, it generated 188022 lines of code without any error!

**Comment by aggreggator** [comment]
V3 uses JIT compiler and does not generate all claases. Only classes you used in your files are generated. Take a look at documentation. Major paradigm shift.

**Comment by segzybaba** [comment]
i am facing same issue right now
