### ISSUE TITLE
Not all postcss configuration options are supported using the tailwind CLI

### ISSUE THREAD

**Issue by rbclark** [tailwindlabs/tailwindcss#7856]
**What version of Tailwind CSS are you using?**

For example: v3.0.23

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: tailwind-cli v3.0.2.3 directly

**What version of Node.js are you using?**

For example: v17.7.1

**What browser are you using?**

N/A

**What operating system are you using?**

macOS

**Reproduction URL**

https://gist.github.com/rbclark/71a0425496cdb5b662627704576ad276

**Describe your issue**

No matter what options I pass into the `map` option, they are not respected. When doing the exact same thing though the `postcss-cli` the options are respected. In my case I am running into an issue where one of my files has an external sourcemap and it is forcing all of my sourcemaps to be generated externally. Switching to the postcss CLI with the exact same config fixed the problem which makes me think it is a problem with the tailwind CLI.

**Comment by rbclark** [comment]
Thanks @thecrypticace!

**Comment by thecrypticace** [comment]
Hey, good catch! Yeah we were only loading the plugins from the config file and not passing options through the CLI. The fix for this should hit our insiders build in a few minutes.
