### ISSUE TITLE
Default timing is generated even if a custom one is given

### ISSUE THREAD

**Issue by bakura10** [tailwindlabs/tailwindcss#7866]
**What version of Tailwind CSS are you using?**

v3.0.23

Hi :),

When specifying a custom timing function:

```
.foo {
  @apply transition-all duration-500 ease-[cubic-bezier(0.77,0,0.175,1)];
}
```

Tailwind generate both the default AND the custom timing:

```
.foo {
  transition-property: all;
  transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
  transition-duration: 500ms;
  transition-timing-function: cubic-bezier(0.77,0,0.175,1);
}
```

While the desired result should be:

```
.foo {
  transition-property: all;
  transition-duration: 500ms;
  transition-timing-function: cubic-bezier(0.77,0,0.175,1);
}
```

This seems to be a bug because despite the default duration being 150ms, if we set a custom one only this one is generated.

Thans!

**Comment by marco-carvalho** [comment]
[I just started a discussion very similar to yours](https://github.com/tailwindlabs/tailwindcss/discussions/7873)
