### ISSUE TITLE
Prefix option does not work with custom properties

### ISSUE THREAD

**Issue by bakura10** [tailwindlabs/tailwindcss#7874]
**What version of Tailwind CSS are you using?**

v3.0.23

Hi !

I am trying to use the prefix option, but I have found a problem that prevents it to work for more complex patterns. For instance, here is a simple code _without_ any prefix:

```
.button {
  @apply text-[color:rgb(var(--button-background,var(--primary-button-background)))];
}
```

This properly generates the following markup:

```
.button {
  color: rgb(var(--button-background,var(--primary-button-background)));
}
```

When using a prefix (in my example "tw-"), if I change the apply:

```
.button {
    @apply tw-text-[color:rgb(var(--button-background,var(--primary-button-background)))];
  }
```

Then the following incorrect CSS is generated (note the lack of selector):

```
 {
  color: rgb(var(--button-background,var(--primary-button-background)));
}
```

**Comment by bakura10** [comment]
To complement this issue, here are a few other use cases where CSS generation fails with prefix:

```
.accordion-content {
    @apply tw-ease-[cubic-bezier(0.77,0,0.175,1)];
  }
```

Generates this incorrect markup:

```
 {
  transition-timing-function: cubic-bezier(0.77,0,0.175,1);
}
```

While the same without the prefix configured generate the correct markup.

**Comment by bakura10** [comment]
Hi,

Here are a few other cases where Tailwind generate incorrect CSS with prefix:

```
.foo {
  @apply tw-rounded-[min(4px,var(--input-border-radius))];
}
```

It generates the following incorrect code (notice the lack of selector):

```
{
  border-radius: min(4px,var(--input-border-radius));
}
```

**Comment by Hammond555** [comment]
I'd be in favor to, since Bootstrap can live beside other libraries (eg. Booster v4 includes jQuery TableSorter, speaking of table styles leaking) or custom code.
