### ISSUE TITLE
JIT does not recognize some classes with custom attributes

### ISSUE THREAD

**Issue by bakura10** [tailwindlabs/tailwindcss#7884]
**What version of Tailwind CSS are you using?**

Insider version

Hi :),

I am generating classes in Liquid (Shopify programming language), but TailWind does not recognize some classes when I am using prefix + custom attributes. For instance, this is properly recognized by the JIT engine (even without spaces):

```
{% if settings == 'foo'%}tw-translate-x-8{% endif %}
```

However, this is not:

```
{% if settings == 'foo'%}tw-translate-x-[var(--scroll-offset)]{% endif %}
```

However, if I add spaces around the Liquid condition, then it is recognized:

```
{% if settings == 'foo'%} tw-translate-x-[var(--scroll-offset)] {% endif %}
```

I tried to check the doc for the condition and from my understanding the case without spaces should be catched, but it is not.

Thanks! :)

**Comment by anosadal** [comment]
Happy you like it. We have been utilizing this for half a month at this point and it is by all accounts going pleasantly.

**Comment by Emmitt121** [comment]
I was trying this out and got some issues and still finding it can you give some more suggestions if any thanks in advance.

**Comment by thecrypticace** [comment]
Hey! We've rewritten our default class candidate extractor and it should be a good bit more resilient in situations like these. Would you mind giving the insiders build a test and make sure that you're seeing what you expect? `npm install tailwindcss@insiders` — thanks!
