### ISSUE TITLE
Scroll Snapping is broken in Firefox

### ISSUE THREAD

**Issue by ggoraa** [tailwindlabs/tailwindcss#7907]
**What version of Tailwind CSS are you using?**

v3.0.23

**What build tool (or framework if it abstracts the build tool) are you using?**

[Publish](https://github.com/JohnSundell/Publish) with a custom step to run Tailwind

**What version of Node.js are you using?**

Included with TailwindCSS CLI tool

**What browser are you using?**

Firefox 98.0.1

**What operating system are you using?**

macOS 12.3

**Reproduction URL**

https://tailwindcss.com/blog/tailwindcss-v3#scroll-snap-api

**Describe your issue**

Scroll snap does not work, and simply just messes with scrolling. On Safari everything works as expected. 

**Safari**:

![](https://user-images.githubusercontent.com/61655029/159290659-56b17395-a771-4f3e-938a-7b2ba82f6f25.mov)

**Firefox:**

![](https://user-images.githubusercontent.com/61655029/159290941-79c64195-02e1-414c-86c9-45be564ff2c7.mov)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

Our scroll snap utilities set the native scroll snap related properties. This is unfortunately a browser bug (https://bugzilla.mozilla.org/show_bug.cgi?id=1749352) and we don't have control over browsers implementation so there is not much we can do here.

If you need this functionality in Firefox as well you either have to wait until it is properly implemented / fixed, or you need a js polyfill like implementation.

**Comment by rvanbaalen** [comment]
Is this still an ongoing issue? Scroll snap does not seem to do anything in Firefox.
