### ISSUE TITLE
input type=password, the clickable eye disappears

### ISSUE THREAD

**Issue by FelipeGiovanni** [tailwindlabs/tailwindcss#7916]
**What version of Tailwind CSS are you using?**
3.0.23

**What build tool (or framework if it abstracts the build tool) are you using?**
next.jx 12.1.0

**What version of Node.js are you using?**
17.0.21

**What browser are you using?**
Chrome/Edge

**What operating system are you using?**
Windows

**Reproduction URL**
![image](https://user-images.githubusercontent.com/53339832/159504798-7c057856-41c3-4463-abc1-c2184b2c314d.png)
![image](https://user-images.githubusercontent.com/53339832/159504828-8c462a78-b70d-42a2-8447-cdbd6de30ff8.png)

**Describe your issue**
Edge - When <input> type=password, the clickable eye appears, but if you click outside the component and click on the component again, the eye will disappear.
Chrome - Eye doesn't seem to show password

**Comment by FelipeGiovanni** [comment]
actually it looks like a component error and not a tailwind error.

https://codesandbox.io/s/next-js-forked-gsukxg?file=/index.js

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This doesn't seem like a Tailwind CSS issue so there is not much we can do here. Going to close this for now.
