### ISSUE TITLE
Customizing extraction logic fails when there is no match

### ISSUE THREAD

**Issue by balazser** [tailwindlabs/tailwindcss#7951]
**What version of Tailwind CSS are you using?**

tailwindcss v3.0.23

**What build tool (or framework if it abstracts the build tool) are you using?**

`npx tailwindcss -o tailwind.scss`

**What version of Node.js are you using?**

v16.14.0

**What browser are you using?**

N/A

**What operating system are you using?**

Debian Linux Bullseye

**Describe your issue**

I use `Customizing extraction logic` according to the [documentation](https://tailwindcss.com/docs/content-configuration#customizing-extraction-logic) and I realized building the style `npx tailwindcss -o tailwind.scss` fails at  `tailwindcss/lib/lib/expandTailwindAtRules.js:77` when the function does not return with the result or empty array as a fallback.

**Comment by adamwathan** [comment]
If I'm understanding right then yep this is working as expected — the function should return an array (either with matches, or empty).

If you think there's a real bug here please include a proper reproduction and we can take a look 👍🏻
