### ISSUE TITLE
[question] Desgin Resources

### ISSUE THREAD

**Issue by TinsFox** [tailwindlabs/tailwindcss#7962]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/7913

<div type='discussions-op-text'>

<sup>Originally posted by **TinsFox** March 22, 2022</sup>
Do we have design resources? Something like [ant design](https://ant.design/docs/resources-cn). I really like the visual design of tailwindcss, but it is quite cumbersome to use tailwindcss to build the middle and backend. I want to use React to build a component library, but I don't know where to find the visual design specification.
I would be very grateful if you could tell me where to find the information I need</div>

**Comment by adamwathan** [comment]
Please don’t abuse the issue tracker for questions.
