### ISSUE TITLE
Can't use % for background-position arbitrary value

### ISSUE THREAD

**Issue by dwkns** [tailwindlabs/tailwindcss#7997]
**What version of Tailwind CSS are you using?**

3.0.23

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss-cli 9.1.0

**What version of Node.js are you using?**

v17.7.2

**What browser are you using?**

Safari

**What operating system are you using?**

macOS

**Reproduction URL**
https://play.tailwindcss.com/dBpXEnLlgb

**Describe your issue**
Percentages are not output when using `bg-[ arbitrary values ]`
`bg-[top_right_75px]` → works just fine
`bg-[top_right_5rem]` → works just fine
`bg-[top_right_50%]` → doesn't output the expected CSS

Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead.
https://play.tailwindcss.com/dBpXEnLlgb

Update:
`bg-[top_right_calc(50%)]` → works just fine!!!!

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #8015, and will be available in the next release.

You can already try it by using the insiders build `npm install tailwindcss@insiders` or `yarn add tailwindcss@insiders`.
