### ISSUE TITLE
Tailwind without CSS Variables and `calc()`

### ISSUE THREAD

**Issue by syahid246** [tailwindlabs/tailwindcss#8003]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/7990

<div type='discussions-op-text'>

<sup>Originally posted by **syahid246** March 30, 2022</sup>
Hi! I really like Tailwind CSS 😄, and also attach great importance to browser compatibility 🙂.

I've tried it in the IE browser, but it doesn't work well 😅.

For example `text-blue-700`.
Tailwind CSS generates the code : `rgb(29 78 216 / var(--tw-text-opacity)))`,
while CSS Variables are not supported in all browsers ([https://caniuse.com/css-variables](https://caniuse.com/css-variables)). 😥

`calc()` also : [caniuse.com/calc](https://caniuse.com/calc). 😓

Is there a plan not to wear it? 🤔

Or in previous versions of Tailwind CSS not use CSS Variables and Calc? If so, in what version? 😀

Thanks. 😁</div>

Maybe this discussion is sinking 😔😓, so I'm creating the issue.

**Comment by syahid246** [comment]
> Please don't abuse issues for questions like this

Oh, sorry 🙏🙇‍♂️ I'm new to Github and still learning 🙃😔.

But, thanks for the answer 👍. My user clients are using old browsers, so I attach great importance to browser compatibility 🤐.

**Comment by brandonmcconnell** [comment]
@syahid246 Just a heads up that IE will reach its full end-of-life on June 15, 2022, at which point lots of things will start to break for IE users because even Microsoft will not be supporting the browser anymore.

You can read more about that here:
https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge/

**Comment by syahid246** [comment]
> @syahid246 Just a heads up that IE will reach its full end-of-life on June 15, 2022, at which point lots of things will start to break for IE users because even Microsoft will not be supporting the browser anymore.


No, actually I use IE only to test whether my code is compatible with IE, if so, usually users who use HP can appear and function properly.
