### ISSUE TITLE
Arbitrary values work but arbitrary properties does not work (SvelteKit)

### ISSUE THREAD

**Issue by DoisKoh** [tailwindlabs/tailwindcss#8005]
**What version of Tailwind CSS are you using?**

For example: v3.0.23

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: SvelteKit (official example)

**What version of Node.js are you using?**

For example: v16.14.2

**What browser are you using?**

For example: Chrome

**What operating system are you using?**

For example: Windows

**Reproduction URL**

https://github.com/DoisKoh/tailwind-css-svelte-arbitrary-properties

**Describe your issue**

Tailwind CSS's arbitrary properties does not work with SvelteKit.

`npm install` then `npm run dev` the project and view the page - the border is 15px and the color is not red.

**Comment by adamwathan** [comment]
Hey! The problem is the space in `[color: red]`. Classes can't have spaces in them or the browser will treat it as two separate classes.

Change it to `[color:red]` and it works 👍🏻

**Comment by DoisKoh** [comment]
Haha... oh god there's 4 hours of my life I'll never get back... thanks.
