### ISSUE TITLE
Arbitrary font-family with quotes not working properly

### ISSUE THREAD

**Issue by dcastil** [tailwindlabs/tailwindcss#8012]
**What version of Tailwind CSS are you using?**

v3.0.23

**What build tool (or framework if it abstracts the build tool) are you using?**

Tailwind CSS playground

**What version of Node.js are you using?**

not applicable

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/KDujkzjaXO

**Describe your issue**

When using arbitrary values for the font-family class, I noticed that their CSS is not generated when I use multiple font-families and at least one of them is quoted. All of these following examples should work, but some of them don't:
- `font-[arbitrary]`: ✅ 
- `font-['arbitrary_with_space']`: ✅ 
- `font-[arbitrary,arbitrary2]`: ✅ 
- `font-[arbitrary,'arbitrary_with_space']`: ❌
- `font-['arbitrary_with_space','arbitrary_2']`: ❌

**Comment by thecrypticace** [comment]
Hey! We've rewritten our default class candidate extractor and it should allow arbitrary values with mixed quotes. Would you mind giving the insiders build a test and make sure that you're seeing what you expect? `npm install tailwindcss@insiders` — thanks!

**Comment by dcastil** [comment]
Just tried it out and it works! Thanks for the fix! 🙏
