### ISSUE TITLE
Can't whitelist keyframes 

### ISSUE THREAD

**Issue by hta218** [tailwindlabs/tailwindcss#8014]
**What version of Tailwind CSS are you using?**
3.0.23

**What build tool (or framework if it abstracts the build tool) are you using?**
Remix

**What version of Node.js are you using?**
14.x

**What browser are you using?**
Chrome

**What operating system are you using?**
macOS

**Describe your issue**
With the new `content` config in the 3.x version. How can we whitelist the keyframes?

I have added new keyframes like this: 
```js
{
  content: [fromRoot('./app/**/*.+(js|ts|tsx|mdx|md|css)')],
  theme: {
    extend: {
      keyframes: {
        'slideUp': {
          from: { height: '100%' },
          to: { height: 0 },
        },
        'slideDown': {
          from: { height: 0 },
          to: { height: '100%' },
        },
      },
    }
  }
}
```

And use them inside a CSS file (not by using an animation class!) like this:
```css
.my-div {
  animation: slideDown 300ms ease forwards;
}
```

But the keyframes definition doesn't show up in the `tailwind.css` file? How can I safelist those keyframes?

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

Right now the keyframes are part of the `animation` plugin, therefore you can safelist the animation itself which will include the keyframes. https://play.tailwindcss.com/wdyCm3WRPj?file=config

If you don't want to include the animation itself, then you can also move your keyframes to the css file without any layers: https://play.tailwindcss.com/aTve5K34Oq?file=css

**Comment by hta218** [comment]
Hey @RobinMalfait! Thank you for the answer!

I know this. But actually, I don't have a `tailwind.css` file

This is how I'm generating the CSS: `tailwindcss -o ./app/styles/tailwind.css`
