### ISSUE TITLE
I have content declared but getting "The `content` option in your Tailwind CSS configuration is missing or empty"

### ISSUE THREAD

**Issue by purejgleason** [tailwindlabs/tailwindcss#8029]
**What version of Tailwind CSS are you using?**

2.2.17

**What build tool (or framework if it abstracts the build tool) are you using?**

Rollup/Vite

**What version of Node.js are you using?**

18-pre (16)

**What browser are you using?**

Chrome/Firefox

**What operating system are you using?**

MacOS

**Describe your issue**

I have a package with 

```
"dependencies": {
    "@tailwindcss/forms": "0.5.0",
    ...
    "postcss": "^8.2.13",
    "tailwindcss": "latest",
  },
```

and a config like this...

```
// tailwind.config.mjs
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  ...
}
```

But when I run `eslint --fix "**/*.js" "**/*.vue"` , I get...

warn - The `content` option in your Tailwind CSS configuration is missing or empty.
warn - Configure your content sources or your generated CSS will be missing styles.
warn - https://tailwindcss.com/docs/content-configuration

I am confused because I have content declared.

**Comment by adamwathan** [comment]
Right now your Tailwind config has to be a CommonJS file, we don't support ESM config files at the moment so what's happening is Tailwind is completely ignoring your config file. The file should be called `tailwind.config.js` and should use `module.exports`, not `export default`.

Possible we'll support ESM in the future 👍🏻

**Comment by purejgleason** [comment]
Confirmed that this is an issue with `eslint` and the warning does not show up during a normal run.

**Comment by ViniAraujo99** [comment]
> ```
> // tailwind.config.mjs
> 
> safelist: [/^bg-/, /^text-/, /^border-/]
> ```
> 
> ```
> warn - Regular expressions in `safelist` work differently in Tailwind CSS v3.0.
> warn - Update your `safelist` configuration to eliminate this warning.
> warn - https://tailwindcss.com/docs/content-configuration#safelisting-classes
> ```
> 
> ```
> safelist: [
>     {
>       pattern: /^bg-/
>     },
>     {pattern: /^text-/},
>     {pattern: /^border-/}
>   ],
> ```
> 
> Doesn't so it is clearly seeing the file

Works for my, thx o/

**Comment by Msolmaz4** [comment]
- The `content` option in your Tailwind CSS configuration is missing or empty.
warn - Configure your content sources or your generated CSS will be missing styles.
warn - https://tailwindcss.com/docs/content-configuration
 ✓ Compiled / in 3.5s (510 modules)

**Comment by luchillo17** [comment]
Another thing that could happen is if you have a monorepo, the root of the project is not the root of the tailwind app, so you need to prepend the `__dirname` to the globs and config file path:
```mjs
// astro.config.mjs
import tailwind from '@astrojs/tailwind';
import { defineConfig } from 'astro/config';
import { join } from 'node:path';

// https://astro.build/config
export default defineConfig({
  root: import.meta.dirname,
  outDir: '../../dist/apps/portfolio',
  integrations: [
    tailwind({
      configFile: join(import.meta.dirname, './tailwind.config.mjs'),
    }),
  ],
});
```
```mjs
// tailwind.config.mjs
import { join } from 'node:path';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    join(__dirname, './src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'),
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};

```
