### ISSUE TITLE
after running npm install -D tailwindcss command , package.json and package-lock.json files are not created in apple m1 macbook pro...i'm using vs code for this purpose and all my softwares are updated !

### ISSUE THREAD

**Issue by ashusnapx** [tailwindlabs/tailwindcss#8031]
**What version of Tailwind CSS are you using?**

For example: v2.0.4

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: postcss-cli 8.3.1, Next.js 10.0.9, webpack 5.28.0

**What version of Node.js are you using?**

For example: v12.0.0

**What browser are you using?**

For example: Chrome, Safari, or N/A

**What operating system are you using?**

For example: macOS, Windows

**Reproduction URL**

A Tailwind Play link or public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.

**Describe your issue**

Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead.

**Comment by adamwathan** [comment]
Closing as the issue template was ignored.
