### ISSUE TITLE
utility classes do not apply to .jsx files(components) in Next JS 

### ISSUE THREAD

**Issue by hampak** [tailwindlabs/tailwindcss#8033]
**What version of Tailwind CSS are you using?**
-> @latest, 3.0.23

For example: v2.0.4

**What build tool (or framework if it abstracts the build tool) are you using?**
-> Next JS (version 12.1.4)
-> React version (latest - 18)

For example: postcss-cli 8.3.1, Next.js 10.0.9, webpack 5.28.0

**What version of Node.js are you using?**
-> 16.14.2

For example: v12.0.0

**What browser are you using?**
-> Chrome

For example: Chrome, Safari, or N/A

**What operating system are you using?**
-> Windows

For example: macOS, Windows

**Reproduction URL**
**_-> Please do not close this bug report. I cannot provide a reproduction URL right now (due to some reasons). I'm using a cloud ide service "Goorm ide". I'll explain as in much detail as possible. Please HELP!_**

**Describe your issue**
After creating a Next app, and creating the config files, I change the code in tailwind.config.js
`
content: [
 "./pages/**/*.{js, jsx}",
 "./components/**/*.{js, jsx}"
]
`

After doing this, I create a components folder, add a component with the **file name ending in .jsx**. However, the tailwind utility classes do not change the styles in the said .jsx file (and yes, I added @tailwind base, components, utilities in the globals styles file). However, if I change the said component's name ending in .js (for example, NavBar.jsx -> NavBar.js) the style applies... I don't know why this is happening. I think tailwind isn't applying styles to .jsx files.

I found a workaround where I manually add it in the config file like this:
`content: [
 "./pages/**/*.{js, jsx}",
 "./components/**/*.{js, jsx}",
"./components/NavBar.jsx"
]
`

If I manually add jsx files specifically by their name, then the styles will apply to it. However, if I don't add the .jsx file in the config file, it won't get applied and I would have to change the file name to NavBar.js

I double, triple-checked for typos and other mistakes but none!

Please HELP!

I installed postcss and autoprefixer too

**Comment by adamwathan** [comment]
Hey! Your glob is invalid, you need to remove the spaces:

```diff
- content: [ "./pages/**/*.{js, jsx}", "./components/**/*.{js, jsx}" ]
+ content: [ "./pages/**/*.{js,jsx}", "./components/**/*.{js,jsx}" ]
```

That's the way we show it in the docs as well.

In the future please open this as a discussion in the "Help" category unless you are absolutely sure you've discovered a bug in the framework.

**Comment by hampak** [comment]
Opp! Sorry and thanks for pointing that out! I can't believe I missed that... Cheers!
