### ISSUE TITLE
MUI StyledEngineProvider with TailwindCSS Base CSS cause Button styling issues

### ISSUE THREAD

**Issue by stephyswe** [tailwindlabs/tailwindcss#8075]
**What version of Tailwind CSS are you using?**
v. 3.0.23

**What build tool (or framework if it abstracts the build tool) are you using?**
react-react-app - 
"react": "^17.0.2",

**What version of Node.js are you using?**
v16.14.2

**What browser are you using?**
Chrome

**What operating system are you using?**
Windows 10

**Reproduction URL**
Making two URL's one with working example, one with bug introduced. 
Github: https://github.com/stephyswe/reproduction-url-tailwind-mui-StyledEngineProvider-issue-fix

Github Commits:
bug(commit 3): https://github.com/stephyswe/reproduction-url-tailwind-mui-StyledEngineProvider-issue-fix/commit/16d3c3445d74cf805f6c8d5808a2405ed8103671
working (commit 4): bug: https://github.com/stephyswe/reproduction-url-tailwind-mui-StyledEngineProvider-issue-fix/commit/f18a555652b37ab82ca7b28ee2ae29835699e2eb

website (bug-commit 3):  https://reproduction-url-tailwind-mui-styled-engine-provider-issue-fix.vercel.app/
website (fix-commit 4):  https://reproduction-url-tailwind-mui-styled-engine-provider-issue.vercel.app/

As we know. 

A Tailwind Play link or public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.

**Describe your issue**
It's very simple. 

TailwindCSS and MUI used in React Project cause styling issue. The style issue appear when adding the so-called StyledEngineProvider from MUI. The issue happens because StyledEngine lower the prioritization of css classes, and let tailwind base class overwrite the button class. 

More about MUI StyledEngine (CSS injection order):
https://mui.com/material-ui/guides/interoperability/#css-injection-order

Working:
```
ReactDOM.render(
  <React.StrictMode>
      <App />
  </React.StrictMode>,
  document.getElementById("root")
);
```

Not working:
```
import { StyledEngineProvider } from "@mui/material";

ReactDOM.render(
  <React.StrictMode>
    <StyledEngineProvider injectFirst>
      <App />
    </StyledEngineProvider>
  </React.StrictMode>,
  document.getElementById("root")
);
```

Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead.

**Comment by adamwathan** [comment]
Hey! What you’re describing sounds to me like it would be an issue even if you were just hand writing CSS instead of using Tailwind, and that it’s just a collision of two conflicting sets of styles.

Unfortunately it’s impossible to eliminate these issues completely on our end, all we can recommend is that you be deliberate about which order your CSS is loaded in. We split Tailwind into the ‘base’, ‘components’, and ‘utilities’ layers to give you the control to inject your own custom styles in between them, but that’s really all we can do.

You can disable `preflight` in your `corePlugins` configuration to remove Tailwind’s base styles entirely which might be the best way to use it in your case if you only need the utilities.

**Comment by stephyswe** [comment]
> Hey! What you’re describing sounds to me like it would be an issue even if you were just hand writing CSS instead of using Tailwind, and that it’s just a collision of two conflicting sets of styles.
> 
> Unfortunately it’s impossible to eliminate these issues completely on our end, all we can recommend is that you be deliberate about which order your CSS is loaded in. We split Tailwind into the ‘base’, ‘components’, and ‘utilities’ layers to give you the control to inject your own custom styles in between them, but that’s really all we can do.
> 
> You can disable `preflight` in your `corePlugins` configuration to remove Tailwind’s base styles entirely which might be the best way to use it in your case if you only need the utilities.

Hi. 

I opened the issue only to showcase this behavior. It has nothing to do with the combability of tailwind CSS nor mui. To inform that it existed. Should I remove the issue thread I can do that. Is that desirable?
