### ISSUE TITLE
Variables as a color?

### ISSUE THREAD

**Issue by Gedewon** [tailwindlabs/tailwindcss#8092]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/8041

<div type='discussions-op-text'>

<sup>Originally posted by **mxcdh** April  4, 2022</sup>
tailwind not scanning for variable input at compile-time, even if we provide it with a lookup table as an object.

My code:
![image](https://user-images.githubusercontent.com/98115983/161549770-1c0fea6a-c6b5-4c93-82dc-4e8ba17fe3c5.png)
</div>

**Comment by adamwathan** [comment]
Closing in favor of original discussion, everything looks like it’s working as expected here, please review docs on using dynamic classes.
