### ISSUE TITLE
Facing less-loader build error after upgrading tailwindCSS to v3

### ISSUE THREAD

**Issue by rohit1101** [tailwindlabs/tailwindcss#8096]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/8095

<div type='discussions-op-text'>

<sup>Originally posted by **rohit1101** April 12, 2022</sup>
These are the packages that i am using for the project:

- "@storybook/addon-actions": "^6.4.21",
- "@storybook/addon-essentials": "^6.4.21",
- "@storybook/addon-links": "^6.4.21",
- "@storybook/addon-postcss": "^2.0.0",
- "@storybook/addon-viewport": "^6.4.21",
- "@storybook/builder-webpack5": "^6.4.21",
- "@storybook/manager-webpack5": "^6.4.21",
- "@storybook/react": "^6.4.21",

I am using storybook on a gatsby project along with tailwindCSS v3.

Current Version of tailwindCSS, postcss and gatsby:

- "tailwindcss": "^3.0.23",
- "postcss": "^8.4.12"
- "postcss-import": "^14.0.0"
- "postcss-preset-env": "^7.4.3"
- "gatsby": "^4.0.0",

I am getting storybook build errors after migrating **tailwindCSS from v2 to v3.**

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/37110560/162946848-f2cb5063-661b-4587-8fb7-d165396a4934.png">
</div>

**Comment by RobinMalfait** [comment]
Closing in favor of original discussion. Please also attach a reproduction repo to your discussion so that debugging becomes easier.
