### ISSUE TITLE
🐛 Unnecessary classes are output

### ISSUE THREAD

**Issue by k-utsumi** [tailwindlabs/tailwindcss#8102]
<details>
<summary>Environments</summary>

**What version of Tailwind CSS are you using?**

v3.0.24

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss v8.4.7, webpack v5.72.0

**What version of Node.js are you using?**

v16.13.2

**What browser are you using?**

N/A

**What operating system are you using?**

macOS
</details>

**Reproduction URL**

- https://play.tailwindcss.com/KvFiBdkhw3  
  To check the output of 2 characters,  
  change `prefix:'tw_-'` to `prefix:'tw-'` in `Config` tab.
- https://play.tailwindcss.com/00iNAwt2JZ

**Describe your issue**

As the title says.
Unnecessary classes should not be output.

**Comment by thecrypticace** [comment]
Thanks for the report! This one was super weird. Took quite a while to debug it but I tracked it down to an issue of how we handled detection of utilities that might be negatives. I've fixed this in #8121.

**Comment by k-utsumi** [comment]
Thanks for the quick response 🏎️💨
