### ISSUE TITLE
Ring Offset Transparent Should Show Background

### ISSUE THREAD

**Issue by vhscom** [tailwindlabs/tailwindcss#8128]
**What version of Tailwind CSS are you using?**

For example: v3.0.24

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: postcss-cli 8.4.12, SvelteKit beta.300 something

**What version of Node.js are you using?**

For example: v17.x

**What browser are you using?**

For example: Arc by The Browser Company (just kidding, it's Brave)

**What operating system are you using?**

For example: macOS

**Reproduction URL**

The bug is demonstrated with a workaround here:
https://github.com/tailwindlabs/tailwindcss/discussions/5257#discussioncomment-1336456

**Describe your issue**

Implementation details aside, a ring offset with a color of `transparent` should show through to the background color. Is there a way to make this happen without nesting elements as shown in the repro? If not, could there be?

**Comment by adamwathan** [comment]
Hey! Unfortunately just no way to do this with CSS that is simple enough to be able to expose with a utility. Not a bug, this works the way it was designed to work, just a limitation of CSS.

The `outline` property is better for this sort of thing but unfortunately custom border radiuses have only recently started to be respected by the `outline` property (and only in Chrome and Firefox, not in Safari). Hopefully one day we can just start using that!
