### ISSUE TITLE
tailwindcss svg color fill not working on next js with typescript 

### ISSUE THREAD

**Issue by sacsbrainz** [tailwindlabs/tailwindcss#8130]
**"tailwindcss": "^3.0.7"**

**What build tool (or framework if it abstracts the build tool) are you using?**

"postcss": "^8.4.5", "prettier": "^2.5.1", "prettier-plugin-tailwindcss": "^0.1.1", "tailwindcss": "^3.0.7", "typescript": "4.5.4"

**What version of Node.js are you using?**

v16.14.2

**What browser are you using?**

Mozila firefox

**What operating system are you using?**

Ubuntu 20.04

**Reproduction URL**
[Tailwind play ground](https://play.tailwindcss.com/OMhGipoEe2)
**Describe your issue**
this same code that works above only works on html
when i try to use it in a next js project with typescript it does not fill color and the only difference is the change from "class" to "className" as required but it still refused to fill

**Comment by adamwathan** [comment]
Hey! Please create a new issue that includes a reproduction showing it *not* working so we can clone it down and troubleshoot it in the fastest possible way. 

Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
