### ISSUE TITLE
Make sure it is defined within a `@layer` directive.

### ISSUE THREAD

**Issue by Hongbusi** [tailwindlabs/tailwindcss#8140]
**What version of Tailwind CSS are you using?**

v3.0.24

**What build tool (or framework if it abstracts the build tool) are you using?**

``` json
"postcss": "^8.4.12",
"vite": "^2.9.1"
```

**What version of Node.js are you using?**

v14.18.1

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

[Demo](https://stackblitz.com/edit/vitejs-vite-th8rtp?file=src/App.vue)

**Describe your issue**

The `p-` class does not exist. If `p-` is a custom class, make sure it is defined within a `@layer` directive in less.

**Comment by adamwathan** [comment]
Hey! This looks specific to Less, if you remove `lang="less"` it works. Less must be compiling it in a way where it is either removing the `[20px]` part before Tailwind processes it, or adding a space after the `p-` part.

https://stackblitz.com/edit/vitejs-vite-rufwr3?file=src/App.vue

Going to close as not a Tailwind issue unfortunately, nothing we can really do here. In general we recommend avoiding using any preprocessor with Tailwind:

https://tailwindcss.com/docs/using-with-preprocessors

**Comment by Hongbusi** [comment]
Thank you!
