### ISSUE TITLE
Flexible data table (resizable columns)

### ISSUE THREAD

**Issue by lordisp** [tailwindlabs/tailwindcss#8161]
I turn this now ito an issue. Would be cool to have a tw class for this.

### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/5688

<div type='discussions-op-text'>

<sup>Originally posted by **lordisp** October  4, 2021</sup>
Does anyone have an example on how to resize table columns?

I found this: https://codepen.io/adam-lynch/pen/GaqgXP but would love a kind of Tailwind/AplineJS combo-thing</div>

**Comment by adamwathan** [comment]
This is not a bug in Tailwind, please don’t abuse issues.
