### ISSUE TITLE
Custom Breakpoint overriding standard breakpoints in unexpected manner

### ISSUE THREAD

**Issue by OwnageBanana** [tailwindlabs/tailwindcss#8194]
**What version of Tailwind CSS are you using?**
3.0.24 (cdn in Minimal example)

**What build tool (or framework if it abstracts the build tool) are you using?**

    "postcss": "^8.4.6",
    "webpack": "^5.69.1"

**What version of Node.js are you using?**

    "node": "^16"

**What browser are you using?**

Chrome, firefox

**What operating system are you using?**

Windows

**Reproduction URL**

https://play.tailwindcss.com/B1Em9tnnvq

**Describe your issue**

The issue is, that the `xs` breakpoint in the playground link will overwrite the `lg` breakpoint, cascading over it. What I would expect to happen is that when the screen width is 1024px (the `lg` breakpoint) that the `lg` breakpoint would take priority. 

In the link I also added an example of it working as expected with the `sm` breakpoint instead of a `xs` breakpoint demonstrating how I would expect it to behave.

**Comment by bradlc** [comment]
Hey @OwnageBanana. This is explained in the documentation along with the solution: https://tailwindcss.com/docs/screens#adding-smaller-breakpoints – I hope that helps!

Side note: the Play CDN (cdn.tailwindcss.com) does not work on Tailwind Play, nor is it required. You can use the "Config" tab to customise the Tailwind config 👍

**Comment by OwnageBanana** [comment]
Thanks for taking a look at my report and the help with fixing my confusion! it seems I had extended the screen breakpoints rather than overwriting them.

I will just take this moment to add to this comment to provide a working example for any future readers:

https://play.tailwindcss.com/frie01h1Sp
