### ISSUE TITLE
scrollbar support

### ISSUE THREAD

**Issue by regnaio** [tailwindlabs/tailwindcss#8200]
The first example in the official docs https://tailwindcss.com/docs/background-attachment uses

```html
<div class="... overflow-y-scroll scrollbar:!w-1.5 scrollbar:!h-1.5 scrollbar-track:!bg-slate-100 scrollbar-thumb:!rounded scrollbar-thumb:!bg-slate-300 ..." ...>
      ...
</div>
```

(See `Elements` tab in Console)

Where does `scrollbar:`, `scrollbar-track:`, `scrollbar-thumb:` come from? There's no mention of these in the official docs, and it seems we cannot use these in our own projects...

**Comment by bradlc** [comment]
Hey @regnaio. The `scrollbar` variants are added by a custom plugin that you can see in the [Tailwind config](https://github.com/tailwindlabs/tailwindcss.com/blob/0d3dc6b2a40fade2c40689bd982566efa88f7551/tailwind.config.js#L264-L266) for the site. Check out the Tailwind CSS documentation for more information on creating your own variants: https://tailwindcss.com/docs/plugins#adding-variants

**Comment by relagio** [comment]
why not add this as default?
