### ISSUE TITLE
Bug with multiple @apply in one parent

### ISSUE THREAD

**Issue by psucodervn** [tailwindlabs/tailwindcss#8203]
Consider the line 312 here
https://github.com/tailwindlabs/tailwindcss/blob/1cc1ace14260f13ba97123c35aeb826edf8cca08/src/lib/expandApplyAtRules.js#L312-L314

Should it be
```js
let candidates = (perParentApplies.get(apply.parent) || [[]])[0];
```
instead?

**Comment by thecrypticace** [comment]
It should be `let candidates = []` since we've just initialized perParentApplies and are then immediately overwriting that key in perParentApplies. I pushed the change for this to `master`. The existing code isn't a problem — it's just unnecessary. Thanks for pointing it out 🤦 

As for multiply uses of `@apply` in a single rule we handle that because we split one rule into 2 or more whenever we encounter an `@apply`.

**Comment by psucodervn** [comment]
Hi @thecrypticace , thanks for the quick response. Yeah, I know that the lib itself works well with the current code (because that rules with multiple @apply were already split, as you said). But other libraries may use this function without notice about this, and it would cause some related issues.

For example, in my case, I'm using [Tailwind CSS IntelliSense](https://github.com/tailwindlabs/tailwindcss-intellisense) extension in vscode. This extension import and use the `expandApplyAtRules` function (https://github.com/tailwindlabs/tailwindcss-intellisense/blob/master/packages/tailwindcss-language-server/src/server.ts#L662). Then when I'm including a plugin that have a rule that contains multiple `@apply` (i.e. `@vechaiui/core`), the extension will failed to process.

My example `tailwind.config.js`:
```js
module.exports = {
  ...
  plugins: [
    require('@vechaiui/core'),
  ],
}
```

Your new code (`let candidates = []`) will let the extension continuing to execute, but it will eliminate other `@apply`s in a rule that have multiple of them.

**Comment by thecrypticace** [comment]
Understood. In this case that would be a bug in the language server that needs to be addressed.

**Comment by thecrypticace** [comment]
@psucodervn I just did a little test with the intellisense extension and so far am not having problems. It handles the multiple applies as expected. Can you prep a small reproduction of what you're seeing? It'd be much appreciated!

Plugin:
![Screen Shot 2022-04-27 at 09 47 51](https://user-images.githubusercontent.com/614993/165533522-fa114f3f-0994-4769-a58d-4a8f7c1fba21.png)

Popup from intellisense:
![Screen Shot 2022-04-27 at 09 45 19](https://user-images.githubusercontent.com/614993/165533276-4940c8f6-27f5-4c8d-9bfc-230c2ed441b0.png)

**Comment by psucodervn** [comment]
Hi @thecrypticace, thanks for the investigation. Here is a minimal project repo to reproduce the issue: https://github.com/psucodervn/tailwind-intellisense-issue.
 
Hope it helps.

**Comment by thecrypticace** [comment]
I've pushed a fix and it should be in our insiders build in a few minutes. I used something fairly close to what you wrote so I credited you as a co-author. Thanks again for the persistence and I'm so sorry for all the confusion!
