### ISSUE TITLE
`border-current` in dark mode will not match the expected text color

### ISSUE THREAD

**Issue by benjamintd** [tailwindlabs/tailwindcss#8235]
**What version of Tailwind CSS are you using?**

v3.0.24

**What build tool (or framework if it abstracts the build tool) are you using?**

Next.js@latest

**What version of Node.js are you using?**

v16.13.0

**What browser are you using?**

Chrome@latest

**What operating system are you using?**

macOS

**Reproduction URL**

Head to https://play.tailwindcss.com/4SFSkFTMif and toggle dark mode. Tailwind Play dark mode will not toggle the preview's dark mode. You'll need to toggle it from the Chrome devTools, for instance. I used the "Automatic dark mode" option in the devTools: 
<img width="564" alt="image" src="https://user-images.githubusercontent.com/11202803/165977843-87c0cb2b-d448-42ac-bdfb-e340154c8b07.png">

**Describe your issue**

When toggling dark mode, the `border-current` property will not switch the border color to match the text color. I don't know if this is an issue with Tailwind or the way the browser interprets the generated CSS. 

(PS: Thanks for the amazing library, Tailwind UI, and the rest !)

**Comment by adamwathan** [comment]
Hey! I can't reproduce this — for me the border color changes to match the text:

https://play.tailwindcss.com/l2ftcQDqZ9

https://user-images.githubusercontent.com/4323180/165985328-092cb7b8-2d29-4cb9-b141-f0ec85abc06a.mov

Can you create a video or anything?

**Comment by benjamintd** [comment]
Hi @adamwathan, thanks for the quick reply. Here is the video using the reproduction you sent me: 
https://user-images.githubusercontent.com/11202803/165990510-d6286ef4-442c-4b7c-929a-c5e63406cca7.mov

This might be a bug of Chrome itself? I'm on `Version 100.0.4896.127 (Official Build) (x86_64)`.

**Comment by benjamintd** [comment]
Indeed. I looked up how to emulate dark mode, and that checkbox showed up among the first results. It seems though that "Automatic dark mode" is Chrome's best effort to emulate dark mode on sites that do not support it: https://developer.chrome.com/blog/auto-dark-theme/

I'll close this issue, thanks again for your help.
