### ISSUE TITLE
Custom breakpoints breaking Grid layouts 

### ISSUE THREAD

**Issue by DerickMasai** [tailwindlabs/tailwindcss#8237]
Hello,

I created custom breakpoints (to cater to tiny handhelds) in the config file as per the docs. They worked flawlessly till I noticed random issues with my styling; the weird thing is when I force them i.e using `!important` they work just fine. Just pinpointed the issue right now: apparently, when I use these custom breaks anywhere on a page I'm using grid the styling above the custom break no longer functions.

Example (In this case the `xxs` break is a custom break I made that caters to `@media (min-width: 372px)`):

`<div class="mt-8 w-full grid grid-cols-1 xxs:grid-cols-2 md:grid-cols-4 gap-8 xxs:gap-6 md:gap-8">`

So, in this example, `grid-cols-4` will not be compiled at all while `gap-8` works just fine. Notice though that both CSS styles use the custom break `xxs` but for some reason any responsive grid styling above the custom break simply doesn't work. **However**, when I use `!` it works again i.e !grid-cols-4 like below and the code suddenly works again.

`<div class="mt-8 w-full grid grid-cols-1 xxs:grid-cols-2 md:!grid-cols-4 gap-8 xxs:gap-6 md:gap-8">`

Please note that anywhere else I use the breaks they work flawlessly except with grids so that can be ruled out. 

Lastly, let me just say I love Tailwind and can't thank you guys enough for creating and working on this. Let me know if I can assist further and any corrections I can make as this is my first GitHub issue submission. Good day.

**Comment by DerickMasai** [comment]
Hi guys, apologies for the misleading remark "_Notice though that both CSS styles use the custom break xxs but for some reason any responsive grid styling above the custom break simply doesn't work._". Just tested this again and all the styles are breaking above the custom break so let me close this issue and test it out on my end. Apologies for any inconvenience.

**Comment by sprajapat770** [comment]
@DerickMasai  did you found any solution for that? md:gap-8 is not working at my end yet.
