### ISSUE TITLE
The color-adjust shorthand is currently deprecated

### ISSUE THREAD

**Issue by frbuceta** [tailwindlabs/tailwindcss#8250]
**What version of Tailwind CSS are you using?**

v3.0.24

**What build tool (or framework if it abstracts the build tool) are you using?**

Nuxt3 with Vite

**What version of Node.js are you using?**

18.0.0

**What browser are you using?**

Chrome

**What operating system are you using?**

Linux

**Reproduction URL**

It is not a problem with TailwindCSS but with a property that is deprecated.

**Describe your issue**

```
 WARN  [vite:css] Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
1  |  @tailwind base;
   |   ^
2  |  @tailwind components;
3  |  @tailwind utilities;
```

**Comment by joshuajung** [comment]
This seems to have been caused by [this change](https://github.com/postcss/autoprefixer/commit/51b991c6175fe5e0f90e20041e10441df1434670) in autoprefixer 10.4.6.

**Comment by frbuceta** [comment]
I confirm, I have downloaded to version 10.4.5 and it has been solved

**Comment by tianyingchun** [comment]
i faced the seem issue too.

**Comment by Vannsl** [comment]
Same issue as we updated to autoprefixer 10.4.6.

**Comment by kb1995** [comment]
I started getting the same warning as of this morning after I upgraded to 10.4.6

**Comment by seabasss** [comment]
Is this still the official solution for this problem? `npm install autoprefixer@10.4.5 --save-exact`
