### ISSUE TITLE
Alert message: about Replace color-adjust

### ISSUE THREAD

**Issue by iappaPedroza** [tailwindlabs/tailwindcss#8277]
[vite:css] Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.

Got this message when run project in dev mode
[vite:css] Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
1  |  @tailwind base;
   |   ^
2  |  @tailwind components;
3  |  @tailwind utilities; (x3)
Somebody got the same issue?

**Comment by adamwathan** [comment]
Hey! Upgrade to the latest version of `@tailwindcss/forms` and it'll resolve the warning 👍🏻 

https://github.com/tailwindlabs/tailwindcss-forms/pull/115

**Comment by thinkjrs** [comment]
I also had to pin `autoprefixer` to `10.4.5` to get the errors to go away, in case it helps others.

**Comment by tiagobarros01** [comment]
> Hey! Upgrade to the latest version of `@tailwindcss/forms` and it'll resolve the warning 👍🏻
> 
> [tailwindlabs/tailwindcss-forms#115](https://github.com/tailwindlabs/tailwindcss-forms/pull/115)

This solve my problem!

**Comment by DanChristos** [comment]
Same issue here with me. 
`"autoprefixer": "^10.4.5"` and `"@tailwindcss/forms": "^0.5.1"`.
```
[vite:css] Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
1  |  @tailwind base;
   |   ^
2  |  @tailwind components;
3  |  @tailwind utilities; (x6)
```

**Comment by adamwathan** [comment]
You need to update `@tailwindcss/forms` to the latest version.

**Comment by jjaimealeman** [comment]
> You need to update `@tailwindcss/forms` to the latest version.

Perfect, that worked for me!

```
  "devDependencies": {
    "autoprefixer": "10.4.5",
    "postcss": "^8.4.13",
    "prettier": "^2.6.2",
    "prettier-plugin-tailwindcss": "^0.1.10",
    "tailwindcss": "^3.0.24",
    "vite": "^2.9.9",
    "vite-plugin-handlebars": "^1.6.0"
  },
  "dependencies": {
    "@alpinejs/intersect": "^3.10.2",
    "@tailwindcss/forms": "^0.5.2",
    "alpinejs": "^3.10.2",
    "flowbite": "^1.4.5",
    "tailwindcss-fluid-type": "^1.3.3"
  }
```

For anyone else getting stuck, `"autoprefixer": "10.4.7"` will bring the error message back, so stick with `10.4.5` 👍

**Comment by Pblfer** [comment]
> You need to update `@tailwindcss/forms` to the latest version.

these work for me

**Comment by Temepest74** [comment]
> > You need to update `@tailwindcss/forms` to the latest version.
> 
> Perfect, that worked for me!
> 
> ```
>   "devDependencies": {
>     "autoprefixer": "10.4.5",
>     "postcss": "^8.4.13",
>     "prettier": "^2.6.2",
>     "prettier-plugin-tailwindcss": "^0.1.10",
>     "tailwindcss": "^3.0.24",
>     "vite": "^2.9.9",
>     "vite-plugin-handlebars": "^1.6.0"
>   },
>   "dependencies": {
>     "@alpinejs/intersect": "^3.10.2",
>     "@tailwindcss/forms": "^0.5.2",
>     "alpinejs": "^3.10.2",
>     "flowbite": "^1.4.5",
>     "tailwindcss-fluid-type": "^1.3.3"
>   }
> ```
> 
> For anyone else getting stuck, `"autoprefixer": "10.4.7"` will bring the error message back, so stick with `10.4.5` 👍

thank you a lot, i was already getting fed up with this. i hope they fix it

**Comment by petertflem** [comment]
Worked when I downgraded autoprefixer to 10.4.5. Had @tailwindcss/form at 0.5.2.

**Comment by sheecegardezi** [comment]
yarn upgrade --latest

**Comment by wildyeast** [comment]
> yarn upgrade --latest

I have neither @tailwindcss/form nor autoprefixer installed. `yarn upgrade `removed the messages.

**Comment by sarjid** [comment]
**Add following line in package.json:**

If you’re using yarn:

"resolutions": {
    "autoprefixer": "10.4.5"
}
If you’re using npm:

"overrides": {
    "autoprefixer": "10.4.5"
}
