### ISSUE TITLE
`leading` property being overruled by `text-{size}` rules when using breakpoints

### ISSUE THREAD

**Issue by hood** [tailwindlabs/tailwindcss#8311]
**What version of Tailwind CSS are you using?**
3.0.24

**What build tool (or framework if it abstracts the build tool) are you using?**
NextJS 12.06, Parcel 2.4.1

**What version of Node.js are you using?**
v18

**What browser are you using?**
Chrome, Firefox

**What operating system are you using?**
Arch linux

**Reproduction URL**
Providing screenshots for now, will repro asap.

**Describe your issue**
Given the following code:
![image](https://i.imgur.com/p45um8t.png)

The following CSS rules get applied:
![image](https://i.imgur.com/h1sxkDc.png)

Making the `line-height` property set by `leading-none` overridden by the default `line-height` values defined for `text-{size}` classnames at specific breakpoints.

**Comment by adamwathan** [comment]
Hey! See previous issue: https://github.com/tailwindlabs/tailwindcss/issues/6504
