### ISSUE TITLE
Code conflicts exist

### ISSUE THREAD

**Issue by L3gacy03** [tailwindlabs/tailwindcss#8317]
![image](https://user-images.githubusercontent.com/53899720/167528384-926e161d-f56e-415d-af16-5a2fca0636ad.png)
![image](https://user-images.githubusercontent.com/53899720/167528432-217d3e40-90d7-407b-b3b9-9122ea515c20.png)

**Comment by adamwathan** [comment]
Hey! That’s not our website unfortunately, nothing we can do to fix that.
