### ISSUE TITLE
bg-color variable substitution issue

### ISSUE THREAD

**Issue by kdejaeger** [tailwindlabs/tailwindcss#8319]
Hello,

We are having an issue where `bg-${color}` is not being 'compiled' correctly, resulting in a lacking css.
Weirdly enough, when saving temporally as bg-green it works, ctrl-z and it still works. However after deleting .nextjs and node_modules, the css is not present. This could be due to next.js or how tailwind 'compiles' the css.

I made handy sandbox link demonstrating the issue:
https://codesandbox.io/s/naughty-turing-46y7w0?file=/pages/index.js

Any clue how I can work around this?

**Comment by zslabs** [comment]
You can't construct classnames dynamically https://tailwindcss.com/docs/content-configuration#class-detection-in-depth

**Comment by adamwathan** [comment]
Yep what @zslabs said 👍🏻

**Comment by kdejaeger** [comment]
Hello, I have refactored and updated the codesandbox example so it uses non-dynamic classnames. However, bg-yellow and bg-red still don't work. Why is that?
