### ISSUE TITLE
Base styles not applied to build.

### ISSUE THREAD

**Issue by ComputerCarl** [tailwindlabs/tailwindcss#8335]
As posted in [issue 7037](https://github.com/tailwindlabs/tailwindcss/issues/7037), the tag styles defined in `@layer base` do not make it to the build.

tailwind.css:
```
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
    html, body, #root {
        @apply min-h-screen;
        @apply bg-slate-400;
    }
}
```

Build command:
`npx tailwindcss -o ./release/css/tailwind-built.css`

Result (partial) only includes 1 `body` tag and 1 `html` tag and 0 `#root`:
```

html {
  line-height: 1.5;
  /* 1 */
  -webkit-text-size-adjust: 100%;
  /* 2 */
  -moz-tab-size: 4;
  /* 3 */
  -o-tab-size: 4;
     tab-size: 4;
  /* 3 */
  font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
  /* 4 */
}

/*
1. Remove the margin in all browsers.
2. Inherit line-height from `html` so users can set them as a class directly on the `html` element.
*/

body {
  margin: 0;
  /* 1 */
  line-height: inherit;
  /* 2 */
}

```

However, if I use Vite build, then the output css file does include a second `body` tag in the file, as well as the other tags from the base additions.
Partial:
```
y:none}html,body,#root{min-height:100vh;--tw-bg-opacity: 1;background-color:rgb(148 163 184 / var(--tw-bg-opacity))}*,:before,:after{--tw-translate-x: 0;--tw-translate-y: 0;--tw-rotate: 0;--tw-skew-x: 0;--tw-skew-y: 0;--tw-scale-x: 1;--tw-scale-y: 1;--tw-pan-x: ;
```

**Comment by adamwathan** [comment]
Hey! Please provide a reproduction, when I try to reproduce this it works as expected:

<img width="802" alt="image" src="https://user-images.githubusercontent.com/4323180/168163285-466ed8b6-e1f8-4387-bdfb-6b25f01105d3.png">

As mentioned in the issue template, we have a policy of closing issues that don't include reproductions, so if this is still an issue for you, please open a new issue but include a reproduction we can look at ❤️
