### ISSUE TITLE
Breakpoint specific container horizontal padding is not applying.

### ISSUE THREAD

**Issue by soorajkj** [tailwindlabs/tailwindcss#8408]
module.exports = {
  theme: {
    container: {
      padding: {
        DEFAULT: '1rem',
        sm: '2rem',
        lg: '4rem',
        xl: '5rem',
        '2xl': '6rem',
      },
    },
  },
};

This code is from the Tailwindcss v3.0.24 official documentation. but it is not working as expected and I also found that the bug is reported and fixed two years ago. It is still not working.

**Comment by adamwathan** [comment]
Hey! Copied that code here and it works perfectly: https://play.tailwindcss.com/btVBelSlYs

Closing since this all seems to work.

**Comment by soorajkj** [comment]
yes it's worked. Thanks for your support.

**Comment by kachkaev** [comment]
Interestingly, same issue here with `tailwindcss 3.3.2`. Could not get any padding working apart from DEFAULT 🤔
