### ISSUE TITLE
[Prettier Plugin] Add twig support

### ISSUE THREAD

**Issue by shekler** [tailwindlabs/tailwindcss#8478]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/8294

<div type='discussions-op-text'>

<sup>Originally posted by **JeanLucEsser** May  7, 2022</sup>
I was expecting to see the plugin work in .twig files as they are mainly just html.
But it looks like this works only on .html files unless I'm missing something.

I think it would make sense to make it work by default on every extension that contains some html such as twig or blade. But maybe that's not as obvious and/or simple as it seems.</div>

---

I strongly second this. I am working almost exclusively with Twig files in my team. We have been using the Headwind plugin before with VS Code, but with Tailwind v3 this doesn't work anymore.

To help with coding conventions in my team, adding Twig compatibility would be great.

**Comment by adamwathan** [comment]
Hey! We use issues for bug reports only. Please don’t convert discussions into issues when they aren’t bugs.
