### ISSUE TITLE
Tailwind not resolving `tailwind.config.cjs`

### ISSUE THREAD

**Issue by ekwoka** [tailwindlabs/tailwindcss#8543]
**What version of Tailwind CSS are you using?**

    "postcss": "^8.4.14",
    "tailwindcss": "^3.0.24",

**What build tool (or framework if it abstracts the build tool) are you using?**

Directly calling tailwind cli

**What version of Node.js are you using?**

v18.3.0

**What operating system are you using?**

macOS

**Describe your issue**

When setting the tailwind config to be `tailwind.config.cjs` the config is not found.

Discussion with others having same issue:  https://github.com/tailwindlabs/tailwindcss/discussions/7695
Original PR that added `.cjs` support: https://github.com/tailwindlabs/tailwindcss/pull/3181

**Comment by ekwoka** [comment]
Edit, looks like this is solved just not published yet.

https://github.com/tailwindlabs/tailwindcss/commit/6c63f67d20c433b5c7281e9e26744038ed41ccc2

**Comment by thecrypticace** [comment]
Hey! This should've been resolved for you in the v3.1 release. If you have any issues with it though please let us know! Thanks for reporting it!
