### ISSUE TITLE
There are problems with the latest custom variant escape symbol resolution,He can't generate it correctly

### ISSUE THREAD

**Issue by jipika** [tailwindlabs/tailwindcss#8573]
![image](https://user-images.githubusercontent.com/59040157/173014385-d5b88cfd-c7b3-4127-81d6-aa44b1513915.png)
![image](https://user-images.githubusercontent.com/59040157/173015379-b2b61972-6590-4d08-aaa3-019b8527c01c.png)
Nothing happened

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

I have to close this as a reproduction was not provided and the issue template has not been followed. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction — a [Tailwind Play](https://play.tailwindcss.com) if the issue can be reproduced there, or a GitHub repository where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
