### ISSUE TITLE
CLI --watch does not resolve imports

### ISSUE THREAD

**Issue by SimonWpt** [tailwindlabs/tailwindcss#8579]
I use [Tailwind Windows Version 3.1.1](https://github.com/tailwindlabs/tailwindcss/releases/download/v3.1.1/tailwindcss-windows-x64.exe)

**Describe your issue**
I have a file called app.css with the content:
```css
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
@import "./test.css";
```
I start tailwind in watch modus:
`.\tailwind.exe  -i ./css/app.css -o ./css/app.min.css -w`

Instead of merging the compiled test.css, tailwind leave it as an import command.
```css
@import "./test.css";
```
testcase: [test.zip](https://github.com/tailwindlabs/tailwindcss/files/8877487/test.zip)

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #8580, and will be available in the next release (probably later today).

You can already try it by using the insiders build `npm install tailwindcss@insiders`.
