### ISSUE TITLE
Error TS2307: Cannot find module './generated/CorePluginList'

### ISSUE THREAD

**Issue by maximeg** [tailwindlabs/tailwindcss#8586]
**What version of Tailwind CSS are you using?**

v3.1.1

**What build tool (or framework if it abstracts the build tool) are you using?**

Typescript type checking with `tsc`

**What version of Node.js are you using?**

For example: v18.3.0

**What operating system are you using?**

Ubuntu 20.0 LTS

**Describe your issue**

In our project, we run tsc to typecheck.
Even if not used directly in my codebase, typescript reads the type definitions of tailwindcss.

Since 3.1.1, doing so on our Github Actions CI, we run into a `Error: node_modules/tailwindcss/types/config.d.ts(1,37): error TS2307: Cannot find module './generated/CorePluginList' or its corresponding type declarations.` error.

Indeed, by doing a ls of the directory, we see that the file is  generated as`corePluginList.d.ts`.

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/252162/173059510-3d3d66ea-0a94-4cd0-a312-8a20999f7c64.png">

PS: this not an issue on Mac OS.

**Comment by gregrafferty** [comment]
I recently stumbled upon this too, it looks to me like there is a casing error in the import of './generated/corePluginList'.
