### ISSUE TITLE
3.1 version, theme function reports lint error

### ISSUE THREAD

**Issue by Rayzhangzhang** [tailwindlabs/tailwindcss#8619]
**What version of Tailwind CSS are you using?**

v3.1.2

**What build tool (or framework if it abstracts the build tool) are you using?**

**What version of Node.js are you using?**

16.14

**What browser are you using?**

**What operating system are you using?**

**Reproduction URL**

**Describe your issue**

`theme('colors[primary] / 20%')` reports `'colors[primary] / 20%' does not exist in your theme config.`. 

It works well , but reports a lint error.  Do I need to add any config  or change the code below in `tailwind.config.js` ?

```css
...
primary: withOpacity('--color-primary-rgb'),
...

```

Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead.

**Comment by thecrypticace** [comment]
Hey, thanks for reporting this. This should **definitely** work but we didn't test the quoted syntax with alpha values at all — we don't generally recommend it anymore just for consistency with CSS itself. I've merged the fix in and it'll be in our insiders build fairly shortly which you can test with `npm install tailwindcss@insiders` if you want to give it a try before we tag a new version.
