### ISSUE TITLE
Classes inside arbitrary variants are incorrectly being prefixed

### ISSUE THREAD

**Issue by thecrypticace** [tailwindlabs/tailwindcss#8626]
Classes inside arbitrary variants are prefixed when they shouldn't be as they're not tailwind utilities.

The utility `[.foo_&]:tw-text-red-400` incorrectly generates a selector referencing `.tw-foo` instead of `.foo`

See: https://github.com/tailwindlabs/tailwindcss/pull/8299#issuecomment-1154053957

Reproduction: https://play.tailwindcss.com/GCMzAzdKNY

**Comment by pandeyprashant123-coder** [comment]
I put '\' in front of '.foo_&' and it is some how giving selector .foo 

https://play.tailwindcss.com/LWujxXokrG

**Comment by brandonmcconnell** [comment]
> I put \ in front of '.foo_&' and it is some how giving selector .foo
> 
> https://play.tailwindcss.com/LWujxXokrG

For some reason, I'm not seeing any in red in your Tailwind CC Play example, and there is no generated CSS. Do you see the same?
