### ISSUE TITLE
no css output for inline classes which specify an attribute value in an arbitrary variant

### ISSUE THREAD

**Issue by olets** [tailwindlabs/tailwindcss#8660]
**What version of Tailwind CSS are you using?**

3.1.3

**What build tool (or framework if it abstracts the build tool) are you using?**

https://play.tailwindcss.com

**What version of Node.js are you using?**

<https://play.tailwindcss.com>'s

**What browser are you using?**

Chrome 102.0.5005.115

**What operating system are you using?**

macOS 12.4

**Reproduction URL**

https://play.tailwindcss.com/zYyWNdDUB4

**Describe your issue**

Arbitrary variants don't support specifying attribute values. Using the form `[&[my-attribute]]:` generates the expected CSS. Adding a value —`[&[my-attribute='val']]:` or `[&[my-attribute="val"]]:`— results in no CSS being generated for that class.

**Comment by brandonmcconnell** [comment]
Tailwind v.1.3.4 is gonna be a great release 🎉

Thanks for getting this one added @thecrypticace 👏🏼
