### ISSUE TITLE
Tailwind Not Working in Production Mode with Next.js Build

### ISSUE THREAD

**Issue by currenthandle** [tailwindlabs/tailwindcss#8673]
I started a new project from scratch with no material-ui and only tailwindcss, and I see the same issue as before. When I deploy my code or a run production build locally, the styling breaks down.

Look at the screenshots, in development the highlighted  `span` has a width across the viewport/page. In production, the same `span` tag has the same classes and apparently, the same styles are applied, however, it's narrower than the page. If I set `width: 100%;`, manually in the styles in chrome dev tools the container-span becomes the width of the page and the image it contains looks correct.

The primary issue is that it's impossible to style a page if it's going to look different once it's up and running. Does anyone know what's going on here or how to address this?

`Development:`
<img width="1542" alt="Screen Shot 2022-06-18 at 10 09 25 AM" src="https://user-images.githubusercontent.com/10948068/174449285-064ff5d8-18fa-4341-8f1e-41a428051e53.png">

`Production:`
<img width="1519" alt="Screen Shot 2022-06-18 at 10 08 54 AM" src="https://user-images.githubusercontent.com/10948068/174449291-2342ffc4-77a4-4510-b3ef-350fce030ec2.png">

```
// Rectangle.js
// the component shown in the screenshots

import Image from 'next/image';
import dynamic from 'next/dynamic';

const ReactPlayer = dynamic(() => import('react-player/lazy'), { ssr: false });

export default function Rectangle({ verticle, asset: { attributes: asset } }) {
  let image = null;
  if (asset.video) {
  } else {
    image = asset.image.data.attributes;
  }
  return (
    <div
      className={`${
        !verticle ? 'w-full flex' : 'w-6/12 flex'
      } relative  justify-center 2xl:h-[500px] xl:h-[450px] lg:h-[400px] md:h-[300px] h-[200px] overflow-hidden`}
    >
      {!asset.video ? (
        <Image
          objectFit='cover'
          height={image.height}
          width={image.width}
          src={
            process.env.NODE_ENV === 'development'
              ? `http://localhost:1337${image.url}`
              : `https://cryptic-cove-11110.herokuapp.com${image.url}`
          }
          alt={image.title}
          className='w-full overflow-hidden'
        />
      ) : (
        <ReactPlayer
          url='https://player.vimeo.com/video/290582899?h=41ed9d7a84'
          controls={true}
          autoplay={true}
        />
      )}
    </div>
  );
}
```

```
// tailwind.config.js

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
```
```
/* global.css */
@tailwind base;
@tailwind components;
@tailwind utilities;

```
```
// postcss.config.js
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
```
```
// next.config.js
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    domains: ['localhost', 'cryptic-cove-11110.herokuapp.com'],
  },
};

module.exports = nextConfig;
```

_Originally posted by @currenthandle in https://github.com/tailwindlabs/tailwindcss/discussions/8521#discussioncomment-2977453_

**Comment by adamwathan** [comment]
Closing in favor of original discussion, if you believe you’ve discovered an actual bug in Tailwind we require a reproduction (in the form of an actual GitHub repo we can clone) to submit an issue.
