### ISSUE TITLE
content utility does not render string, when it contains space(s)

### ISSUE THREAD

**Issue by akomm** [tailwindlabs/tailwindcss#8706]
**What version of Tailwind CSS are you using?**

3.1.4

**What build tool (or framework if it abstracts the build tool) are you using?**

direct use: "yarn tailwind -i ./app/styles/tailwind.css -o ./app/styles/tailwind.out.css --watch"

**What version of Node.js are you using?**

v14.15.3

**What browser are you using?**
Firefox

**What operating system are you using?**
Linux

**Reproduction URL**

https://play.tailwindcss.com/ju3vBiMDVO

**Describe your issue**

The `content-['xyz']` utility does not render, when string contains space(s)

**Comment by aggreggator** [comment]
That's not a bug.
You can find further information in the docs:
https://tailwindcss.com/docs/adding-custom-styles#handling-whitespace
