### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'config')

### ISSUE THREAD

**Issue by scajal** [tailwindlabs/tailwindcss#8740]
**What version of Tailwind CSS are you using?**
3.1.4

**What build tool (or framework if it abstracts the build tool) are you using?**
Laravel Mix

**What version of Node.js are you using?**
Yarn 1.22.19

**What browser are you using?**
Edge

**What operating system are you using?**
Windows

**Reproduction URL**
N/A

**Describe your issue**
When passing a custom configuration file using Laravel Mix, the error is thrown and no asset is generated.
`webpack.mix.js` configuration:
`.postCss("resources/css/app.css", "public/css", [require("tailwindcss")("tailwind-mail.config.js"),])`

**Comment by yogarasu** [comment]
I ran into a similar problem, but I solved it by fixing the file path
https://github.com/tailwindlabs/tailwindcss/issues/6393#issuecomment-1080723375

**Comment by thecrypticace** [comment]
Hey! I can't reproduce this. I replied to your issue in the Laravel Mix repo but this is likely a configuration problem.

Let's track this one there: https://github.com/laravel-mix/laravel-mix/issues/3285
