### ISSUE TITLE
Changing container max-width also changes breakpoint itself

### ISSUE THREAD

**Issue by silveltman** [tailwindlabs/tailwindcss#8757]
v3.1.3
postcss 8.4.14
postcss-cli 9.1.0
Node v16.15.1
Firefox
Windows

tailwind play: https://play.tailwindcss.com/mhySV5bYi6?file=config

Setting the max-width for container in config does not only change the max width, but also the breakpoint itself.

![image](https://user-images.githubusercontent.com/52583398/176932675-fb91572b-3c0c-4df4-99e1-c29869257706.png)

**Comment by adamwathan** [comment]
Hey! So the `screens` option is this super old legacy crufty thing that was added so you could use different breakpoints for the container if you wanted to, _not_ to change the width of the container on certain breakpoints. In our minds this whole option doesn't even really exist, it's just there for super old backwards compatibility reasons.

If you want to change the container size at different breakpoints, the recommend solution is to actually just configure the padding for the container for each breakpoint:

https://tailwindcss.com/docs/container#adding-horizontal-padding

```js
// tailwind.config.js
module.exports = {
  theme: {
    container: {
      padding: {
        DEFAULT: '1rem',
        sm: '2rem',
        lg: '4rem',
        xl: '5rem',
        '2xl': '6rem',
      },
    },
  },
};
```

Hope that helps!

**Comment by silveltman** [comment]
Hi Adam, thanks for the reply!

Is there a way to disable the max-width of the container (without making a utility)? Since I would like to have a fluid container width.

My ideal setup would be a container with a max-width of 1280px with fluid padding, like min(20px, 5vw) or something

**Comment by jd1378** [comment]
@adamwathan what if it's a design decision to not have fixed width till `"md"` breakpoint ?
I think being able to change the behavior of max width is still a valid use case
It's currently only setting `width: 100%;` before `sm`, but I want it to be applied to `sm` itself as well
how do I do that ?

**Comment by jd1378** [comment]
as a workaround I did this but I don't think it's the right way:

```ts
import type {Config} from 'tailwindcss';
import type {PluginAPI} from 'tailwindcss/types/config';

export default <Partial<Config>>{
// ...
plugins: [
    function ({addComponents}: PluginAPI) {
      addComponents({
        '.container': {
          '@screen sm': {
            maxWidth: '100% !important',
          },
        },
      });
    },
  ],
  };

  ```
