### ISSUE TITLE
Color property bg-black results in rgba(0, 0, 0, 0.7) in Chrome

### ISSUE THREAD

**Issue by sparker888** [tailwindlabs/tailwindcss#8781]
**What version of Tailwind CSS are you using?**

 3.1.4

**What build tool (or framework if it abstracts the build tool) are you using?**

Gatsby

**What version of Node.js are you using?**

v. 17.9.0

**What browser are you using?**

Chrome (works fine in Firefox and Safari)

**What operating system are you using?**

both macOS and Windows

**Reproduction URL**

[See src/pages/layout1.js in this repo.](https://github.com/sparker888/gsapScroll)

Here's a screenshot with Dev Tools open to see the specific value in far-right panel: https://i.imgur.com/zVqkTov.png

NOTE: Notice in the browser window on the left side an image with a black background next to the slightly lighter "black" background. Spoiler, it's not black.

**Describe your issue**

The Tailwind bg-black class is results in rgba(0, 0, 0, 0.7) in a Chrome browser (Version 103.0.5060.114 (Official Build) (64-bit))

Obviously this is a browser issue, but I'm reporting the issue here to see if anyone else experiences this and if there's a workaround. 

Thanks!

**Comment by adamwathan** [comment]
Hey! That class isn't coming from Tailwind, you can see the Tailwind class is being overridden by some non-Tailwind CSS in your screenshot:

<img width="285" alt="image" src="https://user-images.githubusercontent.com/4323180/177585128-b4d7c4f4-9872-45e9-8b67-d8f0afedfdd6.png">

Something is injecting its own `bg-black` class in a `<style>` tag and overriding Tailwind.

Cursory search makes it look like you have this Chrome extension installed:

https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en

...based on the `--darkreader-bg` prefix on the CSS variable in the style rule.

Just installed it to test myself and it's definitely the culprit, so no Tailwind bug here, that Chrome extension is just doing what it's meant to do which is override all of your styles with automatically generated dark mode styles.
