### ISSUE TITLE
Commas in custom variants being removed

### ISSUE THREAD

**Issue by corneliusio** [tailwindlabs/tailwindcss#8799]
**What version of Tailwind CSS are you using?**
v3.1.0 and up

**What build tool (or framework if it abstracts the build tool) are you using?**
postcss@8.4.14
webpack@5.72.0

**What version of Node.js are you using?**
v18.4.0

**What browser are you using?**
Chrome

**What operating system are you using?**
macOS

**Reproduction URL**
https://play.tailwindcss.com/mXkrZEPO2j

**Describe your issue**
We currently use custom variants to apply state-based styles to components on our sites. It looks like a bug was introduced in v3.1 that caused commas in these custom variants to be stripped out of the compiled CSS. I've included the below example of what we're doing and the issue itself can be seen in the above Tailwind Play link.

```js
plugin(({ addVariant, e }) => {
    addVariant('is-active', ({ modifySelectors, separator }) => {
        modifySelectors(({ className }) => [
            `.is-active .${e(`is-active${separator}${className}`)}`,
            `.is-active.${e(`is-active${separator}${className}`)}`
        ].join(',\n'));
    });
})
```

**Comment by thecrypticace** [comment]
Hey, thanks for the report. We've actually got a first-class feature for variants with multiple selectors!

You can rewrite the plugin above like so:
```js
plugin(({ addVariant, e }) => {
  addVariant("is-active", [".is-active &", "&.is-active"])
})
```

The `modifySelectors` API is only meant to modify each individual selector a utility produces (which is most of the time just a single selector). It cannot turn one selector into multiple selectors. I would suggest you use the array version of `addVariant` for your situation. Hopefully that helps!
