### ISSUE TITLE
Why tailwind CSS does not support `via-[rgb(245,205,130)]` ??

### ISSUE THREAD

**Issue by jcindex** [tailwindlabs/tailwindcss#8843]
**What version of Tailwind CSS are you using?**

3.1.6

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite 2.9.13

**What version of Node.js are you using?**

v16.15.1

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction URL**

No URL

**Describe your issue**

Why tailwind CSS does not support `via-[rgb(245,205,130)]` but `via-[#f5cd82]` ??

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

It does support that, e.g.: https://play.tailwindcss.com/MyfDwXuRGD
