### ISSUE TITLE
Cannot use bg-gradient-to-x when I set some custom 'backgroundImage' in tailwind.config.js

### ISSUE THREAD

**Issue by varKeytrap** [tailwindlabs/tailwindcss#8899]
**What version of Tailwind CSS are you using?**

For example: v3.1.6

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: postcss 8.4.14, Next.js 12.2.2 (using [this](https://github.com/ixartz/Next-js-Boilerplate) templates)

**What version of Node.js are you using?**

For example: v16.15.1

**What browser are you using?**

For example: MS Edge

**What operating system are you using?**

For example: Windows 10

**Reproduction URL**

https://play.tailwindcss.com/vv2YSFrsZz

**Describe your issue**

When I set this in tailwind config:

```
backgroundImage: {
      hero: "url('/assets/images/background.jpg')",
    }
```

I can't set any gradient class for example `bg-gradient-to-t`.
Try to set a gradient class in the tailwind play.
If you remove the `backgroundImage` node in the tailwind config, the gradient intellisense appears and works.

Here's a simple demo so that I'm 100% clear :

![Animation](https://user-images.githubusercontent.com/17864005/179834724-7831386f-1d02-4f44-8f83-9ce755a1d51d.gif)

Maybe I'm doing something wrong ?

**Comment by adamwathan** [comment]
Hey! This is because you are overriding all of the built-in background image classes. You want to use `extend` if you want to add new background image utilities while preserving the defaults:

https://play.tailwindcss.com/uDhEHFkhtg?file=config

Hope that helps!

**Comment by varKeytrap** [comment]
I just realised it and was going to close the issue. Thank you for your quick reply, and keep up your great videos en YouTube 🚀 !
