### ISSUE TITLE
[Feature] Support for a static plugin resolution format

### ISSUE THREAD

**Issue by adamwathan** [tailwindlabs/tailwindcss#890]
Leaving this for myself so I don't forget 😅

I want to make it possible to do something like this in your config:

```js
plugins: [
  'my-third-party-plugin',
  'my-other-third-party-plugin',
]
```

...to make it safe to load your `tailwind.config.js` file in your front end bundles without accidentally bringing along a bunch of build dependencies.

The format I like the most so far is the Babel format:

```js
{
  "plugins": [
    'simple-plugin-with-no-options',
    [
      'plugin-that-can-have-options-so-included-as-a-tuple',
      {
        optionA: 'banana',
        optionB: 'sandwich'
      }
    ]
  ]
}
```

**Comment by adamwathan** [comment]
Another note for myself — anything registered statically like this is really easy for me to register as a watchable file so I should do that too. That way if you have any custom plugins in your project, your CSS can automatically rebuild when you tweak those plugins.

**Comment by adamwathan** [comment]
Going to close this, no plans to add this right now. I would recommend a solution like [babel-plugin-preval](https://github.com/kentcdodds/babel-plugin-preval) if you want to import your config into front-end code with the minimum bundle size increase instead.

**Comment by espensgr** [comment]
I guess the [twin](https://github.com/ben-rogerson/twin.macro) plugin that @ben-rogerson made solves this? Maybe add it to the documentation as a possible solution.

**Comment by terlan4** [comment]
@adamwathan could you please show demo of how to configure babel-plugin-preval properly for referencing in javascript? https://tailwindcss.com/docs/configuration#referencing-in-java-script
