### ISSUE TITLE
GHSA vulnerability force me to downgrade to v2.0.4

### ISSUE THREAD

**Issue by simkimsia** [tailwindlabs/tailwindcss#8901]
I came here because of this advisory:
https://github.com/advisories/GHSA-cj88-88mr-972w

**What version of Tailwind CSS are you using?**

Was using
    "@tailwindcss/forms": "^0.4.0",
    "@tailwindcss/typography": "^0.5.0",
    "tailwindcss": "^3.0.13"

then re-run `npm audit fix --force` changed to 
    "@tailwindcss/forms": "^0.3.4",
    "tailwindcss": "^2.0.4"
    "@tailwindcss/typography": "^0.4.1",
    
        
**What build tool (or framework if it abstracts the build tool) are you using?**

I use django-tailwind==3.1.1 # https://github.com/timonweb/django-tailwind/releases

**What version of Node.js are you using?**

npm: 8.14.0
node is v17

**What browser are you using?**

Edge

**What operating system are you using?**

macOS but i build using docker with the image os as `FROM ubuntu:focal-20220531`

**Reproduction URL**

I don't have this sorry. I am reporting what happens when I needed to rebuild using `npm audit fix` forcing me to downgrade my tailwindcss otherwise my npm install would have failed.

**Describe your issue**

I am not sure if this is an issue?

This is my full list of current package.json

```
{
  "name": "theme",
  "version": "3.1.1",
  "description": "",
  "scripts": {
    "start": "npm run dev",
    "build": "npm run build:clean && npm run build:tailwind",
    "build:clean": "rimraf ../static/css/dist",
    "build:tailwind": "cross-env NODE_ENV=production tailwindcss --postcss -i ./src/extra-to-tailwind-styles.css -o ../static/css/dist/styles.css --minify",
    "dev": "cross-env NODE_ENV=development tailwindcss --postcss -i ./src/extra-to-tailwind-styles.css -o ../static/css/dist/styles.css -w",
    "tailwindcss": "node ./node_modules/tailwindcss/lib/cli.js"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "@tailwindcss/aspect-ratio": "^0.4.0",
    "@tailwindcss/forms": "^0.3.4",
    "@tailwindcss/line-clamp": "^0.3.1",
    "@tailwindcss/typography": "^0.4.1",
    "cross-env": "^7.0.3",
    "postcss": "^8.4.5",
    "postcss-import": "^14.0.2",
    "postcss-nested": "^5.0.6",
    "postcss-simple-vars": "^6.0.3",
    "rimraf": "^3.0.2",
    "tailwindcss": "^2.0.4"
  }
}

```

This is my git diff

![image](https://user-images.githubusercontent.com/245021/179920379-68698728-6db8-4121-8501-69d91f136f9d.png)

**Comment by adamwathan** [comment]
Hey! We've already updated to `glob-parent` 6.0.2 so shouldn't be an issue anymore. Regardless it's really a [false positive](https://overreacted.io/npm-audit-broken-by-design/) and not actually a security issue because Tailwind is a build tool and not something people can actually interact with as end users of your project 👍🏻
