### ISSUE TITLE
ADDING BACKGROUND IMAGE TO STATIC HOSTED PAGE

### ISSUE THREAD

**Issue by thrila** [tailwindlabs/tailwindcss#8913]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/8912

<div type='discussions-op-text'>

<sup>Originally posted by **thrila** July 20, 2022</sup>
I added a background image in my project and  it worked on the live version i then ran `npm build && npm export ` and made the site live on github when the site became live the rest of my CSS worked but my image wouldn't work 

the way i imported inserted the image is `background-image: url('../public/image 2.PNG'); `  </div>

**Comment by RobinMalfait** [comment]
Hey! Let's keep the conversation in the discussion.
