### ISSUE TITLE
I can't set up a new rails project with tailwind-css

### ISSUE THREAD

**Issue by deyemiobaa** [tailwindlabs/tailwindcss#8916]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/8915

<div type='discussions-op-text'>

<sup>Originally posted by **deyemiobaa** July 21, 2022</sup>
Hello, I'm trying to set up a new rails project with `rails new my_app --css tailwind` && `rails new my_app --css=tailwind` but I keep getting an error
![image](https://user-images.githubusercontent.com/55185309/180105856-9ccf9863-e711-4f00-af84-12420a0110f1.png)

This same error also exists if I try to add tailwind-CSS manually using the steps specified in the documentation
![image](https://user-images.githubusercontent.com/55185309/180106000-913b8f61-3599-499e-aebb-47fe4b527e46.png)

I use a Windows 10 PC</div>

**Comment by ajarouih** [comment]
If you run in a vagrant box, you'll need to tell foreman to bind all interfaces. Change first line of Procfile.dev to read as web: bin/rails server -b 0.0.0.0 -p 3000

**Comment by ajarouih** [comment]
rails assets:clean assets:precompile

This command resolved helped me to resolved this issue.
