### ISSUE TITLE
Missing declaration file for "tailwindcss/resolveConfig"

### ISSUE THREAD

**Issue by joshmossas** [tailwindlabs/tailwindcss#8920]
**What version of Tailwind CSS are you using?**

For example: v3.1.6

**What build tool (or framework if it abstracts the build tool) are you using?**

Vite, Typescript

**What version of Node.js are you using?**

For example: v16.15.1

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows 10

**Reproduction URL**

https://github.com/joshmossas/tailwindcss-resolve-config-missing-types

**Describe your issue**

When attempting to use the [resolveConfig](https://tailwindcss.com/docs/configuration#referencing-in-java-script) helper in a typescript project you get a type error `Could not find a declaration file for module 'tailwindcss/resolveConfig'`.

**Comment by joshmossas** [comment]
For anyone that needs a quick work-around, create a `.d.ts` file in your types/typings directory with the following

```ts
declare module "tailwindcss/resolveConfig" {
  import type { Config } from "tailwindcss";
  export default function (config: Config): Config;
}
```

**Comment by thecrypticace** [comment]
Hey, I merged in your PR. This will be in our insiders build until we tag a new release (likely tomorrow). Thanks again for the PR! 🎉

**Comment by robclancy** [comment]
I am using some utils, would be nice if all of them had types. Here is what I've done to add some.

```ts
declare module "tailwindcss/src/util/normalizeScreens" {
  import {
    ResolvableTo,
    Screen,
    ScreensConfig,
  } from "tailwindcss/types/config";

  type ScreenDefinition = {
    name: string;
    values: Screen;
  };

  export function normalizeScreens(
    screens: ResolvableTo<ScreensConfig>
  ): ScreenDefinition[];
}

declare module "tailwindcss/src/util/buildMediaQuery" {
  import { ScreenDefinition } from "tailwindcss/src/util/normalizeScreens";

  function buildMediaQuery(screen: ScreenDefinition): string;

  export = buildMediaQuery;
}
```

**Comment by thecrypticace** [comment]
@robclancy Those utils are not part of the Tailwind CSS public API so we are not likely to add types for them.

**Comment by Sidnioulz** [comment]
If it's not part of your public API, why is it on your public documentation?

https://tailwindcss.com/docs/configuration#referencing-in-java-script

**Comment by Sidnioulz** [comment]
@thecrypticace aaaand I read too fast. My sincerest apologies! :scream:

**Comment by thecrypticace** [comment]
@Sidnioulz All good!
