### ISSUE TITLE
Class delay-0 doesn't exist

### ISSUE THREAD

**Issue by federicocappellotto97** [tailwindlabs/tailwindcss#9021]
**What version of Tailwind CSS are you using?**

3.1.7

**What build tool (or framework if it abstracts the build tool) are you using?**

Tailwind CLI

**What version of Node.js are you using?**

14.18.3

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Describe your issue**

Delay class' docs says to use the class **hover:delay-0** but the class delay-0 doesn't exist, so it doesn't work. I need to use delay-[0s]

**Comment by adamwathan** [comment]
[Changed the docs](https://github.com/tailwindlabs/tailwindcss.com/commit/9197609ec74afbd40ffbffd273307aa9a2cc7647) to use a class that does exist, thanks.
