### ISSUE TITLE
Not detecting class names with template literals

### ISSUE THREAD

**Issue by westernwontons** [tailwindlabs/tailwindcss#9043]
**What version of Tailwind CSS are you using?**
v3.1.7

**What build tool (or framework if it abstracts the build tool) are you using?**
Next.js 12.2.2

**What version of Node.js are you using?**
v16.13.2

**What browser are you using?**
Tried in Chrome v104, Safari v15.6 and Firefox v103.0.1

**What operating system are you using?**
macOS

**Reproduction URL**
https://github.com/westernwontons/tailwind-classnames-bug-reproduction

**Describe your issue**

Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead.

The problem is the following:

The component `InputWithLabelThatWorks` as it's name implies, works. It has static classNames.
The component `InputWithLabelThatDoesntWork` will not render the classNames if they are inserted dynamically with template literals.

To reproduce the issue:

1. Go to line 64 and add `colour='accent'` prop to the component
2. Check your browser. It doesn't render.
3. Go to line 34 and replace `input-primary` with `input-accent`
4. Now the new colour is visible in `InputWithLabelThatDoesntWork` component.

My idea is that Tailwind doesn't recognize dynamically inserted classNames with template literals UNTIL that specific CSS class has been written into a className property.

**Comment by adamwathan** [comment]
See the docs: https://tailwindcss.com/docs/content-configuration#dynamic-class-names
