### ISSUE TITLE
Not possible to set ring color with `future.respectDefaultRingColorOpacity` enabled

### ISSUE THREAD

**Issue by dcastil** [tailwindlabs/tailwindcss#9066]
**What version of Tailwind CSS are you using?**

v3.1.7

**What build tool (or framework if it abstracts the build tool) are you using?**

n/a

**What version of Node.js are you using?**

n/a

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/N1ko1lZjzn?file=config

**Describe your issue**

When `future.respectDefaultRingColorOpacity` is set to `true` in Tailwind config, I can't set ring colors like `ring-gray-500` anymore. The respective class is not created by the Tailwind compiler.

Related: https://github.com/tailwindlabs/tailwindcss/issues/9016#issuecomment-1210378693

**Comment by thecrypticace** [comment]
🤦 heh oops… thanks for reporting this. The fix will be in our insider build in a few and in the next tagged release.
