### ISSUE TITLE
Arbitrary values color with opacity tailwind

### ISSUE THREAD

**Issue by VictorPulzz** [tailwindlabs/tailwindcss#9069]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/9068

<div type='discussions-op-text'>

<sup>Originally posted by **VictorPulzz** August 10, 2022</sup>
Hello!
Сan you help me?
I want add dynamic color with opacity in component with css variables
Component:
```ts
 <div
      className={styles.block}
      style={{  '--color': color} as CSSProperties}
   />
```
Scss module: 
```css
.block {
  @apply text-[color:var(--color)] bg-[color:var(--color)]/10;
}
```
This class `bg-[color:var(--color)]/10` not work(</div>

**Comment by adamwathan** [comment]
Please don't create issues for questions, your original discussion was the right place for this.

**Comment by VictorPulzz** [comment]
It's just that issues are always checked more often.
