### ISSUE TITLE
line-clamp doesn't work properly on safari

### ISSUE THREAD

**Issue by furbatamang** [tailwindlabs/tailwindcss#9087]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/9086

<div type='discussions-op-text'>

<sup>Originally posted by **furbatamang** August 12, 2022</sup>
Line clap doesn't truncate the paragraph properly on safari</div>

**Comment by thecrypticace** [comment]
Closing in favor of the discussion
