### ISSUE TITLE
Error loading PostCSS config: Invalid PostCSS Plugin found: [0]

### ISSUE THREAD

**Issue by jamols09** [tailwindlabs/tailwindcss#9180]
**What version of Tailwind CSS are you using?**

"tailwindcss": "^3.1.8", 

**What build tool (or framework if it abstracts the build tool) are you using?**

PyroCMS 3.4
```
"laravel/framework": "5.5.*",
"devDependencies": {
    "autoprefixer": "^10.4.8",
    "axios": "^0.16.2",
    "bootstrap-sass": "^3.4.1",
    "cross-env": "^5.2.1",
    "jquery": "^3.4.1",
    "laravel-mix": "^1.0",
    "lodash": "^4.17.4",
    "postcss": "^8.4.16",
    "tailwindcss": "^3.1.8",
    "vue": "^2.1.10"
  },
  "dependencies": {
    "node-sass": "^6.0.1",
    "select2": "^4.0.10",
    "vue-bootstrap-typeahead": "^0.2.6",
    "vue-loading-overlay": "^3.2.0",
    "vue-multiselect": "^2.1.6",
    "vue-recaptcha": "^1.3.0",
    "vue-resource": "^1.5.1",
    "vue2-dropzone": "^3.6.0"
  }
```
**What version of Node.js are you using?**

For example: v14.7.1

**What browser are you using?**

Edge

**What operating system are you using?**

Windows. I don't have any idea why my coworker was able to run this project smoothly without any problems. We all have the same version on package.lock, npm version & node version the only difference was he/she was using Mac.

**Reproduction URL**
N/A

**Describe your issue**
my postcss.config is empty
```
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
```

When running npm run dev/watch I got this error `Error loading PostCSS config: Invalid PostCSS Plugin found: [0]` or this ` error  in ./node_modules/vue-bootstrap-typeahead/src/components/VueBootstrapTypeahead.vue`
![image](https://user-images.githubusercontent.com/20100579/186683450-2e1740a8-56e5-4db9-9c5b-50061343c1d7.png)

**Comment by adamwathan** [comment]
Hey! I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction — a [Tailwind Play](https://play.tailwindcss.com) if the issue can be reproduced there, or a GitHub repository where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!
