### ISSUE TITLE
CLI duplicate selectors in output after updates when important: true

### ISSUE THREAD

**Issue by willdean** [tailwindlabs/tailwindcss#9203]
V3.1.18
Tailwind CLI
Node v14.18.1
Chrome
Window 10 (No Docker or WSL)
CLI command line:  `npx tailwindcss --output wwwroot/css/tailwind.css --watch -i wwwroot/css/twbase.css`

**Reproduction URL**

I have a perfectly consistent repro on a large real project which I cannot share, and I cannot repro this in a small project.  However I'm going to describe it in the hope that it might be diagnosable by someone familiar with the code.  Please don't summarily execute my morning's worth of work on this bug report because of the lack of a URL - I will work with you guys to track this down.

**Describe your issue**

Each time a new selector is found and added to the output on an update, at least one existing selector is also duplicated.

* The starting point was a large output file, which already contain a `.ml-2` selector along with many many other selectors, including other `.ml-xx` values.  This is attached in zip file tailwind_orig.css.

* I added a selector `ml-[96px]` to a div class property, TW did an update and inserted the following into the output file:
```
 .ml-2 {
  margin-left: 0.5rem !important;
}

.ml-\[96px\] {
  margin-left: 96px !important;
}
```
The first selector is a duplicate of one which is already in the file, the ml-[96] is the correct new one.
There were also several other duplicates, scattered through the file.  The result is tailwind_diff1.css,, in zip.

* Then I edited the source file to change the `ml-[96px]` into `ml-[94px]`,   Again, TW correctly detects the change, but adds the following to the output:
```
 .ml-2 {
  margin-left: 0.5rem !important;
}

.ml-\[94px\] {
  margin-left: 94px !important;
}
```
There are now three copies of the ml-2 selector: the original and two duplicates.
The other duplicates do not seem to have been repeated.
The result of this is tailwind_diff2.css

* The process can be repeated indefinitely - each time the `ml-[??px]` selector is changed, TW adds the correct new code but also adds a duplicate of the `ml-2` selector.

The content spec from the config is:
```
    content: [
        "./Views/**/*.cshtml",
        "./Views/**/*.razor",
        "./Pages/**/*.cshtml",
        "./Components/**/*.razor"
    ],
```
It doesn't make any different whether I'm modifying the  file from Visual Studio or Notepad - i.e. it doesn't seem to be some safe-save race type problem.   We often notice other duplicates in the file, not just `ml` - a restart of the CLI cleans them up

[TW_Dups.zip](https://github.com/tailwindlabs/tailwindcss/files/9439649/TW_Dups.zip)

**Comment by adamwathan** [comment]
Can you try and delete stuff from the bigger project while still reproducing the issue until it’s something you can share, or invite someone from our team to the repo privately? Unfortunately it’s just totally impossible for us to troubleshoot or fix any issue here without being able to reproduce it.

**Comment by willdean** [comment]
Thanks Adam - I'll see what I can do.   I posted this at this stage in the hope that someone would already have some suspicion and this might help confirm that.
When I get my head around TW's code a bit more I plan to add something which checks for duplicates and aborts immediately - then at least I'll know where it's happening.

**Comment by willdean** [comment]
@adamwathan I'm wrestling through the code here and have what I hope is a quick question:

Should I expect to see duplicate rules within `context.stylesheetCache`?   

i.e. does the processing that prevents there being duplicates in the output file happen before rules are added to 'context.stylesheetCache' (i.e. in `expandTailwindAtRules` / `buildStylesheet` or after that point (when the CSS is being generated)?

For info, what I see in my repro situation is that `generateRules` generates a bunch of rules for the recently-modified file, and these all get added to `context.stylesheetCache` (as duplicates) each time there's an update.  

If I can't make progress with the code today (it's a public holiday here...) then I'll put equivalent effort into a repro that I can share.

**Comment by willdean** [comment]
OK, here's some code which "fixes" the problem in my situation.   **I am not proposing this as a fix, it's clearly wrong, but it might be diagnostic of the real problem in some way**

This is for the "utilities" clause of `buildStylesheet`:

```
  if (sort & context.layerOrder.utilities) {
            let dup = false;
            for (let util of returnValue.utilities) {
                if(util.selector === rule.selector) {
                    dup = true;
                    break;
                }
            }
            if(!dup) {
                returnValue.utilities.add(rule);
            }
            continue;
        }
```

This prevents the duplicates being added to the `context.stylesheetCache`, which prevents them appearing in the output file.  The new selectors *are* still correctly added.

Please excuse the stream of consciousness as I work towards the actual trigger for this problem.
