### ISSUE TITLE
Error: Expected a backslash preceding the semicolon.

### ISSUE THREAD

**Issue by IgorDePaula** [tailwindlabs/tailwindcss#9204]
**What version of Tailwind CSS are you using?**

For example: v2.0.4

**What build tool (or framework if it abstracts the build tool) are you using?**

"autoprefixer": "^10.4.8",
"tailwindcss": "^3.1.8"
"laravel-vite-plugin": "^0.5.0",
"lodash": "^4.17.19",
"postcss": "^8.4.16",
"vite": "^3.0.0"

**What version of Node.js are you using?**

v16.14.2

**What browser are you using?**

Firefox 103.0.2 (64-bits)

**What operating system are you using?**

ubuntu 22.04

**Reproduction URL**

https://github.com/IgorDePaula/sitebanco

**Describe your issue**

After install tailwind with vite I can`t process tailwind css file, with error message: Expected a backslash preceding the semicolon.
I contact the vite org and they said that i problem with tailwind. This occur only with blade files.

![Captura de tela de 2022-08-28 10-47-49](https://user-images.githubusercontent.com/2833993/187080971-065a6a17-c19a-49ce-b440-77d1b311b685.png)
![Captura de tela de 2022-08-28 10-48-03](https://user-images.githubusercontent.com/2833993/187080972-996ae98a-156e-4c8a-b55f-aa00bc14af8a.png)

![Captura de tela de 2022-08-28 10-47-20](https://user-images.githubusercontent.com/2833993/187080969-728365e4-4e3e-4904-8a46-146575714a81.png)

**Comment by IgorDePaula** [comment]
Wrong copy file. Sorry!

**Comment by harveyhq** [comment]
@IgorDePaula how you solved the issue?

**Comment by IgorDePaula** [comment]
@harveyhq The template that I buyed was has strangers characters, when I removed it, the problem disappeared.

**Comment by VulcanTech-io** [comment]
I had this problem earlier today, I am using NextJS and had to delete my .next file to fix it.
