### ISSUE TITLE
w-fit not contained in utilities.css

### ISSUE THREAD

**Issue by Destroxim** [tailwindlabs/tailwindcss#9216]
I recently rebuild my whole module-packer pipeline because it seemed to fail purging tailwind classes..

Until I realised, that "w-fit" isn't contained in any .css file provided by the tailwindcss package.

Please add:

`.w-fit {
    width: fit-content;
}
`

to utilities.css

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

`w-fit` already exists, and does work as expected (checkout the generated css > utilities at the bottom) https://play.tailwindcss.com/UUCysq9SwL

If you don't see it, and you are using it, then make sure that the file you are using it in is listed in your `content` section of your `tailwind.config.js` file. https://tailwindcss.com/docs/content-configuration

**Comment by Destroxim** [comment]
Hey! Thank you for the quick answer!

My Tailwind.config.js is correct, I ensured by trying other tailwind classes on the same html element.

Could you tell me, where exactly the original tailwindcss utilities.css file is stored in the node_modules directory and in your git repository?
The one I import by @utilities..
Because I found one in tailwindcss/dist/utilities.css and it doesn't contain w-fit.. (see screenshot)

I installed tailwindcss via npm and everything else is working.
![screenshot](https://user-images.githubusercontent.com/42513454/187498830-192f0cbe-799b-4206-8a37-bc725c797977.png)

Sorry for taking your time.. I don't want to dirty fix it, by adding it to other css files. (which worked..)

**Comment by RobinMalfait** [comment]
Looks like you are on an old version of tailwind where we didn't have that yet. Either add it yourself or update to the latest version 👍

If you still have issues, then please add a reproduction repo so that we can take a look.
