### ISSUE TITLE
Arbitrary properties mask-image and clip-path conflicting

### ISSUE THREAD

**Issue by n1k1c4** [tailwindlabs/tailwindcss#9275]
I am using `tailwindcss: 3.1.8` and `eslint-plugin-tailwindcss: 3.6.1`.

I'm doing this thing:
<img width="70" alt="image" src="https://user-images.githubusercontent.com/8379098/188685130-d23c9cf5-085f-47d7-b4a2-91cd16aa3046.png">

In `classNames` I write this:
```jsx
<div
  className={clsx(
    "[clip-path:circle(100%_at_center)]",
    "[mask-image:radial-gradient(circle_at_center,transparent_51%,black_54.8%)]",
    "bg-[conic-gradient(transparent,#9e9ab1)]",
    "pointer-events-none h-6 w-6 animate-spin rounded-full"
  )}
/>
```

Everything is displayed as it should. But after updating `@typescript-eslint/eslint-plugin` to version `5.36.2` and `typescript` to version `4.8.2`, eslint shows an error:
```
Classnames [clip-path:circle(100%_at_center)], 
[mask-image:radial-gradient(circle_at_center,transparent_51%,black_54.8%)] are conflicting!
eslint[tailwindcss/no-contradicting-classname](https://github.com/francoismassart/eslint-plugin-tailwindcss/tree/master/docs/rules/no-contradicting-classname.md)
```

**Comment by adamwathan** [comment]
Hey! This seems like an issue with `eslint-plugin-tailwindcss` which is not made or maintained by us. I'd open the issue over there 👍🏻
