### ISSUE TITLE
Tailwind fails to detect single class wrapped in double quotes in minified JS build.

### ISSUE THREAD

**Issue by aidanCQ** [tailwindlabs/tailwindcss#9297]
**What version of Tailwind CSS are you using?**

v3.0.24

**What build tool (or framework if it abstracts the build tool) are you using?**

Next.js 12.3.0

**What version of Node.js are you using?**

v16.15.0

**What browser are you using?**

Firefox

**What operating system are you using?**

macOS

**Reproduction URL**

-

**Describe your issue**

I am installing a component library I have created and have added it to the `content` field in `tailwind.config.js`. Tailwind is able to detect 99% of the classes except for single classes wrapped in double quotes.

In my component library code I am condionally appending classes like so:
```tsx
<div className={cx(condition ? "px-3.5" : "", "bg-blue-600 text-gray-500")}></div>
```
The output js in the build is this:
```js
//...minifiedJS
r?"px-3.5":"" // This is where the problem lies
//...minifiedJS
```
Tailwind fails to detect the class `px-3.5` if it is alone in double quotes. If I manually edit the build, tailwind is able to detect the class in the following:
```js
//...minifiedJS
r?" px-3.5 ":"" // I have added whitespace around the class and this works
//...minifiedJS
```

**Comment by thecrypticace** [comment]
Hey! So we rewrote the extractor in Tailwind CSS v3.1 to be a lot more resilient to these kinds of issues. I see you are on an older version of v3. I've double checked and it looks like this is fine in the latest version of Tailwind CSS: https://play.tailwindcss.com/CRTXV4TM9E

**Comment by aidanCQ** [comment]
> Hey! So we rewrote the extractor in Tailwind CSS v3.1 to be a lot more resilient to these kinds of issues. I see you are on an older version of v3. I've double checked and it looks like this is fine in the latest version of Tailwind CSS: https://play.tailwindcss.com/CRTXV4TM9E

Oh right, thank you!
