### ISSUE TITLE
Exception thrown when a plugin defined with `plugin.withOptions` is being used without options

### ISSUE THREAD

**Issue by yaronuliel** [tailwindlabs/tailwindcss#9316]
**What version of Tailwind CSS are you using?**
v3.1.8

**What build tool (or framework if it abstracts the build tool) are you using?**
vite 3.1.0, postcss 8.4.16

**What version of Node.js are you using?**
v18.7.0

**What browser are you using?**
Not Relevant

**What operating system are you using?**
macOS 12.5 

**Reproduction URL**
https://play.tailwindcss.com/RJUiGy8hnJ

**Describe your issue**
According to the [documentation](https://play.tailwindcss.com/RJUiGy8hnJ), plugins defined with `plugin.withOptions` should work as callable function with `options` object, or by just passing them to the `plugins` array without invoking the function

For example, these 2 snippets should do the same thing:
```js
const customPlugin1 = plugin.withOptions(...)

module.exports = {
   ...,
   plugins: [customPlugin1]
}
```

```js
const customPlugin2 = plugin.withOptions(...)

module.exports = {
   ...,
   plugins: [customPlugin2({})]
}
```

Instead, the first snippet, passes `undefined` instead of `{}` for the `options` argument - causing direct access to properties on the `options` argument (as depicted in the docs) to throw the following exception:

```
Cannot read properties of undefined (reading '[WHATEVER]')
```

I'd either expect the docs to be corrected [here](https://github.com/tailwindlabs/tailwindcss.com/blob/master/src/pages/docs/plugins.mdx?plain=1#L539) and [here](https://github.com/tailwindlabs/tailwindcss.com/blob/master/src/pages/docs/plugins.mdx?plain=1#L573), or preferably - the library to send `{}` as the `options` argument if the plugin is registered without invoking it

**Comment by thecrypticace** [comment]
Hey, this is definitely a documentation issue. We've updated it to use a default value in the plugin options like we do for our [typography plugin](https://github.com/tailwindlabs/tailwindcss-typography/blob/5f85ce93cbd19b4c0193a8eeef85b76f6f214685/src/index.js#L70) and our [forms plugin](https://github.com/tailwindlabs/tailwindcss-forms/blob/b3ed1576aa886bdca96b6d7c6d8ab3bf7ea5e7d5/src/index.js#L8).

When using `withOptions`  it is up to the plugin authors to handle the `undefined` case. Given that plugins may design their plugin API as they see fit, they may not even use an options object but decide on positional arguments instead. In this scenario we wouldn't know the correct values to pass in as defaults ourselves which leaves it for the plugin to handle.

Hopefully that helps — if you have any further questions feel free to leave a comment ✨
