### ISSUE TITLE
Ring does not work

### ISSUE THREAD

**Issue by msftMazzone** [tailwindlabs/tailwindcss#9329]
**What version of Tailwind CSS are you using?**

`"tailwindcss": "^3",`

**What build tool (or framework if it abstracts the build tool) are you using?**

`"postcss": "^8.4.5",`

**What version of Node.js are you using?**

`v14.17.5`

**What browser are you using?**

Chrome, Safari

**What operating system are you using?**

macOS Monterey

**Describe your issue**

The `ring` utility does not work. I can copy/paste [the code directly from the documentation](https://tailwindcss.com/docs/ring-offset-width) and it does not look anything like it does in the docs. 
I create a plain HTML `<button>` and use the ring utils as below:
`<button className={styles.notWorking}>Does not work</button>`
With the styles copied from the documentation:
`@apply px-4 py-2 font-semibold text-sm bg-white text-slate-700 border border-slate-300 rounded-md shadow-sm ring-2 ring-offset-slate-50 ring-pink-500 ring-offset-4;`

And the result is this: 
<img width="232" alt="image" src="https://user-images.githubusercontent.com/101905492/190179728-39426f6b-deac-4941-9ca7-a7cde20d60a2.png">

If I add `ring-inset` it becomes visible, but looks nothing like [the example from the docs](https://tailwindcss.com/docs/ring-offset-width).
<img width="224" alt="image" src="https://user-images.githubusercontent.com/101905492/190179879-48afa835-a010-46fc-8888-23e60954bc74.png">

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

You probably have a setup issue somewhere, works fine: https://play.tailwindcss.com/gtckKKb9qK

You can open a discussion with a reproduction repo attached so that we can debug whatever is going on. You likely forgot to configure your content paths: https://tailwindcss.com/docs/content-configuration
