### ISSUE TITLE
Gradient class not working with webpack?

### ISSUE THREAD

**Issue by NickWoodward** [tailwindlabs/tailwindcss#9332]
**What version of Tailwind CSS are you using?**

**3.1.8**

**What build tool (or framework if it abstracts the build tool) are you using?**

"postcss": "^8.4.16",
"postcss-loader": "^7.0.1",
"webpack": "^5.74.0"

**What version of Node.js are you using?**
node: v16.14.0

**What browser are you using?**
Chrome, Version 104.0.5112.101, but also happens in FF

**What operating system are you using?**
Win 10

**Reproduction URL**

// Minimal repo with webpack where the gradient class doesn't seem to work (but other classes do)
https://github.com/NickWoodward/gradient-example

// Minimal repo without webpack where the gradient class does work
https://github.com/NickWoodward/tailwind-starter

**Describe your issue**

Adding a gradient class (`bg-gradient-to-r from-cyan-500 to-blue-500` for example) doesn't seem to work as described in the docs when using webpack. I'm guessing it's something to do with the webpack and its loaders, because i don't seem to have a problem using just tailwind. Maybe I've misunderstood the docs, but I've not had any suggestions on a fix on SO either, other than older versions not supporting certain colors. However my version is up to date, and I've tried more obvious colors too.

Appreciate you guys are a small team, but would love being pointed in the right direction! 

Thanks,

Nick

**Comment by adamwathan** [comment]
Hey! So you’ve accidentally deleted the gradient classes by totally overriding the `backgroundImage` utilities in your config:

https://github.com/NickWoodward/gradient-example/blob/f4e8e3733a91f661caf19af4cddfd35385cd1c72/tailwind.config.js#L23

Move that under `extend` and you should be good to go 👍🏻

(On phone or would provide more specific code sample for you, sorry!)

**Comment by NickWoodward** [comment]
Ah perfect, thank you so much for the quick response!
