### ISSUE TITLE
rgba in linear-gradient does not work

### ISSUE THREAD

**Issue by yassh** [tailwindlabs/tailwindcss#9382]
**What version of Tailwind CSS are you using?**

v3.1.6

**What build tool (or framework if it abstracts the build tool) are you using?**

Next.js v12.2.0, PostCSS v8.4.14

**What version of Node.js are you using?**

v18.4.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/w1bYAm92KB

**Describe your issue**

`rgba` in `linear-gradient` does not work.

**Examples:**

Works:
```html
<div class="bg-[rgba(255,_0,_0,_0.5)]">...</div>
<div class="bg-[linear-gradient(90deg,_#FFFFFF,_#000000)]">...</div>
```

Does not work:
```html
<div class="bg-[linear-gradient(90deg,_rgba(255,_0,_0,_0.5),_#000000)]">...</div>
<div class="bg-[linear-gradient(90deg,_#FFFFFF,_rgba(255,_0,_0,_0.5))]">...</div>
```

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is something we already fix, and it will be available in the next release.

You can already try it by using the insiders build `npm install tailwindcss@insiders`.

Here is your same Tailwind Play using the insiders build: https://play.tailwindcss.com/Vlw47ZWoj0
