### ISSUE TITLE
background and text color for each option of select element doesn't work in firefox

### ISSUE THREAD

**Issue by sandeep-gh** [tailwindlabs/tailwindcss#9383]
**What version of Tailwind CSS are you using?**

v3.0 (from <script src="https://cdn.tailwindcss.com"></script>)

**What build tool (or framework if it abstracts the build tool) are you using?**

No build framework

**What version of Node.js are you using?**
N/A

**What browser are you using?**

Chrome (version 104.0.5112.105) and Firefox version 91.13.0esr 

**What operating system are you using?**

Raspian 

**Reproduction URL**

 https://codepen.io/sancodessometimes/pen/poVwMJO

**Describe your issue**
Background color  for select html element for each option works in chrome but not in firefox-esr.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

The background utilities only set the `background-color` css property so I'm afraid there is nothing we can do within Tailwind CSS itself to fix this issue.

My guess would be that the Firefox version you are using might be a few versions behind. When I open normal Firefox which has version 104.0.2 on my computer it does behave the same as in Chrome:
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/1834413/191468797-6450b3b0-db7d-4582-8b64-3b9f0addd98e.png">

However, each `option` looks like the default OS both in Chrome and Firefox on my machine. I don't think you can style those properly. That's one of the reasons why we created Headless UI to get control over styling. More info: https://headlessui.com/react/listbox

**Comment by sandeep-gh** [comment]
Thanks for taking a look also for heads up on the headless UI. Looks great and will take a look. Thank you.
