### ISSUE TITLE
space-x-* and space-y-* is not working with flex-row-reverse and flex-col-reverse

### ISSUE THREAD

**Issue by edgarasben** [tailwindlabs/tailwindcss#9411]
**What version of Tailwind CSS are you using?**
`v3.1.8`

**What build tool (or framework if it abstracts the build tool) are you using?**
`play.tailwindcss.com`

**What version of Node.js are you using?**
`play.tailwindcss.com`

**What browser are you using?**
`Brave (Chromium)`

**What operating system are you using?**
`macOS`

**Reproduction URL**
https://play.tailwindcss.com/iSSWGR1Ga3

**Describe your issue**
I just noticed that `space-x-*` and `space-y-*` doesn't work correctly with `flex-row-reverse` and `flex-col-reverse`. Instead of space in between children, the spacing is displayed on a side.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

That's expected behaviour, you have to use `space-x-reverse` in that case as well: https://tailwindcss.com/docs/space#reversing-children-order

**Comment by edgarasben** [comment]
Oh I see now, thank you for pointing it out @RobinMalfait!

I guess it would be more intuitive without needing to write `space-x-reverse`. But I guess there are technical limitations preventing this.

**Comment by RobinMalfait** [comment]
In you case since you are using `flex` already, I would recommend you to use `gap-x-32` or just `gap-32` which looks like the better solution to me.

The space utilities work by setting a margin on all but the first item to create that gap.

**Comment by edgarasben** [comment]
Good tip! But flex gap is not yet well supported (92% globally) and also it's not always I use flex when I need space between elements.

I think the space utility should ideally understand the reverse order and place margins on the correct side.
