### ISSUE TITLE
Safelist classes doesn't cascade other classes that are not in safelist

### ISSUE THREAD

**Issue by adriannecris** [tailwindlabs/tailwindcss#9440]
**What version of Tailwind CSS are you using?**
v3.1.8

**What build tool (or framework if it abstracts the build tool) are you using?**

```
"next": "^12.3.0",

devDep:
"postcss": "^8.4.16",
"sass": "^1.54.9",
"tailwindcss": "^3.1.8",
"webpack": "^5.74.0",
"webpack-cli": "^4.10.0",
"webpack-dev-middleware": "^5.3.3",
"webpack-dev-server": "^4.11.0"
```

**What version of Node.js are you using?**

lts/gallium -> v16.17.0

**What browser are you using?**

Chrome, Firefox

**What operating system are you using?**

Windows (but im running my nextjs on WSL Ubuntu 20)

**Reproduction URL**

https://codesandbox.io/s/winter-voice-v1qo6o?file=/src/App.js

**Describe your issue**
I've found a problem in my current project, I decided to replicate the problem in codesandbox, as you can see once you safelist a class, it will not cascade classes that are not in safelist. In my current project, pretty much most of the classes came from the backend.

![image](https://user-images.githubusercontent.com/35050635/192802392-b230680b-0b3a-45a0-b705-e9f1af155c84.png)
![image](https://user-images.githubusercontent.com/35050635/192802509-49c0d7a0-ad5f-4d7d-a180-b88819b27cfe.png)

Expected Result (note: I removed the class from the safelist)
![image](https://user-images.githubusercontent.com/35050635/192803588-8b7a5e9a-8d24-4062-9e8c-7153bc7a2e0f.png)

**Comment by adamwathan** [comment]
Hey! This is intended behavior — when you add two classes that conflict like that the result is indeterministic. The order of the CSS is based on which classes Tailwind "sees" first, and anything in the safelist is seen before things in your HTML.

The order of classes in your HTML doesn't matter to the browser, only the order of the classes in your CSS.

For example, both of these divs are going to be green, doesn't matter what order the classes are in in your HTML:

```html
<style>
  .bg-red {
    background: red
  }
  .bg-green {
    background: green
  }
</style>

<div class="bg-red bg-green"></div>
<div class="bg-green bg-red"></div>
```

https://jsfiddle.net/wg1yve54/

So the solution here is to only add the class you actually want to take effect 👍
