### ISSUE TITLE
bg-[url('')] doesn't work with external urls with PHP

### ISSUE THREAD

**Issue by 536f6e6179** [tailwindlabs/tailwindcss#9446]
Hey guys,

as the title says, I have a problem with bg-[url('')]. If you connect this variable with PHP to display an external image from the database, bg-[url('')] is not executed at all, but it works if you take PHP out again and leave it hardcoded which is not the point.

**Tailwind version:**
3.1.8

**Framework:**
Laravel 9 w/ Vite

**Node.js version**
16.15.0

**Tested on browsers:**
Chrome, Firefox & Safari

**Operating System:**
macOS

**Examples:**

_Hardcoded works_
```
<div class="bg-[url('https://images.pexels.com/photos/12123082/pexels-photo-12123082.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load')] w-full h-full"></div>
```

_Included PHP doesn't work_
```
@php ($image = 'https://images.pexels.com/photos/12123082/pexels-photo-12123082.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load')
<div class="bg-[url('{{ $image }}')] w-full h-full"></div>
```

And it works as well, with style="background-image:url('')" but not class="bg-[url('')]"

Maybe one of you have the same issue like me or fixed it.

**Comment by adamwathan** [comment]
Hey! See docs: https://tailwindcss.com/docs/content-configuration#dynamic-class-names

**Comment by 536f6e6179** [comment]
I already saw it but it's not how I need it. Every entry in my database have different images and is not defined thats the problem.

**Comment by vashfox** [comment]
same issue

**Comment by mimoudix** [comment]
same issue , just use `style="background-image: url('php object here')"`

**Comment by MBousss** [comment]
> same issue , just use `style="background-image: url('php object here')"`

This isn't a proper solution. It's doesn't allow for responsive breakpoints. I don't think this issue should have been closed.

**Comment by vinayakkulkarni** [comment]
```html
<div class="before:bg-[url('{{ $image }}')] w-full h-full"></div>
```

how would you handle this case?

**Comment by wongjn** [comment]
I'd do:

```html
<div
  class="before:bg-[image:var(--bg)] w-full h-full"
  style="--bg: url('{{ $image }}')"
>
```
