### ISSUE TITLE
Type issue when creating a plugin.

### ISSUE THREAD

**Issue by antondalgren** [tailwindlabs/tailwindcss#9499]
**What version of Tailwind CSS are you using?**

v3.1.8

**What build tool (or framework if it abstracts the build tool) are you using?**

Next.js 12.3.1

**What version of Node.js are you using?**

v16

**What browser are you using?**
N/A

**What operating system are you using?**

MacOS

**Reproduction URL**
https://playcode.io/979683

**Describe your issue**
Typing expects `content` to be present in the second argument but the [example](https://tailwindcss.com/docs/plugins#providing-default-values) in the docs shows that it is not required. Should there be a content, and if so what value?

**Comment by thecrypticace** [comment]
Hey, thanks for reporting this one. Yeah this is definitely a mistake. I've merged in the fix for the types and it'll go out in v3.2. Appreciate it!
