### ISSUE TITLE
Tailwind adds space after a colon for paged media (print css) 

### ISSUE THREAD

**Issue by deadcoder0904** [tailwindlabs/tailwindcss#9528]
**What version of Tailwind CSS are you using?**
3.1.8

**What build tool (or framework if it abstracts the build tool) are you using?**
postcss-cli

**What version of Node.js are you using?**
v18.9.1

**What browser are you using?**
Chrome

**What operating system are you using?**
macOS

**Reproduction URL**
https://play.tailwindcss.com/gF6jqBljqr?file=css

**Describe your issue**

VSCode inserts a space after a colon for paged media.

For example, the below could should not have space between `:` & `first`

```css
@page: first{
  size: 5.5in 8.5in;
  margin: 0;
}
```

It should look like:

```css
@page:first {
  size: 5.5in 8.5in;
  margin: 0;
}
```

If you open the Tailwind Play & click `Tidy` on `CSS` tab, you will see how it gets formatted.

This [has been discussed before](https://github.com/tailwindlabs/tailwindcss/discussions/6284) but those solutions don't work for me. Probably, because I'm using Paged Media.

I tried inserting the following in `.vscode/settings.json`:

```json
{
  "files.associations": {
    "*.css": "tailwindcss"
  }
}
```

But it didn't work.

**Comment by adamwathan** [comment]
This looks like a bug in Prettier — Tailwind doesn't actually do any formatting itself. Can see the reproduction in Prettier here:

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABADgQwOZyQMwEsAnAZxgAJgAdKCi0wgLzwoFYA6NwugDi54BuWvQC2mYth5IKABmFQAviAA0ICOhiFopZKAnEIAdwAKEhLpSYANkcwBPXWoBGxTGADWcGAGVMouAAZHjhkfBtSOBc3T28fLDAebGQYYgBXKJA4UWc4ABM8-MDMKGw0nDgAMQhicRgtUuQQTDSYCFUQAAsYUWsAdU7CeFIEuB8LIcIANyH7JrBSJxAeSOIYEzdscTCIzIArUgAPHyTrOABFNIh4HetItSwyOGJ5xY70Yh4YPsI8mE7kLxZA9DJE+m50E0PnBVlNQmoAI5XeAbDSWZqkAC0UDg+XyHWIcCRJDgGxw2wIuzUkVEhBS6UyjFKZ0u11ClLumRgmGcPz+AKQACY1KlMIRrEkAMIQUQUrKkNgdNKRAAqPMs4U5aimGQAklBCrAfGBPpoAIIGnwwexnW6RRSKIA

**Comment by deadcoder0904** [comment]
@adamwathan any solutions on your end since you've already made refactoring ui with paged media? or should i open a bug on prettier?

**Comment by adamwathan** [comment]
Unfortunately I think the only solution is to not use Prettier for CSS until it's fixed if you have rules like that in your CSS :( Going to close since not a Tailwind issue but hopefully they can resolve that in Prettier for you!

**Comment by adamwathan** [comment]
Looks like it's actually fine, you just need to write it with a space after `@page`.

Here's the example from MDN:

<img width="821" alt="image" src="https://user-images.githubusercontent.com/4323180/195417454-f46adc55-35eb-4481-808c-f5be3ecd3a0c.png">

Does that work with Prince? Prettier handles it properly if you write it that way anyways 👍

**Comment by deadcoder0904** [comment]
can confirm, that works with prince & prettier formats it correctly. thanks adam :)
