### ISSUE TITLE
Using arbitrary value for rounded (e.g. rounded-l-[30px]) and rounded-r-full together doesn't seem to work properly

### ISSUE THREAD

**Issue by dominicarrojado** [tailwindlabs/tailwindcss#9529]
**What version of Tailwind CSS are you using?**

For example: v3.1.8

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: postcss-cli 8.4.17, Next.js latest

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://codesandbox.io/s/cranky-shirley-yru1ui?file=/package.json

**Describe your issue**

Using arbitrary value for rounded left (`rounded-l-[30px]` and using `rounded-right-full` doesn't seem to work. When `rounded-right-full` is removed, it will work.

**Comment by adamwathan** [comment]
Hey! Check out this previous discussion for the relevant info: https://github.com/tailwindlabs/tailwindcss/discussions/7402
