### ISSUE TITLE
can't use color name as variable 

### ISSUE THREAD

**Issue by SaqibSattar** [tailwindlabs/tailwindcss#9534]
**What version of Tailwind CSS are you using?**

v3.1.8

**What build tool (or framework if it abstracts the build tool) are you using?**

Next.js 12.3.1

**What version of Node.js are you using?**

v14.17.1

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Describe your issue**

I'm fetching my colors array from DB and want to show those colors on frontend side, but it's not showing my correct colors
<img width="463" alt="1" src="https://user-images.githubusercontent.com/47052057/195434597-13e6f034-1b5d-4371-9983-e9fa8adc1f7a.PNG">
<img width="735" alt="2" src="https://user-images.githubusercontent.com/47052057/195434631-fab8ed63-441a-4ffe-9104-6c7a320c519a.PNG">
![image](https://user-images.githubusercontent.com/47052057/195435346-1998fed7-f50d-4815-a6eb-fd6f07d34bbe.png)

**Comment by adamwathan** [comment]
Hey! See the docs: https://tailwindcss.com/docs/content-configuration#dynamic-class-names
