### ISSUE TITLE
Insiders builds content paths not detected

### ISSUE THREAD

**Issue by gigsta12** [tailwindlabs/tailwindcss#9565]
**What version of Tailwind CSS are you using?** 
insiders.2a88642

**What build tool (or framework if it abstracts the build tool) are you using?**
Reproduced in two different environments
Parcel 2.7.0, postcss 8.4.18

Webpack 4.10.0, postcss 8.4.18

**What version of Node.js are you using?**
v16.14.0

**What browser are you using?**
Chrome

**What operating system are you using?**
Windows 10

**Reproduction URL**
https://github.com/gigsta12/TailwindContentRepro

**Describe your issue**
Using the current versions of insiders e.g. 2a88642 the content paths are not identified when you run the project. None of the css is generated in the output files.

The following is shown in the console.
```
console: warn - No utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CSS configuration.   

console: warn - https://tailwindcss.com/docs/content-configuration
```
This has occurred in both in my existing larger webpack project but also in the repro project listed above. Unsure if this is related to the new multiple `@config` files? Reading the announcement I wasn't entirely sure if with the upcoming 3.2, the `@config` is now required to be included in the input css file so I included it anyways.

**Comment by adamwathan** [comment]
Hey! I can't seem to reproduce this, when I clone your project and run it I don't see any errors and the served page has the styles I'd expect:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/4323180/196031345-a0e2e69a-99a5-4a27-b34d-be1a812016c4.png">

I did make sure to remove the `^` in `package.json` where the Tailwind version was specified before running `npm install` because it causes the wrong version of the insiders build to be installed (it thinks a higher number is newer and often installs a build with a different SHA, when really these are all just Git SHAs so the number has no correlation with recency).

```diff
   "dependencies": {
-    "tailwindcss": "^0.0.0-insiders.2a88642"
+    "tailwindcss": "0.0.0-insiders.2a88642"
   }
```

Can you try that and run `npm install` again and see if it makes any difference?

**Comment by gigsta12** [comment]
Hey, I removed the `^` as suggested and then cleaned and reinstalled the npm packages. I am still getting the same issue.

![image](https://user-images.githubusercontent.com/1834690/196034343-126f3404-d159-40d4-b5b3-60325e9e9834.png)

I had a colleague of mine clone and run the project and he is also seeing the same thing.

**Comment by thecrypticace** [comment]
Looks like it only does this on Windows. Not sure why but I can confirm that, on Windows, this does indeed happen.

**Comment by thecrypticace** [comment]
Thanks for brining this issue to our attention! I figured out the problem and have opened a PR to fix it. We have some other unrelated stuff that's causing the build to fail which I'll need to wait for us to fix before merging it.

**Comment by thecrypticace** [comment]
I'm working on getting a new insiders build out right now. Hang tight!

**Comment by thecrypticace** [comment]
Okay, there's a new insiders build out! Can you give that a test and see if your problems are fixed?

**Comment by gigsta12** [comment]
Sure let give it a test and circle back here

**Comment by thecrypticace** [comment]
Should just need to do `npm install tailwindcss@insiders` to get the latest I think. `npm upgrade` doesn't work for them b/c of the use of a sha instead of incrementing version number.

**Comment by gigsta12** [comment]
Tested on both projects and the issue is fixed. Appreciate getting it fixed so quickly!

**Comment by thecrypticace** [comment]
Of course — thank you for letting us know! ✨ 

The tl;dr on what happen is that Windows's different path separator occasionally requires a bit extra work that otherwise doesn't need to happen and it was missed in this case.
