### ISSUE TITLE
@parcel/transformer-postcss: @apply is not supported within nested at-rules like @bottom-left. You can fix this by un-nesting @bottom-left.

### ISSUE THREAD

**Issue by deadcoder0904** [tailwindlabs/tailwindcss#9583]
**What version of Tailwind CSS are you using?**

3.1.8

**What build tool (or framework if it abstracts the build tool) are you using?**

parcel 2.7.0

**What version of Node.js are you using?**

18.9.1

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/deadcoder0904/parcel-tailwind-paged-media-css

**Describe your issue**

I'm trying to use Paged Media CSS with Tailwind. I have setup nesting before but can't get this working. Not even sure if it's nesting or not.

### src/index.css

```css
@page :right {
  @bottom-left {
    margin: 10pt 0 30pt 0;
    border-top: 0.25pt solid #666;
    content: 'Our Dogs';
    font-size: 9pt;
    @apply text-red-400;
  }
}
```

The `@apply` doesn't work. I get an error that says:

```bash
🚨 @parcel/transformer-postcss: ~/Code/Forked/parcel-tailwind-paged-media-css/src/index.css:15:5: @apply is not supported within nested at-rules like @bottom-left. You can fix this by un-nesting @bottom-left.
CssSyntaxError: ~/Code/Forked/parcel-tailwind-paged-media-css/src/index.css:15:5: @apply is not supported within nested at-rules like @bottom-left. You can fix this by un-nesting @bottom-left.
    at Input.error (~/Code/Forked/parcel-tailwind-paged-media-css/node_modules/postcss/lib/input.js:148:16)
    at AtRule.error (~/Code/Forked/parcel-tailwind-paged-media-css/node_modules/postcss/lib/node.js:60:32)
    at processApply (~/Code/Forked/parcel-tailwind-paged-media-css/node_modules/tailwindcss/lib/lib/expandApplyAtRules.js:313:25)
    at ~/Code/Forked/parcel-tailwind-paged-media-css/node_modules/tailwindcss/lib/lib/expandApplyAtRules.js:476:9
    at ~/Code/Forked/parcel-tailwind-paged-media-css/node_modules/tailwindcss/lib/processTailwindFeatures.js:55:50
    at plugins (~/Code/Forked/parcel-tailwind-paged-media-css/node_modules/tailwindcss/lib/index.js:33:63)
    at LazyResult.runOnRoot (~/Code/Forked/parcel-tailwind-paged-media-css/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (~/Code/Forked/parcel-tailwind-paged-media-css/node_modules/postcss/lib/lazy-result.js:393:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.transform (~/Code/Forked/parcel-tailwind-paged-media-css/node_modules/@parcel/transformer-postcss/lib/PostCSSTransformer.js:287:9)
```

I like using `@apply` in CSS but this doesn't work. Ideally, it would unnest but from the examples i'm reading unnesting happens with `&`.

I also have `tailwindcss/nesting` in `.postcssrc`:

### .postcssrc

```json
{
  "plugins": {
    "tailwindcss/nesting": {},
    "tailwindcss": {}
  }
}
```

I'm not sure if this is as intended or a bug.

Is it possible to use Tailwind with Paged Media at all? Or should I not use it this way,i.e, in `@page :right`?

**Comment by adamwathan** [comment]
Hey! Yeah this is a bug, our nesting detection isn't considering the fact that this type of nesting isn't really a problem. We have plans for reworking how `@apply` works completely in the near future though so I don't think we are going to be able to justify investing any time into fixing this one.

Instead I'd recommend just using `theme()`:

```css
@page :right {
  @bottom-left {
    margin: 10pt 0 30pt 0;
    border-top: 0.25pt solid #666;
    content: 'Our Dogs';
    font-size: 9pt;
    color: theme(colors.red.400);
  }
}
```

Going to close as a "won't fix" since we are going to rework all this like I mentioned, but hopefully that solution helps 👍🏻
