### ISSUE TITLE
CLI fails because of missing 'micromatch' dependency in package.json when using Yarn Modern with PNP

### ISSUE THREAD

**Issue by real-az** [tailwindlabs/tailwindcss#9619]
**What version of Tailwind CSS are you using?**

v3.2.0

**What version of Yarn are you using?**

3.2.4

**Describe your issue**

v3.2.0 adds the 'micromatch' dependency in the [code](https://github.com/tailwindlabs/tailwindcss/blob/master/src/cli/build/watching.js#L5) but does not have it in the package.json file which causes Yarn Modern with PNP to fail calls to CLI:

`yarn tailwindcss --version`
fails with
`Error: tailwindcss tried to access micromatch, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
Required package: micromatch`

**Proposed solution**

Add the 'micromatch' package to dependencies in package.json.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #9620, and will be available in the next release.

You can already try it by using the insiders build `npm install tailwindcss@insiders`.
