### ISSUE TITLE
Tailwind CSS configuration could not detect utility classes

### ISSUE THREAD

**Issue by anrcry** [tailwindlabs/tailwindcss#9632]
**What version of Tailwind CSS are you using?**
3.1.8

**What build tool (or framework if it abstracts the build tool) are you using?**

- vite-3.1.8
- postcss-8.4.18
- autoprefixer-10.4.12

**What version of Node.js are you using?**

node version `v18.11.0`

**What browser are you using?**

Brave Browser (Chromium)

**What operating system are you using?**

Windows 10

**Reproduction URL**

[Soon will be updated]

**Describe your issue**

So I have configured `tailwindcss.config.cjs` as required by the documentation.

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,tsx,ts,html}",
    "./index.html",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

This is a used within a project using vitejs and the react-typescript template. When I run `npm run dev` to spin up the dev server the following pops up:

> warn - No utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CSS configuration.
>
> warn - https://tailwindcss.com/docs/content-configuration

I cannot seem to fix the error.

**Comment by anrcry** [comment]
Issue has been resolved. My "build" folder had a file named "index.html". The `content` of the `tailwindcss.config.cjs` file did not include the same.

My solution:

```js
...
content: [
    './src/**/*.{js,jsx,tsx,ts}',
    '**/index.html',
  ],
...
```

**Comment by BenXi630** [comment]
So am I. Did you solve it
