### ISSUE TITLE
Tailwind v3.2.1 & prettier-plugin-tailwindcss v0.1.13 doesn't work in php files

### ISSUE THREAD

**Issue by arifur-rahman-arif** [tailwindlabs/tailwindcss#9661]
**What version of Tailwind CSS are you using?**

For example: v3.2.1

**What build tool (or framework if it abstracts the build tool) are you using?**

webpack 5.74.0

**What version of Node.js are you using?**

For example: v16.17.0

**What browser are you using?**

For example: Chrome, Firefox

**What operating system are you using?**

For example: Linux

**Describe your issue**

Tailwind plugin **prettier-plugin-tailwindcss** works perfectly on HTML, JS, TS files. But as I was working on PHP files in my VScode, when I save my files or run the prettier command that is defined in my package.json file
Tailwind classes seem to have no effect by the plugin as it's a PHP file. But if I change the file extension to a HTML file it works perfectly. I assume prettier plugin for tailwind don't have php support

I've not tested other language files like python, ruby etc.
If anyone can assure than this class sorting plugin works well with other language files that would be great

**Comment by adamwathan** [comment]
Closing in favor of the issue on the actual plugin repo 👍🏻
