### ISSUE TITLE
Collapse functionality is broken v3.2.1

### ISSUE THREAD

**Issue by nkalodimas** [tailwindlabs/tailwindcss#9663]
**What version of Tailwind CSS are you using?**

v 3.2.1

**What build tool (or framework if it abstracts the build tool) are you using?**

CDN

**What version of Node.js are you using?**

**What browser are you using?**

Chrome

**What operating system are you using?**

**Reproduction URL**
Visit https://tailwind-elements.com/docs/standard/components/accordion/ and click show code on the first example.
The accordion body is getting shown and immediately disappears afterwards.

Also visit https://tailwind-elements.com/docs/standard/components/collapse/ and click show code on the first example.

The element that contains the code is getting shown and immediately disappears afterwards.

**Describe your issue**

When we use data-bs-toggle="collapse" there is a bug and the collapse class is not getting removed at the target element although show class is added.

**Comment by adamwathan** [comment]
Hey! Tailwind Elements is a third party project and has nothing to do with us, best to report the issue there 👍🏻

**Comment by outdoorsman** [comment]
I'm having this issue as well. I found this StackOverflow that describes one way to do a sort of hack if you want to give preference to the Bootstrap class. Something like that could be done to give preference to TailwindCss too if desired.

https://stackoverflow.com/questions/74520409/accordion-closing-imediately-after-opening-with-tailwind-css#answer-74535087
