### ISSUE TITLE
CLI watch mode not working correctly when using visual studio

### ISSUE THREAD

**Issue by tecxx** [tailwindlabs/tailwindcss#9667]
**What version of Tailwind CSS are you using?**

TailwindCSS CLI: v3.2.1
Visual Studio: 2022 - Version 17.3.6

**What build tool (or framework if it abstracts the build tool) are you using?**

Visual Studio

**What operating system are you using?**

Windows 10

**Describe your issue**

the tailwind cli in watcher mode: tailwind.exe -i ./Styles/site.css -o ./wwwroot/css/site.css --watch --verbose
edit a .razor or cshtml file with Notepad++ and save the file - the watcher sees the change and rebuilds correctly

but when i open visual studio and edit the exact same file in vstudio, and save the file, nothing happens.
as you can see on the screenshot, notepad++ detects there is a change, but the tailwind cli tool does not

![image](https://user-images.githubusercontent.com/4305825/198109303-86211b47-a706-435f-9035-d82dffa9b21f.png)

config:

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./**/*.{razor,html,cshtml}"],
    theme: {
        extend: {},
    },
    plugins: [],
}
```

i then made a copy of a cshtml file in windows explorer, and noticed the watcher is not reacting on the new file as well. only when i restart the cli tool, edits in the new file trigger a rebuild. this made me investigate some more: 
changing the configuration to
`content: ["./Pages/*.*"],`

and saving a .razor page in visual studio in this folder leads to this crash:

![image](https://user-images.githubusercontent.com/4305825/198111941-77657f67-530b-4b0e-bae2-cbfd9f097a67.png)

looks like visual studio is saving files via a temp file, and then renames it. this way the cli watcher doesn't see it anymore.
is this possible to fix? or is this just happening on my computer? :)

**Comment by pm64** [comment]
I'm experiencing similar behavior, and it has left me at a standstill.

From what I'm observing, if your project is loaded in Visual Studio, the watcher becomes oblivious to all changes, whether they took place in Visual Studio, Notepad++, or whatever (however -- in my case, even using the --verbose option, Tailwind CSS does not display any indication of an exception).

If you then close Visual Studio and re-start Tailwind CSS, the watcher's behavior returns to normal (rebuilding in response to changes made in Notepad++, for example).

**Comment by JereKaplas** [comment]
I've also noticed similar things after updating to 3.2.0 (3.2.1 doesn't fix it either). Changes in Visual Studio don't seem to trigger rebuilding.

The same project in VS Code will trigger rebuilds on changes though.

**Comment by thepra** [comment]
I did update too and I'm having tailwindcss CLI just scanning and updating the output file the first time, then when I change something in Visual Studio 2022 it's as if nothing happened for the CLI.

**Comment by krompaco** [comment]
We see the behavior after a while both with Visual Studio and VS Code and not only with dotnet. Changing back to 3.1.7 and all work as expected.

**Comment by 1player** [comment]
I probably have the same issue in Emacs, so perhaps it's not fault of the editor.

**Comment by ds1971** [comment]
Sounds like the same issue I had (just added a fresh TW code to existing TS/next.js application). Using a dummy fix: in order to get the fresh changes, I'm saving unchanged tailwind.config.js file. A related post in SO: https://stackoverflow.com/questions/74240061/tailwind-doesnt-recognise-all-w-styles

**Comment by jbrocher** [comment]
I am experiencing the same issue using `tailwindcss 3.1.2`. My editor is neovim. I agree with @TunkShif tho, it doesn't seem editor related. Downgrading to 3.1.8 fixes the issue for me.

**Comment by thecrypticace** [comment]
Hey all, I merged a PR by @natrys that _should_ fix these problems. If you could give the latest insiders build a test and report back here it would be much appreciated.

I've done some testing on my own and it appears that Visual Studio on Windows is finally working again and VIM on Linux (and WSL even) when it performs backups for saves.

Note: that WSL fs events are effectively broken under `/mnt/{a,b,c,d,…}` so you have to use `--poll` or be in a different, non-shared mount.

Gonna close as we believe the issue has been fixed _but_ will re-open if there turns out to be more things we need to address w/ regards to the CLI watching.

**Comment by thepra** [comment]
I tested it today and I have to say that the fix doesn't work, the first time starts all well and after changes in VS 2022 nothing is perceived changed from the cli

**Comment by krizpoon** [comment]
Nothing worked. I ended up using `fb-watchman` to trigger the build process.
