### ISSUE TITLE
Possible issue with .collapse class selector not respecting alpine's 'show' (.show class)

### ISSUE THREAD

**Issue by daveb1014** [tailwindlabs/tailwindcss#9674]
**What version of Tailwind CSS are you using?**

v3.2.1

**What build tool (or framework if it abstracts the build tool) are you using?**

Laravel 9.36.4 with vite 3.2.0

**What version of Node.js are you using?**

v18.0.0

**What browser are you using?**

Chrome Version 106.0.5249.119 (Official Build) (64-bit)

**What operating system are you using?**

Windows 10

**Reproduction URL**

To the best of my knowledge this is correct... I could have this wrong though

Tailwind Play:
https://play.tailwindcss.com/ypOHcH5T84

Select V2.2.19 to see expected behaviour, change to v3.2.1 to see (what I think to be) broken behaviour.

**Describe your issue**

Issue was first observed using the Tailwind-Elements accordion component with a Laravel & Tailwind CSS project, and the same issue can be observed on the Tailwind-Elements site with all of the "Show code" example buttons:

https://tailwind-elements.com/docs/standard/components/accordion/

The issue is that when expanding a 'collapsible' component, the contents are shown while the collapsible is expanding or collapsing but once it is fully expanded, the contents are suddenly hidden.

They appear to be hidden due to the `collapse` class applying `.collapse { visibility: collapse; }`

In Tailwind 3.1.8 this selector looked like

```
.collapse:not(.show) {
    display: none
}
```

More details in a Tailwind-Elements issue I posted: https://github.com/mdbootstrap/Tailwind-Elements/issues/1085

**Comment by adamwathan** [comment]
Hey! So `collapse` is a new utility added in v3.2, we did not have any CSS using that class in v3.1.8. That must be some extra CSS included with Tailwind Elements that’s now conflicting with core. Unfortunately this is just the nature of using CSS from multiple sources, there are chances of conflicts. Nothing we can really do about it on our end, no plans to change our class or anything to accommodate it. They’ll need to change how they handle this if they want their stuff to keep working with v3.2.


You can disable the “visibility” core plugin in your config if you want and add custom utilities to bring back the “visible” and “invisible” classes using a plugin or just in your CSS 👍🏻
