### ISSUE TITLE
Adjust animation-duration is currently not possible

### ISSUE THREAD

**Issue by jonasdev** [tailwindlabs/tailwindcss#9731]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/9730

<div type='discussions-op-text'>

<sup>Originally posted by **jonasdev** November  4, 2022</sup>
I am using `animation-pulse` for an icon. Looks great.
But I want to adjust the `animation-duration` to be a tiny bit slower.
It is running `2000ms` by default, I want it to be `3000ms`.

Currently I've tried with `duration-[3000ms]` - which doesn't have any effect, since this is `transform-duration` and **not** `animation-duration`.

I think the class for `animation-duration` is missing?</div>

**Comment by RobinMalfait** [comment]
Let's keep the feature suggestion in the discussion 👍
