### ISSUE TITLE
Can't use arbitrary variants with group

### ISSUE THREAD

**Issue by M1CK431** [tailwindlabs/tailwindcss#9860]
**What version of Tailwind CSS are you using?**
v3.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**
Vue v3.2.45, Vite v3.2.4

**What version of Node.js are you using?**
v19.1.0

**What browser are you using?**
Vivaldi v5.5.2805.44 (Chromium based)

**What operating system are you using?**
Archlinux

**Reproduction**

```html
<div class="[&>div:first-child]:group">
  <!-- that part of the HTML come from third party library -->
  <div>
    <span>Header title</span>
    <span>
      <button class="opacity-0 group-hover:opacity-100">
        Extra header action
      </button>
    </span>
  </div>
  <div>Here come the main content</div>
  <!-- end of third party code -->
</div>
```

**Describe your issue**

I'm trying to use the arbitrary variant `[&>div:first-child]` to target the first child `div` (aka header) and add the `group` class on it. I can't directly add the `group` class on the "header" `div` because that part of the DOM come from third party library. My goal is to show the extra header action button when the user hover the "header" `div` of the third party component.

I haven't see anything in the documentation which forbid that kind of combination but perhaps I miss it 🤷🏼‍♂️

**Comment by reinink** [comment]
Hey! So the `group` class in Tailwind CSS is only a marker for variants like `group-hover` to target, so what you're trying to do here unfortunately won't work. However, you can use an arbitrary variant to accomplish something similar:

```html
<div class="group">
  <!-- that part of the HTML come from third party library -->
  <div>
    <span>Header title</span>
    <span>
      <button class="opacity-0 [.group_div:first-child:hover_&]:opacity-100">
        Extra header action
      </button>
    </span>
  </div>
  <div>Here come the main content</div>
  <!-- end of third party code -->
</div>
```

This generates the following CSS:

```css
.group div:first-child:hover .\[\.group_div\:first-child\:hover_\&\]\:opacity-100 {
  opacity: 1;
}
```

Pretty gnarly, but it works 😅

You can see this in action in this Play I just created: https://play.tailwindcss.com/hZ2bHRZJQt

Hope that helps! 🤙

**Comment by M1CK431** [comment]
It helps a lot, thank you for explanation and working demo 🙏🏼 😘 
`_&` at the end of the child selector was the key I didn't found while trying to achieve my goal myself.
