### ISSUE TITLE
--watch doesn't work in background

### ISSUE THREAD

**Issue by stfnx** [tailwindlabs/tailwindcss#9870]
**What version of Tailwind CSS are you using?**

v3.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**

TailwindCSS standalone binary

**What operating system are you using?**

Happens on both Linux and Windows

**Describe your issue**

I have a shell script to start my development server:
```
#!/bin/env bash

# Get absolute path to project's root direcotry
PROJECT_ROOT=$(realpath "$0")
PROJECT_ROOT=$(dirname "$PROJECT_ROOT")

# Run tailwind watcher in background
${PROJECT_ROOT}/tailwind/tailwind_bin_v3.2.4 \
--watch \
--config ${PROJECT_ROOT}/tailwind/config.js \
--input ${PROJECT_ROOT}/tailwind/main.css \
--output ${PROJECT_ROOT}/app/static/css/tailwind.css &

# Run flask dev server in debug mode
flask --debug run
```

This worked perfectly fine with TailwindCSS v3.1.8 but now I upgraded to v3.2.4 and it doens't work anymore.

Downgrading to v3.1.8 makes it work again.

# Expected behaviour

When running the script, the Tailwind watcher should run as a background process and I should see its output (Rebuilding...Done in 267ms) in stdout.

# Actual behaviour

The Tailwind watcher doesn't run and I can't see any output in stdout.

# Note

When running the command in foreground (without `&` at the end) it works as expected. So as a workaround I run flask in background and tailwind in foreground.

**Comment by thecrypticace** [comment]
Hey, I've added a `--watch=always` option to the CLI to work around this behavior. It should be in our insiders build in a few minutes. Once it's published you can test it by using `npm install tailwindcss@insiders`.

I've verified this on my end that it seems to work. Please let me know if you encounter any more issues. Thanks! ✨

**Comment by stfnx** [comment]
Are prebuilt standalone binaries distributed for the insider version? I'm not going to use npm.

**Comment by gypsydave5** [comment]
I was running the tailwindcss standalone cli binary on a watch from inside a Gradle task - the `--watch=always` trick worked like a charm. Just leaving this here to say thanks and as documentation

**Comment by hayesall** [comment]
This is inconsistent for me with zsh, but nohup seems to be an okay workaround:

```bash
nohup npx tailwindcss -i ./input.css -o ./output.css --watch=always </dev/null &

# Optional: capture an id and send the kill signal when finished
tid=$!
kill -9 $tid
```

**Comment by JamesHutchison** [comment]
Can we make this the default behavior or error if it gets an immediate EOF or something? If it starts in a non-interactive shell, ending immediately can not be the desired behavior.

**Comment by tamara-nexus** [comment]
Hello,

This thread helped me. Can someone verify if this is the best way to have a bash script compile multiple separate files at once and watch for change.

My main issue was that:

`npx tailwindcss -i "$input_file" -o "$output_file" --watch &`
Did not generate any output files.

`npx tailwindcss -i "$input_file" -o "$output_file"`
This generated output but only once. No watch.

Based on this thread:
`npx tailwindcss -i "$input_file" -o "$output_file" --watch=always &`
This made my script work

Full bash script:

`#!/bin/bash

# Define the base directory to search
BASE_DIR="./src"

# Define a list of input and output files
INPUT_FILES=($(find "$BASE_DIR" -type f -name '*-tw.css'))

# Function to process each file
process_file() {
  local input_file=$1
  local output_file="${input_file%-tw.css}.css"
  echo "Processing $input_file -> $output_file"
  npx tailwindcss -i "$input_file" -o "$output_file" --watch=always &
}

# Export the function for use in subshells
export -f process_file

# Process each file in the background
for file in "${INPUT_FILES[@]}"; do
  process_file "$file"
done

# Inform the user that processes have started
echo "All tailwindcss watch processes started."

# Keep the script running to allow the watch processes to continue
wait

echo "All tailwindcss watch processes completed."`

**Comment by reorx** [comment]
this drives me mad man
