### ISSUE TITLE
does not reproduce classes for template literals in js

### ISSUE THREAD

**Issue by sifat0666** [tailwindlabs/tailwindcss#9889]
i am using tailwind with next js and i have to call the classes individually first or else the classes are not recognized by tailwind. i am using a map to display different colors

```              
           <div className="flex gap-x-2">
              {labelsClasses.map((label, i) => (
                <span
                  key={i}
                  className={`bg-${label}-500 w-6 h-6 rounded-full flex items-center justify-center cursor-pointer`}
                ></span>
              ))}
            </div>
 ```

**Comment by adamwathan** [comment]
Hey! Yeah this is expected/by design, check out the relevant documentation here:

https://tailwindcss.com/docs/content-configuration#dynamic-class-names
