### ISSUE TITLE
@screen on dynamic (min-*, max-*) breakpoints

### ISSUE THREAD

**Issue by jemhuntr** [tailwindlabs/tailwindcss#9908]
**What version of Tailwind CSS are you using?**

3.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss-cli 10.0.0 with postcss-import and tailwindcss/nesting

**What version of Node.js are you using?**

16.16

**What browser are you using?**

N/A

**What operating system are you using?**

Windows

**Reproduction URL**

https://play.tailwindcss.com/HvPuPtAlc5?file=css

**Describe your issue**

Hi! Is there any way to get the min/max dynamic breakpoints to work with the `@screen` directive or the `screen()` function? Both of these currently don't work on 3.2 as far as I can see:

```css
@screen max-lg {
  ...
}

@media screen(max-lg) {
...
}
```

The dynamic breakpoint variants work great on classes & @apply rules directly; only the screen functions seem to be non-functional. It'd be great if this can be included so I can apply bigger chunks of mobile-only styles!

**Comment by reinink** [comment]
Hey! So we definitely discussed this when we were adding the new `min` and `max` variants to `v3.2`, but decided against it for now just to keep things simple. We may reconsider this in the future, but for now you can write similar media queries in your CSS like this:

```css
@media not all and (min-width: theme('screens.lg')) {
   ...
}
```

Admittedly not as nice, but works. We'll keep this feature request in mind for future version of the framework 👍

**Comment by mrleblanc101** [comment]
@reinink 
How is it more simple ? 
It actually caused me quite a bit of confusion.
Because my breakpoint worked in class but not @screen.
This does not seem to be documented anywhere.

**Comment by sovetski** [comment]
Any update on this?
