### ISSUE TITLE
duplicated tailwind  rules in producion css file

### ISSUE THREAD

**Issue by superchangme** [tailwindlabs/tailwindcss#9920]
**What version of Tailwind CSS are you using?**

For example: v3.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: postcss-cli 8.3.1, vite 3.2,vue 3.4

**What version of Node.js are you using?**

For example: v14.19.1

**What browser are you using?**

For example: Chrome

**What operating system are you using?**

For example: Windows

**Reproduction URL**

A Tailwind Play link or public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.

**Describe your issue**

1. i found my build output css file has duplicated tailwind  rules, file contents like below

```css
#root .flex-1{
flex:1 1 0%
}
#root .flex-1{
flex:1 1 0%
}
```
my use way like this

``` css
// @/assets/base.css

@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities"; 

```

``` ts
// src/main.ts
import "@/assets/base.css";

```

------------------------------------------------

2. i look official documents and github, try many ways this day,at last i found one way to avoid build duplicate tailwind rules.
delete tailwind import define in css and use import in javascript.

``` ts
// src/main.ts
import "tailwindcss/tailwind.css"
```

------------------------------------------------
3.  why the used way like 1. generate  duplicated  codes, but the way 2. will not. i found the code in `tailwindcss/tailwind.css` is same with my base.css.

Can you  solve this puzzle for me?

**Comment by superchangme** [comment]
when i use way 2 ,anothor problem occured,  chrome console print
```
[ Failed to load resource: the server responded with a status of 404 (Not Found)](main.aa7de47b.css:1          GET xxxx/tailwindcss/base net::ERR_ABORTED 404 (Not Found))
```
can't find css

**Comment by adamwathan** [comment]
Hey! Please create a reproduction we can clone and play with, no way for us to help without that I'm afraid.

**Comment by superchangme** [comment]
i'm sorry, i make a simple vite template with tailwindcss can't recurrence this problem. i guess some my ui framework make  this problem. i choose to close this issue temporarily...
