### ISSUE TITLE
Combining `darkMode: 'class'` and `important` configs doesn't work as expected

### ISSUE THREAD

**Issue by shengslogar** [tailwindlabs/tailwindcss#9968]
**What version of Tailwind CSS are you using?**

v3.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**

N/A (Laravel Mix)

**What version of Node.js are you using?**

N/A (v19.1.0)

**What browser are you using?**

N/A (Chrome)

**What operating system are you using?**

N/A (macOS Monterey)

**Reproduction URL**

https://play.tailwindcss.com/qtdsow5nGH?file=config

**Describe your issue**

Given the following Tailwind config:

```
module.exports = {
  darkMode: 'class',
  important: '#app',
};
```

And the following HTML:
```
<div id="app">
  <div class="w-10 h-10 bg-red-500 dark:bg-blue-500"></div>
</div>
```

The following CSS is generated:

```
#app .dark .dark\:bg-blue-500 {
  --tw-bg-opacity: 1;
  background-color: rgb(59 130 246 / var(--tw-bg-opacity))
}
```

I would expect either `#app.dark` or `.dark #app` to be outputted instead. [Docs](https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually) suggest only the HTML tag is ever intended to have the `.dark` class applied, so `.dark #app` is likely the correct output here.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is currently expected behaviour, Adam wrote a bit more about it here: https://github.com/tailwindlabs/tailwindcss/issues/3842#issuecomment-810362604

**Comment by shengslogar** [comment]
@RobinMalfait Thanks for the update!

**Comment by shengslogar** [comment]
Would a PR to note this in the docs be valuable?
