### ISSUE TITLE
arbitrary variants with modifiers inside the selector are generated in the wrong order

### ISSUE THREAD

**Issue by Torsten85** [tailwindlabs/tailwindcss#9977]
**What version of Tailwind CSS are you using?**

v3.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**

playground

**Reproduction URL**
https://play.tailwindcss.com/RWATzeVv1a

**Describe your issue**

This arbitrary variant `[&::-webkit-scrollbar-thumb:hover]:bg-green-500` is generated in the wrong order as  `&:hover::-webkit-scrollbar-thumb` but should be `&::-webkit-scrollbar-thumb:hover`.

When replacing the `::` with just one `:`, the generated order is correct (but the result obviously does not work anymore)

**Comment by thecrypticace** [comment]
Hey, I've merged in a fix for this which will be available in our next release. If you want to test it before then you can use our insiders build which should be published in the next few minutes: `npm install tailwindcss@insiders`
