### ISSUE TITLE
Appearance dynamically set to textfield produces wrong css classname

### ISSUE THREAD

**Issue by Jimmy89** [tailwindlabs/tailwindcss#9978]
**What version of Tailwind CSS are you using?**

3.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**

Play.tailwindcss.com

**What version of Node.js are you using?**

play.tailwindcss.com

**What browser are you using?**
Firefox

**What operating system are you using?**

Windows

**Reproduction URL**
https://play.tailwindcss.com/ARH58ZZiSU

**Describe your issue**
For a custom number input I want to hide the up/down icons that come with the type='number' input field. Based on some experimentation, I want to set appearance to "textfield" ("none" does not do the trick). So I ended up with trying to find all ways of dynamically inserting the value without extending my tailwind config file.

I tried all kind of ways, but the output syntax class of tailwind is simply said very wrong. You can see this easily with the production URL.

**Comment by adamwathan** [comment]
Hey! This example generates the CSS you are trying to generate:

https://play.tailwindcss.com/du3lnZesyU

<img width="755" alt="image" src="https://user-images.githubusercontent.com/4323180/205046328-2fbcc669-601d-4509-8806-0a1d826e5268.png">

The class name is `[appearance:textfield]` as per the documentation:

https://tailwindcss.com/docs/adding-custom-styles#arbitrary-properties

This hides the up/down arrows in Firefox but not in other browsers. For other browsers you need to target the `::-webkit-outer-spin-button` and `::-webkit-inner-spin-button` pseudo-elements:

https://play.tailwindcss.com/xvYmYDqqeG

Hope that helps!
